### ISSUE TITLE
plugin proxy-rewrite has some problems

### ISSUE THREAD

**Issue by NetRainn** [apache/apisix-dashboard#1003]
### key and value is “test”
![image](https://user-images.githubusercontent.com/35440615/101730379-de3e7b00-3af4-11eb-9cbb-a055e95f9774.png)

### but
I'll get it through Linux
![image](https://user-images.githubusercontent.com/35440615/101730514-1e9df900-3af5-11eb-9461-0f98a5f94ee0.png)

### I can't find this header in Java
![image](https://user-images.githubusercontent.com/35440615/101730600-4b521080-3af5-11eb-81c9-2fa75a86be24.png)

**Comment by NetRainn** [comment]
There is no problem with command generation
maybe The format is wrong（dashboard）

**Comment by juzhiyuan** [comment]
Hi, please use the latest codes for we just removed the plugin form, using code mirror currently.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/101757619-523b4c00-3b12-11eb-9c33-e7ee696e0b99.png)
