### ISSUE TITLE
add spell CI tool

### ISSUE THREAD

**Issue by moonming** [apache/apisix-dashboard#1013]
# Feature request
just like https://github.com/apache/apisix/pull/3011

## Please describe your feature

A clear and concise description of what you want and what your use case is.

**Comment by starsz** [comment]
That's good. Assign to me.

**Comment by starsz** [comment]
Hi @juzhiyuan, please have a look, when you are free.
![image](https://user-images.githubusercontent.com/25628854/102901471-a4805380-44a8-11eb-991d-e4cda0c9e544.png)

**Comment by juzhiyuan** [comment]
Hi @guoqqqi, here has one misspelling in the `DebugDrawView` file, please fix this.

As for misspellings in yarn.lock, ignore it because we couldn't modify it.

**Comment by juzhiyuan** [comment]
Hi @starsz, would we invoke a CI to check every PR?

**Comment by starsz** [comment]
@juzhiyuan Yes, I will. I want to know which directories should be checked under "web".

**Comment by juzhiyuan** [comment]
1. `/web/src`
2. `/web/cypress`
