### ISSUE TITLE
CI: failed to run the CI after merge PR#868

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1016]
here is the task of CI:

https://github.com/apache/apisix-dashboard/runs/1535613056

**Comment by membphis** [comment]
@starsz do you have time to look at this issue?

![image](https://user-images.githubusercontent.com/6814606/101873580-27a8cc00-3bc2-11eb-8186-0ac7c5befb24.png)

**Comment by membphis** [comment]
if it is not easy to resolve, then we need to revert this commit first

**Comment by starsz** [comment]
OK, I found the problem. Let me fix it.
