### ISSUE TITLE
style: code optimization for `api/filters/schema.go`

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1023]
refer to:

https://github.com/apache/apisix-dashboard/pull/986#discussion_r540804001
https://github.com/apache/apisix-dashboard/pull/986#discussion_r540806059
https://github.com/apache/apisix-dashboard/pull/986#discussion_r540806679

**Comment by juzhiyuan** [comment]
close?

**Comment by membphis** [comment]
This is the to do things we need
