### ISSUE TITLE
bug: create consumer or route and enable any plugin, will be an error

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1028]
# Bug report

## Describe the bug

create consumer or route and enable any plugin via **enable button not setting button**, will be an error
except prometheus plugin.

## How to Reproduce
![image](https://user-images.githubusercontent.com/7396835/101968622-119b1a00-3c5b-11eb-80e6-e6b9784a110f.png)

**Comment by juzhiyuan** [comment]
What's the enable button and setting button? could you please take a snapshot?

**Comment by juzhiyuan** [comment]
This Error will popup when the plugin data is not compatible with that plugin's schema.

**Comment by idbeta** [comment]
> What's the enable button and setting button? could you please take a snapshot?

![image](https://user-images.githubusercontent.com/7396835/101969563-df3feb80-3c5f-11eb-8a93-c598b529f05d.png)

**Comment by juzhiyuan** [comment]
**Schema from http://139.217.190.60/routes/328942401265598931/edit**

![image](https://user-images.githubusercontent.com/2106987/101969712-e6b3c480-3c60-11eb-83e0-1d9a1053b27a.png)

**Schema from 40.73.92.163:8080**

![image](https://user-images.githubusercontent.com/2106987/101969726-f4694a00-3c60-11eb-869e-4be19fc6b899.png)

Should check backend first
