### ISSUE TITLE
Collect E2E code coverage

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1033]
There are many test cases for Manager-API, and code coverage cannot be obtained at present.
For E2E testing, we need to collect code coverage, which is very important for subsequent development.

**Comment by membphis** [comment]
welcome to discuss at this issue  @ShiningRush do you have any suggestions?

**Comment by membphis** [comment]
@gxthrj said: https://tech.youzan.com/you-zan-go-xiang-mu-dan-ce-ji-cheng-zeng-liang-fu-gai-lu-tong-ji-yu-fen-xi

**Comment by ShiningRush** [comment]
> @gxthrj said: https://tech.youzan.com/you-zan-go-xiang-mu-dan-ce-ji-cheng-zeng-liang-fu-gai-lu-tong-ji-yu-fen-xi

I have already read it and check our team code before, Now I am sure that our team is also use the same way.

**Comment by juzhiyuan** [comment]
done?

**Comment by ShiningRush** [comment]
I will do it this week

**Comment by membphis** [comment]
any news? @ShiningRush
