### ISSUE TITLE
Client-side URL redirect

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1038]
# Bug report

## Describe the bug

https://github.com/apache/apisix-dashboard/security/code-scanning/3?query=ref%3Arefs%2Fheads%2Fmaster

![image](https://user-images.githubusercontent.com/2106987/101979572-0ebf1a00-3c99-11eb-841f-d739b0e00752.png)

Redirecting to a URL that is constructed from parts of the DOM that may be controlled by an attacker can facilitate phishing attacks. In these attacks, unsuspecting users can be redirected to a malicious site that looks very similar to the real site they intend to visit, but which is controlled by the attacker.

**Comment by juzhiyuan** [comment]
We may limit the target redirect URL to have the same host as the current URL.

**Comment by ThanoshanMV** [comment]
Hi @juzhiyuan, I would like to work on this issue. Can you please guide me here?

**Comment by juzhiyuan** [comment]
@ThanoshanMV sure! please give me some time to prepare this issue.

BTW, here[1] is our Slack channel, welcome to join in :)

[1] http://s.apache.org/slack-invite

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/104311758-a3bf6800-5510-11eb-8291-45765ac335d3.png)


Hi @ThanoshanMV, here is the explanation from GitHub, we should limit the `redirect` URL, it MUST do the redirect action with the current host.

**Comment by ThanoshanMV** [comment]
Am I okay here: `decodeURIComponent(redirect)`'s host should be the current host. If it is, then we'll perform the redirect action and if it doesn't, we don't perform any redirect action.

**Comment by juzhiyuan** [comment]
@ThanoshanMV yep :)
