### ISSUE TITLE
Support Error highlighting for plugin's code mirror

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1040]
# Feature request

## Please describe your feature

Currently, when we use plugin's CodeMirror, one error message will pop up when we input an invalid JSON data, it would be more clear to have the Error Line highlighting support for CodeMirror.

Related issue: https://github.com/apache/apisix-dashboard/issues/815

**Comment by nic-chen** [comment]
not urgent

**Comment by qian0817** [comment]
@juzhiyuan Can I use the [monaco editor](https://microsoft.github.io/monaco-editor/) instead of codemirror to achieve this?

**Comment by juzhiyuan** [comment]
Sure! that's what I want to do!

**Comment by juzhiyuan** [comment]
But you may face some issues from E2E test, you could ask for @guoqqqi @LiteSun to help you.

**Comment by LiteSun** [comment]
Good to go.
