### ISSUE TITLE
failed to load the route in etcd

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1041]
here are the routes in my `etcd`, I created them by a python script:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import grequests

payloads = {}
for id in range(100):
    payload = {
                "uri": "/test_%s"%id,
                "upstream": {
                    "type": "roundrobin",
                    "nodes": {
                        "127.0.0.1:7000": 1
                    }
                }
    }
    payloads[id]=payload
unsent_request = []
header = {"X-API-KEY":"edd1c9f034335f136f87ad84b625c8f1"}
for id in payloads:
    print(id)
    unsent_request.append(grequests.post("http://127.0.0.1:9080/apisix/admin/routes/" ,json=payloads[id], headers = header))
    responses = grequests.map(unsent_request)
for response in responses:
    print(response.content)
    response.close()
```

the Manager API can not load them, here are the routes in etcd:

[routes.log](https://github.com/apache/apisix-dashboard/files/5684342/mm.log)

**Comment by membphis** [comment]
@nic-chen do you have time to look at this issue?

**Comment by membphis** [comment]
cc @idbeta

**Comment by nic-chen** [comment]
@membphis 

the Manager API has loaded them, but the ID is null for each routes.


I guess you can't see them on the FE UI?

**Comment by juzhiyuan** [comment]
> @membphis 
> 
> the Manager API has loaded them, but the ID is null for each routes.
> 
> 
> I guess you can't see them on the FE UI?
> 
> 

Just for sure, does API return those records?

**Comment by nic-chen** [comment]
> > @membphis
> > the Manager API has loaded them, but the ID is null for each routes.
> > I guess you can't see them on the FE UI?
> 
> Just for sure, does API return those records?

No, It depends. My guess is wrong.

**Comment by membphis** [comment]
I think that is a bug of Manager API.

```
http://ubuntu:9000/apisix/admin/routes?page=1&page_size=20

{
	"code": 0,
	"message": "",
	"data": {
		"rows": [{
			"id": null,
			"create_time": 1607505576,
			"update_time": 1607505576,
			"uri": "/test_95",
			"upstream": {
				"nodes": [{
					"host": "127.0.0.1",
					"port": 7000,
					"weight": 1
				}],
				"type": "roundrobin",
				"hash_on": "vars",
				"pass_host": "pass"
			}
		}],
		"total_size": 1
	},
	"request_id": "b082cb4a-e8f2-4c41-b2aa-fc3e28a62a72"
}

**Comment by juzhiyuan** [comment]
fix in M2.3?

**Comment by membphis** [comment]
> fix in M2.3?

this is ok
