### ISSUE TITLE
chore: show a friendly prompt when the project is successfully built

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1045]
![image](https://user-images.githubusercontent.com/6814606/102055038-35aa5700-3e25-11eb-94fb-8c5593a03f98.png)

```
$ make build
... ...

The build is successful and the file is saved in the `output` directory.
```

**Comment by juzhiyuan** [comment]
Yep, and this message is from [Webpack](https://webpack.js.org/)
