### ISSUE TITLE
figure out what happened to gitleaks

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1059]
# Bug report

## Describe the bug

https://github.com/apache/apisix-dashboard/runs/1564493861

**Comment by Yiyiyimu** [comment]
Hi @juzhiyuan do we need to delete this action, or use submodule to make it running

**Comment by juzhiyuan** [comment]
ok, we could remove it, we have Security alert from GitHub.

**Comment by juzhiyuan** [comment]
Just checked, we'd better keep it working 🤔 I don't want to see keys uploaded by mistake 😂

**Comment by stevending1st** [comment]
> The logs for this run have expired and are no longer available.

The log is only saved for 3 months, so we can’t see the log now.Please save the log in time next time.

Can we reproduce it again?

**Comment by juzhiyuan** [comment]
> > The logs for this run have expired and are no longer available.
> 
> The log is only saved for 3 months, so we can’t see the log now.Please save the log in time next time.
> 
> Can we reproduce it again?

https://github.com/apache/apisix-dashboard/issues/1817

See here
