### ISSUE TITLE
discuss: Support empty nodes in Upstream

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1065]
Manager API should keep same as Admin API, we need to track the discussion in APISIX, and sync if any thing changes.  

related issue:
https://github.com/apache/apisix/issues/3072

**Comment by juzhiyuan** [comment]
done?

**Comment by membphis** [comment]
ping @nic-chen

**Comment by liuxiran** [comment]
May I ask whether Fe also need to support empty nodes in upstream? The current policy is that use have to fill in at least one node

**Comment by nic-chen** [comment]
I think FE don't need this feature now, it's for ingress controller, manually add upstream should not allow empty nodes.
