### ISSUE TITLE
feat: show front-end e2e test report on PR's comment.

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1075]
# Feature request

in order to let developers have clear info about why the front-end e2e test failed, we need show the front-end e2e report  in each pr's comment, just like Codecov Report.

refer pr: #991

**Comment by LiteSun** [comment]
I tried it under my fork branch and it worked as shown here.

![image](https://user-images.githubusercontent.com/31329157/104309152-aa4be080-550c-11eb-941e-044da0aac25f.png)

waiting for admin to install Cypress Github app. https://issues.apache.org/jira/projects/APISIX/issues/APISIX-19?filter=allopenissues

**Comment by juzhiyuan** [comment]
This issue is relying on Cypress's Write permission, which needs infra's reply.
