### ISSUE TITLE
OnlineDebug throws error when sending request

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1077]
# Bug report

## Describe the bug

![图片](https://user-images.githubusercontent.com/2106987/102687112-ac7d9080-4227-11eb-83cd-3580ab9c8160.png)

## How to Reproduce

0. Visit http://139.217.190.60/routes/list
1. Go to Route list;
2. Click on Online Debug;
3. Input path "/hello";
4. Click Send Request then error shown;

**Comment by juzhiyuan** [comment]
Please take a look when you have time :)

cc @liuxiran

**Comment by juzhiyuan** [comment]
![图片](https://user-images.githubusercontent.com/2106987/102687314-1c404b00-4229-11eb-8f7f-7140b9fa7d4b.png)

**Comment by liuxiran** [comment]
need to fill in the full URL of the request in the url input, e.g: http://ip:port/hello @juzhiyuan 

Perhaps a simple FAQ can help users quickly know how to use this feature, let me add it later. ^_^

**Comment by juzhiyuan** [comment]
oh I know what happened, the error says the protocol for that URL is missing 😂

**Comment by liuxiran** [comment]
> oh I know what happened, the error says the protocol for that URL is missing 😂

yes you are right~! perhaps I need to do another enhancement 

-  a clearer information about the error is needed here
-  fe add a input validation to reject not validate url

**Comment by imjoey** [comment]
Hi @juzhiyuan @liuxiran , since #1091 and #1092 had been merged, so shall we close this issue?

**Comment by liuxiran** [comment]
> Hi @juzhiyuan @liuxiran , since #1091 and #1092 had been merged, so shall we close this issue?

Thanks for your reminder @imjoey ,  another pr for update the debug api error msg is on the way, I will finish it ASAP

**Comment by liuxiran** [comment]
As all prs has been merged, close this issue, feel free to reopen it when you need, thanks
