### ISSUE TITLE
Store the `script.ID` in the router entity?

### ISSUE THREAD

**Issue by spacewander** [apache/apisix-dashboard#1085]
It seems currently there is not reference between `/apisix/route` and the `/apisix/script`?

**Comment by tokers** [comment]
That's really, we may add the reference relations just like route and upstream.

**Comment by nic-chen** [comment]
sure, we should store it.

**Comment by membphis** [comment]
yes, we need this feature ^_^

APISIX needs to be updated for this feature, all right? @spacewander

**Comment by spacewander** [comment]
Yes.

**Comment by juzhiyuan** [comment]
any update?

**Comment by spacewander** [comment]
APISIX already updated for this feature

**Comment by juzhiyuan** [comment]
ok, waiting manager-api's update.

**Comment by membphis** [comment]
ping @nic-chen

**Comment by juzhiyuan** [comment]
done??

**Comment by imjoey** [comment]
> done??

@juzhiyuan I will work on this if no one has taken.

**Comment by juzhiyuan** [comment]
All right, thanks!

**Comment by imjoey** [comment]
> APISIX already updated for this feature

@spacewander  AFAIK, APISIX seems not going to deal with loading script by `script_id` from etcd, which acts not the same as `upstream_id`. So just to confirm with you that in manager-api, we must fulfill the `script` property if the input only contains the `script_id`. Please let me know if I'm wrong. Thanks.

**Comment by spacewander** [comment]
The `script_id` is planned to used for debug and optimization(cache). Currently we can assume the script_id is the route's id.

**Comment by imjoey** [comment]
> The `script_id` is planned to used for debug and optimization(cache). Currently we can assume the script_id is the route's id.

@spacewander thanks for getting back. So could we have the following assumptions for now:

- Currently users could not manipulate the `script` via manager-api, which means there are no explicite CURDL APIs for `script` object.
- If the `script_id` in request does not equal to the `id` of the affiliated `route`, we can directly send back the `Bad Request` response.

Thanks.

**Comment by spacewander** [comment]
I think just filling the script_id field with the route id when the script is saved is enough.

**Comment by imjoey** [comment]
> I think just filling the script_id field with the route id when the script is saved is enough.

@spacewander Wow, that's great. Many thanks for clear directions.

**Comment by imjoey** [comment]
@spacewander @tokers @juzhiyuan 

For now, APISIX and manager-api have both supported `script_id` in Route entity. Cause `The script_id is planned to used for debug and optimization(cache). Currently we can assume the script_id is the route's id.`, IMHO there is no need to do anything else in manager FE, so could we close this issue?

**Comment by juzhiyuan** [comment]
agree with u.
