### ISSUE TITLE
support EWMA in upstream balancer

### ISSUE THREAD

**Issue by moonming** [apache/apisix-dashboard#1086]
# Feature request

https://github.com/apache/apisix/blob/4d316bc0681c80435ab1a3fc113c3c6ea3c82831/apisix/balancer.lua#L33

## Please describe your feature

A clear and concise description of what you want and what your use case is.

**Comment by juzhiyuan** [comment]
Doc: https://github.com/apache/apisix/blob/master/doc/admin-api.md#upstream

May I know what should happen after selecting EWMA?

cc @membphis

**Comment by membphis** [comment]
> May I know what should happen after selecting EWMA? @juzhiyuan 

same as `roundrobin`

**Comment by juzhiyuan** [comment]
cc @guoqqqi
