### ISSUE TITLE
路由修改无法提交

### ISSUE THREAD

**Issue by candicandi** [apache/apisix-dashboard#1095]
# Bug report

## How to Reproduce

正常情况下添加路由，重定向设置为禁用，提交后再编辑这个路由，把重定向选择为强制https，其他不变，会无法提交

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

**Comment by juzhiyuan** [comment]
@idbeta please take a look.

**Comment by idbeta** [comment]
My environment has not reproduced. I remember that we modified this question some time ago #692

**Comment by juzhiyuan** [comment]
fine, please use the latest codes based on the master branch. @candicandi 

thanks! @idbeta
