### ISSUE TITLE
The menu bar `consumer ` in Chinese view supports Chinese

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#1098]
# Feature request

![image](https://user-images.githubusercontent.com/12752710/102889924-785bd700-4496-11eb-9164-fe02c3e9271c.png)
![image](https://user-images.githubusercontent.com/12752710/102889956-890c4d00-4496-11eb-8220-cb11311fc1a3.png)

**Comment by juzhiyuan** [comment]
oh yes, that's because we don't have a proper description in Chinese, what's your opinion? 🤔

**Comment by liuxiran** [comment]
We translated `consumer` to `应用` In the course of our use, for most of the consumers of the apis are applications.

**Comment by juzhiyuan** [comment]
1. `消费者`;
2. `应用`;
3. xxx

**Comment by Caelebs** [comment]
As far as the current functions are concerned, `用户` +1

**Comment by juzhiyuan** [comment]
I would prefer using `用户`, let's wait for others replies 💯 

cc @membphis @ShiningRush

**Comment by membphis** [comment]
my vote: '用户' +1

**Comment by imjoey** [comment]
Sorry for this late response. `应用` +1 for me. 

My reasons are as follows:

- `Consumer` actually represents a program, which will take with an auth key for emitting client calls to the `Route`. The word `用户` probably indicate that it's a **person**.
- The word `用户` may be confusing once we add support for multi-tenant (`RBAC` in other words).

In Aliyun API Gateway, a user can login in and access the web console, and he/she may owns many Apps (`应用`) for different APIs(`Routes`) with authorization. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/2542401/103333469-02b0c600-4aa9-11eb-9a2b-979f93324459.png)

Looking forward to your insights. Thanks.

**Comment by juzhiyuan** [comment]
Let's wait for another 72 hours to have a final conclusion :)

**Comment by imjoey** [comment]
> Let's wait for another 72 hours to have a final conclusion :)

@juzhiyuan  Many thanks for your kindness.

**Comment by juzhiyuan** [comment]
After consideration according to the above comments, let's use `应用` for `Consumer`.

**Comment by juzhiyuan** [comment]
Hi all, how about calling `Consumer` as `消费者`? `应用` is more like an application.

**Comment by imjoey** [comment]
> Hi all, how about calling `Consumer` as `消费者`? `应用` is more like an application.

@juzhiyuan it's OK for me. If we still using `consumer` in English version, `消费者` is a more proper translation.
