### ISSUE TITLE
 Select only wolf-rabc in the plugin list when creating consumer，Unable to continue

### ISSUE THREAD

**Issue by Hcreak** [apache/apisix-dashboard#1103]
# Bug report

## Describe the bug

I follow the steps of the official document([https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/wolf-rbac.md])(https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/wolf-rbac.md) to deploy wolf-rbac plugin,
When I creating consumer in the dashboard, the page prompts: `请启用一种身份认证类插件`

If I continue to use the dashboard, I cannot  to continue.

## How to Reproduce

1. Go to 'Create Consumer'
2. Click on 'Enable wolf-rbac plugin'
3. Click on 'Next Step'

## Expected behavior

Create Consumer with wolf-rbac plugin

## Screenshots

![error](https://user-images.githubusercontent.com/15710701/102957751-3a05fc80-4516-11eb-8723-b5b2dc5832fe.png)

## System information

- OS: [e.g. macOS, Windows]  Centos7
- Browser (if applies) [e.g. Chrome, Safari, Edge] Chrome
- Version: [e.g. 2.0-rc3] `apisix-dashboard:2.2` ,build for latest Dockerfile

**Comment by juzhiyuan** [comment]
Hi, please use the latest codes on the master branch.

**Comment by juzhiyuan** [comment]
BTW, yes, we must enable a Plugin under the Authentication category when creating consumer.

**Comment by Hcreak** [comment]
Thanks for your reply, Do you mean that the next version will put wolf-rbac into the Authentication category to fix this bug?

**Comment by juzhiyuan** [comment]
The next version(2.3) will be released in the middle of the next month :)

**Comment by juzhiyuan** [comment]
currently, you could fix this by following steps:
1. update this value to `Authentication` here[1];
2. rebuild the web :)

[1] https://github.com/apache/apisix-dashboard/blob/master/web/src/components/Plugin/data.tsx#L110

**Comment by juzhiyuan** [comment]
related to #532

**Comment by Hcreak** [comment]
Thanks
