### ISSUE TITLE
request help: frontend E2E test (change upstream type to chash) need a better the search method

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1113]
# Feature request

## Please describe your feature

now the method of `change upstream type to cash and input hash_on and key` which in frontend E2E test is:
```
cy.get('[title=roundrobin]').click();
cy.wait(sleepTime);
cy.get('.ant-select-item:nth-child(2)').click();
cy.get('#hash_on').click();
cy.wait(sleepTime);
cy.get('.ant-select-item-option-active:nth-child(1) > .ant-select-item-option-content').click();
cy.get('#key').click();
cy.wait(sleepTime);
cy.get('div:nth-child(8) .ant-select-item:nth-child(1) > .ant-select-item-option-content:nth-child(1)').click();
```
These steps seem too complicated, I hope there are simpler steps to achieve it. 

https://github.com/apache/apisix-dashboard/blob/master/web/cypress/integration/upstream/create_and_delete_upstream.spec.js#L73-L84

**Comment by membphis** [comment]
@idbeta please provide a link about your example, it is easier to view

**Comment by membphis** [comment]
@LiteSun Need your help ^_^

**Comment by idbeta** [comment]
> @idbeta please provide a link about your example, it is easier to view

ok, I have added the link.

**Comment by moonming** [comment]
ping @LiteSun
