### ISSUE TITLE
bug: host pass error with dashboard 2.0

### ISSUE THREAD

**Issue by gy09535** [apache/apisix-dashboard#1115]
### Issue description
When we set upstream in dashboard ,the value of "upstream.pass_host"  not  be set, after that we set the nodes with domain, the domain value should be set to the backend node, but it not be set. because of the pass_host default value is pass( ref: https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L360 ), it can not execute the node host set logical(ref: https://github.com/apache/apisix/blob/master/apisix/init.lua#L306-L327 and https://github.com/apache/apisix/blob/master/apisix/init.lua#L467-L473). I have fixed it change the upstream default value to node, I think it is not a good idea, we should add the config in dashboard ui 2.0.

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by nic-chen** [comment]
Do you mean dashboard need to support config `pass_host`?

**Comment by gy09535** [comment]
> Do you mean dashboard need to support config `pass_host`?

yeah, If we not do that, the upstream host should not be set.

**Comment by juzhiyuan** [comment]
already supported yesterday, please check.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/103062073-288d2500-45e8-11eb-9ca8-5a21815e7299.png)

https://github.com/apache/apisix-dashboard/pull/1088
