### ISSUE TITLE
schema- sync.sh generate schema.json Is empty

### ISSUE THREAD

**Issue by qwxingzhe** [apache/apisix-dashboard#1120]
# Bug report

## Describe the bug

I want to make apisix plug-ins, but I met the problem I asked yesterday  #1117. I changed the plug-in configuration in apisix config, and the plug-in list in the dashboard was not updated. So I installed the two projects in source code, using api/build-tools/schema-sync.sh to update schema.json The result is generated schema.json It's empty. Do I need to install related Lua dependencies or have version requirements?

我想制作apisix插件，不过遇到了昨天提的问题 #1117，更改apisix的config中的插件配置dashboard中插件列表未更新，于是用源码方式安装了这两个项目，使用api/build-tools/schema-sync.sh去更新schema.json，结果生成出来的schema.json是空的。是否需要安装相关lua依赖、或者有版本要求?

## How to Reproduce

1. Go to '{apisix-dashboard path}'
2. run 'api/build-tools/schema-sync.sh /usr/local/apisix'
3. See error

## Expected behavior

schema.json Is empty

## Screenshots

![image](https://user-images.githubusercontent.com/7071651/103128579-dd9b0c80-46d0-11eb-87fe-2847186bd30f.png)

## System information
![image](https://user-images.githubusercontent.com/7071651/103128594-e5f34780-46d0-11eb-8f6d-ce8f5e5b76a0.png)
![image](https://user-images.githubusercontent.com/7071651/103128601-e8ee3800-46d0-11eb-8f43-b06437c99a96.png)

**Comment by nic-chen** [comment]
@qwxingzhe 
what versions are your APISIX and Dashboard?

**Comment by qwxingzhe** [comment]
> @qwxingzhe
> what versions are your APISIX and Dashboard?

v2.2

I installed it according to this document
https://github.com/apache/apisix-dashboard/blob/master/docs/deploy.md

![image](https://user-images.githubusercontent.com/7071651/103130835-49817300-46d9-11eb-8afd-47a4cdbb8f5e.png)

**Comment by starsz** [comment]
Hi @qwxingzhe, Because the `schema-sync.lua` doesn't preload the package `ngx.errlog` on v2.2.
Maybe you can try the `schema-sync.lua` on master branch.

See more details: 
https://github.com/apache/apisix-dashboard/blob/78b4031d6899be672fcb41b29fcb40f9f898509b/api/build-tools/schema-sync.lua#L26

**Comment by nic-chen** [comment]
@qwxingzhe 
APISIX 2.1 doesn't have plugin `error-log-logger.lua`, you can download it on:
https://github.com/apache/apisix/releases/tag/2.1

if you are using code from APISIX master branch, please use Dashboard's master branch together.

**Comment by qwxingzhe** [comment]
> @qwxingzhe
> APISIX 2.1 doesn't have plugin `error-log-logger.lua`, you can download it on:
> https://github.com/apache/apisix/releases/tag/2.1
> 
> if you are using code from APISIX master branch, please use Dashboard's master branch together.

I build it again through the master, but it's stuck in this link
![image](https://user-images.githubusercontent.com/7071651/103136042-ece18080-46f7-11eb-9b95-683a704ccc53.png)

**Comment by juzhiyuan** [comment]
cc @LiteSun

**Comment by qwxingzhe** [comment]
It took me more than 30 minutes to rebuild,tks.
