### ISSUE TITLE
bug: manager-api doesn't support PATCH method

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1127]
# Bug report

## Describe the bug

manager-api do not support PATCH method:
when using the following three types of bodies to update node of `service`, will be error
1.
```
{
	"upstream": {
		"nodes": [{
			"host": "172.16.238.20",
			"port": 1981,
			"weight": 1
		}]
	}
}
```
2.
```
{
    "upstream": {
        "nodes": {
            "39.97.63.216:80": 1
        }
    }
}
```
return error:
```
"{\"code\":10000,\"message\":\"not a valid map: *entity.Service\",\"data\":null,\"request_id\":\"xxxxx\"}"
```

3.
```
PATCH http://127.0.0.1:9000/apisix/admin/services/your-service-id/upstream/nodes
... ...
"404 page not found\n"
```

and
`ExpectCode` of the test framework does not work

## Expected behavior

The `upstream nodes` of the service can be updated correctly.

**Comment by starsz** [comment]
Please assigned it to me.

**Comment by nic-chen** [comment]
@starsz 
Patch methods for service, upstream, consumer have bug, you could refer to Patch method for SSL or route.

**Comment by starsz** [comment]
@nic-chen, I had checked the apisix. And only `global_rule`, `routes`, `services`, `ssl`, `upstream`.

Do `consumer` need the `Patch` method?

**Comment by nic-chen** [comment]
> @nic-chen, I had checked the apisix. And only `global_rule`, `routes`, `services`, `ssl`, `upstream`.
> 
> 
> 
> Do `consumer` need the `Patch` method?

sure

**Comment by juzhiyuan** [comment]
not urgent, the frontend doesn't need this method.

**Comment by starsz** [comment]
Not urgent, I think this should be done in M2.5.

**Comment by starsz** [comment]
@juzhiyuan Help me move to M2.5.

**Comment by starsz** [comment]
I had checked the apisix and apisix-dashboard.

apisix's PATCH method:
* service
* plugin_config
* global_rules
* ssl
* routes
* upstream

apisix-dashboard's PATCH method:
* service
* plugin_config
* global_rules
* ssl
* routes
* upstream

So they are the same.I think this issue can be closed now.
