### ISSUE TITLE
通过dockerfile无法创建镜像

### ISSUE THREAD

**Issue by zd1990** [apache/apisix-dashboard#1133]
# Bug report

## Describe the bug

通过docker部署的文档无法创建镜像，编译镜像报错

## How to Reproduce

`
git clone https://github.com/apache/apisix-dashboard.git  
`
`
cd apisix-dashboard  
`
`
docker build -t apisix-dashboard:v1 . --build-arg ENABLE_PROXY=true
`

## Expected behavior

编译镜像成功

## Screenshots

![image](https://user-images.githubusercontent.com/11418143/103188415-54b7e700-4903-11eb-9ca2-646bdd59d6a8.png)

## System information

- OS: [e.g. macOS]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

## Additional context

`wget https://github.com/apache/apisix-dashboard/archive/v2.0.tar.gz`
下载dockerfile里面的包解压后，发现里面并没有dockerfile里面写的/usr/local/apisix-dashboard/api/cmd/manager目录

**Comment by LY-GO** [comment]
i also meet same question

**Comment by juzhiyuan** [comment]
Hello, @LY-GO @zd1990 I see you are using 2.0-rc3, but clone from the master branch, I'm curious that the master branch is going to release v2.0, not 2.0-rc3.

@idbeta  Please help to verify if this issue occurred in the master branch.

**Comment by nic-chen** [comment]
@LY-GO @zd1990 

If you want to use `https://github.com/apache/apisix-dashboard/archive/v2.0.tar.gz`, you should read docs in branch v2.0, not master.

And I recommend to use v2.2.

**Comment by imjoey** [comment]
Hi @zd1990 , previously there's bug that the `Dockerfile` in master branch is trying to fetch `v2.2` source code. It has been fixed via https://github.com/apache/apisix-dashboard/pull/1146 , you could rerun the commands with the latest code from master branch. That already works for me now. Thanks.

**Comment by juzhiyuan** [comment]
great, let's close this first, feel free to reopen if needed.
