### ISSUE TITLE
 The Plan of dashboard shows the gateway’s Plugin interceptors

### ISSUE THREAD

**Issue by Hcreak** [apache/apisix-dashboard#1134]
# Feature request

https://github.com/apache/apisix/blob/master/doc/zh-cn/plugin-interceptors.md

I need  use `interceptors` functions to protect some plugin interfaces, 
Do you have any plans to display it on the dashboard? Thanks.

A clear and concise description of what you want and what your use case is.

**Comment by juzhiyuan** [comment]
Hi, would you have any proposal for this feature?

**Comment by juzhiyuan** [comment]
You would lead this feature and we will help u if needed.

**Comment by Hcreak** [comment]
I want to know if you have any plans for this, and if you put it in Milestones， Thanks.

**Comment by Hcreak** [comment]
If there is it will be the best

**Comment by juzhiyuan** [comment]
No, we don't have a plan for this feature now, welcome PR to resolve this.
