### ISSUE TITLE
config_etcd.lua:262: sync_data(): failed to check item data of [/apisix/routes] err:additional properties forbidden

### ISSUE THREAD

**Issue by pguokun** [apache/apisix-dashboard#1135]
**Issues Description:**

After installing apisix v2.1 and apisix-dashboard v2.2, after adding a new routing configuration through apisix-dashboard, the ```apisix/logs/error.log``` file shows that ```config_etcd.lua``` has been and often reports errors, and APISIX cannot update routing information
similar to the following：

```
2020/12/28 14:49:43 [error] 42#42: *110 [lua] config_etcd.lua:262: sync_data(): failed to check item data of [/apisix/routes] err:additional properties forbidden, found status ,val: {"id":"334881807369503455","update_time":1609136271,"uris":["\/*"],"methods":["GET","HEAD","POST","PUT","DELETE","OPTIONS","PATCH"],"priority":0,"hosts":["default-01.test.com"],"status":1,"plugins":{"redirect":{"http_to_https":true},"prometheus":{"disable":true}},"upstream":{"nodes":[{"port":7001,"weight":1,"host":"172.22.1.90"},{"port":7002,"weight":1,"host":"172.22.1.90"}],"upstream_host":"172.22.1.90","type":"roundrobin","hash_on":"vars","timeout":{"send":6000,"read":6000,"connect":6000},"pass_host":"rewrite"},"desc":"测试接口","vars":{},"create_time":1609134711,"name":"test-1"}, context: ngx.timer
```

**Environment:**
apisix version : v2.1
apisix-dashborad version : v2.2
etcd Version: 3.4.13
OS: CentOS Linux release 7.8.2003 (Core)

**Comment by pguokun** [comment]
> Apisix 2.1 doesn't have field `status`.
> CC @juzhiyuan

So this is the incompatibility between apisix v2.1 and apisix-dashboard v2.2?

**Comment by liuxiran** [comment]
hi @pguokun,I want to make sure that `apisix-dashboard v2.2` you mentioned in the issue is got from https://github.com/apache/apisix-dashboard/releases/tag/2.2

**Comment by liuxiran** [comment]
Hi @pguokun , I want to make sure that if the `apisix-dashboard v2.2` you mentioned in the issue was got from https://github.com/apache/apisix-dashboard/releases/tag/2.2 or https://github.com/apache/apisix-dashboard/tree/v2.2 instead of master branch of dashboard?

Route status is added after apisix-dashboard v2.2 released, I have checked that the branch V2.2 or the 2.2 release codes did have this feature.

So, If you want to experience our 2.2 released feature, maybe you have to change to our 2.2 released code or v2.2 branch
If you want to experience route status, you have to use [apisix-dashboard master branch](https://github.com/apache/apisix-dashboard) and [apisix master branch](https://github.com/apache/apisix)

Any feedbacks is much more appreciated, thanks ~

**Comment by pguokun** [comment]
> Hi @pguokun , I want to make sure that if the `apisix-dashboard v2.2` you mentioned in the issue was got from https://github.com/apache/apisix-dashboard/releases/tag/2.2 or https://github.com/apache/apisix-dashboard/tree/v2.2 instead of master branch of dashboard?
> 
> Route status is added after apisix-dashboard v2.2 released, I have checked that the branch V2.2 or the 2.2 release codes did have this feature.
> 
> So, If you want to experience our 2.2 released feature, maybe you have to change to our 2.2 released code or v2.2 branch
> If you want to experience route status, you have to use [apisix-dashboard master branch](https://github.com/apache/apisix-dashboard) and [apisix master branch](https://github.com/apache/apisix)
> 
> Any feedbacks is much more appreciated, thanks ~

I tried to reinstall apisix 2.1 and apisix-dashboard 2.2 in the master branch, but still reported the following error log:
···
2020/12/29 12:39:39 [error] 42#42: *79 [lua] config_etcd.lua:262: sync_data(): failed to check item data of [/apisix/routes] err:additional properties forbidden, found status ,val: {"id":"335013859259581286","status":1,"priority":0,"methods":["GET"],"vars":{},"hosts":["default-01.test.com"],"labels":{"env":"test"},"update_time":1609213420,"create_time":1609213420,"uris":["\/*"],"name":"test","upstream":{"pass_host":"rewrite","upstream_host":"172.22.1.90","type":"roundrobin","hash_on":"vars","timeout":{"read":6000,"connect":6000,"send":6000},"nodes":[{"port":7001,"weight":1,"host":"172.22.1.90"},{"port":7002,"weight":1,"host":"172.22.1.90"}]}}, context: ngx.timer
2020/12/29 12:43:30 [error] 40#40: *81 [lua] config_etcd.lua:509: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:additional properties forbidden, found status,  etcd key: /apisix/routes, context: ngx.timer
2020/12/29 12:43:30 [error] 46#46: *44 [lua] config_etcd.lua:509: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:additional properties forbidden, found status,  etcd key: /apisix/routes, context: ngx.timer
2020/12/29 12:43:30 [error] 43#43: *26 [lua] config_etcd.lua:509: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:additional properties forbidden, found status,  etcd key: /apisix/routes, context: ngx.timer
···

Get the code method:
apisix：git clone https://github.com/apache/apisix.git
apisix-dashboard：git clone https://github.com/apache/apisix-dashboard.git

**Comment by juzhiyuan** [comment]
cc @idbeta

**Comment by nic-chen** [comment]
@pguokun please confirm your APISIX is using master branch， and restart successfully

**Comment by pguokun** [comment]
> @pguokun please confirm your APISIX is using master branch， and restart successfully

I am sure, I am using version 2.1 of the master branch, and successfully restarted

![图片](https://user-images.githubusercontent.com/15042141/103265012-83a78900-49e7-11eb-9867-811ece2a696c.png)

**Comment by nic-chen** [comment]
> > @pguokun please confirm your APISIX is using master branch， and restart successfully
> 
> I am sure, I am using version 2.1 of the master branch, and successfully restarted
> 
> ![图片](https://user-images.githubusercontent.com/15042141/103265012-83a78900-49e7-11eb-9867-811ece2a696c.png)

APISIX 2.1 doesn't  support `status` on  route. It will be support next version. also you can use code in master branch.

here is the pr:
https://github.com/apache/apisix/pull/2943

**Comment by liuxiran** [comment]
Hi @pguokun , have your problem been solved? looking for your reply 😊

**Comment by membphis** [comment]
we can use the APISIX 2.2 version now. https://github.com/apache/apisix/releases/tag/2.2
