### ISSUE TITLE
Adding useful information to backend E2E test cases

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1136]
# Feature request

## Please describe your feature

- [x] Which test case is failed (would better support error highlighting);
- [x] Which file is this test case in?

cc @idbeta @nic-chen

**Comment by membphis** [comment]
@idbeta @nic-chen what is your opinion?

**Comment by membphis** [comment]
related issue? https://github.com/apache/apisix-dashboard/issues/1140

if yes, then we can close one of them

**Comment by nic-chen** [comment]
yes, it's duplicate.
we can use the ginkgo framework to improve the readability of e2e test information.

**Comment by nic-chen** [comment]
since bug of e2e failed has fixed, we could put it to M2.4

**Comment by idbeta** [comment]
> @idbeta @nic-chen what is your opinion?

I agree with @juzhiyuan .

**Comment by nic-chen** [comment]
finish framework and route part in M2.4

**Comment by nic-chen** [comment]
We have another issue #1500 to track. And we have used ginkgo to rewrite many e2e test cases in milestone 2.5.
This issue can be closed now.
