### ISSUE TITLE
Feat: try storage.Get in GenericStore.Get

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1137]
# Feature request

## Please describe your feature

Hello. Now we only try to get info from the cache in GenericStore.Get.
You can see this:

https://github.com/apache/apisix-dashboard/blob/822aa6d1f40c5eb5bfef00030304eb5b619a9eea/api/internal/core/store/store.go#L139-L146

It's not perfect.

## Describe the solution you'd like

IMO, I think that we need to try `storage.Get` if it can't found in the cache. Because sometimes there is latency in etcd watch.
Like this:

```
func (s *GenericStore) Get(key string) (interface{}, error) { 
 	ret, ok := s.cache.Load(key) 
 	if !ok { 
                // call s.Stg.Get
 		log.Warnf("data not found by key: %s", key) 
 		return nil, data.ErrNotFound 
 	} 
 	return ret, nil 
 } 
```

## Additional context

Add I think this can fix: https://github.com/apache/apisix-dashboard/issues/922

**Comment by juzhiyuan** [comment]
oh yes!!!

**Comment by juzhiyuan** [comment]
If we couldn't find it from the cache, shall we set it to cache once we get it from Storage?

**Comment by starsz** [comment]
> If we couldn't find it from the cache, shall we set it to cache once we get it from Storage?

I think there is no need. Because this will be done in `etcd` watch.

https://github.com/apache/apisix-dashboard/blob/822aa6d1f40c5eb5bfef00030304eb5b619a9eea/api/internal/core/store/store.go#L113-L134

**Comment by nic-chen** [comment]
The failure is on the APISIX api. We could have a try for it.

**Comment by juzhiyuan** [comment]
> The failure is on the APISIX api. We could have a try for it.
> 
> 

APISIX API means admin api?

**Comment by nic-chen** [comment]
> > The failure is on the APISIX api. We could have a try for it.
> > 
> > 
> 
> APISIX API means admin api?

DP API

**Comment by moonming** [comment]
Didn't you operate etcd directly?  Why is it related to dp?

**Comment by nic-chen** [comment]
> Didn't you operate etcd directly? Why is it related to dp?

Oh, E2E test failed on DP API. The issue is about trying to fix E2E failed, the title is a bit misleading.

**Comment by starsz** [comment]
The e2e test fixed in https://github.com/apache/apisix-dashboard/pull/1139
