### ISSUE TITLE
ci: Use the ginkgo framework to run E2E test cases to better display the running result information

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1140]
Currently e2e tests use the original `testing` to run, we can add a `ginkgo` framework for better displaying of the results. here is an example:

https://travis-ci.org/github/onsi/ginkgo/jobs/751622591

**Comment by membphis** [comment]
can we implement this issue at milestone `2.3`? or `2.4`?

**Comment by nic-chen** [comment]
duplicate with #1136
