### ISSUE TITLE
request help: global_rule need create_time and update_time

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1143]
### Issue description

Now, the global rule schema doesn't have `create_time` and `update_time`.
I think we can add it.

https://github.com/apache/apisix/blob/9b5fa0b4c49c1eb1a12a21f5ced32a456c7c39f1/apisix/schema_def.lua#L686-L694

### Environment

* apisix version (cmd: `apisix version`): master
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by membphis** [comment]
> Now, the global rule schema doesn't have `create_time` and `update_time`.

why do we need to export this field?

**Comment by starsz** [comment]
IMO, if we have `create_time` and `update_time` in `global rules` will be useful for developers. We can know the `global rules` create time and update time. 

Besides, `route`, consumer` and `services`  all have both fields.

**Comment by membphis** [comment]
> IMO,`create_time` and `update_time` in `global rules` will be useful for developers. They can know the `global rules`s create time and update time.

only need to read this field for API caller, all right?

**Comment by starsz** [comment]
Right.

**Comment by juzhiyuan** [comment]
conclusion and solution?

**Comment by starsz** [comment]
Add create_time and update_time in the `global rule` like `route`.

**Comment by imjoey** [comment]
@juzhiyuan cause this functionality is still not integrated in FE, so shall we keep it open for now? Thanks.

**Comment by juzhiyuan** [comment]
@imjoey Just to make sure, https://github.com/apache/apisix-dashboard/blob/master/web/src/pages/ServerInfo/List.tsx#L86-L91 if those 2 fields are returned from manager-api, then the fe will show them directly.

**Comment by imjoey** [comment]
> @imjoey Just to make sure, https://github.com/apache/apisix-dashboard/blob/master/web/src/pages/ServerInfo/List.tsx#L86-L91 if those 2 fields are returned from manager-api, then the fe will show them directly.

@juzhiyuan I'm a little confused that the code you mentioned is about ServerInfo, not GlobalRule.

**Comment by juzhiyuan** [comment]
ok fine, for Global Rule in the FE, the Global Plugin(Global Rule actually) doesn't plan to have UI to show created_time/updated_time, please see here https://github.com/apache/apisix-dashboard/blob/d6dcaa4066acf864b2d9303e570486b5dabb9265/web/src/pages/Plugin/service.ts#L30

**Comment by imjoey** [comment]
> ok fine, for Global Rule in the FE, the Global Plugin(Global Rule actually) doesn't plan to have UI to show created_time/updated_time, please see here
> 
> https://github.com/apache/apisix-dashboard/blob/d6dcaa4066acf864b2d9303e570486b5dabb9265/web/src/pages/Plugin/service.ts#L30

@juzhiyuan thanks for reply. If there is no plan in FE, we can close this for now. 🍻
