### ISSUE TITLE
插件配置项里面，必填项没有默认参数，导致配置提交失败

### ISSUE THREAD

**Issue by kinbod** [apache/apisix-dashboard#1144]
# Bug report

## Describe the bug

插件配置项里面，启用插件，然后关闭插件后，发送给后端的json数里面仍然包含已关闭插件的属性，由于某些插件的配置属性里面包含必填项，最终导致整个配置无法提交

## How to Reproduce

(root): key is required
(root): time_window is required

Must validate one and only one schema (oneOf)
(root): whitelist is required

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

**Comment by juzhiyuan** [comment]
This issue is resolved in the coming v2.3, please use the master branch currently.
