### ISSUE TITLE
plugin compose support Edge browser

### ISSUE THREAD

**Issue by QiuQiu0034** [apache/apisix-dashboard#1150]
plugin compose doesn't support Edge browser

The Edge and Chrome are both based on Chromium.
maybe the edge will work well

**Comment by juzhiyuan** [comment]
Yep, but we have a long way to support other browsers currently 😂 Would you like to have a try on this issue? We could help you to resolve this.

**Comment by qian0817** [comment]
Hi @juzhiyuan 
I found plugin orchestration works well with Edge (Chromium) browser,so consider modifying the judgment condition to allow Edge to use this feature
