### ISSUE TITLE
Resource create request should return the ultimate data

### ISSUE THREAD

**Issue by tokers** [apache/apisix-dashboard#1154]
# Feature request

## Please describe your feature

When create resources like Route without specifying id, the ultimate data should be returned, otherwise people cannot reference the just created resource by id.

![image](https://user-images.githubusercontent.com/10428333/103332608-8f598500-4aa5-11eb-856e-c2a23fd97740.png)

## Describe the solution you'd like

Output the data in the response.

**Comment by starsz** [comment]
Agree with it.

IMO, we need to keep the same response as apisix.

**Comment by membphis** [comment]
agree with this too

**Comment by imjoey** [comment]
@tokers @starsz @membphis Users could create a resource via `POST` or `PUT` methods. No way to refer the new object only occurs at `POST` method. Shall we also return the ultimate data when using `PUT` method?  FYI, the answer is yes for APISIX, need to make manager-api the same as Admin API?

Looking forward to your insights. Thanks.

**Comment by membphis** [comment]
> Shall we also return the ultimate data when using PUT method? FYI, the answer is yes for APISIX, need to make manager-api the same as Admin API?

the Admin API and Manager API should work in the same way. 
So I think the answer is yes, they should return the final data at the same time, whether it is PUT or POST method.

**Comment by imjoey** [comment]
> > Shall we also return the ultimate data when using PUT method? FYI, the answer is yes for APISIX, need to make manager-api the same as Admin API?
> 
> the Admin API and Manager API should work in the same way.
> So I think the answer is yes, they should return the final data at the same time, whether it is PUT or POST method.

@membphis copy. Thanks for the directions.

**Comment by juzhiyuan** [comment]
> we also need to fix that for HTTP PUT methods

This is needed.

**Comment by imjoey** [comment]
> > we also need to fix that for HTTP PUT methods
> 
> This is needed.

@juzhiyuan yep, I will commit an PR for this.

**Comment by imjoey** [comment]
@tokers  @juzhiyuan  since both #1277 and #1322 had been merged, I could close this issue. Please feel free to reopen it if anything unexpected. Thanks.
