### ISSUE TITLE
bug(cmd): Inaccurate output Version number of manger-api command

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-dashboard#1155]
# Bug report

## Describe the bug

When running `manager-api` command generated by the latest code from `master` branch, the output `Version` is `2.2`, which is obviously inaccurate. The log shows as below:

```
➜  apisix-dashboard/output git:(master) ./manager-api
The manager-api is running successfully!

Version : 2.2
Listen  : 127.0.0.1:9000
Loglevel: warn
Logfile : /Users/imjoey/Work/apache-apisix/apisix-dashboard/output/logs/error.log
```

## How to Reproduce

1. Fetch the latest code from master branch;
2. Run `make build`;
3. Go into `output` directory and run `./manager-api`;
4. See error;

## Expected behavior

The `Version` should be `master`. 

## System information

- OS: macOS
- Version: master

## Additional context

While honestly, the `master` is still **not intuitive**, so shall we also add Git hash into the output? Such as:

```
Version : master
GitHash: 4317a5f
Listen  : 127.0.0.1:9000
Loglevel: warn
Logfile : /Users/imjoey/Work/apache-apisix/apisix-dashboard/output/logs/error.log
```

Any feedback is welcome. Thanks.

**Comment by juzhiyuan** [comment]
I agree, it's really helpful in the develop branch. @tokers @membphis  right?

**Comment by starsz** [comment]
Agree +1. PR is welcomed.

**Comment by imjoey** [comment]
@juzhiyuan @starsz OK, thanks for your feedback. I can tackle this. 😃
