### ISSUE TITLE
test: add FE e2e test for global plugin

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1156]
# Feature request

## Please describe your feature
After #1106 merged, we need to add  e2e test for the global plugin.

**Comment by LiteSun** [comment]
cc @idbeta

**Comment by membphis** [comment]
ping @idbeta

**Comment by juzhiyuan** [comment]
FYI: most test cases for every plugin have been added.

**Comment by idbeta** [comment]
No problem, I submit a PR to achieve it.
