### ISSUE TITLE
UI: incorrect page width in Plugin Market page

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1158]
# Bug report

## Describe the bug

Too width to see all contents, unless scroll horizontal.

## How to Reproduce

1. Go to Consumer module;
2. Create a Consumer;
3. We will see incorrect width on the Step2.

## Expected behavior

Don't show the scrollbar.

## Screenshots

![image](https://user-images.githubusercontent.com/2106987/103341935-2aad2300-4ac3-11eb-8ec5-8229ef058201.png)

## System information

- OS: All
- Browser: All
- Version: 2.2

**Comment by guoqqqi** [comment]
You can assign it to me, I will try to solve it.

**Comment by moonming** [comment]
why we need “

How to Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
”？
NEVER used.

**Comment by juzhiyuan** [comment]
It's an Issue template, to make authors have a guide on how to clearly describe what this Issue does (AMAP), just updated the issue description.
