### ISSUE TITLE
通过apisix访问 manage-api(作为upstream), 偶发性的403?

### ISSUE THREAD

**Issue by json7** [apache/apisix-dashboard#1159]
# Bug report

## 
1. enable_admin: false 关闭 admin api
2. 启动 dashboard: apisix-dashboard 运行起来后,listen 9001.  然后基于localhost:9001的方式 访问web管理系统, 然后创建一个upstream(就是manage-api 自己 127.0.0.1:9001), 再去创建路由( /* 全部匹配 )
3. curl 127.0.0.1:9080/apisix/admin/upstreams 偶发性403 (理论上这应该转发到manage-api上,实时流量被apisix拦住了)

**Comment by starsz** [comment]
Hello, please provide your apisix and apisix-dashboard version.

I think the reason is the apisix doesn't sync data from etcd in time.
Maybe you can check the `resync_delay` option in apisix config.

**Comment by json7** [comment]
不是的.我手动查看过etcd中的数据,并且尝试N次apisix restart. 还是无效.
当然我已经解决,就是将 manage-api中的 url前缀 "apisix/admin" 修改为 "apisixbug/admin" . 问题已经解决.  目测来看这个bug不是dashboard的,而是apisix的

**Comment by juzhiyuan** [comment]
> 不是的.我手动查看过etcd中的数据,并且尝试N次apisix restart. 还是无效.
> 当然我已经解决,就是将 manage-api中的 url前缀 "apisix/admin" 修改为 "apisixbug/admin" . 问题已经解决. 目测来看这个bug不是dashboard的,而是apisix的

cc @spacewander Please take a look.

**Comment by tokers** [comment]
> 不是的.我手动查看过etcd中的数据,并且尝试N次apisix restart. 还是无效.
> 
> 当然我已经解决,就是将 manage-api中的 url前缀 "apisix/admin" 修改为 "apisixbug/admin" . 问题已经解决.  目测来看这个bug不是dashboard的,而是apisix的
> 
> 

What's the response body like about this 403?

**Comment by json7** [comment]
> What's the response body like about this 403?

没有响应body, http 协议 status是403

**Comment by json7** [comment]
> > 不是的.我手动查看过etcd中的数据,并且尝试N次apisix restart. 还是无效.
> > 当然我已经解决,就是将 manage-api中的 url前缀 "apisix/admin" 修改为 "apisixbug/admin" . 问题已经解决.  目测来看这个bug不是dashboard的,而是apisix的
> 
> What's the response body like about this 403?

复现方法:
关闭admin api, 直接curl  ip:9080/apisix/admin/upstreams, 10次请求以内就会出403.  9443https不会出现, 只有http 9080会出现

**Comment by json7** [comment]
> > 不是的.我手动查看过etcd中的数据,并且尝试N次apisix restart. 还是无效.
> > 当然我已经解决,就是将 manage-api中的 url前缀 "apisix/admin" 修改为 "apisixbug/admin" . 问题已经解决.  目测来看这个bug不是dashboard的,而是apisix的
> 
> What's the response body like about this 403?

![Uploading image.png…]()

**Comment by json7** [comment]
![image](https://user-images.githubusercontent.com/3734822/103363503-336b1c80-4af6-11eb-8ca0-6ddd31fcb353.png)

**Comment by json7** [comment]
![image](https://user-images.githubusercontent.com/3734822/103363626-83e27a00-4af6-11eb-98a1-5ae955965a85.png)

**Comment by spacewander** [comment]
Please provide the error log when 403 happened. Since the error log will be large, you should upload the whole one instead of paste it here.

**Comment by spacewander** [comment]
Remember to decrease the error_log level to "info" before providing the error log.

**Comment by json7** [comment]
Yes, it's about the openresty version. I went back to 1.17 and it's normal
