### ISSUE TITLE
Feat: remove the etcd dependency in the unit test

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1161]
# Feature request

## Please describe your feature

Now, `route`, `ssl` `services`  and `upstream` module are use etcd to store info.
I think we should remove the etcd dependency in the unit test.

## Describe the solution you'd like

Use store.MockInterface{} instead of using the etcd.

- [x] route
- [x] ssl
- [x] services
- [x] upstream

**Comment by tokers** [comment]
Agree +1.

**Comment by juzhiyuan** [comment]
If we need to resolve this issue in 2.3 or 2.4?

**Comment by starsz** [comment]
> If we need to resolve this issue in 2.3 or 2.4?

I think it's a feature. So we may resolve it in 2.4.

**Comment by starsz** [comment]
This is a big project, I will finish part of them in M2.4

**Comment by nic-chen** [comment]
finish test cases of  route, service

**Comment by Jaycean** [comment]
@starsz 
Hi,I have finished writing the SSL unit test, and if you do not start writing the upstream unit test, I can do so.

**Comment by starsz** [comment]
> @starsz
> Hi,I have finished writing the SSL unit test, and if you do not start writing the upstream unit test, I can do so.

Oh, good.Thank you very much.

**Comment by starsz** [comment]
Because the test cases of the route, service had finished, so I think we can change the millstone to M2.5.

**Comment by starsz** [comment]
This problem was solved. Thank you for every contributor.
