### ISSUE TITLE
Langauge selection issue in Dashboard 

### ISSUE THREAD

**Issue by jinusuresh** [apache/apisix-dashboard#1163]
# Bug report
Despite setting the language to English , the language is not getting set in Dashboard , for example the create Route screen , first screen shows in English but the following screen is in Chinese , a screen shot attached  
## Describe the [bug](url)
![SharedScreenshot](https://user-images.githubusercontent.com/51432247/103347396-e7e84c80-4abc-11eb-848a-2a1c5d697094.jpg)

Despite setting the language to English , the language is not getting set in Dashboard , for example the create Route screen , first screen shows in English but the following screen is in Chinese , a screen shot attached  

## How to Reproduce

1. Go to '...' "APISIX Dashboard"
2. Click on '....' - Login as admin and click Select Route , then new Route , give name for the API and click next 

## Expected behavior

When language ENGLISH is selected , it should consistently show all screens in English

## Screenshots

attached 

## System information

- OS: [e.g. macOS, Windows] - Windows 
- Browser (if applies) [e.g. Chrome, Safari, Edge] - Chrome/Firefox 
- Version: [e.g. 2.0-rc3] - Latest

**Comment by juzhiyuan** [comment]
Hi, I just checked the latest codes from the master branch, but couldn't produce this issue.

cc @idbeta Please have a try on the Windows, thanks!

![image](https://user-images.githubusercontent.com/2106987/103351421-217d7f80-4ade-11eb-9dc1-90ef324a43ca.png)

**Comment by idbeta** [comment]
> Hi, I just checked the latest codes from the master branch, but couldn't produce this issue.
> 
> cc @idbeta Please have a try on the Windows, thanks!
> 
I tried the `master` branch and `v2.2` branch in windows7, but the problem cannot be reproduced.

**Comment by juzhiyuan** [comment]
got it, thanks. 

@jinusuresh Please have a try on the master branch with APISIX master, if this issue still occurred, we could reopen this issue.

**Comment by jinusuresh** [comment]
Hi ,

This is what used after taking the code from master branch on Ubuntu 20.x

docker build --build-arg APISIX_VERSION=2.1 --build-arg APISIX_DASHBOARD_VERSION=v2.2 -t apache/apisix-dashboard:test5 -f ./all-in-one/apisix-dashboard/Dockerfile .

Thanks,
Jinu Sureshbabu

**Comment by jinusuresh** [comment]
Also did this to run

docker run -v `pwd`/all-in-one/apisix/config.yaml:/usr/local/apisix/conf/config.yaml -v `pwd`/all-in-one/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml -p 19080:9080 -p 12379:2379 -p 19000:9000 -d apache/apisix-dashboard:test5

Thanks,
Jinu Sureshbabu

From: Jinu S - ASISTA<mailto:jinu.s@asista.com>
Sent: Thursday, December 31, 2020 10:14 PM
To: apache/apisix-dashboard<mailto:reply@reply.github.com>; apache/apisix-dashboard<mailto:apisix-dashboard@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [apache/apisix-dashboard] Langauge selection issue in Dashboard (#1163)

Hi ,

This is what used after taking the code from master branch on Ubuntu 20.x

docker build --build-arg APISIX_VERSION=2.1 --build-arg APISIX_DASHBOARD_VERSION=v2.2 -t apache/apisix-dashboard:test5 -f ./all-in-one/apisix-dashboard/Dockerfile .

Thanks,
Jinu Sureshbabu

**Comment by jinusuresh** [comment]
I am still getting the same issue , first screen English and second screen Chinese. I can help with any other info you might need to resolve this

Thanks,
Jinu Sureshbabu

From: Jinu S - ASISTA<mailto:jinu.s@asista.com>
Sent: Thursday, December 31, 2020 10:16 PM
To: apache/apisix-dashboard<mailto:reply@reply.github.com>; apache/apisix-dashboard<mailto:apisix-dashboard@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [apache/apisix-dashboard] Langauge selection issue in Dashboard (#1163)

Also did this to run

docker run -v `pwd`/all-in-one/apisix/config.yaml:/usr/local/apisix/conf/config.yaml -v `pwd`/all-in-one/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml -p 19080:9080 -p 12379:2379 -p 19000:9000 -d apache/apisix-dashboard:test5

Thanks,
Jinu Sureshbabu

From: Jinu S - ASISTA<mailto:jinu.s@asista.com>
Sent: Thursday, December 31, 2020 10:14 PM
To: apache/apisix-dashboard<mailto:reply@reply.github.com>; apache/apisix-dashboard<mailto:apisix-dashboard@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [apache/apisix-dashboard] Langauge selection issue in Dashboard (#1163)

Hi ,

This is what used after taking the code from master branch on Ubuntu 20.x

docker build --build-arg APISIX_VERSION=2.1 --build-arg APISIX_DASHBOARD_VERSION=v2.2 -t apache/apisix-dashboard:test5 -f ./all-in-one/apisix-dashboard/Dockerfile .

Thanks,
Jinu Sureshbabu

**Comment by juzhiyuan** [comment]
@idbeta Please take a further deep search on this issue.

**Comment by jinusuresh** [comment]
Hi Guys ,

Any update ?

Thanks,
Jinu Sureshbabu

**Comment by imjoey** [comment]
> Hi Guys ,

> Any update ?

Hi @jinusuresh , good to see you and sorry for late.

> Hi , This is what used after taking the code from master branch on Ubuntu 20.x docker build --build-arg APISIX_VERSION=2.1 --build-arg APISIX_DASHBOARD_VERSION=v2.2 -t apache/apisix-dashboard:test5 -f ./all-in-one/apisix-dashboard/Dockerfile . Thanks

It seems that your previous command specified a build argument `APISIX_DASHBOARD_VERSION=v2.2`, which would lead to use the code from `v2.2` release of dashboard, instead of the latest code from master. The default value for `APISIX_DASHBOARD_VERSION ` is `master`, so could you please take a try with the following command?

`docker build --build-arg APISIX_VERSION=2.1 -t apache/apisix-dashboard:test5 -f ./all-in-one/apisix-dashboard/Dockerfile . `

Looking forward to your feedbacks. Thanks.

**Comment by juzhiyuan** [comment]
This command should under the `apisix-docker` repo, right?

**Comment by juzhiyuan** [comment]
We have pushed the new docker image to DockerHub `apache/apisix-dashboard`, please have a try.

**Comment by jinusuresh** [comment]
Thanks , it got fixed

Thanks,
Jinu Sureshbabu
