### ISSUE TITLE
tip: display a warning message on the dashboard if the user is not using the recommended APISIX + Dashboard version

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1165]
this is the recommended way.

![image](https://user-images.githubusercontent.com/6814606/103356788-9eaff100-4aec-11eb-807f-07cb0f0923d5.png)

If the user does not use it in this way, we can display a warning message on the dashboard.

It might be a good way to display it on the status page.

related issue: https://github.com/apache/apisix-dashboard/issues/1148

**Comment by starsz** [comment]
Agree with it. 
Do this need to store the `version mapping` info in FE?

**Comment by juzhiyuan** [comment]
The quick way to implement this is just adding some tips in README or some places;

I would prefer adding the `x-client-version: v2.3` header when sending a request, then the backend will check if it's compatible 🤔

**Comment by starsz** [comment]
Now, the way to get apisix version is through `server_info`.And there is more than one apisix instance. So I think we can add an API like this `/version_check` to do the version check.
When FE called `/version_check`, the manger-api will traverse the apisix server info and give the response.

**Comment by juzhiyuan** [comment]
**Backend**
- Provide the `version_check` API;

**Frontend**
- Call the above API when the page first shows, once.

**Comment by moonming** [comment]
When packaging, write a separate version file, which is a json string, is this ok? 
 We are only responsible for the packaged version

**Comment by starsz** [comment]
IMO, BE provide the API as follow. This API is used for checking the version of apisix and dashboard are matched.

```
GET /apisix/admin/tool/version_match
```

The response like this:

```
{
    "code": "2000001 |  0",
    "message": "The version of apisix and dashboard are not matched.",
    "request_id": "",
    "data": {
        "matched": true | false,
        "dashboard_version": "2.3",
        "not_matched_nodes": [{
            "hostname": "apisix-deployment-5c845b74b-bsrjm",
            "version": "2.1"
        }]
    }
}
```

**Comment by juzhiyuan** [comment]
good to go

**Comment by tokers** [comment]
> IMO, BE provide the API as follow. This API is used for checking the version of apisix and dashboard are matched.
> 
> ```
> GET /apisix/admin/tool/version_match
> ```
> 
> The response like this:
> 
> ```
> {
>     "code": "2000001 |  0",
>     "message": "The version of apisix and dashboard are not matched.",
>     "request_id": "",
>     "data": {
>         "matched": true | false,
>         "dashboard_version": "2.3",
>         "not_matched_nodes": [{
>             "hostname": "apisix-deployment-5c845b74b-bsrjm",
>             "version": "2.1"
>         }]
>     }
> }
> ```

maybe `mimatched_nodes` is better than `not_matched_nodes` .

**Comment by juzhiyuan** [comment]
`mismatch_nodes`

**Comment by tokers** [comment]
> `mismatch_nodes`

Gotcha.
