### ISSUE TITLE
When creating a route, the domain name is v1_test-api.xxx.com and it cannot pass the verification json schema verification

### ISSUE THREAD

**Issue by json7** [apache/apisix-dashboard#1167]
# Bug report

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

**Comment by juzhiyuan** [comment]
cc @idbeta

**Comment by juzhiyuan** [comment]
I just checked this host is forbidden by ManagerAPI, let's @nic-chen @starsz take a look.

![image](https://user-images.githubusercontent.com/2106987/103387760-79e56900-4b40-11eb-8965-9facddda4475.png)

**Comment by nic-chen** [comment]
We don't support `_` in host or hosts now. 

Top-level domains do not support `_`. 

But some domain name registrars seem to support `_` for subdomains. 

Do we need to support it ?

cc @membphis @spacewander

**Comment by spacewander** [comment]
Sure.

**Comment by membphis** [comment]
@nic-chen you need to sync the latest JSON schema from APISIX

related PR merged: https://github.com/apache/apisix/pull/3165

**Comment by nic-chen** [comment]
> @nic-chen we need to sync the latest JSON schema from APISIX
> 
> related PR merged: [apache/apisix#3165](https://github.com/apache/apisix/pull/3165)

OK
