### ISSUE TITLE
feat: adding Icons for plugins

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1168]
# Feature request

## Please describe your feature

 adding Icons for plugins

**Comment by imjoey** [comment]
Hi @juzhiyuan , may I ask that what kinds of icons will be added for each plugin? Is there a plan or a design? Looking forward to your reply. Thanks.

**Comment by juzhiyuan** [comment]
Not sure, I will handle this issue those days :)

**Comment by imjoey** [comment]
@juzhiyuan will keep an eye on this. Please let @liuxiran and me know if there is anything we can do. Thanks.
