### ISSUE TITLE
bug: plugin list shows the plugins which are disabled in config-default.yaml

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1172]
# Bug report

## Describe the bug

the plugin list shows the plugins which are disabled in `config-default.yaml`, so they are invalid after setting. 
It is recommended not to display them, or prompt need to enable the plugin first.
like `log-rotate`, `error-log-logger`, `node-status`, `skywalking`, `server-info`

![image](https://user-images.githubusercontent.com/7396835/103402182-f0a55500-4b86-11eb-8458-ec80401f1ae7.png)

**Comment by juzhiyuan** [comment]
ping @nic-chen

**Comment by nic-chen** [comment]
OK, just need to update schema.
