### ISSUE TITLE
request help: server info page does not display any information, can it be displayed by default

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1173]
# Feature request

## Please describe your feature

server Info page does not display any information, can it be displayed by default?

**Comment by juzhiyuan** [comment]
If that plugin is not enabled, there doesn't have any information indeed. We have a tip on this.

![image](https://user-images.githubusercontent.com/2106987/103431393-f6904a00-4c09-11eb-988a-aa396d663d55.png)

**Comment by idbeta** [comment]
> If that plugin is not enabled, there doesn't have any information indeed. We have a tip on this.
> 
> ![image](https://user-images.githubusercontent.com/2106987/103431393-f6904a00-4c09-11eb-988a-aa396d663d55.png)

This is too complicated for ordinary users, I think it should be displayed by default.

**Comment by juzhiyuan** [comment]
This is disabled by default here[1], could you send a new issue about this in apache/apisix?

[1] https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L251

**Comment by idbeta** [comment]
> This is disabled by default here[1], could you send a new issue about this in apache/apisix?
> 
> [1] https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L251

ok
