### ISSUE TITLE
bug: when setting the plugin in codemirror, an error is prompted.

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1174]
# Bug report

## Describe the bug
when create route or setting plugin in `Plugin List`, after setting the plugin in codemirror, submit it,  an error is prompted.
![image](https://user-images.githubusercontent.com/7396835/103402922-4da20a80-4b89-11eb-89cf-a206ee471609.png)

**Comment by juzhiyuan** [comment]
@liuxiran @nic-chen Hello, please take a look at this issue. This issue happened due to different schema for Route and Consumer.

**Comment by nic-chen** [comment]
> the authentication plugins should be only shown with a switch to enabled/disabled in route or service module.

According to https://github.com/apache/apisix-dashboard/issues/529 .

I think we should  not config the auth plugins in route, service or global rule.

**Comment by idbeta** [comment]
> > the authentication plugins should be only shown with a switch to enabled/disabled in route or service module.
> 
> According to #529 .
> 
> I think we should not config the auth plugins in route, service or global rule.

but the `Plugin List` page  is not `global rule`, can’t enable `auth plugins` in it, will make others strange.

**Comment by juzhiyuan** [comment]
> > the authentication plugins should be only shown with a switch to enabled/disabled in route or service module.
> 
> According to #529 .
> 
> I think we should not config the auth plugins in route, service or global rule.

then how to bind Consumer with Route?

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/103497495-a5d45780-4e7c-11eb-96e2-0cf8e89d5e69.png)

Got it, then for Route, Service and Global Rule, we only need to enable/disable Auth plugins without any configurations, right?

**Comment by juzhiyuan** [comment]
we only need to add some tips in the frontend, tells users just enable or disable.

**Comment by liuxiran** [comment]
> > the authentication plugins should be only shown with a switch to enabled/disabled in route or service module.
> 
> According to #529 .
> 
> I think we should not config the auth plugins in route, service or global rule.

Agree, only enable/disable auth plugins in `Route` `Service` module is engough ^_^
but for the global rule, I'm not sure is we only enable a auth plugin, what will happen in Consumer module?

**Comment by nic-chen** [comment]
> > > the authentication plugins should be only shown with a switch to enabled/disabled in route or service module.
> > 
> > 
> > According to #529 .
> > I think we should not config the auth plugins in route, service or global rule.
> 
> Yep, only enable/disable auth plugins in `Route` `Service` module is engough ^_^
> but for the global rule, I'm not sure if we only enable a auth plugin, what will happen in Consumer module? @nic-chen

`global rule` acts like enable plugins for routes. So it's same as enable plugins in routes.

**Comment by juzhiyuan** [comment]
A little strange 🤔 If we need to create a global rule with auth plugins, we should:

1. Create a Consumer with Auth plugins;
2. Create a global rule and enable at least 1 auth plugin;

cc @membphis @spacewander May I know what's your opinion?

**Comment by nic-chen** [comment]
ping

**Comment by spacewander** [comment]
The auth plugin is all for selecting a consumer. It is a noop if we don't have any consumer. Also the route configuration for auth plugin is usually empty.

**Comment by juzhiyuan** [comment]
fine, then for Route, Service, and GlobalRule, we only disable/enable auth plugins, right? 🤔

**Comment by membphis** [comment]
> fine, then for Route, Service, and GlobalRule, we only disable/enable auth plugins, right? 🤔

yes, you are right. @juzhiyuan
