### ISSUE TITLE
bug: server info page shows `create_time` and `update_time`, which are not the content returned by the plugin

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1176]
# Bug report

## Describe the bug

the server info page shows `create_time` and `update_time`, which are not the content returned by the plugin (server-info).

`{"code":0,"message":"","data":{"rows":[{"id":"9b1cfaa8-b33c-4eb9-912e-f2dbe267ece4","create_time":0,"update_time":0,"last_report_time":1609406690,"up_time":1920,"boot_time":1609404770,"etcd_version":"3.4.0","hostname":"xxxx","version":"2.1"}],"total_size":1},"request_id":"f0ac1a65-4e96-4388-ae56-40f25f7e604a"}`

![image](https://user-images.githubusercontent.com/7396835/103404223-c0ad8000-4b8d-11eb-8a44-077486cec2f5.png)

**Comment by spacewander** [comment]
Is the create_time / update_time necessarily in this case? Who cares about the create / update time of server info which only used to display? The life cycle info is not so useful.

**Comment by juzhiyuan** [comment]
Agree, and server info page doesn’t need those 2 fields indeed.--
来自 琚致远

**Comment by imjoey** [comment]
> Is the create_time / update_time necessarily in this case? Who cares about the create / update time of server info which only used to display? The life cycle info is not so useful.

@spacewander agreed. The two fields are only for recording etcd operations, meaningless for APISIX core and users. I would close the linked corresponding PR. @juzhiyuan so please let us mark this issue to `frontend`. Thanks.

**Comment by juzhiyuan** [comment]
Hi @imjoey, do we need to display these 2 fields in the frontend?

**Comment by imjoey** [comment]
> Hi @imjoey, do we need to display these 2 fields in the frontend?

@juzhiyuan IMHO, no need for that, as the `boot_time` and `last_report_time` are already enough for users. 😄

**Comment by juzhiyuan** [comment]
fine, the frontend receives data, then parse it as key/value array, if we need to hide these 2 fields, we'd better do this in manager-api, but I think it's not needed, so just assign a Good First Issue label for it.

https://github.com/apache/apisix-dashboard/blob/v2.3/web/src/pages/ServerInfo/List.tsx#L86-L91

**Comment by imjoey** [comment]
> fine, the frontend receives data, then parse it as key/value array, if we need to hide these 2 fields, we'd better do this in manager-api, but I think it's not needed, so just assign a Good First Issue label for it.
> 
> https://github.com/apache/apisix-dashboard/blob/v2.3/web/src/pages/ServerInfo/List.tsx#L86-L91

@juzhiyuan  sorry for not knowing the fields are provided via backend. 😢   Agreed with you that it should be fixed in manager-api. It's easy with just two tiny changes, please allow to continue with this issue via another PR in manager-api. 😄

**Comment by juzhiyuan** [comment]
Sure 😊

**Comment by imjoey** [comment]
Hi @idbeta , this issue has been fixed via #1203 . Please have a check. Thank you very much.
