### ISSUE TITLE
bug: the date and time displayed on server info page are not human readable

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1178]
# Bug report

## Describe the bug

the date and time displayed on `server info` page are not human readable

![image](https://user-images.githubusercontent.com/7396835/103981552-f91c1200-51bc-11eb-9336-aa29821731b0.png)

**Comment by juzhiyuan** [comment]
Why is this a bug?

**Comment by tokers** [comment]
We may need to convert them to a human friendly format in page.

**Comment by guoqqqi** [comment]
For this problem, I want to try to solve it！
