### ISSUE TITLE
Bug: missed Version and Githash when do `make api-run`

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#1185]
# Bug report

## Describe the bug

when start manager-api using `make api-run`, version and githash fields are empty in command line.

## How to Reproduce

1. update dashboard to lastest master branch
2. use `make api-run` to run manager-api
3. view the info in command line
4. Version field and Githash field are empty.

## Screenshots
![2021-01-04 09-48-56屏幕截图](https://user-images.githubusercontent.com/2561857/103494801-4e7db980-4e73-11eb-8813-62fb516cc9a9.png)

## System information

- OS: Fedora32
- Version: master branch

**Comment by starsz** [comment]
Thanks for the report.
We need to add `ldflags` in `make api-run`.
