### ISSUE TITLE
bug: route's label search is return 400

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1186]
# Bug report

## Describe the bug
the lable of route is `a:1`
when search on route, is return 400.

```
Request URL: http://127.0.0.1:9000/apisix/admin/routes?label=a%3A1%2C&page=1&page_size=20
Request Method: GET
Status Code: 400 Bad Request
Response: {"code":10000,"message":"malformed label: \"a:1,\"","data":null,"request_id":"23661bdf-dbd4-47f1-9a7c-d0c5783a4cbe"}
```
## How to Reproduce
![image](https://user-images.githubusercontent.com/7396835/103500387-192e9700-4e86-11eb-9f6c-2f0d33d519a4.png)

**Comment by starsz** [comment]
@juzhiyuan. If only one label, it shouldn't contain ",".

Like this:
`http://127.0.0.1:9000/apisix/admin/routes?label=a:1&page=1&page_size=20`

And this:
`http://127.0.0.1:9000/apisix/admin/routes?label=a:1,b:1&page=1&page_size=20`

**Comment by LiteSun** [comment]
OK, I'll fix it.
