### ISSUE TITLE
bug: search by status on the route list page is invalid

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1189]
# Bug report

## Describe the bug
![image](https://user-images.githubusercontent.com/7396835/103504788-6d8c4380-4e93-11eb-9ba0-9dddda581e99.png)
I think the query string is wrong.
```
Request URL: http://127.0.0.1:9000/apisix/admin/routes?label=&page=1&page_size=20
Request Method: GET
```

**Comment by Jaycean** [comment]
@liuxiran Please Assigne to me. Thks.
