### ISSUE TITLE
bug: search by description on the Service List page is invalid

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1191]
# Bug report

bug: search by Description on the Service List page is invalid

![image](https://user-images.githubusercontent.com/7396835/103506853-b85c8a00-4e98-11eb-88ef-646815429505.png)

```
Request URL: http://127.0.0.1:9000/apisix/admin/services?page=1&page_size=20
Request Method: GET
```

**Comment by nic-chen** [comment]
it should be better if you can submit the request data and respond data. @idbeta

**Comment by LiteSun** [comment]
I check it in my local environment. both FE and BE need to fix. 😂 @nic-chen 

![image](https://user-images.githubusercontent.com/31329157/103525049-8f002600-4eb9-11eb-8f92-ae2f92d1becf.png)

**Comment by juzhiyuan** [comment]
@LiteSun you mean the manager-api should support search by desc?

**Comment by nic-chen** [comment]
Oh, we don't support search by desc now.

**Comment by LiteSun** [comment]
OK, will remove search desc later.
