### ISSUE TITLE
bug: create service with manual fill upstream, will be error.

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1193]
# Bug report

create service with manual fill upstream, will be error.
This problem will not arise if create service with select an existing upstream.
![image](https://user-images.githubusercontent.com/7396835/103507239-a8917580-4e99-11eb-9cde-d3b514b4d7b3.png)

## How to Reproduce

```
Request URL: http://127.0.0.1:9000/apisix/admin/services
Request Method: POST
Request Body: {"plugins":{},"upstream":{"type":"roundrobin","nodes":[{"host":"127.0.0.1","port":80,"weight":1}],"pass_host":"pass","timeout":{"connect":6000,"send":6000,"read":6000},"checks":{}}}
Response: {"code":10000,"message":"schema validate failed: upstream.checks: Must validate at least one schema (anyOf)\nupstream.checks: active is required"}
```

**Comment by juzhiyuan** [comment]
cc @nic-chen @LiteSun

**Comment by nic-chen** [comment]
should omit `checks`, or it will fail on schema checking. @LiteSun

**Comment by LiteSun** [comment]
> should omit `checks`, or it will fail on schema checking. @LiteSun

Got it.
