### ISSUE TITLE
test:  Check for unnecessary wait in FE e2e

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1194]
# Feature request
The current e2e test case [1] has many `cy.wait()` [2] statements, we cannot change the test code because of the host environment, we need to check if the statements are required, if they are not required, remove them.

refer links:
1: https://github.com/apache/apisix-dashboard/blob/master/web/cypress/integration/upstream/create_and_delete_upstream.spec.js#L73- L84
2: https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-Waiting

**Comment by LiteSun** [comment]
cc @idbeta @juzhiyuan

**Comment by moonming** [comment]
I am very puzzled, why can't I just get rid of the waiting?  The official document explains very clearly, waiting is not necessary

**Comment by juzhiyuan** [comment]
I will check and update those test cases with @LiteSun today, `wait` is used too tricky just due to a different tester host.

**Comment by juzhiyuan** [comment]
Those test cases still have improvements, after discussing with @LiteSun, we are going to solve this in M2.4 first.
