### ISSUE TITLE
 can not save plugin ip-restriction blacklist

### ISSUE THREAD

**Issue by chenyicai** [apache/apisix-dashboard#1198]
# Bug report

## Describe the bug

When I edit the plugin （ip-restriction ） and configure blacklist, the page will display "is an invalid additional property"。
then  i can not save this configuretion;

## How to Reproduce

1. Go to 'Plugin Config'
2. Click on 'ip-restriction'
3. Scroll down to 'blacklist'

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies) [e.g. Chrome, Safari, Edge] chrome
- Version: [e.g. 2.0-rc3] v2.1.1-rc1

**Comment by nic-chen** [comment]
@chenyicai  what's your APISIX version ?

**Comment by chenyicai** [comment]
my apisix version is v2.0

**Comment by nic-chen** [comment]
`Dashboard 2.1.1 should be used with APISIX 2.1. It is not recommended to use with other APISIX versions.`

If you can upgrade it, It is recommended to use Dashboard 2.2 and use it with APISIX 2.1 now.
