### ISSUE TITLE
Change the structure of manager api will cause build failure in project apisix-docker.

### ISSUE THREAD

**Issue by agile6v** [apache/apisix-dashboard#1199]
# Bug report

## Describe the bug

The [structure](https://github.com/apache/apisix-dashboard/commit/cc9eb35db608142996fbba14c216181048182a1d#diff-a549989c42f7953e1c5f4ce79a9e5a5401dda0dae43897a0e1d43c69428ae49a) of the project will cause the build failure in [this](https://github.com/apache/apisix-docker/tree/master/all-in-one/apisix-dashboard) project.

Please see the [issue](https://github.com/apache/apisix-docker/issues/111).

## How to Reproduce

1. Run `docker build .` in [this project](https://github.com/apache/apisix-docker/tree/master/all-in-one/apisix-dashboard).

## Expected behavior

Expect forward compatibility.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

**Comment by gxthrj** [comment]
With [build args](https://github.com/apache/apisix-docker#quick-test-with-all-dependencies-in-one-docker-container) we can build the 2.0, 2.1 version, if build from master it will be failed.

I have to set some conditional judgment in Dockerfile.
