### ISSUE TITLE
bug(global_rule): check if the returned global_rule list data is as expected

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-dashboard#1208]
# Bug report

## Describe the bug

I enabled two plugins in global scope ( also known as `global_rule` ). The json data in response from endpoint `manager-api:9000/apisix/admin/global_rules` is as follows:

```json
{
   "code":0,
   "message":"",
   "data":{
      "rows":[
         {
            "id":"1",
            "plugins":{
               "cors":{
                  "disable":false
               },
               "echo":{
                  "before_body":"before the body modification ",
                  "disable":false
               }
            }
         }
      ],
      "total_size":1
   },
   "request_id":"221ac1c3-f66c-4661-974d-510535f48604"
}
```

The above data structure is not the same as others retuned by other interfaces. You will find the `total_size` is `1`. While what does the `id:1` mean for two plugins, does it indicate a APISIX server?  

Take `/apisix/admin/global_rules` for example, it returns the following json data: (some properties removed):

```json
{
   "code":0,
   "message":"",
   "data":{
      "rows":[
         {
            "id":"336048915977602045",
            "name":"tetst1",
            "status":1
         },
         {
            "id":"336048939381818365",
            "name":"test2",
            "status":1
         }
      ],
      "total_size":2
   },
   "request_id":"87c20714-3fa0-4745-8494-96aa5c2f5624"
}
```

So is the global_rule data as expected? Thanks.

## System information

- OS: macOS
- Version: latest in master branch (https://github.com/apache/apisix-dashboard/commit/45e90ec8e13a1c9659645034f1fd50f0552b93e3)

**Comment by nic-chen** [comment]
don't quite understand, where is the second data returned?

**Comment by imjoey** [comment]
@nic-chen there are two plugins in : `cors` and `echo`. The following screenshot could be illustrated on that.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/2542401/103618058-4b192980-4f6a-11eb-8680-aa11db0aeb1b.png">

**Comment by nic-chen** [comment]
I know the difference between the two data. what are the steps to reproduce?

**Comment by imjoey** [comment]
Sorry not provide the reproduce steps:

- Create two plugins on the `Plugin List` page
- Use `curl http://manager-api:9000/apisix/admin/global_rules` to fetch the global rule list

**Comment by juzhiyuan** [comment]
@imjoey Hello,  the frontend will ALWAYS use one fixed id as global_rule id, using `1` currently.

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/blob/master/web/src/constants.ts#L35

**Comment by nic-chen** [comment]
@imjoey   can't reproduce on my side.. could you provide more detail, please ? thanks.

**Comment by juzhiyuan** [comment]
@imjoey How about using `DEFAULT_GLOBAL_RULE_ID` as that rule's id?

**Comment by nic-chen** [comment]
Sorry, It's not a problem with the returned data, just about data format. 

The logic of this is really different, you could have a look the proposal:
https://github.com/apache/apisix-dashboard/issues/820

**Comment by imjoey** [comment]
> Sorry, It's not a problem with the returned data, just about data format.
> 
> The logic of this is really different, you could have a look the proposal:
> #820

@juzhiyuan @nic-chen Thank you guys for the explanations. This issue is proposed only to have a confirm that if the data format is as expected. Very happy to see everything works fine.

> @imjoey How about using `DEFAULT_GLOBAL_RULE_ID` as that rule's id?

Since I've understand the data format, so I guess `1` is also OK for me. 😄 

I would close this issue, much appreciated.
