### ISSUE TITLE
The process of creating routes using dashboard needs improvement

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#1213]
# Bug report

Now, upstream is necessary when using dashboard to create a route. If service is selected, the user needs to fill in upstream twice, which is unreasonable. I drew a flowchart to express what I mean.

![image](https://user-images.githubusercontent.com/7396835/103635666-d2bf6200-4f83-11eb-9556-3e874309b1ab.png)

**Comment by juzhiyuan** [comment]
This is not a bug IMHO...
