### ISSUE TITLE
bug: module 'resty.radixtree' not found when call command `http://schema-sync.sh/`

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1216]
original comment: https://github.com/api7/lua-resty-radixtree/issues/87

ping @qwxingzhe

**Comment by juzhiyuan** [comment]
Please check ASAP to see if this issue should be fixed in M2.3

**Comment by starsz** [comment]
OK. I had found the reason. Let me fix it.

**Comment by imjoey** [comment]
@starsz @juzhiyuan I'm afraid that this issue has not been completely fixed. With the latest code from master branch, I still got the following errors:

```
lua: ./apisix/init.lua:24: module 'resty.ngxvar' not found:
```

and 

```
lua: ./apisix/plugins/traffic-split.lua:21: module 'resty.roundrobin' not found:
```

After I added these two missing module names into `fake_module_list` variable. Everything works fine. So please have a check, if it's a bug,  I would commit a PR to fix that. Thanks.
