### ISSUE TITLE
support debug file transfer in online debug

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#1217]
# Feature request

## Please describe your feature

In the process of solving #1196, I found that the current online debug does not support debugging file transfer. It would be better to support this feature since APISIX support it.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/2561857/103676650-4e3d0580-4fbc-11eb-9d88-3d7685c00221.png)

I would like to implement this feature in form of request forwarding the `Content-type: multipart/form-data`, just refer to postman.

**Comment by liuxiran** [comment]
a TODO feature, reopen now

**Comment by Jaycean** [comment]
@liuxiran @juzhiyuan I can help with the BE, please assign to me ,Thks.
