### ISSUE TITLE
fe: remove npm mirror from taobao

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1223]
# Feature request

## Please describe your feature

Some dependencies are using taobao as npm mirror, we have to remove them from yarn.lock.

**Comment by imjoey** [comment]
Nice catch. Good for non-Chinese users worldwide. 👍  Chinese users should have their own settings on mirror if needed. 😄

**Comment by bzp2010** [comment]
* A good way to use [npmjs](https://www.npmjs.org) as modules repository.
* At the same time, we may use webpack external to separate some main modules (such as React) from the compiled products and load them from CDNs such as [jsdelivr](https://www.jsdelivr.com/), which will reduce the size of the compiled products (managed by configuration).
