### ISSUE TITLE
The API for fetching all plugins should return `disable` property

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1227]
# Feature request

## Please describe your feature

The data from `plugins?all=true`, only part of the data contains a `disable` property, so the FE has to hack codes.

https://github.com/apache/apisix-dashboard/blob/master/web/src/components/Plugin/PluginDetail.tsx#L62-L74

**Comment by juzhiyuan** [comment]
cc @nic-chen 

High Priority

**Comment by nic-chen** [comment]
Add the disable attribute to the schema of all plugins? Or should the manager api do this hack? What is your opinion? Thanks. @juzhiyuan 

What do you think is better? Thanks. @membphis @spacewander

**Comment by juzhiyuan** [comment]
Because I see that a part of plugins have that property, and others don't have :( little curious

**Comment by spacewander** [comment]
@juzhiyuan 
It is expected that the property is injected into each plugin. Which plugins have that property and which don't?

**Comment by juzhiyuan** [comment]
`apisix/admin/plugins?all=true`

![image](https://user-images.githubusercontent.com/2106987/104418821-7cb97280-55b2-11eb-95a3-ca939e51dac5.png)

![image](https://user-images.githubusercontent.com/2106987/104418829-804cf980-55b2-11eb-8e1d-f5c64c939070.png)

**Comment by juzhiyuan** [comment]
@nic-chen anything we need to do for this issue?

**Comment by nic-chen** [comment]
> @nic-chen anything we need to do for this issue?

oh, we need to sync the schema to dashboard since the PR has been merged.

**Comment by juzhiyuan** [comment]
ok, reop
