### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by belongwqz** [apache/apisix-dashboard#1233]
# Bug report

## Describe the bug

docker build fail when build manager-api

## How to Reproduce

1. `docker build -t apisix-dashboard:2.2 --build-arg APISIX_DASHBOARD_VERSION=v2.2 .` or `docker build -t apisix-dashboard:2.2 --build-arg ENABLE_PROXY=true --build-arg APISIX_DASHBOARD_VERSION=v2.2 .`
2. when get to the "**build manager-api**" step, it fails.
3. error log is:`
go: github.com/api7/go-jsonpatch@v0.0.0-20180223123257-a8710867776e: Get "https://proxy.golang.org/github.com/api7/go-jsonpatch/@v/v0.0.0-20180223123257-a8710867776e.mod": dial tcp 172.217.25.17:443: i/o timeout
The command '/bin/sh -c go env -w GO111MODULE=on     && CGO_ENABLED=0 go build -o ../output/manager-api .' returned a non-zero code: 1
`
4. The reason is the `github.com/api7/go-jsonpatch@v0.0.0-20180223123257-a8710867776e` doesn't exist any more.

## Expected behavior

Docker build apisix-dashboard success.

## Screenshots

NA.

## System information

- OS: Linux
- Version: 2.2

## Additional context

NA.

**Comment by imjoey** [comment]
@belongwqz thanks for reporting. We will check ASAP.

**Comment by juzhiyuan** [comment]
cc @idbeta

**Comment by starsz** [comment]
Hi, @belongwqz. Do you use the apisix-docker project?

**Comment by belongwqz** [comment]
> Hi, @belongwqz. Do you use the apisix-docker project?

I have tried both with the same result.

**Comment by belongwqz** [comment]
I switch the `golang:1.14` image to `golang:1.15` and `ENABLE_PROXY`(only for go build), then it's OK, sorry to trouble, maybe it's something about my development environment.
