### ISSUE TITLE
Cannot read property 'upstream_id' of undefined

### ISSUE THREAD

**Issue by LLLLimbo** [apache/apisix-dashboard#1234]
1.  I added a route in this way
`curl --location --request PUT 'http://192.168.2.102:9080/apisix/admin/routes/1' \
--header 'Content-Type: application/json' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--data-raw '{
    "uri": "/car/*",
    "upstream": {
        "service_name": "SEEINER-CAR",
        "type": "roundrobin",
        "discovery_type": "eureka"
    }
}'`

2. Then I  tried to edit the route's name in dashboard. Finally I got this:
![image](https://user-images.githubusercontent.com/31607003/103861326-3b2f5000-50f8-11eb-8c3b-74015d689f2a.png)

I think, maybe dashboard does not support upstreams  fetched from  registery center like eureka at the moment ?

**Comment by juzhiyuan** [comment]
Will be resolved by https://github.com/apache/apisix-dashboard/issues/1234
