### ISSUE TITLE
bug: Online Debug can not use key-value to enter the integer params

### ISSUE THREAD

**Issue by fukiki** [apache/apisix-dashboard#1236]
# Bug report

## Describe the bug

When Online Debug, using key-value to enter `Header Params`, the params validation failed.
![apisix-bug1](https://user-images.githubusercontent.com/59835099/103863127-391ac080-50fb-11eb-97ba-ba15e96c91f3.png)

I enable plugin `request-validation`, the headers and body data will be validated. The schema for request-validation plugin is as follows:
```json
{
  "disable": false,
  "header_schema": {
    "properties": {
      "timeouts": {
        "default": 3,
        "maximum": 254,
        "minimum": 1,
        "type": "integer"
      }
    },
    "required": [
      "required_payload"
    ],
    "required_payload": {
      "type": "string"
    },
    "type": "object"
  }
}
```

## How to Reproduce

1. Go to 'Route'
2. Click on 'Online Debug'
3. Input Params: 
- URL:`GET http://127.0.0.1:9080/headers`
- Header Params: `{"required_payload":"test payload", "timeouts":10}`
- Body Params: `{"boolean-payload":true,"required_payload":"hello"}`
4. See error: `property "timeouts" validation failed: wrong type: expected integer, got string`

## Expected behavior

In step 4: Request successful, response body is as follow:
```json
{
    "headers": {
        "Accept-Encoding": "gzip",
        "Host": "127.0.0.1",
        "Required-Payload": "test payload",
        "User-Agent": "Go-http-client/1.1",
        "X-Amzn-Trace-Id": "Root=1-5ff6ae93-0a2dd616262bf298084de7dd",
        "X-Forwarded-Host": "127.0.0.1"
    }
}
```

## System information

- OS: macOS, centos
- Browser：Chrome
- Version: master branch

## Additional context

It has the same problem using `json` to enter Body Params, but  using`raw input - json` is ok.

**Comment by liuxiran** [comment]
Thanks for your report.

There are two parts params validation can be defined in `request-validation`  plugin, one is the header params, another is body params.

> The header fields are transmitted after the request line (in case of a request HTTP message) or the response line (in case of a response HTTP message), which is the first line of a message. Header fields are colon-separated key-value pairs in clear-text string format, terminated by a carriage return (CR) and line feed (LF) character sequence. (Quoted from [wiki](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields) )

Refer to the header params descriptions, we could only pass string values to headers, so IMHO,  @fukiki you would better modify your configuration mentioned in the issue.

And for the body field, actually we can defiine any supported type to the property, that is a bug for online debug, I have modified, after the pr megerd, you can edited your json body in 

![mmexport1610532215693](https://user-images.githubusercontent.com/2561857/104437509-d11c1c80-55c9-11eb-887a-3caa6db96cb3.jpg)

that is a also a way postman used.

Hope this solution can help you, and welcome any feedback, thanks.

**Comment by juzhiyuan** [comment]
good good
