### ISSUE TITLE
sync plugins' testcases from apisix automatically

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1238]
# Feature request

## Please describe your feature

We use the dataset[1] to store plugins' valid and invalid data for the frontend's Plugin E2E test, we would better use the shell to automatically update this dataset from apisix[2] instead of updating by hand.

[1] https://github.com/apache/apisix-dashboard/blob/master/web/cypress/fixtures/plugin-dataset.json
[2] https://github.com/apache/apisix/tree/master/t/plugin

## Note
1. `response-rewrite` is handled by APISIX separately https://github.com/apache/apisix/blob/master/t/plugin/response-rewrite.t#L317-L340;
2. `Zipkin` is skipped from APISIX https://github.com/apache/apisix/blob/master/t/plugin/zipkin.t#L49-L68;

**Comment by juzhiyuan** [comment]
Do we have any solutions to export those Lua test cases to JSON?

cc @spacewander @tokers

**Comment by spacewander** [comment]
Since most of plugins use jsonschema to do validation, we only need to handle a few plugin?

**Comment by juzhiyuan** [comment]
The Dashboard maintains a dataset[1] to ensure the plugin editor could validate as expected 🤣

[1] https://github.com/apache/apisix-dashboard/blob/master/web/cypress/fixtures/plugin-dataset.json

**Comment by juzhiyuan** [comment]
Hi @spacewander @starsz, do we have any quick ideas to export those test cases from Lua?

**Comment by spacewander** [comment]
I don't any idea unless we modify the code of APISIX and dump the data we used.

**Comment by juzhiyuan** [comment]
all right, ping @membphis @nic-chen, any ideas about this feature?

It seems a little cumbersome, if we could resolve this issue, there has no need to sync the dataset by hand anymore. But if we couldn't handle it easily and smoothly, we have to sync the dataset by hand.

**Comment by membphis** [comment]
> Hi @spacewander @starsz, do we have any quick ideas to export those test cases from Lua?

I do not have a good idea for this job :(
