### ISSUE TITLE
chore: change the type of `ExpectBody`  to []string in backend e2e test

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1246]
# Feature request

## Please describe your feature

Hi, now the type of `ExpectBody` is `string` in the backend e2e test. 
See: https://github.com/apache/apisix-dashboard/blob/40d8f97de8770187599ff5963617049603020e92/api/test/e2e/base.go#L177

Sometimes we need to check multiple strings (such as the list function) in the response body. So I recommend changing the type of `ExpectBody` to `[]string`.

## Describe the solution you'd like

Change the type of `ExpectBody` to `[]string`.

**Comment by starsz** [comment]
Maybe change it into interface{}, and we can judge the type of it.
If the type is `string`, just check it.
If the type is `[]string`, and we need to traverse it.

**Comment by imjoey** [comment]
@starsz just want to make sure, does the `ExpectBody` of `[]string` type indicate that the response body equals to one of the items within this string array?

**Comment by starsz** [comment]
Hi, @imjoey, every item in []string should be contained in response body.

**Comment by imjoey** [comment]
> Hi, @imjoey, every item in []string should be contained in response body.

@starsz got you. the `interface{}` type is better, since it will keep the backward compatibility. Shall we also make the same change for the `Unexpected` field?

**Comment by starsz** [comment]
> > Hi, @imjoey, every item in []string should be contained in response body.
> 
> @starsz got you. the `interface{}` type is better, since it can guarantee the backward compatibility. Shall we also make the same change for the `UnexpectedBody` field?

Good idea.We shoud.

**Comment by imjoey** [comment]
> > > Hi, @imjoey, every item in []string should be contained in response body.
> > 
> > 
> > @starsz got you. the `interface{}` type is better, since it can guarantee the backward compatibility. Shall we also make the same change for the `UnexpectedBody` field?
> 
> Good idea.We shoud.

@starsz  pls assign this to me, if no one has taken. Thanks.

**Comment by imjoey** [comment]
@starsz @juzhiyuan thank you guys very much.
