### ISSUE TITLE
release workflow

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1262]
**Workflow[1]** 

http://processon.com/chart_image/5ffbd7e707912914e7e0ab17.png

[1] https://www.processon.com/view/link/5ffbdad81e0853437c3a846d

**Comment by juzhiyuan** [comment]
cc @imjoey

**Comment by imjoey** [comment]
@juzhiyuan @nic-chen @liuxiran 

The recommended mode from me  for this project from me, is to adept the **Gitlab flow**, especially the **Release branches with GitLab flow** [[1]] . I've updated the chart on  [[2]].  Any feedback is welcome.



[1]: https://docs.gitlab.com/ee/topics/gitlab_flow.html#release-branches-with-gitlab-flow
[2]: https://www.processon.com/diagraming/5ffbd7e707912914e7e0ab14

**Comment by liuxiran** [comment]
> @juzhiyuan @nic-chen @liuxiran
> 
> The recommended mode from me for this project, is to adapt the **Gitlab flow**, especially the **Release branches with GitLab flow** [[1](https://docs.gitlab.com/ee/topics/gitlab_flow.html#release-branches-with-gitlab-flow)] . I've updated the chart on [[2](https://www.processon.com/diagraming/5ffbd7e707912914e7e0ab14)]. The practice is from previous collaborations with Red Hat engineers working on oVirt and Ansible projects. Any feedback is welcome.

the new updated image could not be viewed due to the permission, it would be better to updated again

**Comment by imjoey** [comment]
> @juzhiyuan @nic-chen @liuxiran
> 
> The recommended mode from me for this project, is to adapt the **Gitlab flow**, especially the **Release branches with GitLab flow** [[1](https://docs.gitlab.com/ee/topics/gitlab_flow.html#release-branches-with-gitlab-flow)] . I've updated the chart on [[2](https://www.processon.com/view/link/5ffbdad81e0853437c3a846d)]. The practice is from previous collaborations with Red Hat engineers working on oVirt and Ansible projects. Any feedback is welcome.

@juzhiyuan 

One more thing, we need to protect `master` and all the release branches. It will prevent these branches from force-pushing or deleting by accident. 😄

**Comment by liuxiran** [comment]
LGTM, let's wait for others' suggestions.

cc @membphis @moonming @spacewander

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/104160279-d2afde00-542b-11eb-922c-5bb8514cec3b.png)

This workflow looks good to me indeed!!!

> we need to protect master and all the release branches

Fine, I need to file a ticket to Infra for all branches start with `v2.x`, then every release branch would get protected. Need some time.

**Comment by membphis** [comment]
> This workflow looks good to me indeed!!!

LGTM too

**Comment by juzhiyuan** [comment]
Fine, @imjoey could you please add this workflow to some documentation, like contributing or release-guide?

**Comment by imjoey** [comment]
> Fine, @imjoey could you please add this workflow to some documentation, like contributing or release-guide?

@juzhiyuan very glad to add relevant docs. May I ask that in which repository I should put it?

**Comment by nic-chen** [comment]
LGTM too.

It looks similar to what was discussed before. Are there something that need special attention? Thanks.

**Comment by juzhiyuan** [comment]
@imjoey Here are 2 repos that could cover this requirement:

- https://github.com/apache/apisix-website
- https://github.com/apache/apisix-dashboard

I would prefer the `website` 🤔

**Comment by imjoey** [comment]
> LGTM too.
> 
> It looks similar to what was discussed before. Are there something that need special attention? Thanks.

Hi @nic-chen , IMHO, we should pay more attention to the following two things:

- During the release time window, keep a close eye on every new PR and issue, as maintainers need to decide if it should be within the present release. If yes, relevant PR needs to be attached with a `need backport` label and then back port to release branch. Meanwhile, the issue should also be marked with proper milestone for tracking.
- Consider the release branch as important as master. Once creating the release branch by forking from master (also called pre-release step), we need to provide necessary CI environments for it. After release (also called post-release step), we also need to add CHANGLOG back to master branch, indicating the announcement of the new release.

**Comment by imjoey** [comment]
> @imjoey Here are 2 repos that could cover this requirement:
> 
> * https://github.com/apache/apisix-website
> * https://github.com/apache/apisix-dashboard
> 
> I would prefer the `website` 🤔

@juzhiyuan My opinion is also `website`. 😄

**Comment by nic-chen** [comment]
> > LGTM too.
> > It looks similar to what was discussed before. Are there something that need special attention? Thanks.
> 
> Hi @nic-chen , IMHO, we should pay more attention to the following two things:
> 
> * During the release time window, keep a close eye on every new PR and issue, as maintainers need to decide if it should be within the present release. If yes, relevant PR needs to be attached with a `need backport` label and then back port to release branch. Meanwhile, the issue should also be marked with proper milestone for tracking.
> * Consider the release branch as important as master. Once creating the release branch by forking from master (also called pre-release step), we need to provide necessary CI environments for it. After release (also called post-release step), we also need to add CHANGLOG back to master branch, indicating the announcement of the new release.

thanks very much for  the explanation.

**Comment by imjoey** [comment]
@juzhiyuan Regarding to tag `v2.3`, I'm still curious about shall we need to revert `branch v2.3` and `tag v2.3` to commit https://github.com/apache/apisix-dashboard/commit/d518b477b7d5e506ae124283aeb7cedb05027dc1 , cause it's the code generating the assets of 2.3 release. The latest commits can be put into v2.3.1 then, if any.  😄

**Comment by juzhiyuan** [comment]
🤔 sure, let me force push to the target commit, and please help to cherry-pick needed commits to 2.3 (if needed).

**Comment by imjoey** [comment]
@juzhiyuan Since https://github.com/apache/apisix-website/pull/143 has been merged, could this be closed now? We can reopen it if anything in the docs needs improvement. Thanks.
