### ISSUE TITLE
use apisix-docker to manage Dockerfile

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1265]
# Feature request

## Please describe your feature

Use the `apisix-docker` repo to manage Dockerfile and documentation.

**Comment by starsz** [comment]
Agree +1.
And we should introduce this in README.md like apisix.

**Comment by gxthrj** [comment]
I will do this feature next week, and modify readme.

**Comment by nic-chen** [comment]
ping @gxthrj

**Comment by gxthrj** [comment]
ref to https://github.com/apache/apisix-docker/pull/150

**Comment by gxthrj** [comment]
But still need to update README.

**Comment by nic-chen** [comment]
> ref to [apache/apisix-docker#150](https://github.com/apache/apisix-docker/pull/150)

@gxthrj  That is just adding dashboard in docker-compose example..

**Comment by starsz** [comment]
> > ref to [apache/apisix-docker#150](https://github.com/apache/apisix-docker/pull/150)
> 
> @gxthrj That is just adding dashboard in docker-compose example..

Yes. @gxthrj Can you help to create a dockerfile in apisix-docker to manage the apisix-dashboard.

**Comment by gxthrj** [comment]
Thanks for remind, will add a dockerfile for dashboard in apisix-docker repo.
