### ISSUE TITLE
build docker image failed for v2.3

### ISSUE THREAD

**Issue by logan2013** [apache/apisix-dashboard#1268]
# Bug report

## Describe the bug

docker build failed for v2.3

## How to Reproduce

1. Switch to branch v2.3
2. build
```shell
$ export APISIX_DASHBOARD_VERSION=v2.3
$ docker build -t world/apisix-gw-dashboard:${APISIX_DASHBOARD_VERSION} . --build-arg ENABLE_PROXY=true --build-arg APISIX_DASHBOARD_VERSION=${APISIX_DASHBOARD_VERSION}
```

## Expected behavior

success build docker image

## Screenshots

![image](https://user-images.githubusercontent.com/5728244/104165046-caf43780-5433-11eb-9962-9309bafdcf04.png)

## System information

- OS: centos 7
- docker: Docker version 19.03.2, build 6a30dfc

**Comment by nic-chen** [comment]
@logan2013 

In branch v2.3, it's 
```sh
go build -o ../output/manager-api ./cmd/manager
```
not
```sh
go build -o ../output/manager-api .
```
please see:
https://github.com/apache/apisix-dashboard/blob/v2.3/Dockerfile#L47-L48

please check that you are using the right code.  thanks.

**Comment by logan2013** [comment]
@nic-chen thanks. I think that's because my Dockfile is wrong
