### ISSUE TITLE
How to deploy with RPM?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1269]
# Feature request

## Please describe your feature

Dashboard v2.3 now supports deployment with RPM[1], we need to improve README and related docs.

[1] https://github.com/apache/apisix-dashboard/releases/tag/v2.3

**Comment by juzhiyuan** [comment]
cc @idbeta

**Comment by idbeta** [comment]
> cc @idbeta

No problem, I will submit a PR to introduce this.
