### ISSUE TITLE
当Route中存在被禁用的插件时Service里的同名插件失效

### ISSUE THREAD

**Issue by belongwqz** [apache/apisix-dashboard#1279]
# Bug report

## Describe the bug

当Route中存在被禁用的插件时Service里的同名插件失效。

## How to Reproduce

1. 创建一个Service SRV-A，启用basic-auth插件
2. 创建一个Route ROUTE-A，关联上第一部的SRV-A，启用basic-auth插件
3. 创建一个Consumer，配置basic-auth的账号和密码
4. 编辑ROUTE-A，将其之前启用的basic-auth插件禁用
5. 根据ROUTE-A访问应用时basic-auth失效，因为etcd中对应route配置有{"plugins": {"basic-auth":{"disable": true}}}的配置，且Route里的同名插件basic-auth优先级高于其对应的Service插件。
6. 手工编辑ROUTE-A在etcd里的配置，将其“basic-auth”删除（不仅是disable），再次据ROUTE-A访问应用则basic-auth生效

## Expected behavior

根据ROUTE-A访问应用时basic-auth生效

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

## Additional context

建议在配置插件时不仅仅将其enable或者disable，还需要提供**删除插件**的功能。

**Comment by nic-chen** [comment]
I think this is normal. The only problem is that the FE needs to provide the feature of deleting a plugin. 
@LiteSun @juzhiyuan

**Comment by juzhiyuan** [comment]
Route is higher than Service IMO, even if it's disabled.

@membphis, what's your opinion?

**Comment by membphis** [comment]
> Route is higher than Service IMO, even if it's disabled.

you are right. 

@belongwqz for your case, you need to delete the plugin in route first.

**Comment by belongwqz** [comment]
> > Route is higher than Service IMO, even if it's disabled.
> 
> you are right.
> 
> @belongwqz for your case, you need to delete the plugin in route first.

I agree, but now the problem is that we need a button to performs the `delete plugin` action on the dashboard.

**Comment by membphis** [comment]
@juzhiyuan Do you have any advice?

**Comment by LiteSun** [comment]
IMO, Remove plug-in functionality needs to be added
Interface interaction issues need to be discussed
- When will the delete button be displayed?
- Should the delete button be placed in the card or the drawer?

**Comment by LiteSun** [comment]
High priority. @LiteSun

**Comment by juzhiyuan** [comment]
I would prefer placing the Delete button outside the Drawer:

1. In the GlobalPlugin list, we could directly delete that plugin;
2. In the Service/Route/Consumer module, we could delete one plugin by clicking the button on Card.

**Comment by LiteSun** [comment]
> I would prefer placing the Delete button outside the Drawer:
> 
> 1. In the GlobalPlugin list, we could directly delete that plugin;
> 2. In the Service/Route/Consumer module, we could delete one plugin by clicking the button on Card.

Agree with you. What do you think?? cc @nic-chen @liuxiran

**Comment by liuxiran** [comment]
> I would prefer placing the Delete button outside the Drawer:
> 
> 1. In the GlobalPlugin list, we could directly delete that plugin;
> 2. In the Service/Route/Consumer module, we could delete one plugin by clicking the button on Card.

Agree with placing the Delete button outside the Drawer too.


There is still a detail I want to confirm:

> In the Service/Route/Consumer module, we could delete one plugin by clicking the button on Card.

this means we need to add button something called `Delete` together with the `Enable` button on the Card right? If so, maybe the name of `Enable` button need to change at the same time, because `Enable` may be misinterpreted as `enable the plugin` IMHO.

**Comment by juzhiyuan** [comment]
ya, actually, it's `Configured` and `Not configured`, and `configured` means `disable` or `enable`.

**Comment by moonming** [comment]
any PR for this?

**Comment by juzhiyuan** [comment]
no, I will take this.
