### ISSUE TITLE
Switch Language doesn't work 🤔 

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1290]
# Bug report

## Describe the bug

The Language Switcher[1] doesn't work as expected 🤔 

cc @guoqqqi Please take a look

[1] http://139.217.190.60/consumer/list

**Comment by juzhiyuan** [comment]
Still not working 🤔

**Comment by liuxiran** [comment]
related issue: https://github.com/umijs/umi/issues/5974

**Comment by juzhiyuan** [comment]
@guoqqqi Once this issue is fixed, please add related test case.

**Comment by juzhiyuan** [comment]
@guoqqqi Test!
