### ISSUE TITLE
test(fe): add e2e test for online debug

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#1291]
# Feature request

## Please describe your feature

as mentioned in https://github.com/apache/apisix-dashboard/pull/1287#pullrequestreview-567116648 and https://github.com/apache/apisix-dashboard/pull/1239#issuecomment-755963097, we need to add e2e test cases to online debug.

**Comment by liuxiran** [comment]
according to this comment: https://github.com/apache/apisix-dashboard/pull/1326#discussion_r560013791

in fact, the original purpose of `online debug` is to debug routes published on APISIX, so if I want to test whether the function is correct, I need to run APISIX together with the fontend-e2e-test.

I have two solutions:

1. only test whether the ui is corrent, and do not take care of the funciton.
2. upate fontend-e2e-test.yml, run APISIX together with the fe e2e ci.

which one do you perfer? 

cc @juzhiyuan @LiteSun @nic-chen

**Comment by juzhiyuan** [comment]
I would prefer:
1. UI is correct;
2. JS functionalities are correct;

We don't need to run APISIX for now 🤔

**Comment by LiteSun** [comment]
How about using the [cypress intercept](https://docs.cypress.io/api/commands/intercept.html#Waiting-on-a-request) function to check if the request is correct. 🤔

**Comment by juzhiyuan** [comment]
😂

like 

```js
expect(request.body).toBe({a: "b"})
```

**Comment by liuxiran** [comment]
Thanks for the instruction which teach me how to use `cypress intercept`, it will be very useful to write this test spec. @juzhiyuan @LiteSun 

and if we did not run APISIX, my test object is not a route published on the APISIX, it becomes an accessible request, actually that also makes sense.

**Comment by juzhiyuan** [comment]
fine
