### ISSUE TITLE
route vars support IN operator

### ISSUE THREAD

**Issue by belongwqz** [apache/apisix-dashboard#1293]
# Feature request

## Please describe your feature

route vars support `IN` operator, in etcd it will like:
```
"vars": [["http_host","IN",["host1","host2"]]]
```
apisix project already support this feature #[3123](https://github.com/apache/apisix/issues/3123)

## Describe alternatives you've considered

Currently, I have to create two routes with same config except vars: `"vars": [["http_host","==","host1"]]]` and `"vars": [["http_host","==","host2"]]]`

**Comment by juzhiyuan** [comment]
@LiteSun Please take a look at this issue, and leave some steps to achieve this issue. Then @belongwqz would you like to implement this issue?

**Comment by belongwqz** [comment]
> @LiteSun Please take a look at this issue, and leave some steps to achieve this issue. Then @belongwqz would you like to implement this issue?

My most familiar stack is around python, so I can't do it now.

**Comment by juzhiyuan** [comment]
all right, we will support this feature in M2.4[1]

[1] https://github.com/apache/apisix-dashboard/milestone/10
