### ISSUE TITLE
request help: traffic-split plugin does not work

### ISSUE THREAD

**Issue by htwdjqr** [apache/apisix-dashboard#1294]
### Issue description
traffic-split plugin does not work.

```json
traffic-split config:
{
  "disable": false,
  "traffic-split": {
    "rules": [{
      "match": [{
        "vars": [
          [
            "http_release",
            "==",
            "new_release"
          ]
        ]
      }],
      "weighted_upstreams": [{
        "upstream": {
          "name": "upstream_A",
          "nodes": {
            "192.168.100.21:8002": 10
          },
          "type": "roundrobin"
        }
      }]
    }]
  }
}
```

request like this:
![企业微信截图_16105345164716](https://user-images.githubusercontent.com/26807197/104441752-0f680a80-55cf-11eb-8485-65ce94aab657.png)

### Environment

* apisix version (cmd: `apisix version`):2.2
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by htwdjqr** [comment]
config like this,It works.
thanks. @nic-chen @Firstsawyou 

{
	"rules": [{
		"match": [{
			"vars": [
				[
					"http_release",
					"==",
					"new_release"
				]
			]
		}],
		"weighted_upstreams": [{
			"upstream": {
				"name": "upstream_A",
				"nodes": {
					"192.168.100.21:8002": 10
				},
				"type": "roundrobin"
			}
		}]
	}]
}

**Comment by juzhiyuan** [comment]
@nic-chen Please update this issue's status, done or still need to be resolved 🤔

**Comment by Firstsawyou** [comment]
> "plugins": {
> "traffic-split": {
> "disable": false,
> "traffic-split": {
> "rules": [{
> "match": [{

It may be caused by two `tarffic-split` names.

**Comment by nic-chen** [comment]
@Firstsawyou 

I check the schema for plugin `traffic-split`, it doesn't have `additionalProperties = false` to limit config, could we add this limit ? so that we could  prompt error when config invalid.

**Comment by Firstsawyou** [comment]
> @Firstsawyou
> 
> I check the schema for plugin `traffic-split`, it doesn't have `additionalProperties = false` to limit config, could we add this limit ? so that we could prompt error when config invalid.

Agree, we need to add it.

**Comment by Firstsawyou** [comment]
> > @Firstsawyou
> > I check the schema for plugin `traffic-split`, it doesn't have `additionalProperties = false` to limit config, could we add this limit ? so that we could prompt error when config invalid.
> 
> Agree, we need to add it.

I will submit a pr to add it later.
