### ISSUE TITLE
after editing a Service, the upstream info will be lost.

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1299]
# Bug report

## Describe the bug

![image](https://user-images.githubusercontent.com/2106987/104589683-36910b80-56a5-11eb-92f2-17d224a6ba66.png)

## How to Reproduce

1. Go to Service List;
2. Find a Service and click on Edit;
3. Update Upstream configuration;
4. Submit;
5. Edit again but without upstream configuration.

## System information

- Version: master branch

**Comment by juzhiyuan** [comment]
cc @guoqqqi

**Comment by LiteSun** [comment]
ping
