### ISSUE TITLE
Doc: a better doc about how to write and run e2e test and unit test for Backend

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#1303]
# Feature request

## Please describe your feature

Recently when my partners and I tried to finish the the issues of backend, we always found troubles in writting unit test cases and e2e test cases. I have to say the big reason is that we are not skilled enough with the current testing framework, it would be better to add a detailed documentation to guide the newcomer on how to start writting  test cases and local debugging.

## Describe the solution you'd like

add a `backend-test.md`

**Comment by juzhiyuan** [comment]
cc @nic-chen @starsz

**Comment by starsz** [comment]
@liuxiran Thanks for your advice. I think we should add a doc after those issues were solved:

1. remove the etcd dependency in the unit test #1161 
2. use ginko framework in e2e test #1136 

Then we can add a doc to introduce how to write the test for backend.

**Comment by liuxiran** [comment]
> @liuxiran Thanks for your advice. I think we should add a doc after those issues were solved:
> 
> 1. remove the etcd dependency in the unit test #1161
> 2. use ginko framework in e2e test #1136
> 
> Then we can add a doc to introduce how to write the test for backend.

Got it,  thanks a lot @starsz, waiting for the right timing~

**Comment by Jaycean** [comment]
Looking forward to the documentation, new developers have a headache writing unit tests and E2E tests, such as me.
But now I've learned a few ways.
Documentation can help other developers.

**Comment by bisakhmondal** [comment]
Hey guys!! Interested in working on this issue. Could you please elaborate, how do we wish to help the newcomer? 
for eg.
1. Currently the environment setup with docker-compose is not elaborative (`back-end-e2e.md`), I am thinking of updating along with adding a bash script to automate the workflow.

2. For unit testing, we are using golang's native testing framework (that includes working with mockInterfaces, I think which needs some explanation) & for e2e, how should we introduce that into docs about the ginkgo stuff for the new?

Please share your thoughts. Thank you :)

**Comment by juzhiyuan** [comment]
cc @nic-chen @starsz to help @bisakhmondal

**Comment by nic-chen** [comment]
hi, @bisakhmondal  

Thanks for working on this issue!

> Currently the environment setup with docker-compose is not elaborative (back-end-e2e.md), I am thinking of updating along with adding a bash script to automate the workflow.

that's great.

> For unit testing, we are using golang's native testing framework (that includes working with mockInterfaces, I think which needs some explanation) & for e2e, how should we introduce that into docs about the ginkgo stuff for the new?

About unit testing, I think mocking and how to run tests are two points that need to be described clearly.
About e2e testing, just point out that the ginkgo framework should be used to write cases.

Other details, I think you could write according to your thoughts. 
The more detailed the better, especially you have just participated in the development of the dashboard not long ago, it is easier to consider the content that newcomers want to know more.  : )

**Comment by bisakhmondal** [comment]
Thank you for addressing this. Sure, I'll definitely put down the information as much elaborative as I can.
