### ISSUE TITLE
make build2.3版本的时候cypress和node-pty无法下载；显示二进制文件过大。Expected downloaded file to have size: 203515894 Computed size: 9120117

### ISSUE THREAD

**Issue by admin-xl-2048** [apache/apisix-dashboard#1305]
# Feature request

## Please describe your feature

A clear and concise description of what you want and what your use case is.

**Comment by juzhiyuan** [comment]
Hi, this issue is fixed in the master branch. You could simply do this patch[1] for your codes.

[1] https://github.com/apache/apisix-dashboard/commit/93b9765e3e77c6cefe0487e1657886d5f05d4146#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R39

**Comment by admin-xl-2048** [comment]
非常感谢，按照这个方法我已经解决掉了。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix-dashboard"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 下午3:12
收件人:&nbsp;"apache/apisix-dashboard"<apisix-dashboard@noreply.github.com&gt;;
抄送:&nbsp;"1004860942"<1004860942@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/apisix-dashboard] make build2.3版本的时候cypress和node-pty无法下载；显示二进制文件过大。Expected downloaded file to have size: 203515894 Computed size: 9120117 (#1305)





 
Hi, this issue is fixed in the master branch. You could simply do this patch[1] for your codes.
 
[1] 93b9765#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R39
