### ISSUE TITLE
FE: save List page's meta status

### ISSUE THREAD

**Issue by to2false** [apache/apisix-dashboard#1313]
# Bug report

## Describe the bug

when I select 50 per page and refresh the page, it changes back to 20 per page

## How to Reproduce

1. select 50 per page
2. refresh page
3. still 20 per page

## Expected behavior

when I select 50 per page and refresh the page, it keeps 50 per page.

## System information

- OS: [macOS]
- Browser (if applies) [Chrome]
- Version: [2.3]

**Comment by juzhiyuan** [comment]
It's not a bug, it's a feature.

We could use queryString to save status like page, pageSize, etc. Welcome PR to enhance this, ping me if there has any problems.

**Comment by juzhiyuan** [comment]
ping @guoqqqi
