### ISSUE TITLE
bug: non-json data causes error logs

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1329]
# Bug report

## Describe the bug

json parse failed log in error.log

## How to Reproduce

1. start Manager API (new installation)
2. start APISIX (new installation)

## Expected behavior

no error log

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3] master

## Additional context

first time installation and start APISIX after the Manager API started.

**Comment by starsz** [comment]
@nic-chen Sorry, I don't get your point. Can you give more info about this?

**Comment by tokers** [comment]
@nic-chen Any examples?

**Comment by nic-chen** [comment]
![image](https://user-images.githubusercontent.com/33000667/105200809-2e404100-5b7b-11eb-889b-7b70a2c74bae.png)

@tokers @starsz

**Comment by imjoey** [comment]
@nic-chen I'm afraid I cannot reproduce in my environment. Is the etcd also newly installed? I guess there's something wrong with the data in etcd. So could you please have a try to run `etcdctl del "/apisix" --prefix && apisix init && apisix init_etcd` to reinitialize the etcd?

**Comment by nic-chen** [comment]
> @nic-chen I'm afraid I cannot reproduce in my environment. Is the etcd also newly installed? I guess there's something wrong with the data in etcd. So could you please have a try to run `etcdctl del "/apisix" --prefix && apisix init && apisix init_etcd` to reinitialize the etcd?

a simple reproduce step:

1. run Manager API
2. etcdctl del --prefix /apisix
3. apisix init

in the process don't stop the Manager API.

**Comment by imjoey** [comment]
> > @nic-chen I'm afraid I cannot reproduce in my environment. Is the etcd also newly installed? I guess there's something wrong with the data in etcd. So could you please have a try to run `etcdctl del "/apisix" --prefix && apisix init && apisix init_etcd` to reinitialize the etcd?
> 
> a simple reproduce step:
> 
> 1. run Manager API
> 2. etcdctl del --prefix /apisix
> 3. apisix init
> 
> in the process don't stop the Manager API.

@nic-chen thanks for the details. I managed to reproduce this issue. The reason is that we should explicitly ignore the `init_dir` etcd event during `Watch` etcd process. I would commit an PR to fix this. Thanks for reporting.
