### ISSUE TITLE
bug: Forward the request to the stale upstream node

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1330]
# Bug report

![image](https://user-images.githubusercontent.com/6814606/104990711-1c19b200-5a58-11eb-8cb0-4a870f543fbd.png)
![image](https://user-images.githubusercontent.com/6814606/104990723-2340c000-5a58-11eb-8c8e-ace71ec3bd7a.png)

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

**Comment by membphis** [comment]
need more information from the user.

**Comment by juzhiyuan** [comment]
Any update?

**Comment by juzhiyuan** [comment]
I couldn't search that user in QQ Group 🤔

**Comment by membphis** [comment]
we can close this issue now.
