### ISSUE TITLE
feat: Improve testing coverage for the POST and PATCH methods of the resources

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-dashboard#1332]
# Feature request

## Please describe your feature

At present, most test cases in Backend E2E and Unit-test cases are using `PUT` method for creating and updating the resource, which leads to extremely low testing coverage for creating by `POST` and updating by `PATCH`.

## Describe the solution you'd like

So it would be much better that if we could add more test cases for the `POST` and `PATCH` methods of the resource. Of course, I would say adding missing test cases is heavy work, so let us fix this gradually.

**Comment by starsz** [comment]
Aha! Much appreciated.

**Comment by Jaycean** [comment]
I hope to help add more test cases.

**Comment by juzhiyuan** [comment]
@Jaycean Assign to you! Thanks a lot!

**Comment by imjoey** [comment]
> I hope to help add more test cases.

@Jaycean thanks a lot. 😄

**Comment by Jaycean** [comment]
issue: #1161
Planned unit test refactoring of ssl,route,upstream,service.
Unit testing of the patch method will be added.

**Comment by nic-chen** [comment]
@Jaycean  could we close this issue now ?

**Comment by Jaycean** [comment]
> @Jaycean could we close this issue now ?

The issue is closed and the test case is complete. If there is any problem, open it again.
