### ISSUE TITLE
request help: How to add icons to custom plugins?

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#1337]
I added a custom plugin. I want to add a logo when displaying the plugin in the dashboard. What do I need to do? For example, the jwt-auth plugin has a corresponding logo.

![20210120151324](https://user-images.githubusercontent.com/12752710/105140241-5d7e9000-5b32-11eb-9910-0d6ea7fa490a.png)

**Comment by juzhiyuan** [comment]
This is not an easy job, but I will draft documentation about this after v2.4 release.

**Comment by Caelebs** [comment]
> 这不是一件容易的事，但是我将在v2.4发布之后起草有关此问题的文档。

nice. looking forward to the next version

**Comment by Caelebs** [comment]
> This is not an easy job, but I will draft documentation about this after v2.4 release.

nice. looking forward to the next version

**Comment by juzhiyuan** [comment]
Hi, please refer to iconfont.cn , once you collect your icons, you could download it & replace this one:

![image](https://user-images.githubusercontent.com/2106987/114417490-380a9b00-9be4-11eb-8c16-c44787028201.png)

BTW, we are going to add icons for current dashboard, refer to #1760
