### ISSUE TITLE
bug: some apis bypassed authentication

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1351]
# Bug report

## Describe the bug

I found that some apis that need to get the original data of the request without using the droplet bypass the authentication, I think it's due to #1296

we need to fix it before release.

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3] master

**Comment by nic-chen** [comment]
cc @starsz

**Comment by starsz** [comment]
Right. It's a bug.
IMO, we can wrap those functions into droplet, because the droplet has updated before.
