### ISSUE TITLE
CI: Create Route with Upstream is unstable

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1365]
# CI Unstable

## How to Reproduce

https://github.com/apache/apisix-dashboard/runs/1756582600

## Screenshots

![image](https://user-images.githubusercontent.com/2106987/105628168-48796800-5e76-11eb-8f9b-e5d6d3f2e441.png)

## Additional context

cc @guoqqqi @LiteSun

**Comment by guoqqqi** [comment]
https://github.com/apache/apisix-dashboard/pull/1364 
This PR will solve it!

**Comment by membphis** [comment]
can we close this issue now? #1364 has been merged

**Comment by juzhiyuan** [comment]
ping @guoqqqi

**Comment by guoqqqi** [comment]
Yes! It can be closed, it be resolved!

**Comment by juzhiyuan** [comment]
@guoqqqi 

`deepl.com` and `Grammarly` are your friends.
