### ISSUE TITLE
Update Deploy with RPM Doc

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1368]
# Feature request

## Please describe your feature

Update documentation about deploying with RPM[1].

## Describe the solution you'd like

Tell us how to visit the dashboard.

[1] https://github.com/apache/apisix-dashboard/blob/master/docs/deploy-with-rpm.md

**Comment by juzhiyuan** [comment]
cc @idbeta

**Comment by idbeta** [comment]
`deploy-with-rpm.md` should add description like this:
without changing `/usr/local/apisix/dashboard/conf/conf.yaml`, you can visit http://127.0.0.1:9000 to use the dashboard with GUI, where the default username and password are `admin`.

**Comment by stu01509** [comment]
Hi @juzhiyuan 

Could you guide me how to approach this issue?

**Comment by juzhiyuan** [comment]
We should add tips to this part[1] :) After running that command, users should visit xxx to use the dashboard.

[1] https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy-with-rpm.md#run
