### ISSUE TITLE
reduce plugin testcases' running time

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1371]
# Feature request

## Please describe your feature

![image](https://user-images.githubusercontent.com/2106987/105674606-bd09e080-5f22-11eb-865d-5e254e578fe9.png)

Plugin Test takes a long time to run.

**Comment by guoqqqi** [comment]
Can we reduce the time by reducing the number of working on the current plug-in.

**Comment by juzhiyuan** [comment]
how?

**Comment by guoqqqi** [comment]
I mean to say, Can we reduce the data in the DataSet.

**Comment by juzhiyuan** [comment]
of course not...
