### ISSUE TITLE
Update Years in NOTICE file

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1375]
# Feature request

## Please describe your feature

We are entering the year 2021, it's time to update 2020 to 2021.

## How?

1. Visit https://github.com/apache/apisix-dashboard/blob/master/NOTICE#L2
2. Click this button:
![image](https://user-images.githubusercontent.com/2106987/105794003-1b879b00-5fc5-11eb-8420-d1f65854f3e1.png)
3. Replace `2020` with `2021`.
4. 
![image](https://user-images.githubusercontent.com/2106987/105794082-3ce88700-5fc5-11eb-82b3-8801206b20dc.png)
5. 
![image](https://user-images.githubusercontent.com/2106987/105794149-630e2700-5fc5-11eb-9008-8409f483d244.png)

**Comment by krak7602** [comment]
Can I work on this issue?

**Comment by imjoey** [comment]
> Can I work on this issue?

@krak7602 sure, assign this issue to you and please go ahead. Many thanks.

**Comment by 96RadhikaJadhav** [comment]
@juzhiyuan Is this issue still available? I wish to work on it.

**Comment by juzhiyuan** [comment]
Hi, another contributor is working on this, could you please take a look at other good first issue?

**Comment by nathannaveen** [comment]
This issue is already fixed by https://github.com/apache/apisix-dashboard/pull/1377

**Comment by liuxiran** [comment]
> This issue is already fixed by #1377

yap, close now~ thanks
