### ISSUE TITLE
Doc: Add the document of backend E2E environment

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix-dashboard#1380]
# Feature request

## Please describe your feature

- In the process of submitting my contribution, I found that there was no local documentation for setting up E2E test environment, and I didn't know how to conduct E2E test locally. I could only view the results of GitHub Ci by submitting code, which was very unfriendly. So I checked the command of GitHub Ci and found that I needed to run docker upstream locally

## Describe the solution you'd like
- I want to submit a PR update doc, so that more developers can quickly develop for the first time and use E2E test locally.

```
docker run -d --name upstream -v /home/apisix-dashboard/api/test/docker/upstream.conf:/etc/nginx/conf.d/default.conf:ro -p 80:80 -p 1980:1980 -p 1981:1981 -p 1982:1982 -p 1983:1983 -p 1984:1984 johz/upstream:v2.0
```

**Comment by imjoey** [comment]
@Jaycean good catch. I believe that would be very helpful for every contributor. Your PR is greatly welcome. Thanks.

**Comment by juzhiyuan** [comment]
cc @starsz @LiteSun to know this tip.

**Comment by starsz** [comment]
Can't agree anymore. 😄
