### ISSUE TITLE
chore: When exporting route, whether the parameter is empty or not

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix-dashboard#1383]
# Bug report

## Describe the bug

- When exporting route data, the current logic will export empty swagger data when the route data is null or there is no route data. Whether to add judgment will directly return an error.

```
{
  "components": {},
  "info": {
    "title": "RoutesExport",
    "version": "3.0.0"
  },
  "openapi": "3.0.0",
  "paths": {}
}
```

## Expected behavior

- When null characters are passed in, routeid is not passed in, or all routeid data is exported, there is no data in the database, and an error should be reported directly.

**Comment by Jaycean** [comment]
cc @liuxiran @nic-chen @starsz

**Comment by starsz** [comment]
Agree with you. Thank you for your PR.

**Comment by nic-chen** [comment]
we could close it now since the pr merged.
