### ISSUE TITLE
应用无法使用Oauth2进行认证

### ISSUE THREAD

**Issue by sanmen359** [apache/apisix-dashboard#1387]
# Bug report

## Describe the bug

我们拥有独立的认证中心(使用Authing)，创建应用时，无法使用OpenID Connect认证。

## How to Reproduce

1. 打开网址"http://127.0.0.1:9000/consumer/list"
2. 点击 '创建'
3. 输入"demo"
3. 点击“下一步”
4. 选择“OpenID Connect”，输入OpenID Connect配置内容后保存
5.点击下一步，提示“请启用一种身份认证类插件”，无法进入下一步

OpenID Connect配置内容：

```
“{
            "client_id":"60118e33bf766f807a991b52",
            "client_secret":"abfd508342bc02c1c05246ef450ae491",
            "discovery":"https://1611763239295.authing.cn/oidc/.well-known/openid-configuration", 
            "introspection_endpoint":"https://1611763239295.authing.cn/oidc/token/introspection",
            "bearer_only":true,
            "realm":"master",
            "introspection_endpoint_auth_method":"client_secret_basic"
        }”
```

## Expected behavior

希望应用可以使用Oauth2进行认证

## Screenshots

 
![image](https://user-images.githubusercontent.com/4597642/106109704-cb573700-6184-11eb-853f-2a6e2319638a.png)

## System information

- OS: Centos7
- Browser : firefox
- Version: 2.3

**Comment by juzhiyuan** [comment]
This issue is related to this one[1]

**Quick fix:**
1. Open this file: https://github.com/apache/apisix-dashboard/blob/master/api/conf/schema.json
2. Find `openid-connect` plugin, append the `type` property, set its value as `auth` like here[2]

[1] https://github.com/apache/apisix/issues/3239
[2] https://github.com/apache/apisix-dashboard/blob/master/api/conf/schema.json#L4187

**Comment by imjoey** [comment]
@juzhiyuan This looks more like a critical bug. I was wondering that whether only the openid-connect plugin is affected. If so, can we commit a PR in APISIX and then sync the schema here to fix this? Thanks.

**Comment by juzhiyuan** [comment]
This issue should be reconsidered, due to `openid-connect` will rely on `OAuth Server`, then this plugin should not belong to `auth` type 🤔

**Comment by juzhiyuan** [comment]
Here is the doc[1] for `openid-connect`.

[1] https://github.com/apache/apisix/blob/master/doc/plugins/openid-connect.md

**Comment by juzhiyuan** [comment]
If it does not belong to `Auth`, users have to enable one auth plugin like `key-auth`, strange IMO.

The first thing that needs to confirm, whether users should use at least one auth plugin with `openid-connect` or not? If yes, we don't need to anything here; if not, we may add that plugin to allowlist in Dashboard.

cc @membphis @imjoey

**Comment by imjoey** [comment]
> If it does not belong to `Auth`, users have to enable one auth plugin like `key-auth`, strange IMO.
> 
> 
> 
> The first thing that needs to confirm, whether users should use at least one auth plugin with `openid-connect` or not? If yes, we don't need to do anything here; if not, we may add that plugin to allowlist in Dashboard.
> 
> 
> 
> cc @membphis @imjoey 

@juzhiyuan I have always seen `openid-connect` as an auth plugin. 👻

**Comment by juzhiyuan** [comment]
fine, we may add this to the allowlist in FE first..

**Comment by membphis** [comment]
> @juzhiyuan I have always seen `openid-connect` as an auth plugin

I think the `openid-connect` is an auth plugin too. I think we should add the `auth` type in APISIX project.

**Comment by juzhiyuan** [comment]
Fine, cc @spacewander do you agree with this?

**Comment by membphis** [comment]
> I think the `openid-connect` is an auth plugin too. I think we should add the `auth` type in APISIX project.

After offline discussion, "openid-connect" is not an "auth" plugin. Because it cannot find out the consumer of apisix. 
I'm very sorry for the wrong understanding. 

@sanmen359 why you need to bind plugin `openid-connect` to `consumer`? I think this is forbidden.

**Comment by sanmen359** [comment]
> > I think the `openid-connect` is an auth plugin too. I think we should add the `auth` type in APISIX project.
> 
> After offline discussion, "openid-connect" is not an "auth" plugin. Because it cannot find out the consumer of apisix.
> I'm very sorry for the wrong understanding.
> 
> @sanmen359 why you need to bind plugin `openid-connect` to `consumer`? I think this is forbidden.

我希望对 API 进行保护，所以需要对访问 API 的应用进行控制。我研究了一下，发现authz-keycloak 插件是个好选择。I want to protect the API, so I need to control the application accessing the API . I found the "authz keycloak" plug-in a good choice.

**Comment by membphis** [comment]
> 我希望对 API 进行保护，所以需要对访问 API 的应用进行控制
> I want to protect the API, so I need to control the application accessing the API .

for this case, you can bind the plugin `openid-connect` to Route, then it should work well for your case.
here is the doc: https://github.com/apache/apisix/blob/master/doc/plugins/openid-connect.md#token-introspection

**Comment by nic-chen** [comment]
close.
if you have any problem with this , feel free to reopen
