### ISSUE TITLE
feat: Modify the usage of upstream and service go-jsonpatch to json-patch/v5 

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix-dashboard#1392]
# Feature request

## Please describe your feature

When I look at the test cases, I find that the jsonpatch(`github.com/api7/go-jsonpatch`) used by upstream and service when calling the patch method is still the old package, but I see that PR：#1005 has been updated to `github.com/evanphx/json-patch/v5`,The current use of old packages will also result in interface errors, so I'm going to fix them.

## Describe the solution you'd like

I will submit PR to make upstream and service use the new package.

Ping @starsz @nic-chen @imjoey .
Pls assign to me. Thks

**Comment by imjoey** [comment]
@Jaycean thanks for reporting. IMHO, this is indeed a bug and we should omit the dependency of `github.com/api7/go-jsonpatch` and use `github.com/evanphx/json-patch/v5` for all cases.

Ping @nic-chen for comfirmation. Thanks.

**Comment by nic-chen** [comment]
@imjoey @Jaycean  that's great, thanks!

**Comment by Jaycean** [comment]
PR merged. Now close the issue and open it again if there is any problem
