### ISSUE TITLE
feat: Customize the configurations of Semantic-Pull-Request check in CI

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-dashboard#1397]
# Feature request

## Please describe your feature

Currently apisix-dashboard is using the default configurations for Semantic Pull Request check in CI and I guess with several customizations may make the contributions more smooth.

- Only do semantic check for the PR title but not for the commit message, this could bring less burden to contributors.
- Add `backport` into valid type list, which indicates this PR or issue is for backport purpose.

## Describe the solution you'd like

Add `semantic.yml` under `.github` directory, with some configurations inside. Please refer to [Official guide](https://github.com/zeke/semantic-pull-requests#configuration) and [The configs in APISIX](https://github.com/apache/apisix/blob/master/.github/semantic.yml) for directions.

**Comment by starsz** [comment]
Good idea. 👍

**Comment by defp** [comment]
> By default types specified in commitizen/conventional-commit-types is used.
> See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json

No `backport` type in index.json

**Comment by nic-chen** [comment]
> > By default types specified in commitizen/conventional-commit-types is used.
> 
> > See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
> 
> 
> 
> No `backport` type in index.json
> 
> 

could we add it？

**Comment by defp** [comment]
> Add support for custom types
https://github.com/zeke/semantic-pull-requests/pull/67

@nic-chen  Yes!

**Comment by defp** [comment]
https://github.com/apache/apisix-dashboard/pull/1688/commits/44fa580af59b648957657e56ea3a153aef70daa8
backport type

**Comment by defp** [comment]
可以关闭这个issue了
