### ISSUE TITLE
support to show raw data for Route, Upstream, Service and so on

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1399]
# Feature request

## Please describe your feature

Due to some fields are not supported by Frontend, once users modify a Route that is created by admin API, then that Route would be overridden by Frontend's data. 

## Describe the solution you'd like

We may first support showing raw data and allow the user to modify it directly and add some tips before submitting data change, to tell the user to be careful if this Route is created by Admin API.

If possible, we could support Data Diff before data submitting.

cc @LiteSun @liuxiran @membphis

**Comment by LiteSun** [comment]
This feature allows the user to see the data faster and more intuitively, a very good feature. 

It is necessary to check the legitimacy of the data if the user is allowed to enter it manually. otherwise, such a problem #1234 will occur.

**Comment by liuxiran** [comment]
This feature would be more practical for advanced users, Perhaps `Expert Mode` is a fitting name for it(config in form can be defined as `Normal Mode`)

As we have plan to deprecate the `admin-api`, my only question is that Is this feature only for interim use or intended for long-term support?

**Comment by juzhiyuan** [comment]
Long term support, of course, both `Normal mode` & `Advanced Mode`.

**Comment by LiteSun** [comment]
## Solutions design:
On the page, in the list of route, service, consumer and upstream, add a view button. When the user clicks view, a Drawer will pop up on the right side, and the corresponding data will be displayed in the form of json in the Drawer.

![image](https://user-images.githubusercontent.com/31329157/108809901-cc914d80-75e4-11eb-9115-a4be803288b2.png)
![image](https://user-images.githubusercontent.com/31329157/108809910-d450f200-75e4-11eb-9913-97db3fc3fd93.png)

The code editor uses codemirror, the same as the plugin editor;
- documents: When clicked, it will jump to the corresponding document.
- format: When clicked, it will format the current code.
- copy: When clicked, the code will be copied to the clipboard for testing and debugging purposes.

## Discussion needed:
If the user uses raw data for editing, the edited data is missing fields that the front-end depends on, which can cause the page to crash.
For example, the following issue: https://github.com/apache/apisix-dashboard/issues/1234 

Can we use jsonchema to verify that the data entered by the user is legitimate, just like we verify that the plugin is legitimate?

@juzhiyuan @nic-chen @liuxiran

**Comment by juzhiyuan** [comment]
> Can we use jsonchema to verify that the data entered by the user is legitimate

As far as I know, the backend is using this method to check the client's input, right?

**Comment by membphis** [comment]
ping @LiteSun

**Comment by LiteSun** [comment]
1. I submitted a PR for rawDataEditor's view mode. #1505 

2. `edit` mode needs @nic-chen's support to validate data.

**Comment by nic-chen** [comment]
@LiteSun  
The api cannot verify whether the submitted data is missing fields.
Only required fields can be checked if they are missing.

**Comment by LiteSun** [comment]
> @LiteSun
> The api cannot verify whether the submitted data is missing fields.
> Only required fields can be checked if they are missing.

ok, let me do more research on how to prevent the page from crashing if a field is missing.
