### ISSUE TITLE
We can get the backend version and git hash at the front end.

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1404]
# Feature request

## Please describe your feature

Hello, there is no way to get the backend version and the git hash at the front end.
But I think it's in need.

## Describe the solution you'd like

Backend adds an API like `/apisix/admin/version" to return the version and git hash.

**Comment by starsz** [comment]
API:

`GET /info`

Response:

```
{
  "code": 0,
  "message": "",
  "data": {
    "commit_hash": "94d952f",
    "version": "master"
  },
  "request_id": "09b92a36-2d42-4865-bedc-0560c3fa5aaa"
}
```

**Comment by moonming** [comment]
Can the version number of the front end be displayed? I think it can be placed in the footer
@juzhiyuan

**Comment by membphis** [comment]
> Can the version number of the FE and commit hash be displayed? I think it can be placed in the footer
> @juzhiyuan

ping @juzhiyuan

**Comment by juzhiyuan** [comment]
See #1434
