### ISSUE TITLE
Unstable front-end test cases

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#1410]
# Bug report

## Describe the bug

Trace occasional failures of  The front-end test cases

1. https://github.com/apache/apisix-dashboard/pull/1409/checks?check_run_id=1805078346
2. https://github.com/apache/apisix-dashboard/pull/1414/checks?check_run_id=1808679183
3. https://github.com/apache/apisix-dashboard/pull/1414/checks?check_run_id=1811238315

**Comment by membphis** [comment]
fixed? @liuxiran

**Comment by liuxiran** [comment]
> fixed? @liuxiran

I have submitted a pr, it may be due to the interaction between loop operations
a  few more CI runs are needed to test whether the solution is feasible ^_^
