### ISSUE TITLE
test: delete button in plugin drawer

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-dashboard#1411]
https://github.com/apache/apisix-dashboard/pull/1402
added a delete button to the drawer of the plugin in this PR, 
now we need to add a test for it. 

Related links on completing test development: 
https://github.com/apache/apisix-dashboard/blob/a34317193cece2532ed333aaaacfd3a6af7328c4/docs/front-end-e2e.md

Very thanks!

**Comment by vinayaksh42** [comment]
can I work on this issue?

**Comment by imjoey** [comment]
> can I work on this issue?

@vinayaksh42 sure, thanks and looking forward to your pr.

**Comment by juzhiyuan** [comment]
Hi, @vinayaksh42, once #1402 is merged, you could try to add testcase for it.

**Comment by vinayaksh42** [comment]
> Hi, @vinayaksh42, once #1402 is merged, you could try to add testcase for it.

Sure

**Comment by guoqqqi** [comment]
HI, @vinayaksh42 , #1402  has been merged, so you can start trying to add test cases to it.

**Comment by vinayaksh42** [comment]
> HI, @vinayaksh42 , #1402 has been merged, so you can start trying to add test cases to it.

Thanks for the update, will get started with it

**Comment by guoqqqi** [comment]
Hi, any update? 😊

**Comment by stu01509** [comment]
Hi @guoqqqi 

I'm interested in this issue, Could you assign this issue to me?

**Comment by nic-chen** [comment]
@stu01509  thanks!

**Comment by guoqqqi** [comment]
Hi @stu01509 
Thank you very much and looking forward to your PR.

**Comment by nic-chen** [comment]
ping @stu01509

**Comment by stu01509** [comment]
Hi @nic-chen 

Thanks for your mention, I will start to solve it.

**Comment by guoqqqi** [comment]
ping @stu01509
