### ISSUE TITLE
Bug: the commit_hash in the demo is empty string

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1438]
# Bug report

## Describe the bug

The commit_hash is "", when requesting the online demo.

## How to Reproduce

`
curl 139.217.190.60/apisix/admin/tool/version -v
`

The response:

```
"code":0,"message":"","data":{"commit_hash":"","version":"master"},"request_id":"a96d8d8f-e0af-4a17-8caa-d4a7bff03a3b"}
```

## Expected behavior

Return the correct commit_hash.

**Comment by juzhiyuan** [comment]
related PR: #1434
