### ISSUE TITLE
feat: support plugin `grpc-transcode`

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1449]
# Feature request

## Please describe your feature

support config plugin `grpc-transcode` on Dashboard

## Describe the solution you'd like

upload proto like SSL, and select proto in `grpc-transcode` config page

**Comment by hnlq715** [comment]
Happy to see this feature in dashboard :-)

**Comment by bzp2010** [comment]
Hi,
It seems that to realize the support of `grpc-transcode` plugin, we must first provide the management function of `proto` data entities. I will first implement it in the backend.

**Comment by hnlq715** [comment]
Nice job, and uploading protoset files is preferred against single proto file :-)

https://github.com/fullstorydev/grpcurl#protoset-files

**Comment by liuxiran** [comment]
in order to let dashboard work together with APISIX 2.9, we adjusted our plan to quickly release a suitable version, and for this missing feature, move it to m2.9, and hope for this big feature ready, any questions can comment here, thanks a lot

**Comment by zaunist** [comment]
Hi, @juzhiyuan . I found `grpc-transcode` plugin have implement in dashboard.

![image](https://user-images.githubusercontent.com/38528079/147640320-256f73d7-5303-4088-87f3-43c41311de95.png)

**Comment by juzhiyuan** [comment]
According to https://apisix.apache.org/docs/apisix/plugins/grpc-transcode/ , we need to use `PUT /apisix/admin/proto/1` as well 🤔

**Comment by zaunist** [comment]
I see.. There is still some front-end work left, the back-end already supports proto. The frontend needs to create the proto first, and then enable the grpc plugin.

**Comment by juzhiyuan** [comment]
Yes, corretly.

**Comment by Baoyuantop** [comment]
Hi everyone, after @oil-oil nice work https://github.com/apache/apisix-dashboard/pull/2320, now we can manage the proto file on the dashboard. So you can configure proto file `id` in the `grpc-transcode` plugin. I think this problem is solved.
cc @nic-chen @hnlq715
