### ISSUE TITLE
feat: support etcd prefix as apisix does

### ISSUE THREAD

**Issue by liuyang211** [apache/apisix-dashboard#1456]
# Feature request

## Please describe your feature

apisix has supported etcd prefix to store different clusters' configuration. Dashboard should also support this.
This is very useful in some resource limited situation like dev/test environment.

## Describe the solution you'd like

set multiple prefix in one dashboard, and let the user choose which apisix cluster he want to manage.

## Describe alternatives you've considered

Not yet.

## Additional context

Thank you!

**Comment by tokers** [comment]
Nice idea, @starsz @nic-chen What's your opinion?

**Comment by starsz** [comment]
Pretty good. I think it's a good idea.
PRs are welcomed.

**Comment by nic-chen** [comment]
> Nice idea, @starsz @nic-chen What's your opinion?

great.
@liuyang211 would you like to submit a
PR for this feature? ^_^

**Comment by liuyang211** [comment]
> > Nice idea, @starsz @nic-chen What's your opinion?
> 
> great.
> @liuyang211 would you like to submit a
> PR for this feature? ^_^

Sorry, I didn't program in both go and javascript before. That would be a great challenge to me.

**Comment by nic-chen** [comment]
> Sorry, I didn't program in both go and javascript before. That would be a great challenge to me.

it deeds only `go` for this feature. and we could help you finish this pr together, if you are interested.

**Comment by liuyang211** [comment]
> > Sorry, I didn't program in both go and javascript before. That would be a great challenge to me.
> 
> it needs only `go` for this feature. and we could help you finish this pr together, if you are interested.

I would like to have a try.
I've viewed the apisix-dashboard\api\ these days. But I still don't get the point.
So where should I start?

**Comment by starsz** [comment]
Now, the routes are set in the `api/internal/hander/*.go`
IMO, we can configure the `prefix` in the `conf.go` and use the `gin.Group` to set the prefix of route.

**Comment by nic-chen** [comment]
@liuyang211 

The detailed steps are as follows:

1. Configure the prefix in yaml:
https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L24-L31

2. Read configuration
https://github.com/apache/apisix-dashboard/blob/master/api/internal/conf/conf.go#L135-L158
https://github.com/apache/apisix-dashboard/blob/master/api/internal/conf/conf.go#L222-L234

3. Use configuration
`BasePath: "/apisix/consumers"`, `BasePath: "/apisix/routes"` is the prefix of various resources
https://github.com/apache/apisix-dashboard/blob/master/api/internal/core/store/storehub.go#L83-L181


you could have a try : )

**Comment by liuyang211** [comment]
> @liuyang211
> 
> The detailed steps are as follows:
> 
> 1. Configure the prefix in yaml:
>    https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L24-L31
> 2. Read configuration
>    https://github.com/apache/apisix-dashboard/blob/master/api/internal/conf/conf.go#L135-L158
>    https://github.com/apache/apisix-dashboard/blob/master/api/internal/conf/conf.go#L222-L234
> 3. Use configuration
>    `BasePath: "/apisix/consumers"`, `BasePath: "/apisix/routes"` is the prefix of various resources
>    https://github.com/apache/apisix-dashboard/blob/master/api/internal/core/store/storehub.go#L83-L181
> 
> you could have a try : )

Thank you, I've done it. But I modified this, is that OK?
2. Read configuration
https://github.com/apache/apisix-dashboard/blob/master/api/internal/conf/conf.go#L66-L71

And use the global variable conf
`	err := InitStore(HubKeyConsumer, GenericStoreOption{
		BasePath: conf.ETCDConfig.Prefix + "/consumers",
		ObjType:  reflect.TypeOf(entity.Consumer{}),
		KeyFunc: func(obj interface{}) string {
			r := obj.(*entity.Consumer)
			return r.Username
		},
	})
`

BTW, it seems that one dashboard can only manage one apisix cluster if /web remains the same.
I think it would be better, if dashboard can manage multiple apisix clusters. The prefix is passed as a parameter to api by web.

**Comment by nic-chen** [comment]
> And use the global variable conf

It's ok. But we need to make sure that `conf.ETCDConfig.Prefix` has a default value.

**Comment by nic-chen** [comment]
> I think it would be better, if dashboard can manage multiple apisix clusters. The prefix is passed as a parameter to api by web.

It's great feature. But we don't recommend to use an ETCD cluster for multiple APISIX clusters.

**Comment by liuyang211** [comment]
> > And use the global variable conf
> 
> It's ok. But we need to make sure that `conf.ETCDConfig.Prefix` has a default value.

I've created a PR, but 3 checks fail. Can you review that code, and what should be fixed?
Thanks.
