### ISSUE TITLE
better user experience

### ISSUE THREAD

**Issue by Junnplus** [apache/apisix-dashboard#1458]
# Feature request

### friendly menu icon
![image](https://user-images.githubusercontent.com/8097526/107170183-af605a80-69fa-11eb-81b6-6035702c68c6.png)

### fiexd sidercar
![image](https://user-images.githubusercontent.com/8097526/107170233-cacb6580-69fa-11eb-999f-2b11835ebee0.png)

### consistent name for list page
![image](https://user-images.githubusercontent.com/8097526/107170243-d1f27380-69fa-11eb-9747-1a639485b5d3.png)
![image](https://user-images.githubusercontent.com/8097526/107170255-d61e9100-69fa-11eb-9d95-40c9564850cb.png)

`上游列表` and `服务 列表` should consistent.

**Comment by juzhiyuan** [comment]
Ya

**Comment by juzhiyuan** [comment]
Thanks, @Junnplus !
