### ISSUE TITLE
feat: Confirm whether the store related functions are still in use. If not, delete them

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix-dashboard#1461]
# Feature request

## Please describe your feature

comment: https://github.com/apache/apisix-dashboard/pull/1452#discussion_r571882686
Confirm whether the store related functions are still in use. If not, delete them.
```
store.NewFilter([]string{"name", name})
store.NewPagination(0, 0)
store.NewQuery(sort, filter, pagination)
store.NewFilterSelector(toRows(ret), query)
```

**Comment by starsz** [comment]
We can remove it and refactor the logic using it.

**Comment by Jaycean** [comment]
I see pr: #1568  issue: #1567 
Think of this issue.

**Comment by starsz** [comment]
> I see pr: #1568 issue: #1567
> Think of this issue.

Oh Yes.Sorry for forgetting this.

**Comment by Jaycean** [comment]
> > I see pr: #1568 issue: #1567
> > Think of this issue.
> 
> Oh Yes.Sorry for forgetting this.

It doesn't matter. Actually, I forgot it. It's my problem.
