### ISSUE TITLE
doc: improve documentation for route export and import

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1464]
# Feature request

## Please describe your feature

We need to describe the route import and export feature in detail, including the processing details of upstream, service, plugins and other data in route, and other details.

There are most of the descriptions in the relevant proposals, we could refer to them.

**Comment by nic-chen** [comment]
cc @Jaycean @liuxiran

**Comment by Jaycean** [comment]
Yes, there is a simple description document at present.[IMPORT_OPENAPI_USER_GUIDE](https://github.com/apache/apisix-dashboard/blob/master/docs/IMPORT_OPENAPI_USER_GUIDE.md) 
We can add a more detailed document later to enable developers and users to understand and use the import and export function faster.

**Comment by liuxiran** [comment]
Besides, we can also add some examples of what import and export files look like to help user more easily use this feature

**Comment by starsz** [comment]
> Besides, we can also add some examples of what import and export files look like to help user more easily use this feature

Yes. It will be useful for users.

**Comment by imjoey** [comment]
@liuxiran @Jaycean  I guess we could tackle this and help users know more about this great feature.  Meanwhile, the community could also get feedbacks to further improve it. What's your opinions? 😄

**Comment by liuxiran** [comment]
> @liuxiran @Jaycean I guess we could tackle this and help users know more about this great feature. Meanwhile, the community could also get feedbacks to further improve it. What's your opinions? 😄

yep, already in our schedule ^^

**Comment by imjoey** [comment]
> > @liuxiran @Jaycean I guess we could tackle this and help users know more about this great feature. Meanwhile, the community could also get feedbacks to further improve it. What's your opinions? 😄
> 
> yep, already in our schedule ^^

Much appreciated and looking forward to your PRs.
