### ISSUE TITLE
Backend E2E failed

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1470]
https://github.com/apache/apisix-dashboard/runs/1872715478

**Comment by juzhiyuan** [comment]
I see a bundle of PRs is failed due to backend E2E, please take a look when you are free.

![image](https://user-images.githubusercontent.com/2106987/107864671-968ff300-6e99-11eb-8e61-01a65db9daa6.png)

**Comment by starsz** [comment]
Just guess there were some changes on apisix. 
They cause this problem.

**Comment by moonming** [comment]
@nic-chen ch

**Comment by nic-chen** [comment]
E2E test failed because of an update of global rule in APISIX a few days ago.. I submitted a pr to fix this problem.

https://github.com/apache/apisix/pull/3595

**Comment by membphis** [comment]
can we close this issue now? @nic-chen

**Comment by nic-chen** [comment]
yes, it is solved
