### ISSUE TITLE
bug: add route param `Redirect : Enable HTTPS`, show toast error

### ISSUE THREAD

**Issue by umelly** [apache/apisix-dashboard#1476]
chrome 88.0.4324.150 / macos 11.3 beta

apisix-dashboard 2.4

## screenshots

![image](https://user-images.githubusercontent.com/973111/108193450-69b93580-7150-11eb-8997-f3e6a43d4a97.png)

devtools
![image](https://user-images.githubusercontent.com/973111/108194059-214e4780-7151-11eb-8a1d-23416aa5a946.png)

**Comment by juzhiyuan** [comment]
@umelly Hi, could you please give fake request data? and cc @nic-chen to check what happened, thanks.

![image](https://user-images.githubusercontent.com/2106987/108208525-1b159680-7164-11eb-990c-cc4af9f3fe39.png)

**Comment by nic-chen** [comment]
I reproduced the bug, I think we need to change the parameters of this api to solve this problem.
