### ISSUE TITLE
doc: the FAQ doc add the steps of how to load a custom plugin to the plugin list

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1484]
### Issue description

`How to load a custom plug-in to the plug-in list` is a very common problem, but there is no relevant record in the current document. I think the FAQ document should add `How to load a custom plugin to the plugin list steps`.

**Comment by juzhiyuan** [comment]
#1486

**Comment by membphis** [comment]
if it is a duplicated issue, we should close this one

**Comment by membphis** [comment]
ping @Firstsawyou

**Comment by Firstsawyou** [comment]
> ping @Firstsawyou

There has been a PR to resolve this issue, and this issue has been closed.
