### ISSUE TITLE
麻烦问下我新增的自定义插件如何在apisix-dashboard的插件页面显示出来呢

### ISSUE THREAD

**Issue by StretchV** [apache/apisix-dashboard#1507]
我自定义了一个插件，然后在新增路由选插件的阶段如何能让apisix-dashboard显示出来我自定义的插件呢

**Comment by juzhiyuan** [comment]
Please see here:

https://github.com/apache/apisix-dashboard/blob/master/docs/FAQ.md#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard

**Comment by StretchV** [comment]
@juzhiyuan    这句话是什么意思呢“If you have a custom plugin, make sure it is in the apisix directory and use the following command.”   这里的apisix directory 指的是哪个目录呢

**Comment by juzhiyuan** [comment]
Hi, could you help to provide where you see this sentence?

**Comment by StretchV** [comment]
抱歉，我看错文档了，万分感谢，很有效
