### ISSUE TITLE
feat: Dashboard should keep same as APISIX, the enabled plugin list can be configured.

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1508]
The dashboard should be the same as APISIX, and the list of enabled plugins can be configured.

When exporting the JSON Schema from APISIX, only the schema of the plugins that APISIX has been enabled are exported. These plugins can be considered as the list of plugins that the dashboard can configure.

So the current implementation is that the list of plugins available in the dashboard is the list of plugins in `schema.json`.

However, APISIX's strategy is to allow different instances to configure different enabled plugin lists (of course all instances are the same, it is even more possible).

This means that the JSON Schema exported from one of multiple APISIX instances may not be a complete list.

So we should distinguish the JSON Schema from the list of enabled plugins. JSON Schema should export the JSON Schema of all plugins, and add another configuration item to control which plugins can be configured in the dashboard.

Configuration (same as APISIX):
```yaml
plugins: # plugin list
  -api-breaker
  -authz-keycloak
  -basic-auth
  -batch-requests
  -consumer-restriction
  -cors
  #-dubbo-proxy
  -echo
  #-error-log-logger
  #-example-plugin
  -fault-injection
  -grpc-transcode
  -hmac-auth
  -http-logger
  -ip-restriction
  -jwt-auth
  -kafka-logger
  -key-auth
  -limit-conn
  -limit-count
  -limit-req
  #-log-rotate
  #-node-status
  -openid-connect
  -prometheus
  -proxy-cache
  -proxy-mirror
  -proxy-rewrite
  -redirect
  -referer-restriction
  -request-id
  -request-validation
  -response-rewrite
  -serverless-post-function
  -serverless-pre-function
  #-skywalking
  -sls-logger
  -syslog
  -tcp-logger
  -udp-logger
  -uri-blocker
  -wolf-rbac
  -zipkin
  -server-info
  -traffic-split
```

**Comment by juzhiyuan** [comment]
maintain a yaml file or filter from schema.json?

**Comment by nic-chen** [comment]
> maintain a yaml file or filter from schema.json?

1. All plugins are included in schema.json
2. Add a new configuration item `plugins` in `conf.yaml` to control which plugins are displayed in the dashboard.

**Comment by nic-chen** [comment]
cc @membphis @imjoey  @liuxiran @ShiningRush

**Comment by starsz** [comment]
If we add a plugin in apisix, we should sync with the plugins configuration?

**Comment by juzhiyuan** [comment]
How about loop the schema.json and get the enabled plugin list?

**Comment by ShiningRush** [comment]
Do Dashboard users care about plugins that are not enabled? it is reasonable for Dashboard to only display enabled plugins to me.

**Comment by juzhiyuan** [comment]
> When exporting the JSON Schema from APISIX, only the schema of the plugins that APISIX has been enabled are exported. 

Because APISIX will only export enabled plugins schemas, so for Dashboard, we could loop this file and get all plugin names, they are enabled indeed.

**Comment by nic-chen** [comment]
> If we add a plugin in apisix, we should sync with the plugins configuration?

yes

**Comment by nic-chen** [comment]
> Do Dashboard users care about plugins that are not enabled? it is reasonable for Dashboard to only display enabled plugins to me.

some of them do care about it, It will look clearer to only display the plugins you want.

**Comment by nic-chen** [comment]
> > When exporting the JSON Schema from APISIX, only the schema of the plugins that APISIX has been enabled are exported.
> 
> Because APISIX will only export enabled plugins schemas, so for Dashboard, we could loop this file and get all plugin names, they are enabled indeed.

However, APISIX's strategy is to allow different instances to configure different enabled plugin lists (of course all instances are the same, it is even more possible).

This means that the JSON Schema exported from one of multiple APISIX instances may not be a complete list.
