### ISSUE TITLE
the configuration relationship between "host" and "allow_list" in the conf.yaml file

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1510]
# Feature request

## Please describe your feature

If the configuration allows all IPs to access the APISIX Dashboard, only configuring `allow_list` will not take effect immediately, and you need to configure the `host` part. According to the description of the `allow_list` field, it is easy to misunderstand that you only need to configure the `allow_list` part. We should add configuration examples or instructions on how to allow all IPs to access APISIX Dashboard.

**Comment by nic-chen** [comment]
They are two different configurations.

Maybe we can set the default value of `listen.host` to `0.0.0.0`.

**Comment by starsz** [comment]
> They are two different configurations.
> 
> Maybe we can set the default value of `listen.host` to `0.0.0.0`.

Agree +1.

**Comment by juzhiyuan** [comment]
I would prefer to keep the current default value, once users use the following configuration:

- listen.host == 0.0.0.0
- The ManagerAPI is running in public IP
- Using the default Username/Password

Then an urgent security issue will occur.

**Comment by juzhiyuan** [comment]
We'd better update the documentation and configuration file more clear about this issue, no matter use 127.0.0.1 or 0.0.0.0

**Comment by Firstsawyou** [comment]
> They are two different configurations.
> 
> Maybe we can set the default value of `listen.host` to `0.0.0.0`.

I think it would be better to explain the `allow_list` field.  https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L22

E.g: 
```yaml
allow_list:             # Before configuring `allow_list`, you need to set "host" to "0.0.0.0" .
    - 127.0.0.0/24      # If we don't set any IP list, then any IP access is allowed by default.
```

**Comment by nic-chen** [comment]
> I would prefer to keep the current default value, once users use the following configuration:
> 
> * listen.host == 0.0.0.0
> * The ManagerAPI is running in public IP
> * Using the default Username/Password
> 
> Then an urgent security issue will occur.

allow_list default value is `127.0.0.0/24`.
it's ok for this.
