### ISSUE TITLE
Plugin template configuration

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1512]
## Background and purpose

To allow users to configure plugin templates in advance and bind the corresponding plugin templates when creating routes to achieve the fast configuration of routing plugin.

### Front-end

- Plugin template configuration portal:
Add the Plugin Template Config button to the top of the route list, and enter the Plugin Template list page after clicking the button.

![image](https://user-images.githubusercontent.com/31329157/109111245-8caca080-7773-11eb-8284-4c8042f5d52a.png)

- New plugin template configuration list page
The list page is consistent with the style of other list pages and contains CRUD.

![image](https://user-images.githubusercontent.com/31329157/109111516-05abf800-7774-11eb-972a-2ed9c43c25f0.png)

- Add a new plugin template configuration step page
After clicking Create or Edit in the plugin template configuration List page, you will enter the plugin template configuration Steps page.
The steps page is divided into two pages:
   - Basic configuration information (e.g., desc) and plugin template configuration, which interacts with the Plugin Marketplace page.
![image](https://user-images.githubusercontent.com/31329157/109111802-87038a80-7774-11eb-9aa4-ce9aa95e733b.png)
   - Preview page
  
- Update the Create Route configuration route page to include the plugin template selector, and render the corresponding plugin information after selecting the corresponding plugin template.
![image](https://user-images.githubusercontent.com/31329157/109114509-bae0af00-7778-11eb-8388-3d2a27177a1d.png)

  Policy is consistent with apisix:
    - If the route is already configured with `plugins`, then the plugin configuration inside the Plugin config will be merged in.
    - The same plugins will overwrite the original `plugins` plugins
 
#### Back-end
Required interfaces:

- Plugin configuration list
- Plugin list search
- Create plugin configuration
- Update Plugin Configuration
- Delete plugin configuration
- May need to update Create and update routing interface, need @nic-chen  to confirm

**Comment by moonming** [comment]
will pugin support `tag`? 
In this way, the management and grouping of plug-ins can be completed, which is more flexible

**Comment by LiteSun** [comment]
> will pugin support `tag`?
> In this way, the management and grouping of plug-ins can be completed, which is more flexible

Good catch!  
Does apisix plugin config support tag? Need @spacewander  to confirm, if apisix supports it, I will update the tag to the solution.

**Comment by nic-chen** [comment]
> May need to update Create and update routing interface, need @nic-chen to confirm

need to update entity and schema for route.

**Comment by LiteSun** [comment]
Let me do more research on how to prevent the page from crashing if a field is missing

**Comment by LiteSun** [comment]
> > will pugin support `tag`?
> 
> > In this way, the management and grouping of plug-ins can be completed, which is more flexible
> 
> 
> 
> Good catch!  
> 
> Does apisix plugin config support tag? Need @spacewander  to confirm, if apisix supports it, I will update the tag to the solution. 

Ping @spacewander

**Comment by LiteSun** [comment]
Apisix has submitted pr to complete this requirement: https://github.com/apache/apisix/pull/3703

The front-end page was changed as follows to complete the requirement.
1. new label search on the plugin template list page, similar to the route list label search.
![image](https://user-images.githubusercontent.com/31329157/109445467-9e938980-7a7a-11eb-990e-0714889e4297.png)

2. add label field in the basic information configuration. similar to the creation of the route when the configuration label.
![image](https://user-images.githubusercontent.com/31329157/109445629-f7632200-7a7a-11eb-814a-0f37d5ce91a9.png)

**Comment by spacewander** [comment]
> 
> 
> > > will pugin support `tag`?
> > 
> > 
> > > In this way, the management and grouping of plug-ins can be completed, which is more flexible
> > 
> > 
> > Good catch!
> > Does apisix plugin config support tag? Need @spacewander  to confirm, if apisix supports it, I will update the tag to the solution.
> 
> Ping @spacewander

Added in https://github.com/apache/apisix/pull/3703

**Comment by liuxiran** [comment]
I am a little confused about how to use the plugin template.  Do we need to bind the template to the target route manually?  @LiteSun

**Comment by LiteSun** [comment]
> I am a little confused about how to use the plugin template. Do we need to bind the template to the target route manually? @LiteSun

Yes, just like binding upstream in a route.

**Comment by liuxiran** [comment]
> > I am a little confused about how to use the plugin template. Do we need to bind the template to the target route manually? @LiteSun
> 
> Yes, just like binding upstream in a route.

Got it, and does the plugin template can also be bind to service?

**Comment by LiteSun** [comment]
> > > I am a little confused about how to use the plugin template. Do we need to bind the template to the target route manually? @LiteSun
> > 
> > 
> > Yes, just like binding upstream in a route.
> 
> Got it, and does the plugin template can also be bind to service?

Binding service depends on apisix, which does not currently support this feature

**Comment by membphis** [comment]
@litesun can we close this issue now?

**Comment by juzhiyuan** [comment]
@LiteSun Do remember to use `close/resolve/fix #xxx` to link issue in PR.

**Comment by LiteSun** [comment]
closed by #1540

**Comment by LiteSun** [comment]
> @LiteSun can we close this issue now?

Sure.
