### ISSUE TITLE
Incomplete i18n coverage

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1514]
# Feature request
## Please describe your feature

Currently the dashboard is not fully internationalized, so we need to go through it and fix them.
- [ ] route list page
![image](https://user-images.githubusercontent.com/31329157/109122570-c2598580-7783-11eb-9094-396e92c01c45.png)

- [ ] route step3 page
![image](https://user-images.githubusercontent.com/31329157/109122655-dbfacd00-7783-11eb-8b05-c98379202fd7.png)

- [ ] upstream list page
![image](https://user-images.githubusercontent.com/31329157/109122777-0fd5f280-7784-11eb-99eb-90c28fdc5b15.png)

- [ ] service list page
![image](https://user-images.githubusercontent.com/31329157/109122838-2419ef80-7784-11eb-964b-a0b4ccbca935.png)

- [ ] consumer list page
![image](https://user-images.githubusercontent.com/31329157/109122952-4449ae80-7784-11eb-91ea-2fc7f7c140ad.png)

- [ ] SSL list page
![image](https://user-images.githubusercontent.com/31329157/109123132-71965c80-7784-11eb-84a5-462cd8cddac8.png)

**Comment by Baoyuantop** [comment]
Let me do it 😁

**Comment by juzhiyuan** [comment]
ok!

**Comment by LiteSun** [comment]
> Let me do it 😁

any update?😆 @Baoyuantop

**Comment by Baoyuantop** [comment]
> > Let me do it 😁
> 
> any update?😆 @Baoyuantop

I am doing it, submit a PR today or tomorrow

**Comment by LiteSun** [comment]
You can upgrade the pro-table version if you can solve the problem. 😄
