### ISSUE TITLE
bug: BE E2E test case is unstable

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix-dashboard#1521]
# Bug report

## How to Reproduce

BE E2E test case is unstable
https://github.com/apache/apisix-dashboard/pull/1466/checks?check_run_id=1984404224

BE E2E test case is unstable and appears again in PR：#1504, so it is directly repaired in #1504.

commit: https://github.com/apache/apisix-dashboard/pull/1504/commits/de3a084bf038a1ef17576d5d20e3b611a141a4c0

**Comment by moonming** [comment]
@nic-chen @membphis How to solve this problem completely?  Appeared many times

**Comment by Jaycean** [comment]
@nic-chen @starsz @membphis 
I think it's because the E2E test case didn't add sleep for data sync. Do you have any suggestions?

**Comment by nic-chen** [comment]
@moonming @membphis 

Regarding this issue, I have added sleep to the `RunTestCase` function to avoid omissions.

However, for test cases written by hand without calling RunTestCase, they can't avoid the issue yet. I will find a way to avoid  the issue under this circumstances. 

@Jaycean  Thanks for the explanation.

**Comment by Jaycean** [comment]
> @moonming @membphis
> 
> Regarding this issue, I have added sleep to the `RunTestCase` function to avoid omissions.
> 
> However, for test cases written by hand without calling RunTestCase, they can't avoid the issue yet. I will find a way to avoid the issue under this circumstances.
> 
> @Jaycean Thanks for the explanation.

Yes, there is also my problem. I left it out when I wrote it by hand.

**Comment by Jaycean** [comment]
The CI problem has been fixed. If there is a problem, restart it.
