### ISSUE TITLE
broken document link in plugin module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1528]
# Bug report

## Describe the bug

Hi, we are building the new document website and refactored some projects' docs structure, which leads to broken links. In Dashboard -> Plugin Editore, the `Document` button will lead to a 404 issue, we should fix it.

## Expected behavior

When users click the Document button, they should visit the correct page.

## Screenshots

![image](https://user-images.githubusercontent.com/2106987/109459842-8a5f8480-7a9a-11eb-977b-9a239b906e38.png)

## System information

- Version: all

## Solution
1. Visit this file: https://github.com/apache/apisix-dashboard/blob/master/web/src/components/Plugin/PluginDetail.tsx#L261-L267
2. Use this link: `https://apisix.apache.org/docs/apisix/plugins/${name}`

**Comment by stu01509** [comment]
Please assign this issue to me.

**Comment by starsz** [comment]
Fixed by #1533
