### ISSUE TITLE
docs: fix the link failure in the FAQ.md doc

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1534]
## Issue description

In FAQ.md, some document links are invalid, we need to fix it.(https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/FAQ.md#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard)

As follows:

<img width="1075" alt="截屏2021-03-01 下午11 26 54" src="https://user-images.githubusercontent.com/52862365/109519155-f2878800-7ae5-11eb-8151-06f206da2ec6.png">

**Comment by stu01509** [comment]
Hi @Firstsawyou 

I sent a PR in #1532
