### ISSUE TITLE
When I click on the  link of  how to update schema.json  return error page 404

### ISSUE THREAD

**Issue by Abbila** [apache/apisix-dashboard#1543]
# Bug report

## Describe the bug

When I click on the  link of  how to update schema.json  return error page 404
## How to Reproduce
 The  3'td step  page ,I want to see how to update schema.json,I click on the link.  like this:
![image](https://user-images.githubusercontent.com/17827327/109633569-341a4080-7b83-11eb-86f5-79bca954eb8c.png)
![image](https://user-images.githubusercontent.com/17827327/109633620-3f6d6c00-7b83-11eb-8e77-4904f6754d5a.png)

**Comment by juzhiyuan** [comment]
Hi, welcome to send a PR to use the correct FAQ file link :)
