### ISSUE TITLE
request help: discovery setting in dashboard

### ISSUE THREAD

**Issue by xvjialing** [apache/apisix-dashboard#1546]
### Issue description
Can add service discovery settings in the dashboard interface, such as eureka, consul, nacos
### Environment

* apisix version (cmd: `apisix version`): 2.3 
* OS (cmd: `uname -a`): ubuntu 16.0.4
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version: 3.4.9
* apisix-dashboard version, 2.3

**Comment by spacewander** [comment]
It seems it is impossible as the configuration is written in the yaml file.
