### ISSUE TITLE
Clicking on a mask while editing a plugin does not allow the drawer to be closed

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1548]
# Feature request

Users may click on the mask by mistake when editing complex plugins, and the drawer will close after clicking on the mask, resulting in the loss of data edited by the user.
![image](https://user-images.githubusercontent.com/31329157/109763441-0984c200-7c2d-11eb-9976-9b4f178e5b84.png)

## Describe the solution you'd like
Clicking on the mask does not allow the drawer to be closed

We can set `maskClosable ` to `false` to do this. 

Refer link:  https://ant.design/components/drawer/#API

cc @tokers

**Comment by nic-chen** [comment]
agree +1

**Comment by bisakhmondal** [comment]
Yeah, it sounds logical. Can I work on this issue, @LiteSun, @nic-chen? I also noticed that editing any existing plugins also result in the same behaviour. Should I restrict that too?

**Comment by nic-chen** [comment]
> Yeah, it sounds logical. Can I work on this issue, @LiteSun, @nic-chen? I also noticed that editing any existing plugins also result in the same behaviour. Should I restrict that too?

sure, welcome.

**Comment by LiteSun** [comment]
> Yeah, it sounds logical. Can I work on this issue, @LiteSun, @nic-chen? I also noticed that editing any existing plugins also result in the same behaviour. Should I restrict that too?
> 
> Edit: I have made the changes. Can I open a PR?

Looking forward to your PR! 🎉

**Comment by bisakhmondal** [comment]
Hello guys!! Just opened it :)
Waiting for the review, hehe. Thanks for the super quick reply.
