### ISSUE TITLE
feat: support `discovery_type` in Dashboard

### ISSUE THREAD

**Issue by caukie** [apache/apisix-dashboard#1549]
当前dashboard仅支持upstream的人工配置后端服务节点，实际apisix支持基于eureka的服务发现集成扩展，因此需要在dashboard上补充discovery_type参数的传入。进而可以由管理人员决定后端服务是走etcd的upstream服务发现，还是走eureka的服务发现。

**Comment by nic-chen** [comment]
@cakie 
Thanks for your suggestion

**Comment by starsz** [comment]
@caukie Good suggestion. Thank you very much.
PRs are welcomed : )

**Comment by caukie** [comment]
> @caukie Good suggestion. Thank you very much.
> PRs are welcomed : )

pretty sorry, i'm not good at nodejs, so which version will you support it?

**Comment by nic-chen** [comment]
> > @caukie Good suggestion. Thank you very much.
> > PRs are welcomed : )
> 
> pretty sorry, i'm not good at nodejs, so which version will you support it?

what about golang ? : )

**Comment by caukie** [comment]
> > > @caukie Good suggestion. Thank you very much.
> > > PRs are welcomed : )
> > 
> > 
> > pretty sorry, i'm not good at nodejs, so which version will you support it?
> 
> what about golang ? : )

i'm a javaer, but i can try with golang if you wish.

**Comment by nic-chen** [comment]
hi @caukie 
I have submit a PR for it , you could have a look:
https://github.com/apache/apisix-dashboard/pull/1557

**Comment by caukie** [comment]
> hi @caukie
> I have submit a PR for it , you could have a look:
> #1557

i think there still need some code for dashboard show, so i can't check the feature from dashboard now.

**Comment by nic-chen** [comment]
> i think there still need some code for dashboard show, so i can't check the feature from dashboard now.

yes, you are right. the pr is only for backend.

**Comment by stu01509** [comment]
I want to try this, Please assign this issue to me :)

**Comment by juzhiyuan** [comment]
Hi, please resolve other issues first 😊

**Comment by caukie** [comment]
> Hi, please resolve other issues first 😊

can this issue be assigned to @stu01509 now?

**Comment by juzhiyuan** [comment]
@caukie Hi, would you like to have a try?

**Comment by caukie** [comment]
@juzhiyuan sorry，i'm not working with nodejs, so still waiting for help.

**Comment by juzhiyuan** [comment]
oh got it, @stu01509 just to make sure, would you have time to resolve this?

**Comment by juzhiyuan** [comment]
AFAIK, @stu01509 is working on other issues, let's wait for other contributors to take this.

**Comment by juzhiyuan** [comment]
duplicate with https://github.com/apache/apisix-dashboard/issues/1977
