### ISSUE TITLE
health check `active.host` optional

### ISSUE THREAD

**Issue by to2false** [apache/apisix-dashboard#1551]
# Feature request

## Please describe your feature

![image](https://user-images.githubusercontent.com/21302817/109932879-bb8fbd00-7d05-11eb-80f1-b705dc076202.png)
`active.host` looks like an optional item

## Describe the solution you'd like

config it optional

**Comment by nic-chen** [comment]
hi @to2false  does this issue duplicate with #1552 ?

**Comment by juzhiyuan** [comment]
@guoqqqi Please take a look at the documentation, to check if this field is optional.

**Comment by guoqqqi** [comment]
![image](https://user-images.githubusercontent.com/72343596/109950454-7bd1d100-7d17-11eb-9ea1-916b8f3bb09b.png)
Hi, I checked the documentation and it does not state that it is optional, we can see the information here：
https://apisix.apache.org/docs/apisix/health-check/

**Comment by juzhiyuan** [comment]
fine, I notice that there has no `optional` field, then it should be required.

![image](https://user-images.githubusercontent.com/2106987/109953544-2992af00-7d1b-11eb-8c1c-ef7300c3edc0.png)

@guoqqqi Please create a issue to improve this doc, e.g use a table to list all parameters would be more clear.
