### ISSUE TITLE
health check disable not work

### ISSUE THREAD

**Issue by to2false** [apache/apisix-dashboard#1552]
# Bug report

## Describe the bug

disabled health check in one upstream, it still in checking.

## How to Reproduce

1. Go to one upstream
2. Click on health check switch button to disable it
3. Submit it
4. Check apisix log, it still prints check warning log

## Expected behavior

no more checks

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version: docker apache/apisix-dashboard:2.4
- Apisix version: apisix 2.3-centos

**Comment by juzhiyuan** [comment]
@to2false Hi, would you please take a look at etcd, to see if the data is incorrect?

**Comment by nic-chen** [comment]
@to2false 
would you please take a look at etcd:
```
$ etcdctl get --prefix /apisix/upstream
```

**Comment by to2false** [comment]
ok, I'll give feedback tomorrow morning.

**Comment by to2false** [comment]
sorry, I got the wrong version in the test environment, this problem happened on the old version. 
The new version looks like it has fixed the problem.

**Comment by nic-chen** [comment]
> sorry, I got the wrong version in the test environment, this problem happened on the old version.
> The new version looks like it has fixed the problem.

OK, thanks for the feedback.
