### ISSUE TITLE
discuss: select upstream in the "Define API Backend Server" should provide a search function

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1555]
# Feature request

## Please describe your feature

When selecting upstream in `Define API Backend Server` in `Create Route`, the function of searching upstream should be provided. Because the current selection of the upstream part is displayed through a list. When there are many upstreams, it is not easy for us to select the designated upstream. When choosing upstream, it would be better to provide a search upstream function.

<img width="721" alt="截屏2021-03-04 下午5 18 27" src="https://user-images.githubusercontent.com/52862365/109941073-b8003400-7d0d-11eb-8b6e-cd4b364301f4.png">

## Describe the solution you'd like

When `Select Upstream`, the function of searching upstream should be added.

**Comment by nic-chen** [comment]
agree +1 
I think it's good for users.

**Comment by starsz** [comment]
Agree +1.
Good ideal.

**Comment by Jaycean** [comment]
Agree +1.

**Comment by bisakhmondal** [comment]
Can I open a PR? I have made the required changes😅

**Comment by stu01509** [comment]
Hi @bisakhmondal 

Are you working on this issue?

**Comment by bisakhmondal** [comment]
Hii buddy, thanks for asking. Yep, had some free time, so I made the small changes required for the feature.
Btw, is there any issue @stu01509?

**Comment by juzhiyuan** [comment]
> Can I open a PR? I have made the required changes😅

@bisakhmondal  Of course :)
