### ISSUE TITLE
discuss: the "Host" in the active health check should be optional

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1563]
# Feature request

## Please describe your feature

In the active health check, Host is the host name of the HTTP request used to discover the health of the upstream node. It is required only when the upstream node has restrictions on Host, otherwise it is optional. In the current active check configuration, `Host` is a required option. I think it would be better if Host should be an optional.

<img width="889" alt="截屏2021-03-08 下午1 50 55" src="https://user-images.githubusercontent.com/52862365/110280058-25190f80-8015-11eb-921b-f871da090efa.png">

## Describe the solution you'd like

It would be better if the `Host` configuration is an option in the active check configuration.

**Comment by juzhiyuan** [comment]
@guoqqqi I remember there was a similar issue, right

**Comment by guoqqqi** [comment]
Yes, please refer to #1551.

**Comment by moonming** [comment]
IMO, "host" should be optional.
@nic-chen @membphis please check the lua-resty-healthcheck.
@Firstsawyou this issue should @ to apisix too. It is not just a FE issue

**Comment by moonming** [comment]
What does the text hint in the input box mean?
“active host” is confusing

**Comment by nic-chen** [comment]
> IMO, "host" should be optional.
> @nic-chen @membphis please check the lua-resty-healthcheck.
> @Firstsawyou this issue should @ to apisix too. It is not just a FE issue

OK, I will check the lib ` lua-resty-healthcheck` to confirm it.

**Comment by membphis** [comment]
> IMO, "host" should be optional.

agree this +1

**Comment by juzhiyuan** [comment]
done
