### ISSUE TITLE
The upstream timeout unit is seconds instead of milliseconds

### ISSUE THREAD

**Issue by dickens7** [apache/apisix-dashboard#1565]
![image](https://user-images.githubusercontent.com/41516298/110411578-c8296200-80c5-11eb-90af-fe53965a69bf.png)

**Comment by nic-chen** [comment]
@juzhiyuan  it's in seconds. see:

https://github.com/apache/apisix/blob/master/apisix/balancer.lua#L108
https://github.com/apache/apisix/blob/master/apisix/balancer.lua#L23

https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#set_timeouts

**Comment by juzhiyuan** [comment]
OK

**Comment by stu01509** [comment]
I want to fix this issue, please assign this issue to me.

**Comment by nic-chen** [comment]
ok, thanks. @stu01509

**Comment by iamayushdas** [comment]
@stu01509 have you resolved the issue. if not then i would like to work on it
@nic-chen

**Comment by nic-chen** [comment]
ping  @stu01509

**Comment by stu01509** [comment]
Hi @nic-chen sir

I sent the PR, Please review it :)
