### ISSUE TITLE
docker-compose building apisix image is failing (for e2e backend test)

### ISSUE THREAD

**Issue by bisakhmondal** [apache/apisix-dashboard#1581]
# Bug report

## Describe the bug
Currently, the compose file located in `/api/test/docker` directory needs a `Dockerfile-apisix` for spinning up two apisix docker containers.
https://github.com/apache/apisix-dashboard/blob/48e66cded1f4f7b67d37a9f1337fca492d6f44f5/api/test/docker/docker-compose.yaml#L128-L132

But in the mentioned directory there is no such file.
<pre>
.
├── apisix_config2.yaml
├── apisix_config.yaml
├── apisix_logs
├── docker-compose.yaml
├── Dockerfile
├── manager-api-conf.yaml
└── upstream.conf
</pre>
It should be present in the mentioned path as per the [docs](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/back-end-e2e.md#start-with-docker-compose), resulting in a failure in starting up the required containers.

## How to Reproduce
```bash
cd api/test/docker


docker-compose build
#or 
docker-compose up
```

## Screenshots

![image](https://user-images.githubusercontent.com/41498427/110947400-1bb9db00-8366-11eb-9d0a-99ba5eeed32e.png)

## System information

Linux turing 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thank you.

**Comment by Jaycean** [comment]
@bisakhmondal 
Hi, The missing dockerfile can be found in this project(https://github.com/apache/apisix-docker). You can download the dockerfile in alpine-dev.

**Comment by bisakhmondal** [comment]
Thank you. Docker-compose is working now.

**Comment by bisakhmondal** [comment]
After going through the workflow [config file](https://github.com/apache/apisix-dashboard/blob/master/.github/workflows/backend-e2e-test.yml), I see why it is not present. I think it would be a better idea if we add a script to help spinning up all the containers including altering the `conf.yaml` file and add an option to revert back to the previous config for the sake of completeness of this [doc](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/back-end-e2e.md#start-with-docker-compose). What do you say :)

**Comment by nic-chen** [comment]
> After going through the workflow [config file](https://github.com/apache/apisix-dashboard/blob/master/.github/workflows/backend-e2e-test.yml), I see why it is not present. I think it would be a better idea if we add a script to help spinning up all the containers including altering the `conf.yaml` file and add an option to revert back to the previous config for the sake of completeness of this [doc](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/back-end-e2e.md#start-with-docker-compose). What do you say :)

That's great! Welcome to update the [doc](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/back-end-e2e.md) from your perspective.

**Comment by bisakhmondal** [comment]
> That's great! Welcome to update the [doc](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/back-end-e2e.md) from your perspective.

Sure. Thanks for the assent :D
