### ISSUE TITLE
Config Plugin button enable status

### ISSUE THREAD

**Issue by stu01509** [apache/apisix-dashboard#1586]
# Bug report

## Describe the bug
I think if the plugin's current status is `enable`, the button text should be `disable`.

## How to Reproduce

1. Click the Plugin List
2. Click Create button
3. See the plugin list

## Screenshots
![image](https://user-images.githubusercontent.com/22230889/111025732-0b1a6b00-8421-11eb-9dca-778fc272fca0.png)

## System information

- OS: [e.g. macOS, Windows] Windows 10
- Browser (if applies) [e.g. Chrome, Safari, Edge] Chorme
- Version: [e.g. 2.0-rc3] 80

## Additional context

If it is a bug, I would like to fix it:)

**Comment by juzhiyuan** [comment]
ya, we use a `blue` background now, welcome to send a PR to improve this.
