### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by stu01509** [apache/apisix-dashboard#1596]
# Bug report

## Describe the bug
Hi all
I found when I switch the language to the **English** on some page and element still used the **Chinese**

## How to Reproduce

1. Go to Route List
2. See the error

## Screenshots
- Route List
![image](https://user-images.githubusercontent.com/22230889/111227652-db848200-861d-11eb-9db5-8e30472d24e0.png)
![image](https://user-images.githubusercontent.com/22230889/111227703-efc87f00-861d-11eb-91e3-dd98dde06a25.png)

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

## Additional context
If it is a bug, I would like to solve it.

**Comment by nic-chen** [comment]
great, we could check other place, and fix them all.

**Comment by juzhiyuan** [comment]
Hi @stu01509, we just merged a PR https://github.com/apache/apisix-dashboard/pull/1538

This PR fixes most of the translation issues, @guoqqqi Please recheck if those issues exist.

**Comment by imjoey** [comment]
@stu01509 thanks for reporting and assign this to you. Let's wait for the confirmation from @guoqqqi .

**Comment by guoqqqi** [comment]
Hi, @stu01509 This issue has been fixed and you can see it by updating the master branch code, (which requires deleting the local cache, node_modules and .umi).
![image](https://user-images.githubusercontent.com/72343596/111278785-ec141700-8674-11eb-884e-50d5e4724bed.png)

**Comment by stu01509** [comment]
Hi @nic-chen, @juzhiyuan, @imjoey, and @qiujiayu 

After I recheck, Almost the translation error has been solved, but I still found in the System Status uptime field mixed some Chinese.
![image](https://user-images.githubusercontent.com/22230889/111294969-d3602d00-8685-11eb-8923-38c89babcb95.png)

**Comment by guoqqqi** [comment]
Yes, there are still some problems here. @stu01509 Can you help fix it?

**Comment by stu01509** [comment]
> Yes, there are still some problems here. @stu01509 Can you help fix it?

Sure 😃
