### ISSUE TITLE
Backend API Cookie secret

### ISSUE THREAD

**Issue by stu01509** [apache/apisix-dashboard#1609]
# Bug report

## Describe the bug
Hi all

I found in `apisix-dashboard/api/internal/route.go`, the cookie secret directly setting in the codebase, I think it may need to use `api/conf/conf.yaml` or env file to set it.
https://github.com/apache/apisix-dashboard/blob/master/api/internal/route.go#L58

![image](https://user-images.githubusercontent.com/22230889/111506867-09d0a180-8785-11eb-9408-3cc3fb0cfeb3.png)

**Comment by juzhiyuan** [comment]
cc @nic-chen @starsz to confirm.

**Comment by nic-chen** [comment]
oh, we don't use sessions, we could remove it.

**Comment by juzhiyuan** [comment]
ok, then it's not a high vulnerability issue? we could mark it as `good first`?

**Comment by nic-chen** [comment]
> ok, then it's not a high vulnerability issue? we could mark it as `good first`?

It's not. This code is not used.

**Comment by starsz** [comment]
Good capture. @stu01509

**Comment by stu01509** [comment]
I will fix it in tonight, please assign the issue to me.
