### ISSUE TITLE
Optimized front-end e2e test time

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1614]
# Feature request
Currently the front-end e2e test takes 30-40 minutes to run through the test, which takes too long, we need to do something to reduce the time
![image](https://user-images.githubusercontent.com/31329157/111570693-509fb500-87e0-11eb-87b9-78260cc96187.png)

## Describe alternatives you've considered
 - [ ] Caching node_modules
 - [ ] Parallel running front-end e2e tests
 
refer link: https://docs.cypress.io/guides/continuous-integration/github-actions.html#Parallelization

**Comment by juzhiyuan** [comment]
don't forget to add label
