### ISSUE TITLE
when creating a `Service`, `Select Upstream` should be optional, not required

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1616]
# Feature request

## Please describe your feature

Currently, when creating a `Service` in the Dashboard, it is found that `upstream` is a required option. I think this is unreasonable, because when creating a service in APISIX, `upstream` is optional, and we should keep the configuration consistent with APISIX.
<img width="1138" alt="截屏2021-03-18 下午5 03 52" src="https://user-images.githubusercontent.com/52862365/111600675-9b372680-880c-11eb-95ab-f1824aded21e.png">

For example, in APISIX, when we only need to use the plugin on the service, upstream may not be configured.

```shell
curl http://127.0.0.1:9080/apisix/admin/services/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "name": "my_service",
    "plugins": {
        "limit-count": {
            "count": 2,
            "time_window": 10,
            "rejected_code": 503,
            "key": "remote_addr"
        }
    }
}'
```

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "name": "my_route",
    "uri": "/hello",
    "service_id": 1,
    "upstream": {
        "nodes": {
            "127.0.0.1:1980": 1
        },
        "type": "roundrobin"
    }
}'
```

```shell
curl http://127.0.0.1:9080/hello -v
* About to connect() to 127.0.0.1 port 9080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> GET /hello HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-RateLimit-Limit: 2
< X-RateLimit-Remaining: 1
< Date: Thu, 18 Mar 2021 08:40:35 GMT
< Server: APISIX/2.3
< 
1980
```

## Describe the solution you'd like

When creating a `Service`, `Select Upstream` should be optional.

**Comment by juzhiyuan** [comment]
How about adding an optional `None` to the `Upstream Setector`?

**Comment by Firstsawyou** [comment]
> How about adding an optional `None` to the `Upstream Setector`?

Yes, I think it is appropriate to add an optional None.

**Comment by nic-chen** [comment]
> How about adding an optional `None` to the `Upstream Setector`?

agree +1

**Comment by stu01509** [comment]
I would like to fix it, please assign this issue to me :)
