### ISSUE TITLE
feat: Making the list page paginator a standalone component

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-dashboard#1621]
# Feature request

Making the list page paginator a standalone component.
Related #1584 
Currently, a paginator has been added to each listing page and it is hoped that this state paginator can be made into a component that can be easily called from each listing page, once it is completed we need to add test cases to it.

TODO:
- [ ] Making the list page paginator a standalone component
- [ ] Adding front-end E2E testing 

![image](https://user-images.githubusercontent.com/72343596/111771736-035a3b00-88e7-11eb-9e34-db882ce90903.png)

**Comment by LiteSun** [comment]
why we need this component?

**Comment by juzhiyuan** [comment]
ping @guoqqqi

**Comment by guoqqqi** [comment]
> why we need this component?

Yes, there is currently some duplicate code in each route that needs to be abstracted out.
![image](https://user-images.githubusercontent.com/72343596/119267480-6b980680-bc21-11eb-8243-18c4cc61ea58.png)

**Comment by LiteSun** [comment]
ok.
