### ISSUE TITLE
SSL parse failed when creating Route in v2.4

### ISSUE THREAD

**Issue by JackLiMEM** [apache/apisix-dashboard#1623]
![图片](https://user-images.githubusercontent.com/20733031/111858400-993ba780-8973-11eb-8b9d-57389a528ab5.png)

**Comment by juzhiyuan** [comment]
Hi @JackLiMEM, this issue is fixed in the master branch, and will be released next week. Could you have a try on the latest codes in the master branch? It's compatible with v2.4.

**Comment by nic-chen** [comment]
yes, this issue is fixed in the master branch. you could have a try with it.

**Comment by juzhiyuan** [comment]
I'm going to close this one, if that issue still occurred in the master branch, kindly reopen it.
