### ISSUE TITLE
Discussion: Is the name field required or not when BE create a route

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix-dashboard#1624]
## Issue description

- Fe create route `name` field is required.

- However, in BE, the `name` field is still optional. PR: #1606  adds the BE judgment on whether the `name` field is repeated when creating a `route`.

- When I use BE interface instead of FE to create route I found a problem(`127.0.0.1:9000/apisix/admin/routes POST create route`). 
- I create a `route` without inserting the `name` field, I can succeed the first time because it is not a required field, but I still do not pass in the name field in the second time, which will trigger the repeated judgment of the `name` field, resulting in the failure to create a route.

- So I think there is a problem here. my idea is:

1. The `name` field be is still not required, but the `name` field is empty, so repeated judgment is not required.
2. The `name` field of be `route` is directly changed to a required field. At present, the logic will not have the situation that multiple `name` fields are empty and cannot be added.

cc @nic-chen @starsz @tokers @imjoey @gxthrj 
Do you have any good suggestions?

**Comment by juzhiyuan** [comment]
Hi, will this issue get fixed once we use `ManagerAPI` instead of `AdminAPI`?

**Comment by Jaycean** [comment]
> Hi, will this issue get fixed once we use `ManagerAPI` instead of `AdminAPI`?

Hi, the current `name` field judgment logic is written in `ManagerAPI`, so I think we need to discuss and fix this problem.

**Comment by juzhiyuan** [comment]
cc @nic-chen to confirm

**Comment by nic-chen** [comment]
I think we could change `name` to be required when we use Manager API instead of Admin API

**Comment by starsz** [comment]
Agree with @nic-chen.
The name of route is important.

cc @membphis What's your opinion?

**Comment by membphis** [comment]
> cc @membphis What's your opinion?

change `name` to be required, LGTM ^_^

**Comment by batman-ezio** [comment]
great to see name is mark as required. we'll have more test cases to update ^_^

**Comment by gxthrj** [comment]
Agree +1 , Let `name` to be required.

**Comment by imjoey** [comment]
Since #1647 has been merged which regards the route name as mandatory, we could close this issue for now. Please feel free to reopen this if anything is unexpected. Thanks.
