### ISSUE TITLE
improve Metrics module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1627]
Here are some minor issues on the Login page we could resolve.

## TODO

- [ ] Metrics page name change to: Dashboard.
- [ ] Metrics page hint: Use browser localStorage mechanism to store Grafana links locally, as a preview page only, currently no substantive function.

**Comment by stu01509** [comment]
I would like to try this.

**Comment by iamayushdas** [comment]
does first todo meant the following change:
![Screenshot from 2021-03-22 11-42-20](https://user-images.githubusercontent.com/40708551/111947694-f8302680-8b03-11eb-82de-a42f931adca5.png)

@juzhiyuan

**Comment by juzhiyuan** [comment]
ya
