### ISSUE TITLE
When creating a route, the upstream cannot select ‘none’

### ISSUE THREAD

**Issue by StretchV** [apache/apisix-dashboard#1643]
## Issue description

When creating a route, the upstream cannot select ‘none’，
## Expected behavior

I configured the service, hoping to select "None" in the upstream

## Environment

* apisix version (cmd: `apisix version`):2.3
* OS (cmd: `uname -a`):UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* {"hostname":"wpm-HP-ENVY-x360-Convertible-15-dr1xxx","up_time":14555,"boot_time":1616405157,"etcd_version":"3.4.0","id":"2f194fc9-968d-4e03-8066-14404ae354a9","last_report_time":1616419678,"version":"2.3"}
* apisix-dashboard version, if have:2.3

**Comment by stu01509** [comment]
I think it duplicates with #1616

**Comment by juzhiyuan** [comment]
ya

**Comment by juzhiyuan** [comment]
@iamayushdas Please have a check if this issue gets fixed, if yes, then cc me to close this issue :) Thanks

**Comment by iamayushdas** [comment]
> @iamayushdas Please have a check if this issue gets fixed, if yes, then cc me to close this issue :) Thanks

Ok

**Comment by iamayushdas** [comment]
> @iamayushdas Please have a check if this issue gets fixed, if yes, then cc me to close this issue :) Thanks

No its not :(
![Screenshot from 2021-05-04 21-00-49](https://user-images.githubusercontent.com/40708551/117029074-f1f4b300-ad1b-11eb-8863-54b4ceb44c5d.png)

**Comment by iamayushdas** [comment]
Do you want me to fix this @juzhiyuan ?

**Comment by juzhiyuan** [comment]
ok, I see what happened. `None` is only available when creating a Service. When creating Route, we can't use `None` here. Consider closed.

**Comment by iamayushdas** [comment]
okay cool
