### ISSUE TITLE
How to let users know the version correspondence between Dashboard and APISIX

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1652]
# Feature request

## Please describe your feature

The current README.md document of Dashboard explains the version correspondence between Dashboard and APISIX.

![image](https://user-images.githubusercontent.com/52862365/112118596-7e796500-8bf7-11eb-95a3-ce656271a4de.png)

However, many users do not seem to pay attention to these prompt messages. When installing Dashboard and APISIX, they often appear that their version relationship does not match, and an error message appears. For example, deploy Dashboard 2.4 and APISIX 2.4:

<img width="459" alt="截屏2021-03-23 下午4 50 43" src="https://user-images.githubusercontent.com/52862365/112118749-a4066e80-8bf7-11eb-9b27-a0d66f5acd12.png">

But this does not seem to affect the use of Dashboard and APISIX. Therefore, I think that when the Dashboard and APISIX versions do not match (within a relatively small version difference), we should not prompt an error message on the Dashboard page, but prompt a warning message and give the Dashboard and APISIX adaptation Version Information. In this way, users can solve whether they need to update to an adapted version according to the prompt information.

## Describe the solution you'd like

When the Dashboard and APISIX versions do not match (within a relatively small version difference), we should not prompt an error message on the Dashboard page, but prompt a warning message and give the Dashboard and APISIX adaptation version information. In this way, users can solve whether they need to update to an adapted version according to the prompt information.

**Comment by juzhiyuan** [comment]
@nic-chen @starsz  Could API provide more information about CP & DP versions?

**Comment by starsz** [comment]
> @nic-chen @starsz Could API provide more information about CP & DP versions?

Yes.The API can provide the info like:

The apisix version is xxx, and recommends using dashboard version xxx.

**Comment by juzhiyuan** [comment]
ok, just provide something like:

```json
{
  "current_version": {
     "apisix": "",
     "dashboard": "",
   },
  "expected_version": {
     "apisix": "",
     "dashboard": "",
   }
}
```

**Comment by nic-chen** [comment]
I took a look at the code, and it seems that there is no version number that should match in the output @starsz

**Comment by starsz** [comment]
> I took a look at the code, and it seems that there is no version number that should match in the output @starsz

We can support it.

**Comment by liuxiran** [comment]
https://github.com/apache/apisix-dashboard/issues/1944
