### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#1656]
When will the next version be released? The current dashboard is adapted to the apisix2.3 version, when can it be adapted to the apisix2.4 version?

**Comment by juzhiyuan** [comment]
We are going through the release process today by @nic-chen, and will be released when the Vote is passed 3 days later.

BTW, you could subscribe our mailing list to get the latest news: https://apisix.apache.org/docs/general/subscribe-guide

**Comment by Caelebs** [comment]
Roger that
