### ISSUE TITLE
doc: Improve docs about route import and export

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1660]
Our current doc about route import is too simple, see:
https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/IMPORT_OPENAPI_USER_GUIDE.md

We need to supplement doc about route export.
The docs should be described in more detail.
Such as:
1. What does the imported content include?
2. How to deal with duplicate imported routes
3. Import standard swagger documents, how to deal with data that apisix does not have
4. What data to export
5. When exporting, apisix has it, but what will happen to the data that is not in the swagger standard?
etc..

**Comment by batman-ezio** [comment]
are there any existing documents  can refer to ? 
what about put some steps and screenshoots  the document and list success and fails cases?

**Comment by nic-chen** [comment]
> are there any existing documents can refer to ?
> what about put some steps and screenshoots the document and list success and fails cases?

updated. thanks for reminding.

**Comment by liuxiran** [comment]
duplicate with #1646 

@nic-chen sorry for late response for this issue, and pr is on the way

**Comment by nic-chen** [comment]
> duplicate with #1646 
> 
> 
> 
> @nic-chen sorry for late response for this issue, and pr is on the way

thanks for remind. but the issue id seems wrong…

**Comment by liuxiran** [comment]
> > duplicate with #1646
> > @nic-chen sorry for late response for this issue, and pr is on the way
> 
> thanks for remind. but the issue id seems wrong…

it should be https://github.com/apache/apisix-dashboard/issues/1660

**Comment by juzhiyuan** [comment]
why not assign labels for this issue?
