### ISSUE TITLE
当编辑已有路由，修改重定向这个内容，由禁用改为 启用https的时候，提交报10005

### ISSUE THREAD

**Issue by logonmy** [apache/apisix-dashboard#1665]
![image](https://user-images.githubusercontent.com/3469202/112290052-d1bbe800-8cc9-11eb-8df3-ff866be55806.png)
看我的截图，提示，我是编辑已经存在的路由。

**Comment by batman-ezio** [comment]
which version are you use? i find a fix at https://github.com/apache/apisix-dashboard/pull/1527 and will release soon at 2.5 version

**Comment by logonmy** [comment]
> which version are you use? i find a fix at #1527 and will release soon at 2.5 version

thank you, version is 2.4.
