### ISSUE TITLE
Select Upstream may have a function matching upstreams by enter keyword 

### ISSUE THREAD

**Issue by wangruozhu** [apache/apisix-dashboard#1669]
# Feature request

## Please describe your feature

In old dashboard, apisix's version is 1.0 or earlier, when I edit the route, I can enter keyword to match the upstream.
Now, the new apisix-dashboard seems not have this function.
I which to add this function because some company have so much upstreams, even hundreds of thousands. And use select takes too much time to look for the correct upstream.

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/pull/1589

Hi, just to make sure, do you mean this feature?

**Comment by wangruozhu** [comment]
yes, it is the same.
