### ISSUE TITLE
feat: show http response header in debug view

### ISSUE THREAD

**Issue by qian0817** [apache/apisix-dashboard#1680]
# Feature request

## Please describe your feature

Currently only the response body is displayed, consider displaying the response header and response code at the same time.

![image](https://user-images.githubusercontent.com/45898769/112619435-4b86d980-8e62-11eb-8777-5bdc38e27989.png)

**Comment by stu01509** [comment]
I would like to try this.

**Comment by juzhiyuan** [comment]
@stu01509 Hi, how about resolving other issues first? and I remember you have the GSoC task 🤔

**Comment by stu01509** [comment]
Hi @juzhiyuan 

Actually, I almost have resolving other issues, waiting for merge and pass the test case, 
and also  @nic-chen recommend me to do more PR about the Backend issue.

**Comment by juzhiyuan** [comment]
ok got it, assign to you :)
