### ISSUE TITLE
Updating URI of an existing route causes 404 error

### ISSUE THREAD

**Issue by bisakhmondal** [apache/apisix-dashboard#1682]
## Issue description

If I update the uris of an already created route, necessary effects are getting taken for the old uris name, but for the new ones, it is causing a 404 nginx/openresty error.

## Expected behavior

The update should either take place or not, if the manager-api is able to update it should display the upstream content, else the apisix should send an error. But in this case the error is shown from nginx.

## How to Reproduce
1. Running all the containers. `./setup.sh up`
2. make a put request to managerapi for URI `hello` & route id r1
[PUT] http://localhost:9000/apisix/admin/routes/r1
```json
{
 "name": "route1",
 "uri": "/hello",
 "methods": ["GET"],
  "upstream": {
	"type": "roundrobin",
	 "nodes": [{
		"host": "172.16.238.20",
		 "port": 1980,
		"weight": 1
		 }]
	 }
 }
```
3. Now making an update request with uri `newhello` keeping the same upstream
[PUT] http://localhost:9000/apisix/admin/routes/r1
```json
{
 "name": "route1",
 "uri": "/newhello",
 "methods": ["GET"],
  "upstream": {
	"type": "roundrobin",
	 "nodes": [{
		"host": "172.16.238.20",
		 "port": 1980,
		"weight": 1
		 }]
	 }
 }
```
It disables the old route. but for the updated route it is throwing an Nginx error.
## Screenshots
after making the first API call
![image](https://user-images.githubusercontent.com/41498427/112726504-d5f33a00-8f43-11eb-987e-af199f7f2f6e.png)

**After updating the uri**
 The old uri
![image](https://user-images.githubusercontent.com/41498427/112726587-413d0c00-8f44-11eb-9028-1623d50881f1.png)

The new URI
![image](https://user-images.githubusercontent.com/41498427/112726613-5ca81700-8f44-11eb-9d93-1cba6f798021.png)

## Environment
Running the tests using docker-compose services.
```sh
./api/test/docker/setup.sh up
```
* OS (cmd: `uname -a`): Linux turing 5.8.0-44-generic 50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* apisix-dashboard version, if have: 2.4
* Browser version, if have: Google Chrome Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by starsz** [comment]
The URI in route is `/newhello` , but the URI in the browser `/hellonew`.

Please check about it.

**Comment by bisakhmondal** [comment]
> The URI in route is `/newhello` , but the URI in the browser `/hellonew`.
> 
> Please check about it.

Sorry, my bad. I have mistakenly put yesterday's screenshots. It's updated now. Thank you.

**Comment by nic-chen** [comment]
@bisakhmondal 
what is the content in nginx.conf
and is there error log for this？

**Comment by bisakhmondal** [comment]
Thanks, @nic-chen, @starsz for looking into this. Actually, the error has nothing to do with manager-api. Thanks to @Jaycean, only `/hello`, `/hello_` and `/hello1` routes are whitelisted on the upstream docker image that we are currently using for testing [ [ref](https://github.com/apache/apisix-dashboard/pull/1675#issuecomment-809023973) ]. So in the case of `newhello` it's a 404 from upstream itself.

The issue isn't relevant anymore to keep it open. 

Thanks again, everyone. Closing.
