### ISSUE TITLE
request help: What’s the function of export OpenAPI on the dashboard

### ISSUE THREAD

**Issue by aiyiyi121** [apache/apisix-dashboard#1687]
### Issue description
 What’s the function of export OpenAPI on the dashboard,  why can't I export the configuration of routes and upstreams correctly through it.
And how can I export API configuration to yaml configuration?

### Environment

apisix version (cmd: apisix version): 2.4
OS (cmd: uname -a): Ubuntu 16.04.2 LTS
OpenResty / Nginx version (cmd: nginx -V or openresty -V): openresty/1.19.3.1
etcd version, if have (cmd: run curl http://127.0.0.1:9090/v1/server_info to get the info from server-info API): 3.4.13
apisix-dashboard version, if have: 2.4

**Comment by nic-chen** [comment]
please give some detail about how to reproduce it

**Comment by aiyiyi121** [comment]
> please give some detail about how to reproduce it, thanks.

Just use the function "导出 OpenAPI" on the dashboard, and it exports data like:

```components: {}
info:
  title: RoutesExport
  version: 3.0.0
openapi: 3.0.0
paths:
  /acm: {}
  /{params}: {}
  /{params}-APISIX-REPEAT-URI-3: {}
  /{params}-APISIX-REPEAT-URI-4: {}
  /{params}-APISIX-REPEAT-URI-5: {}
```
Is it right?

**Comment by Jaycean** [comment]
> > please give some detail about how to reproduce it, thanks.
> 
> Just use the function "导出 OpenAPI" on the dashboard, and it exports data like:
> 
> ```
> info:
>   title: RoutesExport
>   version: 3.0.0
> openapi: 3.0.0
> paths:
>   /acm: {}
>   /{params}: {}
>   /{params}-APISIX-REPEAT-URI-3: {}
>   /{params}-APISIX-REPEAT-URI-4: {}
>   /{params}-APISIX-REPEAT-URI-5: {}
> ```
> 
> Is it right?

Please provide the detailed data of the export route. Or check if the methods are set in the route data. If not, refer to the issue: #1668. We are repairing it.

**Comment by aiyiyi121** [comment]
> Please provide the detailed data of the export route. Or check if the methods are set in the route data. If not, refer to the issue: #1668. We are repairing it.
Thanks，it works
