### ISSUE TITLE
可以为2.5版本提供rpm包下载么？

### ISSUE THREAD

**Issue by belongwqz** [apache/apisix-dashboard#1694]
# Feature request

## Please describe your feature

可以为2.5版本提供rpm包下载么？

## Describe the solution you'd like

一般内公司内网无法访问很多golang语言包，自行编译难以实现，如果可以提供编译好的rpm包会比较方便，2.4版本有提供的，2.5咋没了。

**Comment by moonming** [comment]
@juzhiyuan @nic-chen can CI build RPM package?

**Comment by juzhiyuan** [comment]
@nic-chen will provide the RPM first, and we will try to support CI to build RPM.

**Comment by nic-chen** [comment]
@belongwqz  we have uploaded the rpm package, please have a look.

**Comment by juzhiyuan** [comment]
It's here https://github.com/apache/apisix-dashboard/releases

I will close this issue now :) if you have any problems, please let us know :)

**Comment by belongwqz** [comment]
> @belongwqz we have uploaded the rpm package, please have a look.

I saw, 3Q!
