### ISSUE TITLE
Translation error in plugin page

### ISSUE THREAD

**Issue by stu01509** [apache/apisix-dashboard#1700]
## Issue description
Hi all

I found when I switch the language to English on plugin page and element still used the Chinese

## How to Reproduce

1. Go to the plugin page.
2. Click on create plugin button.
3. See translation error

## Screenshots

![image](https://user-images.githubusercontent.com/22230889/113156843-f2a5af80-926c-11eb-9ffe-79f97c809a2d.png)

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

**Comment by iamayushdas** [comment]
resolved in  #1685

**Comment by juzhiyuan** [comment]
Hi @stu01509, if this error goes away after syncing your repo, kindly close this issue :)

**Comment by stu01509** [comment]
Hi @juzhiyuan  and @iamayushdas 

Yeah, this issue has been solved in #1685, so close this issue.
