### ISSUE TITLE
security: support HTTPS for dashboard

### ISSUE THREAD

**Issue by moonming** [apache/apisix-dashboard#1706]
# Feature request

## Please describe your feature

Now dashboard does not support HTTPS access, which is not safe and easy to be hijacked and sniffed.

## Describe the solution you'd like

We should support HTTPS access. How about adding Apache APISIX in front of the manager API?

**Comment by bisakhmondal** [comment]
Hii, are we planning to run manager-api as https server with tls configs?

**Comment by moonming** [comment]
@nic-chen @membphis

**Comment by nic-chen** [comment]
> Hii, are we planning to run manager-api as https server with tls configs?

sure, PR is welcome!

**Comment by moonming** [comment]
@nic-chen you need to discuss how to implement this feature first

**Comment by membphis** [comment]
@nic-chen ping

**Comment by nic-chen** [comment]
The discussion email has been sent.

**Comment by membphis** [comment]
I suggest posting the email discussion address here. It is easier for reading

**Comment by nic-chen** [comment]
sure. 
here is the discussion thread: 
https://lists.apache.org/thread.html/r082c75e50b3c2445a4e15c012a267ea1f4844f2dac5ab02fa6508a41%40%3Cdev.apisix.apache.org%3E
