### ISSUE TITLE
The name rule is not applied to every name input

### ISSUE THREAD

**Issue by batman-ezio** [apache/apisix-dashboard#1711]
# Feature request

## currently we only check the name format in route's name use regexp, 
with below code in frontend
![image](https://user-images.githubusercontent.com/80014017/113649753-935afb80-96c1-11eb-8ee5-d4cb28929606.png)

```
 {
            pattern: new RegExp(/^[a-zA-Z][a-zA-Z0-9_-]{0,100}$/, 'g'),
            message: formatMessage({ id: 'page.route.form.itemRulesPatternMessage.apiNameRule' }),
          }
```

but in other place, like Upstream, Service ... , we allow to input any chars

## Describe the solution you'd like

extract the rule to global, and apply to all name fields

**Comment by stu01509** [comment]
Hi @juzhiyuan 

I would like to solve this issue, could you tell me which pattern we need?

**Comment by juzhiyuan** [comment]
Hi, @stu01509 I'm back, this issue will be resolved by https://github.com/apache/apisix-dashboard/pull/1799
