### ISSUE TITLE
Wildcard SSL certificate is not available

### ISSUE THREAD

**Issue by Hcreak** [apache/apisix-dashboard#1716]
## Issue description

I added a wildcard certificate in the dashboard.
When I added the route and turned on HTTPS redirection, the error was reported as follows:

```
Request Error Code: 10000
SSL cert not exists for sni：...............
```
## Expected behavior

The specified domain name can use the corresponding wildcard certificate

## How to Reproduce

1. Go to SSL page and Add corresponding wildcard certificate
2. Go to Create Route page
2. specified domain name And turned on HTTPS redirection
3. Scroll down to Next

## Screenshots

![image](https://user-images.githubusercontent.com/15710701/113962835-13689900-985b-11eb-98c0-17d28c6f3e62.png)

## Environment

* apisix version (cmd: `apisix version`):  apache/apisix:2.3-centos docker image
* OS (cmd: `uname -a`): 
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):  3.4.14
* apisix-dashboard version, if have: master branch
* Browser version, if have:

**Comment by juzhiyuan** [comment]
Could you provide a sample wildcard cert? or where do you get the cert?

**Comment by Hcreak** [comment]
> Could you provide a sample wildcard cert? or where do you get the cert?

Let's Encrypt , Use acme.sh

**Comment by juzhiyuan** [comment]
cc @nic-chen @starsz to take a look

**Comment by starsz** [comment]
Thank you for the report. 
I check the code. It seems that manager-api don't check this situation:
1. Configure the wildcard SSL certificate.
2. Create the route using a specified domain that matches the wildcard SSL certificate.

**Comment by juzhiyuan** [comment]
Just to make sure, is it easy to fix or is it urgent for users?

**Comment by Hcreak** [comment]
Do you have any plans to fix this bug in the next version?

**Comment by starsz** [comment]
> Do you have any plans to fix this bug in the next version?

Yes. This is a serious bug. We will fix it as soon as possible.
Maybe today.

**Comment by nic-chen** [comment]
@Hcreak  thinks for feedback, we will fix it ASAP

**Comment by starsz** [comment]
Hi, @Hcreak.
Sorry, I can't reproduce this error.
Do you mean this?

Step 1: create a wildcard certificate like *.apisix.com
![image](https://user-images.githubusercontent.com/25628854/114256797-75a5d300-99ee-11eb-9784-55161841060a.png)

Step 2: Create a route with xx.apisix.com
![image](https://user-images.githubusercontent.com/25628854/114256822-a0902700-99ee-11eb-9765-dc7b2d45857c.png)

Step 3: Turn on the HTTPS redirection.

I can create it successfully.

Can you add some details about it?

**Comment by Hcreak** [comment]
Wildcard certificate for two domain names Please test

**Comment by Hcreak** [comment]
I seem to have found the reason. I specified the fourth-level domain name in the route，but I used second-level domain name wildcard certificate
