### ISSUE TITLE
before login dashboard,there occurs an error:  /apisix/admin/tool/version_match 401 (Unauthorized)

### ISSUE THREAD

**Issue by xiaotaibai2008** [apache/apisix-dashboard#1717]
## Issue description

when open dashboard in  web browser,there occurs a error:Failed to load resource: the server responded with a status of 401 (Unauthorized)
## Expected behavior

 no such error 

## How to Reproduce

when type "ip-address :9000" in web browser ,then the website redirect to login page ;
press F12 ,there is an error occurs 

## Screenshots

![image](https://user-images.githubusercontent.com/24215735/113976060-03f54a00-9873-11eb-8808-507846cba0e0.png)

## Environment
![image](https://user-images.githubusercontent.com/24215735/113976120-271ff980-9873-11eb-8e0f-293be7d1ded6.png)

**Comment by bisakhmondal** [comment]
Hii, It seems the dashboard is making a GET request to the backend without a valid authorization token. And it's obvious when the user hasn't still logged in. I think as a solution, we can check the `localstorage` for the token, if present only then we will send the GET request to the backend. How does it sound to you @juzhiyuan? :)

**Comment by juzhiyuan** [comment]
good for me :)

**Comment by bisakhmondal** [comment]
Cool😄. Should I open a PR or let the others pick it up!!

**Comment by juzhiyuan** [comment]
oh sure!
