### ISSUE TITLE
change: remove ID of consumer

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1742]
# Feature request

## Please describe your feature

APISIX has removed the consumer id in version 2.5. 

Dashboard also needs to remove the consumer id before it can be used with APISIX 2.5 and above.

## Describe the solution you'd like

1. Sync schema from APISIX 2.5 version
2. Remove the id field from the consumer's struct
3. Modify related test cases

**Comment by juzhiyuan** [comment]
FE will use `username` as identify.
