### ISSUE TITLE
change: remove `listen.host` from api/conf/conf.yaml

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#1743]
# Feature request

## Please describe your feature

The configuration item `listen.host` in conf.yaml often confuses users, because when the configuration dashboard can be accessed non-locally, two places need to be modified (the other place is `allow_list`).
We can remove the `listen.host` configuration item from conf.yaml, but retain the feature, and users can add it when they need it.

## Describe the solution you'd like

1. remove `listen.host` from api/conf/conf.yaml
2. set `ServerHost` in [the code](https://github.com/apache/apisix-dashboard/blob/master/api/internal/conf/conf.go#L47
) to an empty string

**Comment by starsz** [comment]
I am confused about the PR and this issue.
Are they related to each other？

**Comment by starsz** [comment]
`list.host` also confuse me.Do you mean `listen.host` ?

**Comment by nic-chen** [comment]
> `list.host` also confuses me.Do you mean `listen.host` ?
> 
> Maybe we can set the ServerHost to "0.0.0.0" because it is used in the printInfo function.

oh. typo
