### ISSUE TITLE
support icons on Plugin Marcket

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1760]
# Feature request

## Please describe your feature

Hi, we have some plugin icons for a few plugins currently, like this one:

![image](https://user-images.githubusercontent.com/2106987/114417069-dcd8a880-9be3-11eb-902c-ee97b47e3739.png)

To have a better & clearer view, we would better add plugins for those icons.

## Describe the solution you'd like

We could find some icons from `iconfont.cn`, but most can not, so we have to draw some icons by ourselves.

## Describe alternatives you've considered

None

## Additional context

We need icons in SVG format.

**Comment by iamayushdas** [comment]
Do you need help in creating icons?

**Comment by juzhiyuan** [comment]
sure! Do you have experiences on this?

**Comment by iamayushdas** [comment]
Yes i have, but not as professional, i want to give it a try if our community liked those then only we will use🙂
