### ISSUE TITLE
the `Regex` in the routing configuration cannot be displayed normally

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1768]
## Issue description

After configuring the `Regex` in the `URI Override` of the `Request Override`, when editing the route again, the configured `Regex` information cannot be displayed.

1.  Create a route and configure the `Regex` information in `URI Override`.
<img width="759" alt="截屏2021-04-14 上午11 32 36" src="https://user-images.githubusercontent.com/52862365/114651585-d7c84600-9d16-11eb-97dd-78e36d8a2e36.png">

2. Edit the route again, the `Regex` configuration information cannot be displayed, but the `Stay The Same` option is defaulted.
<img width="806" alt="截屏2021-04-14 上午11 33 43" src="https://user-images.githubusercontent.com/52862365/114651614-e9115280-9d16-11eb-9546-006159ec3607.png">

## Expected behavior

After configuring the `Regex` information in the `URI Override`, when editing the route again, the `Regex` configuration information should be displayed.

## Environment

* apisix version (cmd: `apisix version`): 2.4
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.5
* Browser version, if have:

**Comment by Engine-AI** [comment]
@juzhiyuan @moonming This problem has been solved  #1721
