### ISSUE TITLE
CI: golangci will be expected for long time

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1772]
## Issue description

Hi, I found that when we do some change on FE, the golangci will be expected for a long time.
This will lead the CI can't pass.

## Expected behavior

The golangci can be run

## How to Reproduce

1. Create a PR only change the FE
2. Then see the github action

## Screenshots

![image](https://user-images.githubusercontent.com/25628854/114734383-bc8d2300-9d76-11eb-9f79-75a4fefa7845.png)

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

## Additional context

Now, we turn off the golangci.
When we find the reason, we should turn on it.

**Comment by juzhiyuan** [comment]
resolved by Infra

**Comment by juzhiyuan** [comment]
This issue is due to incorrect settings on Actions
