### ISSUE TITLE
add missing fields for limit-count plugin (redis cluster)

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#1773]
## Issue description

Because the limit-count document(http://apisix.apache.org/docs/apisix/plugins/limit-count/) does not match the actual jsonchema(https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count.lua#L37), the missing fields need to be filled in.

refer pr: #1739 

## Expected behavior

Fields are consistent with limit-count jsonschema.

**Comment by juzhiyuan** [comment]
related issue #1775

**Comment by iamayushdas** [comment]
@juzhiyuan i think limit-count doc matches the json schema? if i am wrong could you please enlight me up?

**Comment by juzhiyuan** [comment]
Pay attention to redis cluster

**Comment by liuxiran** [comment]
Confirmed,:

**Comment by liuxiran** [comment]
Comfirmed:

**Comment by liuxiran** [comment]
Confirmed:

1. we need to update the doc for `limit-count` according to the lua code:
`redis_password ` and `redis_timeout ` can be configured both in `redis` policy and `redis-cluster` policy
now it is not specify in the [doc](http://apisix.apache.org/docs/apisix/plugins/limit-count/#attributes)

2. for current dashboard master branch, the UI form for `limit-count` plugin is already completed, we do not need to update it.

![image](https://user-images.githubusercontent.com/2561857/128670386-9d13a2d9-b823-4dd8-abbc-84a477051487.png)

![image](https://user-images.githubusercontent.com/2561857/128670466-32f0975e-d4cc-41c7-a23a-6387312ba7f7.png)

cc @juzhiyuan @LiteSun @iamayushdas

**Comment by juzhiyuan** [comment]
@liuxiran just to make sure, we could close this issue, and create a doc issue in apisix?

**Comment by liuxiran** [comment]
Yep, close it now

the issue in APISIX: https://github.com/apache/apisix/issues/4781
