### ISSUE TITLE
excuse,how to do the fuzzy search of routing in the apisix-dashboard

### ISSUE THREAD

**Issue by StretchV** [apache/apisix-dashboard#1778]
请问dashboard中路由的模糊搜索是怎么做的呢,是后台程序自己做的循环正则匹配etcd中的值吗

**Comment by StretchV** [comment]
@nic-chen 大佬可以帮解惑一下吗

**Comment by nic-chen** [comment]
hi @StretchV 

The Manager API loops to match the values ​​in cache (from ETCD), but it is not a regular match.
For the detail, please see:
https://github.com/apache/apisix-dashboard/blob/master/api/internal/core/store/store.go#L187-L195
https://github.com/apache/apisix-dashboard/blob/master/api/internal/handler/route/route.go#L222-L239

**Comment by StretchV** [comment]
感谢
