### ISSUE TITLE
bug: domain name/ip was disappeared after update

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-dashboard#1780]
### Issue description

Question 1: I update the domian name -> medcloud-dev.dental-practice-patient
and click the submit button, then i click update button again, the domian name/ip was disappeared after update

Question 2: What the  domian name/IP i should write in when i use k8cluster？if `medcloud-dev.dental-practice-patient` is supported? `medcloud-dev` is the namespace of service and `dental-practice-patient` is service name.

![image](https://user-images.githubusercontent.com/52538259/114858444-0aa83200-9e1c-11eb-932d-1cf2040d232a.png)
![image](https://user-images.githubusercontent.com/52538259/114858489-1a277b00-9e1c-11eb-8dc1-4ed9b732451b.png)

### Environment

* use apisix-helm-chart

**Comment by Marco-Zheng** [comment]
Yeap, i upgraded the apisix-dashboard to 2.5, but the problem still exsist
![image](https://user-images.githubusercontent.com/52538259/115048656-5cc88080-9f0c-11eb-945a-22ea20baba1d.png)
you can see i add an IP and save it, then click the update botton, but it is disappeared

**Comment by Marco-Zheng** [comment]
> Yeap, i upgraded the apisix-dashboard to 2.5, but the problem still exsist
> ![image](https://user-images.githubusercontent.com/52538259/115048656-5cc88080-9f0c-11eb-945a-22ea20baba1d.png)
> you can see i add an IP and save it, then click the update botton, but it is disappeared

attach the result
![image](https://user-images.githubusercontent.com/52538259/115048866-a2854900-9f0c-11eb-9cd7-8fa89220a53b.png)

**Comment by liuxiran** [comment]
> @liuxiran this problem doesn't exist in v2.7.1

got it, thanks for your checking @iamayushdas , would you please update the stable reproduce steps here, and try to fix it?
