### ISSUE TITLE
update remark in UpstreamForm when creating Service

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1787]
we will reuse `UpstreamForm` when creating a service

![image](https://user-images.githubusercontent.com/2561857/115162774-f85a1c80-a0d7-11eb-8607-2fc3c34f4e9d.png)

so remove `（仅在绑定服务时可用）` may be  more general here or change another remark ^_^

_Originally posted by @liuxiran in https://github.com/apache/apisix-dashboard/pull/1784#discussion_r615463646_

**Comment by liuxiran** [comment]
refer to #1616 , we need `None` here, just change the remark for it ^-^

**Comment by iamayushdas** [comment]
As far as i got we have to remove this 仅在绑定服务时可用 ? is it?

**Comment by juzhiyuan** [comment]
Yes
