### ISSUE TITLE
关于路由/*有效，/foo/*无效

### ISSUE THREAD

**Issue by leon1509** [apache/apisix-dashboard#1796]
## Issue description
版本：apisix-dashboard:2.4
            apisix:2.3-alpine
            etcd:3.4.9

环境：docker-compose

场景：新建上游DataQL-Demo，再创建路由DataQL-route，不加载任何插件。

现象：
路径设置为/*时
![image](https://user-images.githubusercontent.com/4725850/115326907-a3de9c00-a1c0-11eb-9b2a-cd5849585028.png)

测试结果正常：
![image](https://user-images.githubusercontent.com/4725850/115326992-c53f8800-a1c0-11eb-9534-b7885120c5bf.png)

路径设置为/foo/*时：
![image](https://user-images.githubusercontent.com/4725850/115327081-ea33fb00-a1c0-11eb-814c-70b66fbfed46.png)

测试结果404：
![image](https://user-images.githubusercontent.com/4725850/115327125-fd46cb00-a1c0-11eb-8ec9-31289a43e822.png)

**Comment by juzhiyuan** [comment]
cc @Firstsawyou to take a look

**Comment by Firstsawyou** [comment]
Hi，@leon1509  
Do you have an API for `/foo/api/user/get` in your backend service? From the response data, it is likely that there is no corresponding API in the back-end service.

**Comment by leon1509** [comment]
My back-end service is http://localhost:8080/api/user/get, I want to add /api/user/get via apisix

**Comment by nic-chen** [comment]
> My back-end service is http://localhost:8080/api/user/get, I want to add /foo[/api/user/get] via apisix

I think you could use the proxy-rewrite plugin to achieve your need:
https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-rewrite.md

**Comment by Firstsawyou** [comment]
You can also try to configure it like this in Dashboard:
<img width="921" alt="截屏2021-04-21 下午1 18 41" src="https://user-images.githubusercontent.com/52862365/115500683-62272180-a2a4-11eb-96d7-d5789b7e7e46.png">

<img width="1024" alt="截屏2021-04-21 下午1 18 55 1" src="https://user-images.githubusercontent.com/52862365/115500706-6ce1b680-a2a4-11eb-89a5-2adde9de8d26.png">

**Comment by leon1509** [comment]
> You can also try to configure it like this in Dashboard:
> <img alt="截屏2021-04-21 下午1 18 41" width="921" src="https://user-images.githubusercontent.com/52862365/115500683-62272180-a2a4-11eb-96d7-d5789b7e7e46.png">
> 
> <img alt="截屏2021-04-21 下午1 18 55 1" width="1024" src="https://user-images.githubusercontent.com/52862365/115500706-6ce1b680-a2a4-11eb-89a5-2adde9de8d26.png">

![image](https://user-images.githubusercontent.com/4725850/115688888-25375980-a38e-11eb-91f9-3d5baae00f37.png)

**Comment by juzhiyuan** [comment]
@leon1509 As for Redirect issue, it has been fixed in 2.6, and it will release today by @nic-chen

**Comment by nic-chen** [comment]
Consider resolved. If there is any problem, welcome to reopen it.

**Comment by leon1509** [comment]
@juzhiyuan 
2.6版本的也不行
![image](https://user-images.githubusercontent.com/4725850/116066663-de61a080-a6ba-11eb-8713-08055ca27310.png)

**Comment by juzhiyuan** [comment]
@leon1509 You mean Static Path doesn't show in 2.6?

**Comment by leon1509** [comment]
The requirement is actually very simple, that is, the path in the route is set to "/foo/*", how should I call it?
需求其实非常简单，就是路由里的路径设置为“/foo/*”，我应该如何调用？

The status quo is：
现在情况是：

Route path： /foo/*           --->       /foo/api//user/get --->  http status is 404
Route path:   /*                  --->      /api/user/get          --->  http status is 200

Did I describe it clearly?
不知道我描述清楚了嘛？

**Comment by leon1509** [comment]
问题已解决，方案是/foo这个前缀不是随便设置的，需要与后端的url前缀保持一致（可以是[/api/*]，也可以是[/api/user/*]！

**Comment by juzhiyuan** [comment]
https://apisix.apache.org/docs/apisix/router-radixtree

**Comment by leon1509** [comment]
@juzhiyuan 

Problem is solved, thank you
