### ISSUE TITLE
Error: while running manager-api on ubuntu 20.04.2

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-dashboard#1800]
Erro while running after successfully building upcoming release 2.6

![Screenshot from 2021-04-20 10-06-39](https://user-images.githubusercontent.com/40708551/115338378-54986b80-a1c0-11eb-8cf5-1dfd3d7cd71c.png)

@juzhiyuan @tokers @Yiyiyimu  @Jaycean

**Comment by qian0817** [comment]
Is etcd running? @iamayushdas

**Comment by iamayushdas** [comment]
Yes

**Comment by qian0817** [comment]
can you use etcdctl to connect to etcd.`context deadline exceeded` is returned by grpc client when it can't establish the connection.
