### ISSUE TITLE
DockerHub is unstable to install FE dependencies (yarnpkg)

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1801]
## Issue description

Hi, we have connected with DockerHub so it could build Image when there has a new commit to master or other branch, but it's failed to install some dependencies due to a Network error.

When I test on my local computer, I removed all dependencies and get a refresh installation, it works well as expected.

## Screenshots

![image](https://user-images.githubusercontent.com/2106987/115341754-badeb780-a1db-11eb-8b6a-b7a2c973777a.png)

![image](https://user-images.githubusercontent.com/2106987/115341782-c5994c80-a1db-11eb-84fd-87c45a56dc44.png)

## Environment

* apisix version (cmd: `apisix version`): None
* OS (cmd: `uname -a`): None
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): None
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): None
* apisix-dashboard version, if have: None
* Browser version, if have: None

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/115342149-5ec86300-a1dc-11eb-9e61-48f2cd3946dd.png)

I just disabled this auto-build temporarily, and will send a ticket to DockerHub to see what happened. https://hub.docker.com/repository/docker/apache/apisix-dashboard/builds/edit

**Comment by membphis** [comment]
> I just disabled this auto-build temporarily, and will send a ticket to DockerHub to see what happened. https://hub.docker.com/repository/docker/apache/apisix-dashboard/builds/edit

ok, got it

**Comment by liuxiran** [comment]
Hi @juzhiyuan please help to update the ticket status when you have time, thanks a lot
