### ISSUE TITLE
Question: is it a bug that users can delete all target nodes forms in upstream create page?

### ISSUE THREAD

**Issue by ericsyh** [apache/apisix-dashboard#1803]
## Issue description

When fixing the Upstream form warning message issue, i found a behavior that users can delete all target nodes forms on the page like 

![](http://piw45adv3.bkt.clouddn.com/%E6%8D%95%E8%8E%B7.PNG)

But this upstream can be created successfully. 

![](http://piw45adv3.bkt.clouddn.com/%E6%8D%95%E8%8E%B72.PNG)

## Expected behavior

Not sure is it a expected behavior.

## How to Reproduce

1. Go to 'Upstream Page'
2. Click on 'Create Button'
3. Delete all targets nodes forms

## Environment

* apisix version (cmd: `apisix version`): the master branch
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

**Comment by liuxiran** [comment]
Hi @ericsyh thanks for your report.

Acctually from the funcitonal point of view, the empty node list is a feature, see:

 `The nodes can be empty, which means it is a placeholder and will be filled later. Clients use such an upstream will get 502 response.`
(come from https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#upstream)

But from the UE point of view, an upstream can not be used with the empty node list, so keep at least one node in the node list is better.

How about add this restriction to the dashboard? 
Let's wait for others option @juzhiyuan @LiteSun @nic-chen @imjoey

**Comment by juzhiyuan** [comment]
As @liuxiran said, we actually support an empty node list, it will return a 5xx status code to the client. I would prefer keeping the current behaviour, because if users really want to do it, what they can do on the dashboard?

**Comment by nic-chen** [comment]
+1 for  keeping the current behavior

**Comment by liuxiran** [comment]
@juzhiyuan @nic-chen  keep the current behavior is also reasonable for me

If there is no objection, we will close the issue

cc @ericsyh

**Comment by ericsyh** [comment]
ok for close the issue. But i am quite interesting in what scenario that users will create a upstream with empty node list?

**Comment by juzhiyuan** [comment]
> ok for close the issue. But i am quite interesting in what scenario that users will create a upstream with empty node list?

@Firstsawyou any scenarios when users create an upstream with empty nodes?

**Comment by LiteSun** [comment]
+1 for keeping the current behavior

**Comment by Firstsawyou** [comment]
> > ok for close the issue. But i am quite interesting in what scenario that users will create a upstream with empty node list?
> 
> @Firstsawyou any scenarios when users create an upstream with empty nodes?

I have not encountered this situation. Setting the upstream with empty node, it seems that there is no usage scenario.
I will create an issue on the backend to discuss it.

**Comment by liuxiran** [comment]
Then how about leave enough space for users, that is to say, we just keep the current behavior, when users have scenarios that create an upstream with no nodes(even if we have not encountered now), they can do this through dashboard.

**Comment by starsz** [comment]
> > > ok for close the issue. But i am quite interesting in what scenario that users will create a upstream with empty node list?
> > 
> > 
> > @Firstsawyou any scenarios when users create an upstream with empty nodes?
> 
> I have not encountered this situation.

I think in some test situations. Users use the `echo plugin` to return responses. So they don't need any upstream nodes.

**Comment by nic-chen** [comment]
close now. If you have any question, welcome reopen it.
