### ISSUE TITLE
style(fe): how about changing the navigation bar to dark? 

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#1810]
![image](https://user-images.githubusercontent.com/6814606/115491834-46ffe600-a293-11eb-9fe1-d0887ccdc9f1.png)

**Comment by nic-chen** [comment]
I We can directly try to see the modified effect.

cc @LiteSun @juzhiyuan  @liuxiran  @guoqqqi

**Comment by juzhiyuan** [comment]
@membphis @nic-chen Hi, we usually call it `Left Sidebar`.

You could see this preview site: https://preview.pro.ant.design/dashboard/analysis

**Comment by nic-chen** [comment]
> @membphis @nic-chen Hi, we usually call it `Left Sidebar`.
> 
> You could see this preview site: https://preview.pro.ant.design/dashboard/analysis

the dark mode LGTM

**Comment by iamayushdas** [comment]
> > @membphis @nic-chen Hi, we usually call it `Left Sidebar`.
> > You could see this preview site: https://preview.pro.ant.design/dashboard/analysis
> 
> the dark mode LGTM

me too

**Comment by iamayushdas** [comment]
Drk mode looks good as default. should we go for it ?

![scrnli_22_04_2021_11-04-17](https://user-images.githubusercontent.com/40708551/115661277-d0c6b680-a35a-11eb-8e70-d8ff79b5c32c.png)

**Comment by guoqqqi** [comment]
We can also refer to the examples in the documentation： https://procomponents.ant.design/components/layout#menu～

**Comment by iamayushdas** [comment]
> We can also refer to the examples in the documentation： https://procomponents.ant.design/components/layout#menu

Thanks for this😊

**Comment by juzhiyuan** [comment]
> Dark mode looks good as default. should we go for it ?

Hi, we need more members to review this :)

**Comment by juzhiyuan** [comment]
cc @membphis @guoqqqi @stu01509 @qier222

**Comment by qier222** [comment]
Looks good😀

**Comment by juzhiyuan** [comment]
ok, then vote +1

**Comment by guoqqqi** [comment]
Agree +1

**Comment by iamayushdas** [comment]
+1 for sure

**Comment by stu01509** [comment]
LGTM +1

**Comment by liuxiran** [comment]
LGTM +1, dark mode draws a clear line between sidebar and content

**Comment by starsz** [comment]
LGTM +1.

**Comment by LiteSun** [comment]
Black looks more technological. LGTM+1
