### ISSUE TITLE
The manager-api and apache apisix are mismatched?

### ISSUE THREAD

**Issue by hzbd** [apache/apisix-dashboard#1811]
**Issue description**
_Request Error Code: 2000001
The manager-api and apache apisix are mismatched._

![image](https://user-images.githubusercontent.com/3000843/115493420-516faf00-a296-11eb-979f-85538325aa77.png)
**Environment**
**CentOS 7.9**
[root@xxx dashboard]# ./manager-api -v
**Version : 2.5
GitHash : 5c95d97**
[root@xxx dashboard]# apisix version
**/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
2.5**
[root@xxx dashboard]# openresty -v
**nginx version: openresty/1.19.3.1**

Is this a bug or is it a problem with my settings？

**Comment by nic-chen** [comment]
hi @hzbd  
can't use Dashboard 2.5 with APISIX 2.5, need to wait for Dashboard 2.6.

Dashboard 2.5 works with APISIX 2.4.

**Comment by forgaoqiang** [comment]
The problem happened when I use apache/apisix:2.5-centos with apisix-dashboard:2.6.1

dashboard 2.6.1 didn't support apisix:2.5 ??

Is there any way I could know the which apisix-dashboard could play with apisix

**Comment by nic-chen** [comment]
hi  @forgaoqiang

Please take a look at `System Info` on Dashboard to make sure that the versions of APISIX and Dashboard are what you expect.

![image](https://user-images.githubusercontent.com/33000667/121837845-399e2f80-cd09-11eb-9553-54ed8d18a7c8.png)

**Comment by xshans** [comment]
Request Error Code: 2000001
The manager-api and apache apisix are mismatched.

![image](https://user-images.githubusercontent.com/52526052/125582337-6363f9f0-76bd-40f5-b813-ce8e3512b2d1.png)

**Comment by juzhiyuan** [comment]
see https://github.com/apache/apisix-dashboard/issues/1944
