### ISSUE TITLE
[Fe]: issue regarding viewport in `route` page

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-dashboard#1815]
## Issue description
1. issue occurred while running website on "1366 x 768" resolution.
2. also the subtitle of every page looks bit odd for the UI, I guess its about font, or the subtitles should have least amount of text, or should be in bullet format

## Expected behavior
should be responsive on "1366 x 768" resolution

## How to Reproduce

 Go to "route page"

## Screenshots
![scrnli_21_04_2021_23-11-30](https://user-images.githubusercontent.com/40708551/115598051-9d067500-a2f7-11eb-805e-c596249f225b.png)

## Environment
OS : Ubuntu 20.04.2

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/115639234-aa971b80-a346-11eb-93ea-a487067aef28.png)

How about clicking this place?

**Comment by iamayushdas** [comment]
Doing that would work, but is that the only solution?

**Comment by juzhiyuan** [comment]
or only show some selected columns?

**Comment by iamayushdas** [comment]
yes that could be the good solution

**Comment by liuxiran** [comment]
Inspired by antd：
![2021-04-23 16-59-44屏幕截图](https://user-images.githubusercontent.com/2561857/115847509-9e4db400-a455-11eb-83d6-925e5bd22185.png)

add a scroll-y for table, and at the same time limit the columns width is also a choice

**Comment by juzhiyuan** [comment]
Good! There indeed has one configuration to enable scroll y

**Comment by iamayushdas** [comment]
> Inspired by antd：
> ![2021-04-23 16-59-44屏幕截图](https://user-images.githubusercontent.com/2561857/115847509-9e4db400-a455-11eb-83d6-925e5bd22185.png)
> 
> add a scroll-y for table, and at the same time limit the columns width is also a choice

could you guide me for this?

**Comment by juzhiyuan** [comment]
Hi, you could refer to https://ant.design/components/table-cn/#components-table-demo-fixed-columns
