### ISSUE TITLE
I want to edit the Id when creating the upstream、route and service

### ISSUE THREAD

**Issue by cverdela** [apache/apisix-dashboard#1821]
# Feature request

## Please describe your feature

A clear and concise description of what you want and what your use case is.

I want to edit the Id when creating the upstream、route and service

## Describe the solution you'd like

I want to manage the id for record and report

## Describe alternatives you've considered

using manage api in dashboard，but i don't like jwt ,
using manage api in apisix，but it's not on the control plane.

**Comment by starsz** [comment]
I think you can deploy an additional apisix as the control plane. And only use the admin-api.

By the way, just want to know what's the reason that you don't like jwt?

**Comment by nic-chen** [comment]
@cverdela 
You can also specify the id using the Manager API, just like using the Admin API.

**Comment by starsz** [comment]
I will close this ISSUE. If there is a problem, you can reopen it @cverdela.
