### ISSUE TITLE
manager-api: Why putting the feature of daemon in core code?

### ISSUE THREAD

**Issue by fregie** [apache/apisix-dashboard#1840]
When I reading the code of manager-api,it take me a lot of time understanding the moudle of daemon and cmd,but these are not the core features of manager-api.Why don't we keep the core code less and simple?

Maybe it's a good idea taking this feature out of manager-api as a stand-alone tool to manage the manager-api service.And manager-api will only be a executable file that launching a http/https service when executing.

**Comment by nic-chen** [comment]
hi, @fregie  could you point out the files and lines of the code? Thanks.

**Comment by fregie** [comment]
In file `api/cmd/service.go` and functions `newxxxCommand()` in `api/cmd/manageapi.go`.
I don't think the code in these two files is necessary be added in the core code.It's fine just invoke `manageAPI()` in `manageapi.go` starting the service,and use a stand-alone script or something else to manage this service.
On the other hand, this feature is redundant if it runs in a container.

**Comment by starsz** [comment]
Maybe you can refer this Issue： https://github.com/apache/apisix-dashboard/issues/842

**Comment by bisakhmondal** [comment]
Hi @fregie, sorry to hear that and thank you for elaborating the issue.

The code had been updated keeping 3 things in mind.
1. Cross-platform support for daemonizing Manager API.
2. Feature-rich CLI experience. 
3. And also a good codebase readability. 

If we ignore the service part, it's just a CLI command which invokes the `manageAPI` method which handles the core logic without introducing any service-related stuff. And rest `newxxxCommand` commands are just simple addons subcommand attached with the main CLI command (Actually, it's the way the package `spf13/cobra` works, the CLI management library we are using).

Thanks for the recommendation but I think standalone scripts/service unit files focussed on each OS (Linux, Windows, OSX) would make things even messier. 

>On the other hand, this feature is redundant if it runs in a container.

Freely use `./manager-api` as an entry point :)
Hope it helps. Thanks.

**Comment by fregie** [comment]
@bisakhmondal  Thank you for explanation.
I don't think use a standalone tool would make things messier.Because both ways need to focus on each OS (Linux, Windows, OSX),just the current way using library `takama/daemon` dealt with this problem,we can also use a library to do this to avoid spending a lot of time of us dealing with it.
And I don't think it's a good idea deal with system-level differences in core code.This will bring more uncertainty to our core logic.
Like this:
```golang
if runtime.GOOS == "darwin" {
	d, err = daemon.New("apisix-dashboard", "Apache APISIX Dashboard", daemon.GlobalDaemon)
} else {
	d, err = daemon.New("apisix-dashboard", "Apache APISIX Dashboard", daemon.SystemDaemon)
}
```

**Comment by bisakhmondal** [comment]
Hii @fregie, it's nice to see your concern :)

Could you please elaborate on the "standalone tools" part you mentioned? 
If it is writing unit files corresponding to the different os-specific service managers, that's exactly what getting handled by the `takama/daemon` [[ref](https://github.com/takama/daemon/blob/496d69192531c6cb1004380a0be0fcf2031b06f4/daemon_linux_systemd.go#L214-L227)] internally. Also if we provide raw unit files, we have to document the steps, from copying the unit file to commands required reloading the daemon manager for registering the service for a list of OS's and also we have to manually manage the lifecycle of those unit files ourselves. The same goes for the shell scripts too.
>we can also use a library to do this to avoid spending a lot of time of us dealing with it.

Sorry, didn't get this. Do you feel we missed something or works left to be done?

Yes, that's the only instance we went with such a trade-off, yet it doesn't touch any of the core logic. Just FYI, if we are running on some hypothetical OS where there is no known service manager `manager-api` will work fine if no commands related to the service is used.

I just stated our motive behind this current approach but new changes are always welcome :)
Thanks.

**Comment by fregie** [comment]
@bisakhmondal 
I have an immature draft,maybe we can just split manager-api into two part
One is only a executable file launching the http service with core logic
The another also use `takama/daemon` but it invokes this executable file
In this way,we can also use commend like `xxx strart`,`xxx stop` etc,and it can also decouple the service management function from the core logic

**Comment by bisakhmondal** [comment]
> @bisakhmondal
> I have an immature draft,maybe we can just split manager-api into two part
> One is only a executable file launching the http service with core logic
> The another also use `takama/daemon` but it invokes this executable file
> In this way,we can also use commend like `xxx strart`,`xxx stop` etc,and it can also decouple the service management function from the core logic

Oh, you mean another binary that simply kickstarts the plain old `manager-api` as a service. Thanks for the clarification.

I have a neutral feeling about this approach. Wondering,  won't it impact the user experience🤔? Let's hear from the others too.
Pinging @nic-chen, @starsz

**Comment by starsz** [comment]
> I have an immature draft,maybe we can just split manager-api into two part

If so, I think we can use `supervisor` instead.

IMO, I think the feature of the daemon is very good. The reason is talked about before.
Thanks for the @bisakhmondal. 😊.

If you had met any problem while reding the code. 
You can create an issue to discuss it or can you help to improve the code readability.
That would be more interesting if we can keep this feature and improve the code readability.

**Comment by fregie** [comment]
I can have a try.
Assigne this to me?

**Comment by starsz** [comment]
> @starsz
> I can have a try.
> Assigne this to me?

Cool.Thank you very much.

**Comment by nic-chen** [comment]
> @starsz
> I can have a try.
> Assigne this to me?

looking forward to it.
