### ISSUE TITLE
default connection timeout not equal with nginx?

### ISSUE THREAD

**Issue by oldthreefeng** [apache/apisix-dashboard#1882]
## Issue description

what is the default connection timeout in apisix? 

for  i found it  used 6s to default (User Guide Picture).   nginx set the timeout to 60s . 

why this happened? 

## How to Reproduce

just install. 
## Environment

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.14
* apisix-dashboard version, if have: 2.6
* Browser version, if have:

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L345-L353

Just rechecked the schema_def, there doesn't have default value actually, so this issue turns to what's default value should dashboard use on timeout fields.

@totemofwolf I remember you also have this question?

**Comment by oldthreefeng** [comment]
if  i dont set the timeout section.  what the value the apisxi upstream use?  @juzhiyuan

**Comment by starsz** [comment]
> what the value the apisix upstream use

It will inherit the timeout value of the global nginx.conf configuration (like proxy_connect_timeout.
You can referer: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#set_timeouts

**Comment by starsz** [comment]
> for ngx . send_timeout, proxy_connect_timeout, proxy_read_timeout, proxy_write_timeout . this all default to 60s.
> 
> for apisix. send_timeout default to 10s . proxy_connect_timeout, proxy_read_timeout, proxy_write_timeout, default to 6s(from dashboard create default).
> 
> why this changed in apisix ? @starsz

IMO, the default value is too large.

**Comment by starsz** [comment]
Close this issue. If there is a problem, you can reopen it. @oldthreefeng
