### ISSUE TITLE
consumer/list page bug

### ISSUE THREAD

**Issue by mrcaobin** [apache/apisix-dashboard#1886]
in consumer/list, click view button, on the pop up page ,cllick submit, it will add a new data record named 'undifined'

在消费者页面，点击查看页面，在右侧弹出框中，直接点击提交，不是进行更新，二是会增加一条新的记录。

**Comment by juzhiyuan** [comment]
Ya, it needs a better title like `Raw Data Editor` or `Configure by Raw Data Editor`? The second one is too long hh

**Comment by liuxiran** [comment]
> in consumer/list, click view button, on the pop up page ,cllick submit, it will add a new data record named 'undifined'
> 
> 在消费者页面，点击查看页面，在右侧弹出框中，直接点击提交，不是进行更新，二是会增加一条新的记录。

 Fixed by: https://github.com/apache/apisix-dashboard/pull/1987
