### ISSUE TITLE
Create/Configure Route page is broken

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1889]
## Issue description

Hi, when I visit the demo site http://139.217.190.60/ today, I found that the `Create/Configure Route` page is broken with a wired error.

When I running this project locally and using `yarn start` mode, all things are good. I haven't tried to use `yarn build` & setup a Production environment.

## Expected behavior

It needs to show the Create steps page.

## How to Reproduce

1. Go to http://139.217.190.60/ 
2. Click on /routes/create
3. Error happened

## Screenshots
![image](https://user-images.githubusercontent.com/2106987/117911736-dd627d00-b310-11eb-8d12-4242da71597f.png)

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: the latest commits from master branch
* Browser version, if have: Chrome

## Additional context
No

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/117912050-5e217900-b311-11eb-912a-ac683d374ee3.png)

When I reload, it's loading infinitly.

**Comment by iamayushdas** [comment]
Okay looking into this, will report you asap

**Comment by juzhiyuan** [comment]
Thanks!

**Comment by iamayushdas** [comment]
Yesterday's commits have some problem i guess, 
production deploy from day before yesterday is working fine:
https://609b7441688c4c9abaeb03df--apache-dashboard.netlify.app/

production deploy Url: (Fetched from recently updated repo)
https://609b7ed3b39e03b0705cf446--apache-dashboard.netlify.app/routes/create

**Comment by iamayushdas** [comment]
@guoqqqi @liuxiran could you guide me a little in this

**Comment by juzhiyuan** [comment]
Got it, it's too wired due to we have tests passed 🤔 cc @guoqqqi to hep you, he may reply not quickly these days.

**Comment by iamayushdas** [comment]
Okay

**Comment by juzhiyuan** [comment]
For users who want to visit the demo site, please use https://609b7441688c4c9abaeb03df--apache-dashboard.netlify.app/ for temporality.

**Comment by iamayushdas** [comment]
we can unpin this now, i guess
