### ISSUE TITLE
Enable Husky to check in pre-commit

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1900]
It would be great to have a checker here:
1. We could enable Husky to check pre-commit;
2. When changed files contain local cache paths, like `@/.umi/xx`, just throw errors.

_Originally posted by @juzhiyuan in https://github.com/apache/apisix-dashboard/issues/1899#issuecomment-841829529_

**Comment by liuxiran** [comment]
closed with #1957
