### ISSUE TITLE
request help: dashborad doesn't provide plugin_config menu bar, how to change plugin_config?

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix-dashboard#1904]
### There are two features i need
One: I need get route list filter by label, i know apisix-dashboard can do it,but how to implements it by apisix not dashboard?
Two: how to charge plugin_config? dashborad not supply plugin_config  manu bar

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
![image](https://user-image.githubusercontent.com/2106987/118762340-9ba17b80-b8a8-11eb-8430-d977277f4146.png)

Hi @vincentwc, just to make sure, does this screenshot make sense to you? This feature is under the Advanced selector.

**Comment by vincentwc** [comment]
> ![image](https://user-images.githubusercontent.com/2106987/118762472-d4415500-b8a8-11eb-96d9-d7df2998affc.png)
> 
> Hi @vincentwc, just to make sure, does this screenshot make sense to you? This feature is under the Advanced selector.

yes, it's true .but this manu not check button?so i don't know what i set in plugin_config , apisix_dashboard version is 2.5

**Comment by vincentwc** [comment]
> > One: I need get route list filter by label, i know apisix-dashboard can do it,but how to implements it by apisix not dashboard?
> 
> We are planning to replace Admin API with Manager API: https://github.com/apache/apisix/milestone/11
> So this new feature won't be implemented again in Admin API.
> 
> You can refer to Manager API's doc: http://apisix.apache.org/docs/dashboard/api/api#get-2 and deploy it separately: https://github.com/apache/apisix-dashboard/tree/master/api
> 
> > Two: how to charge plugin_config? dashborad not supply plugin_config manu bar
> 
> This question needs to be answered by dashboard's developer: https://github.com/apache/apisix-dashboard/issues/
> 
> CC @juzhiyuan

thanks, so the item one will be implemetns in v3？ i think the features is really  usefull.

**Comment by juzhiyuan** [comment]
>  i don't know what i set in plugin_config 

@vincentwc Got it, cc @LiteSun to have a Document on this feature.

**Comment by LiteSun** [comment]
ok.
