### ISSUE TITLE
Dashboard support the use of Nacos storage APISIX configuration?

### ISSUE THREAD

**Issue by coolbeevip** [apache/apisix-dashboard#1911]
I noticed that APISIX supports [Service discovery via Nacos](https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/nacos.md)

Does APISIX Dashboard support the use of Nacos storage configuration? I did not find any information on this

**Comment by juzhiyuan** [comment]
Yes, Dashboard doesn't support this feature now, would you like to file a PR on this?

**Comment by coolbeevip** [comment]
Sorry, I'm a javaer,  I don't understand front-end development

**Comment by anjia0532** [comment]
不光是不支持Nacos，是啥discovery都不支持。
翻了下源码是因为这些discovery 拉取到实例信息后，只存在于内存。不写etcd，你通过调用api或者看etcd都是看不到具体的实例信息的

有个蛋疼的事是，通过dashboard修改路由时，会直接去掉discovery的配置信息。意味着，discovery只能通过api来管理

**Comment by juzhiyuan** [comment]
> 有个蛋疼的事是，通过dashboard修改路由时，会直接去掉discovery的配置信息。意味着，discovery只能通过api来管理

Yes, Dashboard doesn't support configuring Service Discovery by UI now, welcome to submit PR to support this nice feature.

**Comment by anjia0532** [comment]
@juzhiyuan 还有个方案，通过api创建upstream，route和service关联upstream_id，这时候，不校验 `目标节点` 的必填属性。比较小成本的解决了这个问题

**Comment by juzhiyuan** [comment]
duplicate with https://github.com/apache/apisix-dashboard/issues/1977
