### ISSUE TITLE
Add route path search in dashboard

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-dashboard#1916]
# Feature request
Advise add route path search in dashboard
![image](https://user-images.githubusercontent.com/52538259/119312338-d2aacf00-bca4-11eb-9681-4e6cbbe0b654.png)

## Please describe your feature

We have 200+ routes for one env, like dev dev01 uat uat01, and i seperate them by using tags, but It‘s still difficult to find a route by route path.

**Comment by starsz** [comment]
Agree with. I think we need this feature.

**Comment by imjoey** [comment]
Nice feature.  +1 from me.

**Comment by Firstsawyou** [comment]
Agree +1，I think this feat is very useful.

**Comment by liuxiran** [comment]
Reference: https://procomponents.ant.design/components/table/?current=1&pageSize=5

Welcome to submit PR to improve user experience

**Comment by nic-chen** [comment]
agree +1

**Comment by iamayushdas** [comment]
@nic-chen does back-end service (API)supports searching the path field
as the search is not working for path
![Screenshot from 2021-05-25 13-00-12](https://user-images.githubusercontent.com/40708551/119457684-92f1ef00-bd59-11eb-9ba2-45397c5381e1.png)

**Comment by nic-chen** [comment]
> @nic-chen does back-end service (API)supports searching the path field
> as the search is not working for path
> ![Screenshot from 2021-05-25 13-00-12](https://user-images.githubusercontent.com/40708551/119457684-92f1ef00-bd59-11eb-9ba2-45397c5381e1.png)

not yet. welcome PR.

**Comment by Marco-Zheng** [comment]
> > @nic-chen does back-end service (API)supports searching the path field
> > as the search is not working for path
> > ![Screenshot from 2021-05-25 13-00-12](https://user-images.githubusercontent.com/40708551/119457684-92f1ef00-bd59-11eb-9ba2-45397c5381e1.png)
> 
> not yet. welcome PR.

@nic-chen 
I add `dataIndex: 'uri'` in web/src/pages/Route/List.tsx, it works and regular search uri successfully
![image](https://user-images.githubusercontent.com/52538259/119487762-5ab7d400-bd8c-11eb-9563-7652d95777d5.png)

**Comment by nic-chen** [comment]
@Marco-Zheng  good to know, thanks for feedback

**Comment by iamayushdas** [comment]
added the PR

**Comment by iamayushdas** [comment]
IMO this should be a good first issue , it consists of testing too other wise it won’t work @nic-chen

**Comment by nic-chen** [comment]
> IMO this shouldn’t be a good first issue , it consists of testing too other wise it won’t work @nic-chen

agree with you

**Comment by Marco-Zheng** [comment]
@nic-chen Could you please give me an advise, if i update the code locally and want to replace the code for apisix-dashboard docker image, how can i do for this?

can i `make build` locally and replace the dictionary `html`?

**Comment by nic-chen** [comment]
> @nic-chen Could you please give me an advise, if i update the code locally and want to replace the code for apisix-dashboard docker image, how can i do for this?
> 
> 
> 
> can i `make build` locally and replace the dictionary `html`?

I think you should better build an new image

**Comment by Marco-Zheng** [comment]
@nic-chen Ok, thanks for your kindly reply
