### ISSUE TITLE
support vars in URI

### ISSUE THREAD

**Issue by hozaifaaoud** [apache/apisix-dashboard#1919]
How can I add vars in uri?
And how can I create a route like this 
Http://127.0.0.1:9080/tel/{TelNum}/email/{EmailAdd}

**Comment by iamayushdas** [comment]
Hey @hozaifaaoud have you tried it by adding route path as you stated.

**Comment by hozaifaaoud** [comment]
Yes, and I am facing this issue 
![image](https://user-images.githubusercontent.com/79872781/119589884-059fb080-bdd4-11eb-9e66-7b4849580e09.png)

**Comment by iamayushdas** [comment]
@starsz have a look here.
Thank you

**Comment by starsz** [comment]
Add vars in uri is not support.

But you can try to use var filed in route.
refer: https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#route

Like this:
```
 "vars": [["uri", "~~", "{your regex}"]],
```

**Comment by nic-chen** [comment]
please refer to:

https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#5-parameter-match

https://github.com/api7/lua-resty-radixtree/#parameters-in-path

**Comment by liuxiran** [comment]
Hi @hozaifaaoud , have our answers solved your problem? If not, please update more details, or we consider the problem solved and will close it after three days, thanks a lot

**Comment by imjoey** [comment]
> please refer to:
> 
> https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#5-parameter-match
> 
> https://github.com/api7/lua-resty-radixtree/#parameters-in-path

@starsz  @nic-chen @liuxiran 

Hi all, according to the docs, the parameter `radixtree_uri_with_parameter` allows users to set `/blog/:name` as the uri which could match `/blog/dog` and `/blog/:cat`. I was wondering that if we can also use it in `regex_uri`? For example, if `regex_uri` is set to `[" /iresty/:p1/:p2/:p3", "/x:p1/y:p2/z:p3"]`, apisix could match request with `/iresty/name/age/gender` and rewrite the request url to `/xname/yage/zgender` and then send to the upstreams.

Looking forward to your feedbacks. Thanks.

**Comment by liuxiran** [comment]
> > please refer to:
> > https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#5-parameter-match
> > https://github.com/api7/lua-resty-radixtree/#parameters-in-path
> 
> @starsz @nic-chen @liuxiran
> 
> Hi all, according to the docs, the parameter `radixtree_uri_with_parameter` allows users to set `/blog/:name` as the uri which could match `/blog/dog` and `/blog/:cat`. I was wondering that if we can also use it in `regex_uri`? For example, if `regex_uri` is set to `[" /iresty/:p1/:p2/:p3", "/x:p1/y:p2/z:p3"]`, apisix could match request with `/iresty/name/age/gender` and rewrite the request url to `/xname/yage/zgender` and then send to the upstreams.
> 
> Looking forward to your feedbacks. Thanks.

also cc @spacewander to help take a look, thanks a lot

**Comment by spacewander** [comment]
radixtree_uri_with_parameter is disabled by default. And it has a design defect: ':' is a valid character in the URL, so it is not recommended to enable it.

**Comment by liuxiran** [comment]
> radixtree_uri_with_parameter is disabled by default. And it has a design defect: ':' is a valid character in the URL, so it is not recommended to enable it.

thanks for @spacewander 's replay, also cc @imjoey @hozaifaaoud to kown.

As vars in url is helpful for some users, I wonder if we have plan to Improve this feature?

**Comment by imjoey** [comment]
> > radixtree_uri_with_parameter is disabled by default. And it has a design defect: ':' is a valid character in the URL, so it is not recommended to enable it.
> 
> thanks for @spacewander 's reply, also cc @imjoey @hozaifaaoud to kown.
> 
> As vars in url is helpful for some users, I wonder if we have plan to Improve this feature?

That would be great. Uses could use these vars to design complicated route match rules, as well as request parameter rewrite.

**Comment by hozaifaaoud** [comment]
any good news

**Comment by juzhiyuan** [comment]
AFAIK, no plan to support this, but PR is welcome.
