### ISSUE TITLE
Error: .jsx: Unexpected token 

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-dashboard#1920]
## Issue description

![image](https://user-images.githubusercontent.com/52538259/119598027-bded4900-be14-11eb-88cc-af59d6048307.png)

When i run dashboard 2.5 locally,  here comes error `.jsx: Unexpected token `
But 2.6 works successflly

**Comment by Marco-Zheng** [comment]
> ## Issue description
> ![image](https://user-images.githubusercontent.com/52538259/119598027-bded4900-be14-11eb-88cc-af59d6048307.png)
> 
> When i run dashboard 2.5 locally, here comes error `.jsx: Unexpected token `
> But 2.6 works successflly

I download the source code from `https://archive.apache.org/dist/apisix/dashboard/2.5/`

**Comment by iamayushdas** [comment]
could you tell me steps after which you triggered with this error?

**Comment by Marco-Zheng** [comment]
@iamayushdas Hi, I manual `umi build` and `yarn run start` locally, the error was happened

**Comment by iamayushdas** [comment]
i just ran two commands : 
1. etcd
2. make api-run
3. yarn && yarn start (inside website directory)

it worked

**Comment by Marco-Zheng** [comment]
@iamayushdas Thanks, let me try for this

**Comment by juzhiyuan** [comment]
If this error still happens, please let me know.
