### ISSUE TITLE
 On the front end, the websocket button is useless

### ISSUE THREAD

**Issue by xyz2b** [apache/apisix-dashboard#1933]
## Issue description

I enable websocket in dashborad, but it doesn't work after I saved it.
I check that there is no websocket parameter in the request initiated.

## How to Reproduce

1. Go to 'route config website'
2. Click on 'WebSocket button'
3. And save route config
4. Checking the configuration of the route
5. The WebSocket button is gray

## Screenshots

![企业微信截图_16227872597735](https://user-images.githubusercontent.com/48942966/120754499-5a16fe80-c53f-11eb-992f-228573443ff3.png)

![企业微信截图_16227872997999](https://user-images.githubusercontent.com/48942966/120754514-5d11ef00-c53f-11eb-9d1e-795e04536baa.png)

![企业微信截图_16227873305622](https://user-images.githubusercontent.com/48942966/120754528-600cdf80-c53f-11eb-826d-a547cef63b3f.png)

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.6.1
* Browser version, if have: chrome 89.0.4389.90

**Comment by iamayushdas** [comment]
Checking

**Comment by liuxiran** [comment]
Confirmed, when bind a service in create Route step1, `enable_websocket` will be lost, and without Service binding, `enable_websocket` work normally. Need to fix it in 2.7.1

**Comment by juzhiyuan** [comment]
cc @Baoyuantop to take a look, and @liuxiran please provide some necessary testcases for this fix.

**Comment by liuxiran** [comment]
@spacewander help request about this `enable_websocket` param in route: when we create a route with `redirect` plugin, does it still need `enable_websocket` param? looking forward to your reply, thanks a lot

after this question got confirmed, I 'll provide corresponding test cases about this issue @juzhiyuan

**Comment by spacewander** [comment]
> when we create a route with redirect plugin, does it still need enable_websocket param?

We don't need it.

**Comment by liuxiran** [comment]
> > when we create a route with redirect plugin, does it still need enable_websocket param?
> 
> We don't need it.

Thanks a lot @spacewander 

then we have to update two points:

1. when we bind service to a Route, we should pass `enable_websocket` normally to API.
this can be tested by recheck `enable_websocket` value in the configure view

2. when we enable  `redirect` in a Route, we should omit `enable_websocket` field in the create/configure step1.
this can be tested by 
2.1. when we enable `direct`, `enable_websocket` should not exist in the step1
2.2 when we recheck the Route in the configure page, `enable_websocket` still not existed.

@Baoyuantop 

cc @juzhiyuan

**Comment by juzhiyuan** [comment]
OK

**Comment by Baoyuantop** [comment]
> > > when we create a route with redirect plugin, does it still need enable_websocket param?
> > 
> > 
> > We don't need it.
> 
> Thanks a lot @spacewander
> 
> then we have to update two points:
> 
> 1. when we bind service to a Route, we should pass `enable_websocket` normally to API.
>    this can be tested by recheck `enable_websocket` value in the configure view
> 2. when we enable  `redirect` in a Route, we should omit `enable_websocket` field in the create/configure step1.
>    this can be tested by
>    2.1. when we enable `direct`, `enable_websocket` should not exist in the step1
>    2.2 when we recheck the Route in the configure page, `enable_websocket` still not existed.
> 
> @Baoyuantop
> 
> cc @juzhiyuan

OK
