### ISSUE TITLE
After configuring redirect in route, dashboard cannot run normally

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1934]
## Issue description

After configuring the redirection in the route, click Edit `Route` again. Dashboard does not work normally, and then the Dashboard page crashes.

## Expected behavior

After configuring `Redirect` in the configuration of `Route`, Dashboard can work correctly.

## How to Reproduce

1. Configure redirect in route
<img width="1388" alt="截屏2021-06-04 下午5 31 23" src="https://user-images.githubusercontent.com/52862365/120780741-fb5f7e00-c55a-11eb-960f-14e37c062d7a.png">

<img width="1173" alt="截屏2021-06-04 下午5 32 23" src="https://user-images.githubusercontent.com/52862365/120780786-03b7b900-c55b-11eb-9d8e-63152179bb54.png">

config data:

```shell
{
  "uris": [
    "/post"
  ],
  "name": "redirect-test",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "redirect": {
      "ret_code": 302,
      "uri": "/get"
    }
  },
  "status": 1
}
```

2. Edit the route again and any data at noon on the page
<img width="1327" alt="截屏2021-06-04 下午5 34 23" src="https://user-images.githubusercontent.com/52862365/120781147-5c875180-c55b-11eb-804d-934ea52bac67.png">

3. Clicking on the other options of Dashboard is invalid and the page is abnormal

<img width="998" alt="截屏2021-06-04 下午5 19 01" src="https://user-images.githubusercontent.com/52862365/120781211-6b6e0400-c55b-11eb-986b-ec00befd9293.png">

<img width="1116" alt="截屏2021-06-04 下午5 15 59" src="https://user-images.githubusercontent.com/52862365/120781228-732da880-c55b-11eb-9f43-74c2ec638b6d.png">

## Environment

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):  3.4.0
* apisix-dashboard version, if have: 2.6
* Browser version, if have:

**Comment by liuxiran** [comment]
duplicate with #1922

**Comment by liuxiran** [comment]
since #1922 is closed, close this issue too, reopen it when you needed, thanks @Firstsawyou
