### ISSUE TITLE
cannot find package "github.com/apisix/manager-api/

### ISSUE THREAD

**Issue by BigBoyY** [apache/apisix-dashboard#1939]
## Issue description
 When using the source build manager - API make build in. / API/build go file 45th line
 ```
cd ./api && go build -o ../output/manager-api -ldflags "${GOLDFLAGS}" ./cmd/manager && cd .. 

 ```
 Go to import github.com/apisix/manager-api/ in the package
```
go build -o ../output/manager-api -ldflags '-X github.com/apisix/manager-api/internal/utils.version=2.6 -X github.com/apisix/manager-api/internal/utils.gitHash=73b5cfd' ./cmd/manager
cmd/manager/main.go:23:2: cannot find package "github.com/apisix/manager-api/cmd" in any of:
        /usr/local/go/src/github.com/apisix/manager-api/cmd (from $GOROOT)
        /root/goweb/src/github.com/apisix/manager-api/cmd (from $GOPATH)
 cp ./api/conf/schema.json ./output/conf/schema.json
cp: 无法获取"./api/conf/schema.json" 的文件状态(stat): 没有那个文件或目录  
```
 There is no project under github.com/apisix/. How should I build
 
## Expected behavior
make build

## How to Reproduce

1.  git clone -b release/2.6 https://github.com/apache/apisix-dashboard.git
2. cd apisix-dashboard
3. make build

## Environment

* apisix version : 2.6
* OS :  6.1
* OpenResty / Nginx version:  openresty/1.19.3.2
* etcd version: 3.4.13
* apisix-dashboard version: 2.6

**Comment by bzp2010** [comment]
You can try to open the go module feature and use the `GO111MODULE` environment variable.
It seems that the golang compiler searches `GOPATH` for related packages and ignores the definitions in the `go.mod` file.

I'm not sure that's what's causing your problem, but you can try it.

**Comment by nic-chen** [comment]
hi @BigBoyY what is your GO version

**Comment by BigBoyY** [comment]
> 嗨@BigBoyY你的GO版本是什么

go version go1.8.3 linux/amd64

**Comment by bzp2010** [comment]
@BigBoyY You need to upgrade the Golang version. The go module feature can only be used in the minimum version 1.13.

**Comment by BigBoyY** [comment]
> You can try to open the go module feature and use the `GO111MODULE` environment variable.
> It seems that the golang compiler searches `GOPATH` for related packages and ignores the definitions in the `go.mod` file.
> 
> I'm not sure that's what's causing your problem, but you can try it.

I looked at the DockeFile and it actually did  “go env -w GO111MODULE=on”  I'll give it a try. Thank you very much

**Comment by BigBoyY** [comment]
> hi @BigBoyY, You need to upgrade the Golang version. The go module feature can only be used in the minimum version 1.13.

OK. I'll  try. Thank you very much
