### ISSUE TITLE
bug: dashboard does not support healcheck config

### ISSUE THREAD

**Issue by panhow** [apache/apisix-dashboard#194]
### Issue description
dashboard does not support healcheck config

i config healthcheck by `curl` command, then i update some config in dashboard.
The dashboard update upstream by `PUT` method URL，but the json body does not send the healthcheck config

**Comment by juzhiyuan** [comment]
Yep, dashboard doesn't support health check yet, we will have a meeting about this issue.

**Comment by juzhiyuan** [comment]
This feature is in development now and will be released in about 10 days.

**Comment by juzhiyuan** [comment]
UPDATE: This issue will be addressed soon.

**Comment by juzhiyuan** [comment]
related #470
