### ISSUE TITLE
request help: I have a question about how to edit the key of cookies  in Dashborad 2.2. The old version can edit it directly

### ISSUE THREAD

**Issue by 1026197530** [apache/apisix-dashboard#1952]
### Issue description
I have a question about how to edit the key of cookie in Dashborad 2.2. The old version can edit it directly，
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.2
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.15.8.3
![2EE3AE741DD0DA407FA99F64EF67DC05](https://user-images.githubusercontent.com/28381375/123240630-0af73480-d513-11eb-8339-c45a77d859be.jpg)
![5668F386C5F8B7C21436DD7E28608E00](https://user-images.githubusercontent.com/28381375/123240650-0fbbe880-d513-11eb-8f3b-6ad05c76c2e1.jpg)

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.11  
* apisix-dashboard version, if have: 2.2
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/123356548-7df7be00-d59a-11eb-84ff-e7580e171d1a.png)

Just to make sure, if we use `hash_on == cookie`, then the `key` is customized from the client, right?

Doc: https://apisix.apache.org/docs/apisix/next/admin-api/#request-body-parameters-3

**Comment by 1026197530** [comment]
yeap!I want to customize this key

**Comment by juzhiyuan** [comment]
yes, it doesn't support customization in 2.2, welcome to send a PR to support this feature! Ant Design has a component that supports Input & Selection.

**Comment by juzhiyuan** [comment]
@guoqqqi Please take a look at this issue, and support this feature.

@1026197530 You could submit PR to support this, or wait for @guoqqqi.

**Comment by iamayushdas** [comment]
@guoqqqi if you are busy then ping me to look into this issue

**Comment by guoqqqi** [comment]
OK, Let me have a look
