### ISSUE TITLE
At least storage the PATH of the grafana in the etcd 

### ISSUE THREAD

**Issue by forgaoqiang** [apache/apisix-dashboard#1953]
# Feature request
At least storage the PATH of the grafana in the etcd 
## Please describe your feature
Store the grafana configuration in the local storage is wired, every time I change computer or browser, I have to retype it in
Even the Grafana's username and password can't be stored, it's better to provide a grafana login interface better than not.

A clear and concise description of what you want and what your use case is.

**Comment by nic-chen** [comment]
@forgaoqiang PR is welcome

**Comment by jwrookie** [comment]
assign to me, i will finish it

**Comment by jwrookie** [comment]
I don't think we need to store it in `etcd`, just make it a configuration item because it hardly be updated, and as a stateless service, we shouldn't store our own configuration to other dependent services

**Comment by starsz** [comment]
> I don't think we need to store it in `etcd`, just make it a configuration item because it hardly be updated, and as a stateless service, we shouldn't store our own configuration to other dependent services

I think we can store it in the etcd. The reason is the same as [forgaoqiang](https://github.com/forgaoqiang).

@nic-chen @bzp2010 What's your idea?

**Comment by nic-chen** [comment]
> > I don't think we need to store it in `etcd`, just make it a configuration item because it hardly be updated, and as a stateless service, we shouldn't store our own configuration to other dependent services
> 
> I think we can store it in the etcd. The reason is the same as [forgaoqiang](https://github.com/forgaoqiang).
> 
> @nic-chen @bzp2010 What's your idea?

sure. store it in the etcd is better than a local configuration

**Comment by bzp2010** [comment]
In the current implementation, storing to etcd is slightly difficult, storing in the configuration file is simpler, but we can consider implementing more storage in a later version of V3.
