### ISSUE TITLE
Dashboard consumer undefined user

### ISSUE THREAD

**Issue by Applenice** [apache/apisix-dashboard#1954]
## Issue description
Undefined users can be created in Consumer List via Dashboard

## Expected behavior
The appearance of undefined users does not make sense

## How to Reproduce
Create two Comsumer and enable plugin configuration
First，the configuration is as follows:
```
{
  "username": "Pokemon",
  "plugins": {
    "basic-auth": {
      "disable": false,
      "password": "Pokemon",
      "username": "Pokemon"
    },
    "ip-restriction": {
      "disable": false,
      "whitelist": [
        "192.168.0.112"
      ]
    }
  }
}
```
In fact, you can create undefined users in this step:
`Consumer List`->First Consumer Pokemon-> Operation `View`-> click `Submit`，you can see that there is an additional undefined user in the list, except for the username is different, other configuration and Pokemon consistent.
```
{
  "username": "undefined",
  "plugins": {
    "basic-auth": {
      "disable": false,
      "password": "Pokemon",
      "username": "Pokemon"
    },
    "ip-restriction": {
      "disable": false,
      "whitelist": [
        "192.168.0.112"
      ]
    }
  }
}
```

Second，the configuration is as follows:
```
{
  "username": "Pikachu",
  "plugins": {
    "basic-auth": {
      "disable": false,
      "password": "Pikachu",
      "username": "Pikachu"
    },
    "ip-restriction": {
      "disable": false,
      "whitelist": [
        "127.0.0.1"
      ]
    }
  }
}
```
Next, the operation:
`Consumer List`->Second Consumer Pikachu-> Operation `View`-> click `Submit`，you can see that the configuration of the undefined user has been modified, except for the username, which is the same as Pikachu, so I won't post it

## Screenshots
![image](https://user-images.githubusercontent.com/30207614/123432636-2b032280-d5fd-11eb-857b-526ea00c7d30.png)

## Environment

* apisix version (cmd: `apisix version`): 2.6
* OS (cmd: `uname -a`):Ubuntu 1804
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.13
* apisix-dashboard version, if have: release/2.7
* Browser version, if have: Firfox 89.0.1

**Comment by juzhiyuan** [comment]
cc @iamayushdas to take a look

**Comment by iamayushdas** [comment]
okay

**Comment by iamayushdas** [comment]
yes @Applenice there is a bug confirmed
