### ISSUE TITLE
There is a problem with the dashboard display

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix-dashboard#1959]
## Issue description
On the upstream service settings page of the dashboard, there is a health check-unhealthy setting. One of the options is the timeout period. This is wrong. This option should be the number of unhealthy statuses.

As shown below

![image](https://user-images.githubusercontent.com/17425270/123923085-3e2a3f80-d9bb-11eb-8b8e-7c2c1a046b45.png)

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:   2.7
* Browser version, if have:

**Comment by iamayushdas** [comment]
looking into it , wait for a while, thank you for your time

**Comment by iamayushdas** [comment]
yes you are right @zuiyangqingzhou i just checked this, @juzhiyuan what's you opinion on this

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/124052013-26e96180-da50-11eb-8f17-429a98002510.png)

https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L196-L200

Hi, I just searched the schema_def file, and this field is existed indeed, which part is incorrect? @iamayushdas @zuiyangqingzhou

**Comment by zuiyangqingzhou** [comment]
Are you sure that the configuration here refers to the timeout period? Instead of referring to the number of timeouts? If it is indeed a timeout, I have two questions, which are explained in the picture below

![image](https://user-images.githubusercontent.com/17425270/124054621-ed672500-da54-11eb-84f6-2203c88c6490.png)

There is also a small question, is there something wrong with this display?

![image](https://user-images.githubusercontent.com/17425270/124054749-34551a80-da55-11eb-83ae-350da2efa96b.png)

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L146-L168

@zuiyangqingzhou Dashboard's fields are according to above schema_def file, there doesn't have `active.health.timeouts` field.

![image](https://user-images.githubusercontent.com/2106987/124076450-d5090180-da78-11eb-937a-c58ebc149a61.png)

This is an i18n issue, @guoqqqi could fix this.

**Comment by zuiyangqingzhou** [comment]
Okay, I'll go to the apisix project to ask

**Comment by liuxiran** [comment]
Since the dashboard I18n has been modified by #1963 , close this issue now.

And for the details about `timeouts` please refer issue: https://github.com/apache/apisix/issues/4528

Thanks~
