### ISSUE TITLE
Feature: add more details log messages in authentication.go

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#1964]
# Feature request

## Please describe your feature

Hi, I found that the log in authentication.go is a little bit less
Like : 

https://github.com/apache/apisix-dashboard/blob/3cfc32761122ad7f15f67edcfc251d0bed2e7538/api/internal/filter/authentication.go#L67-L70

## Describe the solution you'd like

Maybe we can add more details info in it.

Like:

1. How to solve this problem.
```
please check the secret in conf.yaml"
```

**Comment by burntcarrot** [comment]
@starsz I would like to take this issue up. Can you assign me?

**Comment by starsz** [comment]
> @starsz I would like to take this issue up. Can you assign me?

Sure.Thank you very much.

**Comment by burntcarrot** [comment]
Created PR. Requesting review.
