### ISSUE TITLE
This code snippet is confusing  me

### ISSUE THREAD

**Issue by RedemptionC** [apache/apisix-dashboard#1965]
## Issue description
I'm trying to submit my first PR,so I need to read and modify some testing code
[and this line is confusing me](https://github.com/apache/apisix-dashboard/blob/master/api/test/e2enew/version/version_test.go#L40-L49)
why does this test expect OK status while expect error message(mismatched) at the same time?

## context
I am trying to make the error message(due to APISIX and dashboard version mismatch) provide more  information
And I also wonder how this test should be written,should it only include the matching/mismatching situation,or both of them?

**Comment by LiteSun** [comment]
ping @starsz

**Comment by starsz** [comment]
IMO. The API is for check the version match.
So, even if the version is mismatch, we should return the mismatch info, and return 200 OK. And the FE will check the code in response and return the warning information.

**Comment by RedemptionC** [comment]
> IMO. The API is for check the version match.
> So, even if the version is mismatch, we should return the mismatch info, and return 200 OK. And the FE will check the code in response and return the warning information.

Hi,I don't quite get it
In my developing env,the version is matched,but the test failed,does that make sense?
I don't understand what the correct behavior should be when running this test
Could you provide some further explanation?Thanks

**Comment by starsz** [comment]
Oh, I found the reason.
Because in the docker of CI, we don't add the version and hash into binary.
So the version in manager-api is "", and will return the mismatch.

Refer: 
https://github.com/apache/apisix-dashboard/blob/3cfc32761122ad7f15f67edcfc251d0bed2e7538/api/test/docker/Dockerfile#L25
