### ISSUE TITLE
Using apisix to proxy TCP/UDP. but apisix-dashboard do not have the interface to access it. 

### ISSUE THREAD

**Issue by oldthreefeng** [apache/apisix-dashboard#1966]
# Feature request

## Please describe your feature

Add stream_route in apisix-dashboard just like apisix admin-api to manage it.

## Describe the solution you'd like

like normal http-route to manage the stream-route

## Describe alternatives you've considered

just support it.  layer 4 proxy is needed.

**Comment by juzhiyuan** [comment]
Hi, would you like to draft a prototype for this feature?

**Comment by liuxiran** [comment]
related issue: https://github.com/apache/apisix-dashboard/issues/1986

**Comment by liuxiran** [comment]
close by duplicate with #1986
