### ISSUE TITLE
In route, both upstream and service<service can has upstream too> can be set at the same time

### ISSUE THREAD

**Issue by forgaoqiang** [apache/apisix-dashboard#1967]
## Issue description
In route config, both upstream and service<service has upstream too> can be set at the same time
we have two paths:
```
route -> upstream
route -> service -> upstream
```
At the same time, you can set an upstream to route and service at the same time, if I set an upstream to a route and associated a service<the service itself has an upstream> to the route, **which upstream will the route use**? 

## Expected behavior
I think it should set upstream in service since we have a unique way to route a request
`Request -> match route -> go through the plugins in the service -> upstream to DST service provider `

## Environment
APISIX 2.6 with APISIX-dashboard 2.7

**Comment by juzhiyuan** [comment]
🤔 When we select a Service, it should hide the Upstream page, cc @guoqqqi to take a look when you have time.

**Comment by guoqqqi** [comment]
Ok，Let me have a look

**Comment by juzhiyuan** [comment]
@guoqqqi any update here?

**Comment by guoqqqi** [comment]
> @guoqqqi any update here?
Yes, I found the problem in the latest version of the dashboard:
When we select a service in the route page, clicking on the next page still configures the upstream.

**Comment by guoqqqi** [comment]
Our current version is
- In the Route page, when selecting a service, you can select None to skip the Upstream page
Do we need to update it

**Comment by juzhiyuan** [comment]
Yes I think so, when binding a Servcie with Route, it should be ok to skip Upstream Configure.

**Comment by liuxiran** [comment]
> Yes I think so, when binding a Servcie with Route, it should be ok to skip Upstream Configure.

Agree, refer to https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/service.md

actually when we associated a Route with a Service, we can also specify different plugin parameters or upstream for Route, at that time the Route parameter has a higher priority than Service. So it is ok for current dashboard IMO, when you want to use service upstream, just select `None` to skip the upstream page. 

If we want to further optimize the user experience, we can make `None` as the default selection when select a service in the first step.

![image](https://user-images.githubusercontent.com/2561857/126907788-16e51403-e93a-41f1-9938-ac52bf567d53.png)

Looking forward to your reply @forgaoqiang 

cc @guoqqqi @juzhiyuan

**Comment by liuxiran** [comment]
Hi @forgaoqiang , did our answer solve your problem? If not, please update more details here, or we  consider this issue to be resolved after three days, thanks a lot~

**Comment by liuxiran** [comment]
close now, feel free to reopen it with any questions, thanks
