### ISSUE TITLE
request help: imported configuration can't be deleted

### ISSUE THREAD

**Issue by philzhangrui** [apache/apisix-dashboard#1969]
### 2.6版本

在测试环境搭建的单机， etcd 直接使用kill 命令删除之后， etcd里的数据就没有了，
但是导入进去的数据查询还在，删除的时候，删除不了。

![image](https://user-images.githubusercontent.com/7685507/124721702-eb610280-df3b-11eb-9f77-9c926082ac5a.png)

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by philzhangrui** [comment]
导致路由上看到的数据是导入的数据，创建的路由数据，看不到

**Comment by nic-chen** [comment]
hi @philzhangrui 

Hello, this is because the Manager API has cached these data. You can restart the Manager API , and the data won't be there.

**Comment by philzhangrui** [comment]
etcd 里的数据为什么没有了

**Comment by nic-chen** [comment]
I think it may be an issue with etcd, you can submit an issue to the etcd repo.

**Comment by juzhiyuan** [comment]
@philzhangrui Hi, could you please provide your steps in detail? I would love to help to have a check.

**Comment by liuxiran** [comment]
Hi @philzhangrui , does your issue resolved, if not, please update more details here
