### ISSUE TITLE
bug: error using the openid-connect plugin

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix-dashboard#1975]
## Issue description

The data editor suggests that no configuration is required, but after submission it shows that the clinet_id property must be configured, which is contradictory.

take a look at Screenshots
## Screenshots

![image](https://user-images.githubusercontent.com/30819887/125281021-5188c380-e348-11eb-87be-3bc9fbab2241.png)

## Environment

* apisix version (cmd: `apisix version`): 2.6
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.7
* Browser version, if have:

**Comment by starsz** [comment]
`client_id`, `client_secret`,`discovery` are required. cc @juzhiyuan @LiteSun

**Comment by nic-chen** [comment]
> `client_id`, `client_secret`,`discovery` are required. cc @juzhiyuan @LiteSun

yes, it needs to be configured for the plugin `openid-connect` in the route. @LiteSun
