### ISSUE TITLE
bug: Can't submit openid-connect plugin

### ISSUE THREAD

**Issue by flightefore** [apache/apisix-dashboard#1976]
> ### Issue description

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):  2.7
* OS (cmd: `uname -a`): unbuntu18
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.
2.
3.

### What's the expected result?
> 
I can't  edit json file,and can't sumit the plugin
> 

> 

> 
![QQ图片20210713100102](https://user-images.githubusercontent.com/39718566/125378840-090dec00-e3c2-11eb-9c19-2a495f62518d.jpg)

>

**Comment by tzssangglass** [comment]
similar as #1975

**Comment by juzhiyuan** [comment]
duplicate with #1975, will fix it.
