### ISSUE TITLE
perf optimization: plugin config drawer onClose has no animation and cannot closed by clicking mask

### ISSUE THREAD

**Issue by foolwc** [apache/apisix-dashboard#1980]
## Issue description
Plugin config drawer onClose has no animation and cannot close by clicking mask.

## Expected behavior
Just like other dawer: consumer view drawer.

## Environment
APISIX 2.6 with APISIX-dashboard 2.7

**Comment by iamayushdas** [comment]
Hmm, Right.
We should have that feature.

Agree? cc @juzhiyuan @liuxiran

**Comment by juzhiyuan** [comment]
This is not a bug, just a configuration from Ant Design component. Why we should allow the click mask to close? Once it's closed, how about the editing data?

**Comment by foolwc** [comment]
Maybe we could use Ant Design Drawer component in a uniform way.

**Comment by juzhiyuan** [comment]
yes, I would prefer keeping the `closeOnMask = false`
