### ISSUE TITLE
ApiSix-Dashboard white screen

### ISSUE THREAD

**Issue by wjmmjr** [apache/apisix-dashboard#1981]
## Issue description

When I fill in “Select Upstream”，The screen turned white.The premise is that I didn't create any upstream
## How to Reproduce
![52(CE@0X(32M@{A)TNT2 (5](https://user-images.githubusercontent.com/18857921/125570004-4ba5e26f-163a-4d97-9ab1-41b3e281893d.jpg)
![L$G_ED2I NXR88Q5X 67R59](https://user-images.githubusercontent.com/18857921/125570005-caa59afb-fb6a-4a20-afa4-e0a5f8a35995.jpg)

## Environment
apisix version：release/2.7
apisix-dashboard: 2.6
* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

**Comment by juzhiyuan** [comment]
cc @iamayushdas to have a look

**Comment by juzhiyuan** [comment]
cc @Baoyuantop to have a look

**Comment by Baoyuantop** [comment]
Hi, @wjmmjr, I cannot reproduce this error based on the information currently provided. Can you provide a detailed and complete reproduction method?

In addition, when the screen is blank, the console of the browser should print out some error messages. Can you provide some help?
