### ISSUE TITLE
feat: supports dynamic configuration of stream-route

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix-dashboard#1986]
# Feature request

## Please describe your feature

dashboard supports dynamic configuration of stream-route, just like configuring route.

## Describe the solution you'd like
we can add a stream-route button on the left side, just like
![image](https://user-images.githubusercontent.com/30819887/126024962-7dba9306-b623-4859-83fe-c7fe2f0b41e4.png)

## Additional context

the APISIX's admin-api of stream-route: https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#stream-route

the stream-proxy of APISIX: https://github.com/apache/apisix/blob/master/docs/en/latest/stream-proxy.md

I'm still working on the idea for this, any good suggestions from the community?

**Comment by liuxiran** [comment]
Agree with @tzssangglass suggestion, add the menu item `Stream Route` after `Route` would be better, and for create/configure the `Stream Route`, we can consider follow the way `Route` does.

And in fact it is a complete module, we need both UI and manager-api, 

for UI:

- [ ] add menu item `Stream Route` and List page
- [ ] Create `Stream Route`
- [ ] Configure `Stream Route`
- [ ] Delete `Stream Route`

for manager-api

refer to https://apisix.apache.org/docs/apisix/2.7/admin-api#request-methods-10

welcome prs to support this feature in the dashboard.

**Comment by Baoyuantop** [comment]
Hi @liuxiran, I would like to try the UI part.

**Comment by liuxiran** [comment]
> Hi @liuxiran, I would like to try the UI part.

thanks a lot @Baoyuantop , assign to you~

**Comment by liuxiran** [comment]
who would like to try the part of manger-api, @Xu-Mj do you like to try it?

**Comment by Xu-Mj** [comment]
> who would like to try the part of manger-api, @Xu-Mj do you like to try it?

ok , i'll try this part.

**Comment by liuxiran** [comment]
> > who would like to try the part of manger-api, @Xu-Mj do you like to try it?
> 
> ok , i'll try this part.

cool~ thanks @Xu-Mj , please comment here when you have any questions

**Comment by Xu-Mj** [comment]
Hi~ @liuxiran how do i validate a stream route is already in effect in apisix?

**Comment by liuxiran** [comment]
> > Hi @liuxiran, I would like to try the UI part.
> 
> thanks a lot @Baoyuantop , assign to you~

Hi @Baoyuantop I noticed that @Xu-Mj has submitted  #2104 for the API part, you can have a try with your UI part, and any problems can comment here, thanks a lot

**Comment by liuxiran** [comment]
in order to let dashboard work together with APISIX 2.9, we adjusted our plan to quickly release a suitable version, and for this missing feature, move it to m2.9, and hope for this big feature ready, any questions can comment here, thanks a lot

**Comment by liuxiran** [comment]
Hi @Baoyuantop do you need any help with the front-end functionality?

**Comment by Baoyuantop** [comment]
> Hi @Baoyuantop do you need any help with the front-end functionality?

I'm doing it, not yet

**Comment by caibirdme** [comment]
any update for this feature?
