### ISSUE TITLE
在预览插件的时候，建议只显示启动的插件而不是显示所有的插件

### ISSUE THREAD

**Issue by edisonwd** [apache/apisix-dashboard#1991]
## Issue description
在预览插件的时候显示了所有的插件
![image](https://user-images.githubusercontent.com/25941671/126585560-a2e51cfc-933d-4c54-8b0d-083cbfaf5f1e.png)

## Expected behavior
建议只显示启动的插件而不是显示所有的插件
![image](https://user-images.githubusercontent.com/25941671/126585046-c5eb190d-d012-462d-85a5-18c2d90f17ba.png)

## Environment

* apisix version (cmd: `apisix version`): 2.7
* apisix-dashboard version, if have: 2.7
* Browser version, if have:

**Comment by liuxiran** [comment]
Good suggestion~! Actually we only need to show the configured plugins and their configuration in the preview step .

Welcome more ideas or pr to support this enhancement~

**Comment by Baoyuantop** [comment]
I tried the current issue, this is the current preview screenshot：

![image](https://user-images.githubusercontent.com/30611190/126974094-9d607fef-1292-4744-8e9f-3de1204a8254.png)

Then I have a question when there is no enabled plugin under a type, should the title of that type also be hidden?

**Comment by liuxiran** [comment]
> I tried the current issue, this is the current preview screenshot：
> 
> ![image](https://user-images.githubusercontent.com/30611190/126974094-9d607fef-1292-4744-8e9f-3de1204a8254.png)
> 
> Then I have a question when there is no enabled plugin under a type, should the title of that type also be hidden?

Yep, that would be better @Baoyuantop ~! And at the same time It would be better to not show plugin part in the preview page when there is no on enabled

**Comment by Baoyuantop** [comment]
Thank you @liuxiran, I understand, I will submit a PR for this issue

**Comment by juzhiyuan** [comment]
@Baoyuantop any update?

**Comment by Si-ege** [comment]
I would like to complete this question
