### ISSUE TITLE
Tabel style bug in Demo site

### ISSUE THREAD

**Issue by hellosean1025** [apache/apisix-dashboard#1992]
## Issue description

in http://139.217.190.60/routes/list site:
![image](https://user-images.githubusercontent.com/17695103/126587783-993a5698-0238-4108-b763-f3c6280ac1df.png)

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

**Comment by juzhiyuan** [comment]
Actually this is a fixed column mode, cc @iamayushdas to have a better description.

**Comment by iamayushdas** [comment]
Hey @hellosean1025 we have done this intentionally as our table was consisting of many columns and with long heading which was making it less responsive.

**Comment by liuxiran** [comment]
Hi all , the key point for this issue IMO is that the path of `x-app-uat1` in our demo site is to long, and we did not specify the column width, so other columns were squeezed together.
![image](https://user-images.githubusercontent.com/2561857/126905724-df434c69-7414-4804-b880-6a90063629fa.png)

We can treat this issue as an enhancement for route table display.
We can refer to https://ant.design/components/table/#components-table-demo-ellipsis-custom-tooltip, add ellipsis and tooltip for column: `host`, `path`, and `description`. 

Looking forward to your opinion.

cc @hellosean1025 @iamayushdas @juzhiyuan

**Comment by juzhiyuan** [comment]
ya, and @hellosean1025 would like to improve this? Just some configurations could solve this issue. If you need any help, just ping me.

**Comment by guoqqqi** [comment]
This issue can now be closed as it has been resolved cc @juzhiyuan @bzp2010
