### ISSUE TITLE
Home page refresh exception

### ISSUE THREAD

**Issue by JackLiMEM** [apache/apisix-dashboard#1993]
## Issue description
Home page refresh exception

## Expected behavior
Why does the prompt not match if the version is the same?

## How to Reproduce
 refresh 
## Additional context
{"code":2000001,"message":"The manager-api and apache apisix are mismatched.","data":{"matched":false,"dashboard_version":"2.7","mismatched_nodes":[{"hostname":"apisix-685cd9bb7f-vg7ns","version":"2.7"}]},"request_id":"63c689ed-d3e7-40de-81ca-aaf4edc96326"}

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/issues/1944#issuecomment-885051655

Hi, we are discussing this case here, welcome to discuss with us :) I really hope this issue will get resolved soon.
