### ISSUE TITLE
request help: when will the next version be released

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix-dashboard#1996]
Apisix 2.8 is coming soon, but apisix-Dashboard currently supports Apisix 2.6. 
I wonder when the next version of apisxi-Dashboard will be released

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/issues/1944#issuecomment-885051655

Hi, we are discussing the Dashboard version plan here, welcome to join in. Once that discussion is closed, will first release a version that is compatible with APISIX 2.7.
