### ISSUE TITLE
support uri & uris, host & hosts, remote_addr & remote_addrs

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#2013]
When we create a Route, the API supports `host/hosts` and `uri/uris` and `remote_addr/remote_addrs`. No matter API contains uri or uris, the Web should support all of them, we could use List component to show uris.

![image](https://user-images.githubusercontent.com/2106987/127469381-a0576de7-7902-470c-873e-4bec539d65a3.png)

Currently, the Web supports `uris/hosts/remote_addrs`, and please have a check if Web could show `uri/host/remote_addr`.

**Comment by Baoyuantop** [comment]
After my verification, no matter what the `Admin API` is used to create this content, the `dashboard` is behaving normally.

The only thing that needs to be done is when the dashboard creates a single `uri/host/remote_addr`, we need to set the field in the request body to `uri/host/remote_addr`.

Currently, whether it is single or multiple, it is `uris/hosts/remote_addrs`.

**Comment by juzhiyuan** [comment]
yes, we need to send `uri` if the origin data is `uri` and this field is not changed.

**Comment by liuxiran** [comment]
> After my verification, no matter what the `Admin API` is used to create this content, the `dashboard` is behaving normally.
> 
> The only thing that needs to be done is when the dashboard creates a single `uri/host/remote_addr`, we need to set the field in the request body to `uri/host/remote_addr`.
> 
> Currently, whether it is single or multiple, it is `uris/hosts/remote_addrs`.

I'm glad to hear that Web can behave normally no matter what what is used by `Admin API`, and thanks for @Baoyuantop verification.

Based on this conclusion, could we consider pushing forward the optimization of `Admin API` @juzhiyuan ? That is to say, since `APISIX` support multiple `uris/remote_addrs/hosts` in one `Route`, only `uris/remote_addrs/hosts` is enough IMO, `uri/remote_addr/host` the existence of this set of parameters only increased barriers to choice for users. What we need to do is just like current: no matter what parameters passed in `Admin API`, web can both behave normally.

**Comment by juzhiyuan** [comment]
I would also prefer keeping the the `uris` field instead of the `uri` field only, but not hurry, because if we change this in 2.x, it's a breaking change for many users maybe. Why not do this in 3.x?

**Comment by liuxiran** [comment]
> I would also prefer keeping the the `uris` field instead of the `uri` field only, but not hurry, because if we change this in 2.x, it's a breaking change for many users maybe. Why not do this in 3.x?

Agree with do it in 3.x, and that is for `Admin API`, so do we still need to change the params passed to `Manager API`?since it behave normally now

**Comment by Baoyuantop** [comment]
It should be noted that if the user uses the `Admin API` to create a `uri` field, the field will automatically change to `uris` after the user using the dashboard.

**Comment by juzhiyuan** [comment]
yes, and please go ahead :)

**Comment by Baoyuantop** [comment]
I think the #2046 change is necessary for the 2.x version, but does it seem to be lack of testing now? For testing, I only provided a few in this PR.

**Comment by juzhiyuan** [comment]
see https://github.com/apache/apisix-dashboard/pull/2046#issuecomment-894800892
