### ISSUE TITLE
[health_check] validate form item "checks.active.port" 

### ISSUE THREAD

**Issue by uriddle** [apache/apisix-dashboard#2019]
## Issue description
upstream 节点健康检查在不配置 active.port 的时候，校验出错

![QV JGL)P 6NBXR3ZNGETC3](https://user-images.githubusercontent.com/22750410/127592683-c1c89f08-1376-4ae8-a61d-33436b96e236.png)

## Expected behavior
官网介绍：
active.port: 用于发现 upstream 节点健康可用的自定义主机端口（可选），配置此项会覆盖 upstream 节点中的端口。

**Comment by juzhiyuan** [comment]
cc @Baoyuantop to have a check

**Comment by uriddle** [comment]
版本：
apisix-dashboard:2.7

**Comment by Baoyuantop** [comment]
Hi @uriddle, In order to better help you solve the problem, can you provide me how to Reproduce ?

for example ：

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by uriddle** [comment]
## How to Reproduce

1. Go to "Upstream" and then click button "configure"
![image](https://user-images.githubusercontent.com/22750410/127606908-b920f5d7-a41c-4169-8222-f088f9326fe3.png)

2. Click on 'configure ' and Scroll down to "Health Check"， click button “Active”
![image](https://user-images.githubusercontent.com/22750410/127607142-f645b5a7-badd-4eef-9d6b-8a3e6691b30a.png)


3. leave “Port” empty.  

the health check host port is optional ，so I don‘t want to change it.

finally，submit

4. See error
![image](https://user-images.githubusercontent.com/22750410/127608166-f6160d34-942e-48cf-8384-e0900c53660c.png)

**Comment by Baoyuantop** [comment]
Thank you @uriddle .

When create or update Upstream, the port option in Health Check is optional.

Dashboard will provide a default value 80, but when the user changes it to empty, dashboard will send `null` to api, this will cause this error.

The possible solution is to not pass the `port` option to the api when the user sets it to `null`, but how will we save the port status as null?

what do you think about it ? @uriddle @juzhiyuan

**Comment by uriddle** [comment]
Maybe we can deal with “Port” just like “Host” option .

**Comment by juzhiyuan** [comment]
Hi @Baoyuantop, all schema in Apache APISIX is in here[1].

I just checked the `health_checker` schema, and the `port` field is optional indeed, I'm not sure what will happen if we don't pass the port field 🤔 need more search on Apache APISIX.

BTW, the Web should omit all `null` values when sending a Request

[1] https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L139-L142

**Comment by Baoyuantop** [comment]
> Hi @Baoyuantop, all schema in Apache APISIX is in here[1].
> 
> I just checked the `health_checker` schema, and the `port` field is optional indeed, I'm not sure what will happen if we don't pass the port field 🤔 need more search on Apache APISIX.
> 
> BTW, the Web should omit all `null` values when sending a Request
> 
> [1] https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L139-L142

I tested the api, it returns 200 when I don't pass the port field, so it's a good idea to omit all `null` values

**Comment by juzhiyuan** [comment]
ok, you may need to omit all null values from a nested object value

**Comment by Baoyuantop** [comment]
I found that in the entire web if there is an optional `InputNumber` component, this bug can be reproduced.

Therefore, I think that all attributes in an object with null values in the request body should be filtered out by `requestInterceptors`.

What do y'all think?

**Comment by juzhiyuan** [comment]
yes, the Request Interceptor is also a good place to omit all `undefined & null` values.

**Comment by liuxiran** [comment]
Hi @uriddle , since pr #2042 got merged, you can retry this issue after version 2.7.1 released or just cherry-pick the related patch to your local env to hot fix this issue. Hope that will help you, reopen it when you have any questions, thanks a lot
