### ISSUE TITLE
dashboard network error

### ISSUE THREAD

**Issue by zhangbing17** [apache/apisix-dashboard#2026]
### Issue description
在dashboard中启动插件后页面包network error

![image](https://user-images.githubusercontent.com/23377580/127822808-c9396d04-2276-4826-a26c-2a87fcfb2053.png)

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.8
* OS (cmd: `uname -a`):Linux slave1 3.10.0-514.el7.x86_64 apache/apisix#1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.13
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4.0

**Comment by zhangbing17** [comment]
![image](https://user-images.githubusercontent.com/23377580/127823530-f9ddbc29-8359-4fa4-8019-85c019ff625e.png)
另外这个问题是什么原因

**Comment by zhangbing17** [comment]
apisix-dashboard 版本，如果有：2.6

![image](https://user-images.githubusercontent.com/23377580/127829124-f228aeb9-b3d6-4004-8408-a2b5fe7d79bf.png)

**Comment by Baoyuantop** [comment]
> ![image](https://user-images.githubusercontent.com/23377580/127823530-f9ddbc29-8359-4fa4-8019-85c019ff625e.png)
> 另外这个问题是什么原因

For more information, please check #1944

**Comment by zhangbing17** [comment]
> > ![image](https://user-images.githubusercontent.com/23377580/127823530-f9ddbc29-8359-4fa4-8019-85c019ff625e.png)
> > 另外这个问题是什么原因
> 
> For more information, please check #1944

这个我看了，好像没说解决方案吧。。上面的nortwork error可以帮忙看下吗

**Comment by zhangbing17** [comment]
dashboard版本目前改成2.7
![image](https://user-images.githubusercontent.com/23377580/127843235-b946b65a-1517-4a40-8f4d-7f24a151fd34.png)

**Comment by liuxiran** [comment]
duplicate with #2027

**Comment by juzhiyuan** [comment]
> > > ![image](https://user-images.githubusercontent.com/23377580/127823530-f9ddbc29-8359-4fa4-8019-85c019ff625e.png)
> > > 另外这个问题是什么原因
> > 
> > 
> > For more information, please check #1944
> 
> 这个我看了，好像没说解决方案吧。。上面的nortwork error可以帮忙看下吗

see https://github.com/apache/apisix-dashboard/issues/1944#issuecomment-885051655

**Comment by juzhiyuan** [comment]
closed due to duplicate with #2027
