### ISSUE TITLE
bug: Network Error prompted up when enable global plugin

### ISSUE THREAD

**Issue by zhangbing17** [apache/apisix-dashboard#2027]
## Issue description

启用插件和删除上游报错Network Error，有的启动插件报其他的错误

## Expected behavior

![image](https://user-images.githubusercontent.com/23377580/127845206-1a4e72eb-d8dd-48e7-acbb-cb1bf05dc7d9.png)

## How to Reproduce

1. Go to '插件'
2. Click on '启动'
3. Scroll down to '任何一个插件'

## Environment

* apisix version (cmd: `apisix version`):2.8
* OS (cmd: `uname -a`):Linux slave1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.2

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.13
* apisix-dashboard version, if have:2.7
* Browser version, if have:

![image](https://user-images.githubusercontent.com/23377580/127845626-bed1688e-eb2f-418a-a4a1-5f4396823407.png)

**Comment by liuxiran** [comment]
Thanks for your report, please provide more detailed information and this will help us to locate the problem more quickly, @zhangbing17

1. which plugin(s) will  prompt up `network error` when you enable it? I did not reproduce it in my local env
2. please provide your upstream configuration

**Comment by zhangbing17** [comment]
> Thanks for your report, please provide more detailed information and this will help us to locate the problem more quickly, @zhangbing17
> 
> 1. which plugin(s) will  prompt up `network error` when you enable it? I did not reproduce it in my local env
> 2. please provide your upstream configuration

@liuxiran 

1、就是单纯的在插件栏，启动插件
![image](https://user-images.githubusercontent.com/23377580/127942415-3ac94f62-f541-4487-89de-5439e3e064e1.png)
![image](https://user-images.githubusercontent.com/23377580/127942447-951a4b06-d6d6-480d-9e02-7570c22de476.png)
![image](https://user-images.githubusercontent.com/23377580/127942474-935ae33d-23fd-40c6-b779-144213db1260.png)
![image](https://user-images.githubusercontent.com/23377580/127942496-bf4fd4ab-5989-4d26-b40a-5bdcaa37c41f.png)
2、上游删除出错的配置
![image](https://user-images.githubusercontent.com/23377580/127942576-121363de-dd7f-45d1-95e1-ff43c1d84dec.png)

**Comment by zhangbing17** [comment]
这是安装步骤。从上面到这里
![image](https://user-images.githubusercontent.com/23377580/127943468-982a8907-86ee-4e6d-b55c-df84656c624a.png)

**Comment by liuxiran** [comment]
> ![image](https://user-images.githubusercontent.com/23377580/127942496-bf4fd4ab-5989-4d26-b40a-5bdcaa37c41f.png)

could you please also provide the message in your  dev-tools like follows: @zhangbing17 

![image](https://user-images.githubusercontent.com/2561857/127947365-f14ee2ca-9020-424a-9085-efb6f8f34a0a.png)

**Comment by liuxiran** [comment]
and need to provide message in your dev-tools when you delete upstream like follows:

![image](https://user-images.githubusercontent.com/2561857/127947737-1d078f88-d26d-4b74-b076-daa984c11f46.png)

**Comment by zhangbing17** [comment]
> > ![图像](https://user-images.githubusercontent.com/23377580/127942496-bf4fd4ab-5989-4d26-b40a-5bdcaa37c41f.png)
> 
> 您能否在您的开发工具中提供如下消息：@zhangbing17
> 
> ![图像](https://user-images.githubusercontent.com/2561857/127947365-f14ee2ca-9020-424a-9085-efb6f8f34a0a.png)


这是是启动插件的
![image](https://user-images.githubusercontent.com/23377580/127948012-7fc0aa97-87b1-4435-be5e-f7b799ee2124.png)

**Comment by zhangbing17** [comment]
> and need to provide message in your dev-tools when you delete upstream like follows:
> 
> ![image](https://user-images.githubusercontent.com/2561857/127947737-1d078f88-d26d-4b74-b076-daa984c11f46.png)

@liuxiran 可以微信，，，或者QQ么。。我在578997126这个群里。

这是删除上游。路由、消费者的，，看不到具体信息，感觉应该也是404.。
![image](https://user-images.githubusercontent.com/23377580/127948258-506d6e40-f68b-4eb3-9e89-5fc080321508.png)

**Comment by liuxiran** [comment]
> 这是是启动插件的
> ![image](https://user-images.githubusercontent.com/23377580/127948012-7fc0aa97-87b1-4435-be5e-f7b799ee2124.png)

and please provide your data message, like this:

![image](https://user-images.githubusercontent.com/2561857/127949577-dcc933d7-ffd4-45bb-9ada-171f0fa76d90.png)

and did you modify any code?

**Comment by zhangbing17** [comment]
> > 这是是启动插件的
> > ![image](https://user-images.githubusercontent.com/23377580/127948012-7fc0aa97-87b1-4435-be5e-f7b799ee2124.png)
> 
> and please provide your data message, like this:
> 
> ![image](https://user-images.githubusercontent.com/2561857/127949577-dcc933d7-ffd4-45bb-9ada-171f0fa76d90.png)
> 
> and did you modify any code?

这是启用插件的
![image](https://user-images.githubusercontent.com/23377580/127949864-f70cd8db-d385-4c87-8570-22d42c9c779f.png)

**Comment by liuxiran** [comment]
seems that there is nothing wrong with parameters, need @nic-chen @starsz to take a look, 
in his env, return `code: 10001` when call `PUT /apisix/admin/global_rules/1`

**Comment by juzhiyuan** [comment]
@zhangbing17 What's your WeChat account? Let's arrange a online meeting.

**Comment by nic-chen** [comment]
@zhangbing17 

What's the data in your etcd?

You could get it by executing:
```
etcdctl get --prefix/
```

**Comment by zhangbing17** [comment]
> @zhangbing17你的微信账号是什么？让我们安排一个在线会议。

13275607690

**Comment by zhangbing17** [comment]
> > @zhangbing17你的微信账号是什么？让我们安排一个在线会议。
> 
> 13275607690



> @zhangbing17
> 
> 您的 etcd 中的数据是什么？
> 
> 你可以通过执行得到它：
> 
> ```
> etcdctl get --prefix/
> ```

![image](https://user-images.githubusercontent.com/23377580/127955653-b9160a9c-372f-400d-b3e8-3f5512d70b2e.png)

**Comment by nic-chen** [comment]
@zhangbing17  
it should be 
```
etcdctl get --prefix /
```
sorry for typo

**Comment by zhangbing17** [comment]
> ```
> etcdctl get --prefix /
> ```
![image](https://user-images.githubusercontent.com/23377580/127958020-f4222be0-505b-4478-b48e-2bd53d49fd37.png)

![image](https://user-images.githubusercontent.com/23377580/127958046-b97b9960-ddd3-411e-b619-7a38554ef5dc.png)

**Comment by nic-chen** [comment]
@zhangbing17  please check the error log

**Comment by zhangbing17** [comment]
> @zhangbing17 please check the error log

这错是是我另外个demo项目没起，，跟我删除路由、上游、服务、启动插件没关系呀

**Comment by nic-chen** [comment]
> > @zhangbing17 please check the error log
> 
> 这错是是我另外个demo项目没起，，跟我删除路由、上游、服务、启动插件没关系呀

please check the error log of the dashboard.

**Comment by zhangbing17** [comment]
> > > @zhangbing17请查看错误日志
> > 
> > 
> > 这错是我另外一个demo项目没起，跟删除路由、上行、服务、启动原生环境呀
> 
> 请检查仪表板的错误日志。

我把dashboard下面的error日志清了，在走，日志里面没输出任何

**Comment by zhangbing17** [comment]
在 @nic-chen 的帮助下  ， 目前已经解决，原因是我们公司关掉了put和delete请求
