### ISSUE TITLE
lint-staged caused many additional changes

### ISSUE THREAD

**Issue by Baoyuantop** [apache/apisix-dashboard#2035]
## Issue description
When committing some code changes in the `web`, `lint-staged` started and made many additional changes (regarding the code format), which caused a lot of trouble for the review code.

I noticed that this feature was added 15 days ago #1957, and the corresponding code format may be missing before then?

## Expected behavior
In a PR, `lint-staged` does not change the extra code

## How to Reproduce
Make code changes on the web, and then commit the code.

## Screenshots
![image](https://user-images.githubusercontent.com/30611190/128285305-9437834e-5cab-4c1e-9924-10df7ea30927.png)
https://github.com/apache/apisix-dashboard/pull/2034/files#diff-88ff6b2eb91bde63ed36ce0bbe0bc5c2f3bd70977e509e81cafd2e56b6da44dbR17

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

## Additional context
I tried lint the whole project, and the result was a lot of changes:

![image](https://user-images.githubusercontent.com/30611190/128284603-ff53a09e-b0e4-42bc-887f-f10398902483.png)

When commit these changes, eslint prompts many errors:

![image](https://user-images.githubusercontent.com/30611190/128284818-ea9c4413-0618-474d-a600-00c67cac35e6.png)

Some of them need to modify the previously non-standard code, and some need to adjust the rules of eslint to adapt to the project.

Any good suggestions？

**Comment by juzhiyuan** [comment]
cc @iamayushdas to take a look

**Comment by Baoyuantop** [comment]
I will try to fix these `eslint` errors and then submit these changes to a PR.

**Comment by juzhiyuan** [comment]
ok
