### ISSUE TITLE
Click submit in the viewing page of Consumer will create an new consumer

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix-dashboard#2053]
## Issue description
Recurrence steps:

1. click [查看(veiw)] button:
![image](https://user-images.githubusercontent.com/9711651/128722692-d625c64f-28b2-4bd3-89a7-b69879f0c8f8.png)

2. Click [提交(sumit)]button:
![image](https://user-images.githubusercontent.com/9711651/128722874-a41f053e-15c6-4638-9f5d-0f3744862d63.png)

3. a new consumer named undefined been created
![image](https://user-images.githubusercontent.com/9711651/128723075-c6b089a7-e6cf-411b-be36-8a7a8e90cea5.png)

4. At this time, the old consumer (bug_test) has been unable to authenticate when consumer-restriction plugin been add.

## Environment

* apisix version (cmd: `apisix version`): 2.8-docker
* apisix-dashboard version, if have: latest(2.7)-docker

**Comment by juzhiyuan** [comment]
cc @LiteSun to take a look

**Comment by Baoyuantop** [comment]
Solved at #1987  @jagerzhang
