### ISSUE TITLE
Make sure validate rules in Apisix Dashboard is same as Apisix api

### ISSUE THREAD

**Issue by suninuni** [apache/apisix-dashboard#2057]
## Issue description

Some rules can be created by CRD, but can not be modified in dashboard.

e.g. `/` in ApisixRoute.spec.http[].name

![image](https://user-images.githubusercontent.com/7345529/128958429-b83abdd2-4220-4a5d-852f-36ed23cae4ae.png)

e.g. add key in limit-count.lua

![image](https://user-images.githubusercontent.com/7345529/128958884-c7cbc4dd-199e-40fe-88e1-bc5075b84c14.png)

## Expected behavior

Make sure validate rules in Apisix Dashboard is same as Apisix api.

**Comment by Baoyuantop** [comment]
Hi @suninuni, would you please help provide environmental information? 

For example:

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

**Comment by bzp2010** [comment]
It seems to be the rule problem of schema checker in dashboard.

**Comment by bzp2010** [comment]
Hi, @suninuni. Can you provide a CRD used yaml file that hides key information?

**Comment by bzp2010** [comment]
Hi, @suninuni. 
OK, I already know the yaml file you use. Sorry, I don't have a k8s local environment, so I can't test directly.

However, according to the principle of ingress controller, it will call the Admin API in APISIX to operate resources such as routes, and this API does perform schema validation.
[https://github.com/apache/apisix/blob/174044e60cfbad6f8aa023200f3be145f5249ed1/apisix/plugins/limit-count.lua#L127](https://github.com/apache/apisix/blob/174044e60cfbad6f8aa023200f3be145f5249ed1/apisix/plugins/limit-count.lua#L127)

I also tested it on the local apisex environment and confirmed that when the key is not within the optional range, the API will return an error. The route record cannot be created normally at this time.
![image](https://user-images.githubusercontent.com/8078418/129137200-210b9327-b067-4e2a-b57d-1bf69d99117e.png)

Therefore, I would like to know if you have done some other operations, such as directly operating ETCD, etc.

**Comment by suninuni** [comment]
> I also tested it on the local apisex environment and confirmed that when the key is not within the optional range, the API will return an error. The route record cannot be created normally at this time.

> Therefore, I would like to know if you have done some other operations, such as directly operating ETCD, etc.

@bzp2010 I just modified the file limit-count.lua according to the document in Apisix image.
 
![image](https://user-images.githubusercontent.com/7345529/129142406-4175517f-5f5b-4f6d-93ee-047addfbbba4.png)

> AND update limit-count.lua with new key http_x_account_id.

Add http_x_account_id in the [enums](https://github.com/apache/apisix/blob/174044e60cfbad6f8aa023200f3be145f5249ed1/apisix/plugins/limit-count.lua#L41).

SO the enums is defined in three places, which mean I need update them if I want add a new key?

- dashboard:
    - web/src/components/Plugin/UI/limit-count.tsx https://github.com/apache/apisix-dashboard/blob/af855915896562c488c2b4669e24883cd140cfb5/web/src/components/Plugin/UI/limit-count.tsx#L265-L270
    - api/conf/schema https://github.com/apache/apisix-dashboard/blob/82575987ebc18b46676a397732c2c4c09dd37191/api/conf/schema.json#L3476
 - apisix:
     - limit-count.lua https://github.com/apache/apisix/blob/174044e60cfbad6f8aa023200f3be145f5249ed1/apisix/plugins/limit-count.lua#L41

**Comment by suninuni** [comment]
@bzp2010 Thanks.

![image](https://user-images.githubusercontent.com/7345529/129146623-b654f541-94ce-4785-82e2-03e8c703cca2.png)

In my test, I don't need modify the schema which generated by APISIX. So why doesn't the dashboard call this api at startup?

**Comment by bzp2010** [comment]
@suninuni APISIX and Dashboard can be deployed separately, and the only connection between them is the same ETCD.

**Comment by suninuni** [comment]
@bzp2010 OK, I have no problem, thank you very much.

**Comment by suninuni** [comment]
@bzp2010 Another question

> / in ApisixRoute.spec.http[].name

![](https://user-images.githubusercontent.com/7345529/128958429-b83abdd2-4220-4a5d-852f-36ed23cae4ae.png)

Why does the Dashboard specify the validation rules instead of using the rules in schema.json(actually schma only defined the max length)? Any issues or design document can help me understand this behavior?

https://github.com/apache/apisix-dashboard/blob/b0dfcb4b85c9ab7949fd741acf18d062bdd8ff9f/web/src/pages/Route/components/Step1/MetaView.tsx#L139

**Comment by liuxiran** [comment]
> @bzp2010 Another question
> 
> > / in ApisixRoute.spec.http[].name
> 
> ![](https://user-images.githubusercontent.com/7345529/128958429-b83abdd2-4220-4a5d-852f-36ed23cae4ae.png)
> 
> Why does the Dashboard specify the validation rules instead of using the rules in schema.json(actually schma only defined the max length)? Any issues or design document can help me understand this behavior?
> 
> https://github.com/apache/apisix-dashboard/blob/b0dfcb4b85c9ab7949fd741acf18d062bdd8ff9f/web/src/pages/Route/components/Step1/MetaView.tsx#L139

thanks @suninuni we will fix it in 2.7.2. it should be the same with the schema define

**Comment by bzp2010** [comment]
Hi, @suninuni.

**Comment by liuxiran** [comment]
hi @foolwc @iamayushdas @KishaniKandasamy , do you have time to deal with this issue?

**Comment by iamayushdas** [comment]
@liuxiran according to me this will make changes in both pattern regex and rule naming right?

**Comment by liuxiran** [comment]
> @liuxiran according to me this will make changes in both pattern regex and rule naming right?

you are right👏
