### ISSUE TITLE
Impossible to create an authz-keycloak plugin config.

### ISSUE THREAD

**Issue by Guillaume69** [apache/apisix-dashboard#2076]
### Issue description

The editor tells me that it doesn't need configuration, so the field is disabled and i can't write into it.

### Expected behavior

I expect to be able to write some configuration in the editor.

### How to Reproduce

create a route, and in the last step click "enable" on the authz-keycloak plugin and try to write a configuration.

### Screenshots

![Capture d’écran 2021-08-18 à 17 28 27](https://user-images.githubusercontent.com/11858349/129926826-b0b36be9-d864-4ef6-b295-7e349661794d.png)

### Environment

- apisix version (cmd: `apisix version`): 2.7
- OS (cmd: `uname -a`): Alpine (via docker)
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): -
- etcd version, if have (cmd: run `etcd --version`): 3.4.9 (docker image)
- apisix-dashboard version, if have: the latest docker image (i assume 2.7.1 ?), but wasn't working on 2.7 or 2.6 either.
- Browser version, if have: Google Chrome 92.0.4515.131

**Comment by liuxiran** [comment]
We have solved this issue in: https://github.com/apache/apisix-dashboard/pull/1983, and released in 2.7.1

Just confirm where did your docker image come from? from https://hub.docker.com/r/apache/apisix-dashboard?

**Comment by Guillaume69** [comment]
Hi @liuxiran 

i confirm that i pulled it from apache/apisix-dashboard on docker hub, tag "latest" but i still have the issue.

**Comment by juzhiyuan** [comment]
cc @nic-chen to have a look

**Comment by nic-chen** [comment]
> Hi @liuxiran
> 
> i confirm that i pulled it from apache/apisix-dashboard on docker hub, tag "latest" but i still have the issue.

Please try again. The previous latest is still the 2.7 version.

**Comment by Guillaume69** [comment]
@nic-chen yeah, works fine :) Thank you, you're the best guys.

**Comment by Guillaume69** [comment]
Fixed in 2.7.1
