### ISSUE TITLE
Feature request: support FQDN in upstream

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#2080]
# Feature request

## Please describe your feature

Currently we can only configure upstream nodes in UI by `Address + (required) Port`, but in fact APISIX also support FQDN, see https://apisix.apache.org/docs/apisix/2.7/FAQ/#does-the-upstream-node-support-configuring-the-fqdn-address, we should update our UI to fit this option.

## Describe the solution you'd like

We can update our input constraints, make port an optional input, and at the same time we can also consider whether to change `host` to the suitable name.

**Comment by bzp2010** [comment]
Hi, @liuxiran.
It seems that the dashboard can now support host input in the form of FQDN. What's the problem?
![image](https://user-images.githubusercontent.com/8078418/130075518-9c2961a1-09a8-45e5-8bd3-44e372d99253.png)
![image](https://user-images.githubusercontent.com/8078418/130075579-3a02b215-cf0d-4ba2-bd8b-0dc138fc2694.png)

**Comment by liuxiran** [comment]
> Hi, @liuxiran.
> It seems that the dashboard can now support host input in the form of FQDN. What's the problem?
> ![image](https://user-images.githubusercontent.com/8078418/130075518-9c2961a1-09a8-45e5-8bd3-44e372d99253.png)

refer to https://github.com/apache/apisix/blob/release/2.7/docs/en/latest/FAQ.md#does-the-upstream-node-support-configuring-the-fqdn-address

when we use FQDN, we do not need to enter `Port`, so fe need to make `Port` an optional field.

Please let me know if I have misunderstood, thanks @bzp2010 

cc @nic-chen @tao12345666333

**Comment by bzp2010** [comment]
I think at the same time we can give it a default value of port 80. XD

**Comment by liuxiran** [comment]
Hi @foolwc , do you have time to take this issue?

**Comment by foolwc** [comment]
I'm willing to take. Just make the `Port`  has a default value and optional ? @liuxiran

**Comment by liuxiran** [comment]
> I'm willing to take. Just make the `Port` has a default value and optional ? @liuxiran

thanks @foolwc , only need to make the `Port` optional, to avoid misuse, we can keep `Port` field empty as default

**Comment by foolwc** [comment]
The upstream JSON schema shows that `Port` must be an Integer. And if we support FQDN, the `nodes` will be an `Object` but not an `Array`. So I'm confused how to deal with it. Please give me some lint. Thanks a lot @liuxiran  
```
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/ip",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.default.svc.cluster.local": 1
        }
    }
}'
```

**Comment by liuxiran** [comment]
```json
nodes: {
	"anyOf": [{
		"patternProperties": {
			".*": {
				"description": "weight of node",
				"minimum": 0,
				"type": "integer"
			}
		},
		"type": "object"
	}, {
		"items": {
			"properties": {
				"host": {
					"pattern": "^\\*?[0-9a-zA-Z-._]+$",
					"type": "string"
				},
				"metadata": {
					"description": "metadata of node",
					"type": "object"
				},
				"port": {
					"description": "port of node",
					"minimum": 1,
					"type": "integer"
				},
				"priority": {
					"default": 0,
					"description": "priority of node",
					"type": "integer"
				},
				"weight": {
					"description": "weight of node",
					"minimum": 0,
					"type": "integer"
				}
			},
			"required": ["host", "port", "weight"],
			"type": "object"
		},
		"type": "array"
	}]
}
```

Hi @foolwc here is our upstream nodes schema, you can see that we support two type of nodes:

* currently we use the second one, which required `host` `port` and `weight`
* when we use FQDN, we can change to the first one, that is:
```json
{
    ${host1}: ${weight1},
    ${host2}: ${weight2},
    ...
}
```

**Comment by foolwc** [comment]
There is a case: if we add two hosts, one is FQDN without port, the other is normal IP with port. How to deal with that, saved with Array or Object just like below ? Thanks for your explanation @liuxiran 
```json
{
     "httpbin.default.svc.cluster.local": 1
     "httpbin2.default.svc.cluster.local:8080": 1
}
```

**Comment by liuxiran** [comment]
> > {
> > "httpbin.default.svc.cluster.local": 1
> > "httpbin2.default.svc.cluster.local:8080": 1
> > }
> 
> Object is good for me, @tzssangglass @nic-chen for double check , thanks

Hi @foolwc please use object as the data struct, no matter enter `IP:port` or `host`

```json
{
    `${IP/host}${: port?}`: ${weight}
}
```

any question please comment here, thanks

**Comment by nic-chen** [comment]
> > {
> > "httpbin.default.svc.cluster.local": 1
> > "httpbin2.default.svc.cluster.local:8080": 1
> > }
> 
> Object is good for me, @tzssangglass @nic-chen for double check , thanks

LGTM

**Comment by starsz** [comment]
> > > {
> > > "httpbin.default.svc.cluster.local": 1
> > > "httpbin2.default.svc.cluster.local:8080": 1
> > > }
> > 
> > 
> > Object is good for me, @tzssangglass @nic-chen for double check , thanks
> 
> Hi @foolwc please use object as the data struct, no matter enter `IP:port` or `host`
> 
> ```json
> {
>     `${IP/host}${: port?}`: ${weight}
> }
> ```
> 
> any question please comment here, thanks

LGTM.

**Comment by foolwc** [comment]
No question, thanks. It's ok to assign to others if this feature is urgent or someone else can do :)   I don't have much time on weekdays and maybe delay your work

**Comment by liuxiran** [comment]
> No question, thanks. It's ok to assign to others if this feature is urgent or someone else can do :) I don't have much time on weekdays and maybe delay your work

Thanks very much for your information, since it is one of our milestone task, and tomorrow is the deadline,  I 'll assign to others, we have other issues you can try the one you want to, thanks again to drive this issue needs to be clear
