### ISSUE TITLE
Bug: after enable redirect  HTTPS,  websocket form field disappeared

### ISSUE THREAD

**Issue by bingoku** [apache/apisix-dashboard#2087]
### Issue description

![image](https://user-images.githubusercontent.com/4134788/130649980-e8949fd6-bf6a-4879-b956-6f3413f9cbf3.png)

### Expected behavior

开启 HTTPS 后能显示 websocket 按钮进行操作

### How to Reproduce

稳定复现

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by liuxiran** [comment]
Hi @bingoku , see here to learn more: https://github.com/apache/apisix-dashboard/issues/1933#issuecomment-895062189

so may I ask what your actual needs are for this operation? Then we can recommend a suitable operating procedure, thanks

**Comment by bingoku** [comment]
其实就是想这个 UI 能发挥自身的作用，个别功能是缺失的。
上述这个问题是，开启重定向后，依然可以选择 继续开启 websocket 是需求。

**Comment by liuxiran** [comment]
> 上述这个问题是，开启重定向后，依然可以选择 继续开启 websocket 是需求。

Is it a possible requirement need @spacewander @tzssangglass 's help, since  @spacewander has helped confirmed that when enable redirect plugin, we do not need `enable_websocket` field.

**Comment by spacewander** [comment]
I see. When the user enables http_to_https, the redirect only happens with HTTP request. So they can still do websocket handshake with the HTTPS request.

**Comment by liuxiran** [comment]
> I see. When the user enables http_to_https, the redirect only happens with HTTP request. So they can still do websocket handshake with the HTTPS request.

thanks @spacewander , that means user can  configure the `enable_websocket` and it can take action, right?

**Comment by spacewander** [comment]
Yes

**Comment by liuxiran** [comment]
> 其实就是想这个 UI 能发挥自身的作用，个别功能是缺失的

welcome to submit issues about missing features, that would be very helpful to make dashboard work better with APISIX. 

Meanwhile, we are now working on making dashboard work smoothly with APISIX2.7, see here: https://github.com/apache/apisix-dashboard/milestone/15, and will soon arrange our milestone 2.8(work with APISIX 2.8) and 2.9 (work with APISIX 2.9),   welcome to participate in, thanks @bingoku

**Comment by liuxiran** [comment]
> Yes

got you, thanks, add this bug to 2.7.2 milestone.

**Comment by liuxiran** [comment]
Hi @iamayushdas , would you like to try to fix this issue?
