### ISSUE TITLE
Feature request: supporting key-auth plugin to get key from query string

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#2092]
# Feature request

## Please describe your feature

refer to https://github.com/apache/apisix/pull/4490, currently we can configure `key-auth` plugin in Route and Service with `header` or `query` properties, so we should remove the tip in the `key-auth` configure page when create/configure Route 、 Service and global plugin

![image](https://user-images.githubusercontent.com/2561857/130881846-c23ec0d2-ac5c-428b-b757-66c9b3d3a23d.png)

**Comment by zaunist** [comment]
Hi, @liuxiran . IMO, we just remove the tips ?
