### ISSUE TITLE
Feature request: plugin: Form config data editer for custom plugin

### ISSUE THREAD

**Issue by fregie** [apache/apisix-dashboard#2111]
# Feature request

## Please describe your feature

Custom plugin only support editing config data by json or yaml.I think use form to edit plugin config is a good idea.

**Comment by liuxiran** [comment]
You are right @fregie , use form to configure plugin is a good way for users, and build UI from json schema is also our ideal state, see here: https://github.com/apache/apisix-dashboard/issues/1039.

Would you like to continue to explore its feasibility, and share your idea about it?

**Comment by fregie** [comment]
> You are right @fregie , use form to configure plugin is a good way for users, and build UI from json schema is also our ideal state, see here: #1039.
> 
> Would you like to continue to explore its feasibility, and share your idea about it?

OK,let's disscus it in #1039
