### ISSUE TITLE
redeveloped apisix dashboard to add security/permissions, but when i run manageApi, still run old code

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-dashboard#2114]
### Issue description

1、i redeveloped apisix dashboard and add security/permissions system
2、when i running local main.go under vscode, i can get the correct result
3、when i running ./manage-api, it seems my code doesn't effect（it running as normal apisix-dashboard-2.7）

### Expected behavior

1、my code will be effectived when i running ./manage-api

### How to Reproduce

1、 because there's too much code, i can't put on it

### Environment

- apisix version (cmd: `apisix version`): 2.6
- apisix-dashboard version, if have: 2.7

### Additional context

Advise we can have any redeveloped doc for apisix-dashboard like apisix

**Comment by liuxiran** [comment]
Hi @Marco-Zheng 

1. see here : https://github.com/apache/apisix-dashboard/pull/2010, whether you do the same thing
3. you can refer this doc : https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md to see if there is a missing step

**Comment by Marco-Zheng** [comment]
@liuxiran Many thanks, it works!

**Comment by liuxiran** [comment]
ok then close this issue now, thanks for @Marco-Zheng feedback
