### ISSUE TITLE
Request help: could not login grafana

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#2122]
### Issue description

TODO

### Expected behavior

TODO

### How to Reproduce

TODO

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by wjmmjr** [comment]
问题描述：grafana单独登录正常，作了页面嵌入，可以在apisix显示，但是登录成功后又会跳转登陆界面
环境：k8s
版本：apisix-dashboard-2.7、grafana8.1.2
![eda045aa781e2ce724b56192f94a850](https://user-images.githubusercontent.com/18857921/132156000-6130a18c-04d1-4bb1-a5d5-942ccf99d9a6.png)

日志如下：
![3b6cf7eed151a7b21723ea0227f4712](https://user-images.githubusercontent.com/18857921/132156016-b749dcb8-4daf-4a6f-95ed-ca4472ce9889.png)

**Comment by liuxiran** [comment]
@wjmmjr thanks for your report, let‘s have a meeting to check your environment, is 4:00 pm today a convenient time for you？

**Comment by liuxiran** [comment]
Thanks for @wjmmjr 's details, during the offline communication, I noticed that there are two sets of environments, one is for test, and another is for production, the test environment can be used normally without problems, but in the production environment, when login grafana, it will be return http code 302, and redirect to /, and in the test, we can see it will redirect to `/api/live/ws`

and he has tried to clear browser cache, and even change a new browser , we can exclude the browser cache.

request help from @nic-chen @imjoey , please take a look when you have time ,thanks a lot

**Comment by nic-chen** [comment]
@wjmmjr 
Please confirm whether the host and port before and after logging in are the same and whether it is redirected to another address after logging in.

The other is to provide your browser information (what browser, and its version), and whether there are any error messages in the browser during this process.

**Comment by wjmmjr** [comment]
my apisix-dashboard is HTTPS domain name，so when i also configure the https domain name for grafana,the problem is solved.

**Comment by liuxiran** [comment]
> my apisix-dashboard is HTTPS domain name，so when i also configure the https domain name for grafana,the problem is solved.

glad to hear that, would you like to add a FAQ to our dashboard, that will be of great help to the later users. @wjmmjr
