### ISSUE TITLE
Store the grafana config in apisix-dashboard

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#2127]
# Feature request

## Please describe your feature

Now, we can config the grafana link in apisix-dashboard, but we can't store the grafana link.
I think we can store the link.

## Describe the solution you'd like

Store the grafana link in etcd

## Describe alternatives you've considered

We can store the grafana link in etcd, and the FE can get the link via API.

**Comment by liuxiran** [comment]
Similar issue:  #1953

**Comment by starsz** [comment]
> Similar issue: #1953

Nice. Got it.
