### ISSUE TITLE
Bug: route pagination error when delete the route item in the last page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#2129]
### Issue description

![page error](https://user-images.githubusercontent.com/2561857/132474934-26f2cca0-c999-4bfa-81af-d95f43a3bb12.png)

when delete last item in the route list , there will no data rendered in the route list, we should update the page query item

### Expected behavior

![image](https://user-images.githubusercontent.com/2561857/132475248-7e1221b0-a45c-4ea8-8526-fd0b53623d68.png)

### How to Reproduce

1. there are 11 routes, and page size is 10
2. turn to the second page, delete the last route

### Environment

- apisix version (cmd: `apisix version`): null
- OS (cmd: `uname -a`): macOS
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): null
- etcd version, if have (cmd: run `etcd --version`): null
- apisix-dashboard version, if have: 2.8
- Browser version, if have: chrome

**Comment by freecodelover** [comment]
I can reproduce it too.
And I see it's requesting such a URL `/apisix/admin/routes?label=&page=2&page_size=10` after deleting the last router.

But the page number is changed to `1` not the previous `2`, so it is confusing.
![image](https://user-images.githubusercontent.com/89953447/133546834-d31427b5-2a4a-4a1f-a536-b2c013b8db7f.png)

I think it's better to use the `page` value in the URL.

**Comment by oil-oil** [comment]
Please assign this task to me and I will fix it.
