### ISSUE TITLE
bug: produce problem of installing by using rpm 

### ISSUE THREAD

**Issue by mzk1234567-mzk** [apache/apisix-dashboard#2130]
### Issue description

install by using rpm to produce problem

### Expected behavior

Service is starting

### How to Reproduce

cd /dashborad
 ./manager-api start
Starting Apache APISIX Dashboard:					[  OK  ]
./manager-api status
Service is stopped

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by mzk1234567-mzk** [comment]
Error occurred while initializing logical store:  /apisix/routes
Error: json unmarshal failed
	Related Key:		1415214191809982464
	Error Description:	json: cannot unmarshal object into Go struct field Route.methods of type []string
Usage:
  manager-api [flags]
  manager-api [command]

Available Commands:
  help        Help about any command
  install     re-install Apache APISIX Dashboard service
  remove      remove Apache APISIX Dashboard service
  start       start Apache APISIX Dashboard service
  status      inspect the status of Apache APISIX Dashboard service
  stop        stop Apache APISIX Dashboard service/program
  version     show manager-api version

Flags:
  -c, --config string     config file (default "./conf/conf.yml")
  -f, --force             force start manager-api
  -h, --help              help for manager-api
  -p, --work-dir string   current work directory (default ".")

Use "manager-api [command] --help" for more information about a command.

json unmarshal failed
	Related Key:		1415214191809982464
	Error Description:	json: cannot unmarshal object into Go struct field Route.methods of type []string

**Comment by liuxiran** [comment]
Hi @mzk1234567-mzk which version of rpm did you use?

**Comment by mzk1234567-mzk** [comment]
etcd的版本号为：v3.5.0
OS：3.10.0-862.el7.x86_64

**Comment by liuxiran** [comment]
cc @imjoey to help to check , thanks a lot

**Comment by mzk1234567-mzk** [comment]
i have make it，3Q ,no problem

**Comment by liuxiran** [comment]
> i have make it，3Q ,no problem

How did you fix your problem, or maybe there's a problem with the way it's used? would you like to share your whole process here? Thanks very much @mzk1234567-mzk

**Comment by imjoey** [comment]
@liuxiran From the error log `Error Description: json: cannot unmarshal object into Go struct field Route.methods of type []string`, I guess there's something wrong with the etcd service or some broken data stored in etcd. Since no response from @mzk1234567-mzk, let us close this. @mzk1234567-mzk your further feedback is welcome.
