### ISSUE TITLE
install failed by rpm

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix-dashboard#2134]
### Issue description

The documentation describes the following ways to install
```
sudo yum install -y https://github.com/apache/apisix-dashboard/releases/download/v2.8.0/apisix-dashboard-2.8.0-0.x86_64.rpm
```
However, there is no pisix-dashboard-2.8.0-0.x86_64.rpm on the release page
![image](https://user-images.githubusercontent.com/17425270/132659569-743c012e-f28b-42b2-8c1a-fccde8f8348a.png)

### Expected behavior

install success by rpm

### How to Reproduce

none

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by liuxiran** [comment]
Hi @zuiyangqingzhou , thanks for your report, checking and will upload the correct rpm soon

cc @imjoey

**Comment by liuxiran** [comment]
Hi @zuiyangqingzhou, the correct rpm package has been uploaded, you can have a try

By the way, the link in our deploy-with-rpm doc is wrong , fix it by pr #2136 , thanks

cc @imjoey

**Comment by imjoey** [comment]
/lgtm .

Thanks for the update. @liuxiran.

**Comment by zuiyangqingzhou** [comment]
good job

**Comment by liuxiran** [comment]
Hi @zuiyangqingzhou , all fixes are ok now, feel free to reopen this issue when you have any questions, thanks
