### ISSUE TITLE
Go Report is not good as usual

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#2135]
### Issue description

Go Report is not good, please have a check.

see https://goreportcard.com/report/github.com/apache/apisix-dashboard

### Expected behavior

I remember ManagerAPI is A+ before 🤔 So please have a check what happened here.

### How to Reproduce

see https://goreportcard.com/report/github.com/apache/apisix-dashboard

### Environment

- apisix version (cmd: `apisix version`): None
- OS (cmd: `uname -a`): None
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): None
- etcd version, if have (cmd: run `etcd --version`): None
- apisix-dashboard version, if have: None
- Browser version, if have: None

**Comment by zaunist** [comment]
Hi,@juzhiyuan  ,I noticed that the last refresh of the page was three months ago, so I clicked Refresh Now and it is now A+   https://goreportcard.com/report/github.com/apache/apisix-dashboard

**Comment by juzhiyuan** [comment]
thanks!
