### ISSUE TITLE
test: unstable test case search-route

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#2140]
After checking the video log, we can found that the [E2E failed](https://github.com/apache/apisix-dashboard/pull/2066/checks?check_run_id=3592634363) caused by 
![image](https://user-images.githubusercontent.com/2561857/133535093-9ebc213c-e2da-4f53-a893-d21411758b8b.png)

we need to find a better way to fix this unstable test case.

video log here:
https://user-images.githubusercontent.com/2561857/133535785-4eae0421-9b8c-43e7-b667-9a3bc879c8ad.mp4

_Originally posted by @liuxiran in https://github.com/apache/apisix-dashboard/issues/2066#issuecomment-920510163_

**Comment by LiteSun** [comment]
After analysis, I think we can solve this problem in two directions.

1. wait a few seconds before clicking the add button (fastest change but not recommended)
2. optimize the existing code logic to ensure that the drawer content is rendered consistently before popping up the drawer. e.g. wait for the interface response to finish before popping up the drawer. (recommended)

Waiting for others' options
