### ISSUE TITLE
bug: Demo site is built from the latest code 

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-dashboard#2141]
### Issue description

As far as I know, the current demo site `http://139.217.190.60/` is built from the latest code. IMHO, this demo site should be far more stable than we expected, to let users know well about APISIX. So shall we use the stable version instead, which means more reliable for everyone.

### Expected behavior

The current demo site is built with the latest stable version of apisix-dashboard.

### How to Reproduce

Kind of policy, no need for reproduced steps.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by imjoey** [comment]
@nic-chen @liuxiran @juzhiyuan @gxthrj, looking forward to your insights. Thanks.

**Comment by juzhiyuan** [comment]
How about maintaining 2 sites? 

A-URL -> Stable
B-URL -> Latest from the master branch

**Comment by iamayushdas** [comment]
Thats a really good idea Zhiyuan sir, looking forward to other’s opinions
to this.

Best regards
Ayush Das<https://github.com/iamayushdas>

**Comment by Baoyuantop** [comment]
> How about maintaining 2 sites?
> 
> A-URL -> Stable
> B-URL -> Latest from the master branch

Agree

**Comment by imjoey** [comment]
> How about maintaining 2 sites?
> 
> A-URL -> Stable
> B-URL -> Latest from the master branch

@juzhiyuan yep, this sounds great.

**Comment by bzp2010** [comment]
> How about maintaining 2 sites?
> 
> A-URL -> Stable
> B-URL -> Latest from the master branch

Agree with this, should we use another IP address, or can we deploy a dashboard over APISIX and distinguish the environment based on the path.

**Comment by juzhiyuan** [comment]
both are ok
