### ISSUE TITLE
support set scope as Path in Advanced Routing Matching Conditions

### ISSUE THREAD

**Issue by suninuni** [apache/apisix-dashboard#2146]
# Feature request

## Please describe your feature

I need to set an Advanced Routing Matching Conditions for path, such as Regex Match rule, but now I can’t configure it through the dashboard.

![image](https://user-images.githubusercontent.com/7345529/134637533-0f5479e9-ce2c-4422-9263-6436cd9e40d3.png)

Even after I configured these rules through ApisixRoute, they displayed as null and I couldn’t modify other options which will change these null value as default.

![image](https://user-images.githubusercontent.com/7345529/134637973-3c436edd-0c3c-4af1-bac0-ca170abb1e3e.png)

![image](https://user-images.githubusercontent.com/7345529/134637839-9f8da6c4-0429-463b-8f4e-c84aa380f9c2.png)

## Describe the solution you'd like

Support Path in  Advanced Routing Matching Conditions

**Comment by bzp2010** [comment]
It should work fine on the current latest version. So I will close this issue.
