### ISSUE TITLE
提示 auth-keycloak 不属于验证插件

### ISSUE THREAD

**Issue by geffzhang** [apache/apisix-dashboard#2147]
### Issue description

我们拥有独立的认证中心(使用keycloak)，创建应用时，无法使用keycloak 认证。

### Expected behavior

希望应用可以使用keycloak进行认证

### How to Reproduce

打开网址"http://xxxxx/consumer/list"
点击 '创建'
输入"demo"
点击“下一步”
选择“authz-keycloak”，输入authz-keycloak配置内容后保存
5.点击下一步，提示“请启用一种身份认证类插件”，无法进入下一步

### Screenshots

![apisixkeycloak](https://user-images.githubusercontent.com/439390/134650696-00e27bd5-cf0e-448a-be1b-187c1419cd8b.png)

**Comment by bzp2010** [comment]
authz: authorization

**Comment by liuxiran** [comment]
hi @geffzhang actually the pop-up message is not very friendly. `consumer` in APISIX should be used with one of ` basic-auth` `key-auth` `hmac-auth` and `jwt-auth`. you can refer 
https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/consumer.md
for details. 

and when you want to enable `authz-keycloak` , you can enable it with route or related services

**Comment by Baoyuantop** [comment]
If there is still a problem, please open it again.
