### ISSUE TITLE
bug: manager-api services can't stop

### ISSUE THREAD

**Issue by zaunist** [apache/apisix-dashboard#2161]
### Issue description

I compiled manager-api from the documentation and then ran `sudo./manager-api start`. So far everything is fine, but when I tried to stop manager-API I failed, I ran `sudo./manager-api stop` and got no response. I then use `kill` to kill the corresponding process, but the system will automatically create a manager-API process.

### Expected behavior

apisix-dashboard is disabled properly

### How to Reproduce

Occasionally

### Screenshots

<img width="706" alt="image" src="https://user-images.githubusercontent.com/38528079/136652942-2a997e6a-10cb-469b-82bb-282b209da751.png">

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):Darwin kusaka.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.9.1
- etcd version, if have (cmd: run `etcd --version`):etcd Version: 3.5.0
- apisix-dashboard version, if have:2.9.0
- Browser version, if have:

**Comment by bzp2010** [comment]
@zaunist Attempt was made to execute the Manager API remove command.

**Comment by zaunist** [comment]
Solve it,thanks

**Comment by Baoyuantop** [comment]
Hi @bzp2010 , I ran into a similar problem, but `failed to get manager-api pid: open /tmp/manager-api.pid: no such file or directory`, I checked that there is no such file.

**Comment by bzp2010** [comment]
@Baoyuantop You need to use the `ps` command to view the PID of the program and stop it.

**Comment by Baoyuantop** [comment]
I was running on macOS and finally I used `launchctl unload /Library/LaunchDaemons/apisix-dashboard.plist` to solve.
