### ISSUE TITLE
HTTP server write timeout value too small 

### ISSUE THREAD

**Issue by nic-6443** [apache/apisix-dashboard#2165]
### Issue description

When the Dashboard is deployed on a server with limited network bandwidth, the `HTTP server write timeout`([code](https://github.com/apache/apisix-dashboard/blob/f50779a3134da0f97114fb54313e1c77ae042b65/api/internal/core/server/http.go#L54-L54)) value is too small, resulting in a timeout when downloading js files, Chrome reports `ERR_CONTENT_LENGTH_MISMATCH` error, and the page continues to be in the loading state. 
![image](https://user-images.githubusercontent.com/22141303/136752086-f401791d-0265-4b37-8bc0-6c0d78c86d2b.png)
![image](https://user-images.githubusercontent.com/22141303/136753201-18e1744c-9098-427c-94f8-78397b1f3d90.png)
![image](https://user-images.githubusercontent.com/22141303/136971567-740e5a6d-9c74-4edf-8728-1e51ed8db82d.png)
![image](https://user-images.githubusercontent.com/22141303/136971806-cbfedc29-9088-41fe-9e68-28f9339c848a.png)

### Expected behavior

The page can be displayed normally in a network-restricted environment

### How to Reproduce

1. Deploy dashboard on servers with low bandwidth(You can use linux tc to simulate low bandwidth scenarios)

**Comment by CGerAJ** [comment]
me too
