### ISSUE TITLE
route.vars support "!" operator

### ISSUE THREAD

**Issue by yangxikun** [apache/apisix-dashboard#2166]
https://github.com/api7/lua-resty-expr#operator-list

I suggest add a checkbox to support the "!" operator.

**Comment by starsz** [comment]
![image](https://user-images.githubusercontent.com/25628854/137830535-454310aa-e2d1-46e4-8449-0aefacf427c9.png)
Do you mean this ?
APISIX-Dashboard had supported "!" already.

**Comment by starsz** [comment]
cc @LiteSun Please check about it.

**Comment by SkyeYoung** [comment]
I browsed through https://github.com/api7/lua-resty-expr/blob/main/t/v1/not.t, looks like the "!" operator is used in combination with other operators.

Maybe a single checkbox is a better choice.

**Comment by LiteSun** [comment]
@SkyeYoung hi, would you like to improve this 😊

**Comment by SkyeYoung** [comment]
@LiteSun Yes, I'd like to try.

**Comment by LiteSun** [comment]
Great! @SkyeYoung  if you have any problems, feel free to comment here. also, cc @guoqqqi  to watch this.

**Comment by zaunist** [comment]
> @LiteSun Yes, I'd like to try.

Great !
