### ISSUE TITLE
"Create Route" form optimization

### ISSUE THREAD

**Issue by nic-6443** [apache/apisix-dashboard#2167]
# Feature request
"Create Route" -> "Define API Backend Server" -> "Select Upstream" can automatically select the "None" option according to whether service is configured in the previous form "Define API Request" -> "Service"

## Please describe your feature
When I select a defined service in the form below: 
![image](https://user-images.githubusercontent.com/22141303/136775242-1f761e8a-abc8-40aa-9618-671087a4bde6.png)
When entering the second form, it let me customize the upstream by default, which makes me very confused whether the service configuration in the previous form is useful.
![image](https://user-images.githubusercontent.com/22141303/136775710-84cb28a2-2eab-43e5-b74e-a367cf018875.png)
So I think the second form can automatically select the **None** option according to whether the service is configured in the first form.
![image](https://user-images.githubusercontent.com/22141303/136776241-71a5372a-8dae-44f1-a244-b01eb1aac425.png)
Of course, we can give some tips on the page to tell users that they can actively choose the **Custom** option.

**Comment by oil-oil** [comment]
Please assign me and I will implement this function.😃

**Comment by starsz** [comment]
> Please assign me and I will implement this function.😃

Nice!
