### ISSUE TITLE
bug: apisix dashoard 2.9版本需要重复登录才能进入UI界面 

### ISSUE THREAD

**Issue by eno16777736** [apache/apisix-dashboard#2174]
### Issue description

apisix dashoard 2.9版本登录时第一次输入密码登录以后显示密码正确，然后再跳转到登录界面，再次输入密码以后才能正常进入UI

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

登录就能发现

### Actual result

反复登录才能进入

### Error log

无

**Comment by zaunist** [comment]
I also found that if the account was logged in from somewhere else, the login interface would return "User has logged in elsewhere" the first time, and the login would only be successful if requested again. Is this login logic appropriate? @bzp2010

**Comment by zaunist** [comment]
![image](https://user-images.githubusercontent.com/38528079/137321571-0158a99f-508a-4721-aed7-11e6761fd429.png)

**Comment by bzp2010** [comment]
Hi, @eno16777736. Are you logging in for the first time? (have you logged in before and dropped out after timeout)

**Comment by bzp2010** [comment]
@zaunist It seems that the error of error code `20006` does not come from the `apache/apisix-dashboard` project. I didn't find it after searching in the code.

**Comment by juzhiyuan** [comment]
@zaunist Please check your project 🤔 This error code is not from Apache APISIX Dashboard.

**Comment by eno16777736** [comment]
首次登陆是可以的，之后等cookie失效后就需要重复登陆两次才可以正常进入

**Comment by eno16777736** [comment]
很明显是dashborad的登录接口的代码逻辑有问题
