### ISSUE TITLE
failed to write pid: Instance of Manager API maybe running with a pid

### ISSUE THREAD

**Issue by astraylinux** [apache/apisix-dashboard#2180]
### Issue description

I'm installed and run ApiSix Dashboard yesterday，The process exited this morning.  Even if I add the `-f` flag, I can't start ther manager-api anymore .

Error: 
```
2021-10-21T09:39:56.055+0800	ERROR	server/server.go:109	failed to write pid: Instance of Manager API maybe running with a pid 10204. If not, please run Manager API with '-f' or '--force' flag

2021-10-21T09:39:56.055+0800	ERROR	cmd/root.go:100	The Manager API server start failed: Instance of Manager API maybe running with a pid 10204. If not, please run Manager API with '-f' or '--force' flag
```

### Expected behavior

 start manager-api server

### How to Reproduce

start manager-api, no exit normally

### Screenshots

![image](https://user-images.githubusercontent.com/4121264/138196537-148136bd-e9f0-4011-ab73-9be8eb6c34b1.png)

### Environment

- apisix version (cmd: `apisix version`):  2.10.0
- OS (cmd: `uname -a`): centos 7.4.1708
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.9.1
- etcd version, if have (cmd: run `etcd --version`): 3.5.1
- apisix-dashboard version, if have: 2.8.0
- Browser version, if have:  Chrome 80.0

**Comment by bzp2010** [comment]
@astraylinux Please check `/tmp/manager-api.pid` exist.

**Comment by astraylinux** [comment]
> @astraylinux Please check `/tmp/manager-api.pid` exist.

It exist, I delete it then `manager-api` can start. Thank you. So the `-f` flag not work, It's bug?

**Comment by bzp2010** [comment]
> > @astraylinux Please check `/tmp/manager-api.pid` exist.
> 
> It exist, I delete it then `manager-api` can start. Thank you. So the `-f` flag not work, It's bug?

@astraylinux Thank you for pointing out the problem. It looks like a mistake and will be fixed as much as possible.

Currently, consideration is being given to removing the built-in service management from the Manager API and using `systemd` or docker containers to manage its life cycle.

**Comment by astraylinux** [comment]
> > > @astraylinux Please check `/tmp/manager-api.pid` exist.
> > 
> > 
> > It exist, I delete it then `manager-api` can start. Thank you. So the `-f` flag not work, It's bug?
> 
> @astraylinux Thank you for pointing out the problem. It looks like a mistake and will be fixed as much as possible.
> 
> Currently, consideration is being given to removing the built-in service management from the Manager API and using `systemd` or docker containers to manage its life cycle.

Ok, thank you very much!
