### ISSUE TITLE
IP输入框的宽度不够，无法显示完整信息

### ISSUE THREAD

**Issue by sofire** [apache/apisix-dashboard#2181]
### Issue description

在mac 13寸笔记本上，IP 输入框 不够宽，无法完全显示信息
尤其是在输入框 被禁用后，无法看到完整信息，不知道输入的啥了。

### Expected behavior

希望能增加 最小宽度 ，能完全显示

### How to Reproduce

无

### Screenshots

![4BDFCAD9D6AA4A94DE3F264E16F61FEF](https://user-images.githubusercontent.com/1177330/138384632-4d521147-1147-49b7-8cd4-ed4208d3c0c8.jpg)

### Environment

版本 2.9.0

**Comment by juzhiyuan** [comment]
@Ylikj Hi, would you help to fix this issue?

**Comment by juzhiyuan** [comment]
fixed
