### ISSUE TITLE
can't find proxy-rewrite plugin

### ISSUE THREAD

**Issue by hozaifaaoud** [apache/apisix-dashboard#2188]
### Issue description

Hi,
I am using apisix dashboard to configure route and need to use proxy-rewrite plugin and can't find it on the plugins on the dashboard
could you please help me to use it?
thanks in advance

### Expected behavior

 proxy-rewrite 

### How to Reproduce

//

### Environment

- apisix version (cmd: `apisix version`):2.5
- OS (cmd: `uname -a`): 144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.9.1
- etcd version, if have (cmd: run `etcd --version`): 3.4.0
- apisix-dashboard version, if have: 2.9.0
- Browser version, if have:

**Comment by juzhiyuan** [comment]
Hi, which version of the dashboard are you using? This plugin has a UI form here.

![image](https://user-images.githubusercontent.com/2106987/139520555-f049fda0-8674-46da-9c7b-9d9630ab3317.png)

**Comment by bzp2010** [comment]
ping @hozaifaaoud

**Comment by zerda** [comment]
This issue is same as https://github.com/apache/apisix-dashboard/issues/2363. 

It makes me a little confused that all other plugins list in route plugin config page except proxy-rewrite. Especially as a new user, when I taking tour with [Getting Started](https://apisix.apache.org/zh/docs/apisix/getting-started#%E4%B8%BA%E8%B7%AF%E7%94%B1%E6%B7%BB%E5%8A%A0%E5%89%8D%E7%BC%80).

**Comment by juzhiyuan** [comment]
> It makes me a little confused that all other plugins list in route plugin config page except proxy-rewrite.

Initially, we wanted to productize the commonly used plugins, so the plugin was directly implemented on the first step page. I will tag a label to track.

**Comment by dbit-xia** [comment]
> > It makes me a little confused that all other plugins list in route plugin config page except proxy-rewrite.
> 
> Initially, we wanted to productize the commonly used plugins, so the plugin was directly implemented on the first step page. I will tag a label to track.

Is there any progress?

**Comment by juzhiyuan** [comment]
No plan yet.
