### ISSUE TITLE
support protobuf on Web

### ISSUE THREAD

**Issue by lwba21190** [apache/apisix-dashboard#2189]
# Feature request

## Please describe your feature

A clear and concise description of what you want and what your use case is.

**Comment by juzhiyuan** [comment]
Please update your issue's description, a clear description could help us better understand your question :)

**Comment by lwba21190** [comment]
好的，多谢。我的目的是想用apisix做网关，将终端的http请求转成grpc到微服务(go)，用的协议文件是protobuf。但是dashboard上面没有看到可以设置proto相关的地方，那grpc transcode插件怎么找到proto的内容呢？

**Comment by bzp2010** [comment]
Hi, @lwba21190.
In the master branch of the dashboard, we already support the administration API of protobuf. but the front-end administration panel still hasn't started and we lack the manpower.
If you are able to support the development of the front-end interface, we are more than welcome to send a PR.

**Comment by lwba21190** [comment]
好吧，多谢

**Comment by guoqqqi** [comment]
Hi, @bzp2010 Is there a more detailed description of this function, I would like to know what needs to be done on the front end 😄

**Comment by bzp2010** [comment]
@guoqqqi What needs to be done here is no different from supporting other resources, providing pages for listing, creating, changing, and deleting. It's like supporting `route` or `consumer`.

**Comment by oil-oil** [comment]
please assign this issue to me, I would like to contribute this feature 😃.
