### ISSUE TITLE
Feature request: Refactor e2e to e2enew

### ISSUE THREAD

**Issue by zaunist** [apache/apisix-dashboard#2190]
# Feature request

## Please describe your feature

Currently, there are two sets of E2E in Apache APISIX Dashboard, we should be able to migrate the test cases from e2e to e2enew, so that we only need to store E2E in one directory, making the directory structure more reasonable and clear.

## Describe the solution you'd like

Refactor the code in the e2e directory and merge it into the e2enew directory.

**Comment by bzp2010** [comment]
+1
We should also comb through the test cases in the e2enew folder to make it more organized.

**Comment by zaunist** [comment]
> +1 We should also comb through the test cases in the e2enew folder to make it more organized.

I'm going to do this, but I have a question whether to submit all the use cases in one PR or split them into multiple PR's.

**Comment by zaunist** [comment]
Repeated https://github.com/apache/apisix-dashboard/issues/2197
