### ISSUE TITLE
CodeMirror is broken when viewing data

### ISSUE THREAD

**Issue by tomzhou1213** [apache/apisix-dashboard#2191]
### Issue description

路由、上游、服务等所有查看数据的地方都出现这个问题

### Expected behavior

正常显示数据

### How to Reproduce

无

### Screenshots

![image](https://user-images.githubusercontent.com/8078418/139579018-7fea100b-1cc1-4747-acf6-19096c08e315.png)

### Environment

- apisix version 2.9.0
- OS : cncentOS 7
- OpenResty version :  1.19.9.1
- etcd version: 3.4.7
- apisix-dashboard version: 2.9.0
- Browser version: Google Chrome   69.0.3497.92（正式版本） （32 位）

**Comment by guoqqqi** [comment]
@barchielAbyss Do you have time to help check this issue?

**Comment by mLiGuangYuan** [comment]
> @barchielAbyss Do you have time to help check this issue?

yep，I'm checking it

**Comment by barchielAbyss** [comment]
@tomzhou1213 

hi, Could you please tell me how you installed Google Chrome 69.0.3497.92? I want to simulate your environment accurately, but I found that this problem cannot be see in the later version of 89.x

**Comment by barchielAbyss** [comment]
> @tomzhou1213
> 
> hi, Could you please tell me how you installed Google Chrome 69.0.3497.92? I want to simulate your environment accurately, but I found that this problem cannot be see in the later version of 89.x

I've used a lot of search engines, and they all point to the wrong download address

**Comment by barchielAbyss** [comment]
I find download's in [here](https://www.chromedownloads.net/)

> > @tomzhou1213
> > hi, Could you please tell me how you installed Google Chrome 69.0.3497.92? I want to simulate your environment accurately, but I found that this problem cannot be see in the later version of 89.x
> 
> I've used a lot of search engines, and they all point to the wrong download address

**Comment by SkyeYoung** [comment]
I think we have removed the code mirror, which should no longer be a problem.

**Comment by Baoyuantop** [comment]
If there is still a problem, please open it again.
