### ISSUE TITLE
Dashboard  upstream does not display the priority field, and the priority setting will be lost when click the commit button

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix-dashboard#2192]
APISIX的路由是支持通过设置priority来满足不同的转发优先级的，但是这个特性并没有在dashboard上开放设置入口，因此我们是通过admin api 来设置的。当通过admin api 设置好priority之后，在dashboard的上游查看界面中，却不显示priority字段，一旦在这个界面点击提交，priority字段设置会丢失，导致既定优先级失效，可能引发不必要的现网故障。

Admin Api 设置的upstream：
![image](https://user-images.githubusercontent.com/9711651/139622038-1e39170c-941a-4599-9ba8-3afda92c2d3f.png)

在dashboard 的upstream view中显示如图：
![image](https://user-images.githubusercontent.com/9711651/139622552-067e14be-0484-4896-9239-ce8a395f697d.png)

一旦在这个界面点击了提交，这个字段将会被删除。

这里推荐2个解决方案：
1、dashboard支持下priority设置特性；
2、dashboard暂时不能支持的功能特性，建议优先采用合并逻辑，而不是覆写，至少不要冲掉已存在的元数据（推荐）

**Comment by bzp2010** [comment]
@jagerzhang Here was determined to be a difference between APISIX and Dashboard, which is a bug. It takes a while to fix.
