### ISSUE TITLE
Should apisix support environment config or profile config?

### ISSUE THREAD

**Issue by gy09535** [apache/apisix-dashboard#2194]
# Feature request
For example  I want to change etcd  ip address and  apisix  prefix for different environment, according to https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L39, how can I do it?
## Please describe your feature

A clear and concise description of what you want and what your use case is.

**Comment by bzp2010** [comment]
@gy09535 You can specify a different profile with `-c`.

**Comment by Engine-AI** [comment]
Hi！@gy09535 ,I have used a stupid way ，You can create the corresponding "conf.yaml" configuration file according to your environment and modify the startup mode in the makefile. like this.
![image](https://user-images.githubusercontent.com/17827327/139778453-8fbb7282-ba43-4ad9-b22b-4265d1464496.png)
![image](https://user-images.githubusercontent.com/17827327/139778466-18e20092-5164-49d2-bcbc-5cec63c87322.png)
![image](https://user-images.githubusercontent.com/17827327/139778490-10a7e55f-0626-4dfb-b8f7-64657aa3c24a.png)

**Comment by gy09535** [comment]
> Hi！@gy09535 ,I have used a stupid way ，You can create the corresponding "conf.yaml" configuration file according to your environment and modify the startup mode in the makefile. like this. ![image](https://user-images.githubusercontent.com/17827327/139778453-8fbb7282-ba43-4ad9-b22b-4265d1464496.png) ![image](https://user-images.githubusercontent.com/17827327/139778466-18e20092-5164-49d2-bcbc-5cec63c87322.png) ![image](https://user-images.githubusercontent.com/17827327/139778490-10a7e55f-0626-4dfb-b8f7-64657aa3c24a.png)

got it, thanks for you help 👍.

**Comment by gy09535** [comment]
> @gy09535 You can specify a different profile with `-c`.
BTW, Are you trying to overwrite the contents of the configuration file via environment variables?

En....., yeah I use it in publish platform, for different environment, I want use one docker image, and change the config with different environment variables, like this![image](https://user-images.githubusercontent.com/15153469/139802289-c526c2c9-555b-4153-890b-1d914d270657.png)> 
>

**Comment by bzp2010** [comment]
> En....., yeah I use it in publish platform, for different environment, I want use one docker image, and change the config with different environment variables, like this

@gy09535 Later I will try to update the Dockerfile of the docker image to open up the `CMD` to help overwrite the config file path, so that I can combine volume and cmd to dynamically select the config file.

**Comment by kevinw66** [comment]
I suggest we can use environment variable APISIX_PROFILE just like apisix do
https://apisix.apache.org/docs/apisix/profile/
