### ISSUE TITLE
dos format shell

### ISSUE THREAD

**Issue by Marno-o** [apache/apisix-dashboard#2205]
### Issue description

I want to build image locally ,but found this error:
```shell
/usr/bin/env: 'bash\r': No such file or directory
```
It's caused by this build script: `api/build.sh`.

This build script was wrote in format dos , it contains `\r` so cannot be read by linux.

### Expected behavior

please check and fix

### How to Reproduce

docker build -t apisix-dashboard:test .

### Environment

- OS (cmd: `uname -a`): CentOS 7
- apisix-dashboard version, if have: 2.9.0

**Comment by Applenice** [comment]
@juzhiyuan I am trying to reproduce it but without success, the end-of-line character of the clone code is LF.
![image](https://user-images.githubusercontent.com/30207614/142018882-577016cd-d14d-4683-8d56-f70ca0f097d6.png)

@Marno-o Have you ever manipulated this file on Windows? For example, I wrote the t.sh file on Windows, the end-of-line character is CRLF:
![image](https://user-images.githubusercontent.com/30207614/142019396-1a281d12-df38-4b30-8f46-e2974ca7cab8.png)

```shell
$ cat t.sh 
#!/usr/bin/env bash
echo test
$ chmod +x t.sh 
$ ./t.sh 
/usr/bin/env: ‘bash\r’: No such file or directory
```

**Comment by zaunist** [comment]
Yeah, maybe some one edit this file in Windos. And there is a tool `dos2unix` can fix this issue.

**Comment by Marno-o** [comment]
I tried to reproduce this problem but not work again:
For some reason ,i must clone on Windows OS first, then upload to my server.
I did not edit this file by any other tools before this problem happened.

So i think maybe this is caused by the FTP tool.
Is a mistake, so sorry fro this disturb,
