### ISSUE TITLE
request help: Ask how to configure the undefined domain name to point to a service

### ISSUE THREAD

**Issue by junmaqiang** [apache/apisix-dashboard#2217]
### Issue description

以前我在Nginx的时候是这样配置的
I used to configure it like this when I was in Nginx

```
server {
    # 防止处理未定义主机名的请求
    # 请注意，default_server 是 listen port 的属性，而不是 server_name 的。
    listen       80 default_server; # 显式设置默认虚拟主机
    listen       [::]:80 default_server;
    server_name  _; # 隐式设置默认虚拟主机，无关域名访问会被此处接收
    server_name  ""; # 请求中没有“Host”头字段的请求，会被此处接收
    return       444; # 返回码444，它可以用来关闭连接
}
```

现在用 Apisix，我要如何定义呢？
Now using Apisix, how do I define it?

我的目的是：让路由没有匹配到的统一都指向到一个地方
My purpose：Let the unity that the route does not match point to one place

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`):Mac
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.5
- apisix-dashboard version, if have: 2.10.1
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
```nginx
server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _; 
    server_name  "";
    return       444;
}
```

For `listen 80`, you need to update APISIX's configuration, see https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L25

For `server_name _`, I'm not sure if you mean `all requests which are not targeted to a specified Routes would return 444`? I need to ask help from @bzp2010.

**Comment by bzp2010** [comment]
If you want to set up a route for handling unmatched requests, set up a low-priority route that does not contain request information matches, for which you can perform custom actions using the plugin.

**Comment by bzp2010** [comment]
I will close this issue temporarily, but you can always open it again if you need to.
