### ISSUE TITLE
Add sub_path support when dashboard under a subdirectory via nginx reverse proxy.

### ISSUE THREAD

**Issue by ltt1987** [apache/apisix-dashboard#2219]
# Feature request

当前如需反向代理到apisix dashboard，只能进行根目录的代理，如果指定 http://host/dashboard/ 的二级目录进行代理，代理后dashboard 中的静态资源路径、请求的api接口路径，均为根路径（src="/favicon.png"）的引用，期望的地址应该是二级目录（src="/dashboard/favicon.png"）地址。

Currently, if you need to reverse proxy to apisix-dashboard, Only support the root directory proxy.

If you set apisix-dashboard under a subdirectory via nginx reverse proxy like http://ip/dashboard/<api-dashboard>, you will get some errors due to the wrong resource path. E.g: `src="/favicon.png"` is wrong, `src="/dashboard/favicon.png"` is correct.

## Describe the solution you'd like

建议增加可指定子路径的功能，类似pgAdmin中，通过增加添加自定义Header X-Script-Name 来指定目录。

It is recommended to add the function of specifying sub-path, For example, in pgAdmin, specify the directory by adding a custom Header X-Script-Name.

## Additional context

> pgAdmin Document：If you wish to host pgAdmin under a subdirectory rather than on the root of the server, you must specify the location and set the X-Script-Name header which tells the pgAdmin container how to rewrite paths:

```
server {
    listen 80;
    server_name _;

    location /pgadmin4/ {
        proxy_set_header X-Script-Name /pgadmin4;
        proxy_set_header Host $host;
        proxy_pass http://localhost:5050/;
        proxy_redirect off;
    }
}
```

**Comment by juzhiyuan** [comment]
Not sure if it's supported with Apache APISIX 🤔 @tzssangglass could you please have a check?

**Comment by juzhiyuan** [comment]
BTW, @ltt1987 I recommend using English here 😄 For we have many contributors and users who speak English and other languages 😄

**Comment by ltt1987** [comment]
> BTW, @ltt1987 I recommend using English here 😄 For we have many contributors and users who speak English and other languages 😄

Sorry for that, I'm not good at english. I have added English content, but I still keep Chinese in order to avoid wrong description.

**Comment by juzhiyuan** [comment]
got it, @bzp2010 would you please take a look?

**Comment by tzssangglass** [comment]
we cau use `proxy-rewrite` plugins to do this, refer to:https://github.com/apache/apisix/issues/3252

**Comment by adoal** [comment]
> we cau use `proxy-rewrite` plugins to do this, refer to:[apache/apisix#3252](https://github.com/apache/apisix/issues/3252)

I don't think `proxy-rewrite` helps, since it only strips the prefix then sends to the backend server, but we also need some mechanism to tell the backend so it will 'know' it should generate anchor URLs under some prefix. Just like `SCRIPT_NAME` and `PATH_INFO` in traditional CGI spec.

**Comment by tzssangglass** [comment]
> since it only strips the prefix then sends to the backend server

APISIX does not modify the url by default.

**Comment by bzp2010** [comment]
Hi, @ltt1987.

I think the problem is that the compilation product of our dashboard project currently uses absolute paths to load resources, so you need to recompile if you want to proxy dashboard in a subdirectory. These are not directly supported by either the Manager API or the `proxy-rewrite` plugin in APISIX.

Of course, we can take some measures to improve it, if you are willing to try.

Here are the configures about it.
[https://github.com/apache/apisix-dashboard/blob/d7b772235f1a13660541e6f52c4844a3bb7929f6/web/config/config.ts#L48-L49](https://github.com/apache/apisix-dashboard/blob/d7b772235f1a13660541e6f52c4844a3bb7929f6/web/config/config.ts#L48-L49)

**Comment by juzhiyuan** [comment]
see https://pro.ant.design/zh-CN/config/config#publicpath

**Comment by ltt1987** [comment]
> Hi, @ltt1987.
> 
> I think the problem is that the compilation product of our dashboard project currently uses absolute paths to load resources, so you need to recompile if you want to proxy dashboard in a subdirectory. These are not directly supported by either the Manager API or the `proxy-rewrite` plugin in APISIX.
> 
> Of course, we can take some measures to improve it, if you are willing to try.
> 
> Here are the configures about it.
> 
> https://github.com/apache/apisix-dashboard/blob/d7b772235f1a13660541e6f52c4844a3bb7929f6/web/config/config.ts#L48-L49

Got it! Thanks!
