### ISSUE TITLE
support Request Loading status

### ISSUE THREAD

**Issue by gy09535** [apache/apisix-dashboard#2222]
### Issue description

Delete route in apisix dashboard is not work.
![image](https://user-images.githubusercontent.com/15153469/143182074-42523a52-7156-4e52-bd3d-259d8d168129.png)

once deleted is dose not work, but twice I got this error.

### Expected behavior

When I delete the route, the list of this route should not be in the list.

### How to Reproduce

just start the dashboard and delete the route.

### Environment

- apisix version (cmd: `apisix version`):2.5
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by gy09535** [comment]
when I restart the dashboard, the route is disappear.Now I am wary about it will show again.

**Comment by gy09535** [comment]
> @gy09535 It seems that you click twice DELETE button, and the first one runs successfully, and then the second request failed.
> 
> This is more like a UX issue, you could set a loading status when Request sent, would like to improve it?

@juzhiyuan It seems the api issue, I restart the dashboard service it can work rather then restart the browser.

**Comment by juzhiyuan** [comment]
ya, it's due to the network issue or API responses too late :) anyway, if UX could handle this case, you will know exactly what happened.

**Comment by CP3cham** [comment]
> > @gy09535 It seems that you click twice DELETE button, and the first one runs successfully, and then the second request failed.
> > This is more like a UX issue, you could set a loading status when Request sent, would like to improve it?
> 
> @juzhiyuan It seems the api issue, I restart the dashboard service it can work rather then the browser.

Could you give  concrete steps.I can't reproduce.Actually,the logic of the code is:after deleting successfully,the page will reload automatically.Maybe the problem caused by Internet?

**Comment by juzhiyuan** [comment]
@CP3cham You could have a try by using Lower network mode 😄 @gy09535 means if Client's network is slow, and click multiple times, then this error happened.

**Comment by CP3cham** [comment]
I will try to check and fix it
