### ISSUE TITLE
The `禁用` button on the plugin list page has ambiguity issues

### ISSUE THREAD

**Issue by jie123108** [apache/apisix-dashboard#2245]
### Issue description

I recently used the `apisix-dashboard` in my project, on the plugins list page, for a plugin that had been enabled. 
It may not be appropriate to call it `禁用` here, right?   It would be more appropriate to name it "编辑”.

`禁用` gives the impression that when you click it, the plugin will be disabled. But in fact it is edited (including the disable function)

For those who are familiar with this feature, it may not be a problem. But a newcomer, seeing this `禁用` button for the first time, especially in a production environment, should be afraid to click it.

### Expected behavior

Maybe a new `配置/编辑（Configure）` button should be used. The `禁用` button function becomes really disabled.

### How to Reproduce

dashboard all plugin pages

**Comment by juzhiyuan** [comment]
Discussion could be found here. https://lists.apache.org/thread/z91bmlvstrj6hs8cmz0496tmd1orjmxc

**Comment by zaunist** [comment]
Hi, @juzhiyuan . Maybe I can contribute to this issue.

**Comment by juzhiyuan** [comment]
😄 Then you could submit your PRs, welcome!
