### ISSUE TITLE
[openapi upload error] kin-openapi lastest version is 0.86.0, and our go.mod version is 0.32.0

### ISSUE THREAD

**Issue by nimohunter** [apache/apisix-dashboard#2246]
# Feature request

## Please describe your feature

OpenAPI upload openAPI yaml return error about ref error .

> Request Error Code: 10000 failed to resolve "#/definitions/dto.EnvironmentReq" in fragment in URI: "definitions": struct field "definitions" not found

## Describe the solution you'd like

i'd like to solve it with MR by update kin-openapi version to lastest and this can solve the problem.

**Comment by nimohunter** [comment]
and i find this import file must use the file which is export before, it can not import swagger json generate by [swaggo](https://github.com/swaggo/swag) 

and the  reason is swagger json generate by swaggo path doesn't have operationId, so can i move the  swagger json path summary as operationId?

**Comment by juzhiyuan** [comment]
> so can i move the swagger json path summary as operationId?

Actually, I'm not very sure about this, may need @nic-chen's help to have a check.

**Comment by nimohunter** [comment]
> > so can i move the swagger json path summary as operationId?
> 
> Actually, I'm not very sure about this, may need @nic-chen's help to have a check.

thanks! and if we move swagger path summary as operationid, then we can import the swagger json generate by swaggo.  
Of course that we may miss some route's parameter.

**Comment by juzhiyuan** [comment]
> Of course that we may miss some route's parameter.

And we could make sure all parameters that Apache APISIX needs are kept? 😄

**Comment by nic-chen** [comment]
LGTM

**Comment by nimohunter** [comment]
> > Of course that we may miss some route's parameter.
> 
> And we could make sure all parameters that Apache APISIX needs are kept? 😄

I found the swagger.yaml generated from swaggo miss some parameters. for example, swagger file doesn't contain the upstream info. I have no ideal about this critical info missing. 

maybe our dashboard can not support the swagger json which is generated. sad. :(

**Comment by juzhiyuan** [comment]
> 

Hi @nimohunter, could we schedule a meeting if possible? My WeChat is **JuShaoyao**

**Comment by nimohunter** [comment]
oh, 

> > > Of course that we may miss some route's parameter.
> > 
> > 
> > And we could make sure all parameters that Apache APISIX needs are kept? 😄
> 
> I found the swagger.yaml generated from swaggo miss some parameters. for example, swagger file doesn't contain the upstream info. I have no ideal about this critical info missing.
> 
> maybe our dashboard can not support the swagger json which is generated. sad. :(

sorry about my fault, this problem can be solved by select a service.  we can select one service when import the swagger file.

**Comment by juzhiyuan** [comment]
🥰🥰

**Comment by nimohunter** [comment]
i can join about the new version dashboard, so this feature will delay to next version start develop.
