### ISSUE TITLE
docs: invalid URL when clone repo

### ISSUE THREAD

**Issue by Carson-T** [apache/apisix-dashboard#2256]
### Issue description

wrong command

### Expected behavior

The install.md file has a wrong command

git clone -b release/2.10.0 https://github.com/apache/apisix-dashboard.git && cd apisix-dashboard

there is no branch release/2.10.0

### How to Reproduce

What I found in this repository is release/2.10

**Comment by zaunist** [comment]
Hi, @Carson-T . I have submitted a PR to  fix this issue, please wait for merge to release branch.

**Comment by juzhiyuan** [comment]
Hi @Carson-T, @zaunist has fixed the issue by https://github.com/apache/apisix-dashboard/pull/2257/files

**Comment by Carson-T** [comment]
Thank you!!! @zaunist @juzhiyuan
