### ISSUE TITLE
Apisix dashboard service's health check does not take effect  

### ISSUE THREAD

**Issue by vickychen2022** [apache/apisix-dashboard#2262]
### Issue description

I create a service in dashboard, and enable the health check, but it does not take effect. But If I enable health check in an upstream , the health check in upstream is ok.  My question is why health check in upstream is ok while service not ok ?

### Expected behavior

The health check enabled in service should work, but it does not . 

### How to Reproduce

1. Create a get interface in a project which will be used for health check
2. Create a new service in dashboard
3. Enable active health check through http request and input the url created in step 1
4. Then post a request to the url by postman, you should see the request is received by the backend system, but the health check not triggered

### Screenshots

[service health check issue.docx](https://github.com/apache/apisix-dashboard/files/7767987/service.health.check.issue.docx)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by juzhiyuan** [comment]
cc @Baoyuantop to have a check, thanks!

**Comment by Baoyuantop** [comment]
Hi @vickychen2022, thank you for reporting the bug! I would like to confirm if you have used the [Admin API](https://apisix.apache.org/docs/apisix/admin-api/) to create resources, and if you use the Admin API to create these resources would you have the same problem?

**Comment by vickychen2022** [comment]
Hi @Baoyuantop , sorry for late reply!  I haven't used admin api to create resources, I created the upstream and service by dashboard. Actually the bug is easy to reproduce: select "custom" in Select upstream and select “node" in upstream type, the health check configuration controls will be enabled to edit, and choose to turn on active health check, and you will find the issue occur. i haven't tried to create resource through admin api yet. will try later and update the result here

**Comment by Baoyuantop** [comment]
OK, I'll try to reproduce it locally and look forward to your results after using the Admin API.

**Comment by guoqqqi** [comment]
Hi @Si-ege, please check this issues

**Comment by Baoyuantop** [comment]
If there is still a problem, please open it again.
