### ISSUE TITLE
Docker Hub have not push the latest version yet

### ISSUE THREAD

**Issue by lemonrains** [apache/apisix-dashboard#2264]
# Feature request

Docker Hub have not push the latest version yet .

## Describe the solution you'd like

Recent version 2.10 and 2.10.1 was not push to the docker hub.
https://hub.docker.com/r/apache/apisix-dashboard/tags

**Comment by zaunist** [comment]
cc @bzp2010 @juzhiyuan

**Comment by juzhiyuan** [comment]
**Update**

The Docker image is building and will be published soon.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/147382696-3dabf661-daf4-4e3f-8959-c7e56d06d486.png)

Done, see https://hub.docker.com/r/apache/apisix-dashboard/tags

**Comment by lemonrains** [comment]
@juzhiyuan Thanks for the quick response

**Comment by juzhiyuan** [comment]
You're welcome :)
