### ISSUE TITLE
setup.sh not support grpc_server_example

### ISSUE THREAD

**Issue by zaunist** [apache/apisix-dashboard#2265]
### Issue description

I have execute `/apisix-dashboard/api/test/docker/setup.sh`, then get an error

![image](https://user-images.githubusercontent.com/38528079/147390006-d9998fed-ba4b-46be-b94b-fbe71d66a0f2.png)

So we need to add grpc_server_example to this shell script, and I'm glad to fix it.

### Expected behavior

will execute setup.sh normally.

### How to Reproduce

1. clone the dashboard repo
2. change to `api/test/docker` path
3. run `bash setup.sh up`

### Screenshots

![image](https://user-images.githubusercontent.com/38528079/147390064-c760ee5b-8f33-43fa-98a9-2fc956880d6e.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by juzhiyuan** [comment]
Hi @bzp2010 @nic-chen, could you please have a check on this? do we need that Docker Shell?

**Comment by zaunist** [comment]
Maybe fix by https://github.com/apache/apisix-dashboard/pull/2204

**Comment by zaunist** [comment]
Have supported.
