### ISSUE TITLE
Configure response-rewrite using Apisix Dashboard does not take effect.

### ISSUE THREAD

**Issue by foreveryang321** [apache/apisix-dashboard#2268]
### Issue description

Configure `response-rewrite` using `Apisix Dashboard` does not take effect.

### Expected behavior

the response header is `Server: xx/x`, not `Server: APISIX/2.11.0`

```shell
yl-mac:apisix yl$ curl http://127.0.0.1 -v -H 'User-Agent: baidu-bot'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> Accept: */*
> User-Agent: baidu-bot
> 
< HTTP/1.1 403 Forbidden
< Date: Wed, 29 Dec 2021 01:44:15 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: APISIX/2.11.0
< 
{"message":"Not allowed"}
```

### How to Reproduce

ignore

### Screenshots

> Configure `response-rewrite` using `Apisix Dashboard`

- Routing Mode
![image](https://user-images.githubusercontent.com/5868190/147620128-82a64bb7-1003-4722-96e9-2230ae6271b0.png)

- Global Mode

![image](https://user-images.githubusercontent.com/5868190/147620706-8b6b472f-f3c3-48b3-aa9d-3301366ea621.png)

> apisix/conf/config.yaml

![image](https://user-images.githubusercontent.com/5868190/147620109-5466b8c3-5a4f-463a-a9d7-160aa4e09389.png)

### Environment

- apisix version (cmd: `apisix version`): apache/apisix:2.11.0-alpine
- OS (cmd: `uname -a`): Mac OS X 10.15.7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  
nginx version: openresty/1.19.3.2
built by gcc 9.3.0 (Alpine 9.3.0) 
built with OpenSSL 1.1.1g  21 Apr 2020
- etcd version, if have (cmd: run `etcd --version`): etcd Version: 3.5.0
- apisix-dashboard version, if have: apache/apisix-dashboard:2.10.1-alpine
- Browser version, if have: Chrome/96

**Comment by juzhiyuan** [comment]
cc @Baoyuantop to have a check 🙈

**Comment by zaunist** [comment]
Hi, @foreveryang321. If you want rewrite `header`, you need configure `response-rewrite` like this:
```
     "headers": {
        "Server": "baidu",
      }
```
I can give you a example configuration:
```
{
  "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
  "disable": false,
  "headers": {
    "Server": "baidu",
    "X-Server-id": 3,
    "X-Server-status": "on"
  }
}
```
![image](https://user-images.githubusercontent.com/38528079/147623172-1d548d96-3a7d-459b-9601-745101180262.png)

test response header:
![image](https://user-images.githubusercontent.com/38528079/147623213-1779bc82-0325-4227-9537-addbd458ca83.png)

**Comment by foreveryang321** [comment]
thx!
