### ISSUE TITLE
make api-test fail

### ISSUE THREAD

**Issue by jwrookie** [apache/apisix-dashboard#2281]
### Issue description

exec "make api-test" failed

### Expected behavior

succes

### How to Reproduce

in apisix-dashboard and make api-test

### Screenshots

![image](https://user-images.githubusercontent.com/41732283/148360044-d7818da5-9f2b-4421-b813-238283fc7f02.png)
![image](https://user-images.githubusercontent.com/41732283/148360623-0eb5daf0-5a4e-4b40-8dad-5d4dd254274f.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):Darwin 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

### Additional context

position https://github.com/apache/apisix-dashboard/blob/master/api/internal/handler/data_loader/route_import_test.go#L92

i think use os.Getwd() instead

i am happy to solve it

**Comment by zaunist** [comment]
Hi, @jwrookie . Could you please provide your system version? We need to know why this error occurred...

**Comment by zaunist** [comment]
And I also think os.Getwd() is better, welcome to PR.

**Comment by jwrookie** [comment]
Hi  @zaunist 
os: Darwin Kernel Version 21.1.0

i am also looking for the cause of this error, welcome to discussed

**Comment by zaunist** [comment]
`Darwin Kernel Version 20.6.0`. I can't reproduce this error.

**Comment by jwrookie** [comment]
> `Darwin Kernel Version 20.6.0`. I can't reproduce this error.

thks for you replay, in my os reproduce rate is 100%, we use os.Getwd() instead
