### ISSUE TITLE
APISIX DASHBOARD: how to use regex to strict match uri with both path and query params in a single request

### ISSUE THREAD

**Issue by stutipatelorigo** [apache/apisix-dashboard#2284]
### Issue description

Currently, I want to achieve the single  request matching both uri path params and query params:

For example, to match this request with strict path param match: 
URL: /api/users/{param1}/statements?name={param2}&dept={param3}
WHERE: 
{param1} is uri path param AND {param2} {param3} are query params

I am trying this on apisix dashboard. Can anyone guide me as i am new here and no proper documentation is there.

**Comment by zaunist** [comment]
@bzp2010 Please take a look, I'm not sure about the answer to this issue.

**Comment by bzp2010** [comment]
We don't have any formal way to do this work, even APISIX can't support it. But here we can do this indirectly using some methods.

Firstly, using this function.
![image](https://user-images.githubusercontent.com/8078418/149049496-145566b9-051c-4fe5-8d9a-1c7de928a041.png)

Config the uri match (the var `uri` is the pure URI and the `request_uri` will include query params `?xxx=xxx`)
![image](https://user-images.githubusercontent.com/8078418/149049562-c2327c2b-40e2-4a18-9a4f-8e74a44579ce.png)

Config the query match
![image](https://user-images.githubusercontent.com/8078418/149049702-865fa14b-13e8-4741-ba74-82f6a5dc72e7.png)

**However, keep in mind that this is not the "right" way to use it, and while it does work, it may cause performance degradation or other problems.**

**Comment by stutipatelorigo** [comment]
hi @juzhiyuan , I am still not sure about this. I tried. It seems like We can declare a global uri for many matching urls but not the specific one which is vulnurable at some point.

for e.g. If i have below urls to create in apisix routes:
1. GET /users/{username}
2. GET /users/{username}/authorities
3. GET /users/{username}/tenants

**Comment by bzp2010** [comment]
Hi, @stutipatelorigo 
You can create multiple routes with different priorities for the different paths you need to match, and they will be matched in turn.

Again, no matter what optimizations are made to match regular expressions, it is a costly operation to perform and you may want to avoid performing one or more regular matches per request by other engineering means whenever possible. For example, using a header, a cookie, or some kind of token containing the above information (you can handle it with a custom plugin) are relatively more viable options.
If we were to natively support the `{params}` syntax, as some Golang frameworks do, we wouldn't be able to use radixtree to provide extremely efficient route matching, so using this pattern would cause performance degradation in either the route matching phase or the HTTP request processing phase, so it's a tradeoff.

**Comment by stutipatelorigo** [comment]
@bzp2010 
thanks for your response. Currently i am facing issue with replacing the path uris. Which is "/sw/users/*" to "/users/$1".
Can you help how to do it with URI Override method ?

**Comment by bzp2010** [comment]
@stutipatelorigo 
You can use the proxy-rewrite[[1]](https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite) plugin.

**Comment by stutipatelorigo** [comment]
hi @bzp2010 , I tried but some config is missing i guess. is there any good or proper example for this? The documentation does not actually justify properly what to include in the config

**Comment by bzp2010** [comment]
@stutipatelorigo 

You can use the `regex_uri`.

```json
{
  "regex_uri": ["^/sw/users/(.*)", "/users/$1"]
}
```

The above code is not syntax-checked, you need to pay attention to it. However, the ideas it contains are completely correct. This is the content of Nginx's rewrite directive, and you can use the experience about it to do this.

**Comment by stutipatelorigo** [comment]
@bzp2010 , I tried that as a first option before i created this help requests in first place.
or  that means i have to use request_uri as a parameter 

STILL NOT WORKING
![Screenshot (23)](https://user-images.githubusercontent.com/97489149/151285080-0edb7a29-2ce7-47ea-b1e8-f9587d5dcffe.png)

**Comment by bzp2010** [comment]
@stutipatelorigo 
NoNoNo, I give the JSON writing method in the Admin API, you need to take the content in quotes and write it in the `regexp` and `template` lines respectively.

**Comment by lucamaf** [comment]
I'm trying something similar and it is not working at the moment ...
any idea?
![Screenshot from 2022-10-19 16-29-33](https://user-images.githubusercontent.com/1726883/196720402-c68eef28-6e39-407d-b2d0-2f024d00752e.png)

**Comment by achalagarwal** [comment]
@lucamaf did you get it working now? I would check make sure to check the logs for the final url it gives
