### ISSUE TITLE
/debug/pprof/  this api un auth

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix-dashboard#2286]
### Issue description

/debug/pprof/  未登录的情况下可以直接访问

### Expected behavior

/debug/pprof/  未登录不能访问

### How to Reproduce

curl localhost:9000/debug/pprof/  

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: 2.10
- Browser version, if have:

**Comment by zaunist** [comment]
@qq54903099 Thansk for your comment, we will check it.

**Comment by jwrookie** [comment]
ref : https://github.com/apache/apisix-dashboard/blob/master/api/internal/filter/authentication.go#L34

path : /debug/pprof  omited the auth check,  by design?

I'd be happy to fix it if you want

**Comment by zaunist** [comment]
> 

You are right! Welcome to pr.

**Comment by jwrookie** [comment]
can i base on cookie to fast fix it?

**Comment by zaunist** [comment]
> 

I'm not sure what do you want to do, can you give some example ？

**Comment by jwrookie** [comment]
currently, `user authentication` is done through http headers,   can not auto add the headers on a newtab for `/debug/pprof`

**Comment by zaunist** [comment]
> 

Got it.

**Comment by zaunist** [comment]
> 

@jwrookie . You can submit a PR to accomplish your idea, and other community member will review your code.

**Comment by jwrookie** [comment]
droplet nonsupport set cookie :disappointed_relieved:

**Comment by bzp2010** [comment]
Maybe we can add a configuration item that is turned off by default, I don't think the pforf API is very meaningful for dashboard. I.e., turn off this API by default and turn it on by modifying the configuration when you need to use it.

**Comment by jwrookie** [comment]
> 

but at turn it on, the problem will reproduce

**Comment by zaunist** [comment]
Hi, community. IMO, since this interface is very rarely used, I suggest removing pprof and adding one manually for debugging if needed in development.

**Comment by zaunist** [comment]
And I'm glad to contribute this issue.

**Comment by jwrookie** [comment]
If it is not connected to `prometheus` or other similar tools, I recommend using it for continuous monitoring and analysis
