### ISSUE TITLE
idle_timeout  will be lost when set to 0 in upstream

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix-dashboard#2294]
### Issue description

see in: https://github.com/apache/apisix/issues/6188

### Expected behavior

```
"keepalive_pool": {
    "idle_timeout": 0,
    "requests": 1000,
    "size": 320
  }
```

### How to Reproduce

1. add a upstream with keepalive_pool:
```
"keepalive_pool": {
    "idle_timeout": 0,
    "requests": 1000,
    "size": 320
  }
```
2. pull upstream with admin-api, idle_timeout was lost
3. updtea this upstream set idle_timeout =0 with admin-api, idle_timeout  exist

### Environment

- apisix version (cmd: `apisix version`): 2.11.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: 2.10.1

- Browser version, if have:

**Comment by zaunist** [comment]
Hi, @jagerzhang. Because the filed definition https://github.com/apache/apisix-dashboard/blob/bec322aafc02ed79c9a289b66bb7a3de0446768c/api/internal/core/entity/entity.go#L159
If the filed be set a default value, the filed will be lost. This is indeed a bug, I will fix it later
@juzhiyuan Please assign to me.

**Comment by bzp2010** [comment]
> Hi, @jagerzhang. Because the filed definition
> 
> https://github.com/apache/apisix-dashboard/blob/bec322aafc02ed79c9a289b66bb7a3de0446768c/api/internal/core/entity/entity.go#L159
> 
> 
> If the filed be set a default value, the filed will be lost. This is indeed a bug, I will fix it later
> @juzhiyuan Please assign to me.

assigned

**Comment by zaunist** [comment]
Thx
