### ISSUE TITLE
Route.Upstream.Retries field needs to support zero value

### ISSUE THREAD

**Issue by Chaunceyan** [apache/apisix-dashboard#2297]
### Issue description

As shown in the doc, the retries field expected zero and null value to behave differently. 
But current entity definition omit zero value to empty, so this configuration does not function properly. 
![image](https://user-images.githubusercontent.com/8214895/151332575-06c43693-0e75-4be9-9d84-ca373f9b516d.png)

I am raising PR for this.

### Expected behavior

Zero and Null value should be well distinguished.

### How to Reproduce

1. Create Upstream with retries being zero.
2. View Upstream to see the retries being empty.

### Screenshots

![image](https://user-images.githubusercontent.com/8214895/151333059-df5d0347-e064-4717-abd2-7f281ff38e68.png)
![image](https://user-images.githubusercontent.com/8214895/151333126-3d2cdbd5-4088-43ed-8519-fa6c9cb8cad4.png)
![image](https://user-images.githubusercontent.com/8214895/151333308-e1470460-f6ab-47a4-b5e6-24ef4db3606f.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by zaunist** [comment]
@juzhiyuan . We can close this issue after the #2298 merged.
