### ISSUE TITLE
插件相关界面添加 "已启用" 分组选项，Insert new ButtonGroup component which with `All` , `Enabled` Child items in Plugin List View. 

### ISSUE THREAD

**Issue by inickel** [apache/apisix-dashboard#2299]
# Feature request

- Route > Route List > Create or Configure > `STEP 3 Plugin Config`
- Service > Create Service > `Step 2 Plugin`
- Plugin > Plugin List > Enable > `Global Plugin List`

## Please describe your feature

Insert new ButtonGroup(or Tabs) component which with `All` , `Enabled` child items. 

When child item is selected `Plugin List` shows the results by filter `all` or `enabled` plugins

界面上添加一个按钮组或者选项卡组，选项为 默认选中 `全部` 和`已启用`  ，快速区分`已经启用`的插件功能。

## Additional context

有没有计划做一个类似 `插件市场` 的功能? 或者在线添加一个插件。

**Comment by zaunist** [comment]
Hi, @inickel . If you have any idea, welcome to send eamil to dev-subscribe@apisix.apache.org and follow the reply to subscribe mailing list, and you can send your idea to mailing list to discuss with other community members.

**Comment by juzhiyuan** [comment]
> 在线添加一个插件

Hi @inickel, this is a big and new feature for both Dashboard and Apache APISIX, when users upload a plugin (Lua or other languages), Dashboard should be able to send the Plugin to APISIX and reload it. Could you please send a DISCUSS to our mailing list first?

**Comment by Wcdaren** [comment]
Perhaps this problem is caused by the confusing logic of adding and enabling plugins, which we can solve with the following modifications.

- Form to show all added plugins (both enabled and unenabled)
- The logic of enabling plugins is modified to add plugins

![image](https://user-images.githubusercontent.com/25494875/178094746-345eaa96-33c6-4bc8-9dc2-20d93b0bf58b.png)

**Comment by guoqqqi** [comment]
Hello @Wcdaren I have a few questions about your proposal
1. 
> Form to show all added plugins (both enabled and unenabled)
I understand that you are thinking that when we configure a plugin and it is not enabled, it should also be displayed in the list, right?
But right now we don't support this and I'm not sure if we need to change the API interface. The current implementation is that the plugin is removed when we don't enable it, and doesn't save its configuration, which is an area that could be optimised.

2.
>The logic of enabling plugins is modified to add plugins
I think adding is more like adding a new plugin, where the expression I think would be more appropriate to enable the functionality of a particular plugin.

**Comment by Wcdaren** [comment]
Of course, it can be tricky to make changes to the logic that distinguishes between add and enable. We can now solve this issue simply by sorting (enabling or not) as follows

![image](https://user-images.githubusercontent.com/25494875/178132964-3ba507e9-24b3-4db6-8c0e-b995eac449d2.png)
![image](https://user-images.githubusercontent.com/25494875/178132978-2f3ce700-74cc-4de9-9694-85a9356cc7de.png)

**Comment by Morakes** [comment]
I think this might be helpful.
1.Add a plugin remote search to the plugin list to help us find the "enable" plugin quickly.
Also, it might be clearer to change the "Add" button to the "Enable" button. Like this.
![82fda9ec36324d1d82e300f3a1471ae](https://user-images.githubusercontent.com/74828385/183823615-760238d1-6973-4dab-b22d-80e1a3a2a281.jpg)

2.Add "Tab" to the global plugins to distinguish between "enable" and "not enbale", which looks intuitive.
![af5ad08c9c33d86a2222b1c834b165f](https://user-images.githubusercontent.com/74828385/183824562-686d6199-18a1-4c52-be23-0e1dec964ca2.jpg)
