### ISSUE TITLE
FR - limit-count plugin form need to add allow_degradation section.

### ISSUE THREAD

**Issue by anldrms** [apache/apisix-dashboard#2301]
# FR - limit-count plugin form need to add allow_degradation section.

## Apisix Dashboard Plugin Editor
![resim](https://user-images.githubusercontent.com/21142588/151945868-e9ee81db-0b3b-4ed4-a158-a80dd1882dee.png)

On the limit-count editor there's something missing on form table. 

## Our problem

allow_degradation default value has false. But if we want trying to change it to true there's no option to do that in form table. And if we'll switch to json table and can change it to manually , unfortunatelly  if there will be change on form table after this step it going to dissapear.

## Request

There should be some options on form table be able to do change values which on plugin editors(limit-count , limit-conn etc.)

**Comment by juzhiyuan** [comment]
cc @guoqqqi to have a look

**Comment by oil-oil** [comment]
Please assign it to me, I'll fix this .😃

**Comment by anldrms** [comment]
@oil-oil I'm looking forward to fix it as soon as you can possible. Thanks.

**Comment by oil-oil** [comment]
> @oil-oil I'm looking forward to fix it as soon as you can possible. Thanks.

OK, It is almost finished, and the PR is expected tomorrow.🐵

**Comment by anldrms** [comment]
Awesome , thank you!
