### ISSUE TITLE
api use dgrijalva / jwt-go have Access Restriction Bypass

### ISSUE THREAD

**Issue by hongbinhsu** [apache/apisix-dashboard#2302]
### Issue description

Access Restriction Bypass
Affecting [github.com/dgrijalva/jwt-goOpen this link in a new tab](https://snyk.io/vuln/golang%3Agithub.com%2Fdgrijalva%2Fjwt-go) package, versions <4.0.0-preview1

PS： https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515

dgrijalva / jwt-go The latest has been switched to golang-jwt/jwt；

It is recommended to use V4 with higher security

### Expected behavior

go install "github.com/golang-jwt/jwt/v4"

### How to Reproduce

look  https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515
and https://github.com/golang-jwt/jwt

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by zaunist** [comment]
Thanks for your contribution https://github.com/apache/apisix-dashboard/pull/2304. And we need pass the CI check before merge to master.
