### ISSUE TITLE
web build in node 16 rjsf/core version to lower

### ISSUE THREAD

**Issue by hongbinhsu** [apache/apisix-dashboard#2306]
### Issue description

When used node 16 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

### Expected behavior

use node 16 build success;

Node 和node-sass的版本存在绑定关系，关系对照表如下：
![image](https://user-images.githubusercontent.com/1223271/152988576-cc476b57-d5fa-40c6-9cff-8ad2620ce4c3.png)

### How to Reproduce

update some js package version in  package.json

启动时间有点慢，试试新出的 MFSU 方案，1s+ 完成启动，详见 https://github.com/umijs/umi/issues/6766

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by zaunist** [comment]
Expect dashboard to support node 16.

**Comment by Baoyuantop** [comment]
You can refer to https://github.com/ant-design/ant-design-pro/blob/master/package.json
