### ISSUE TITLE
bug: Setting rejected_msg in "limit-req" plugin does not save

### ISSUE THREAD

**Issue by 1657486787** [apache/apisix-dashboard#2310]
### Issue description

Setting rejected_msg in "limit-req" plugin does not save

### Environment

- apisix version (cmd: `apisix version`):2.12
- OS (cmd: `uname -a`):Linux wx-2 3.10.0-1160.el7.x86_64

### Steps to reproduce

1.Set rejected_msg in "limit-req" plugin ， eg:
{
  "rate": 1,
  "burst": 1,
  "key_type": "var",
  "key": "1",
  "rejected_code": 503,
  "nodelay": false,
  "rejected_msg":"请求太多了，稍后重试..."
}
2. After saving, go in and check again, and find that it is not saved， eg:
{
  "rate": 1,
  "burst": 1,
  "key_type": "var",
  "key": "1",
  "rejected_code": 503,
  "nodelay": false
}

### Actual result

{
  "rate": 1,
  "burst": 1,
  "key_type": "var",
  "key": "1",
  "rejected_code": 503,
  "nodelay": false
}

### Error log

nothing 

### Expected result

{
  "rate": 1,
  "burst": 1,
  "key_type": "var",
  "key": "1",
  "rejected_code": 503,
  "nodelay": false,
  "rejected_msg":"请求太多了，稍后重试..."
}

**Comment by zaunist** [comment]
@1657486787 I checked this issue,  due to rejected_msg is not supported on the front-end form, it is not displayed, but there is already data in etcd. We should support this filed in front, @guoqqqi please take a look.
![image](https://user-images.githubusercontent.com/38528079/153136204-59c1da8a-e043-4d8f-8cc4-2057168cda29.png)

**Comment by oil-oil** [comment]
Please assign it to me, I'll fix this.

**Comment by tzssangglass** [comment]
> Please assign it to me, I'll fix this.

@oil-oil assigned you, have fun.

**Comment by oil-oil** [comment]
The PR related to this issue has been merged. I think this issue can be closed.
