### ISSUE TITLE
feat: Display ID of all objects on the dashboard

### ISSUE THREAD

**Issue by nfrankel** [apache/apisix-dashboard#2319]
### Feature description

The Admin API allows to create objects (Route, Upstream, etc.). You can either set the ID or let APISIX generate one for you.

The dashboard doesn't show IDs, so in the case of auto-generated IDs, you need to first query the object and find the ID before using it as a reference. It would be more user-friendly to display the ID in the dashboard as a read-only field.

>As a User, I want to display IDs in the dashboard in order to reference them easily in other commands

**Comment by zaunist** [comment]
The consumer does not need to display ids because it uses name as the key and does not have an ID field, ref https://apisix.apache.org/zh/docs/apisix/architecture-design/consumer
