### ISSUE TITLE
Update apisix-dashboard theme color

### ISSUE THREAD

**Issue by oil-oil** [apache/apisix-dashboard#2325]
# Feature request

At present, the theme color of apisix dashboard is ant design default blue, but the theme color of apisix is red. I think if the theme color of apisix dashboard is changed to red, it will be more integrated.

## Describe the solution you'd like
In the development environment, I tried to change the theme color of the apisix dashboard to the same red as the apisix logo, and found that it worked well.

As shown below:
<img width="1949" alt="image" src="https://user-images.githubusercontent.com/57465570/154604586-7f934742-9fad-4d78-a4cf-a25e5645549b.png">

<img width="1955" alt="image" src="https://user-images.githubusercontent.com/57465570/154604636-6898cddd-52a7-47c4-bb9e-138a9c8b00fb.png">

Included some red buttons in previous pages, such as delete button, but after the theme color is changed to red, the main button may be indistinguishable from the delete button.

So I think it is possible to add ghost attribute to danger style button .
As shown below:

before
<img width="360" alt="image" src="https://user-images.githubusercontent.com/57465570/154605730-f0b44602-2fe5-4930-90cb-d656392eb1a6.png">

after
<img width="341" alt="image" src="https://user-images.githubusercontent.com/57465570/154605503-510e8e79-4ec3-4fa9-9074-e0603dbeb80d.png">

More style details can be discussed together .🤓

**Comment by leslie-tsang** [comment]
Sorry, but I prefer the original scheme; the new color scheme makes me nervous.

**Comment by oil-oil** [comment]
> Sorry, but I prefer the original scheme; the new color scheme makes me nervous.

Oh sorry, maybe the red I chose was too bright and it made it look more nervous .

**Comment by jwrookie** [comment]
according to the operation level, only dangerous operations should be set to red
