### ISSUE TITLE
导入OpenAPI会切分多个URI路径

### ISSUE THREAD

**Issue by kevinw66** [apache/apisix-dashboard#2329]
### Issue description

同一个路由若有多个路径信息，导出后再导入会生成多个路由

### Expected behavior

只生成一个路由

### How to Reproduce

导出前
![导出截图](https://user-images.githubusercontent.com/31196226/154783520-949a272e-dbd8-47a1-bd59-ab1a238e785c.jpg)

导入后
![导入截图](https://user-images.githubusercontent.com/31196226/154783528-ca5b0835-636e-4031-b4c5-95577cd85f42.jpg)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by kevinw66** [comment]
在导入后，对任何一个路由的修改都会报名字重复的错误。只能删掉多余的，只剩下一个的情况下修改

**Comment by jwrookie** [comment]
Import and export via `ID`, keeping the same state before export and after import, this problem will not occur

**Comment by juzhiyuan** [comment]
Hello @liuxiran @bzp2010 @membphis, please take a look at this issue 🤗

**Comment by membphis** [comment]
Is it related to the definition of OPENAPI? https://spec.openapis.org/oas/v3.1.0#path-item-object

I am not sure about this. I think @liuxiran and @nic-chen should know it

**Comment by nic-chen** [comment]
hi @kevinw66 

Thanks for your contribution!

We should merge based on `route.id`, not the name, because the name is not completely guaranteed to be unique.
So what needs to be done is, when exporting, need to export a custom field such as `x-apisix-route_id`, which we could merge routes according to it when importing.

**Comment by kevinw66** [comment]
> hi @kevinw66
> 
> Thanks for your contribution!
> 
> We should merge based on `route.id`, not the name, because the name is not completely guaranteed to be unique. So what needs to be done is, when exporting, need to export a custom field such as `x-apisix-route_id`, which we could merge routes according to it when importing.

Ok, I will modify my pull request in the next few days.
