### ISSUE TITLE
consumer can`t enable openid-connect plugin

### ISSUE THREAD

**Issue by hb407033** [apache/apisix-dashboard#2357]
### Issue description

when create  one consumer and enable ‘ openid-connect’ plugin ，but can`t go next step , show 
“”请至少启用如下一种认证类插件： basic-auth, hmac-auth, jwt-auth, key-auth, wolf-rbac”

### Expected behavior

go next step and save result

### How to Reproduce

1. go [comsumer]
2. create and  enable [openid-connect ] plugin
3. go next

### Screenshots

![image](https://user-images.githubusercontent.com/10432196/156350911-d9e8bc30-d3ff-4c06-8ef9-45708c59025c.png)

### Environment

-  2.10.0  (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by Baoyuantop** [comment]
Hi @hb407033 , `Consumer` needs to work with at least one of the plugins in one of the tips, you can refer to https://apisix.apache.org/docs/apisix/architecture-design/consumer/

**Comment by hb407033** [comment]
sorry,  but i don`t need  any plugins in one of the tips,   why can`t work with oidc-connect only? any consider in design?

**Comment by Baoyuantop** [comment]
I don't quite understand why need to use the `openid-connect` plugin with consumer, here are some articles that might help:
https://apisix.apache.org/blog/blog/2021/08/25/using-the-apache-apisix-openid-connect-plugin-for-centralized-authentication

**Comment by hb407033** [comment]
thanks a lot，i will try it

**Comment by leslie-tsang** [comment]
> I don't quite understand why need to use the `openid-connect` plugin with consumer, here are some articles that might help: https://apisix.apache.org/blog/blog/2021/08/25/using-the-apache-apisix-openid-connect-plugin-for-centralized-authentication

The uri is wrong. It should be 
https://apisix.apache.org/blog/2021/08/25/using-the-apache-apisix-openid-connect-plugin-for-centralized-authentication
