### ISSUE TITLE
First click on menu item does not fetch data

### ISSUE THREAD

**Issue by h2cone** [apache/apisix-dashboard#2358]
### Issue description

https://user-images.githubusercontent.com/24283234/156343757-83e020e1-d74f-4b97-9643-1686f0e24cd3.mov

Always happens after re-login: 

Click on Upstream/Service and the list will get stuck unless you click on another menu item first and then click again.

### Expected behavior

The first time you click on a menu item you can immediately see the table.

### How to Reproduce

1. Login.
2. Click on Upstream/Service.
3. See error.

### Environment

- apisix version (cmd: `apisix version`): 
/opt/homebrew/Cellar/openresty/1.19.9.1_2/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.11.0
- OS (cmd: `uname -a`): 
Darwin metaloop.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
nginx version: nginx/1.21.6
built by clang 13.0.0 (clang-1300.0.29.30)
built with OpenSSL 1.1.1m  14 Dec 2021
TLS SNI support enabled
configure arguments: --prefix=/opt/homebrew/Cellar/nginx/1.21.6_1 --sbin-path=/opt/homebrew/Cellar/nginx/1.21.6_1/bin/nginx --with-cc-opt='-I/opt/homebrew/opt/pcre2/include -I/opt/homebrew/opt/openssl@1.1/include' --with-ld-opt='-L/opt/homebrew/opt/pcre2/lib -L/opt/homebrew/opt/openssl@1.1/lib' --conf-path=/opt/homebrew/etc/nginx/nginx.conf --pid-path=/opt/homebrew/var/run/nginx.pid --lock-path=/opt/homebrew/var/run/nginx.lock --http-client-body-temp-path=/opt/homebrew/var/run/nginx/client_body_temp --http-proxy-temp-path=/opt/homebrew/var/run/nginx/proxy_temp --http-fastcgi-temp-path=/opt/homebrew/var/run/nginx/fastcgi_temp --http-uwsgi-temp-path=/opt/homebrew/var/run/nginx/uwsgi_temp --http-scgi-temp-path=/opt/homebrew/var/run/nginx/scgi_temp --http-log-path=/opt/homebrew/var/log/nginx/access.log --error-log-path=/opt/homebrew/var/log/nginx/error.log --with-compat --with-debug --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-ipv6 --with-mail --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module
- etcd version, if have (cmd: run `etcd --version`):
etcd Version: 3.5.2
Git SHA: 99018a77b
Go Version: go1.17.6
Go OS/Arch: darwin/arm64
- apisix-dashboard version, if have: 
Version : 2.10.1
GitHash : 9d99ab7
- Browser version, if have:
Google Chrome 98.0.4758.109

**Comment by jwrookie** [comment]
From the video, when you click `Upstream/Service` at first  the frontend does not send a request to the backend
have a check @Baoyuantop

**Comment by Baoyuantop** [comment]
Hi @h2cone, thanks for the report. Could you please have a try with Chrome window without traces?

**Comment by h2cone** [comment]
I have tried [private browsing](https://support.google.com/chrome/answer/95464?hl=en&co=GENIE.Platform%3DDesktop) and still have the same issue.

**Comment by Baoyuantop** [comment]
OK, let me check also cc @oil-oil

**Comment by oil-oil** [comment]
> OK, let me check also cc @oil-oil

OK, I'll check it.

**Comment by oil-oil** [comment]
@h2cone  Hello, Will you still have this problem now. I can't reproduce this bug in both production and development environments. Can you provide more information for us to check ?

**Comment by h2cone** [comment]
Hi @oil-oil, here is my environment when building from source:

- v17.6.0 (node -v)
- 1.22.17 (yarn -v)
- go version go1.17.8 darwin/amd64

I switched from Chrome to Safari and can't reproduce the problem anymore.

**Comment by oil-oil** [comment]
> Hi @oil-oil, here is my environment when building from source:
> 
> * v17.6.0 (node -v)
> * 1.22.17 (yarn -v)
> * go version go1.17.8 darwin/amd64
> 
> I switched from Chrome to Safari and can't reproduce the problem anymore.

OK, I'll test it again based on this information.

**Comment by Baoyuantop** [comment]
This problem is not found in the latest version. If there is still a problem, please open it again.
