### ISSUE TITLE
Cannot get latest data after ETCD recovery

### ISSUE THREAD

**Issue by yangvipguang** [apache/apisix-dashboard#2360]
### Issue description

dashboard版本：2.10.1
ETCD版本：3.5

目前我测试了一下，如果我要备份etcd，然后删除掉个别配置（比如upsteam等），如果我要恢复之前备份的etcd数据，这个时候dashboard 不能实时更新显示恢复之前的数据，需要重启一下dashboard的服务才可以，不知道这算bug还是就预期内的。

### Expected behavior

目前我测试了一下，如果我要备份etcd，然后删除掉个别配置（比如upsteam等），如果我要恢复之前备份的etcd数据，这个时候dashboard 不能实时更新显示恢复之前的数据，需要重启一下dashboard的服务才可以，不知道这算bug还是就预期内的。

### How to Reproduce

1、备份etcd数据
2、备份后修改一些数据（比如upstream等）
3、恢复etcd数据
4、刷新dashboard页面

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by jwrookie** [comment]
looks not a dashboard bug, the data is fetched from etcd in real time. 
If you want, we can communicate by voice

**Comment by Baoyuantop** [comment]
This seems to be as expected, there is a caching layer between Dashboard and etcd.

**Comment by zaunist** [comment]
Hi, @yangvipguang. We need to discuss how to solve this problem, anyone is welcome to make suggestions!

**Comment by yangvipguang** [comment]
@zaunist  ok， I'm going to try a few times to see if I can reproduce this problem every time

**Comment by jwrookie** [comment]
> This seems to be as expected, there is a caching layer between Dashboard and etcd.

you are right, we have a layer of cache

**Comment by bzp2010** [comment]
What kind of backup/restore means do you use? I don't know much about etcd and am not sure that data changes in any case would trigger an Watch push.

**Comment by jwrookie** [comment]
According to etcd doc, `Disaster recovery` requires a restart of etcd, which means that all previous client links will be invalidated, and the old data you see is just the program's cache

As far as I know, `grpc-go` will manage failed layer 4 connections, so when `Disaster recovery` occurs, we reload the local cache and the problem will solved

**Comment by bzp2010** [comment]
This seems to be automatic in the etcd client, which will handle the reconnection logic automatically. 🤔

**Comment by jwrookie** [comment]
you are right, but we can set dialOption to control the behavior of  reconnection 
ref: https://pkg.go.dev/go.etcd.io/etcd/client/v3#Config,  https://pkg.go.dev/google.golang.org/grpc@v1.44.0/backoff
