### ISSUE TITLE
dashboard v2.10.1 The proxy-rewrite plug-in cannot be configured in routing

### ISSUE THREAD

**Issue by wangkunyu123** [apache/apisix-dashboard#2363]
### Issue description

The proxy-rewrite plug-in cannot be started in a route because it requires the host configuration in the proxy-rewrite plug-in. The plug-in configuration can be started, but it is global.
![Uploading 1646637627(1).jpg…]()

### Expected behavior

The proxy-rewrite plug-in cannot be started in a route because it requires the host configuration in the proxy-rewrite plug-in. The plug-in configuration can be started, but it is global.
![Uploading 1646637627(1).jpg…]()

### How to Reproduce

The proxy-rewrite plug-in cannot be started in a route because it requires the host configuration in the proxy-rewrite plug-in. The plug-in configuration can be started, but it is global.
![Uploading 1646637627(1).jpg…]()

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by zaunist** [comment]
Hi, @wangkunyu123. Could you provide more details for reproduce?

**Comment by wangkunyu123** [comment]
Hey buddy, the main reason is that 'proxy-rewrite' wasn't in the plugins configuration when I created the route, but it was in the plugins list, but I couldn't use 'proxy-rewrite' in the plugins list because it was global in scope and couldn't be selected, Here are my screenshots.
![1646647921(1)](https://user-images.githubusercontent.com/57695179/157012520-77b6fd02-7c2d-43eb-91d9-2c67aa4de3ba.jpg)
![1646647997(1)](https://user-images.githubusercontent.com/57695179/157012528-e33e35a1-fc41-4ee1-b27f-0f7e1b20a164.jpg)

**Comment by wangkunyu123** [comment]
> 嗨，@wangkunyu123。您能否提供更多详细信息以进行复制？

Above is my reply, please see if it is clear.

**Comment by zaunist** [comment]
Hi, @wangkunyu123. The `proxy-rewrite` is integrated into the page where the route is created.

In fact, I don't think it makes sense to integrate the plugin into this place, maybe we have to make a change in v3.

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/38528079/157151615-1de22305-0d32-4b4f-99e5-3dc11d95c5cd.png">

**Comment by wangkunyu123** [comment]
> 嗨，@wangkunyu123。被`proxy-rewrite`集成到创建路由的页面中。
> 
> 其实我觉得把插件集成到这个地方是没有意义的，也许我们要在v3.3中做出改变。
> 
> <img alt="图片" width="1594" src="https://user-images.githubusercontent.com/38528079/157151615-1de22305-0d32-4b4f-99e5-3dc11d95c5cd.png">


Ok, I know, because unlike the version I used before, I didn't notice this place, and if so, I don't think it makes sense
