### ISSUE TITLE
bug: caller in log is positioning error

### ISSUE THREAD

**Issue by jwrookie** [apache/apisix-dashboard#2365]
### Issue description

caller in log is positioning error

![1646709945670](https://user-images.githubusercontent.com/41732283/157160418-b4d757a7-55d4-440b-a705-d4d315cc87b0.jpg)

### Expected behavior

caller should is internal/filter/logging.go:45

https://github.com/apache/apisix-dashboard/blob/561ed377ec2237707bb8c78623e336360c6c6463/api/internal/filter/logging.go#L44-L57

### How to Reproduce

1. start apisix-dashboard
2. send request
3. view access.log

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: 
- Browser version, if have:

### Additional context

I want to solve it

**Comment by starsz** [comment]
Good capture ！

**Comment by zaunist** [comment]
Nice job !
