### ISSUE TITLE
Optimize demo access experience

### ISSUE THREAD

**Issue by Baoyuantop** [apache/apisix-dashboard#2369]
# Feature request

## Please describe your feature

Just a UX optimization suggestion: in the README we have the address and account information for the demo

<img width="951" alt="image" src="https://user-images.githubusercontent.com/30611190/157362917-75d7e8b4-9644-44db-9c85-0fba6d144b64.png">

Since the whole is in the same block of code, when the user clicks copy he will get the whole block of information, which cannot be put into the browser to access. This can make things tedious.

## Describe the solution you'd like

1. Place the address and account information separately so that when the user clicks copy he can paste it directly into the browser to access.
2. Put a separate link above for example: 
We have an online demo, [click to visit](http://106.55.144.26/)

What do you think?

**Comment by guoqqqi** [comment]
Agree +1 
and cc @juxianzheng Can you help finish it? 😄

**Comment by SkyeYoung** [comment]
Agree. And we can refer to https://github.com/unocss/unocss#readme.
