### ISSUE TITLE
TODO: model checking thougth by json schema

### ISSUE THREAD

**Issue by jwrookie** [apache/apisix-dashboard#2372]
ref: https://github.com/apache/apisix-dashboard/pull/2362#discussion_r823227607

**Comment by jwrookie** [comment]
@nic-chen https://github.com/apache/apisix-dashboard/pull/2362#discussion_r823227607
What should we do when there is the same configuration?  use schema.json or customize.json?  

Generally, customization have a higher priority, but i an not sure can overwrite the schema.json

**Comment by nic-chen** [comment]
hi @jwrookie 

I think it should panic and give an error message. 

`schema.json` is generated by APISIX and should not be overwritten.

**Comment by jwrookie** [comment]
got it,thanks
