### ISSUE TITLE
proxy-rewrite.regex_uri need empty value to replaced

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix-dashboard#2381]
### Issue description

at dashboard when proxy-rewrite.regex-uri can't replace empty value;but use apisix api support empty value.
![image](https://user-images.githubusercontent.com/3895272/158342820-bb339a58-bfe0-47bf-944f-f98a550de299.png)

### Expected behavior

support empty value to replaced

### How to Reproduce

use dashboard plugin-rewrite plugin

### Environment

- apisix version (cmd: `apisix version`): 2.12.1& dashboard lasted
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by zaunist** [comment]
Good catch, I think we should fix this problem.

**Comment by leslie-tsang** [comment]
@liangliang4ward would you like to fix it ?

**Comment by liangliang4ward** [comment]
> @liangliang4ward would you like to fix it ?

ok;  assign me. 

but I never download dashboard code .hhh 

let me try.
