### ISSUE TITLE
bug: i18n improvements

### ISSUE THREAD

**Issue by nfrankel** [apache/apisix-dashboard#2387]
### Issue description

Catch all issue to improve i18n:

- [ ] Replace Route List with Routes
- [ ] Use a shorter label for Title and Description

**Comment by juzhiyuan** [comment]
**How to fix**

> This comment is for contributors.

1. Fork this project;
2. Search codes with keyword: `Route List`;
3. Replace all of them with `Routes`.
4. Note: I'm not sure if the E2E test will fail but feel free to submit PR, and our contributors will also help you on E2E.

**Comment by catherineruoxiwu** [comment]
I would like to work on this issue!
