### ISSUE TITLE
help request: How to use plug-in orchestration?

### ISSUE THREAD

**Issue by kingmouse-yx** [apache/apisix-dashboard#2392]
### Description

I've been using plugin orchestration recently. But I have some doubts.
Can only code be used in condition judgment?
Is there any relevant documentation?

### Environment

- APISIX version (run `apisix version`): 2.9
- Operating system (run `uname -a`): arwin kingmouse.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan 5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant: 2.10.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by nic-chen** [comment]
hi @kingmouse-yx 

you could orchestrate plugins on the dashboard.

> Can only code be used in condition judgment?

yes. In theory, any variable can be used, but we only recommend judging by `code` for now.

**Comment by kingmouse-yx** [comment]
@nic-chen 
Hi, I'd like to know if I use other variables instead of code field, will there be a bug？

**Comment by shuaijinchao** [comment]
Currently supports the use of `code` and `body`, which are the return parameters of the plugin, you can understand by the following code.

```lua
local key_auth = plugin.get("key-auth")
local function func_rule_01816807_8c95_4e88_bc49_29b47286585e(ctx)
  local phase_fun = key_auth.access or key_auth.rewrite
  local plugins = ctx.script_plugins

  -- here
  local code, body = phase_fun(_M.conf_01816807_8c95_4e88_bc49_29b47286585e, ctx)
  core.table.insert(plugins, "key-auth")
  core.table.insert(plugins, "conf_01816807_8c95_4e88_bc49_29b47286585e")
  if code == 500 then -- here
    return _M.func_rule_56e9ba95_9099_43df_9bef_051907a27c7c(ctx)
  end

  return _M.func_rule_53c9252d_d3d0_4378_a71a_1c108173ebe2(ctx)
end
```

**Comment by kingmouse-yx** [comment]
Thanks，I get it
