### ISSUE TITLE
docs: How to reset the password of apisix dashboard?

### ISSUE THREAD

**Issue by alexchan10241** [apache/apisix-dashboard#2395]
### Current State

I forgot my account password.Then I can not get access to reset it . Need somebody help,please!!!

### Desired State

I forgot my account password.Then I can not get access to reset it . Need somebody help,please!!!

**Comment by jwrookie** [comment]
https://github.com/apache/apisix-dashboard/blob/162c5d7bcdfa36d76681b2a607267bcb76185cc5/api/conf/conf.yaml#L78-L82

The account and password store in conf.yaml, you can restart  dashboard after change it if you want to change
