### ISSUE TITLE
image version is not correct

### ISSUE THREAD

**Issue by mar-heaven** [apache/apisix-dashboard#2405]
### Issue description

the image of managerapi is *dashboard:ci* in path **api/test/docker-deploy/docker-compose.yaml**, a middle image,need the latest release.

### Expected behavior

use latest version

### How to Reproduce

branch master

### Environment

branch master

**Comment by jwrookie** [comment]
It uses by workflow for some testing
https://github.com/apache/apisix-dashboard/blob/162c5d7bcdfa36d76681b2a607267bcb76185cc5/.github/workflows/deploy-with-docker.yml#L38-L77
