### ISSUE TITLE
Popup message has a typo

### ISSUE THREAD

**Issue by Baoyuantop** [apache/apisix-dashboard#2412]
### Issue description

refer to https://github.com/apache/apisix/discussions/6773#discussioncomment-2520521

### Expected behavior

None

### How to Reproduce

None

### Screenshots

![](https://user-images.githubusercontent.com/45227339/161163840-e5aea8f1-1428-4e50-b3ee-09de05819612.png)

**Comment by SkyeYoung** [comment]
Maybe we should have a `typo` label. :D

**Comment by juzhiyuan** [comment]
**How to fix**

1. Fork this project.
2. Open this project with your preferred editor, for me, it's VS Code.
3. Search codes with keywords: `Please condigure plugin`
4. Fix it and submit PR

**Comment by tiankonglan** [comment]
I have fix typo , and commit a pull request.

**Comment by Baoyuantop** [comment]
Hi @tiankonglan, this typo has been resolved in https://github.com/apache/apisix-dashboard/pull/2417. Thank you for being so helpful ~
