### ISSUE TITLE
docs: 404 when visit deploy.md

### ISSUE THREAD

**Issue by lilien1010** [apache/apisix-dashboard#2426]
### Issue description

NOTE: Only CentOS 7 is supported currently, for more information, please refer to [here](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md).

in https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/install.md

### Expected behavior

no

### How to Reproduce

no

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by juzhiyuan** [comment]
I just checked the reason: in this commit[1], we combined `deploy.md` with `install.md` together, I think it's ok to remove the hyperlink, and update the `RPM` section with:

```
NOTE: Only CentOS 7 is supported currently.
```

[1] https://github.com/apache/apisix-dashboard/commit/32183799dd7943a1b9bb3ae38fa2b682979b73b9
