### ISSUE TITLE
I'm not able to find plugin_config menu bar

### ISSUE THREAD

**Issue by MirtoBusico** [apache/apisix-dashboard#2429]
# Feature request

I've found in [#1904 ](https://github.com/apache/apisix-dashboard/issues/1904) that there should be possible to access plugin_config

But I don't understand Chinese language and I was not able to figure out where is the menu entry

I'm using Dashboard 2.10.1
<img width="1078" alt="ksnip_20220417-115119" src="https://user-images.githubusercontent.com/11090934/163709847-60e5c997-2116-457d-8d3e-baf0370d6b53.png">

## Please describe your feature

Provide documentation in English on how to access the plugin_config entry

**Comment by Baoyuantop** [comment]
<img width="1957" alt="image" src="https://user-images.githubusercontent.com/30611190/163740653-18c87cb9-7a58-4270-a106-5b553d675a27.png">
Hi @MirtoBusico, just making sure this is what you want?

**Comment by MirtoBusico** [comment]
Hi @Baoyuantop YES!
Thanks a lot!
