### ISSUE TITLE
plugins list not sync with apisix plugins list api

### ISSUE THREAD

**Issue by lazychanger** [apache/apisix-dashboard#2430]
https://github.com/apache/apisix-dashboard/blob/0e6411f1d6818843481797f75e5cb25c00c11442/api/internal/handler/schema/plugin.go#L38-L41

https://github.com/apache/apisix-dashboard/blob/0e6411f1d6818843481797f75e5cb25c00c11442/api/internal/handler/schema/plugin.go#L47-L63

读取的是本地[`schema`](https://github.com/apache/apisix-dashboard/blob/master/api/conf/schema.json)。而不是通过`admin api`读取`apisix`配置的[`plugins`](https://apisix.apache.org/zh/docs/apisix/admin-api#plugin)。

这样会导致配置在`apisix`的`conf.yaml`中配置的`plugins`与`dashboard`显示的不一致。

例如：新增插件[`opentelemetry`](https://apisix.apache.org/zh/docs/apisix/plugins/opentelemetry)

### Expected behavior

-

### How to Reproduce

-

### Environment

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/20916944/163746694-0f61f4be-9b4d-4e10-8f8e-4c133381a7ce.png">

**Comment by jwrookie** [comment]
Currently only restart `dashboard ` can solve it, i think we should provide a `sync api` to allow the user to actively refresh the local cache.

**Comment by lazychanger** [comment]
> Currently only restart dashboard can solve it, i think we should provide a sync api to allow the user to actively refresh the local cache.

可能理解有误。我的意思是`apisix`的`conf.yaml`.`plugins`增加或者删除了`plugin`，`dashboard`这边并不会同步`apisix`的`plugins`

**Comment by jwrookie** [comment]
I'm sorry for didn't help you, I will replay you after self-checking

**Comment by Baoyuantop** [comment]
Hi @lazychanger, Currently, Dashboard can only synchronize the APISIX plugin list via the `api/conf/schema.json` file. If the APISIX plugin list changes and you need to synchronize this file to Dashboard, you can refer to https://apisix.apache.org/docs/dashboard/FAQ#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard
We've considered improving this behavior in Dashboard V3, so feel free to join the discussion! https://github.com/apache/apisix-dashboard/issues/2354

**Comment by Baoyuantop** [comment]
If there is still a problem, please open it again.
