### ISSUE TITLE
Certificate records's number does not match that of the ETCD

### ISSUE THREAD

**Issue by bingoku** [apache/apisix-dashboard#2433]
### Issue description

UI 上显示 7 条，实际etcd数据库里面有 10 条

### Expected behavior

应该显示完整的数据。

### How to Reproduce

路径  /ssl/list 可以查看

### Screenshots

<img width="1199" alt="iShot2022-04-18_17 35 35" src="https://user-images.githubusercontent.com/4134788/163789562-8fe6e765-d366-49c7-8c40-31b49ae912d2.png">

<img width="431" alt="iShot2022-04-18_17 34 56" src="https://user-images.githubusercontent.com/4134788/163789656-fed77f66-22bf-4e3c-b78a-c6e3628c043e.png">

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by jwrookie** [comment]
Did you add the `ssl certificate` via `admin-api`?  if so you can restart the dashboard, this may be caused by dashboard cache

**Comment by bingoku** [comment]
> Did you add the `ssl certificate` via `admin-api`? if so you can restart the dashboard, this may be caused by dashboard cache

是的，重启dashboard就解决了。
Yes, just restart the dashboard.

发现另一个问题。
Another problem was found.

同样一份证书，可以重复添加到 SSL 里面？这个似乎也不太对。
The same certificate can be added to SSL repeatedly? This doesn't seem quite right.

**Comment by jwrookie** [comment]
We do not read the certificate content and cannot perceive the difference. 
And you need to determine for yourself the problem of a duplicate certificate.

**Comment by Baoyuantop** [comment]
If there is still a problem, please open it again.
