### ISSUE TITLE
Consumer List Page reports error when a consumer is created with admin api

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix-dashboard#2436]
### Issue description

Consumer List Page reports error when a consumer is created with admin api,  the consumer doesn't have plugin.

### Expected behavior

Consumer List should list the consumer created with admin api

### How to Reproduce

1. creating a consumer with admin api:
 ```bash
curl --location --request PUT 'http://10.18.216.71:9180/apisix/admin/consumers'  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data '{"username":"test","desc":"test"}'
```
2. then view the Consumer List Page got a error

### Screenshots

![image](https://user-images.githubusercontent.com/5896784/164218501-e88778e8-00fa-4a7f-b360-de97e7dbcf9a.png)

### Environment

- apisix version (2.13.1):
- OS (image: apache/apisix:2.13.1-alpine):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: image: apache/apisix-dashboard:2.11-alpine
- Browser version, if have: Microsoft Edge 100.0.1185.44

**Comment by Baoyuantop** [comment]
Hi @qihaiyan, thanks for your report.
> 1. creating a consumer with admin API:

I want to know the response to this request.
By the way you can refer to https://apisix.apache.org/docs/apisix/admin-api#consumer

**Comment by qihaiyan** [comment]
> Hi @qihaiyan, thanks for your report.
> 
> > 1. creating a consumer with admin API:
> 
> I want to know the response to this request. By the way you can refer to https://apisix.apache.org/docs/apisix/admin-api#consumer

the response is 
```json
{"action":"set","node":{"value":{"username":"test","update_time":1650504185,"create_time":1650504185,"desc":"test"},"key":"\/apisix\/consumers\/test"}}
```

the admin api document mentions that only username for consumer is required, other params ars all optional. so when i create a consumer with admin api , only username is used.

**Comment by qihaiyan** [comment]
https://github.com/apache/apisix-dashboard/pull/2437

I made a pr for this issue if you don't mind. @Baoyuantop

**Comment by Baoyuantop** [comment]
> I made a pr for this issue if you don't mind. #2437 @Baoyuantop

Thanks, let me check

**Comment by Baoyuantop** [comment]
Dashboard does not allow users to create consumer objects without auth plugins, which seems inconsistent with the Admin API behavior. cc @bzp2010 @juzhiyuan
