### ISSUE TITLE
bug: advance matching in the route create page causes the page to crash

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix-dashboard#2438]
### Issue description

When we create an advanced match rule in a route, the page will crash if the reverse setting is not adjusted.

Based on the occurrence conditions, it is presumed that the default value of the reverse field is not set correctly. At that point, executing toString on a `null` value will result in a JS error.

https://github.com/apache/apisix-dashboard/blob/1fa5df3618708b392bb5fc2c866419b406cc43a7/web/src/pages/Route/components/Step1/MatchingRulesView.tsx#L148-L152

### Expected behavior

correct operation

### How to Reproduce

1. go to route create page
2. create a advance matching rule that not change `reverse` field (**don't click it**)
3. click `confirm`
4. page crashed

### Environment

- apisix-dashboard version, if have: 2.11.0

**Comment by Si-ege** [comment]
I want to try to finish
