### ISSUE TITLE
A question about redirect to https with  'lb + apisix'

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix-dashboard#2445]
### Discussed in https://github.com/apache/apisix/discussions/6928

<div type='discussions-op-text'>

<sup>Originally posted by **Lewisyixin** April 25, 2022</sup>
Is there any way to redirect from http  to https on apisix which behind a lb  meanwhile use http to proxy between lb and apisix?
We want to use apisix to replace nginx. Our nginx conf is about below..
Our ssl certs are on lb.  lb's 80 port proxy to nginx 80  port and 443 port proxy to nginx 443 port.
We just want to achieve the following conditions:

1. ssl cert just on lb and nginx 443 port is just a http port
2. redirection of https  is completed by nginx(because some domain don't want auto redirection)

`server{
        listen 80;
        server_name www.test.com;
        rewrite ^(.*)$ https://$host$1 permanent;
}

server {
        listen 443 ;
        server_name www.test.com;
}
`

I tried to complete this on apisix but I found that  a different  of apisix is that  mutiple http port can't handle different configs  like behand. So is there any to accomplish the goal？

</div>

**Comment by tzssangglass** [comment]
> In my scene ssl cert should not be the necessary conditions for turning on http_to_https.

Please submit the issue and fill out the complete reproduction steps.

**Comment by Baoyuantop** [comment]
> Just set a domain and turn on "http_to_https" when creating a route rule will easily reproduce.

This process needs to be described in more detail.

**Comment by Lewisyixin** [comment]
as I described..    create route -> fill in name, domin and  turn on "http_to_https"  -> next step will  easily reproduce.
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/17898688/167384789-444a8adc-b340-45ba-99d3-2ff4d7d5746f.png">

**Comment by Baoyuantop** [comment]
> SSL cert not be the necessary conditions for http_to_https

Dashboard needs to remove this restriction
