### ISSUE TITLE
[doc] dashboard docker implement usage optimization

### ISSUE THREAD

**Issue by stubbornTanzhe** [apache/apisix-dashboard#2446]
### Issue description

apisix-dashboard login success,then access apisix/admin/labels/route or apisix/admin/labels/consumer ，encounter to get 401 Unauthorized error code,which means the jwt token that authoried by dashboard is invalid.

finally with community's help，found that the reason is more than 1 dashboard instance.
with multi instance, every instance generate and hold a jwt token,will cause validation conflicted

so we can optimize the doc to emphasize the dashboard instance number not more than 1,DIFFERENT from high availability with apisix itself.

### Expected behavior

optimize the doc,emphasize the dashboard instance number not more than 1

### How to Reproduce

1. implement more than 1 dashboard instance.
2. use user and password login 
3. access route label or service label or consumer label

### Environment

- apisix version (cmd: `apisix version`): 1.11.0
- OS (cmd: `uname -a`): euler os 2.3
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):3.4
- apisix-dashboard version, if have: 1.10.0
- Browser version, if have:

**Comment by FangSen9000** [comment]
I want to solve this issue. Which document should I optimize? Is there any recommendation

**Comment by SkyeYoung** [comment]
@juzhiyuan @bzp2010 Looks like this issue should be closed.
