### ISSUE TITLE
Add a IPv6 address in upstream nodes->host failed

### ISSUE THREAD

**Issue by topzyh** [apache/apisix-dashboard#2449]
### Issue description

When I add a IPv6 address in upstream nodes->host，
report an error:  
schema validate failed: nodes: Must validate at least one schema (anyOf) nodes.0.host: Does not match pattern '^\*?[0-9a-zA-Z-._]+$'

### Expected behavior

My server IP is a IPv6 address, I need add it

### How to Reproduce

Add a IPv6 Address in upstream nodes->host,
such as:
`{
  "nodes": [
    {
      "host": "2409:1000:1::1003",
      "port": 20000,
      "weight": 10
    },
    …
  ],
  …
}`

### Environment

- apisix-dashboard version: 2.11.0

**Comment by jwrookie** [comment]
@topzyh  Hi, it not a bug, just not support now
The good news is that it has been implemented as a new feature and we can support it in the next release 
More detail see: https://github.com/apache/apisix/pull/6908

**Comment by topzyh** [comment]
thanks,
can apisix-dashboard support it ?

**Comment by jwrookie** [comment]
`apisix-dashboard` can support it  just using a new `JSON schema`

**Comment by Baoyuantop** [comment]
Our Host should support IPV6 input.
