### ISSUE TITLE
MQTT edit

### ISSUE THREAD

**Issue by believe1499** [apache/apisix-dashboard#2455]
现在MQTT相关的编辑只能通过命令行调用接口的方式吗，可以在dashboard里面进行编辑吗？

**Comment by jwrookie** [comment]
As far as I know, `apisix-dashborad` doesn't implement it yet

**Comment by believe1499** [comment]
If there is a apisix cluster, we can only call the admin-api one by one to edit the MQTT related config?

**Comment by jwrookie** [comment]
Yes, if your cluster is not using the same etcd instance and specified key prefix
