### ISSUE TITLE
 如何配置etcd的prefix

### ISSUE THREAD

**Issue by jackey20200402** [apache/apisix-dashboard#2469]
### Issue description

使用helm 安装的apisix、apisix-dashboard。apisix 配置了etcd的prefix，但在apisix-dashboard 没有找到相应的配置

### Expected behavior

apisix
etcd:
  # install etcd(v3) by default, set false if do not want to install etcd(v3) together
  enabled: true
  host:
    - http://etcd.host:2379  # host or ip e.g. http://172.20.128.89:2379
  prefix: "/apisix-test"

### How to Reproduce

apisix
etcd:
  # install etcd(v3) by default, set false if do not want to install etcd(v3) together
  enabled: true
  host:
    - http://etcd.host:2379  # host or ip e.g. http://172.20.128.89:2379
  prefix: "/apisix-test"

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by jwrookie** [comment]
here:

https://github.com/apache/apisix-dashboard/blob/a2fe71d0644927eb71ef3dd06b902ea9f4ce81f6/api/conf/conf.yaml#L37-L48

**Comment by starsz** [comment]
I think the problem is solved.
