### ISSUE TITLE
在dashboard中创建路由，无法在集群中查询到

### ISSUE THREAD

**Issue by TridentZZ** [apache/apisix-dashboard#2473]
### Issue description

在dashboard页面上创建的路由无法在集群中通过kubectl get apisixroute -A 查询到，并且没有生效，但通过yaml方式创建的资源可以在dashboard中查看到。

### Expected behavior

希望能够通过dashboard创建资源并且生效。

### How to Reproduce

1.登录dashboard
2.进入路由页面并创建路由
3.在集群中kubectl get apisixroute -A 查询资源

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by bzp2010** [comment]
Hi, @TridentZZ.

Dashboard cannot create and manage Kubernetes CRD resources, it connects directly to the etcd database and writes APISIX routes and upstreams information directly to the database, it does not reverse synchronize to the Kubernetes CRD, it is one-way synchronization in the ingress controller (from CRD to APISIX resource)
