### ISSUE TITLE
嵌入的Grafana页面无法显示

### ISSUE THREAD

**Issue by trdmm** [apache/apisix-dashboard#2491]
### Issue description

嵌入的Grafana页面无法显示.

### Expected behavior

None

### How to Reproduce

None

**Comment by SkyeYoung** [comment]
Could you please give us a screenshot so that we can locate the corresponding error?

**Comment by adocat** [comment]
![3](https://user-images.githubusercontent.com/25237966/176831775-e6e49d52-55eb-4ca3-a70a-74470c088a72.png)
修改dashboard的配置文件，增加截图那一段即可

**Comment by trdmm** [comment]
> ![3](https://user-images.githubusercontent.com/25237966/176831775-e6e49d52-55eb-4ca3-a70a-74470c088a72.png) 修改dashboard的配置文件，增加截图那一段即可 #2492

成功解决 😄
