### ISSUE TITLE
嵌入的Grafana无法正常显示（被CSP阻止）

### ISSUE THREAD

**Issue by adocat** [apache/apisix-dashboard#2492]
### Issue description

Grafana的allow_embedding 已经配置为true

单独用页面使用ifame标签html代码直接嵌入是没问题的，可以显示，怀疑是VUE的问题

### Expected behavior

![2](https://user-images.githubusercontent.com/25237966/176588611-8644d154-4730-4946-a3a0-fb2856e0d213.png)

### How to Reproduce

无

### Screenshots

![1](https://user-images.githubusercontent.com/25237966/176588241-010efaa8-cbe4-41e7-8db7-05a51e99916b.png)

### Environment

直接使用官方docker安装的，没有改过任何其他配置

**Comment by jinnyu** [comment]
me too,
on v2.11 dashboard work well,
I update dashboard to v2.13, grafana dosen't work,
Chrome show errors like above.
AND the plugin list page also show this error, and don't load plugin image.

**Comment by adocat** [comment]
解决了，加个配置就好了，官方文档没有写这部分，看源码发现写了一个csp的头，配置文件里可以自己覆盖掉，MESA的方式不好使，修改：example\dashboard_conf\conf.yaml，根据你需要的写，测试环境用我下面这个就行
![3](https://user-images.githubusercontent.com/25237966/176831351-4d781667-a1ef-44ee-be8f-f82f9070cb33.png)
