### ISSUE TITLE
The last_report_time attribute in the system information of apisix-dashboard is Invalid date

### ISSUE THREAD

**Issue by startzhuzhu** [apache/apisix-dashboard#2499]
### Issue description

The last_report_time attribute in the system information of apisix-dashboard is Invalid date

### Expected behavior

The last_report_time attribute in the system information of apisix-dashboard is not Invalid date

### How to Reproduce

1、Go to apisix-dashboard
2、Click on System Info
3、Scroll down  to last_report_time
4、see error

### Screenshots

![image](https://user-images.githubusercontent.com/46840316/178640709-7218d6c2-e36b-4afe-90eb-219944d55159.png)

### Environment

- apisix version (cmd: `apisix version`): 2.14.1
- OS (cmd: `uname -a`): Linux 3.10.0-1160.6.1.el7.x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.21.4.1
- etcd version, if have (cmd: run `etcd --version`):3.4.18
- apisix-dashboard version, if have: 2.13.0
- Browser version, if have: 

### Additional context

The latest version of apisix server-info plugin has no last_report_time attribute

**Comment by Baoyuantop** [comment]
We may need to remove this field🤔.

**Comment by startzhuzhu** [comment]
Why not keep this field.

**Comment by SkyeYoung** [comment]
> Why not keep this field.

cc @Baoyuantop

**Comment by startzhuzhu** [comment]
![image](https://user-images.githubusercontent.com/46840316/178638767-a28347fd-60bc-4519-a512-91ae97402b3b.png)
![image](https://user-images.githubusercontent.com/46840316/178638899-5f04dcc4-85d0-4503-8f81-dfeb84b34c6e.png)
This field was present in version 2.12, but not in later versions and we want to keep this field.

**Comment by Baoyuantop** [comment]
So only remove this field from the UI if it is not in the API response?

**Comment by startzhuzhu** [comment]
OK.
