### ISSUE TITLE
Want to redirect user-agent with MS Edge browser. but not working.

### ISSUE THREAD

**Issue by RexHuang** [apache/apisix-dashboard#2505]
### Issue description

Want to redirect user-agent with MS Edge browser. but not working.

### Expected behavior

should redirect when user-agent HAS Edg. 

### How to Reproduce

settings:
{
"uri": "/*",
"name": "test",
"methods": [
"GET",
"POST",
"PUT",
"DELETE",
"PATCH",
"HEAD",
"OPTIONS",
"CONNECT",
"TRACE"
],
"vars": [
[
"user-agent",
"HAS",
"Edg"
]
],
"plugins": {
"proxy-rewrite": {
"host": "x.x.x.x:3000"
}
},
"upstream": {
"nodes": [
{
"host": "x.x.x.x",
"port": 3000,
"weight": 1
}
],
"timeout": {
"connect": 6,
"send": 6,
"read": 6
},
"type": "roundrobin",
"scheme": "http",
"pass_host": "pass",
"keepalive_pool": {
"idle_timeout": 60,
"requests": 1000,
"size": 320
}
},
"status": 1
}

### Environment

- apisix version (cmd: `apisix version`):apisix:2.13.0-alpine
- OS (cmd: `uname -a`):CentOS Linux 7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`): etcd:3.4.15
- apisix-dashboard version, if have: 2.10.1-alpine
- Browser version, if have:

image: apache/apisix-dashboard:2.10.1-alpine
image: apache/apisix:2.13.0-alpine
image: bitnami/etcd:3.4.15

**Comment by bzp2010** [comment]
@RexHuang 

1. APISIX does not have the variable `user-agent`, so you cannot use it as a key. If you need to use the UA value, you need to get it through the http header, it can get the http_user_agent this way.
2. APISIX's advanced matching does not support checking substring operators. 
- `has` is used to check whether the left table contains the right element
- `in` is used to check whether the left value is contained in the right table; neither of them is an operator for checking substrings
3. If you need to use this function, you can use the `filter_func` parameter in the route to check it using custom Lua code. https://apisix.apache.org/docs/apisix/admin-api#request-body-parameters

**Comment by RexHuang** [comment]
> @RexHuang
> 
> 1. APISIX does not have the variable `user-agent`, so you cannot use it as a key. If you need to use the UA value, you need to get it through the http header, it can get the http_user_agent this way.
> 2. APISIX's advanced matching does not support checking substring operators.
> 
> * `has` is used to check whether the left table contains the right element
> * `in` is used to check whether the left value is contained in the right table; neither of them is an operator for checking substrings
> 
> 3. If you need to use this function, you can use the `filter_func` parameter in the route to check it using custom Lua code. However, it should be noted that dashboard does not support this configuration now, you need to configure it by hand using the code editor in dashboard or through the APISIX Admin API. https://apisix.apache.org/docs/apisix/admin-api#request-body-parameters

Thanks, is it any simple way to check sub-string, such as regular expression？

**Comment by bzp2010** [comment]
> Thanks, is it any simple way to check sub-string, such as regular expression？

@RexHuang Yes, use `~~`.

![image](https://user-images.githubusercontent.com/8078418/178145998-a8ea2bb2-fe75-47ca-b33c-d48be3c5fd14.png)

**Comment by RexHuang** [comment]
> > Thanks, is it any simple way to check sub-string, such as regular expression？
> 
> @RexHuang Yes, use `~~`.
> 
> ![image](https://user-images.githubusercontent.com/8078418/178145998-a8ea2bb2-fe75-47ca-b33c-d48be3c5fd14.png)

Yes, it works.
Thanks bzp2010!
