### ISSUE TITLE
upload cert file error

### ISSUE THREAD

**Issue by RexHuang** [apache/apisix-dashboard#2510]
### Issue description

upload cert.pem, key.perm in dashboard failed.
files in attach zip file.

### Expected behavior

want to upload cert.pem, key.perm in dashboard

### How to Reproduce

upload self sign cert.pem, key.perm (these file can work as https server)
when submit, I got the following error:
Request Error Code: 10000
schema validate failed: snis: Invalid type. Expected: array, given: null

### Screenshots

![image](https://user-images.githubusercontent.com/4577710/178402168-5efdd9be-c22d-4123-9153-cc4e5c325d35.png)

### Environment

apisix version (cmd: apisix version):apisix:2.13.0-alpine
OS (cmd: uname -a):CentOS Linux 7
OpenResty / Nginx version (cmd: nginx -V or openresty -V):
etcd version, if have (cmd: run etcd --version): etcd:3.4.15
apisix-dashboard version, if have: 2.10.1-alpine
Browser version, if have:

image: apache/apisix-dashboard:2.10.1-alpine
image: apache/apisix:2.13.0-alpine
image: bitnami/etcd:3.4.15

### Additional context

[files.zip](https://github.com/apache/apisix-dashboard/files/9089202/files.zip)

**Comment by bzp2010** [comment]
@RexHuang 

After checking, your domain is not configured with a domain name, including the user and its optional name.\

![311de75178399afba65b2d94b892ab1](https://user-images.githubusercontent.com/8078418/178403420-e921040a-0e6d-4882-a3ad-abff52f7dfba.png)

![9b8136994ba9bec41de5ddc54c91103](https://user-images.githubusercontent.com/8078418/178403436-0d06ca41-17b7-4c24-a891-480e591822b2.png)

**Comment by RexHuang** [comment]
Thanks bzp2010, it has been solved.
