### ISSUE TITLE
After add 'Advanced Routing Matching Conditions' of a route,it will appears nothing

### ISSUE THREAD

**Issue by iori0758** [apache/apisix-dashboard#2524]
### Issue description

i want add some routing matching conditions,but it doesn't work, after click confirm button, it displays white page

### Expected behavior

save routing matching condition succesfuly

### How to Reproduce

1.Go to Route.
2.Configure a Route Record
3.At the Stage "Define API Request", click "Add" which below section "Advanced Routing Matching Conditions" 
4. Create Rule, 
     "Parameter Position": "Cookie", 
     "Parameter Name":"p-u-c", 
     "Operational Character":"Euqal(==)",
     "Parameter Value": "21401"  ,and click Confirm
5.it display white page

### Screenshots

![VeryCapture_20220714161339](https://user-images.githubusercontent.com/3361962/179125646-4d157b59-6862-405c-9d7a-2ed71388c792.gif)

### Environment

- apisix version (cmd: `apisix version`):2.14.1
- OS (cmd: `uname -a`):CentOS Linux release 7.8.2003 (Core)
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.21.4.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled

- etcd version, if have (cmd: run `etcd --version`): 3.5.4
- apisix-dashboard version, if have: 2.13
- Browser version, if have: Google Chrome 版本 102.0.5005.115（正式版本） （64 位）

**Comment by Baoyuantop** [comment]
It has been fixed in https://github.com/apache/apisix-dashboard/pull/2440
