### ISSUE TITLE
Build apisix dashboard on termux

### ISSUE THREAD

**Issue by ghost** [apache/apisix-dashboard#2541]
### Issue description

~/apisix-dashboard $ make build
api/build.sh && cd ./web && export CYPRESS_INSTALL_BINARY=0  && yarn install --ignore-scripts && yarn build  && mkdir -p ../output/logs
+ export ENV=local
+ ENV=local
++ pwd
+ pwd=/data/data/com.termux/files/home/apisix-dashboard
+ rm -rf output
+ mkdir -p output/conf
+ mkdir -p output/dag-to-lua
+ [[ ! -f dag-to-lua-1.1/lib/dag-to-lua.lua ]]
+ wget https://github.com/api7/dag-to-lua/archive/v1.1.tar.gz -P /tmp
--2022-07-25 20:13:24--  https://github.com/api7/dag-to-lua/archive/v1.1.tar.gz
Resolving github.com... 20.205.243.166
Connecting to github.com|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/api7/dag-to-lua/tar.gz/refs/tags/v1.1 [following]
--2022-07-25 20:13:26--  https://codeload.github.com/api7/dag-to-lua/tar.gz/refs/tags/v1.1
Resolving codeload.github.com... 20.205.243.165
Connecting to codeload.github.com|20.205.243.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
/tmp: Read-only file system
/tmp/v1.1.tar.gz: No such file or directory

Cannot write to ‘/tmp/v1.1.tar.gz’ (Success).
make: *** [Makefile:39: build] Error 3

### Expected behavior

Pass

### How to Reproduce

Make build

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by SkyeYoung** [comment]
Hi, I think building with Termux is not a common requirement in production environments. But I think you can submit code for us if you want.
