### ISSUE TITLE
test:  adding route batch deleted function test cases

### ISSUE THREAD

**Issue by FangSen9000** [apache/apisix-dashboard#2562]
# Feature request

## Please describe your feature

In the routing page, there is a batch deletion function that will be launched soon. We need to add test cases to cover it

## Additional context
Specific details can be seen here：
https://github.com/apache/apisix-dashboard/pull/2502
[批量删除.webm](https://user-images.githubusercontent.com/72308243/180745383-d0b5e450-5d33-44ac-a5a7-c49e5d9b4cb3.webm)
![image](https://user-images.githubusercontent.com/72308243/182059334-65beb1b6-23aa-40ee-9cc1-f0ebad16f5f1.png)

**Comment by zfkube0x1** [comment]
Hi @FangSen9000 https://github.com/FangSen9000/apisix-dashboard/pull/3

**Comment by FangSen9000** [comment]
> Hi @FangSen9000 [FangSen9000#3](https://github.com/FangSen9000/apisix-dashboard/pull/3)
Hi, what's going on

**Comment by FangSen9000** [comment]
> Hi @FangSen9000 [FangSen9000#3](https://github.com/FangSen9000/apisix-dashboard/pull/3)
I think you have opened a pr. do you want me to submit it on that or do you want to write it

**Comment by FangSen9000** [comment]
My god, is this finished? amazing! @zfkube0x1

**Comment by FangSen9000** [comment]
@zfkube0x1   Hey, brothers, the batch deletion function has been merged. You can directly open a PR submission for the tested code
