### ISSUE TITLE
The drawer component cannot delete plugins

### ISSUE THREAD

**Issue by Morakes** [apache/apisix-dashboard#2572]
### Issue description

The plugin drawer component could not remove the enable plugin.

### Expected behavior

When the user clicks the delete button in the drawer component, the plugin should be deleted correctly

### How to Reproduce

pass

### Screenshots

![22f485cdc906a25f9b0168c334e2775](https://user-images.githubusercontent.com/74828385/183248650-d2b61afc-efc8-4e5e-adf5-168cb61e0b4f.jpg)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by 1328735450** [comment]
I will try to solve this problem

**Comment by Baoyuantop** [comment]
Hi @Morakes, Could you please describe the steps to reproduce in more detail? I can't reproduce this problem.

**Comment by Morakes** [comment]
1. In the plug-in market page, click on the editable plug-ins.
2. Click the delete button on the drawer to delete the plug-in, but the plug-in is not deleted, it still exists.
