### ISSUE TITLE
Why is there still this problem,grafana cannot be displayed

### ISSUE THREAD

**Issue by yigeqiji** [apache/apisix-dashboard#2586]
### Issue description

Why is there still this problem,grafana cannot be displayed

### Expected behavior

normal

### How to Reproduce

![image](https://user-images.githubusercontent.com/59365443/184277115-feab8843-a4a8-41f4-bab2-44b4ffa90c08.png)

### Screenshots

![image](https://user-images.githubusercontent.com/59365443/184277023-f3941fec-bde7-4b0e-96b9-0f911fca1c0e.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by yigeqiji** [comment]
I tried to change this configuration, but it has no effect

x_frame_options: "sameorigin"

**Comment by pixeldin** [comment]
Hi, @yigeqiji, this maybe help, update the `allow_embedding` config item as `true` in your Grafana configuration file and restart Grafana server.
```
# security
# set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>. default is false.
allow_embedding = true
```

**Comment by sangnguyen7** [comment]
I also getting the same issue, even though set
```
# security
# ...
# set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>. default is false.
allow_embedding = true
```

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/4648887/185229001-f5bdb75a-25e2-458d-9cdd-c823a16f6d50.png">

**Comment by guoqqqi** [comment]
hello @yigeqiji The cause is due to the CSP (content-security-policy) and I think we can run the embed to fix it

**Comment by guoqqqi** [comment]
You can configure `frame-src *` to allow all frame

**Comment by trungtien** [comment]
> You can configure `frame-src *` to allow all frame

it's now working bro :) still the same issues

content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; st
yle-src 'self' 'unsafe-inline'; frame-src *"

**Comment by xiaolei000129** [comment]
Have you solved the prolem?

**Comment by trungtien** [comment]
security:
    access_control_allow_credentials: true 
    access_control_allow_headers: "Authorization"
    access_control-allow_methods: "*"
    x_frame_options: "allow-from *"
    content_security_policy: "frame-src *;"

**Comment by trungtien** [comment]
> Have you solved the prolem?
it'w work for me, add some lines in conf.yaml
  security:
    access_control_allow_credentials: true          # support using custom cors configration
    access_control_allow_headers: "Authorization"
    access_control-allow_methods: "*"
    x_frame_options: "allow-from *"
    content_security_policy: "frame-src *;"

**Comment by xiaolei000129** [comment]
> > 你解决问题了吗？
> > 它对我有用，在 conf.yaml 中添加一些行
> > security: access_control_allow_credentials 
> > : true # support using custom cors configration access_control_allow_headers 
> > : "Authorization" 
> > access_control-allow_methods: "*" 
> > x_frame_options: "allow-from *" 
> > content_security_policy: " frame-源 *;"
Have you solved the prolem?

**Comment by trungtien** [comment]
![image](https://user-images.githubusercontent.com/16741935/189865069-8208539f-8613-488f-ae40-9d30d95c8613.png)
yep,

**Comment by xiaolei000129** [comment]
> ![image](https://user-images.githubusercontent.com/16741935/189865069-8208539f-8613-488f-ae40-9d30d95c8613.png) yep,

是用你上面的配置吗？

**Comment by trungtien** [comment]
> > ![image](https://user-images.githubusercontent.com/16741935/189865069-8208539f-8613-488f-ae40-9d30d95c8613.png) yep,
> 
> 是用你上面的配置吗？

![image](https://user-images.githubusercontent.com/16741935/189947761-40b95362-7745-4ccc-9fc7-3732e89ad3c1.png)

**Comment by lucamaf** [comment]
not documented, facing the same bug

**Comment by LiberiFatali** [comment]
solved after following steps here

**Comment by freemankevin** [comment]
```shell
[root@apisix example]# vim  ./dashboard_conf/conf.yaml
...
  #### csp for grafana ui
  max_cpu: 0             # supports tweaking with the number of OS threads are going to be used for parallelism. Default value: 0 [will use max number of available cpu cores considering hyperthreading (if any)]. If the value is negative, is will not touch the existing parallelism profile.
  security:
    #ccess_control_allow_origin: "http://httpbin.org"
    access_control_allow_credentials: true          # support using custom cors configration
    access_control_allow_headers: "Authorization"
    access_control-allow_methods: "*"
    x_frame_options: "allow-from *"
    content_security_policy: "frame-src *"  # You can set frame-src to provide content for your grafana panel.

[root@apisix example]# docker restart example-apisix-dashboard-1


```
problem solved.


![image](https://user-images.githubusercontent.com/71524776/209631611-b4f00b21-25b3-4025-83fd-c27f3e92a400.png)
![image](https://user-images.githubusercontent.com/71524776/209631712-ca82029e-0b92-4a9b-8c8d-deb4bfd87bb6.png)
