### ISSUE TITLE
When duplicate a Route on Dashboard web, it has the SAME id and cannot edit, so failed to submit at last step

### ISSUE THREAD

**Issue by 81981266** [apache/apisix-dashboard#2598]
### Issue description

When duplicate a Route on Dashboard web, it has the SAME id and cannot edit, so failed to submit at last step

### Expected behavior

id for duplicated route is changeable

### How to Reproduce

click 'Duplicate' button on 'Dashboard web - Route'.

The id shown at the last step can not edit and have conflict.

### Screenshots

<img width="203" alt="image" src="https://user-images.githubusercontent.com/36359920/185726827-8c3be797-3b5f-4844-b4f5-baa843d063db.png">
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/36359920/185726853-dbf50a9a-0247-4cd8-b406-5f6843e4c5a7.png">

**Comment by SkyeYoung** [comment]
In fact, this issue has been fixed in the master branch by https://github.com/apache/apisix-dashboard/pull/2501, but we have not yet released a new version. If you are in a hurry, you can download and compile the master version yourself. 😊

**Comment by SkyeYoung** [comment]
> In fact, this issue has been fixed in the master branch by #2501, but we have not yet released a new version. If you are in a hurry, you can download and compile the master version yourself. 😊

@81981266 

cc @bzp2010
