### ISSUE TITLE
BUG: Rendering exception and timeout

### ISSUE THREAD

**Issue by FangSen9000** [apache/apisix-dashboard#2605]
### Issue description

**This is most likely the reason why the front-end E2E test always loses an element and fails immediately after cy.login**

When we enter the dashboard panel for the first time, there will be a random page that **cannot be loaded**, which has nothing to This is most likely the reason why the front-end E2E test always loses an element and fails immediately after cy.logindo with the waiting time.

### Expected behavior

No matter which page we click, it **should be loaded immediately** instead of always. It can only be solved by refreshing the browser！

### How to Reproduce

1. Find the reason for rendering and improve the situation
2. Let E2E refresh the browser after logging in. I think it will greatly **improve the stability of E2E**

### Screenshots

![image](https://user-images.githubusercontent.com/72308243/186552049-59459ab8-c674-40bd-a5cb-d87464960742.png)
This is most likely the reason why the front-end E2E test always loses an element and fails immediately after cy.login

[dashboard丢失元素原因.webm](https://user-images.githubusercontent.com/72308243/186551737-5bd6d7e2-bf54-4919-bbff-7b95d4451fa4.webm)

### Environment

- apisix version (cmd: `apisix version`): 2022.8.25's lastest

cmd: `yarn start/ yarn start: dev/  pnpm start: dev`

- Browser version, if have: Chrome

**Comment by FangSen9000** [comment]
https://github.com/apache/apisix-dashboard/issues/2613 这个人也有相同情况

**Comment by Baoyuantop** [comment]
If there is still a problem, please open it again.
