### ISSUE TITLE
无法使用高级匹配条件创建路由

### ISSUE THREAD

**Issue by Someant** [apache/apisix-dashboard#2609]
### Issue description

会出现JS报错
![image](https://user-images.githubusercontent.com/4363184/187440374-1649adb0-2a58-4a3b-8573-13faa53de1eb.png)

### Expected behavior

无法使用高级匹配条件创建路由

### How to Reproduce

![image](https://user-images.githubusercontent.com/4363184/187440660-6f8c3e06-35a7-449d-80f4-28c9554bceda.png)
创建任意规则后即可触发

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by Baoyuantop** [comment]
Please provide your apisix-dashboard  version, we have fixed it in https://github.com/apache/apisix-dashboard/pull/2440

**Comment by Someant** [comment]
@Baoyuantop 2.13.0

**Comment by pan003** [comment]
我也遇到这个问题了，这么低级的bug，这功能明显就是没有测试过啊

**Comment by Baoyuantop** [comment]
> @Baoyuantop 2.13.0

I verified using the master code and did not find this problem, need to wait for a new release. cc @bzp2010

**Comment by Baoyuantop** [comment]
> 我也遇到这个问题了，这么低级的bug，这功能明显就是没有测试过啊

We have the corresponding E2E automated test coverage for each feature and bug fix. For this bug you can refer to 
https://github.com/apache/apisix-dashboard/blob/master/web/cypress/e2e/route/can-skip-upstream-when-select-service-id.cy.js#L135

**Comment by pan003** [comment]
版本更新太慢了啊，还没有发新版本么

**Comment by jeffreys-cat** [comment]
I have the same problem

**Comment by jevonsnotes** [comment]
一样的问题，怎么解决？
已用v2.13.0

**Comment by jevonsnotes** [comment]
> 一样的问题，怎么解决？ 已用v2.13.0

@Baoyuantop

**Comment by SkyeYoung** [comment]
@jevonsnotes You can try compiling it yourself using master. For some reason, there is no new official release yet. Maybe you can come and help us with a new release.

**Comment by ipanocloud** [comment]
me too, dashboard version 2.13.0

**Comment by luohoufa** [comment]
我用的是rpm方式安装的2.13.0版本，还是存在这个问题， 几时发rpm新版本解决这个问题？

**Comment by 113998274** [comment]
有旧版本没有这问题吗？

**Comment by Baoyuantop** [comment]
2.13.1 is being released: https://lists.apache.org/thread/r8k7t7nxf2tb0tkqvsbj50zy4cnqmrd0

**Comment by LiteSun** [comment]
2.13.1 is being released. Feel free to reopen it if you still have the same problem.
