### ISSUE TITLE
chrome 浏览器无限loading

### ISSUE THREAD

**Issue by gaoconggit** [apache/apisix-dashboard#2613]
### Issue description

chrome 浏览器偶尔不停 loading , 单独看响应是正常的

火狐浏览器正常

### Expected behavior

不要不停loading 

### How to Reproduce

![image](https://user-images.githubusercontent.com/10905068/189101400-b6b76b6f-0d7c-43f2-9cdb-ca9c5dceb3b3.png)
点了上游 点服务

### Environment

- apisix 2.15.0
- OS win10
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd 3.5.0
- apisix-dashboard version 2.13.0
- Browser version  chrome 105.0.5195.102 x64

**Comment by gaoconggit** [comment]
![image](https://user-images.githubusercontent.com/10905068/189102351-c2f10a33-15c3-44bb-a7ae-33f03fcc47fd.png)

**Comment by gaoconggit** [comment]
http://20.210.250.99:9000 也可以重现

**Comment by FangSen9000** [comment]
你这个和我发现的是一样的，https://github.com/apache/apisix-dashboard/issues/2605

**Comment by FangSen9000** [comment]
> 你能提供开发者面板的网络截图@FangSen9000@gaoconggit

![image](https://user-images.githubusercontent.com/72308243/191641073-de71c74b-a2ff-4de4-9b67-d67d31cb8554.png)
https://github.com/apache/apisix-dashboard/issues/2605
这里有一个视频
@encanto-oss
