### ISSUE TITLE
It's funny that APISIX can't route it's own dashboard web app correctly!

### ISSUE THREAD

**Issue by FullStackPlayer** [apache/apisix-dashboard#2614]
### Issue description

I have successfully installed APISIX family and it worked!
---------------------------
apisix：2.15
apisix-dashboard：2.13
etcd：3.4.15
---------------------------
I was able to access apisix-dashboard via http://ip:9000, but that's not elegent enough, it deserves a sub domain, so i created a new route which matches a sub domain for apisix-dashboard itself, but i failed!
Login page loaded successfully, but with errors appeared in console, as you can see below:
![image](https://user-images.githubusercontent.com/77406496/189128171-a97158d0-0a14-4cae-83e0-0e45d3872859.png)
BTW: these two errors always appeared, even when i visited it via ip, but that would not interrupt my login progress anyway.
Once i tried to login with my account/password, it gave me a 401 error:
```
Request Method: POST
Status Code: 401 
Remote Address: x.x.x.x:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-origin: *
access-control-expose-headers: *
access-control-max-age: 3600
content-type: application/json
date: Thu, 08 Sep 2022 12:43:13 GMT
server: APISIX/2.15.0
```
I did think about the possibility that i made some mistakes, but creating a route for another app just worked well.
So i thought this should be reported.

### Expected behavior

No CSP issues, no 401s, i just want it works.

### How to Reproduce

Just do it as what i described.

### Environment

- apisix version (cmd: `apisix version`): 2.15
- OS (cmd: `uname -a`): Ubuntu 20.04
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`): 3.4.15
- apisix-dashboard version, if have: 2.13
- Browser version, if have: Chromium build 98.0.4758.102

**Comment by bzp2010** [comment]
It would be better if you could read the documentation. https://apisix.apache.org/docs/apisix/FAQ/#how-do-i-access-the-apisix-dashboard-through-apache-apisix-proxy

**Comment by FullStackPlayer** [comment]
> 

Thanks for your reply!
I think the main point is an individual admin port, i changed it and now everything seems ok.
