### ISSUE TITLE
CI failing in latest master branch

### ISSUE THREAD

**Issue by butterfly1924** [apache/apisix-dashboard#2615]
### Issue description

The CI is failing

### Expected behavior

...

### How to Reproduce

...

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by FangSen9000** [comment]
Please close this @butterfly1924
