### ISSUE TITLE
[feat]: Adding a Loading state to buttons

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-dashboard#2625]
# Feature request

## Please describe your feature

Currently, no limit is added to the buttons on all request interfaces. If the user has a poor network environment, there may be a situation where the create button is clicked multiple times in a row.

## Describe the solution you'd like

Add a global custom Hook to change the state of the button to Loading when clicking on a button in the Create, Submit, Delete etc. category and restore the state when the request interface is successful.

**Comment by guoqqqi** [comment]
Hello, @Silence-dream Can you help support this feature?

**Comment by Silence-dream** [comment]
> Hello, @Silence-dream Can you help support this feature?

I will create a pr to complete it
