### ISSUE TITLE
Action CI:Release Test 不支持1.15以上版本编译

### ISSUE THREAD

**Issue by yoyofx** [apache/apisix-dashboard#2626]
### Issue description

其它CI Action都是1.18的编译,导致目前修改后端代码编译不过

### Expected behavior

需要修改 action 中的 Release_Test.yml 目前无法提交

### How to Reproduce

-

### Environment

- apisix version 2.13:
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by bzp2010** [comment]
Fixed
