### ISSUE TITLE
Upload certificate path error

### ISSUE THREAD

**Issue by solid-wang** [apache/apisix-dashboard#2628]
### Issue description

apisix errer.log:
radixtree_sni.lua:146: match_and_set(): failed to find any SSL certificate by SNI

### Expected behavior

The ssl uploaded through the dashboard is stored in the /apisix/ssl/ path of etcd, but actually needs to be placed in the /apisix/ssls/ path.

### How to Reproduce

Upload the certificate through the dashboard and configure the route. Visit your site.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by C2022021** [comment]
what's your apisixand dashboard version?

**Comment by kwanhur** [comment]
I faced the same issue :-(

dashboard version 2.13.0 and commit hash 7543860

**Comment by panhow** [comment]
i face the Same promblem

**Comment by ChaojuWang** [comment]
Same promblem here. My apisix image version is "apache/apisix:2.99.0-debian" baseed on the compose file from https://github.com/apache/apisix-docker/blob/master/example/docker-compose.yml

**Comment by kwanhur** [comment]
> Same promblem here. My apisix image version is "apache/apisix:2.99.0-debian" baseed on the compose file from https://github.com/apache/apisix-docker/blob/master/example/docker-compose.yml
> 
> Problem is solved since I downgrade apisix image to 2.13. @panhow @kwanhur @solid-wang

thanks for your notification.

**Comment by Baoyuantop** [comment]
Fixed in dashboard 3.0.0. If there is still a problem, please open it again.
