### ISSUE TITLE
help: can't install using docker

### ISSUE THREAD

**Issue by Cheol-Soon-Choi** [apache/apisix-dashboard#2640]
### Issue description

I tried to install according to the referenced documentation(https://apisix.apache.org/docs/dashboard/install/), but it failed.
Is there something wrong with my configuration environment or step?

### Expected behavior

docker run dashboard

### How to Reproduce

doc: https://apisix.apache.org/docs/dashboard/install/

1. docker pull apache/apisix-dashboard:2.13-alpine
2. docker run -d --name dashboard \
           -p 9000:9000        \
           -v my_config_path:/usr/local/apisix-dashboard/conf/conf.yaml \
           apache/apisix-dashboard

### Screenshots

<img width="665" alt="스크린샷 2022-10-14 오전 11 42 09" src="https://user-images.githubusercontent.com/79562672/195752146-993755a6-3c6a-4064-b731-b2e7a086cfa4.png">

### Environment

- apisix version (cmd: `apisix version`): 2.15.0
- OS (cmd: `uname -a`): ubuntu
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.21.4.1
- etcd version, if have (cmd: run `etcd --version`): 3.4.18
- apisix-dashboard version, if have: 2.13
- Browser version, if have:

**Comment by Baoyuantop** [comment]
Hi @Cheol-Soon-Choi, can you share your configuration file? Also, make sure that your etcd is appropriately available.

**Comment by Cheol-Soon-Choi** [comment]
> Hi @Cheol-Soon-Choi, can you share your configuration file? Also, make sure that your etcd is appropriately available.

my confing.yaml :
conf:
  listen:
    host: 0.0.0.0
    port: 9000
  allow_list:
    - 0.0.0.0/0

etcd :
![스크린샷 2022-10-17 오전 11 59 48](https://user-images.githubusercontent.com/79562672/196080001-babaf669-e1b5-41d8-969b-d5cf9157611e.png)

1. Do I need to override all items by referring to default-config? I understand that it is enough to override only the parts that need customization.
2. Should I additionally check etcd? (if yes, how?)

Since I am a newbie, I would be very grateful if you could explain it in an easy way.
Thank you in advance.
@Baoyuantop

**Comment by Cheol-Soon-Choi** [comment]
> Do you mean the apisix configuration file? If yes, define only what you need. What you don't have will use the default configuration. You can refer to https://apisix.apache.org/docs/apisix/installation-guide/#configuring-apisix

i mean my dashboard config file, not apisix config file.
I created my config file.yaml by referring to this file(https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml)
Do I have to write everything to my dashboard config file like a reference file?
or can I write only the necessary parts like the apisix config file?

> It would help if you ensured that the etcd address is configured in the conf.yaml file of apisix-dashboard is available, is your etcd also deployed using docker?

For etcd, I just installed it according to doc(https://apisix.apache.org/docs/apisix/installation-guide/). Not docker.
Do I need to take further action?

**Comment by Cheol-Soon-Choi** [comment]
Finally, I implemented my dashboard-config file. Please review.
I configured my dashboard config file by referring to this file(https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml)

@Baoyuantop
Thanks!

conf:
  listen:
    host: 0.0.0.0
    port: 9000
  allow_list:
    - 0.0.0.0/0

  etcd:
    endpoints:
      - "127.0.0.1:2379"
    mtls:
      key_file: ""
      cert_file: ""
      ca_file: ""

  log:
    error_log:
      level: warn
      file_path:
        logs/error.log
    access_log:
      file_path:
        logs/access.log

  security:
    content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src * 'self' data: https:;"

authentication:
  secret:
    secret

  expire_time: 3600
  users:
    - username: admin
      password: admin
    - username: user
      password: user

plugins:
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  # - dubbo-proxy
  - echo
  # - error-log-logger
  # - example-plugin
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  # - log-rotate
  # - node-status
  - openid-connect
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  # - skywalking
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - server-info
  - traffic-split

**Comment by Baoyuantop** [comment]
It looks like because your apisix-dashboard is running in docker and etcd is running in the host, the containers in docker and the server in the host cannot use 127.0.0.1:2379 communication directly. You need to solve this problem by searching.
You can also try using https://github.com/apache/apisix-docker/tree/master/example to launch all components quickly.

**Comment by LiteSun** [comment]
Feeling free to reopen if you still have the problem.
