### ISSUE TITLE
bug: Manual configuration is selected when the dashboard routing configuration plugin is clicked, and there is no plugin_config_id node in the routing information after clicking submit

### ISSUE THREAD

**Issue by ipanocloud** [apache/apisix-dashboard#2648]
### Current Behavior

dashboad create route and manual select plugin config

### Steps to Reproduce

1.create route
2.manual select plugin config
3.submit

### Environment

- APISIX version (run `apisix version`):
2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
3.5.0
- APISIX Dashboard version, if relevant:
2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
`
{
  "uri": "/map-service/api/*",
  "name": "out-route-map-service",
  "desc": "地图路由",
  "methods": [
    "GET",
    "POST"
  ],
  "hosts": [
    "www.test.com"
  ],
  "service_id": "409256655683847112",
  "labels": {
    "API_VERSION": "V1",
    "Out": "MapService"
  },
  "status": 1
}
`

**Comment by hf400159** [comment]
hi, @ipanocloud I reproduced this problem. @bzp2010 Can you help me? This problem also exists in the latest version.

![image](https://user-images.githubusercontent.com/97138894/198959006-70aaea0b-2581-49a9-8b05-23f43aeae436.png)

reproduced steps:
1. create service.
2. create Plugin-Config
3. create routes. And use the service and plugin template you just created.
4. View routing configuration, no plugin_config_id.

**Comment by bzp2010** [comment]
Confirm, I will check it.
