### ISSUE TITLE
The node field is lost after the apisix-dashboard submission

### ISSUE THREAD

**Issue by Bigwen-1** [apache/apisix-dashboard#2661]
### Issue description

I added a service or upstream through the admin api and assigned node's metadata, but the metadata information was lost after I modified it through apisix-dashboard

Original etcd information：
/apisix/services/00000000000000046995
{"enable_websocket":true,"create_time":1668145810,"name":"push-user service2","id":"00000000000000046995","update_time":1668145810,"upstream":{"hash_on":"vars","scheme":"http","type":"roundrobin","nodes":[{"port":8080,"weight":100,"metadata":{"xq_lane":"sep_lane"},"host":"127.0.0.1","priority":0},{"port":8080,"weight":100,"metadata":{"xq_lane":"sep_push"},"host":"192.168.12.8","priority":0}],"pass_host":"pass"}}

Etcd information after changing the service name：
/apisix/services/00000000000000046995
{"id":"00000000000000046995","create_time":1668145810,"update_time":1668145968,"name":"push-user service2","upstream":{"nodes":{"127.0.0.1:8080":100,"192.168.12.8:8080":100},"timeout":{"connect":6,"send":6,"read":6},"type":"roundrobin","scheme":"http","pass_host":"pass","keepalive_pool":{"idle_timeout":60,"requests":1000,"size":320}}}

### Expected behavior

Retain node metadata information

### How to Reproduce

...

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by Baoyuantop** [comment]
Hi @Bigwen-1, please provide information about the version you are using.

**Comment by Baoyuantop** [comment]
The dashboard does not recognize the metadata field in nodes.
