### ISSUE TITLE
SSL certificates upload by dashboard not working

### ISSUE THREAD

**Issue by NATHAN76543217** [apache/apisix-dashboard#2664]
### Issue description

SSL certificates uploaded by the dashboard are not visible / not pushed in the admin API.

### Expected behavior

We expect that certificates uploaded from the dashboard are available and in APISIX and visible from the admin API.

### How to Reproduce

0. Enable SSL on APISIX configuration and restart. 
1. Go to dashboard, on the SSL page.
2. Click on create
3. Create your certificate and upload it.
4. On browser, we still have a certificate error
5. Make a request to the admin API (http://host:port/apisix/admin/ssls)
6. Observe that no certificates are available.

### Screenshots

![image](https://user-images.githubusercontent.com/58692289/201935559-27d22464-a750-4dbb-b32a-06e373157212.png)

![image](https://user-images.githubusercontent.com/58692289/201936931-25e08d01-0335-4c15-8fca-9f79d7ddc2e4.png)

### Environment

- apisix version (cmd: `apisix version`): **3.0.0 (apache/apisix:3.0.0-debian )**
- OS (cmd: `uname -a`): **Linux 5.10.102.1-microsoft-standard-WSL2**
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  the image **nginx:1.19.0-alpine** 
- etcd version, if have (cmd: run `etcd --version`):  **bitnami/etcd:3.4.15**
- apisix-dashboard version, if have: **2.13.0 (apache/apisix-dashboard:2.13-alpine)**
- Browser version, if have: **Edge (Version 107.0.1418.42 (Version officielle) (64 bits))**

### Additional context

Certificates uploaded by a PUT request on the admin API are visible and usable (first screenshot) and also visible on the dashboard but certificates uploaded from the dashboard are visible on the dashboard (second screenshot) but not in the admin API.

**Comment by mscb402** [comment]
What your apisix version is?

**Comment by mscb402** [comment]
The apisix-dashboard currently does not support apisix 3.0.
Apisix 3.0 current change `/apisix/admin/ssl/{id}` to `/apisix/admin/ssls/{id}`. But the old version apisix-dashboard still upload the certificate to /apisix/admin/ssl/. So you can get a certificate from etcd but can't get one from APIs

**Comment by NATHAN76543217** [comment]
Oh okay, thank you. Do you know if it is planed for apisix-dashboard to support apisix 3.0.0?

**Comment by mscb402** [comment]
It's already being planned

**Comment by Baoyuantop** [comment]
fixed in https://github.com/apache/apisix-dashboard/pull/2693
