### ISSUE TITLE
help request: Plugin enable

### ISSUE THREAD

**Issue by ynsdl** [apache/apisix-dashboard#2666]
### Description

I have added some plugin conf.yaml which in under apisix-docker/example/dashboard_conf but I cant see them on apisix dashboard under plugin/list

For example 
  - server-info
  - log-rotate
 

plugins:                          # plugin list (sorted in alphabetical order)
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  - echo
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  - log-rotate
  - openid-connect
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - server-info
  - traffic-split
  - workflow

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): Linux apisix01 3.10.0-693.el7.x86_64 apache/apisix#1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
@bzp2010 I remember some plugins don't show on dashboard? For example log-rotate.

**Comment by ynsdl** [comment]
Thank you.
