### ISSUE TITLE
配置完grafana地址后，首页面板提示：该内容被屏蔽了。请联系网站所有者以解决此问题。 

### ISSUE THREAD

**Issue by yntx-it** [apache/apisix-dashboard#2670]
### Issue description

配置完grafana地址后，首页面板提示：该内容被屏蔽了。请联系网站所有者以解决此问题。 
![image](https://user-images.githubusercontent.com/118282164/203939226-332a9bc9-a3bf-4bd8-aa49-62b7f005a034.png)

### Expected behavior

请问如何解决哇

### How to Reproduce

1.配置Grafana 地址：http://192.168.182.102:3000/d/bLlNuRLWz/apache-apisix?orgId=1&refresh=5s&from=1669363933397&to=1669365733397&var-DS_PROMETHEUS=apisix&var-service=All&var-route=All&var-instance=All&var-consumer=All&var-node=All
2.回到首页

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by zyhui98** [comment]
我也遇到了。

**Comment by yntx-it** [comment]
@SkyeYoung Thank you very mach, i'll try.
