### ISSUE TITLE
Source-based installation fails

### ISSUE THREAD

**Issue by Cheol-Soon-Choi** [apache/apisix-dashboard#2673]
### Issue description

Installing according to https://apisix.apache.org/docs/dashboard/2.13/install/#source

An error occurred in the [make build] step.

### Expected behavior

install finished

### How to Reproduce

https://apisix.apache.org/docs/dashboard/2.13/install/#source

### Screenshots

![스크린샷 2022-11-29 오전 11 07 09](https://user-images.githubusercontent.com/79562672/204420904-62ce2aba-5d3a-4c9c-ba04-cc7e185d368a.png)

### Environment

- apisix version (cmd: `apisix version`): 2.15.1
- OS (cmd: `uname -a`): Ubuntu
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.21.4.1
- etcd version, if have (cmd: run `etcd --version`): 3.5.4
- apisix-dashboard version, if have: release/2.13
- Browser version, if have:

### Additional context

Is the goscript the problem? @Baoyuantop

**Comment by ronething** [comment]
@Cheol-Soon-Choi Hi, what version of go are you using?

**Comment by Baoyuantop** [comment]
Hi @Cheol-Soon-Choi, if there are still problems, you can reopen

**Comment by zqq-nuli** [comment]
hello 
My go version is 1.16.7 but I still encountered the same error. The specific error message is as follows

error for make build

```shell
root@VM-0-15-ubuntu:/home/lighthouse/apisix-dashboard# go version
go version go1.16.7 linux/amd64
```

```error
+ go build -o ../output/manager-api -ldflags '-X github.com/apisix/manager-api/internal/utils.version=3.0.1 -X github.com/apisix/manager-api/internal/utils.gitHash=4133aa1' ./main.go
go: github.com/gin-gonic/gin@v1.9.0 requires
        github.com/kr/text@v0.2.0: missing go.sum entry; to add it:
        go mod download github.com/kr/text
+ cp ./api/conf/schema.json ./output/conf/schema.json
cp: cannot stat './api/conf/schema.json': No such file or directory
make: *** [Makefile:39: build] Error 1

```

**Comment by zqq-nuli** [comment]
> Hi @Cheol-Soon-Choi, if there are still problems, you can reopen

hello,I want your help,thanks
