### ISSUE TITLE
2.15.0版本client-control配置后显示问题

### ISSUE THREAD

**Issue by coolmingwu** [apache/apisix-dashboard#2696]
### Issue description

升级2.15.0版本后，dashboard内的client-control插件配置后显示异常，使用无问题
![image](https://user-images.githubusercontent.com/93962343/208652304-a7ae7275-f8a9-4d9a-85ae-340b2c0558e5.png)
列表页查看正常
![image](https://user-images.githubusercontent.com/93962343/208652643-749640f7-41c8-497c-8116-19d7daf7f24b.png)

### Expected behavior

升级后显示无异常

### How to Reproduce

2.13升级2.15.0后出现问题

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by zsmlinux** [comment]
情况1:
![image](https://user-images.githubusercontent.com/10682145/216930701-ed6abeba-936a-441d-8e5f-4a3852f53a96.png)

![image](https://user-images.githubusercontent.com/10682145/216930414-4f5e1436-dad1-410b-960d-b22250dc1146.png)

情况2:
![image](https://user-images.githubusercontent.com/10682145/216931084-a3647fc3-6466-4d1c-b18f-0785766b3245.png)

apisix-dashboadashboard升级3.0之后在配置模版中 `配置`-->`下一步`后，以及编辑插件时显示空白

**Comment by Baoyuantop** [comment]
It looks like a data incompatibility issue, which I need to troubleshoot carefully. Can you help create a new issue?
