### ISSUE TITLE
limit-count still on work when i disable it!

### ISSUE THREAD

**Issue by tanjiancheng** [apache/apisix-dashboard#2698]
### Issue description

limit-count still on work when i disable it,it only can back to normal only after i delete the limit-count 

### Expected behavior

limit-count when i disable it,request should be normal1

### How to Reproduce

check this,please

### Screenshots

![image](https://user-images.githubusercontent.com/7401570/209778075-98cdbfe3-f42e-40c6-b910-a1588eba52b2.png)

### Environment

- apisix (3.0.0-debian) 
- OS (Linux centos76x64cnISO1810sQPsi 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
- apisix-dashboard (2.15.0-alpine)

**Comment by bzp2010** [comment]
APISIX 3.0 is still incompatible with apisix-dashboard 2.15, especially since APISIX 3.0 has modified the plugin's disable syntax. This is a known issue.
As a temporary alternative you can use the Admin API for this operation.

**Comment by tanjiancheng** [comment]
> modified

ok，Is there any plan to support APISIX 3.0 and when?

**Comment by tanjiancheng** [comment]
> APISIX 3.0 is still incompatible with apisix-dashboard 2.15, especially since APISIX 3.0 has modified the plugin's disable syntax. This is a known issue. As a temporary alternative you can use the Admin API for this operation.

ok，Is there any plan to support APISIX 3.0 and when?

**Comment by SkyeYoung** [comment]
@tanjiancheng We will support it. I'm also trying to find time to provide code, but we still need more community members to participate. If you are interested, you are welcome to contribute code 😺 .
