### ISSUE TITLE
The download rpm apisix-dashboard-2.15.0-0.el7.x86_64.rpm package address is invalid

### ISSUE THREAD

**Issue by bluewaystar** [apache/apisix-dashboard#2699]
### Issue description

sudo yum install -y https://github.com/apache/apisix-dashboard/releases/download/v2.15.0/apisix-dashboard-2.15.0-0.el7.x86_64.rpm

Download apisix-dashboard-2.15.0-0.el7.x86_ 64.rpm rpm packet address is invalid

### Expected behavior

download success

### How to Reproduce

sudo yum install -y https://github.com/apache/apisix-dashboard/releases/download/v2.15.0/apisix-dashboard-2.15.0-0.el7.x86_64.rpm 

can not open xx.rpm

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by bzp2010** [comment]
Fixed https://github.com/apache/apisix-dashboard/releases/tag/v2.15.0

The missing resources have been uploaded.
