### ISSUE TITLE
Need an introduction to manager-api

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-dashboard#270]
Our new version of the dashboard has just been launched, and some new modules have been added, such as manager-api. I think it is necessary to explain this structure.
![image](https://user-images.githubusercontent.com/4413028/84981394-03b28380-b167-11ea-9e9d-3b2371aa68c1.png)
ref:https://github.com/apache/incubator-apisix/raw/master/doc/images/apisix.png

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/blob/master/manager-api.md

**Comment by RedemptionC** [comment]
> https://github.com/apache/apisix-dashboard/blob/master/manager-api.md

Hi,this link is invalid now(404)
what's the currently available resource for manager-api?

**Comment by juzhiyuan** [comment]
@RedemptionC Hi, all docs are under https://github.com/apache/apisix-dashboard/tree/master/docs/en/latest , but something may need update.
