### ISSUE TITLE
如何添加自定义插件

### ISSUE THREAD

**Issue by swtseaman** [apache/apisix-dashboard#2703]
已经开发好自定义插件，并且已经放到了在apisix；看文档https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/FAQ.md，说是需要执行下面的命令导出配置，再放到 dashboard

curl 127.0.0.1:9090/v1/schema > schema.json

但是上面这个命令返回404错误，是不是有什么变化

**Comment by flati31** [comment]
i had the same problem ( i was using the example from the apisix-docker repositorie ).
Switch to port 9092 fixed my problem.

curl 127.0.0.1:9092/v1/schema > schema.json

**Comment by Baoyuantop** [comment]
What is the version information you are using?

**Comment by swtseaman** [comment]
改为9092端口确实可以获取到一个  schema.json的文件，但是文件内容里搜索不到我新加的插件名称

**Comment by swtseaman** [comment]
我是把lua文件放在容器的/usr/local/apisix/apisix/plugins目录下，然后在 /usr/local/apisix/conf/config-default.yaml 里的 plugin节点增加了我的插件名称，最后重启docker
