### ISSUE TITLE
ip限制插件配置UI展示异常

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-dashboard#2707]
### Issue description

ip-restriction插件，数据可以正常的写，但是UI上无法正常展示

### Expected behavior

1、etcd已经有数据
![image](https://user-images.githubusercontent.com/7006014/211279177-1fdcd333-1e71-49f4-951c-d398b6589c46.png)

2、插件配置的id与上面etcd中的ID一致
![image](https://user-images.githubusercontent.com/7006014/211279271-c2c6e5bf-b71b-4634-9c59-cd634e54744f.png)

3、UI上无法展示
![image](https://user-images.githubusercontent.com/7006014/211279477-9526c980-d835-4a61-b173-7fac11e5426f.png)

### How to Reproduce

1、配置插件模板
![image](https://user-images.githubusercontent.com/7006014/211280716-d4f0c6b5-99f8-424f-82d5-6ebf54c9a383.png)
2、提交变更
3、查询插件配置
![image](https://user-images.githubusercontent.com/7006014/211281046-837d8e76-3f71-4cc8-be18-cd9743421c46.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: 2.15.0
- Browser version, if have:

**Comment by Baoyuantop** [comment]
Looks similar to https://github.com/apache/apisix-dashboard/issues/2696
