### ISSUE TITLE
Copy routing rule in api dashboard failure

### ISSUE THREAD

**Issue by gaoxingliang** [apache/apisix-dashboard#2711]
### Issue description

I'm using the apisix dashboard with grpc transcode plugin to route rest to grpc request. 
It failes because the id is also copied and can;t be changed.

### Expected behavior

The copy feature should work.

### How to Reproduce

1. 
![image](https://user-images.githubusercontent.com/3148215/211704707-57815b0f-11d6-41ce-a96b-7e72cdb3be8f.png)

2. when saving
![image](https://user-images.githubusercontent.com/3148215/211704799-6fdf9fdf-15d8-48b6-a70c-89e5f90ecbdc.png)

### Environment

apisix: 3.0.0
apisix dashboard: 2.13.0

**Comment by SkyeYoung** [comment]
This has been fixed in https://github.com/apache/apisix-dashboard/pull/2501, You can update your dashboard version.

At the same time, the current dashboard still does not work well with the 3.x version of APISIX. If you are interested, please help contribute code.
