### ISSUE TITLE
Configure plugin doesn't show the configured value

### ISSUE THREAD

**Issue by gaoxingliang** [apache/apisix-dashboard#2723]
### Issue description

When editing a plugin at global level, the configuration is not shown after re-edit:
![image](https://user-images.githubusercontent.com/3148215/215380721-c6c51fc8-b97b-4f87-b12f-0321f97b6cf7.png)

After checking, some plugins (eg elasticsearch-logger) support showing the configured configurations while some not (eg:file-logger, clickhouse-logger)

My version is:2.15.0

### Expected behavior

It should show the configured values.

### How to Reproduce

1. Go to the plugins and configure one.
2. here is the official online playground： http://20.210.250.99:9000/plugin/list

### Environment

- apisix version (cmd: `apisix version`): 2.15.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by Baoyuantop** [comment]
Fixed by https://github.com/apache/apisix-dashboard/pull/2718
