### ISSUE TITLE
Searching routes by hosts - FR

### ISSUE THREAD

**Issue by anldrms** [apache/apisix-dashboard#2729]
I would like to see "searching routes by host" section on apisix dashboard

In Routes section there is only searching labels Name Path and Labels. We are mostly need searching with hostname. 
Thats why i want to search it with hosts.

I will glad to help for the implementation.

**Comment by anldrms** [comment]
<img width="1570" alt="resim" src="https://user-images.githubusercontent.com/21142588/216601411-0205e527-1938-4f3e-9cb0-5742091296f1.png">

**Comment by Baoyuantop** [comment]
Handy feature; if there is anything you need help with, please feel free to ask.

**Comment by anldrms** [comment]
Thanks for the feedback. I'll start to developing this week.
