### ISSUE TITLE
dashboard return blank pange when edit plugins

### ISSUE THREAD

**Issue by zsmlinux** [apache/apisix-dashboard#2732]
### Issue description

Another problem is here, when enable Plugins or edit Plugin Template Config that return blank page like this:

### Expected behavior

Enable plugins or edit Plugin Template Config that return blank page

### How to Reproduce

1. Go to `http://{address}/plugin/list`
2. Click `Enable`

or 
1. Go to `http://{address}/routes/list`
2. Advanced --> Plugin Template Config

### Screenshots

![image](https://user-images.githubusercontent.com/10682145/216930414-4f5e1436-dad1-410b-960d-b22250dc1146.png)

### Environment

- apisix version (cmd: `apisix version`): 3.0.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: 3.0.0
- Browser version, if have:

**Comment by marchlhw** [comment]
![image](https://user-images.githubusercontent.com/7006014/217480095-81937980-4b19-4582-8941-8153db2550c1.png)
所有涉及到插件的对象都要调整plugins的disable属性，比如：route、service、plugin_config、global_rules、consumer等，否则就会白页，因为前端解析插件disable属性会报错
![image](https://user-images.githubusercontent.com/7006014/217480682-a4787277-0ba8-45be-9846-f7f26e0b2d55.png)

**Comment by andylee830914** [comment]
However, the original setting of _meta (like priority, filter) will be replaced if we manually put the `"disable":true` in _meta.
