### ISSUE TITLE
目前apisix有众多的插件,我应该如何去屏蔽掉一些插件,不在页面上显示出来。

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix-dashboard#2735]
# Feature request

## Please describe your feature

A clear and concise description of what you want and what your use case is.

**Comment by githubxubin** [comment]
不在apisix-bashboard上显示出来 是否可以配置呢

**Comment by mscb402** [comment]
I read the code https://github.com/apache/apisix-dashboard/blob/master/api/internal/handler/schema/plugin.go#L50
I think maybe you could try to modify this file `api/conf/schema.json`, and remove the plugin you want to hide.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/11229089/217759570-a4a7b944-4b72-463a-8032-c2cfabafb2a1.png">

**Comment by holate** [comment]
原来这是个一个bug？我一直以为这是一个特性。😂
我看了 apisix 的插件开发，并没有提到需要配置这个 conf.yaml 才能显示插件
然后我的 dashboard 从 2.15.0 升级到 3.0.1 发现列表不显示插件了。
修改后是否能在文档上进行一些说明？需要同时配置 `conf.yaml` 和 `schema.json` 才能正确显示插件。
https://apisix.apache.org/zh/docs/dashboard/FAQ/#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard
或者说我遗漏了某些文档？
