### ISSUE TITLE
禁用全局插件未使用_meta字段

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix-dashboard#2740]
### Issue description

3.x后，插件的disable属性移植到_meta属性中，但我发现禁用全局插件后在插件配置中依然写入了`"disable":true`，而不是`{"_meta":{"disable":true}`

### Expected behavior

禁用全局插件时，应该写入`{"_meta":{"disable":true}`

### How to Reproduce

1. 全局插件开启状态
![image](https://user-images.githubusercontent.com/7006014/218462108-3229d124-7baf-4c48-bfa9-bd6c83625a7c.png)
2. etcd中的数据
```
/apisix/global_rules/1
{"id":"1","create_time":1665476054,"update_time":1676292166,"plugins":{"prometheus":{"_meta":{"disable":false}}}}
```
3. 禁用全局插件
4. etcd中的数据
```
/apisix/global_rules/1
{"id":"1","create_time":1665476054,"update_time":1676292700,"plugins":{"prometheus":{"_meta":{"disable":false},"disable":true}}}
```

### Environment

- apisix version (cmd: `apisix version`):3.1
- OS (cmd: `uname -a`): centos
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`): 3.5.6
- apisix-dashboard version, if have: 3.0
- Browser version, if have: chorme latest

**Comment by Baoyuantop** [comment]
This issue may cause the global plugin disabling to fail and needs to be fixed. You can temporarily use the `Delete` Global Plugin.
