### ISSUE TITLE
apisix-bashboard login outtime

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix-dashboard#2741]
apisix-bashboard  use the jwt to login ,but when i am operating，the token is always outtime ,how i can  set the token outtime or refresh token？

**Comment by Baoyuantop** [comment]
see https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L76

**Comment by githubxubin** [comment]
> see https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L76

Is there no token refresh mechanism? Can you set only a fixed online expiration period?

**Comment by Baoyuantop** [comment]
This feature is not currently supported.
