### ISSUE TITLE
The apisix-dashboard function is unavailable after independent deployment  

### ISSUE THREAD

**Issue by creaplus** [apache/apisix-dashboard#2744]
### Issue description

 when apisix and apisix-dashboard are deployed separately, operations such as adding certificate routes cannot be performed on dashboards. I'm not sure if it was configured incorrectly or something else

### Expected behavior

I expect to be able to manage another apisix from my separate machine

### How to Reproduce

I updated dashboard's etcd config to the machine used by apisix service. dashboard could be entered, and all the addition on the page did not report error indicating that the addition was successful. However, after refreshing, there was no function that was added just now;

Machine 1:
etcd Version: 3.5.7
apisix: 3.1.0

Machine 2:
apisix-dashboard: 3.0
dashboard config update etcd endpoints to Machine 1

### Environment

- apisix version:
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version 3.1.0
- uname -a
Linux CentOS-s-2-CPU-8-GB 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- openresty -V
nginx version: openresty/1.21.4.1
- etcd --version
etcd Version: 3.5.7
- apisix-dashboard: 3.0
- apisix: 3.1.0

**Comment by Baoyuantop** [comment]
> However, after refreshing, there was no function that was added just now;

Can you describe it in more detail?

**Comment by creaplus** [comment]
When I create upstream, route, service, and finally commit, the page says success but my list is empty and refresh doesn't work。
![创建服务提示成功](https://img-blog.csdnimg.cn/ef15ba0b4e1a4dc6b4525dad018b3cdc.png)
we can add you QQ or wechat contact。

**Comment by creaplus** [comment]
> > However, after refreshing, there was no function that was added just now;
> 
> Can you describe it in more detail?

You can read the content of my new comment

**Comment by Baoyuantop** [comment]
Can you provide the configuration files for apisix and dashboard?

**Comment by creaplus** [comment]
> 

I'm using this file  "https://github.com/apache/apisix-dashboard/blob/v3.0.0/api/conf/conf.yaml"

Only the etc endpoints have been modified


![截屏2023-02-20 10 13 24](https://user-images.githubusercontent.com/17270460/219993478-83597e34-8c21-4c98-b6d9-854957984ff1.png)

**Comment by Baoyuantop** [comment]
Does the dashboard have any error logs?

**Comment by creaplus** [comment]
> Does the dashboard have any error logs?

file log and request response are normal

**Comment by Baoyuantop** [comment]
1. Is there no information in the `error.log` of the dashboard?
2. Once the dashboard indicates that the resource was created successfully, you can check if the resource was created successfully via the apisix admin API.

**Comment by creaplus** [comment]
> 1. Is there no information in the `error.log` of the dashboard?
> 2. Once the dashboard indicates that the resource was created successfully, you can check if the resource was created successfully via the apisix admin API.

Thanks for your answer. Due to time, I have given up this scheme and put apisix, dashboard and etcd on a machine. I will study later when I am free

**Comment by Baoyuantop** [comment]
If there is a problem, please reopen
