### ISSUE TITLE
[bug]can not config plugin on `Plugin List` page 

### ISSUE THREAD

**Issue by Gallardot** [apache/apisix-dashboard#2754]
### Issue description

Can not config plugin on `Plugin List` page .  Failed to load configuration data.

current version
apisix-dashboard version: 2.15.0
apisix version: 2.15.2

It works fine on version:
apisix-dashboard version: 2.13.0
apisix version:  2.15.1

### Expected behavior

Expect the right behavior

### How to Reproduce

1. Go `Pulgin List` page
2. Enable a zipkin plugin.
3. Return to  `Pulgin List` page
4. click `Configure` button.
5. you will find can not  load configuration data

### Screenshots

![RjhM9pIXOX](https://user-images.githubusercontent.com/329265/222027988-4123ff48-ecf7-4278-a6de-95ae80d0825f.jpg)
![SNWWXHpa0C](https://user-images.githubusercontent.com/329265/222028007-975c61c6-5fe9-409f-9406-784b723d8930.jpg)
![bd1Z4UqVDa](https://user-images.githubusercontent.com/329265/222028041-87618284-71b0-4f2a-b9f5-837c03c62f95.jpg)

### Environment

- apisix version (cmd: `apisix version`): 2.15.2
- etcd version, if have (cmd: run `etcd --version`): 3.4.0
- apisix-dashboard version, if have: apisix-dashboard version: 2.15.0
- Browser version, if have: google chrome

**Comment by Baoyuantop** [comment]
We have fixed it and made a change in https://github.com/apache/apisix-dashboard/pull/2745. Need to wait for the next release, or you can just use the latest code from branch release/2.15.

**Comment by Gallardot** [comment]
@Baoyuantop  thanks
