### ISSUE TITLE
Apisix Dashboard v3.0 路由名称长度限制报错

### ISSUE THREAD

**Issue by StevenBrown008** [apache/apisix-dashboard#2758]
### Issue description

发现一个bug，ingress controller自动生成的路由名字实际没达到长度上限，但是修改时会报超过长度错误，这导致自动创建的路由没法配置插件

### Expected behavior

在图形面板正常编辑路由

### How to Reproduce

编辑路由策略

### Screenshots

![routername](https://user-images.githubusercontent.com/105107341/222906337-1297202e-47a6-4545-88d5-1d59a342fe89.jpg)

![routername2](https://user-images.githubusercontent.com/105107341/222906350-59c0f823-9ff0-4dbd-9b9e-459a4ab6d178.jpg)

### Environment

- apisix version ：v3.1
- OS (cmd: `uname -a`): centos8
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:3.0
- Browser version, if have:

**Comment by StevenBrown008** [comment]
@juzhiyuan

**Comment by Baoyuantop** [comment]
Similar to https://github.com/apache/apisix-dashboard/issues/2610, needs to be fixed.

It is also not recommended to use Dashboard when using APISIX Ingress Controller. You can refer to https://github.com/apache/apisix-dashboard#works-with-apisix-ingress-controller

**Comment by Baoyuantop** [comment]
fixed by #2759
