### ISSUE TITLE
bug: apisix dashboard The ssl obtained from APISIXTLS is incorrectly displayed

### ISSUE THREAD

**Issue by charles-liming** [apache/apisix-dashboard#2768]
### Issue description

I used apisixTLS + secret to manage my https certificate. Then I logged into the dashboard and found that the expiration time of my SNI showed invilad date.It doesn't affect my business, but I think it's an important function. It should be displayed correctly.

### Expected behavior

The dashboard should normally display the expiration time of the SNI

### How to Reproduce

1、install repo and fetch localhost
helm repo add apisix https://charts.apiseven.com/
helm repo add bitnami https://charts.bitnami.com/bitnami
helm fetch apisix/apisix
tar -xvf apisix-0.7.2.tgz
mkdir -p apisix/ci

2、Define a value.yaml for helm chart as follows

ci/prod.yaml
apisix:
enabled: true
gateway:
type: NodePort
externalTrafficPolicy: Cluster
http:
enabled: true
servicePort: 80
containerPort: 9080
tls:
enabled: true # 启用 tls
servicePort: 443
containerPort: 9443

etcd:
enabled: true
replicaCount: 3

dashboard:
enabled: true

ingress-controller:
enabled: true
config:
apisix:
serviceName: apisix-admin
serviceNamespace: ingress-apisix
3、install chart
helm upgrade --install apisix ./apisix -f ./apisix/ci/prod.yaml -n apisix
4、 create tls secret and apisixTLS
5、Log in to the dashboard and check whether the sni display is normal

### Environment

APISIX version (run apisix version): ingress-apisix 1.6
Operating system (run uname -a): Linux shxt-test-cpu-public-gc-inside-02-1c2c 3.10.0-862.14.1.5.h520.eulerosv2r7.x86_64 https://github.com/apache/apisix/pull/1 SMP Wed Nov 25 18:33:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OpenResty / Nginx version (run openresty -V or nginx -V): This version follows the ingress-apisix 1.6 version
etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info): This version follows the ingress-apisix 1.6 version
APISIX Dashboard version, if relevant: This version follows the ingress-apisix 1.6 version
Plugin runner version, for issues related to plugin runners: This version follows the ingress-apisix 1.6 version
LuaRocks version, for installation issues (run luarocks --version): This version follows the ingress-apisix 1.6 version

**Comment by charles-liming** [comment]
![image](https://user-images.githubusercontent.com/34326414/224288709-cf31e953-6700-48c1-b4f0-5c0055c4a0d0.png)

**Comment by charles-liming** [comment]
![image](https://user-images.githubusercontent.com/34326414/224289170-e797b924-8be7-4872-a2e4-1e33f388da18.png)

**Comment by Baoyuantop** [comment]
Fixed by https://github.com/apache/apisix-dashboard/pull/2763. Only certificates added via Dashboard will display this field properly. Since APISIX does not resolve expiration times when adding certificates, `None` will be used instead.

**Comment by SkyeYoung** [comment]
@Baoyuantop should we close this since we have fixed this?

**Comment by SkyeYoung** [comment]
@charles-liming Hi. This issue has already been resolved in #2763 and has been released in version [2.15.1](https://github.com/apache/apisix-dashboard/pull/2765). Additionally, the fix has been merged into the master branch and will be released with the new 3.x version.
