### ISSUE TITLE
插件配置界面不兼容旧的配置数据

### ISSUE THREAD

**Issue by wukaixian** [apache/apisix-dashboard#2769]
### Issue description

从2.5.1版本升级到3.1后，旧的路由插件配置缺少 `{“_meta":"disable":false} `配置数据，导致在新版本dashboard界面插件界面无法正常显示。

### Expected behavior

新版本兼容老数据，缺少  `{“_meta":"disable":false} ` 配置时，可以正常显示插件配置界面。

### How to Reproduce

1.路由界面配置一个插件的json数据，如 limit-count，不加 `_meta` 字段
2.点击路由配置，点击下一步，到达插件配置界面
3.插件界面报错，界面显示为空，异常信息提示没有`disable`字段

### Screenshots

![image](https://user-images.githubusercontent.com/5820658/224603937-24be86a0-1819-4026-8ad0-102654cd475e.png)

### Environment

- apisix version (cmd: `apisix version`): 3.1
- OS (cmd: `uname -a`): win10
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: 3.0.0
- Browser version, if have:

**Comment by Baoyuantop** [comment]
Fixed by https://github.com/apache/apisix-dashboard/pull/2739, you can use the code of the master branch or wait for the next release.
