### ISSUE TITLE
edit global plugin, focus no data,dashboard page error

### ISSUE THREAD

**Issue by yangyang122** [apache/apisix-dashboard#2771]
### Issue description

edit global plugin, focus no data,dashboard page error

### Expected behavior

expect this

### How to Reproduce

help
edit global ,
step1:
curl http://127.0.0.1:9180/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
 "plugins": {
    "limit-count": {
	  "count": 10,
	  "time_window": 60,
	  "key": "remote_addr",
	  "rejected_code": 503,
	  "policy": "local"
	}
  }
}'
![图片](https://user-images.githubusercontent.com/12775735/225263148-b7659b5f-7ef4-49ab-98e0-a7cf7422652f.png)

step2: edit this
![图片](https://user-images.githubusercontent.com/12775735/225263351-178b1bed-a358-45a2-bf98-6c6bba9fda57.png)

### Environment

apisix-dashboard:3.0.0

**Comment by Baoyuantop** [comment]
Similar with https://github.com/apache/apisix-dashboard/issues/2769
