### ISSUE TITLE
Negative value option reports an error. 

### ISSUE THREAD

**Issue by freemankevin** [apache/apisix-dashboard#2775]
### Issue description

Since you cannot set a negative value, why do you have such a scroll wheel option? ? ? Ha ha
![image](https://user-images.githubusercontent.com/71524776/225807016-b2ef0177-5386-4a28-a466-5dee0b0a5ba6.png)

### Expected behavior

1

### How to Reproduce

1

### Environment

`docker-compose`   deploy the latest version.

**Comment by Neilblaze** [comment]
@freemankevin I'm taking this up.

cc: @Baoyuantop Primarily we can apply a `visibility: hidden` for `.ant-input-number-handler-wrap`, but I think the better way is to not remove those ` up/down ` arrows and instead we can lock the input to a *minimum value of* **0**.

**Comment by freemankevin** [comment]
good.
