### ISSUE TITLE
Unable to modify plugin configuration.

### ISSUE THREAD

**Issue by freemankevin** [apache/apisix-dashboard#2776]
### Issue description

'Plugin List' cannot dynamically modify the configuration, click to jump to a blank page
![image](https://user-images.githubusercontent.com/71524776/225808024-4299fbc5-807a-4feb-b3b8-1ec5c4d7dd2f.png)
![image](https://user-images.githubusercontent.com/71524776/225807938-2f886f9d-b139-4aed-be70-d7f698ea0220.png)

### Expected behavior

1

### How to Reproduce

1

### Environment

`docker-compose`   deploy the latest version.

**Comment by Baoyuantop** [comment]
Similar to https://github.com/apache/apisix-dashboard/issues/2769, there may be a 3.0.1 release next week.
