### ISSUE TITLE
官网yum安装v3.0.1链接404

### ISSUE THREAD

**Issue by haochencheng** [apache/apisix-dashboard#2793]
### Issue description

![image](https://user-images.githubusercontent.com/20943919/231987051-eac7e2ae-297d-49fe-8281-91493c867405.png)
官网安装链接404
sudo yum install -y https://github.com/apache/apisix-dashboard/releases/download/v3.0.1/apisix-dashboard-3.0.1-0.el7.x86_64.rpm

### Expected behavior

网站地址
https://apisix.apache.org/zh/docs/dashboard/install/
版本3.0,0
https://github.com/apache/apisix-dashboard/releases/download/v3.0.1/apisix-dashboard-3.0.1-0.el7.x86_64.rpm
404

### How to Reproduce

https://github.com/apache/apisix-dashboard/releases/download/v3.0.1/apisix-dashboard-3.0.1-0.el7.x86_64.rpm
404

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by swtseaman** [comment]
同问，这个最新版本在哪里下载安装呢

**Comment by frozer798** [comment]
同问，找不到rpm包，只能找到tgz压缩包

**Comment by zccabb** [comment]
看起来可能是没有上传3.0.1版本的rpm包，导致下载404
https://github.com/apache/apisix-dashboard/releases/tag/v3.0.1
可以先使用3.0.0版本
sudo yum install -y https://github.com/apache/apisix-dashboard/releases/download/v3.0.0/apisix-dashboard-3.0.0-0.el7.x86_64.rpm

**Comment by zccabb** [comment]
@nic-chen @AlinsRan

**Comment by guoqqqi** [comment]
@Baoyuantop Please take a look at this question when you have time.

**Comment by leslie-tsang** [comment]
Working in progress: https://github.com/api7/apisix-build-tools/pull/293

**Comment by leslie-tsang** [comment]
Fixed. :)
