### ISSUE TITLE
ERROR   cmd/root.go:107 etcd connection loss detected

### ISSUE THREAD

**Issue by c8202196** [apache/apisix-dashboard#2823]
### Issue description

I use Docker to install Apisix-Dashboard:
docker run -d --name czApiSixDashboard -p 9000:9000  -v ./dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml apache/apisix-dashboard:3.0.1-alpine

i want connect ETCD to my dev, it actualy work, i can see the route config in dashboard, but i can't edit:
<img width="1435" alt="image" src="https://github.com/apache/apisix-dashboard/assets/22017223/63ddd87c-967b-4abf-a4aa-c349856189fa">

here the dashboard_conf.yaml:
<img width="799" alt="image" src="https://github.com/apache/apisix-dashboard/assets/22017223/62b3397b-9741-4e1d-b172-22fac6bffc2d">

error.log:
2023-06-13T06:00:14.549Z        ERROR   cmd/root.go:107 etcd connection loss detected, times: 273
2023-06-13T06:00:29.552Z        ERROR   cmd/root.go:107 etcd connection loss detected, times: 274
202
3-06-13T06:00:44.554Z        ERROR   cmd/root.go:107 etcd connection loss detected, times: 275

stderr:
{"level":"warn","ts":"2023-06-13T06:13:59.762Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x400051e700/host.docker.internal:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}

### Expected behavior

i can editor the route config in dashboard(http://localhost:9000/routes/list)

### How to Reproduce

just start the docker with config.yaml, use my owner etcd

### Environment

- apisix version (cmd: `apisix version`):apache/apisix:3.3.0-debian
- OS (cmd: `uname -a`):Darwin
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):3.5.7
- apisix-dashboard version, if have: apache/apisix-dashboard:3.0.1-alpine
- Browser version, if have:

### Additional context

my dev etcd env is work, the dashborad can get the route list, but still print error log, and i can't edit route on dashboard

**Comment by c8202196** [comment]
已确定原因： etcd的ETCD_ADVERTISE_CLIENT_URLS=http://host.docker.internal:2379， 设置需要和上面etcd设置一致才可以。

**Comment by Juncx** [comment]
这里感觉很有误导性，两处的配置不在一个地方。异常报错时，错误内容不是conf.yaml里面的endpoints。
