### ISSUE TITLE
schema.json 

### ISSUE THREAD

**Issue by qlql489** [apache/apisix-dashboard#2879]
### Issue description

edit custom plugin，export schema.json  copy to dashbord conf folder, restart dashboard but still can't find it in dashboard @

### Expected behavior

can find in dashboard

### How to Reproduce

1、edit new custom plugin name wb-param
2、edit apisix conf add  the plugin
3、call `curl 127.0.0.1:9090/v1/schema > schema.json`
4、在 dashboard docker启动时映射 schema.json 文件
5、重启 dashboard docker 容器

### Screenshots

[http://image.nianlun.tech/20231107-104604.jpeg](http://image.nianlun.tech/20231107-104604.jpeg)
i delete orher plugins ，only left ai、wb-param(my plugin)、limit-count
[http://image.nianlun.tech/20231107-103918.jpeg](http://image.nianlun.tech/20231107-103918.jpeg)

### Environment

- apisix version (cmd: `apisix version`):3.6.0
- OS (cmd: `uname -a`): macos arm64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.21.4.2
- etcd version, if have (cmd: run `etcd --version`):3.5.9
- apisix-dashboard version, if have: 3.0.1
- Browser version, if have:

**Comment by holate** [comment]
是不是没有在 dashboard的`conf.yml` 中配置你这个插件。
https://github.com/apache/apisix-dashboard/issues/2735#issuecomment-1791951758

**Comment by qlql489** [comment]
对，忘记了dashboard的conf.yml 也需要配置，建议官方文档也加一下，现在也没有提
