### ISSUE TITLE
[Discuss] about the authentication of the dashboard

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix-dashboard#298]
## How
What should this identity authentication module look like?
Is to use apikey verification method provided by APISIX, or add a separate authentication part in the backend implemented by golang?

## What
If you need to add a separate authentication module, what form should it have?
Username+Password, and other. Need some advice.

## Other questions
Does the golang backend have the possibility to directly share APISIX's etcd storage?
Whether the mechanism to synchronize from etcd to mysql should be implemented on the golang backend?

**Comment by bzp2010** [comment]
I think that the authentication information can be set in the environment variable when the docker container is started, and read by the golang backend to provide the user login API.

Hope to get some suggestions. Thanks!

**Comment by juzhiyuan** [comment]
> I think that the authentication information can be set in the environment variable when the docker container is started, and read by the golang backend to provide the user login API. This mechanism is used to ensure that the dashboards exposed in the network environment will not be accessed illegally.
> 
> Hope to get some suggestions. Thanks!

Agree with your comment!

@membphis @gxthrj What do you think, please?

**Comment by AloneFire** [comment]
我认为 Dashboard 最好是一个纯静态的项目，认证以配置插件的形式存在，让用户自己选择是使用apisix自有的认证还是外部的认证服务

**Comment by juzhiyuan** [comment]
@bzp2010 sent a PR days ago, and this feature (unstable) is on the master branch.
