### ISSUE TITLE
[Question] How to connect this dashboard to a dev apisix process?

### ISSUE THREAD

**Issue by mtx2d** [apache/apisix-dashboard#321]
Hi Team, 
I am trying to connect this dashboard to a locally modified apisix process. 

Basically, I made some modification to my local `incubator-apisix` clone, and was able to start a apisix process.
I was able to see picture to confirm that my apisix is up and running:
![test-apisix-is-running](https://user-images.githubusercontent.com/64316805/87480994-72ff8400-c5fc-11ea-9ab6-a7e29c6254e7.png)

**However I was not able to get dashboard** when hitting `127.0.0.1:9080/dashboard`.
The error looks like this, and says "{"error_msg":"failed to match any routes"}":
![fail-to-match-route](https://user-images.githubusercontent.com/64316805/87481129-bbb73d00-c5fc-11ea-85ce-87dc4086682d.png)
 

**I tried deploying `incubator-apisix-dashboard` locally [from doc](https://github.com/apache/incubator-apisix-dashboard/blob/master/compose/README.md)**  but failed with "port alreay in use error":
```
docker-compose -p dashboard up -d
dashboard_manager_1 is up-to-date
grafana is up-to-date
dashboard_mysql_1 is up-to-date
Starting dashboard_dashboard_1 ... 
Starting dashboard_etcd_1      ... 
dashboard_prometheus_1 is up-to-date
dashboard_web2_1 is up-to-date
Starting dashboard_dashboard_1 ... error
WARNING: Host is already in use by another container

ERROR: for dashboard_dashboard_1  Cannot start service dashboard: driver failed programming external connectivity on endpoint dashboard_dashboard_1 (50f7086ee898ab62b2d53e7748b9419113d9eced001836cd31f300c0d730b180): Error starting userland Starting dashboard_etcd_1      ... done
Creating dashboard_apisix_1    ... 
Creating dashboard_apisix_1    ... error

ERROR: for dashboard_apisix_1  Cannot start service apisix: driver failed programming external connectivity on endpoint dashboard_apisix_1 (eba6e4da486e9e0a68f7a190e5b87118da069a3069fc61b63e0c9a04fa0976b9): Error starting userland proxy: listen tcp 0.0.0.0:9443: bind: address already in use

ERROR: for dashboard  Cannot start service dashboard: driver failed programming external connectivity on endpoint dashboard_dashboard_1 (50f7086ee898ab62b2d53e7748b9419113d9eced001836cd31f300c0d730b180): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
```

What is the right way for me to **connect this dashboard to a locally modified apisix?**

**Comment by moonming** [comment]
@gxthrj @membphis please take a look

**Comment by juzhiyuan** [comment]
The Dashboard is in front of Manager API, the Manager API is in front of APISIX, so you should visit the dashboard directly (not from IP:9080/dashboard).

**Comment by juzhiyuan** [comment]
If you want to connect to your modified APISIX, please update sone configurations under `/incubator-apisix-dashboard/compose`, just connect the Manager API with your local apisix.

**Comment by mtx2d** [comment]
> If you want to connect to your modified APISIX, please update sone configurations under `/incubator-apisix-dashboard/compose`, just connect the Manager API with your local apisix.

I am not very familiar with the toolchain, trying to make sure I understand what you mean. 
This means `127.0.0.1` is not the correct ip to connect to. And we can modify some file in `/incubator-apisix-dashbaord/compose/` to be able to connect to APISIX. 

Is `incubator-apisix-dashboard/compose/docker-comopse.yml` file I need to modify?

**Comment by juzhiyuan** [comment]
https://github.com/apache/incubator-apisix-dashboard/blob/master/compose/manager_conf/build.sh#L9

**Comment by juzhiyuan** [comment]
And I think you don't need APISIX built under Dockerfile any more.

https://github.com/apache/incubator-apisix-dashboard/blob/master/compose/docker-compose.yml#L4-L18

**Comment by gxthrj** [comment]
@mtx2d 
1. In the current version, the dashboard and APISIX are independent services.  The dashboard service has its own port, which is 80 by default，no longer 9080，which is the port of APISIX.
2. And the dashboard no longer directly calls the APISIX admin api, but through the manager-api, the calling relationship is like this dashboard -> manager -> APISIX, so the back-end service configured on the dashboard needs to be the service address of the manager-api , The default port is 8080.

ref:https://github.com/apache/incubator-apisix-dashboard/blob/master/compose/README.md
