### ISSUE TITLE
about authentication of manage API

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix-dashboard#329]
The 8080 port of the current manage API needs to be opened to the operator IP of the dashboard before it can be executed. In this way, there will be security risks. There is no restriction on authentication. Only iptables can be relied on. However, a large office area uses NAT and shares the IP address of the office network.

**Comment by gxthrj** [comment]
I think this is a security feature, perhaps, we need to support a simple way for security certificate

**Comment by juzhiyuan** [comment]
This feature is maintained on the master branch, I will close it currently.
