### ISSUE TITLE
Use auto load i18n

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#332]
https://umijs.org/zh-CN/plugins/plugin-locale#%E7%BA%A6%E5%AE%9A%E5%BC%8F%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81

Don’t need import every locale configuration  from Module any more!

**Comment by liuxiran** [comment]
I'm not sure  if ‘every locale configuration from Module ’ means something like

`menu:{
locale: true
}`

in src/config/defaultSettings.ts?

I tried to ignore this line，menu i18n worked still fine , so I think If you mean that , it is sure that i18n auto loaded with locale enable.

**Comment by juzhiyuan** [comment]
Only locales under /src/pages would work as far as I know, you could have a test :D

**Comment by liuxiran** [comment]
> Only locales under /src/pages would work as far as I know, you could have a test :D

I tried to do i18n in src/helps.tsx, which is not under src/pages
It worked by using `formatMessage` directly， which is not recommended, but the recommended way: useIntl is a react hook, only can be used in a React function component or a custom React Hook function.  so some locales such as notification msg in functions could not work. 

do you mean this?

**Comment by liuxiran** [comment]
> Only locales under /src/pages would work as far as I know, you could have a test :D

test passed.👍

although src/pages locales will be auto load , and it may be better to put locales together in src/locales, it's more convenient to do management, later I will submit a pr to modiy i18n.

**Comment by juzhiyuan** [comment]
> > Only locales under /src/pages would work as far as I know, you could have a test :D
> 
> test passed.👍
> 
> although src/pages locales will be auto load , and it may be better to put locales together in src/locales, it's more convenient to do management, later I will submit a pr to modiy i18n.

Here is a standard Page example: https://github.com/apache/apisix-dashboard/tree/master/src/pages/SSL

Please put `locales` folder under each `src/pages/$PAGE` folder.
