### ISSUE TITLE
路由设置proxy-rewrite BUG

### ISSUE THREAD

**Issue by longshang** [apache/apisix-dashboard#346]
proxy-rewrite 界面设置如下图
![image](https://user-images.githubusercontent.com/17903581/88691538-8dbf1600-d12f-11ea-9996-2e67b61aeb2d.png)

保存到数据库proxy-rewrite只设置了uri,而host没有设置？导致proxy-rewrite无法正常反代到http://www.webxml.com.cn/WebServices/WeatherWebService.asmx，如下图
![image](https://user-images.githubusercontent.com/17903581/88691785-e1c9fa80-d12f-11ea-9d70-06da31435610.png)
另外无法对路由设置priority，感觉较为不便。

**Comment by juzhiyuan** [comment]
1. We need a check.
2. We just hidden the priority for Route.

Thanks!

**Comment by juzhiyuan** [comment]
The screenshot above is taken from API request or response?

**Comment by longshang** [comment]
> 上面的屏幕截图来自API请求或响应？

您好，截图不知为什么显示不了，您能否看看QQ群（552030619），上面的截图一个来自Dashboard配置，一个是我截MYSQL的routes表中数据。

**Comment by juzhiyuan** [comment]
Please paste the request body here, thanks.

**Comment by longshang** [comment]
> 请在此处粘贴请求正文，谢谢。

GET /KKK/ HTTP/1.1
Host: 192.168.0.252:9080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: grafana_session=b0e4aaaf65eb57a6739be699e8885ed9

**Comment by juzhiyuan** [comment]
> > 请在此处粘贴请求正文，谢谢。
> 
> GET /KKK/ HTTP/1.1
> Host: 192.168.0.252:9080
> Connection: keep-alive
> Pragma: no-cache
> Cache-Control: no-cache
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,_/_;q=0.8,application/signed-exchange;v=b3;q=0.9
> Accept-Encoding: gzip, deflate
> Accept-Language: zh-CN,zh;q=0.9
> Cookie: grafana_session=b0e4aaaf65eb57a6739be699e8885ed9

This is not the request body, just open network in Chrome, and right click your target request, then copy the request info by cURL.

**Comment by longshang** [comment]
> > > 请在此处列出请求正文，谢谢。
> > 
> > 
> > GET / KKK / HTTP / 1.1 
> > 主机：192.168.0.252:9080 
> > 连接：keep-alive 
> > 语法：no-cache 
> > 缓存控制：no-cache 
> > Upgrade-Insecure-Requests：1 
> > 用户代理：Mozilla / 5.0（Windows NT 10.0; WOW64）AppleWebKit / 537.36（KHTML，例如Gecko）Chrome / 84.0.4147.89 Safari / 537.36 
> > 接受：text / html，application / xhtml + xml，application / xml; q = 0.9，image / webp，image / apng，_/_ ; q = 0.8，application / signed-exchange; v = b3; q = 0.9 
> > Accept-Encoding：gzip，deflate 
> > Accept-Language：zh-CN，zh; q = 0.9 
> > Cookie：grafana_session = b0e4aaaf65eb57a6739be699e8885ed9
> 
> 这不是请求正文，只需在Chrome中打开网络，然后右键单击目标请求，然后通过cURL复制请求信息。

curl 'http://192.168.0.252:9080/KKK/' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cookie: grafana_session=b0e4aaaf65eb57a6739be699e8885ed9' \
  --compressed \
  --insecure

**Comment by longshang** [comment]
> > > 请在此处粘贴请求正文，谢谢。
> > 
> > 
> > GET /KKK/ HTTP/1.1
> > Host: 192.168.0.252:9080
> > Connection: keep-alive
> > Pragma: no-cache
> > Cache-Control: no-cache
> > Upgrade-Insecure-Requests: 1
> > User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
> > Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,_/_;q=0.8,application/signed-exchange;v=b3;q=0.9
> > Accept-Encoding: gzip, deflate
> > Accept-Language: zh-CN,zh;q=0.9
> > Cookie: grafana_session=b0e4aaaf65eb57a6739be699e8885ed9
> 
> This is not the request body, just open network in Chrome, and right click your target request, then copy the request info by cURL.

curl 'http://192.168.0.252:9080/KKK/' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cookie: grafana_session=b0e4aaaf65eb57a6739be699e8885ed9' \
  --compressed \
  --insecure ;
curl 'http://192.168.0.252:9080/favicon.ico' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36' \
  -H 'Accept: image/webp,image/apng,image/*,*/*;q=0.8' \
  -H 'Referer: http://192.168.0.252:9080/KKK/' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cookie: grafana_session=b0e4aaaf65eb57a6739be699e8885ed9' \
  --compressed \
  --insecure

**Comment by juzhiyuan** [comment]
emmm Where is the actually data sent to API?

**Comment by longshang** [comment]
> emmm Where is the actually data sent to API?

是从 IP中的doctor/add 反代到 IP2中doctor/add,大神帮忙看看，我在旧版本Dashboard配置proxy rewrite是可以成功的

**Comment by juzhiyuan** [comment]
Please provide your HTTP Request Body, or I have no idea what your data is.
