### ISSUE TITLE
response-rewrite plugin is no able to write headers

### ISSUE THREAD

**Issue by lilien1010** [apache/apisix-dashboard#359]
for now some plug-in is not able to edit in dashboard，
and BTW I think the button ”Enable“，“disable","Confirm" should at the top of plugin-edit pannel， not at bottom.

![image](https://user-images.githubusercontent.com/3814966/89178810-09eaab00-d5c1-11ea-8587-82846cadd2f5.png)

**Comment by varSmallRookie** [comment]
@lilien1010  I will take care of this feature

**Comment by juzhiyuan** [comment]
Hi, the PluginDrawer is built with `react-jsonschema-form`, and this bug is caused by different JSON Schema version. APISIX’s plugin is using JSON Schema v5 I think, and the `react-jsonschema-form` is using v7, I would recommend adding a transformer for our Plugins’ schema in frontend.

**Comment by juzhiyuan** [comment]
Hi @varSmallRookie, any updates about this issue? Which part could I help you?

**Comment by juzhiyuan** [comment]
Any updates?

**Comment by juzhiyuan** [comment]
related issue https://github.com/alibaba/form-render/issues/131#issuecomment-671780907

**Comment by juzhiyuan** [comment]
Will be fixed here https://github.com/apache/apisix/issues/2087
