### ISSUE TITLE
[Question]when dashboar started in dev mode and not conect to apisix, why some requests like get routes list can also get response instead of get an error?

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#360]
Hi all, 
I have a question that when I run yarn start:no-mock  to start dashboard in dev mode,  and I did not do any settings,
then I visit http://localhost:8000/routes/list page

I noticed that get routes list request: http://localhost:8000/apisix/admin/routes?page=1&size=20&search=    got a response instead of an error,  I'm confused. there is no api server， why this request did not get an error like Service Unavailable？

looking forward to your reply，many thanks～

**Comment by juzhiyuan** [comment]
1. Open Network panel in Chrome;
2. Check the XHR requests;
3. Visit those requests manually.

Maybe you have deployed the manager-api by accident.

**Comment by liuxiran** [comment]
I checked my request, in chrome netword panel like this:
![image](https://user-images.githubusercontent.com/2561857/89365466-40cad900-d707-11ea-89ce-5a6badef7361.png)

the response is:
![image](https://user-images.githubusercontent.com/2561857/89365512-5b9d4d80-d707-11ea-870e-5207790f25ff.png)

actually it returned a page

and my API setting like this:
![image](https://user-images.githubusercontent.com/2561857/89365939-5260b080-d708-11ea-84c1-67e6a51d21e6.png)

so, under this setting, dashboard fe treated its dev server as the manager-api server, my I right?

**Comment by juzhiyuan** [comment]
emmm the api address should be `localhost:8080` by default.

**Comment by liuxiran** [comment]
thanks very much, when I set localhost:8080, I got the expected response error.

close this issue.
