### ISSUE TITLE
About service startup with manager_api

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix-dashboard#369]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
manager_api启动时，能不能手动指定配置文件进行启动，或者通过cli进行传入某些参数来进行启动，而不从环境变量读取，这样会不会更优呢，如果放在k8s中通过configmap挂载配置文件到pod，这样会不会比较好呢

**Comment by gxthrj** [comment]
1. I agree that the manager-api is started by formulating a configuration file, or by rewriting certain parameters when starting. This is a good feature.
2. In k8s, `configmap` can bind configuration files or specify `environment variables`. I prefer to modify specific parameters through `environment variables`, because configuration files need to pay attention to additional configuration structures.

**Comment by Yangzcy423911** [comment]
Currently approved run.sh To start the service, it is also to read variables directly to modify the configuration file, and then start it. Is the efficiency a little low? Moreover, it is not very convenient to get the path of the directory through PWD

**Comment by Yangzcy423911** [comment]
In k8s, mount the configuration file through configmap. Configmap reads from the configuration file and reads different configurations in different environments. Is this more elegant. Also avoid writing the configuration file to the image. This is only my personal opinion. It does not take the place of any judgment. Thank you for your understanding, your reply, thank you very much

**Comment by Yangzcy423911** [comment]
Will this operation be closer to cloud native? There is also a point about manager_ I think it will be better if the database script of API service can be generated in an incremental way, because if there is already this library online and there is real data, an error will be reported when importing the script directly. If there is an incremental script, will the result be different

**Comment by gxthrj** [comment]
> Will this operation be closer to cloud native? There is also a point about manager_ I think it will be better if the database script of API service can be generated in an incremental way, because if there is already this library online and there is real data, an error will be reported when importing the script directly. If there is an incremental script, will the result be different

for now, incremental database script upgrades are not supported. You can mention a separate issue about this feature. The incremental script needs to be bound to the version
