### ISSUE TITLE
About function of manager-api

### ISSUE THREAD

**Issue by mauriciosfriso** [apache/apisix-dashboard#374]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
What is the function of the manager-api?
Why not the frontend does request to apisix's admin api?
Why manager-api use an internal data base and doesn't use admin api?

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/90087883-574ce200-dd50-11ea-9576-faee8449c88d.png)

Please take a look at this image, we may have a more detailed description of this in the future.

**Comment by juzhiyuan** [comment]
related issue #270, I will close this now.
