### ISSUE TITLE
[Question]Parameter mapping feature in dashboard

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#375]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

apisix  plugin [proxy-rewrite](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/proxy-rewrite.md) supports regex_uri, which is a very convenience  to control parameters for users. Do you have a plane to add this feature to dashboard?
___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
related issue #359

**Comment by liuxiran** [comment]
After reading the #359  description carefully, I think these two issues are different， this issue is about plugin:proxy-rewrite, which is used in create route step2
![image](https://user-images.githubusercontent.com/2561857/90228206-63b46600-de48-11ea-9cb2-8612ae4ac8b8.png)

I can only config `keep` and `static` to the upstreamPath, when I want to config `regx`, now it is not supported

**Comment by juzhiyuan** [comment]
> After reading the #359 description carefully, I think these two issues are different， this issue is about plugin:proxy-rewrite, which is used in create route step2
> ![image](https://user-images.githubusercontent.com/2561857/90228206-63b46600-de48-11ea-9cb2-8612ae4ac8b8.png)
> 
> I can only config `keep` and `static` to the upstreamPath, when I want to config `regx`, now it is not supported
> @juzhiyuan

More clearly after reading your comment and snapshot 👍 

Yes, the Manager API supports this feature, but the Dashboard doesn’t support currently, I will label this issue as enhancement.
