### ISSUE TITLE
can not start with docker 

### ISSUE THREAD

**Issue by AllenLi1990** [apache/apisix-dashboard#381]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ - ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
can not start apisix-dashboard with docker.

CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                         PORTS                               NAMES
27083ec44749        apache/apisix:dev     "sh -c '/usr/bin/api…"   3 minutes ago       Restarting (1) 7 seconds ago                                       dashboard_apisix_1
        [C]: at 0x562c561cd320
/usr/local/openresty/luajit/bin/luajit: /usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:698: bad argument #1 to 'sfind' (string expected, got nil)
stack traceback:
        [C]: in function 'sfind'
        /usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:698: in function 'parsedocuments'
        /usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:760: in function 'read_yaml_conf'
        /usr/bin/apisix:679: in function </usr/bin/apisix:672>
        /usr/bin/apisix:936: in main chunk
        [C]: at 0x562891b9e320

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?
ubuntu-1604

- What happened?
just start with docker

___
### Requirement or improvement
- nothing

**Comment by juzhiyuan** [comment]
not sure what happened, could we have a screen sharing when you are free?

**Comment by AllenLi1990** [comment]
I know what happen.
don't run "sh gen-config-yaml.sh" and it will be ok.

**Comment by juzhiyuan** [comment]
🤔 So we SHOULD NOT run that shell, right?

**Comment by AllenLi1990** [comment]
我的情况是不运行就可以，看了下，这个脚本，运行这个脚本生成的配置是可以理解为是空的。
我猜测是作者更新的时候改过了配置文件导致的。
如果不运行，在我的电脑是可以的

**Comment by juzhiyuan** [comment]
thanks!

**Comment by gxthrj** [comment]
this is fixed in #383

**Comment by AllenLi1990** [comment]
thanks!

**Comment by AllenLi1990** [comment]
> this is fixed in #383 
`wget https://raw.githubusercontent.com/apache/apisix/master/conf/config-default.yaml

if [[ "$unamestr" == 'Darwin' ]]; then
   sed -i '' -e ':a' -e 'N' -e '$!ba' -e "s/allow_admin[a-z: #\/._]*\n\( *- [0-9a-zA-Z: #\/._',]*\n*\)*//g" config.yaml
   sed -i '' -e "s%http://[0-9.]*:2379%`echo $etcd_url`%g" config.yaml
else
	sed -i -e ':a' -e 'N' -e '$!ba' -e "s/allow_admin[a-z: #\/._]*\n\( *- [0-9a-zA-Z: #\/._',]*\n*\)*//g" config.yaml
	sed -i -e "s%http://[0-9.]*:2379%`echo $etcd_url`%g" config.yaml
fi`

need add one line
`mv config-default.yaml config.yaml`

**Comment by juzhiyuan** [comment]
done
