### ISSUE TITLE
dashboard api error

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix-dashboard#382]
Please answer these questions before submitting your issue.
dashboard和a'pisix部署在不同机器上，请问我的dashboard访问apisix时，在apisix里的日志看见这个问题，该怎么解决。版本是1.5
![image](https://user-images.githubusercontent.com/17898385/90611144-ef5b3780-e238-11ea-830d-8a7fd35567c8.png)

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Could you describe your deploy steps more detailed?

**Comment by javacjavawf** [comment]
me too!  APISIX 1.5

tail -f access.log
10.111.96.23 - - [24/Aug/2020:13:30:48 +0800] 10.111.96.95:9080 "GET /apisix/favicon.ico HTTP/1.1" 404 54 0.000 "http://10.111.96.95:9080/apisix/dashboard" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" - - -
10.111.96.23 - - [24/Aug/2020:13:30:48 +0800] 10.111.96.95:9080 "GET /apisix/admin/routes HTTP/1.1" 401 578 0.000 "http://10.111.96.95:9080/apisix/dashboard" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" - - -

dashboard install
git clone https://github.com/apache/incubator-apisix-dashboard.git
cd /root/incubator-apisix-dashboard
git checkout v1.0
mkdir -p /usr/local/apisix/dashboard
cp -r dist/* /usr/local/apisix/dashboard

How to solve it？

**Comment by juzhiyuan** [comment]
> me too! APISIX 1.5
> 
> tail -f access.log
> 10.111.96.23 - - [24/Aug/2020:13:30:48 +0800] 10.111.96.95:9080 "GET /apisix/favicon.ico HTTP/1.1" 404 54 0.000 "http://10.111.96.95:9080/apisix/dashboard" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" - - -
> 10.111.96.23 - - [24/Aug/2020:13:30:48 +0800] 10.111.96.95:9080 "GET /apisix/admin/routes HTTP/1.1" 401 578 0.000 "http://10.111.96.95:9080/apisix/dashboard" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" - - -
> 
> dashboard install
> git clone https://github.com/apache/incubator-apisix-dashboard.git
> cd /root/incubator-apisix-dashboard
> git checkout v1.0
> mkdir -p /usr/local/apisix/dashboard
> cp -r dist/* /usr/local/apisix/dashboard
> 
> How to solve it？

Please use the latest dashboard 1.5 or on the master branch instead of 1.0.
