### ISSUE TITLE
My dashboard is not working

### ISSUE THREAD

**Issue by lijiapengsa** [apache/apisix-dashboard#385]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

1、I started manager-api, but I didn't get any useful information. I don’t know if it succeeded or failed
![image](https://user-images.githubusercontent.com/7970836/90726668-a963a980-e2f4-11ea-8292-e71f0fe7a70d.png)
2、
I have used the `yarn start` command to start the dashboard, but I get a 404 error when I access it on the front end. My apisix admin port is 9180 instead of 8000. How should this be changed ?
![image](https://user-images.githubusercontent.com/7970836/90726713-bd0f1000-e2f4-11ea-9ec7-c9ce30ae2f60.png)

![image](https://user-images.githubusercontent.com/7970836/90727192-7372f500-e2f5-11ea-88cb-91e0c1b157b1.png)

3、I have started the apisix server normally and can be used normally

![image](https://user-images.githubusercontent.com/7970836/90727281-9ef5df80-e2f5-11ea-9398-7923414ce566.png)
___
### ENV
Centos 7

**Comment by juzhiyuan** [comment]
emmm There has a tricky way if you want to use your OWN manager-api to develop the Dashboard.

Just modifyed the `prefix` field in this file: `apisix-dashboard/src/app.tsx`.

**Comment by lijiapengsa** [comment]
For the time being, I don't worry about the error of dashboard.

Has the manager-api started successfully? No output. Is `manager-api` listening on the port or starting a process?

![image](https://user-images.githubusercontent.com/7970836/90998212-26916600-e5f6-11ea-822e-82b9a51d2846.png)

**Comment by juzhiyuan** [comment]
@gxthrj Please take a look, thanks
