### ISSUE TITLE
使用docker部署dashboard时 gen-config-yaml.sh中生成配置文件命令异常

### ISSUE THREAD

**Issue by zhou-mfk** [apache/apisix-dashboard#386]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?
最新版本  gen-config-yaml.sh 中  wget https://raw.githubusercontent.com/apache/apisix/master/conf/config-default.yaml -o config.yaml  这个命令不对, 需要修改为wget https://raw.githubusercontent.com/apache/apisix/master/conf/config-default.yaml -O config.yaml

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by gxthrj** [comment]
@zhou-mfk https://github.com/apache/apisix-dashboard/blob/4d4f8159a9c1e29cf4f2ac5f7ea40c99381aad9f/compose/gen-config-yaml.sh#L24
`wget xxx -o xxx ` the `-o` is lowercase

**Comment by gxthrj** [comment]
`-o` is worked in both linux and macos
but `-O` will be fail in macos

**Comment by gxthrj** [comment]
yes, it is a bug,`-o ` is log file, the --output file should be `-O`
