### ISSUE TITLE
How to judge whether `manager-api` has been started successfully

### ISSUE THREAD

**Issue by lijiapengsa** [apache/apisix-dashboard#392]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

Has the manager-api started successfully? No output. Is manager-api listening on the port or starting a process?

![image](https://user-images.githubusercontent.com/7970836/90998771-791f5200-e5f7-11ea-9949-56d91bc900d6.png)

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?
apisix 1.5
Centos7

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by gxthrj** [comment]
Usually our logs are printed on stdout. The situation you encounter is generally a startup failure, usually because of port conflicts. the default port of manager-api is 8080.
Here is a new PR #409  about the log output after startup failure.
