### ISSUE TITLE
bug:got error after login

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#396]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
I pull the latest code, and run docker component
after I login from login page , I got two errors:

![image](https://user-images.githubusercontent.com/2561857/91050972-055e6300-e652-11ea-8c71-e91e1015f2f6.png)

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by liuxiran** [comment]
about login failed: error username or password

the response code is 200:

![image](https://user-images.githubusercontent.com/2561857/91061338-a4895780-e65e-11ea-9657-64f73b57dea9.png)


but it is returned a html in fact

![image](https://user-images.githubusercontent.com/2561857/91061189-760b7c80-e65e-11ea-88bb-a3ea5699d693.png)

the key to the problem is the api url: /user/login, which is not match /apisix/admin/***, so its returned by dashboard-nginx server  instead of mange-api server, so may change the login api url , is a better solution

**Comment by juzhiyuan** [comment]
I get it and will take a look ASAP, thanks!

**Comment by juzhiyuan** [comment]
@bzp2010 This issue is caused due to different API prefix 🤔 

1. All APIs use `/apisix/admin` as a prefix;
2. Modify request fun on the frontend;

Which way would you prefer?

**Comment by liuxiran** [comment]
> @bzp2010 This issue is caused due to different API prefix 🤔
> 
> 1. All APIs use `/apisix/admin` as a prefix;
> 2. Modify request fun on the frontend;
> 
> Which way would you prefer?

modify ng conf can Solve this problem，but in the fe dev environment，here is another question：

login api`s url is /user/login
login page`s url is also:/user/login

how to config  the fe proxy?
so Please consider again whether to unify the interface prefix @juzhiyuan

**Comment by juzhiyuan** [comment]
yep, I agree using the uniform prefix for both admin API and other APIs.
