### ISSUE TITLE
create upstream got 500 error 

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#400]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

1. use admin login

1. create upstream, click submit

1. got 500 error
![image](https://user-images.githubusercontent.com/2561857/91122459-fcf73e00-e6cc-11ea-92a3-91b21519c654.png)

![image](https://user-images.githubusercontent.com/2561857/91122487-0e404a80-e6cd-11ea-86a6-b9112014719d.png)

and the manage-api log shows:
![image](https://user-images.githubusercontent.com/2561857/91122643-64ad8900-e6cd-11ea-94c7-e03ada4f60bc.png)

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

I also tried other functions，also failed，`GET /apisix/admin/plugins` got code 400：
`GET /apisix/admin/plugins`
![image](https://user-images.githubusercontent.com/2561857/91122828-dc7bb380-e6cd-11ea-9e1a-6de09da03c73.png)
![image](https://user-images.githubusercontent.com/2561857/91122846-ebfafc80-e6cd-11ea-9e1b-e92a3442114d.png)

if there is something wrong with authenticate or with my environment？

**Comment by juzhiyuan** [comment]
It seems that the Manager API's API Key is incorrect with APISIX? Have you modified the API Key both in manager-api & APISIX?

**Comment by liuxiran** [comment]
> It seems that the Manager API's API Key is incorrect with APISIX? Have you modified the API Key both in manager-api & APISIX?

👀 I have not modified the API key, just use the default configuration，and use docker-compose to develop the project

**Comment by juzhiyuan** [comment]
hmm May I know what version are you using? 1.5 or from master branch?

**Comment by liuxiran** [comment]
> hmm May I know what version are you using? 1.5 or from master branch?

master branch

**Comment by juzhiyuan** [comment]
ok, I need some time to look into this issue, could you use branch 1.5 currently? it's the latest release version as far as I know.

**Comment by liuxiran** [comment]
> ok, I need some time to look into this issue, could you use branch 1.5 currently? it's the latest release version as far as I know.

thanks very much🤝🤝， later I will try 1.5 branch

**Comment by liuxiran** [comment]
when I checkout v1.5 branch, and use docker-compose to develop, alse got error code,but the error message are different:

![image](https://user-images.githubusercontent.com/2561857/91143841-b82bd100-e6e5-11ea-827f-6a69fceb4f12.png)
return error msg: `apisix upstream create failed: Put http://192.17.5.11:9080/apisix/admin/upstreams/a8925acf-3afb-4aeb-949c-237d09eda8f2: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

docker logs dashboard_manager

![image](https://user-images.githubusercontent.com/2561857/91144059-0d67e280-e6e6-11ea-915c-cf14592a3172.png)

**Comment by nic-chen** [comment]
@liuxiran  I think APISIX was not running in your env, you could pull the master branch and try again. thanks.

**Comment by liuxiran** [comment]
> @liuxiran I think APISIX was not running in your env, you could pull the master branch and try again. thanks.

thanks very much, after I updated master to the lastest, use docker-compose to develop the project, this issue has been solved already.  

close issue, thanks again~
