### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by wanghuashun** [apache/apisix-dashboard#404]
dashboard使用的介绍太少 不知道怎么操作

**Comment by juzhiyuan** [comment]
Ya, because there have more works, so we have no much time to write the User Guide, would you like to help us to write User Guide?

**Comment by wanghuashun** [comment]
现在还不太懂 不敢乱写

**Comment by juzhiyuan** [comment]
The Route module & Plugin module are under refactoring to make them better to use, so I will close this issue currently, the User Guide will be on board once those major issues are resolved :D
