### ISSUE TITLE
bug: click create ssl prestep not response

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#406]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?

    * both the v1.5 branch and master branch

- What happened?
If possible, provide a way to reproduce the error.

[test case]:

1. create ssl, entered necessary info， click [Next] button，changed to step2 form

1. click [Previous]，the form did not change to step1 form

![image](https://user-images.githubusercontent.com/2561857/91158636-87ee2d80-e6f9-11ea-86b5-f35504854f51.png)
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

in step2, when click [Previous], it should change to step1 form.

**Comment by LiteSun** [comment]
Bug confirmed. Thanks for your issue. I will fix it in the next PR.

**Comment by juzhiyuan** [comment]
@LiteSun hmm @liuxiran just created a PR for this issue https://github.com/apache/apisix-dashboard/issues/406

**Comment by LiteSun** [comment]
> @LiteSun hmm @liuxiran just created a PR for this issue #406

Good. i
