### ISSUE TITLE
grafana

### ISSUE THREAD

**Issue by wanghuashun** [apache/apisix-dashboard#410]
![image](https://user-images.githubusercontent.com/32918557/91251839-da2d5e00-e78e-11ea-8c97-515cecf66254.png)
直接填入好像不行  需要其他操作吗

**Comment by juzhiyuan** [comment]
Could you visit this address directly in your browser?

**Comment by wanghuashun** [comment]
可以访问的

**Comment by juzhiyuan** [comment]
Maybe you are visiting this HTTP website under HTTPS mode? Could you please provide more detailed info?

**Comment by wanghuashun** [comment]
就显示响应失败 估计是我安装的问题

**Comment by juzhiyuan** [comment]
😂 ok then, you could visit it directly in your browser instead of setting it in Dashboard

**Comment by wanghuashun** [comment]
Yes, I think so

**Comment by juzhiyuan** [comment]
I will close this issue currently, feel free to reopen this if needed.
