### ISSUE TITLE
after update master, login return error again

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#416]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?
latest master branch

- What happened?
If possible, provide a way to reproduce the error.

[test case]:

1. use docker-compose to develop project,  use admin/admin to login

1. return error

request info:

![2020-08-27 10-06-40屏幕截图](https://user-images.githubusercontent.com/2561857/91375605-baa93a80-e84d-11ea-80d3-43c03641b402.png)

![2020-08-27 10-07-14屏幕截图](https://user-images.githubusercontent.com/2561857/91375572-a2392000-e84d-11ea-9d91-99fc710ce87e.png)

and at the same time, the dashboard_manager docker container has been restarting
![2020-08-27 10-09-31屏幕截图](https://user-images.githubusercontent.com/2561857/91375740-0cea5b80-e84e-11ea-804f-df1ddc320105.png)

logs：
![2020-08-27 10-15-27屏幕截图](https://user-images.githubusercontent.com/2561857/91375828-41f6ae00-e84e-11ea-8017-de0f184331b7.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Looks like the manager api couldn't connect the MySQL because of incorrect username or password, please check.

BTW, we are planning to use other lightweight DB to replace MySQL, it will take some time to finish this work.

**Comment by imjoey** [comment]
> Looks like the manager api couldn't connect the MySQL because of incorrect username or password, please check.
> 
> BTW, we are planning to use other lightweight DB to replace MySQL, it will take some time to finish this work.

@juzhiyuan Could you please elaborate which lightweight DB will be the alternative, as well as the reason? Maybe we could help, with pleasure. 😄

**Comment by juzhiyuan** [comment]
@bzp2010 would involve this issue :D

**Comment by wanghuashun** [comment]
我前天就遇见了  解决了   登陆不上是因为前端的一个地方。

**Comment by wanghuashun** [comment]
前端的请求有问题 
src\pages\User\components\LoginMethodPassword.tsx
98行
 const result = await request('/user/login',
改成  const result = await request('http://192.168.3.124:8000/user/login',
http://192.168.3.124:8080 后端(go)的api地址 之后就好了

**Comment by liuxiran** [comment]
> 前端的请求有问题
> src\pages\User\components\LoginMethodPassword.tsx
> 98行
> const result = await request('/user/login',
> 改成 const result = await request('http://192.168.3.124:8000/user/login',
> http://192.168.3.124:8080 后端(go)的api地址 之后就好了

感谢您的回答，我的问题还不是这个原因，事实上最新的代码中社区的同学已经规范了login的url。
我尝试剔除了这个commit： https://github.com/apache/apisix-dashboard/commit/d37c11b4f05d2dd52165995e1bd81fb2b89eeaef
重新编译构建了代码，问题就不存在了，所以考虑问题是不是出在☝️提交中。

**Comment by juzhiyuan** [comment]
> 前端的请求有问题
> src\pages\User\components\LoginMethodPassword.tsx
> 98行
> const result = await request('/user/login',
> 改成 const result = await request('http://192.168.3.124:8000/user/login',
> http://192.168.3.124:8080 后端(go)的api地址 之后就好了

It seems that you don't notice the nginx file :{ there has a proxy rule to handle requests including `/apisix/admin`

**Comment by juzhiyuan** [comment]
> > 前端的请求有问题
> > src\pages\User\components\LoginMethodPassword.tsx
> > 98行
> > const result = await request('/user/login',
> > 改成 const result = await request('http://192.168.3.124:8000/user/login',
> > http://192.168.3.124:8080 后端(go)的api地址 之后就好了
> 
> 感谢您的回答，我的问题还不是这个原因，事实上最新的代码中社区的同学已经规范了login的url。
> 我尝试剔除了这个commit： [d37c11b](https://github.com/apache/apisix-dashboard/commit/d37c11b4f05d2dd52165995e1bd81fb2b89eeaef)
> 重新编译构建了代码，问题就不存在了，所以考虑问题是不是出在☝️提交中。

Not sure, but the online demo site[1] is using the latest codes from branch 🤔 Every commit sent to master branch will trigger the CI & CD.

[1] http://139.217.190.60/

**Comment by juzhiyuan** [comment]
cc @nic-chen

**Comment by liuxiran** [comment]
> > > 前端的请求有问题
> > > src\pages\User\components\LoginMethodPassword.tsx
> > > 98行
> > > const result = await request('/user/login',
> > > 改成 const result = await request('http://192.168.3.124:8000/user/login',
> > > http://192.168.3.124:8080 后端(go)的api地址 之后就好了
> > 
> > 
> > 感谢您的回答，我的问题还不是这个原因，事实上最新的代码中社区的同学已经规范了login的url。
> > 我尝试剔除了这个commit： [d37c11b](https://github.com/apache/apisix-dashboard/commit/d37c11b4f05d2dd52165995e1bd81fb2b89eeaef)
> > 重新编译构建了代码，问题就不存在了，所以考虑问题是不是出在point_up提交中。
> 
> Not sure, but the online demo site[1] is using the latest codes from branch thinking Every commit sent to master branch will trigger the CI & CD.
> 
> [1] http://139.217.190.60/

yeap, I tried the demo site, it works well , but It still does not work well in my local docker-compose environment, still need help

**Comment by nic-chen** [comment]
it looks like manager api try to connect to mysql on 127.0.0.1:3306 , have you modified `apisix-dashboard/compose/manager_conf/build.sh`? @liuxiran

**Comment by liuxiran** [comment]
> it looks like manager api try to connect to mysql on 127.0.0.1:3306 , have you modified `apisix-dashboard/compose/manager_conf/build.sh`? @liuxiran

no, developed with the default config files

**Comment by juzhiyuan** [comment]
@nic-chen this PR will resolve this issue?

**Comment by nic-chen** [comment]
@juzhiyuan yes i think so.

@liuxiran  you could pull the master branch and try again, thanks.

**Comment by liuxiran** [comment]
> @juzhiyuan yes i think so.
> 
> @liuxiran you could pull the master branch and try again, thanks.

wow, issue has been resolved after I updated to the lastest master.  thanks very much!!!!!!!

BTW, I could not understand why yesterday, with the error code, the demo site still worked fine? If there is something wrong with the ci?

**Comment by juzhiyuan** [comment]
> > @juzhiyuan yes i think so.
> > @liuxiran you could pull the master branch and try again, thanks.
> 
> wow, issue has been resolved after I updated to the lastest master. thanks very much!!!!!!!
> 
> BTW, I could not understand why yesterday, with the error code, the demo site still worked fine? If there is something wrong with the ci?

We don't have smoke testing currently 🤔  and Frontend and Backend are deployed separately, feel free to reopen this issue if there have other errors.
