### ISSUE TITLE
Get routeInfo [websocket] field is not match the value enterd

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#417]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?
* dashboard: master branch except commit https://github.com/apache/apisix-dashboard/commit/d37c11b4f05d2dd52165995e1bd81fb2b89eeaef  and https://github.com/apache/apisix-dashboard/commit/4336873927ac02063e8adf10d1aaa77bba05f034

- What happened?
If possible, provide a way to reproduce the error.

1. create a route with data:
```json
{
	"name": "api2",
	"desc": "",
	"priority": 0,
	"protocols": ["http"],
	"hosts": ["test"],
	"paths": ["/*"],
	"methods": ["GET", "HEAD", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
	"upstream_protocol": "keep",
	"upstream_id": "1b78c1a6-c295-4d7f-a7ba-5cff997898a8",
	"plugins": {},
	"uris": ["/*"],
	"vars": [],
	"upstream_header": {}
}
```

1. edit this route, got route info:
```json
{
	"id": "58a3b678-a905-4f05-8a78-4ad3d54a52dc",
	"name": "api2",
	"methods": ["GET", "HEAD", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
	"uris": ["/*"],
	"hosts": ["test"],
	"protocols": ["websocket", "http"],
	"redirect": {},
	"upstream_id": "1b78c1a6-c295-4d7f-a7ba-5cff997898a8",
	"upstream_protocol": "keep",
	"plugins": {}
}
```

**I noticed that the `protocols`, no matter if `websocket` is turned on when it is created or modified, get route info  always returns protocols include websocket to me.**
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
After carefully checking, It is not a problem with page passing parameters, maybe something goes wrong with manage-api or apxsix?

**Comment by juzhiyuan** [comment]
@LiteSun Please take a look, thx!

**Comment by LiteSun** [comment]
> @LiteSun Please take a look, thx!

@gxthrj  The API returns an error `protocols `,  please have a check.

**Comment by liuxiran** [comment]
update master,  Api can return the right protocols now. close it.
