### ISSUE TITLE
 认证权限

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix-dashboard#425]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
请问这个在哪配，因为我自己写了一个认证插件，我只配我自己写的插件了，但提示我必须选一，我该怎么配置，让我的插件也是认证插件
![image](https://user-images.githubusercontent.com/17898385/91587206-07ddf700-e989-11ea-9746-2cc215fe16f3.png)

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
## Steps
1. Adding your custom Auth plugin to APISIX, please make sure it must contain the `auth` text in the name. e.g custom-auth.
2. Modify the config file[1], and add your custom plugin's name, make sure when visiting the `/apisix/admin/plugins` API, your custom plugin's name should appear here.
3. Downloading the latest Dashboard codes from the master branch.

[1] https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L152

**Comment by juzhiyuan** [comment]
Feel free to reopen this issue if your question still exist :D
