### ISSUE TITLE
bug: there is no response clicking 'createNew' button in create route resultView

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#427]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
the latest master branch

- What happened?
If possible, provide a way to reproduce the error.
when create a route, in it`s resultView ,click [createNew] button, on response.
![image](https://user-images.githubusercontent.com/2561857/91628800-05fe4d00-e9f6-11ea-81b9-48b4a0057276.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
@LiteSun Please take a look.
