### ISSUE TITLE
Requirements for refactoring the Dashboard with Manager API

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#434]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Requirements
- What do you want to know?

As title said

**Comment by juzhiyuan** [comment]
# APIs 
## Route
### Create
### Delete
### Update
### Fetch List
### Fetch Detail
### Check if there has routes with same name
### Fetch Upstream List
`/names/upstreams`
### Check if there has SSL Cert with targeting Host

## Upstream
### Create
### Delete
### Update
### Fetch List
### Fetch Detail

## SSL
### Create
### Delete
### Update
### Fetch List
### Fetch Detail
### Verify SSL Key pair
### Switch enable status

## Consumer
### Create
### Delete
### Update
### Fetch List
### Fetch Detail

## User
### Login

## Other
### Get Plugin Schema
`/schema/plugins/:name``
### Get Plugin List
`/plugins`

**Comment by juzhiyuan** [comment]
@nic-chen Please take a look at above APIs which are related with MySQL? Then you can remove others directly by editing the second comment.

**Comment by liuxiran** [comment]
if routeGroup merged, there are some **routeGroup** apis here: @juzhiyuan  @nic-chen 

Create
POST `/routegroups`

Delete
DELETE `/routegroups/:gid`

Update
PUT `/routegroups/:gid`

Fetch List
GET `/routegroups`

Fetch Detail
GET `/routegroups/:gid`

Fetch name List
GET `/names/routegroups`

Check route group exit
GET `/notexist/routegroups`

**Comment by juzhiyuan** [comment]
cc @gxthrj @nic-chen

**Comment by nic-chen** [comment]
I have updated https://github.com/apache/apisix-dashboard/issues/434#issuecomment-686153897

Note that we need to implement the features using by relational database currently:
1. unique constraint
2. paging
3. foreign key constraint

**Comment by juzhiyuan** [comment]
cc @bzp2010 @gxthrj @moonming @membphis @ShiningRush @liuxiran @tiannian @LiteSun

**Comment by ShiningRush** [comment]
Fine, I will make a simple design image about watching ETCD in this week.
BTW: I have read the code of manager API, but I do not see any code about RBAC, is the feature still not implement?

**Comment by ShiningRush** [comment]
I drew a picture to show how the underlying components work together
![image](https://user-images.githubusercontent.com/24238012/92320639-99b6c580-f055-11ea-9b4b-58a6ca4f0e1a.png)

This is a bit like the design of [k8s apiserver](https://github.com/kubernetes/apiserver/blob/master/pkg/registry/generic/registry/store.go), but it simplifies a lot of details.
Here are the responsibilities of each component:
- `Handler`: handle the requests,each handler will have a their own store which is created from `GenericStore`
- `GenericStore`: this component is responsible for common logic, such as maintaining memory-based etcd copies, queries, etc.
- `Etcd3Storage`: responsible for the operation of etcd, used to decouple GenericStore and persistent components, to facilitate unit testing and expansion

@nic-chen @juzhiyuan @membphis @moonming
If there is no doubt about the design details, I will implement it for ManagerAPI recently.
If there is something unclear, we can hold a meeting to discuss it.

**Comment by juzhiyuan** [comment]
Just waiting for other teammates' response :D

**Comment by nic-chen** [comment]
LGTM.
`GenericStore`, do we implement it, or there are some ready-made component recommended ?

**Comment by ShiningRush** [comment]
We implement it,I do not find any libs can helps us.
But our case it not complex, so it will not take many works.

**Comment by moonming** [comment]
> I drew a picture to show how the underlying components work together
> ![image](https://user-images.githubusercontent.com/24238012/92320639-99b6c580-f055-11ea-9b4b-58a6ca4f0e1a.png)
> 
> This is a bit like the design of [k8s apiserver](https://github.com/kubernetes/apiserver/blob/master/pkg/registry/generic/registry/store.go), but it simplifies a lot of details.
> Here are the responsibilities of each component:
> 
>     * `Handler`: handle the requests,each handler will have a their own store which is created from `GenericStore`
> 
>     * `GenericStore`: this component is responsible for common logic, such as maintaining memory-based etcd copies, queries, etc.
> 
>     * `Etcd3Storage`: responsible for the operation of etcd, used to decouple GenericStore and persistent components, to facilitate unit testing and expansion
> 
> 
> @nic-chen @juzhiyuan @membphis @moonming
> If there is no doubt about the design details, I will implement it for ManagerAPI recently.
> If there is something unclear, we can hold a meeting to discuss it.

We can discuss in an online meeting, and then synchronize the results here

**Comment by imjoey** [comment]
> BTW: I have read the code of manager API, but I do not see any code about RBAC, is the feature still not implement?

@ShiningRush Yeap, RBAC has not been implemented yet.

**Comment by juzhiyuan** [comment]
@moonming @ShiningRush Could you please set a milestone here?

cc @bzp2010

**Comment by imjoey** [comment]
@ShiningRush @juzhiyuan  Just as a reminder, APISIX itself is using API v2 to interactive with etcd, meanwhile this new design seems that API v3 would be adopted in Manager. This will lead to no data could be shared between APISIX and Manager. I did not see any discussions about this(maybe I missed something 😄 ), so I was wondering if we have already deliberated on that? Thank you all.

**Comment by juzhiyuan** [comment]
need @membphis @moonming 's help to address your question 😂

**Comment by moonming** [comment]
APISIX will change to etcd v3 at the same time, there is already a pr in
apisix repo.

琚致远 <notifications@github.com> 于 2020年9月8日周二 下午7:38写道：

**Comment by ShiningRush** [comment]
@imjoey `GenericStore` just depend on a storage interface, so we can also implement etcdv2storage if we need

**Comment by imjoey** [comment]
> @imjoey `GenericStore` just depend on a storage interface, so we can also implement etcdv2storage if we need

@ShiningRush OK, thanks for your point.

**Comment by imjoey** [comment]
> APISIX will change to etcd v3 at the same time, there is already a pr in apisix repo. 琚致远 <notifications@github.com> 于 

@moonming yeah, that would be really great! Thanks.

**Comment by ShiningRush** [comment]
@bzp2010 @gxthrj @moonming @membphis @ShiningRush @tiannian @LiteSun
`GenericStore` has already completed.I write a demo about how to use it in `internal/handler/route/route.go`
I found some project problems, listed below:
- The project structure is not standardized, please refer to [golang-standards/project-layout](https://github.com/golang-standards/project-layout)
- We need a middleware mechanism to solve the following problems
  + error handling
  + result wrapping
  + input validating
- Logger relies on concrete component(logrus), it needs to be decoupled

We can hold a meeting to discuss how to carry out the next task

**Comment by juzhiyuan** [comment]
@ShiningRush Could you please leave the result about the last meeting here?

**Comment by ShiningRush** [comment]
The key points of the meeting are as follows:
- I will write an api demo first, and then x will cooperate to migrate the existing API
- The front end needs to migrate the data format conversion work to the front end, because the ManagerAPI needs to keep the data structure consistent with the AdminAPI

**Comment by juzhiyuan** [comment]
got it ping @moonming

**Comment by moonming** [comment]
LGTM

Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2020年9月11日周五 下午3:24写道：

**Comment by juzhiyuan** [comment]
Any update?

**Comment by juzhiyuan** [comment]
- [ ] Refactor APIs about Route, Upstream, etc. Both backend and frontend.
- [ ] Uniform the Error Codes both on backend and frontend.

**Comment by juzhiyuan** [comment]
fe https://github.com/apache/apisix-dashboard/issues/498
