### ISSUE TITLE
Feature：route publish management

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#437]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

When route successfully created, it is directly published to use, but in actual scenarios, we may want to test it, and trial it before the route published to use. so route publish manage is needed here:

* Support API design, pubilsh, and offline management. After the design is saved, it cannot be accessed externally
* Support to publish API to different environments, such as : test, pre-release, release environment, which can be distinguished by different URI prefix

**Comment by juzhiyuan** [comment]
cc @moonming @nic-chen

**Comment by bzp2010** [comment]
@juzhiyuan 
I don't know what progress has been made in the replacement of database. At present, the pr #450 related to this is use mysql. Is this only regarded as a temporary measure.

**Comment by juzhiyuan** [comment]
> @juzhiyuan
> I don't know what progress has been made in the replacement of database. At present, the pr #450 related to this is use mysql. Is this only regarded as a temporary measure.

tracking issue: https://github.com/apache/apisix-dashboard/issues/434
