### ISSUE TITLE
Route storage failure: Error 1054: Unknown column 'script' in 'field list'

### ISSUE THREAD

**Issue by y934317258** [apache/apisix-dashboard#440]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
Route storage failure: Error 1054: Unknown column 'script' in 'field list'
![IAEE3229OH L7RJTZS_P)VP](https://user-images.githubusercontent.com/68832358/92209098-06e42280-eebf-11ea-9281-ffe9626290dd.png)
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
master
- What happened?
If possible, provide a way to reproduce the error.
only config
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by y934317258** [comment]
Is this a new version of bug？

**Comment by nic-chen** [comment]
@y934317258  
please update your mysql table `routes`: 
```
alter table `routes` add column `script` text;
```

it's updated by this pr:
https://github.com/apache/apisix-dashboard/pull/411/files#diff-8a29820976db180f132d6c80c9044cf5R15
