### ISSUE TITLE
When is the MySQL script initialized? After I started through compose, I found that the initialization script did not execute

### ISSUE THREAD

**Issue by y934317258** [apache/apisix-dashboard#442]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
When is the MySQL script initialized? After I started through compose, I found that the initialization script did not execute
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by nic-chen** [comment]
Initialize with docker-entrypoint-initdb.d script :
https://github.com/apache/apisix-dashboard/blob/master/compose/docker-compose.yml#L84
