### ISSUE TITLE
request help: How to resolve the license conflict in the file header.

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#457]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
Some files have "MIT License" in the header, how to add "ASF Licese". Is it one of the two? 
For example: [https://github.com/apache/apisix-dashboard/blob/master/src/e2e/baseLayout.e2e.js](https://github.com/apache/apisix-dashboard/blob/master/src/e2e/baseLayout.e2e.js)

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Just keep the MIT Header, @moonming right?

**Comment by moonming** [comment]
yes, we should keep these original headers.
you can skip these files in license check tool.

琚致远 <notifications@github.com> 于 2020年9月9日周三 上午8:18写道：

**Comment by Firstsawyou** [comment]
okay, thanks.

**Comment by juzhiyuan** [comment]
closed now, feel free to reopen it if needed.
