### ISSUE TITLE
bug: When creating a route, host should not be required

### ISSUE THREAD

**Issue by tengzhinei** [apache/apisix-dashboard#458]
### Issue description

When creating a route, host should not be required. We are a sass project. Thousands of domain names point to the same system. Now, we are using Kong. kong   is not required

![image](https://user-images.githubusercontent.com/2428304/92546242-af5e0200-f284-11ea-8aca-823c44b5ad26.png)

**Comment by juzhiyuan** [comment]
cc @membphis @nic-chen so it's not needed? 🤔

**Comment by juzhiyuan** [comment]
ping @membphis @nic-chen

**Comment by membphis** [comment]
only `uri` is the required option. the `host` is optional option.

**Comment by juzhiyuan** [comment]
please modify this one when you update the Route module

**Comment by juzhiyuan** [comment]
assigned to @LiteSun

**Comment by juzhiyuan** [comment]
ping @LiteSun

**Comment by juzhiyuan** [comment]
Could we close this issue @LiteSun
