### ISSUE TITLE
In the routing plug-in configuration interface, click response rewrite to display 500

### ISSUE THREAD

**Issue by y934317258** [apache/apisix-dashboard#459]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
master centos7 chrom
- What happened?
If possible, provide a way to reproduce the error.
In the routing plug-in configuration interface, click response rewrite to display 500
![image](https://user-images.githubusercontent.com/68832358/92583791-6da17b80-f2c5-11ea-89c0-fc1e37c2aa8c.png)
![image](https://user-images.githubusercontent.com/68832358/92583809-742ff300-f2c5-11ea-80c5-e1ca60dfc63d.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by LiteSun** [comment]
![image](https://user-images.githubusercontent.com/31329157/92622316-7dd24e80-f2f7-11ea-8c7b-1c281ff68258.png)
It seems that API does not return the expected data.  @gxthrj Please have a check.
front-end needs to enhance error handling.
