### ISSUE TITLE
Custom plug-in profiles and links

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix-dashboard#463]
￼
<img width="961" alt="image" src="https://user-images.githubusercontent.com/17898385/92698954-971edd80-f37f-11ea-8463-d37a1133f5dc.png">

**Comment by juzhiyuan** [comment]
Sure, the description would be added once I have implemented the PluginModule.

**Comment by liubinqi2007** [comment]
Has this functionality been implemented yet? Still need to develop

**Comment by juzhiyuan** [comment]
No, still in progress.

**Comment by juzhiyuan** [comment]
related issue #448
