### ISSUE TITLE
request help: 401 when using apisix in k8s

### ISSUE THREAD

**Issue by maxluo1992** [apache/apisix-dashboard#464]
### Issue description
I use the docker image to open apisix in the k8s environment, but an error 401 Authorization Required is reported when accessing the resources of the dashboard. But I did not report an error when deploying in a traditional environment.
### Environment
* APISIx Version (CMD: 'APISIx version'):1.2
* OS: centos7.8 for docker

**Comment by maxluo1992** [comment]
Yes,my dashboard version is v1.0.

**Comment by juzhiyuan** [comment]
Please use the latest (master or 1.5 branches) if possible.
