### ISSUE TITLE
bug: a related to route basic-auth consumer should not be deleted

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#466]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
the latest master

- What happened?
If possible, provide a way to reproduce the error.

1. create a consumer: user1 with 123456

1. create a route: route1, enabled basic-auth plugin with user1 123456, then the route can only be visited by the user1

1. delete consumer user1, it can be deleted successfully, and then visit the route1, it return a error: `Missing related consumer`

 

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

[expect]

a already related to route basic-auth consumer should not be deleted.

**Comment by juzhiyuan** [comment]
ping @membphis @nic-chen

**Comment by juzhiyuan** [comment]
ping @membphis @nic-chen

**Comment by nic-chen** [comment]
@ShiningRush As discussed before,  I think we should support this feature similar to `foreign key constraints`
 in the refactored `manager api` .

**Comment by ShiningRush** [comment]
OK, I will consider this issue tomorrow, and may need to have little change in architecture.

**Comment by nic-chen** [comment]
consumer and  auth plugins are not binding relation, if consumer be deleted, it just means not allow the consumer to access. I think is ok.

**Comment by liuxiran** [comment]
> consumer and auth plugins are not binding relation, if consumer be deleted, it just means not allow the consumer to access. I think is ok.

thank for your reply, which let me really understand that router and consumer are related through authentication plugins, not foreign key associations.

**Comment by juzhiyuan** [comment]
> OK, I will consider this issue tomorrow, and may need to have little change in architecture.

Hi @ShiningRush How about your consideration?

**Comment by juzhiyuan** [comment]
so this issue has been resolved? @ShiningRush

**Comment by nic-chen** [comment]
it's not a bug here.
