### ISSUE TITLE
Feature: debug a route online

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#469]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Online debugging would be convenient for users to test the route：**

1. support authentication

1. support to edit request params

1. support to show the response info

1. friendly UI  (swagger UI maybe a good choice,  Investigating～～)

**Comment by juzhiyuan** [comment]
ping @membphis @moonming

**Comment by liuxiran** [comment]
After research on swagger-ui, and tried to introduce [swagger-ui-react](https://www.npmjs.com/package/swagger-ui-react ) in our project, I found it would be a  feasible solution to do the online debug here, and the **demo** just like this:

1. add a [online debug] button in route list
![image](https://user-images.githubusercontent.com/2561857/93241981-b3c07880-f7b8-11ea-8f63-e730899b60b8.png)

1. click the debug button, get the route info, tranfer the data to the swagger json object, then render the debug page
![image](https://user-images.githubusercontent.com/2561857/93242244-13b71f00-f7b9-11ea-8d62-c7d62bd448d7.png)
![image](https://user-images.githubusercontent.com/2561857/93242400-57aa2400-f7b9-11ea-8ece-61d83fb15161.png)

1. click [Execute] button, directly initiate a cross-domain request to apisix, and then get response
![image](https://user-images.githubusercontent.com/2561857/93242763-e028c480-f7b9-11ea-9f90-598857335992.png)


The original design was to make a pure front-end function, but due to browser security restrictions, cross-domain requests initiated directly by the front-end cannot directly modify the Host attribute of the request header. This is inconsistent with our business logic, so **this function still needs to rely on manager-api to help forward the request**🤦‍♀️.

How about this proposal? Looking forward to your feedback,thanks @juzhiyuan

**Comment by juzhiyuan** [comment]
Looks good to me, and this needs a backend to proxy those different origins' requests, I guess this doesn't depend on DB, so feel free to go :D

**Comment by membphis** [comment]
That is a useful feature. We can use a specified header for testing. Any suggestion?

**Comment by juzhiyuan** [comment]
take a look at those requests sent from Swagger UI?

**Comment by membphis** [comment]
After researching, the test request does not require any specific request headers.

On the dashboard, it directly simulates the user's request. Very good function, look forward to.
