### ISSUE TITLE
Proposal: Health Checks for Upstream

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#470]
![image](https://user-images.githubusercontent.com/2106987/92912746-b0498c00-f45c-11ea-98eb-0a6a5078f6fa.png)

## Why
Doc: https://github.com/apache/apisix/blob/master/doc/health-check.md

## How
Active and passive checks exist in parallel in the upstream module as separate configurations, they should obey the following rules.
1. All disabled: Only show the Ant Design Switcher components for those two fields, no more configuration form；
2. Enable active check: show its configuration form；
3. Enable passive check
	1. Check if the active check is enabled, if not, just show a warning notification by using Ant Design’s Notification component, and tell users to enable the active check first.
	2. If the active check is enabled, then users could enable the passive check and show its form.

## API
1. Test cases: https://github.com/apache/apisix/blob/master/t/admin/health-check.t#L61

## Reference
1. Logic: https://github.com/apache/apisix/blob/master/apisix/admin/upstreams.lua

**Comment by juzhiyuan** [comment]
ping @membphis @liuxiran

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/92921226-40d89a00-f466-11ea-92b9-350198d9256a.png)

**Comment by liuxiran** [comment]
> How about this design?

Agree with ui design 👍 ,  I have a question about interaction logic：

refer to the [upstream health-check doc:](https://github.com/apache/apisix/blob/master/doc/health-check.md) active check and passive check could  be configured independently 

and you also say：

> Active and passive checks exist in parallel in the upstream module as separate configurations

why does `Enable passive check` depend on the  active check is enabled?

**Comment by juzhiyuan** [comment]
Good catch, @membphis, could you please describe this logic?

**Comment by juzhiyuan** [comment]
Even though we could use Passive Check only, but because once the upstream is down, the Gateway doesn't know when to recover just like Active Check does.

**Comment by liuxiran** [comment]
> Even though we could use Passive Check only, but because once the upstream is down, the Gateway doesn't know when to recover just like Active Check does.
> 
> So we choose to use Passive check only when the Active check is enabled :D

so, is it necessary to update the [documentation](https://github.com/apache/apisix/blob/master/doc/health-check.md), add this description?

**Comment by juzhiyuan** [comment]
It's not a hurry :D because we could use Active Health Check and Passive Health Check independent, but we recommend enabling active health check when enabling passive health check.

**Comment by juzhiyuan** [comment]
hi @liuxiran, would you like to implement this feature (if you have free time)?

**Comment by liuxiran** [comment]
> hi @liuxiran, would you like to implement this feature (if you have free time)?

yes, waiting for my pr :)(later this week)

**Comment by liuxiran** [comment]
`active.type` is mentioned in the test case [=== TEST 6: invalid route: wrong active.type](https://github.com/apache/apisix/blob/8493a607ce869ab335eac1d0e799ffecff10fb93/t/admin/health-check.t#L239), but no details in the api doc, so there is nothing about it in pr. If this key is needed, it would be better to update doc first :)

**Comment by juzhiyuan** [comment]
> `active.type` is mentioned in the test case [=== TEST 6: invalid route: wrong active.type](https://github.com/apache/apisix/blob/8493a607ce869ab335eac1d0e799ffecff10fb93/t/admin/health-check.t#L239), but no details in the api doc, so there is nothing about it in pr. If this key is needed, it would be better to update doc first :)

hi @moonming @nic-chen @membphis Could you take a look at this test case? I cound't find the `active.type` property either :(

**Comment by juzhiyuan** [comment]
@liuxiran I just had a quick discussion with @membphis, he will help you to make sure if the `type` filed is needed :D

**Comment by liuxiran** [comment]
> @liuxiran I just had a quick discussion with @membphis, he will help you to make sure if the `type` filed is needed :D

ok, thanks :), waiting for @membphis `s conclusion
