### ISSUE TITLE
Support Service

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#471]
![image](https://user-images.githubusercontent.com/2106987/92917544-2b14a600-f461-11ea-97bc-65bd916921fd.png)

## Why
Service is aimed to pre config the upstream and plugins and would be referenced when creating a route.
This proposal is aimed to build the Service module only, as for referencing a service when creating a route, this will be discussed when this module is implemented according to this proposal.

## How
Service contains both List and Detail(Create/Edit) page.

### List Page
It’s aimed to show a list of services, some basic fields like desc, update_time, create_time will show on the list. I would recommend using Ant Design’s [Protable](https://protable.ant.design/) component. 

### Detail Page
It contains 3 step pages
1. Desc filed(textarea) and Upstream module；
2. [Plugin module](https://github.com/apache/apisix-dashboard/issues/448);
3. Preview page.

**Comment by juzhiyuan** [comment]
@membphis Please take a look once more, thanks!

**Comment by membphis** [comment]
Allow users to directly fill in the upstream address, we can support this feature later.

**Comment by juzhiyuan** [comment]
> Allow users to directly fill in the upstream address, we can support this feature later.

Just to make sure, does this mean users could fill in the Upstream Form manually instead of choosing a existing one? This will be implemented in the Upstream Form :D

**Comment by LiteSun** [comment]
any update? @juzhiyuan

**Comment by juzhiyuan** [comment]
no, don't have a detailed proposal to support this feature, just moved it to next milestone.
