### ISSUE TITLE
Publish route failed

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#474]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
Codes on the master

- What happened?
![image](https://user-images.githubusercontent.com/2106987/93174519-ae374400-f760-11ea-9815-69590853a143.png)

ping @liuxiran @nic-chen

**Comment by liuxiran** [comment]
something like mysql has not been updated, Will mysql be updated synchronously when the demo environment updated? @juzhiyuan

**Comment by juzhiyuan** [comment]
not sure, cc @nic-chen

**Comment by nic-chen** [comment]
I had updated mysql, you could have a try again. @juzhiyuan @liuxiran

**Comment by liuxiran** [comment]
> I had updated mysql, you could have a try again. @juzhiyuan @liuxiran

passed 👍
