### ISSUE TITLE
What is the default account password of the dashboard?

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#478]
Please answer these questions before submitting your issue.

### Question
- What is the default account password of the dashboard?

**Comment by liuxiran** [comment]
admin/admin 😊

**Comment by Caelebs** [comment]
我用admin/admin登录后端apisix内部的NGINX日志有报错
```
2020/09/16 16:52:09 [warn] 38#38: *559800 [lua] ctx.lua:82: __index(): failed to fetch cookie value by key: cookie_x_api_key error: nil, client: 10.20.12.27, server: , request: "POST /apisix/admin/user/login HTTP/1.0", host: "10.20.8.63:9080", referrer: "http://10.10.16.250:30927/user/login?redirect=%2Fuser%2Flogin"
2020/09/16 16:52:09 [warn] 38#38: *559800 [lua] init.lua:95: handler(): failed to check token: missing apikey, client: 10.20.12.27, server: , request: "POST /apisix/admin/user/login HTTP/1.0", host: "10.20.8.63:9080", referrer: "http://10.10.16.250:30927/user/login?redirect=%2Fuser%2Flogin"
```
前台页面提示账号密码错误...
@liuxiran

**Comment by bzp2010** [comment]
@Caelebs Please check API response by `Chrome Developer Tools (F12)`.

Normally, the response is similar to this.
`  
{  
  "data": {  
    "token": "A JWT string"  
  }  
}  
`

**Comment by Caelebs** [comment]
不好意思我英文不好还是中文描述吧
我这边尝试过注释掉服务端apisix配置文件config.yaml文件中admin_key这一段，这一段注释掉之后前台登录时候user/login接口直接报404，还有这个admin_key配置中的key值我应该怎样生成？
所以我又把注释掉的那一段还原回去，重新部署之后环境以及恢复到之前的状态，登录报错信息和之前的一样
```
2020/09/16 18:23:08 [warn] 37#37: *17282 [lua] ctx.lua:82: __index(): failed to fetch cookie value by key: cookie_x_api_key error: nil, client: 10.20.12.29, server: , request: "POST /apisix/admin/user/login HTTP/1.0", host: "apisix-gw-lb:9080", referrer: "http://10.10.16.250:30927/user/login?redirect=%2F"
2020/09/16 18:23:08 [warn] 37#37: *17282 [lua] init.lua:95: handler(): failed to check token: missing apikey, client: 10.20.12.29, server: , request: "POST /apisix/admin/user/login HTTP/1.0", host: "apisix-gw-lb:9080", referrer: "http://10.10.16.250:30927/user/login?redirect=%2F"
```

前端页面控制台看了下报错401 Authorization Required
但是cookie里面有token
![image](https://user-images.githubusercontent.com/12752710/93325508-06964080-f84a-11ea-816f-2b7780125e1b.png)

![image](https://user-images.githubusercontent.com/12752710/93325561-157cf300-f84a-11ea-9d8a-c1ea1958251b.png)
@bzp2010

**Comment by bzp2010** [comment]
@Caelebs 
It seems that the Manager API is not using the latest version. Can you try to update it?
Explanation: in the previous update, the login API was adjusted from `/user/login` to `/apisix/admin/user/login`, and the frontend code of the dashboard was also updated synchronously. However, in previous versions, API requests prefixed with `/apifix/admin` would be filtered through the filter, and the error request would be returned to HTTP 401.

看起来原因可能是Manager API没有使用最新版本，可以尝试进行更新吗？
解释：登录API在之前的更新中由 `/user/login` 调整至 `/apisix/admin/user/login` ，dashboard前端代码也同步进行了更新，然而在之前的版本以 `/apifix/admin` 前缀的API请求会经由filter进行过滤，并对错误请求返回HTTP 401。

**Comment by Caelebs** [comment]
我重新部署了一下，manager-api的镜像是基于**apisix-dashboard-1.5**这个包里面的/api目录下的Dockerfile构建的，运行起来之后/root/manager-api目录下的conf.json配置看起来应该是正常的
```
{
  "conf": {
    "mysql":{
      "address": "apisix-mysql",
      "user": "root",
      "password": "123456",
      "maxConns": 50,
      "maxIdleConns": 25,
      "maxLifeTime": 10
    },
    "syslog": {
      "host": ""
    },
    "apisix": {
      "base_url": "apisix-gw-lb",
      "api_key": "edd1c9f034335f136f87ad84b625c8f1"
    }
  }
}
```
启动时的日志输出看起来也没有报错
```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env:	export GIN_MODE=release
- using code:	gin.SetMode(gin.ReleaseMode)
[GIN-debug] GET /ping --> github.com/apisix/manager-api/route.healthzHandler.func1 (5 handlers)
[GIN-debug] POST /apisix/admin/routes --> github.com/apisix/manager-api/route.createRoute (5 handlers)
[GIN-debug] GET /apisix/admin/routes/:rid --> github.com/apisix/manager-api/route.findRoute (5 handlers)
[GIN-debug] GET /apisix/admin/routes --> github.com/apisix/manager-api/route.listRoute (5 handlers)
[GIN-debug] PUT /apisix/admin/routes/:rid --> github.com/apisix/manager-api/route.updateRoute (5 handlers)
```
然后dashboard容器内nginx配置文件default.conf里边配置的proxy_pass地址是这样的
```
location /apisix/admin {
        proxy_pass http://apisix-manager-api:8080/apisix/admin;
    }
```
manager-api依赖的MySQL也是可用的，初始化的consumers、routes、ssls、upstreams四张表也创建好了的
我理解是apisix-dashboard指向apisix-manager-api:8080，apisix-manager-api指向后端apisix的base_url，不知道这样对不对？
现在的情况就变成了dashboard登录的时候前台页面提示
```
请求错误，错误码： 404
发出的请求针对的是不存在的记录，服务器没有进行操作。
```
```
10.20.0.0 - - [17/Sep/2020:08:48:32 +0000] "POST /apisix/admin/user/login HTTP/1.1" 404 18 "http://10.10.16.250:30999/user/login?redirect=%2Fapisix%2Fdashboard%2F" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36 Maxthon/5.2.7.4000" "-"
```

我不确定是我的部署方式有问题还是哪儿的配置有问题？
apisix的版本和dashboard应该是配套的，都是用的1.5
```
sh-4.2# apisix version
1.5
```
给整懵了
@bzp2010 @juzhiyuan

**Comment by Caelebs** [comment]
。。。
发现是apisix-dashboard-1.5这个包构建出来的manager-api和apisix1.5可能不配套，用当前最新代码重新构建了一下manager-api的镜像现在可以登录了，数据库的表多了一张。。。

**Comment by juzhiyuan** [comment]
> 。。。
> 发现是apisix-dashboard-1.5这个包构建出来的manager-api和apisix1.5可能不配套，用当前最新代码重新构建了一下manager-api的镜像现在可以登录了，数据库的表多了一张。。。

Yep, codes between the master and the 1.5 branches have a lot of changes, please use the latest codes on the master branch, a new version should release this month.

**Comment by juzhiyuan** [comment]
It looks working for you when using codes from the master branch, I will close this issue, feel free to reopen it.
