### ISSUE TITLE
Plugin configuration not available

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#487]
#387 # Question
- What do you want to know?

VM85:1 GET http://10.10.16.249/apisix/admin/plugins **400** (Bad Request)
界面提示“请启用至少一种身份认证类插件”
![image](https://user-images.githubusercontent.com/12752710/93663750-af3bde80-fa9c-11ea-8176-39b22af11411.png)

{"code":"010301","msg":"find APISIX plugin list failed: status: 404, body: {\"error_msg\":\"failed to match any routes\"}\n"}

**Comment by juzhiyuan** [comment]
it seems that this API doesn't work on your side, could you provide more information about how to deploy it?

**Comment by juzhiyuan** [comment]
Cannot reproduce this issue according to the latest commit[1], if this issue still occurred, please provide your installation steps, tks.

[1] https://github.com/apache/apisix-dashboard/commit/3c7ddb70c5f172d96ee6fd17775e052205ad29d3
