### ISSUE TITLE
Plugin Orchestration: Plugin Category

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#490]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Before starting this issue, please provide an UI design.

**Comment by juzhiyuan** [comment]
1. Uniformity of style: generalization and organization (research, prototyping).
2. Functionality: is the current organization of interactions appropriate? bugs?

**Comment by LiteSun** [comment]
In order to categorize the plugins in the Plugin Orchestration mode, I drew a design diagram, as shown below.

![image](https://user-images.githubusercontent.com/31329157/93994427-74021e00-fdc2-11ea-8c1b-fe369254785c.png)

1. When clicking on all, all the plugins will appear below. Similarly, when clicking on category one, only plugins belonging to category one will be displayed. 

2. The display plugins will be sorted in descending order based on frequency of use.

3. The interaction logic of the Plugin Orchestration is the same as before.

@moonming @membphis @juzhiyuan Please take a look at this interaction logic when you have time to see if there are any problems, thanks!

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/94003354-b3823780-fdcd-11ea-9768-c4b76b5d6751.png)

Looks good to me! is this a Tab area? the antd supports scrollable Tab.

**Comment by LiteSun** [comment]
yes,  but it is unfriendly for a user to use Tab when the Category name is too long. so I change Tab to Select list.

![image](https://user-images.githubusercontent.com/31329157/94096403-934a8b00-fe56-11ea-8310-684c5fb6c933.png)

@juzhiyuan @moonming @membphis

**Comment by membphis** [comment]
> so I change Tab to Select list.

This one is better.

**Comment by covalentbond** [comment]
hey @juzhiyuan, I saw this issue https://issues.apache.org/jira/browse/APISIX-12 `Apache APISIX Dashboard: Enhancement plugin orchestration`. I would like to know, is it still open and if yes, how can I start contributing towards this as a beginner

**Comment by covalentbond** [comment]
In the skills of the issue, React, HTML, CSS & Javascript were mentioned. And I pretty much like them.
But the repository also have Golang. Is it a required skill to work on this issue

**Comment by juzhiyuan** [comment]
Hi @covalentbond, this issue is reported by @LiteSun, let's wait for his reply :)

**Comment by LiteSun** [comment]
Hi, @covalentbond 

1. The [issue](https://issues.apache.org/jira/browse/APISIX-12) is open and if you want to contribute please refer to [contributing](https://github.com/apache/apisix-dashboard/blob/master/CONTRIBUTING.md#how-to-add-a-new-feature-or-change-an-existing-one) ,For develop front-end, please refer to [web-contributing](https://github.com/apache/apisix-dashboard/blob/master/CONTRIBUTING.md#how-to-add-a-new-feature-or-change-an-existing-one).

2. Golang is not a required skill if you just want to develop the front-end.

3. Plugin Orchestration was introduced to the apisix-dashboard project by installing dependencies.

If you want to participate in the development of Plugin Orchestration.

  -  please go to the [dashboard-components](https://github.com/api7/dashboard-components) repository to complete the development.
  - update the version of apisix-dashboard dependency @api7-dashboard/pluginchart.

Contact me if you have any questions.😊
Can't wait to see your PR!👍👍👍

**Comment by covalentbond** [comment]
Sure! I would start by understanding what APISIX is all about and how plugins function in it
