### ISSUE TITLE
improve i18n

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#493]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
- [ ] i18n contributing guide

### Module
- [ ] Plugins
- [ ] Route
- [ ] Route Group
- [ ] Upstream
- [ ] Consumer
- [ ] SSL
- [ ] Login

**Comment by liuxiran** [comment]
I have a pr on the way to modify i18n refer to the Proposal #331, which have been Interrupted by feature development, 
If there are no major changes about the proposal, I'll continue to complete this pr later this week.  @juzhiyuan

**Comment by juzhiyuan** [comment]
> I have a pr on the way to modify i18n refer to the Proposal #331, which has been Interrupted by feature development,
> If there are no major changes about the proposal, I'll continue to complete this pr later this week. @juzhiyuan

feel free to go :D
