### ISSUE TITLE
Using Disable property from APISIX for Plugin

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#495]
- [ ] Disable https://github.com/apache/apisix/pull/2099/files#diff-ed26f75979353d43aa8168d799d931d0R609

**Comment by juzhiyuan** [comment]
@membphis It seems that this property doesn't exist in the response body.

**Comment by juzhiyuan** [comment]
Only when FE sends the disable property to API, then API will response that field.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/100492128-8868eb00-3164-11eb-8d62-6ef5a4b5b84c.png)

![image](https://user-images.githubusercontent.com/2106987/100492143-974f9d80-3164-11eb-8d7b-589280a770f9.png)

Just to make sure, it seems that the manager-api doesn't support this feature now? Do we have any plan about this?

**Comment by nic-chen** [comment]
Looks like it need to modify the code to achieve it? I thought the schema had been modified before.

**Comment by membphis** [comment]
> Looks like it need to modify the code to achieve it?

yes, you can take a look at the processes of APISIX

**Comment by juzhiyuan** [comment]
ok, go ahead.

**Comment by juzhiyuan** [comment]
will be fixed in #815
