### ISSUE TITLE
Use Admin API directly instead of Manager API (frontend)

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#498]
As titled

due date: before 10/10/2020

cc @ShiningRush @moonming @nic-chen @LiteSun

**Comment by juzhiyuan** [comment]
@nic-chen @ShiningRush Please deploy an API Server before 27/09/2020.

**Comment by juzhiyuan** [comment]
@nic-chen will help to deal with the issue about "How to resolve those fields in MySQL".

cc @liuxiran

**Comment by nic-chen** [comment]
We have three problems to solve:
1. publish and offline
as discussed before, we could implement this feature on APISIX

2. route group
I think `labels` is enough for us to group routes or other stuff.
what do you think?  @liuxiran @membphis  

3. relational database features
such as:
https://github.com/apache/apisix-dashboard/issues/466

**Comment by liuxiran** [comment]
> 2. route group
>    I think `labels` is enough for us to group routes or other stuff.
>    what do you think?  @liuxiran @membphis

Agree 😊, It would be more flexible.

>I had checked other sql schema, I think we don’t need to deal with other columns that existed in mysql and not in etcd >temporarily, such as create_time, update_time.

Some users may be concerned about the update time, so that they can trace a resource changes.
so if these fields would not be stored in etcd, maybe it still needs a place where the front end can get it. what do you think? @juzhiyuan @LiteSun

**Comment by juzhiyuan** [comment]
What do you think? @nic-chen @membphis @ShiningRush

**Comment by nic-chen** [comment]
@juzhiyuan  
I had deployed a online demo for refactored manager api, here is the host and port: 40.73.92.163:8080

but there are some problems, such as: 
https://github.com/apache/apisix-dashboard/issues/519
that means you need to specify a ID when create resource.

**Comment by nic-chen** [comment]
@juzhiyuan 
For API parameters, please refer to: https://github.com/apache/apisix/blob/master/doc/admin-api.md

**Comment by juzhiyuan** [comment]
> @juzhiyuan
> For API parameters, please refer to: https://github.com/apache/apisix/blob/master/doc/admin-api.md

I'd like to know only APIs listed in this file have been implemented? how about those APIs?
1. `/notexist/routes`
2. `/names/routegroups`
3. `/names/upstreams`
4. `check_ssl_exists`

etc

**Comment by nic-chen** [comment]
not support relational query yet, so these APIs can't be implemented, and it will take some time

**Comment by juzhiyuan** [comment]
It means all features related to those APIs will be removed from frontend..

**Comment by ShiningRush** [comment]
> I'd like to know only APIs listed in this file have been implemented? how about those APIs?
Here is anyone can tell me what those apis used for?

**Comment by juzhiyuan** [comment]
> > @juzhiyuan
> > For API parameters, please refer to: https://github.com/apache/apisix/blob/master/doc/admin-api.md
> 
> I'd like to know only APIs listed in this file have been implemented? how about those APIs?
> 
> 1. `/notexist/routes`
> 2. `/names/routegroups`
> 3. `/names/upstreams`
> 4. `check_ssl_exists`
> 
> etc

1. `/notexist/routes`: to check if there has an existing route with same name? (maybe, cc @nic-chen)
2. `/names/routegroups`: check if there has a group with the same name
3. `/names/upstreams`: xxx
4. `check_ssl_exists`: to check if there has a related host with SSL certificate.
5. `check_ssl_cert`: to check if the Key and Cert could be compared, and it will return the encrypted data from Certificate.
6. xxx Not sure if there have other APIs.
