### ISSUE TITLE
Online debug failed

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#499]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
master branch
http://139.217.190.60/routes/a944d256-4a51-4349-a8fd-f632b93bfa23/debug

- What happened?
If possible, provide a way to reproduce the error.

![image](https://user-images.githubusercontent.com/2106987/93838643-faccd300-fcbc-11ea-9dab-d6e64e5bd444.png)

**Comment by juzhiyuan** [comment]
cc @liuxiran

**Comment by liuxiran** [comment]
> cc @liuxiran

whether the manager-api updated at the same time?

**Comment by juzhiyuan** [comment]
oh no... @nic-chen

**Comment by nic-chen** [comment]
here is the error log:
>
{"app":"manager-api","level":"error","line":"filter/recover.go:49","msg":"[Recovery] 2020/09/22 - 14:04:07 panic recovered:\n\nruntime error: index out of range [0] with length 0\n/usr/local/go/src/runtime/panic.go:75 (0x42efa2)\n/go/src/github.com/apisix/manager-api/route/route.go:529 (0xa3371c)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bbcea)\n/go/src/github.com/apisix/manager-api/filter/recover.go:53 (0x9ee90a)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bbcea)\n/go/src/github.com/apisix/manager-api/filter/logging.go:54 (0x9edac8)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bbcea)\n/go/src/github.com/apisix/manager-api/filter/request_id.go:40 (0x9eead8)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bbcea)\n/go/src/github.com/apisix/manager-api/filter/authentication.go:64 (0x9ec3b6)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bbcea)\n/go/src/github.com/apisix/manager-api/filter/cors.go:31 (0x9ed61a)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bbcea)\n/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.3/sessions.go:52 (0x9e88fd)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bbcea)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9c5c2c)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9c532d)\n/usr/local/go/src/net/http/server.go:2802 (0x6e1cb3)\n/usr/local/go/src/net/http/server.go:1890 (0x6dd554)\n/usr/local/go/src/runtime/asm_amd64.s:1357 (0x4602b0)\n","time":"2020-09-22T14:04:07+08:00"}

**Comment by juzhiyuan** [comment]
cc @liuxiran

**Comment by liuxiran** [comment]
after testing, online demo site still return 500 on debug page.
so if the online site updated automaticly,  would  you please provide a way to view the log， or last update log here?  many thanks😊 @nic-chen 

and I also have a question , the api `/apisix/admin/routes/:rid/debuginfo` which is added to get route details with Apisix url (because fe has to send the debug request directly to apisix，so I need the apisix url here) works well in my Local docker environment， but got 500 in online demo site, maybe it is caused by configuration( we did not consider enough when analyzing the parameters),so would you please provide `apisixBaseUrl` config in the demo site, thanks again~!

**Comment by nic-chen** [comment]
@liuxiran 
`base_url` is:
http://apisix-admin-svc:9080/apisix/admin

I think we should  judge the value of res before using it :
https://github.com/apache/apisix-dashboard/blob/master/api/route/route.go#L535

**Comment by liuxiran** [comment]
> @liuxiran
> `base_url` is:
> http://apisix-admin-svc:9080/apisix/admin
> 
> I think we should judge the value of res before using it :
> https://github.com/apache/apisix-dashboard/blob/master/api/route/route.go#L535

thanks a lot, I'll updated soon🤝

**Comment by liuxiran** [comment]
online debug page is Available ，but the debug request still failed.

* reason
After communicating with @nic-chen , The online site is a network environment where the internal and external networks are isolated. This would also be a common deployment strategy. 
At present, the baseURl obtained by reading conf.json is an intranet address and cannot be used for online debug

* solution
try to add a config item in the conf.json, which used to configure debugUrl, that would fix the https://github.com/apache/apisix-dashboard/blob/69199d22dd30e47a71c191060a0402d43633addf/src/pages/Route/transform.ts#L353 together

**Comment by juzhiyuan** [comment]
@liuxiran, after the incoming fix, does it support mock server? 

cc @moonming Could you please leave your question or confusion here?

**Comment by liuxiran** [comment]
> @liuxiran, after the incoming fix, does it support mock server?

the debug requires Apisix to forward the request to the corresponding upstream, it would support mock server only when mock server can complete this forwarding job :)

**Comment by juzhiyuan** [comment]
got it, tks!
