### ISSUE TITLE
Failed to compile dashboard

### ISSUE THREAD

**Issue by spacewander** [apache/apisix-dashboard#500]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___

This issue is migrated from https://github.com/apache/apisix/issues/2272
> #2. I tried to build dashboard, go build needs to import following:
"github.com/apisix/manager-api/conf"
"github.com/apisix/manager-api/log"
"github.com/apisix/manager-api/route"
However I kept getting the errors saying those cannot found. I even tried to do, say: go get github.com/apisix/manager-api/conf, etc. they could not be found. I searched the github and unable to find them. Please advise on this.

> #3, Since I could not move forward with #2, I tried to do docker for the dashboard. again it failed with timed-out for what it looked like that something to with GoProxy tried to dial tcp 119.28.201.50:443 I tried to see what the ip address seemed to be un-resolvable. I m from US and didnt think I needed GoProxy. so please advise on this as well.

**Comment by spacewander** [comment]
CC @MrLightSpeed0

**Comment by MrLightSpeed0** [comment]
Hi I disabled the GoProxy. but got the same error. so it is for something else. I am behind a company proxy and I do have http_proxy and https_proxy set up in the system since I was able to do: "go get github.com/something" to download with no issue. no sure why this "dial tcp..." failed...  Thank you.

``` ---> Running in 4ac697c8d207

go: github.com/api7/apitest@v1.4.9: Get https://proxy.golang.org/github.com/api7/apitest/@v/v1.4.9.mod: dial tcp 172.217.4.49:443: connect: network is unreachable
ERROR: Service 'manager' failed to build: The command '/bin/sh -c mkdir /go/manager-api     && go build -o /go/manager-api/manager-api     && mv /go/src/github.com/apisix/manager-api/build.sh /go/manager-api/     && mv /go/src/github.com/apisix/manager-api/conf/conf_preview.json /go/manager-api/conf.json     && rm -rf /go/src/github.com/apisix/manager-api     && rm -rf /etc/localtime     && ln -s  /usr/share/zoneinfo/Hongkong /etc/localtime     && dpkg-reconfigure -f noninteractive tzdata' returned a non-zero code: 1
```

**Comment by juzhiyuan** [comment]
ping @nic-chen

**Comment by nic-chen** [comment]
> Hi I disabled the GoProxy. but got the same error. so it is for something else. I am behind a company proxy and I do have http_proxy and https_proxy set up in the system since I was able to do: "go get github.com/something" to download with no issue. no sure why this "dial tcp..." failed... Thank you.
> 
> ```
> 
> go: github.com/api7/apitest@v1.4.9: Get https://proxy.golang.org/github.com/api7/apitest/@v/v1.4.9.mod: dial tcp 172.217.4.49:443: connect: network is unreachable
> ERROR: Service 'manager' failed to build: The command '/bin/sh -c mkdir /go/manager-api     && go build -o /go/manager-api/manager-api     && mv /go/src/github.com/apisix/manager-api/build.sh /go/manager-api/     && mv /go/src/github.com/apisix/manager-api/conf/conf_preview.json /go/manager-api/conf.json     && rm -rf /go/src/github.com/apisix/manager-api     && rm -rf /etc/localtime     && ln -s  /usr/share/zoneinfo/Hongkong /etc/localtime     && dpkg-reconfigure -f noninteractive tzdata' returned a non-zero code: 1
> ```

It works fine on my machine. I think it's a network issue. you could set `https://goproxy.cn` as `GOPROXY` (in https://github.com/apache/apisix-dashboard/blob/master/api/Dockerfile#L23-L24) and try again.

**Comment by juzhiyuan** [comment]
ok then, closed now.

**Comment by MrLightSpeed0** [comment]
Hello you said the dial tcp error was related to my network. I will check on that. that is the for question #3 (build with docker). what about #2, could you please help on that? copy it here for your quick reference:

#2. I tried to build dashboard, go build needs to import following:
"github.com/apisix/manager-api/conf"
"github.com/apisix/manager-api/log"
"github.com/apisix/manager-api/route"
However I kept getting the errors saying those cannot found. I even tried to do, say: go get github.com/apisix/manager-api/conf, etc. they could not be found. I searched the github and unable to find them. Please advise on this.

**Comment by juzhiyuan** [comment]
> Hello you said the dial tcp error was related to my network. I will check on that. that is the for question #3 (build with docker). what about #2, could you please help on that? copy it here for your quick reference:
> 
> #2. I tried to build dashboard, go build needs to import following:
> "github.com/apisix/manager-api/conf"
> "github.com/apisix/manager-api/log"
> "github.com/apisix/manager-api/route"
> However I kept getting the errors saying those cannot found. I even tried to do, say: go get github.com/apisix/manager-api/conf, etc. they could not be found. I searched the github and unable to find them. Please advise on this.

@nic-chen Please take a look at this one.

**Comment by nic-chen** [comment]
> Hello you said the dial tcp error was related to my network. I will check on that. that is the for question #3 (build with docker). what about #2, could you please help on that? copy it here for your quick reference:
> 
> #2. I tried to build dashboard, go build needs to import following:
> "github.com/apisix/manager-api/conf"
> "github.com/apisix/manager-api/log"
> "github.com/apisix/manager-api/route"
> However I kept getting the errors saying those cannot found. I even tried to do, say: go get github.com/apisix/manager-api/conf, etc. they could not be found. I searched the github and unable to find them. Please advise on this.

`github.com/apisix/manager-api` is  `apisix-dashboard/api`
please take a look at :
https://github.com/apache/apisix-dashboard/blob/master/api/go.mod#L1

**Comment by juzhiyuan** [comment]
Still don't know how to resolve this issue :(

@MrLightSpeed0 Could you please provide a detailed installation steps? so I could try to reproduce this issue.

**Comment by MrLightSpeed0** [comment]
Hello. I was following the steps mentioned on this page: https://github.com/apache/apisix-dashboard
I was at this step 4 Build 
 cd api && go build -o ../manager-api . && cd ..
 and got following error:
`main.go:24:2: cannot find package "github.com/apisix/manager-api/conf" in any of:
        /usr/src/github.com/apisix/manager-api/conf (from $GOROOT)
        /root/go/src/github.com/apisix/manager-api/conf (from $GOPATH)
main.go:25:2: cannot find package "github.com/apisix/manager-api/log" in any of:
        /usr/src/github.com/apisix/manager-api/log (from $GOROOT)
        /root/go/src/github.com/apisix/manager-api/log (from $GOPATH)
main.go:26:2: cannot find package "github.com/apisix/manager-api/route" in any of:
        /usr/src/github.com/apisix/manager-api/route (from $GOROOT)
        /root/go/src/github.com/apisix/manager-api/route (from $GOPATH)`
what do I need to set for $GOPATH and $GOROOT. I am running this as root.

**Comment by juzhiyuan** [comment]
ok, we will test and resolve this issue before 1.6 release.

**Comment by juzhiyuan** [comment]
but could @nic-chen give some suggestions about this issue? not sure if it's a bug or a tricky issue 🤔

**Comment by nic-chen** [comment]
I think it's not a bug. 
more like doc guidance issue.
@MrLightSpeed0  had you enable `go module`?

**Comment by juzhiyuan** [comment]
Please enable Go module
