### ISSUE TITLE
PluginModule: check every plugin's schema & form usability

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#501]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

As the title says.

- [ ] https://github.com/apache/apisix-dashboard/issues/516

**Comment by LiteSun** [comment]
The following plugins perform incorrectly：fault-injection、cors、request-validation

**Comment by juzhiyuan** [comment]
ok, then what schema they should be? could you help have a try here[1]? just like this issue[2].

[1] https://rjsf-team.github.io/react-jsonschema-form/
[2] https://github.com/apache/apisix/issues/2082#issue-681772868

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/apisix/issues/2082
