### ISSUE TITLE
create a consumer only enable openid-connect plugin return a warning blocks the next step

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#509]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

I tried to create a consumer only enabled `openid-connect` plugin, and press [nextStep], then got a warning: `Please enable at least one authentication plugin`. 
![image](https://user-images.githubusercontent.com/2561857/94093591-2502ca00-fe50-11ea-8272-800659961753.png)

and I checked the code: https://github.com/apache/apisix-dashboard/blob/69199d22dd30e47a71c191060a0402d43633addf/src/pages/Consumer/Create.tsx#L71

`openId-connect` does not match the rule indeed, **so change the plugin-name or change the match rule or just keep the degin？**

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
yes, could you help modify this checker? just like a whitelist?

**Comment by liuxiran** [comment]
> yes, could you help modify this checker? just like a whitelist?

OK
