### ISSUE TITLE
using dashboard for a while , the token expired

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#511]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [*] Requirements
- [ ] Feature or performance improvement
- [ ] Other

when i login with admin account and using dashboard for a while , the token expired, i think it's not user-friendly...

**Comment by membphis** [comment]
Is the refresh of the token done on the front end? Or `manage API`?

**Comment by juzhiyuan** [comment]
There have 2 ways to implement this feature:
1. Implement this feature on the backend, so if the token should expire is rely on some cache DB, e.g Redis.
2. JWT with Refresh logic, just like Wechat OAuth[1] does.

[1] https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Authorized_Interface_Calling_UnionID.html

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/102738511-4f97ec80-4385-11eb-91b9-fd5e422d851c.png)
