### ISSUE TITLE
Dashboard build failed on import /manager-api step

### ISSUE THREAD

**Issue by MrLightSpeed0** [apache/apisix-dashboard#513]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
This is related to ticket number 500, someone closed it but I didnt get the answer. copying it here for reference:

#2. I tried to build dashboard, go build needs to import following:
"github.com/apisix/manager-api/conf"
"github.com/apisix/manager-api/log"
"github.com/apisix/manager-api/route"
However I kept getting the errors saying those cannot found. I even tried to do, say: go get github.com/apisix/manager-api/conf, etc. they could not be found. I searched the github and unable to find them. Please advise on this. Thank you

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
duplicate with https://github.com/apache/apisix-dashboard/issues/500
