### ISSUE TITLE
bug：Did not check the settings of selected pulgins when ceate or edit consumer

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#517]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

when Create or edit Consumer, click "next step" button ,it only checked if enable Authentication plugin but not check any settings of selected pulgins, even if they were set to empty, no error is prompted.

**Comment by juzhiyuan** [comment]
The schema for every enabled plugin would validate if it's ok to use, empty data is ok because some plugins allow this.
