### ISSUE TITLE
request help: dashboard 404

### ISSUE THREAD

**Issue by MrJLuo** [apache/apisix-dashboard#518]
### Issue description
![image](https://user-images.githubusercontent.com/24730937/93179490-51d82280-f768-11ea-94b1-b7128fa5718d.png)
![image](https://user-images.githubusercontent.com/24730937/93179554-67e5e300-f768-11ea-89c8-d82474560d97.png)
![image](https://user-images.githubusercontent.com/24730937/93179750-b2675f80-f768-11ea-9e63-b55ec5df2bdf.png)

The nginx static resource file cannot be requested through the dashboard. How should nginx.conf be configured?
### Environment
linux

* apisix version (cmd: `apisix version`):v1.5

* OS:linux

**Comment by juzhiyuan** [comment]
It seems that you are using the elder version,  please use the latest one from the master branch.
