### ISSUE TITLE
discuss: how should we automatically generate a primary key  for new resource

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#519]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

When creating a new resource, we should automatically generate a primary key value instead of [letting the client provide one](https://github.com/apache/apisix-dashboard/blob/refactor/api/internal/core/store/store.go#L189).

Here is the question:
Should we generate a uuid as the primary key value, or should we use etcd revision as the primary key value like [APISIX admin api](https://github.com/apache/apisix/blob/master/apisix/core/etcd.lua#L253)?

**Comment by nic-chen** [comment]
@ShiningRush @membphis @moonming @gxthrj

**Comment by moonming** [comment]
I prefer to etcd revision, which is more easy to trace and will not conflict in cluster.

**Comment by ShiningRush** [comment]
I understand the scenario we are taking about is that user does not give primary key in `PUT` request, right?

**Comment by nic-chen** [comment]
> I understand the scenario we are taking about is that user does not give primary key in `PUT` request, right?

it should be `POST` which means `create`

**Comment by ShiningRush** [comment]
OK, I got it. I think it not a good way that using etcd revision as key.
When two request arrive the server at same time, the later request will cover the former, because them maybe get the same revision.
uuid is a little heavy(128bit), snowflake is fine(64bit), how do you think?

**Comment by membphis** [comment]
> uuid is a little heavy(128bit), snowflake is fine(64bit), how do you think?

I think we can make a try with `snowflake` .

**Comment by juzhiyuan** [comment]
agree with Snowflake!

**Comment by moonming** [comment]
> agree with Snowflake!

lgtm
