### ISSUE TITLE
Bug: i18n errors in route step1(Define API Request)

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#524]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
master branch

- What happened?
If possible, provide a way to reproduce the error.

when I set `redirect` to `custom` in route step1,  the i18n issues are as follows. 

![image](https://user-images.githubusercontent.com/31329157/94505018-c1f0a900-023c-11eb-8f1f-7cd10a8c5fe0.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by LiteSun** [comment]
Possible relevant PR: #522

**Comment by liuxiran** [comment]
> Possible relevant PR: #522

yes, sorry to miss updating the key in jsx, 
`route.request.config.redirect.custom` -> `page.route.form.itemLabel.redirectCustom`
`route.request.config.redirect.custom.example` -> `page.route.input.placeholder.redirectCustom`
`route.request.config.redirect.301` -> `page.route.select.option.redirect301`
`route.request.config.redirect.302` -> `page.route.select.option.redirect302`

**Comment by juzhiyuan** [comment]
@liuxiran hi, do you have time to resolve this issue? If that’s ok, feel free to assign to yourself :D

**Comment by liuxiran** [comment]
> @liuxiran hi, do you have time to resolve this issue? If that’s ok, feel free to assign to yourself :D

ok, I'll resolve this issue, 
I could not assign to myself now,  maybe you have to help to assign to me for a few days, thanks
