### ISSUE TITLE
bug: Got 500 error when select redis policy in limit-count plugin

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#525]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

Version: the latest master
Os: Fedora 32
Browser: google chrome

- What happened?
If possible, provide a way to reproduce the error.

1. create a route, enable limit-count plugin, configurations:
```json
{
  "coun": 10,
  "key": "remote_addr",
  "policy": "redis",
  "redis_port": 6379,
  "redis_timeout": 1000,
  "rejected_code“: 503,
  “time_window”: 60
}
```

2. got a 500 error: `Failed to create APISIX route: status: 400, body: {"error_msg":"failed to check the configuration of plugin limit-count err: failed to validate dependent schema for \"policy\": value should match only one schema, but matches none"}`

![2020-09-29 10-22-13屏幕截图](https://user-images.githubusercontent.com/2561857/94506011-fe250900-023e-11eb-9cb3-490f86caa566.png)
![2020-09-29 10-23-15屏幕截图](https://user-images.githubusercontent.com/2561857/94506020-02e9bd00-023f-11eb-961e-4345f9d1ce1f.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
@nic-chen, need your time to check this issue, not sure if it's related to this plugin's data. thanks.

**Comment by nic-chen** [comment]
@liuxiran 

please take a look at the `limit-count`'s schema 

https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count.lua#L77

**Comment by juzhiyuan** [comment]
ok then it should be a bug on plugin, let me fix it.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/96825409-9f306980-1463-11eb-9ca1-318ff1338583.png)

Just have a try on the latest codes in the master branch, it seems that this issue has been resolved, feel free to reopen it whenever this issue occurred.
