### ISSUE TITLE
wolf-rbac can't add to plugin page

### ISSUE THREAD

**Issue by xtthaop** [apache/apisix-dashboard#527]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
why wolf-rbac can't add to plugin page?

This is the reference document for me: https://github.com/iGeeky/apisix-plugin-rbac

I'm sure I've moved the wolf-rbac.lua to the right place
I try to add it in config.yaml and config.default.yaml, all failed!

![截屏2020-09-29 下午7 58 26](https://user-images.githubusercontent.com/34789109/94555635-7b2b9f00-028e-11eb-8733-a530924b6f06.png)

I find the array returned by backend API has wolf-rbac, but the consumer page is not displayed

![截屏2020-09-29 下午8 08 05](https://user-images.githubusercontent.com/34789109/94556380-8cc17680-028f-11eb-95ca-4a3cb19faad4.png)

However,  the route management page display it in the drag plugin

![截屏2020-09-29 下午8 16 23](https://user-images.githubusercontent.com/34789109/94557132-be870d00-0290-11eb-9939-5a9a068fb047.png)

I wonder if there are configuration files in the frontend, but i can't find it. Is there any other way? Or is it only used by backend API?

**Comment by liuxiran** [comment]
the `wolf-rbac` configed `hidden: true` in the plugin components
https://github.com/api7/dashboard-components/blob/cc1cace9c046040b0c930d56980f055632fc3f03/packages/plugin/src/data.tsx#L98

so it would not shown in the plugin page.

Is there a plan to show it in plugin page @juzhiyuan ?

**Comment by juzhiyuan** [comment]
cc @moonming, should we show this plugin in frontend? I forget why we choosed to hide it 🤔 maybe the UI is broken before?

**Comment by vcoolwind** [comment]
@juzhiyuan 
What time does wolf-rbac can be show in dashboard as default?
This feature is urgently needed.

**Comment by juzhiyuan** [comment]
should be added when releasing 1.6, 1 week currently,

**Comment by juzhiyuan** [comment]
once this PR gets merged, this issue would be resolved.

https://github.com/apache/apisix-dashboard/pull/579/commits/ba44ca304d96f11f88deaa9bdb7721fa70c56747
