### ISSUE TITLE
discuss: improve the UE of config Authentication plugins

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#529]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Why
The Authentication plugins, e.g: `basic-auth` `openid-connect` and other auth plugins supported by Apisix should work with consumer together. Only when one auth plugin is enabled and configed correctly can a consumer be created or modified, and can access a route which is also enabled the same auth plugin. At the same time, a route or a service can enabled the auth plugin  without any configs(even if configured here, the auth plugin configuration of consumer will  matched by default).

RIght now, the auth plugins can be configed both in consumer and route, but the auth config in route doesn't really work, and it will Induce user that only the configed consumer can access the route. So it would be better to improve the UE of config auth plugins.

### Proposal

1. the authentication plugins should be enabled with configuration in consumer module.
![2020-09-30 10-44-11屏幕截图](https://user-images.githubusercontent.com/2561857/94637854-2843fd00-030b-11eb-96bf-0029ab13105a.png)

1. the authentication plugins should be only shown with a switch to enabled/disabled in route or service module.
![2020-09-30 10-44-11屏幕截图](https://user-images.githubusercontent.com/2561857/94637879-33972880-030b-11eb-9177-3363b573ae96.png)

1. right now if a route enabled two auth plugins, it should be matched with this two auth token, In fact, it is not possible for users to access the same route using two or more different authentication methods. so it would be better to only enabled one auth plugin in route.

**Comment by liuxiran** [comment]
@juzhiyuan  @LiteSun @bzp2010

**Comment by juzhiyuan** [comment]
Got your point, you mean for Auth plugins, we should only config it in Consumer instead of Route, and we COULD choose to enable or disable it in Route instead of cobfig, right?

I agree to this proposal, how about others suggestions? 

cc @membphis @nic-chen @moonming ?

**Comment by membphis** [comment]
agree with this proposal too.

https://github.com/apache/apisix/issues/2308 , if we support this feature, the dashboard will easier.

**Comment by nic-chen** [comment]
agree +1

**Comment by liuxiran** [comment]
> Got your point, you mean for Auth plugins, we should only config it in Consumer instead of Route, and we COULD choose to enable or disable it in Route instead of cobfig, right?
> 
> I agree to this proposal, how about others suggestions?
> 
> cc @membphis @nic-chen @moonming ?

yes you got my point @juzhiyuan 🤝,  and furthermore, if the authentication plugin can be turned into the consumer’s default support plugin, just like `proxy-rewrite` in route, that would be better, but the cost of plugin modification may be higher

**Comment by juzhiyuan** [comment]
yep, let's implement your proposal first :D

**Comment by juzhiyuan** [comment]
I just put this feature in M1.7.

**Comment by juzhiyuan** [comment]
I checked this issue once more, and it seems that the backend should support this feature too 🤔 @liuxiran @membphis right?

**Comment by liuxiran** [comment]
> I checked this issue once more, and it seems that the backend should support this feature too  @liuxiran @membphis right?

thanks for @juzhiyuan 's reminder,  I also rethinked this issue, and IMHO, it is better to get support from BE:

- get `whether the plugin needs to be config` together with `category` of all plugins instead of only get plugin names from `GET /apisix/admin/plugins`

`whether the plugin needs to be config` could also not be a specific flag, FE can also judge from whether the [plugin].schema.properties is empty, in this case , api should return the schema at the same time.

**Comment by juzhiyuan** [comment]
This solution works for me, but it seems that there still has also a lot of work to do, could you please take a look at this issue? cc @membphis @tokers.

**Comment by membphis** [comment]
We can create a new API to return all the information of the plug-in, such as `schema`, `type`, `priority`, etc.

For example the new API: `/apisix/admin/plugins/meta_attributes`, we need to discuss it on the mailing list first. 

@liuxiran would like to handle this job?

**Comment by liuxiran** [comment]
> We can create a new API to return all the information of the plug-in, such as `schema`, `type`, `priority`, etc.
> 
> For example the new API: `/apisix/admin/plugins/meta_attributes`, we need to discuss it on the mailing list first.
> 
> @liuxiran would like to handle this job?

sure, I have already sent a mail to dev, just waiting for others' comments and suggestions :)

**Comment by juzhiyuan** [comment]
Hi folks, final conclusion here?

**Comment by membphis** [comment]
@liuxiran I think we can close this issue and create a new one with the final conclusion from the emailing list.

**Comment by liuxiran** [comment]
> @liuxiran I think we can close this issue and create a new one with the final conclusion from the emailing list.

got it , and as we talked yesterday., this issue would be move to M2.3, right? @membphis

**Comment by membphis** [comment]
yes, confirm this @liuxiran

**Comment by juzhiyuan** [comment]
any update?

**Comment by liuxiran** [comment]
after the new api `GET /plugins?all=ture` finished, I will open a new issue to trace the process. close it now.
