### ISSUE TITLE
插件配置->普通模式缺少grpc-transcode配置

### ISSUE THREAD

**Issue by tanjiancheng** [apache/apisix-dashboard#530]
I want to use grpc-transcode can be configure in the dashboard but it is miss that

and found
https://github.com/api7/dashboard-components/blob/master/packages/plugin/src/data.tsx

```
'grpc-transcode': {
    category: 'Other',
    hidden: true,
 },
```
why this is hide，may be not finish the cpanel about this plugin？

**Comment by juzhiyuan** [comment]
not sure, let me have a check on its panel ASAP 🤔

**Comment by tanjiancheng** [comment]
@juzhiyuan thanks，the plugin maybe have two feature

1、like /apisix/admin/proto/<id> to save proto file content
2、like /apisix/admin/routes/<id> to save route rules and upstream
