### ISSUE TITLE
fetching category for plugins from APISIX

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#532]
~~related issue https://github.com/apache/apisix/issues/2308~~

```
GET /plugins?all=true
```

**Comment by juzhiyuan** [comment]
waiting for https://github.com/apache/apisix/issues/2308#issuecomment-735024172

**Comment by membphis** [comment]
backend todo things:

- [ ] sync tools: support to sync more field(eg: type)
- [ ] API: `/plugins?all=true`
