### ISSUE TITLE
bug: respond status of api should keep same as `admin api` do

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#537]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug

after refactor, respond status of api should keep same as `admin api` do.
but it's always 200 currently.
I think we need to fix it in `github.com/shiningrush/droplet`

@ShiningRush  please take a look.

**Comment by ShiningRush** [comment]
We only need to ensure that the data structure is the same as that of AdminAPI, not the response code.
Using response codes to check the result is not a good way,this will increase the complexity of the front-end, and can not enumerate all situations

**Comment by nic-chen** [comment]
As far as I know, some users have already used `http status` in their system, if we do not maintain the original `http status `, they will have to modify the code. 

Moreover, the response status code of the admin api complies with `resful` specifications. 

The workload of front-end changes need @juzhiyuan  to take a look

**Comment by juzhiyuan** [comment]
Please follow the RESTful way, thanks.

**Comment by ShiningRush** [comment]
OK, I will add a new field for `Response` to control http status code this afternoon.

**Comment by juzhiyuan** [comment]
After discussions, the frontend will use the Logic Code instead of standard HTTP Status code to check if this request is successful.
