### ISSUE TITLE
bug: authentication security issue

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#538]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug

We should not use a fixed value as the default secret key of jwt token. 

If the user does not modify the default Secret key, then others can generate tokens, and the account and password are useless. 

I think we need to randomly generate a secret key during the first run.

**Comment by juzhiyuan** [comment]
would this be fixed in 1.6 before 16.10?

**Comment by nic-chen** [comment]
I think we could fix it in 1.6

**Comment by nic-chen** [comment]
fixed.
