### ISSUE TITLE
bug: [refactor] test case run failed sometimes

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#539]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug

in refactored CI, test cases are not stable and sometimes fail.

https://github.com/apache/apisix-dashboard/runs/1221212550#step:7:78

**Comment by juzhiyuan** [comment]
not sure what happened, cc @ShiningRush

**Comment by ShiningRush** [comment]
The iteration of map is unordered, so occasionally it will fail. I will fix this use case later.
