### ISSUE TITLE
feature: [refactor] support json schema check

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#540]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Requirement or improvement

We need to pull the right version of the json schema definition from Apache APISIX, and perform schema verification on the apis which will change data, to ensure that the data is correct.

**Comment by juzhiyuan** [comment]
May I ask if this issue would be resolved in 1.6?

**Comment by nic-chen** [comment]
done.
