### ISSUE TITLE
feature: [refactor] run Apache APISIX's `admin api` test cases in dashboard

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#541]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirement or improvement

We need to run Apache APISIX's `admin api` test cases in dashboard to ensure that the refactored api is correct and can be compatible with APISIX.

**Comment by juzhiyuan** [comment]
resolved?
