### ISSUE TITLE
feature: [refactor] embedding static files into Go binaries

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#542]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirement or improvement

We need to embed static files into Go binaries, 

so that we don't need to deploy an additional nginx ,

and it will be very easy to use.

**Comment by juzhiyuan** [comment]
@bzp2010 is working on this issue, please let @nic-chen know whenever there have any blocker issues.

**Comment by bzp2010** [comment]
Work branch: [Click Here](https://github.com/bzp2010/apisix-dashboard/pull/1)
Github Workflow: [Click Here](https://github.com/bzp2010/apisix-dashboard/blob/master/.github/workflows/api_newci.yml)

## feature
- [x] Packing (It worked on my own computer)
> It's use [rakyll/statik](https://github.com/rakyll/statik) library.
- [ ] build by Github Actions

## problem 
- The binary program provided by `rakyll/statik` is used for packaging, but after executing the go get instruction in GitHub Actions, the program is not in the path directory and needs to be processed.

**Comment by juzhiyuan** [comment]
cc @nic-chen @gxthrj Could anyone help @bzp2010 to resolve this problem?
