### ISSUE TITLE
[refactor] license issue of refactored `api` 

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#546]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [x] Other

___
### Requirement or improvement

need to use the right way to fix license issue because some code is copied from Kubernetes dashboard, and current way is not right.

#535 
https://github.com/apache/apisix-dashboard/pull/535/files#r499468721

**Comment by moonming** [comment]
ok, I will fix it

**Comment by nic-chen** [comment]
add:
https://github.com/apache/apisix-dashboard/pull/551/files#r503025206

**Comment by juzhiyuan** [comment]
Should notice this issue before releasing, cc @LiteSun \

**Comment by LiteSun** [comment]
We need to remove `api/internal/core/store/validate_mock.go` and `api/internal/core/storage/storage_mock.go` manually before releasing.
