### ISSUE TITLE
bug: API后端服务配置域名的bug

### ISSUE THREAD

**Issue by tangjun2012** [apache/apisix-dashboard#547]
### Issue description
我是艾佳生活公司的开发，使用apisix时遇到如下问题，具体如下图，在1.5版本中，配置域名的时候，在目标服务器接收到的是ip，而不是域名，如：http://dashboard.apisix.dev/routes/4b84e67a-f874-4554-b3f6-906306116860/edit
即：我有多个域名指向了同一台服务器，对应不同的服务，其中ip=>服务A，域名1=>服务b，域名2=>服务c，当我在网关里配置域名1的时候，访问的却是服务A而不是正确的服务b

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

![image](https://user-images.githubusercontent.com/8478093/95642579-dd30a380-0adb-11eb-9005-eeb64b0852f3.png)

**Comment by juzhiyuan** [comment]
We should check what is the Request Body sent to API, then check if this issue is related to frontend or backend, this issue would be addressed before 1.6 release.

**Comment by moonming** [comment]
@tangjun2012 Did you specify the host header of domain name 1 in your client request? If not, you will meet the current situation

**Comment by tangjun2012** [comment]
![image](https://user-images.githubusercontent.com/8478093/95650022-79c26800-0b13-11eb-82a5-df4df685149f.png)
我这边已经修复了，是go项目的api里没有将header里的host信息写到host参数中导致的

**Comment by juzhiyuan** [comment]
cc @nic-chen

**Comment by moonming** [comment]
@tangjun2012 welcome PR to fix it, thx

**Comment by juzhiyuan** [comment]
The new version doesn't have this issue any more.
