### ISSUE TITLE
Cannot find wolf-rabc in the plugin list when creating consumer

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#554]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Bug

___
### Question

Reference document link [wolf-rbac](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/wolf-rbac.md)
When I created a consumer referring to the content of this document, I found that wolf-rabc could not be found in the plugin list?
![image](https://user-images.githubusercontent.com/12752710/95853899-b21eac00-0d88-11eb-830e-c58b29660008.png)

The dashboard version is 1.5 & apisix version 1.5

**Comment by juzhiyuan** [comment]
will be fixed in 1.6
