### ISSUE TITLE
bug: when etcd had dirty data, API Server  start fail 

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#555]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

```
$ etcdctl get --prefix "/apisix"
/apisix/consumers/
init_dir
/apisix/global_rules/
init_dir
/apisix/node_status/
```
ping @nic-chen

**Comment by juzhiyuan** [comment]
It would be more clear to say API server starts failed

**Comment by nic-chen** [comment]
fix
