### ISSUE TITLE
apisix升级问题

### ISSUE THREAD

**Issue by jealone** [apache/apisix-dashboard#560]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

问一下，如果现有服务用的apisix1.4版本，但是没有部署基于mysql的dashboard，如果要升级到新的dashboard

1. 是否需要升级apisix？
2. dashboard是否会拉取原有的etcd数据作为管理数据？

**Comment by nic-chen** [comment]
It is suggested that you can wait for version 2.0 and upgrade it together.

**Comment by idbeta** [comment]
it will thankful if If you can rephrase your question in EN

**Comment by juzhiyuan** [comment]
the newer dashboard will use data from etcd directly.

**Comment by juzhiyuan** [comment]
Hi @jealone , we have released the 2.0 RC version, kindly have a look at https://github.com/apache/apisix-dashboard/tree/v2.0#deployment
