### ISSUE TITLE
The 1.5 version of the dashboard cannot be edited again to display the previous settings

### ISSUE THREAD

**Issue by lizeming** [apache/apisix-dashboard#562]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
Apache APISIX Dashboard 1.5
Chrome 85.0.4183.121
Windows 10 Profession 1909

- What happened?
In the 1.5 version of the dashboard, after editing the HTTP header, rewriting and saving, the editing content before entering the editing again cannot be displayed. If you continue to the next step and save, the previous editing content will disappear.

![Snipaste_2020-10-17_19-43-04](https://user-images.githubusercontent.com/897138/96336355-b52fda00-10b1-11eb-94dc-a984738faa54.jpg)
![Snipaste_2020-10-17_19-43-29](https://user-images.githubusercontent.com/897138/96336356-b5c87080-10b1-11eb-8d8c-a734f33c151d.jpg)
![Snipaste_2020-10-17_19-47-45](https://user-images.githubusercontent.com/897138/96336361-ba8d2480-10b1-11eb-94f6-791d5a17ccbb.jpg)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Check this issue after the master branch gets updated.

**Comment by juzhiyuan** [comment]
This issue no longer exists in v2.0, will be released soon.
