### ISSUE TITLE
In the third step of editing routing in the new version of dashboard, the configuration item of proxy rewrite is missing in normal mode

### ISSUE THREAD

**Issue by nirvanareborn** [apache/apisix-dashboard#565]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirem1ents
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- In the third step of editing routing in the new version of dashboard, the configuration item of proxy rewrite is missing in normal mode

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Will be added in the release soon
