### ISSUE TITLE
[refactor][discuss] do we need to support int as ID ? 

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#567]
In APISIX ID could be int or string:
https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L28

do we need to support int as ID after refactored?

**Comment by nic-chen** [comment]
cc @membphis @ShiningRush @moonming

**Comment by moonming** [comment]
I think we don't need to support int as ID.
String is enough.

**Comment by juzhiyuan** [comment]
the string is enough, and just keep one style, please.

**Comment by ShiningRush** [comment]
string + 1

**Comment by membphis** [comment]
string +1

**Comment by nic-chen** [comment]
OK, I think we got an agreement.

**Comment by membphis** [comment]
For this question, do we need to do anything else in the future?
