### ISSUE TITLE
[refactor]missing refactoring apis

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#571]
here is the list:

- [x] /apisix/admin/schema/*

- [x] /apisix/admin/plugins/*

- [ ] /apisix/admin/global_rules

- [ ] /apisix/admin/plugin_metadata

- [ ] /apisix/admin/stream_routes

not used in dashboard, but if we want to replace `admin api` with `manager api`, we need to refactor them.

**Comment by juzhiyuan** [comment]
Implement in 2.3?

**Comment by membphis** [comment]
`/apisix/admin/global_rules`

we need this API in milestone `2.3`. @nic-chen I think we can create a new issue about this

**Comment by nic-chen** [comment]
has a new issue to track for it, so close this now.
