### ISSUE TITLE
为什么mysql不需要指定库名，如果不是给root，会发生什么

### ISSUE THREAD

**Issue by aogg** [apache/apisix-dashboard#580]
如题

还有建表语句是什么，代码中怎么没有找到

文档有提到的，是哪里的
$ mysql –uroot –p123456
> source ./api/script/db/schema.sql

是不是master目前不能用，只能用1.5，然后库名必须固定为manager  ？？

**Comment by juzhiyuan** [comment]
MySQL will be removed from the new release soon

**Comment by aogg** [comment]
> MySQL will be removed from the new release soon

现在master分支的版本不用数据库那，数据是存储在哪里，用户docker部署的

**Comment by juzhiyuan** [comment]
etcd
