### ISSUE TITLE
Enable SSL module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#585]
- [ ] PATCH

**Comment by aogg** [comment]
是不是没有ssl设置，而且设置了*的就必须要*的证书，这个明显不对，之前都是可以自动读取ssl证书的。

还有必须要开放http和https的选择，否则https的上游是80，但上游会自动跳转https，这样apisix层就又代理到上游80端口，形成无限跳转（bug）

**Comment by juzhiyuan** [comment]
> 是不是没有ssl设置，而且设置了_的就必须要_的证书，这个明显不对，之前都是可以自动读取ssl证书的。
> 
> 还有必须要开放http和https的选择，否则https的上游是80，但上游会自动跳转https，这样apisix层就又代理到上游80端口，形成无限跳转（bug）

Good catch, just sent a PR to enable this module.
