### ISSUE TITLE
最新master分支构建，路由选择上游后报错

### ISSUE THREAD

**Issue by aogg** [apache/apisix-dashboard#586]
![image](https://user-images.githubusercontent.com/8998031/96839173-63090300-147b-11eb-8095-6ad0426297a8.png)
![image](https://user-images.githubusercontent.com/8998031/96839215-71571f00-147b-11eb-9d8a-ae8e05359b2f.png)
现在路由列表一直打不开，有点严重

**Comment by aogg** [comment]
manager_1    | {"app":"manager-api","level":"error","line":"filter/recover.go:49","msg":"[Recovery] 2020/10/22 - 15:29:44 panic recovered:\n\nruntime error: invalid memory address or nil pointer dereference\n/usr/local/go/src/runtime/panic.go:199 (0x44665b)\n/usr/local/go/src/runtime/signal_unix.go:394 (0x446498)\n/go/src/github.com/apisix/manager-api/internal/handler/route/route.go:141 (0xc8dd3d)\n/go/src/github.com/apisix/manager-api/internal/core/store/store.go:172 (0xc80f09)\n/usr/local/go/src/sync/map.go:333 (0x47cbb2)\n/go/src/github.com/apisix/manager-api/internal/core/store/store.go:167 (0xc7d803)\n/go/src/github.com/apisix/manager-api/internal/handler/route/route.go:123 (0xc8bbf1)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/middleware.go:18 (0xa14570)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/middleware/base.go:16 (0xa17d8e)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/middleware/traffic_log.go:77 (0xa17d99)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/middleware/base.go:16 (0xa15269)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/middleware/http_input.go:84 (0xa15274)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/middleware/base.go:16 (0xa176a1)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/middleware/http_resp_resharp.go:23 (0xa176ac)\n/go/pkg/mod/github.com/shiningrush/droplet@v0.2.1/pipe.go:84 (0xa14c91)\n/go/pkg/mod/github.com/shiningrush/droplet/wrapper/gin@v0.2.0/gin.go:39 (0xa194e6)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bc7ea)\n/go/src/github.com/apisix/manager-api/filter/recover.go:53 (0x9ef8ba)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bc7ea)\n/go/src/github.com/apisix/manager-api/filter/request_id.go:41 (0x9efb67)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bc7ea)\n/go/src/github.com/apisix/manager-api/filter/authentication.go:70 (0x9eebe3)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bc7ea)\n/go/src/github.com/apisix/manager-api/filter/cors.go:31 (0x9ef4aa)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bc7ea)\n/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.3/sessions.go:52 (0x9d780d)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9bc7ea)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9c672c)\n/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9c5e2d)\n/usr/local/go/src/net/http/server.go:2802 (0x6e9103)\n/usr/local/go/src/net/http/server.go:1890 (0x6e49a4)\n/usr/local/go/src/runtime/asm_amd64.s:1357 (0x460500)\n","time":"2020-10-22T15:29:44+08:00"}

**Comment by juzhiyuan** [comment]
this branch is unstable as README says, it will release soon.

**Comment by aogg** [comment]
那我要用什么分支，是不是整个项目都不可用的，
我试了1.5分支那个连插件都没有，添加路由就报错405还是多少

我能用哪里的代码，还要显示所有插件的

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/96839928-6650be80-147c-11eb-912e-235ae9ed3e5a.png)
现在master还有这个证书也是刚开始就报错了，啥都没动的时候

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/milestone/4

just waiting for this milestone to be completed

**Comment by aogg** [comment]
目前master-20201020分支是不是会相对稳定些

**Comment by juzhiyuan** [comment]
no, that branch is just a backup for 1.5 (MySQL needed), and the master branch aims to deprecate MySQL.

**Comment by aogg** [comment]
> no, that branch is just a backup for 1.5 (MySQL needed), and the master branch aims to deprecate MySQL.

运行起来master-20201020，不需要mysql的，但还是同样的报错，不能选择上游，你们应该重视起来当bug来修复。
然后怎么清理etcd的数据的，刚用上etcd还不太清楚怎么找到数据并删除 @juzhiyuan

**Comment by aogg** [comment]
master-20201020可用，有多插件，确实是mysql的但没报错
