### ISSUE TITLE
通过apisix代理到nginx在代理到apisix-dashboard，就报这个错误

### ISSUE THREAD

**Issue by aogg** [apache/apisix-dashboard#590]
2020/10/23 02:18:45 [warn] 38#38: *947042 [lua] ctx.lua:82: __index(): failed to fetch cookie value by key: cookie_x_api_key error: nil, client: 14.145.136.241, server: , request: "POST /apisix/admin/user/login HTTP/1.1", host: "apisix.my.com", referrer: "http://apisix.my.com/user/login?redirect=%2Fuser%2Flogin"
2020/10/23 02:18:45 [warn] 38#38: *947042 [lua] init.lua:95: handler(): failed to check token: missing apikey, client: 14.145.136.241, server: , request: "POST /apisix/admin/user/login HTTP/1.1", host: "apisix.my.com", referrer: "http://apisix.my.com/user/login?redirect=%2Fuser%2Flogin"

之前nginx直接代理apisix-dashboard是没有问题的

分支master-20201020

![image](https://user-images.githubusercontent.com/8998031/96948971-6ce14380-1519-11eb-8189-d27b282c1375.png)

**Comment by juzhiyuan** [comment]
You could have a try on the latest codes from the master branch, nearly stable.

**Comment by juzhiyuan** [comment]
codes from the master branch don't include MySQL anymore, totally different with codes from the `master-xxx` branch.

**Comment by aogg** [comment]
master分支有提示的啊，而且上一个提问你还说不稳定
Please Note: This branch is still under development, please DO NOT use this branch currently.



> You could have a try on the latest codes from the master branch, nearly stable.


重要是这个和是否使用mysql没有关系，是nginx代理相关的

**Comment by aogg** [comment]
failed to fetch cookie value by key: cookie_x_api_key

**Comment by membphis** [comment]
@aogg please use English in the public channel

**Comment by melotusme** [comment]
same problem, too.
I can't directly use apisix to proxy apisix-dashboard, while I can use nginx to proxy apisix-dashboard.

**Comment by juzhiyuan** [comment]
https://apisix.apache.org/docs/apisix/FAQ#how-to-access-apisix-dashboard-through-apisix-proxy

@melotusme Hi, please take a look at this link.
