### ISSUE TITLE
Based on NPM package, the plug-in list cannot be displayed

### ISSUE THREAD

**Issue by tangjun2012** [apache/apisix-dashboard#595]
Please answer these questions before submitting your issue.
基于npm的包，插件列表无法显示，具体错误如下：
![image](https://user-images.githubusercontent.com/8478093/97002965-5238ba00-156d-11eb-9824-e54eb36adf7a.png)

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Could you please paste the response (`/apisix/admin/plugins`) from Network panel.

**Comment by tangjun2012** [comment]
> Could you please paste the response (`/apisix/admin/plugins`) from Network panel.
After clearing folder node_modules，
run npm install 、 npm run dev to see my error

**Comment by juzhiyuan** [comment]
Just follow this doc to develop the dashboard.

https://github.com/apache/apisix-dashboard/blob/master/docs/develop.md
