### ISSUE TITLE
2.0版本控制台创建路由时proxy-rewrite插件错误提示，无法正常保存

### ISSUE THREAD

**Issue by nirvanareborn** [apache/apisix-dashboard#599]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
proxy-rewrite插件是否可以看下是Bug，还是我的使用方法不对？
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
version:2.0
- What happened?
If possible, provide a way to reproduce the error.
proxy-rewrite插件错误提示，无法正常保存
should NOT have fewer than 1 properties

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.
是否可以看下是Bug，还是我的使用方法不对？

**Comment by juzhiyuan** [comment]
Thanks for your report! This issue would be resolved before releasing 2.0.

**Comment by juzhiyuan** [comment]
added this issue here[1], please follow that issue.

[1] https://github.com/apache/apisix/issues/2082#issuecomment-714225553
