### ISSUE TITLE
limit-count options args without consumer_name?

### ISSUE THREAD

**Issue by hzbd** [apache/apisix-dashboard#601]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

```
$ apisix version
2.0

dashboard version
v2.0-rc1
```

- What happened?
If possible, provide a way to reproduce the error.
**limit count options args without consumer_name?**

https://raw.githubusercontent.com/apache/apisix-dashboard/v2.0/api/conf/schema.json

<img width="766" alt="WX20201026-154300@2x" src="https://user-images.githubusercontent.com/3000843/97146573-0a02dd00-17a3-11eb-892b-adb0307d67a3.png">
<img width="1174" alt="WX20201026-154859@2x" src="https://user-images.githubusercontent.com/3000843/97146602-15560880-17a3-11eb-8baf-a94ceeb49c32.png">

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Hi, in this RC version, please have a try according to https://github.com/apache/apisix-dashboard/blob/v2.0/docs/develop.md#sync-jsonschema

Also, don't forget to pull codes from 2.0 branch.

**Comment by juzhiyuan** [comment]
If the method above solves your issue, please close this issue :D

**Comment by hzbd** [comment]
Hi there,

It's worked. thank you.

Well BTW，Is there a scheduled time for the next release version? I want to use `limit count` by `consumer_name` in the production environment.

**Comment by juzhiyuan** [comment]
We are waiting for Dashboard 2.0’s RC feedbacks, it will be released no more than 7 days.
