### ISSUE TITLE
Etcd api version not match

### ISSUE THREAD

**Issue by jiayx** [apache/apisix-dashboard#602]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question

Apisix 1.5 is using etcd v2 api，apisix-dashboard using v3 api, so apisix-dashboard can't communicate with apisix
The user needs to be reminded

Apisix 1.5 使用的是 etcd v2 版本的 API，apisix-dashboard 使用的是 v3 API。在 etcd 中 v2 和 v3 的数据不互通，所以读取不到 apisix 的配置，感觉可以在文档中提醒一下

**Comment by juzhiyuan** [comment]
Would you like to send a PR about this issue when you have time?

**Comment by jiayx** [comment]
ok

**Comment by jiayx** [comment]
> Would you like to send a PR about this issue when you have time?

写在那个文件里比较合适？

**Comment by juzhiyuan** [comment]
how about README's FAQ section?
