### ISSUE TITLE
Do we need gin accesslog file?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#603]
![image](https://user-images.githubusercontent.com/2106987/97161222-763c0b80-17b8-11eb-8915-b57fca430533.png)

Please take a look at this file, is it necessary in 2.0?

**Comment by nic-chen** [comment]
we have error log，we could do this in 2.1

**Comment by nic-chen** [comment]
We could add a simple access log first. It is conducive for data analysis and problem location.

We could add advanced features later, such as custom fields and custom formats, log rotate, etc.
