### ISSUE TITLE
discuss: how to get different type of plugin schema in 2.0 manager-api

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#605]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Premise

Refered to https://github.com/apache/apisix/issues/2441#issuecomment-714330623, we are tring to implement the feature, that getting different plugin schema by schema type  through query params.

After refactoring, manager-api will get the plugin schema via [schema.json](https://github.com/apache/apisix-dashboard/blob/v2.0/api/conf/schema.json), which is generated by [schema-sync.sh](https://github.com/apache/apisix-dashboard/blob/v2.0/api/build-tools/schema-sync.sh) and [schema-sync.lua](https://github.com/apache/apisix-dashboard/blob/v2.0/api/build-tools/schema-sync.lua) instead of getting directly from admin-api

### Question

Is it possible to add this query param in 2.0 manager-api？ 

- change the plugin schema generated by `schema-sync.sh` and `schema-sync.lua` ?

- some other way?

**Comment by liuxiran** [comment]
cc @juzhiyuan @nic-chen @ShiningRush

**Comment by nic-chen** [comment]
@liuxiran 

I think we need to update two files:

1. update `schema-sync.lua` so that it can sync all types schemas.

2. update `internal/handler/plugin/plugin.go` so that it can get different plugin schema by type through query params

**Comment by nic-chen** [comment]
we could do this after the feature you mentioned is done.

**Comment by liuxiran** [comment]
> @liuxiran
> 
> I think we need to update two files:
> 
>     1. update `schema-sync.lua` so that it can sync all types schemas.
> 
>     2. update `internal/handler/plugin/plugin.go` so that it can get different plugin schema by type through query params

Thx for your feedback @nic-chen :), when the feature done, I`ll update  the comment.

**Comment by moonming** [comment]
@liuxiran @nic-chen 
I have been busy during this period and I did not see this issue. Welcome to post this kind of important discussion to the mailing list.
Going back to the problem of synchronization schema, what I hope to achieve in the end is:
1. The tool for synchronizing schema has nothing to do with the dashboard project. After all, this is a product that the data plane should generate;
2. When the schema of the data plane changes, there is no need to modify the code of this tool;
3. The dashboard project should not depend on Lua.

What do you think?

**Comment by membphis** [comment]
welcome to discuss this in mail list: 

https://lists.apache.org/thread.html/r83f31a15112b66e849ea28e073d11962dee77e5eb928c4f1e8deac10%40%3Cdev.apisix.apache.org%3E

**Comment by moonming** [comment]
@nic-chen will you lead this feature? We have reached a consensus on the mailing list

**Comment by nic-chen** [comment]
> @nic-chen will you lead this feature? We have reached a consensus on the mailing list

yes, of course.

**Comment by membphis** [comment]
@nic-chen do we will implement this feature in version `2.2`?

**Comment by nic-chen** [comment]
> @nic-chen do we will implement this feature in milestone `2.2`?

sure

**Comment by membphis** [comment]
related issue: https://github.com/apache/apisix/issues/2700

**Comment by nic-chen** [comment]
@membphis 
I think we could move it to 2.2 
what do you think?

**Comment by membphis** [comment]
> @membphis
> I think we could move it to 2.2
> what do you think?

agree, and set the milestone to `2.2`
