### ISSUE TITLE
manager服务构建docker镜像使用了可能不稳定的 apisix:master 分支

### ISSUE THREAD

**Issue by fregie** [apache/apisix-dashboard#608]
In api/Dockerfile:
```shell
RUN  wget https://github.com/apache/apisix/archive/master.zip \
     && apt-get update && apt-get install zip -y \
     && unzip master.zip \
     && rm -rf /go/manager-api/build-tools/apisix/ \
     && mkdir -p /go/manager-api/build-tools/apisix \
     && mv ./apisix-master/apisix/* /go/manager-api/build-tools/apisix/
```
使用master分支构建是不稳定的，比如我现在无法构建成功，修改为1.5分支后构建成功。
BTW，为什么manager服务要依赖apisix的代码？

**Comment by nic-chen** [comment]
@fregie It should be removwd.welcome PR ：）

**Comment by juzhiyuan** [comment]
This issue should be resolved in next release (no matter if it’s an RC)

**Comment by juzhiyuan** [comment]
Once this issue is resolved, we are going to publish it to DockerHub under Apache.

**Comment by juzhiyuan** [comment]
added related issue https://github.com/apache/apisix-dashboard/issues/615

**Comment by juzhiyuan** [comment]
The new Dockerfile is under development, so I will close this issue.
