### ISSUE TITLE
Publish the Dashboard to DockerHub under Apache

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#609]
related issue https://github.com/apache/apisix-dashboard/issues/608

- [ ] CI support
- [ ] Publish

**Comment by juzhiyuan** [comment]
Hi @totemofwolf would you have time to this issue?

**Comment by juzhiyuan** [comment]
Just sent the discussion mail

**Comment by juzhiyuan** [comment]
https://hub.docker.com/repository/docker/apache/apisix-dashboard

Just created.

cc @liuxiran @totemofwolf

**Comment by imjoey** [comment]
Hi @juzhiyuan , I noticed that currently the image is published to Azure Container Registry service triggered by every single commit. After we publish to Docker Hub, will be the Azure registry still in use? Thanks.

**Comment by juzhiyuan** [comment]
Azure is used to deploying a preview website, we will still use it for a long time IMO.

**Comment by imjoey** [comment]
> Azure is used to deploying a preview website, we will still use it for a long time IMO.

@juzhiyuan thanks for the explanations. Sorry for not knowing much of its usage.

**Comment by juzhiyuan** [comment]
Will publish images soon

https://hub.docker.com/r/apache/apisix-dashboard
