### ISSUE TITLE
Deploy Dashboard using RPM package

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#613]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other
___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

Build the Dashboard then package it as an RPM package.

- [ ] What's files does the RPM package needs? @nic-chen @ShiningRush 
- [x] Frontend: Files under `/dist` folder 
- [ ] Package @moonming

**Comment by juzhiyuan** [comment]
Hi @idbeta, could you please take a look at this issue? We need to package the Dashboard as an RPM package.

**Comment by membphis** [comment]
It is an easy job, welcome to take a look at this project(build APISIX RPM): 

https://github.com/api7/build-tools
https://github.com/api7/build-tools/blob/master/run.sh

**Comment by idbeta** [comment]
> Hi @idbeta, could you please take a look at this issue? We need to package the Dashboard as an RPM package.

sure, I have written the script, where do you think it is better to put this script?

**Comment by juzhiyuan** [comment]
not sure where to put that script is properly 🤔 How about utils?

**Comment by nic-chen** [comment]
we could upload the rpm package when release a new version

**Comment by juzhiyuan** [comment]
https://github.com/api7/build-tools/pull/7/files

cc @nic-chen @gxthrj
