### ISSUE TITLE
proposal: UI autotest

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#614]
# Background

Automated testing is very important to ensure quality. For apisix-dashboard, we need to add UI automated testing to CI.

# Plan

1. We plan to use the e2e test solution recommended by [antd](https://pro.ant.design/docs/ui-test#e2e-test), which is base on [Jest](https://jestjs.io/) and [Puppeteer](https://github.com/puppeteer/puppeteer).
2. We split the corresponding test cases according to different pages.
3. We will add an independent action integrated UI automated test in CI.

# Test cases

1. Login & Logout
- [ ] login: correct and incorrect password/username 
- [ ] logout

2. Metrics
- [ ] page jump:

3. Route
- [ ] create: long description and  name include common symbols
- [ ] edit:
- [ ] delete:
- [ ] search: full match, partial match, no match
- [ ] big data environment test: route operation under more than 200 routes

4. SSL
- [ ] enter correct certificate and private key:
- [ ] enter unmatched certificate and private key:
- [ ] upload correct certificate and private key:
- [ ] upload unmatched certificate and private key:

5.Upstream
- [ ] create: long description and  name include common symbols
- [ ] edit:
- [ ] delete:
- [ ] search: full match, partial match, no match
- [ ] big data environment test: upstream operation under more than 200 upstreams

6. Consumer
- [ ] create: not enable authentication plugin, create the same name consumer
- [ ] edit:
- [ ] delete:

7. Setting
- [ ] page jump:
- [ ] set grafana address:

related issue https://github.com/apache/apisix-dashboard/issues/44
@juzhiyuan @LiteSun

**Comment by LiteSun** [comment]
Any suggestions for this e2e test solution?
@liuxiran @bzp2010

**Comment by juzhiyuan** [comment]
Just hold on, give us no longer than 3 days to check this issue.

**Comment by juzhiyuan** [comment]
3. Route

a. Please adjust those cases' order, it should be: create, get, put, search, delete, get
b. how to generate 200+ records? through Puppeteer or admin API?

4. SSL
a. update case
b. delete case

6. Consumer
a. it should have all cases like Upstream or Route(CRUD)

7. Setting
a. Just set an URL then refresh and check if they are the same.

8. Other
a. Don't need check plugin currently, because the JSONSchema will check if the data is correct, and it's too complicated to check UI currently.

**Comment by moonming** [comment]
This proposal looks good to me.
If it is added to github actions, I suggest that each type of test use a separate action, so that it can be processed in parallel

**Comment by idbeta** [comment]
> * b. how to generate 200+ records? through Puppeteer or admin API?
> *
I think it should generate by backend API, but we could lower its priority.

**Comment by juzhiyuan** [comment]
I will close this tracking issue, for there have a lot of detailed issues to track.
