### ISSUE TITLE
chore: remove the dependency on `Lua` due to plugin orchestration 

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#618]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Requirements or improvement

we could use Lua VM in Go to replace Lua

**Comment by juzhiyuan** [comment]
Will this be implemented in 2.3?
