### ISSUE TITLE
requirement: Support custom listening IP and port for manager api

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#621]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Requirements or improvement

Need to support custom listening IP and port for manager api

**Comment by juzhiyuan** [comment]
This issue has been resolved in 2.0 RC2
