### ISSUE TITLE
apisix-dashboard 403 Forbidden

### ISSUE THREAD

**Issue by wangxunfan** [apache/apisix-dashboard#623]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [√] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
I want to know what caused it，I want to know how to solve this problem。
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
v1.5
linux (Red Hat 4.8.3-9)
chrome 70

- What happened?
If possible, provide a way to reproduce the error.
Deploy apifix 1.5 and apisx dashboard 1.5 according to the document, and enter the API SX dashboard interface. You can only view it but not save it.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Hi @wangxunfan, we are refactoring the new Dashboard 2.0, and it's under the 2.0 RC2 stage, would you like to have a try on the newer dashboard?

Here is the milestone: https://github.com/apache/apisix-dashboard/milestone/4
Here is the source codes(2.0 RC2): https://github.com/apache/apisix-dashboard/tree/v2.0

**Comment by juzhiyuan** [comment]
2.0 is totally different from 1.5, 2.0 doesn't have MySQL anymore, it's lighter and clearer, once you find any question, feel free to open issues and tell us.

This issue will be closed soon, we will not maintain 1.5 anymore.

**Comment by wangxunfan** [comment]
@juzhiyuan change 2.0。I can't log in to the system, 401 Authorization Required occurred，help。

**Comment by wangxunfan** [comment]
http://192.168.202.127:9080/apisix/admin/user/login
401 Authorization Required

**Comment by juzhiyuan** [comment]
> http://192.168.202.127:9080/apisix/admin/user/login
> 401 Authorization Required

In Dashboard 2.0, we are using 8080 as manager-api's port & frontend's port, it seems like you are using the older version? Would you please provide more detailed info?

**Comment by wangxunfan** [comment]
@juzhiyuan
1. Nginx error.log file printing missing api-key
2.Deploy apisix 2. 0 and apisix-dashboard v2.0 rc2 according to the document。
https://github.com/apache/apisix-dashboard/blob/master/docs/deploy.md#build-the-frontend
————————————
3.Ask a question. 
1)Where is manager-api's dist folder？
Reference fragment(deploy.md#build-the-frontend)
6. Move files under dist folder to manager-api's dist folder, then visit http://127.0.0.1:8080 in your browser, 8080 is the default listen port of manager-api.
2)api-key ，Is there a time limit？How to generate  a valid key.

**Comment by wangxunfan** [comment]
Nginx error.log file printing：
2020/10/29 07:28:32 [warn] 12213#12213: *28873 [lua] ctx.lua:83: __index(): failed to fetch cookie value by key: cookie_x_api_key error: no cookie found in the current request, client: 192.168.202.1, server: , request: "POST /apisix/admin/user/login HTTP/1.1", host: "192.168.202.127:9080", referrer: "http://192.168.202.127:9080/apisix/dashboard/user/login?redirect=%2Fapisix%2Fdashboard"
2020/10/29 07:28:32 [warn] 12213#12213: *28873 [lua] init.lua:95: handler(): failed to check token: missing apikey, client: 192.168.202.1, server: , request: "POST /apisix/admin/user/login HTTP/1.1", host: "192.168.202.127:9080", referrer: "http://192.168.202.127:9080/apisix/dashboard/user/login?redirect=%2Fapisix%2Fdashboard"


/app/apisix/conf

**Comment by wangxunfan** [comment]
/app/apisix/conf/nginx.conf：
server {
        listen 9080 reuseport;
        .....
        location /apisix/dashboard {
                allow 127.0.0.0/24;
                allow 192.168.202.0/24;
                allow 192.168.202.127;
                deny all;

            alias dashboard/;

            try_files $uri $uri/index.html /index.html =404;
        }

**Comment by juzhiyuan** [comment]
> @juzhiyuan
> 
> 1. Nginx error.log file printing missing api-key
>    2.Deploy apisix 2. 0 and apisix-dashboard v2.0 rc2 according to the document。
>    https://github.com/apache/apisix-dashboard/blob/master/docs/deploy.md#build-the-frontend
>    ————————————
>    3.Ask a question.
>    1)Where is manager-api's dist folder？
>    Reference fragment(deploy.md#build-the-frontend)
> 2. Move files under dist folder to manager-api's dist folder, then visit http://127.0.0.1:8080 in your browser, 8080 is the default listen port of manager-api.
>    2)api-key ，Is there a time limit？How to generate  a valid key.

It seems that you are using the wrong link.

https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy.md

**Comment by wangxunfan** [comment]
I found a problem.  
problem: 404 error , http://192.168.202.127:8080/
version: apisix-dashboard 2.0 RC2
file: ./api/run.sh
detail:  Processing without compilation in run.sh file ,base apisix-dashboard 2.0 RC2
I try to do: 
  cd /app/apisix/dashboard/
  ./api/build.sh
  ./api/run.sh

Reference: 
https://github.com/apache/apisix-dashboard/blob/master/docs/deploy.md#build-the-manager-api
3.Build and Run
$ ./api/run.sh &

**Comment by juzhiyuan** [comment]
hmmm @wangxunfan, I mean you are using old codes in the master branch, could you please have a try on the v2.0 branch?

https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy.md

**Comment by wangxunfan** [comment]
@juzhiyuan thanks,“deploy.md” file is very deatailed. Successfully deployed.

**Comment by juzhiyuan** [comment]
Glad to know that, kindly leave any questions in GitHub issues.

**Comment by cleverpig** [comment]
haha, Why don't modify the link in project page ?
it's old version deploy guide: https://github.com/apache/apisix-dashboard/blob/master/docs/deploy.md

**Comment by juzhiyuan** [comment]
> haha, Why don't modify the link in project page ?
> it's old version deploy guide: https://github.com/apache/apisix-dashboard/blob/master/docs/deploy.md

Because 2.0 is still in RC3, not a stable release, we are waiting for the release of RC3 :)

**Comment by cleverpig** [comment]
> > haha, Why don't modify the link in project page ?
> > it's old version deploy guide: https://github.com/apache/apisix-dashboard/blob/master/docs/deploy.md
> 
> Because 2.0 is still in RC3, not a stable release, we are waiting for the release of RC3 :)

ok! understand now~
