### ISSUE TITLE
Remove dependencies for Apache APISIX and lua

### ISSUE THREAD

**Issue by moonming** [apache/apisix-dashboard#626]
We should delete all the logic in this file, and users don't need to care about these details at all. We generate these files and put them in the code repo. @nic-chen

_Originally posted by @moonming in https://github.com/apache/apisix-dashboard/pull/598#discussion_r514088648_

**Comment by juzhiyuan** [comment]
Do we still have this issue? cc @nic-chen

**Comment by moonming** [comment]
@nic-chen ping

**Comment by nic-chen** [comment]
yes, we could remove them in 2.1

**Comment by nic-chen** [comment]
fixed by #1083
