### ISSUE TITLE
Route update prompts: scheme validate failed: (root): Additional property enabled is not allowed

### ISSUE THREAD

**Issue by jiayx** [apache/apisix-dashboard#627]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

Bug with routing updates. When the prometheus plugin is enabled, update route request prompts: `scheme validate failed: (root): Additional property enabled is not allowed`

路由更新时的 bug，当 prometheus 插件开启的时候，更新路由时会提示：`scheme validate failed: (root): Additional property enabled is not allowed`

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by LiteSun** [comment]
Would you please provide more info? I just try it on our [demo page](http://139.217.190.60/) and no bug found.

**Comment by jiayx** [comment]
> Would you please provide more info? I just try it on our [demo page](http://139.217.190.60/) and no bug found.

Click [this link](http://139.217.190.60/routes/326210800941269471/edit). Then click next > next > next > submit.

![image](https://user-images.githubusercontent.com/6910037/97559981-155f3e00-1a19-11eb-80c4-e8623e0a7697.png)

**Comment by LiteSun** [comment]
Bug confirmed. fix it soon.
