### ISSUE TITLE
Deploy with Docker：returned a non-zero code: 1

### ISSUE THREAD

**Issue by webtom-hzm** [apache/apisix-dashboard#628]
Step 1/17 : FROM golang:1.13.8 AS build-env
 ---> 3a7408f53f79
Step 2/17 : WORKDIR /go/src/github.com/apisix/manager-api
 ---> Using cache
 ---> 6bd80bc6d338
Step 3/17 : COPY . .
 ---> c0cb0a93e487
Step 4/17 : RUN mkdir -p /go/manager-api     && mkdir -p /go/manager-api/build-tools     && go env -w GOPROXY=https://goproxy.io,direct     && export GOPROXY=https://goproxy.io     && go build -o /go/manager-api/manager-api     && mv /go/src/github.com/apisix/manager-api/entry.sh /go/manager-api/     && mv /go/src/github.com/apisix/manager-api/build-tools/* /go/manager-api/build-tools/     && mv /go/src/github.com/apisix/manager-api/conf/conf_preview.json /go/manager-api/conf.json     && rm -rf /go/src/github.com/apisix/manager-api     && rm -rf /etc/localtime     && ln -s  /usr/share/zoneinfo/Hongkong /etc/localtime     && dpkg-reconfigure -f noninteractive tzdata
 ---> Running in c98e5ac5176d
go: downloading github.com/sirupsen/logrus v1.7.0
go: downloading github.com/shiningrush/droplet v0.2.1
go: downloading go.uber.org/zap v1.16.0

...........................................................
...........................................................

rm: cannot remove '/go/src/github.com/apisix/manager-api/internal/utils/consts': Directory not empty
rm: cannot remove '/go/src/github.com/apisix/manager-api/log': Directory not empty

ERROR: Service 'manager' failed to build: The command '/bin/sh -c mkdir -p /go/manager-api     && mkdir -p /go/manager-api/build-tools     && go env -w GOPROXY=https://goproxy.io,direct     && export GOPROXY=https://goproxy.io     && go build -o /go/manager-api/manager-api     && mv /go/src/github.com/apisix/manager-api/entry.sh /go/manager-api/     && mv /go/src/github.com/apisix/manager-api/build-tools/* /go/manager-api/build-tools/     && mv /go/src/github.com/apisix/manager-api/conf/conf_preview.json /go/manager-api/conf.json     && rm -rf /go/src/github.com/apisix/manager-api     && rm -rf /etc/localtime     && ln -s  /usr/share/zoneinfo/Hongkong /etc/localtime     && dpkg-reconfigure -f noninteractive tzdata' returned a non-zero code: 1

**Comment by LiteSun** [comment]
cc @juzhiyuan

**Comment by juzhiyuan** [comment]
related issue #381

**Comment by juzhiyuan** [comment]
Hi @webtom-hzm, because this has 1 existing related issue #381, so I close this now. Deploy with Docker is rewriting now, and will be fixed in 2.0 RC3.
