### ISSUE TITLE
add e2e test for config route with remote_addr or remote_addrs

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#631]
detail:

 - [ ]  add test case for config route with invalid remote_addr

 - [ ]  add test case for config route with  invalid remote_addrs 

 - [ ]  add test case for config route with remote_addr and remote_addrs at the same time

 - [ ]  add test case for config route with correct  remote_addr 

 - [ ]  verify the route just configured

 - [ ]  add test case for config route with correct remote_addrs 

 - [ ]  verify the route just configured

For background and description, please see:

https://github.com/apache/apisix-dashboard/issues/607

**Comment by idbeta** [comment]
Hi, please assign it to me.
