### ISSUE TITLE
add e2e test for config route with vars

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#633]
detail:

 - [ ]  add test case for config route with invalid args vars

 - [ ]  add test case for config route with  invalid cookie vars 

 - [ ]  add test case for config route with  invalid header vars 

 - [ ]  add test case for config route with correct  args vars 

 - [ ]  verify the route just configured

 - [ ]  add test case for config route with correct cookie vars 

 - [ ]  verify the route just configured

 - [ ]  add test case for config route with correct header vars 

 - [ ]  verify the route just configured

 - [ ]  add test case for config route with header vars and cookie vars  at the same time

 - [ ]  verify the route just configured

 - [ ]  add test case for config route with args vars  and cookie vars at the same time

 - [ ]  verify the route just configured

 - [ ]  add test case for config route with args vars  and  header vars at the same time

 - [ ]  verify the route just configured

 - [ ]  add test case for config route with args vars,  cookie vars and  header vars at the same time

 - [ ]  verify the route just configured

* in the above test cases, please use different operators at each case.

---

For background and description, please see:

https://github.com/apache/apisix-dashboard/issues/607

**Comment by idbeta** [comment]
Hi, I want to handle it
