### ISSUE TITLE
add e2e test for config route with priority

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#635]
detail:

 - [ ]  add test case for config route with wrong data type priority

 - [ ]  add test case for config route with correct  priority

 - [ ]  add test case for config route with another correct  priority

 - [ ]  add test case for config route without priority (default priority)

 - [ ]  verify the route just configured for priority

For background and description, please see:

https://github.com/apache/apisix-dashboard/issues/607

**Comment by idbeta** [comment]
Hi, please assigned to me.
