### ISSUE TITLE
add e2e test for config route with management fileds

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#638]
detail:

 - [ ]  add test case for config route with name and desc

 - [ ]  verify the route just configured with correct name and desc, and has create_time and update_time

 - [ ]  add test case for update route  with other name and desc

 - [ ]  verify the route just configured with correct name and desc, update_time has changed.

 - [ ]  add test case for config route with labels and filter_func

 - [ ]  add test case for config route with  non-existent fields

 - [ ]  verify routing correctness under multi routes

For background and description, please see:

https://github.com/apache/apisix-dashboard/issues/607

**Comment by idbeta** [comment]
Hi, please assign it to me.

**Comment by idbeta** [comment]
The frequency of using `filter_func` is low, it is recommended to move to the 2.2 milestone. What do you think? cc @nic-chen

**Comment by nic-chen** [comment]
agree with that.

**Comment by idbeta** [comment]
` verify routing correctness under multi routes`, this test point need to 
Now, there are few effective uris provided by the upstream service docker, can you provide an upstream, similar to nginx `location /`? In that case, no matter how many routes are created, they can all use different valid uris.
