### ISSUE TITLE
add e2e test for Route

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#640]
Route
- [ ] create: long description and  name include common symbols
- [ ] edit:
- [ ] delete:
- [ ] search: full match, partial match, no match
- [ ] big data environment test: route operation under more than 200 routes

related issue  #614

**Comment by LiteSun** [comment]
The Route section was too complex to test and was temporarily moved to [Milestone 2.2](https://github.com/apache/apisix-dashboard/milestone/6), but maybe moved to [Milestone 2.1](https://github.com/apache/apisix-dashboard/milestone/5) later if there is enough time.

cc @juzhiyuan

**Comment by idbeta** [comment]
hello, assign to me pls.

**Comment by juzhiyuan** [comment]
related feature: 
- [ ] https://github.com/apache/apisix-dashboard/pull/1079
