### ISSUE TITLE
docker-compose up

### ISSUE THREAD

**Issue by jinpy666** [apache/apisix-dashboard#652]
![image](https://user-images.githubusercontent.com/5868671/97685532-08535500-1ad4-11eb-895e-2f142b5e94fe.png)

**Comment by juzhiyuan** [comment]
Hi, @jinpy666 , sorry to lead you confusion, the docker compose is not stable both in the master branch and v2.0 branch, so we remove the Docker way from v2.0, and we are working on how to build Docker more smoothly and easily. This issue would be resolved in 2.0 RC3 soon.

**Comment by juzhiyuan** [comment]
I will close this issue because there exists a duplicated issue #647

**Comment by juzhiyuan** [comment]
Hi @jinpy666 we just added the Docker support, feel free to have a try :)

**Comment by jinpy666** [comment]
> Hi @jinpy666 we just added the Docker support, feel free to have a try :)

Yes! It is suggested that the ENABLE_PROXY in Dcokerfile can pass the switch via parameters.

**Comment by juzhiyuan** [comment]
Then is it working on your side now? If it is, kindly close this issue please:)
