### ISSUE TITLE
Form instance warning

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#656]
This would be fixed using this method

[1] https://github.com/ant-design/ant-design/issues/21543#issuecomment-598515368

**Comment by LiteSun** [comment]
I try hours to fix this bug but failed. 

I found that if I comment line 74、76、83、84 below，the warning disappears. but I can't found a proper way to fix this.
![image](https://user-images.githubusercontent.com/31329157/101798544-22a63700-3b46-11eb-8474-b99cb425ef8f.png)


any suggestions? 👀👀 @juzhiyuan @liuxiran
