### ISSUE TITLE
Run Actions according to changed files' type

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#658]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other
___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.
 
Run API Test when API files changed; Run FE Test when FE files changed. This will save a lot of Action time.

Would this be possible?

**Comment by bzp2010** [comment]
I think it can be achieved.
[documents at here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths)

**Comment by juzhiyuan** [comment]
refer to https://dev.to/flipp-engineering/linting-only-changed-files-with-github-actions-4ddp

**Comment by membphis** [comment]
@bzp2010 do you want to handle this issue? that is a useful feature ^_^

**Comment by juzhiyuan** [comment]
https://github.com/dorny/paths-filter

**Comment by juzhiyuan** [comment]
https://github.com/peter-evans/repository-dispatch

**Comment by nic-chen** [comment]
not urgent
