### ISSUE TITLE
I found service menu in old version， New version has no service menu，I know is it available. 

### ISSUE THREAD

**Issue by wangxunfan** [apache/apisix-dashboard#661]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
I found service menu in old version， New version has no service menu，I know is it available. 
For example: https://github.com/apache/apisix/blob/master/doc/zh-cn/architecture-design.md#service

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.
I found service menu in old version， New version has no service menu，I know is it available.

**Comment by juzhiyuan** [comment]
a TODO feature in 2.1.

related issue #145
