### ISSUE TITLE
Dashboard: consumer list can't add basic-auth 

### ISSUE THREAD

**Issue by Fatpa** [apache/apisix-dashboard#665]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Bug
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
2.0-rc2

- What happened?
When adding basic-atuh consumer from `dashboard -> consumer`, the view just told me `work with route or service object` but not asking me to fill username and password. Even if I add consumer by apisix-api, it still can't edit it by the dashboard and return an error.

![image](https://user-images.githubusercontent.com/1449393/97862050-adbe3100-1d3f-11eb-91a6-84aacba0c12a.png)

**Comment by LiteSun** [comment]
cc @juzhiyuan

**Comment by juzhiyuan** [comment]
I remember this issue has been resolved from APISIX's side, @liuxiran right?

Let me check this before RC3 releasing.

**Comment by juzhiyuan** [comment]
BTW, It will take no more than 1 week to have the RC3 release.

**Comment by juzhiyuan** [comment]
Duplicate with #646 , we should update 2.0's schema json.

**Comment by liuxiran** [comment]
> I remember this issue has been resolved from APISIX's side, @liuxiran right?
> 
> Let me check this before RC3 releases.

yep, depend on APISIX`s side, witch has already been merged, and it is also depend on 

- https://github.com/apache/apisix-dashboard/pull/651

- https://github.com/api7/dashboard-components/pull/137

@juzhiyuan

**Comment by juzhiyuan** [comment]
> > I remember this issue has been resolved from APISIX's side, @liuxiran right?
> > Let me check this before RC3 releases.
> 
> yep, depend on APISIX`s side, witch has already been merged, and it is also depend on
> 
> * #651
> * [api7/dashboard-components#137](https://github.com/api7/dashboard-components/pull/137)
> 
> @juzhiyuan

Published & Dashboard gets updated.

**Comment by juzhiyuan** [comment]
waiting for #657 then recheck this issue.

**Comment by juzhiyuan** [comment]
Once the jsonschema gets updated, this issue could be resolved.
