### ISSUE TITLE
CI: collect golang code coverage(include E2E and unit test case)

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#668]
this PR collects the Golang unit test code coverage:
https://github.com/apache/apisix-dashboard/pull/654

but it is not enough. 
some test cases are written with E2E, we need to collect the code coverage of them too.

- [x] Feature or performance improvement

**Comment by membphis** [comment]
@nic-chen @ShiningRush if you have any suggestions, please leave a message.

**Comment by nic-chen** [comment]
duplicate with #1033
