### ISSUE TITLE
CI(manager-api): run `manager-api` with specified configuration value

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#669]
I think we should create a new CI and it is name is `manager-api-config`.

In this CI, we can run the test case like those:

https://github.com/apache/apisix-dashboard/blob/v2.0/.github/workflows/test-api.yml#L48-L62

**Comment by membphis** [comment]
@nic-chen what do you think?

**Comment by nic-chen** [comment]
we have got one:
https://github.com/apache/apisix-dashboard/blob/v2.0/.github/workflows/cli_test.yml
