### ISSUE TITLE
feat: use Lua's `__index` to mock all of the share dict

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#671]
- Why do you submit this issue?
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

original comment: https://github.com/apache/apisix-dashboard/pull/651/files#r516339002
___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

`__index` can mock all of the share dicts, even we can use it to mock all of the API in `ngx`.

**Comment by juzhiyuan** [comment]
done?

**Comment by juzhiyuan** [comment]
cc @starsz

**Comment by starsz** [comment]
Please assign it to me. I will improve the schema-sync.lua.

Releated: https://github.com/apache/apisix-dashboard/issues/1237.

**Comment by nic-chen** [comment]
we don't need the tool `schema-sync` now, we could use [APISIX controlAPI](https://github.com/apache/apisix/blob/master/doc/control-api.md#get-v1schema) to export schema. 
we only need to update doc about sync schema here.

**Comment by nic-chen** [comment]
it's same with #1237 , we could close this now.

**Comment by juzhiyuan** [comment]
@nic-chen Please remove any related text from this repo if needed

**Comment by nic-chen** [comment]
> @nic-chen Please remove any related text from this repo if needed

sure, we will update the doc, and track it in #1237
