### ISSUE TITLE
Improve FAQ

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#673]
![image](https://user-images.githubusercontent.com/2106987/97935229-eb0fd680-1db2-11eb-9e8a-d140e606c50d.png)

**Comment by LiteSun** [comment]
Convert the Chinese characters in the image to English：

The dashboard project is the control plane, where all parameter validation needs to be done; Apache APISIX is now a mix of data plane and control plane, and will evolve to a pure data plane later.
The dashboard project is divided into two parts: the front-end and the manager API. The front-end schema validation is optional and only affects the experience at most. The manager API is meant to replace the admin API in Apache APISIX, so the parameter checking logic needs to be synchronized from the Apache APISIX project.
The above descriptions can be written in the project README as follows

**Comment by juzhiyuan** [comment]
It's no urgent, would be added to doc in 2.1.
