### ISSUE TITLE
feature: support access log for `manager api`

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#676]
relate to  #620

- [ ] Access log:
  - [ ] Support save to a local file, and can customize the path
  - [ ] Support log rotate
  - [ ] Support custom log format

we could use [zap](https://github.com/uber-go/zap) that most gophers recommend.

**Comment by membphis** [comment]
Bad title, we need to specify that this function is mainly used for `manager-api`.

And pleases set the right label when you create a new issue.

**Comment by juzhiyuan** [comment]
Done?

**Comment by membphis** [comment]
@nic-chen ping

**Comment by nic-chen** [comment]
yes，it has been merged
