### ISSUE TITLE
discuss: refactor `conf` of `manager api`

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#677]
relate to  #620

- [ ] Do not write absolute paths in the code

- [ ] Unified format, use snake case for config

**Comment by juzhiyuan** [comment]
Would this be resolved in 2.0?

**Comment by membphis** [comment]
> * Do not write absolute paths in the code
> * [ ]  Unified format, use snake case for config

I think we need to fix those in `2.0`.

**Comment by membphis** [comment]
I create a new issue, we can fix them later.

https://github.com/apache/apisix-dashboard/issues/684

**Comment by nic-chen** [comment]
close according to pr merged.
