### ISSUE TITLE
 chore: refactor error log for `manager api`

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#678]
relate to  #620

  - [ ] Currently only panic logs are retained, errors are just respond by apis. we need to  retain error logs.
  - [ ] Support custom error log level
  - [ ] Support saving to a local file, and can customize the file path
  - [ ] Support log rotate

we could use [zap](https://github.com/uber-go/zap) that most gophers recommend.

**Comment by membphis** [comment]
https://github.com/cilium/cilium/blob/master/pkg/logging/logging.go

it seems a good choice.

**Comment by nic-chen** [comment]
@membphis 
it use `github.com/sirupsen/logrus`

zap is better than logrus for us, I'm sure about that.

**Comment by membphis** [comment]
nice @nic-chen  ^_^

**Comment by nic-chen** [comment]
> nice @nic-chen ^_^
> 
> can you list some reason? We need to why.

it has almost the same feature and much faster. and it support atomic level, sampling .. etc advanced features

**Comment by membphis** [comment]
Nice got it. And I check the license, it is MIT, good for us too. 

Please confirm whether it will introduce new dependent libraries and their licenses are acceptable.

**Comment by nic-chen** [comment]
done.

rotate should be done with `access log` feature or after that.
