### ISSUE TITLE
feature: support custom CPU quantity used for `manager api`

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#682]
- [ ] support custom cup quantity used for `manager api` 

- [ ] support config custom cup quantity in conf file

**Comment by juzhiyuan** [comment]
plan?

**Comment by bisakhmondal** [comment]
Hi guys. I'm interested in working with the manager API. Could you please briefly explain the issue? I am not getting it😅

**Comment by nic-chen** [comment]
hi @bisakhmondal 
1. sets the maximum number of CPUs that can be executing simultaneously in `api/conf/conf.yaml`
2. Read the configured number in `api/internal/conf/conf.go`
3. Use `runtime.GOMAXPROCS(n)` to limit CPU usage

**Comment by bisakhmondal** [comment]
Okay. I got it. Pushing the changes soon :)

**Comment by nic-chen** [comment]
> Okay. I got it. Pushing the changes soon :)

looking forward to it~
