### ISSUE TITLE
bug: fail to build dashboard web, got error

### ISSUE THREAD

**Issue by Jackson-soft** [apache/apisix-dashboard#685]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
v2.0

- What happened?
![image](https://user-images.githubusercontent.com/3928114/97969162-9ee88480-1dfa-11eb-8947-d08df568f1f7.png)

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by membphis** [comment]
@Jackson-soft what is the command you inputted? I can not get it from the picture.

**Comment by Jackson-soft** [comment]
![Uploading image.png…]()

**Comment by membphis** [comment]
@Jackson-soft please reupload the picture again.

![Uploading image.png…]()

**Comment by Jackson-soft** [comment]
![image](https://user-images.githubusercontent.com/3928114/97970914-364ed700-1dfd-11eb-8fb7-87289299c45b.png)

**Comment by membphis** [comment]
why you install `python3` here?

where can I found this command? Any doc?

**Comment by Jackson-soft** [comment]
![image](https://user-images.githubusercontent.com/3928114/97971319-ce4cc080-1dfd-11eb-9947-52d29f11c5ae.png)

**Comment by membphis** [comment]
Which document did you refer to? I'm confused.

![image](https://user-images.githubusercontent.com/6814606/97971678-5e8b0580-1dfe-11eb-8001-1d225b87e599.png)

**Comment by juzhiyuan** [comment]
Just ignore this error output, it’s related to node-gyp but couldn’t affect our dashboard.

**Comment by juzhiyuan** [comment]
All you need do is just to wait for the rest building.

**Comment by Jackson-soft** [comment]
Yes, Although the compilation error does not affect the operation

**Comment by juzhiyuan** [comment]
Yep, so I will close this :)
