### ISSUE TITLE
conf.json copy of fan.

### ISSUE THREAD

**Issue by griffenliu** [apache/apisix-dashboard#691]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
conf.json copy of fan.

```
# config
cp ${pwd}/api/conf/conf_preview.json ${pwd}/conf.json
export APIX_DAG_LIB_PATH="${pwd}/dag-to-lua-1.1/lib/"
export APIX_ETCD_ENDPOINTS="127.0.0.1:2379"
export SYSLOG_HOST=127.0.0.1

if [[ "$unamestr" == 'Darwin' ]]; then
	sed -i '' -e "s%#syslogAddress#%`echo $SYSLOG_HOST`%g" ${pwd}/conf.json
else
	sed -i -e "s%#syslogAddress#%`echo $SYSLOG_HOST`%g" ${pwd}/conf.json
fi

cp ${pwd}/conf.json ${pwd}/api/conf/conf.json
```

**Comment by juzhiyuan** [comment]
Hi @griffenliu, I’m not sure what you mean, but I noticed that it seems that you are using the Dashboard 2.0 RC2, kindly have a try by using the latest codes on the v2.0 branch.

**Comment by griffenliu** [comment]
> Hi @griffenliu, I’m not sure what you mean, but I noticed that it seems that you are using the Dashboard 2.0 RC2, kindly have a try by using the latest codes on the v2.0 branch.

ok, i'll try v2.0 branch. thanks.
