### ISSUE TITLE
Returned with historical dirty data after updating redirect  from disable to custom

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#695]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

Route redirect (redirect) is returned with historical dirty data after updating from disable to custom.
For example， The script field should not return.
![image](https://user-images.githubusercontent.com/31329157/98187822-bfc0ef00-1f4c-11eb-9b25-e555a8d0ca20.png)
![image](https://user-images.githubusercontent.com/31329157/98187840-cc454780-1f4c-11eb-8731-c976b9fb6e2a.png)

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by membphis** [comment]
@nic-chen Please take a look at this problem. Is it easy to solve this issue?

**Comment by nic-chen** [comment]
> @nic-chen Please take a look at this problem. Is it easy to solve this issue?

yes, just handle nil when update route with `script`

**Comment by nic-chen** [comment]
fixed.
