### ISSUE TITLE
dashboard 2.0 failed to fetch ssl certificate not found

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix-dashboard#697]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

dashboard 2.0 
centos 7
chrome 83

- What happened?
If possible, provide a way to reproduce the error.
证书已经上传了，但是错误日志中报下面这个截图
![image](https://user-images.githubusercontent.com/68040978/98194997-af644080-1f5b-11eb-9c9a-c2b29534af59.png)

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by membphis** [comment]
Can you provide a certificate file that can reproduce this problem?

**Comment by juzhiyuan** [comment]
cc @idbeta

**Comment by idbeta** [comment]
ok, I try to reproduce in my environment.

**Comment by idbeta** [comment]
@tiger333777  It did not reproduce in my environment, can you provide the certificate file that can reproduce this problem?

**Comment by juzhiyuan** [comment]
@idbeta Could you please list where your test cert come from?

- [ ] Self make
- [ ] Aliyun
- [ ] Let's Encrypt

**Comment by idbeta** [comment]
@juzhiyuan 
[x]Aliyun 
[x]Self make
They can all reproduce the problem.

**Comment by moonming** [comment]
is bug of manager API or apisix？

**Comment by idbeta** [comment]
> is bug of manager API or apisix？
This is a bug of manager API.

**Comment by moonming** [comment]
> > is bug of manager API or apisix？
> 
> This is a bug of manager API.

@nic-chen please take a look

**Comment by nic-chen** [comment]
> > > is bug of manager API or apisix？
> > 
> > This is a bug of manager API.
> 
> @nic-chen please take a look

working on it

**Comment by membphis** [comment]
@nic-chen I think you have told me that, you have found this bug? all right?

**Comment by nic-chen** [comment]
> @nic-chen I think you have told me that, you have found this bug? all right?

yes，will fix it soon

**Comment by nic-chen** [comment]
fixed.
