### ISSUE TITLE
feat:  build  web  docker image in source code

### ISSUE THREAD

**Issue by gy09535** [apache/apisix-dashboard#699]
I think we should build web project and api project in two docker images and we can combine it in docker compose or in k8s pod. Users can build images in source code easily. I have change it in my  private  repository , I do not know it it useful for us?

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Not sure, just waiting for more replies.

**Comment by membphis** [comment]
> I think we should build web project and api project in two docker images and we can combine it in docker compose or in k8s pod.

I think one docker or one server is more simple. only manager API or manager API + dashboard, I think it is simpler and easier for user.

**Comment by gy09535** [comment]
> > I think we should build web project and api project in two docker images and we can combine it in docker compose or in k8s pod.
> 
> I think one docker or one server is more simple. only manager API or manager API + dashboard, I think it is simpler and easier for user.

Go it.
