### ISSUE TITLE
CI: improve docker test 

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#703]
currently CI for docker test is too simple, it just test docker build, can not catch `docker run` error :
https://github.com/apache/apisix-dashboard/blob/v2.0/.github/workflows/test-docker.yml

we need to check:
1. docker run OK
2. access to web(page) successful, not 404
3. api for plugin orchestration works fine.

**Comment by membphis** [comment]
yes, we need this. nice

**Comment by juzhiyuan** [comment]
How about adding those tests in this PR? https://github.com/apache/apisix-dashboard/pull/701

This action is used to `Test then Deploy with Docker` if it's failed in test, then the deploy would be terminated, too.

**Comment by nic-chen** [comment]
LGTM

**Comment by nic-chen** [comment]
close since #701 merged.
