### ISSUE TITLE
bug: Missing directory “/output/logs/”

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#709]
After deploy manually, when I run 
`$api/run.sh &`
it will prompt an error
` panic: couldn't open sink "/Users/idbeta/1106/apisix-dashboard/output/logs/error.log"
- Please describe your requirements or improvement suggestions.`

It was correct after I manually added this directory“/output/logs/”

**Comment by membphis** [comment]
the `output/logs` should be created in `api/run.sh`

**Comment by membphis** [comment]
we already have `logs` folder in `api`, why we choose a new temporary `output`?

it makes me confused.

**Comment by membphis** [comment]
here is an example of APISIX, please ref: https://github.com/apache/apisix/blob/master/Makefile#L87

**Comment by juzhiyuan** [comment]
> we already have `logs` folder in `api`, why we choose a new temporary `output`?
> 
> it makes me confused.

The `output` directory is the final directory to save the binary file, config file, the frontend's files, and so on. It's the directory that is used to save the Build-after product. We should not generate those products under the source codes.

**Comment by membphis** [comment]
ok, got it. thansk for your explain
