### ISSUE TITLE
无法移动 dist 目录到 manager-api 的目录下

### ISSUE THREAD

**Issue by webtom-hzm** [apache/apisix-dashboard#712]
在手动部署dashboard时，最后一步骤：6、移动 dist 目录下的文件到 manager-api 的 dist 目录下，然后在浏览器中访问 http://127.0.0.1:8080，8080 是 manager-api 的默认监听端口。

问题：在apisix-dashboard目录下面只有一个manager-api文件而不是目录，请问dist如何移动到这个文件下面 ？

**Comment by juzhiyuan** [comment]
It seems that you are using the codes on the master branch, but we are working on the 2.0 RC3.

Please use the codes under the v2.0 branch, and use this way[1] to build.

![image](https://user-images.githubusercontent.com/2106987/98347298-34ca1c80-2052-11eb-9a39-ad8a35641bf4.png)

Deploy with Docker has something wrong currently, once #701 is merged, you could use Docker to deploy.

[1] https://github.com/apache/apisix-dashboard/blob/v2.0/README.zh-CN.md#%E9%83%A8%E7%BD%B2

**Comment by juzhiyuan** [comment]
Deploy with Docker has been fixed!
