### ISSUE TITLE
bug: The consumer can not be delete by dashboard which created by admin API 

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#718]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

I used admin API created a consumer like this
```
curl http://127.0.0.1:9080/apisix/admin/consumers -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "username": "user123",
  "plugins": {
      "jwt-auth": {
          "key": "dd",
          "secret": "my-secret-key"
      }
  }
}'
```
but when I try to delete it by dashboard, it prompt error
![image](https://user-images.githubusercontent.com/7396835/98435973-4d9a0700-2112-11eb-91d1-8dda51ac0d01.png)

**Comment by membphis** [comment]
> but when I try to delete it by dashboard, it prompt error

**Comment by idbeta** [comment]
@membphis 
request
```
Request URL: http://127.0.0.1:8080/apisix/admin/consumers/
Request Method: DELETE
Status Code: 200 OK
```
response
![image](https://user-images.githubusercontent.com/7396835/98436734-c43a0300-2118-11eb-9ed3-06334d0405e4.png)

**Comment by membphis** [comment]
> Request URL: http://127.0.0.1:8080/apisix/admin/consumers/
> Request Method: DELETE

the URL should be wrong. missing consumer name.

https://github.com/apache/apisix/blob/master/doc/admin-api.md#consumer

**Comment by juzhiyuan** [comment]
@membphis  That’s because the API doesn’t return consumer name.

**Comment by moonming** [comment]
Why the update time is 1970 in dashboard? @juzhiyuan

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/98438448-47615600-2125-11eb-8e7d-b04dbed5d99a.png)

@membphis This issue is related to API, that's because the API doesn't return ID as agreed.

**Comment by juzhiyuan** [comment]
> Why the update time is 1970 in dashboard? @juzhiyuan

because the date returned from API is invalid.

**Comment by juzhiyuan** [comment]
@idbeta  Why not paste the response here?

**Comment by moonming** [comment]
> @membphis  That’s because the API doesn’t return consumer name.

But the user name can display in dashboard

**Comment by juzhiyuan** [comment]
> > @membphis  That’s because the API doesn’t return consumer name.
> 
> But the user name can display in dashboard

ID has been used since the beginning, and no one tells us to fallback to a username.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/98438634-a7a4c780-2126-11eb-99a5-63ebe6cfb541.png)

@membphis @moonming  And according to this doc, we MUST use the ID as the key instead of the username.

**Comment by membphis** [comment]
the `id` and `username` must be the same.  if they were not the same, will return an error message. confirm this.

the doc is wrong. will update it soon.

if we can get `username`, we should use `username`. if not, we can use `id`.

**Comment by membphis** [comment]
@juzhiyuan 

> if we can get `username`, we should use `username`. if not, we can use `id`.

`frontend` should use this way to read the consumer `id`.

**Comment by juzhiyuan** [comment]
Why the frontend should do this fallback? If it's sure that we must use the username as identify (from docs), then both fe and backend should use the username.

**Comment by membphis** [comment]
I check the process in APISIX, I am sure that we can use `username` is enough. then we can ignore the field `id`.

> use the username as identify (from docs), then both fe and backend should use the username

agree +1

**Comment by membphis** [comment]
@juzhiyuan if we both use `username`, please confirm the `frontend` need to update.

it shows you mainly use `id` now:
https://github.com/apache/apisix-dashboard/issues/718#issuecomment-723427291

**Comment by juzhiyuan** [comment]
Yes, the frontend has to update the consumer.

**Comment by membphis** [comment]
@nic-chen please if we need any update for manager-api. I think we do not need to update `manager-api`.

if we do not need to update `manager-api`, we should remove the label `backend`.

**Comment by nic-chen** [comment]
> @nic-chen please confim if we need any update for manager-api. I think we do not need to update `manager-api`.
> 
> if we do not need to update `manager-api`, we should remove the label `backend`.

yes, we do not need to update `manager-api`.

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/blob/v2.0/api/internal/handler/consumer/consumer.go#L102-L110

Should the manager-api still handle ID? cc @nic-chen @membphis

**Comment by membphis** [comment]
I suggest we remove `input.ID` to avoid trouble. only use the consumer name is clearer and simpler.

**Comment by nic-chen** [comment]
> https://github.com/apache/apisix-dashboard/blob/v2.0/api/internal/handler/consumer/consumer.go#L102-L110
> 
> Should the manager-api still handle ID? cc @nic-chen @membphis

the schema of consumer has field ID, the code here is just used to make sure keep the ID same as name.

**Comment by moonming** [comment]
Then we should remove id of consumer in schema too. Only keep name of consumer

**Comment by membphis** [comment]
yes, I have created the issue in APISIX project: https://github.com/apache/apisix/issues/2653
