### ISSUE TITLE
[discuss] differences between manager api and admin api

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#720]
I will check current differences between manager api and admin api and update here.

**Comment by membphis** [comment]
Very good, I think you can make a checkpoint list. then you can check them step by step.

**Comment by juzhiyuan** [comment]
done?

**Comment by nic-chen** [comment]
yes, and we have E2E test for it now.

**Comment by starsz** [comment]
@nic-chen . It means that the response from admin API and manager-api are the same?

Please have look about this https://github.com/apache/apisix-dashboard/issues/1154.
