### ISSUE TITLE
refactory(manager-api): use Golang standard file structure

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#721]
we need to follow Golang standard way(unofficial, but more reasonable):

https://github.com/golang-standards/project-layout

the current file structure is unacceptable:

![image](https://user-images.githubusercontent.com/6814606/98455959-41fe1d00-21b2-11eb-81f9-52b6a51a3e7e.png)

**Comment by membphis** [comment]
@gxthrj Do you have time to do this job?

**Comment by gxthrj** [comment]
Assign to me

**Comment by juzhiyuan** [comment]
in 2.2?

**Comment by gxthrj** [comment]
> in 2.2?

Yes
