### ISSUE TITLE
bug: When the description is too long, the front end should be abbreviated

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#723]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX 2.0 + APISIX-dashboard 2.0

When the description is too long, the front end should be abbreviated, otherwise, the page will be destroyed. I think this point needs to be considered when each field is displayed.
![image](https://user-images.githubusercontent.com/7396835/98465535-87e3d100-2204-11eb-821c-c575d643322d.png)

**Comment by juzhiyuan** [comment]
`ellipsis` would resolve this issue, but it doesn't work now.

https://procomponents.ant.design/components/table
