### ISSUE TITLE
bug: create route and do not input domain name, will display "undefined"

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#724]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX 2.0 + APISIX-dashboard 2.0

create the route and do not input domain name, will display "undefined"
![image](https://user-images.githubusercontent.com/7396835/98465571-c24d6e00-2204-11eb-93d6-34b85076990e.png)

**Comment by juzhiyuan** [comment]
This issue is due to the validate rules, non blocking the normal creating, just put it in 2.2.
