### ISSUE TITLE
bug: creating upstream, an error will be displayed when the name is too long

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#726]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX 2.0 + APISIX-dashboard 2.0

creating upstream, there is no limit on the length of the name, an error will be displayed when the name is too long.
![image](https://user-images.githubusercontent.com/7396835/98465666-7b13ad00-2205-11eb-8c1d-2d3b3fd68dc1.png)

**Comment by moonming** [comment]
Not bug

**Comment by juzhiyuan** [comment]
The frontend doesn't know this maximum length from backend, this issue is more related to UX IMO.
