### ISSUE TITLE
bug: creating consumer, an error will be displayed when the name is too long

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#727]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX 2.0 + APISIX-dashboard 2.0

creating consumer, there is no limit on the length of the name, an error will be displayed when the name is too long
![image](https://user-images.githubusercontent.com/7396835/98465712-b9a96780-2205-11eb-94c7-1fbbc1f35936.png)

**Comment by moonming** [comment]
This not bug
