### ISSUE TITLE
chore:  log should be written when an error occurs

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#730]
log should be written when an error occurs, like:
https://github.com/apache/apisix-dashboard/pull/719/files#diff-27f91a2b4832aa966415bf0e08564cbffdc61d1d1a7e1bd598df5082e9e78786L151

and

https://github.com/apache/apisix-dashboard/pull/719/files#diff-27f91a2b4832aa966415bf0e08564cbffdc61d1d1a7e1bd598df5082e9e78786L173

and other similar places.

**Comment by membphis** [comment]
do we need to fix it in `2.0` or `2.1`?

**Comment by nic-chen** [comment]
I think 2.1 is OK
