### ISSUE TITLE
update_time from manager api shouldn't be 0

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#734]
This issue would be fall back on the frontend according to @membphis 's advice.

**Comment by membphis** [comment]
if the `update_time` or `change_time` is `0`, we'll show `None` at dashboard.

tip: this is a temporary hack, we'll remove this process finally.

**Comment by juzhiyuan** [comment]
what's change_time?

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L289-L290
![image](https://user-images.githubusercontent.com/6814606/98545055-d8743080-22cf-11eb-8d8b-7e1491094f62.png)

**Comment by juzhiyuan** [comment]
hmm, you mean updated time?

**Comment by membphis** [comment]
> what's change_time?

sorry, it should be `create_time`
