### ISSUE TITLE
Install signal handler for graceful shutdown

### ISSUE THREAD

**Issue by tokers** [apache/apisix-dashboard#737]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

manager-api doesn't watches on signal channel so the shutdown is forcible, the direct influence is the `Closer` (to cleanup some resources) is useless.

**Comment by starsz** [comment]
Hi @tokers, I quite agree with you. By the way, do I have a chance to do this?

**Comment by nic-chen** [comment]
> Hi @tokers, I quite agree with you. By the way, do I have a chance to do this?

welcome！

**Comment by tokers** [comment]
Solved by https://github.com/apache/apisix-dashboard/pull/796
