### ISSUE TITLE
Implmement sub-command like stop, restart for manager-api

### ISSUE THREAD

**Issue by tokers** [apache/apisix-dashboard#741]
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

### Requirements or improvement.

Currently the restart of manage-api is manual, 。i.e. kill the process firstly, that's not so convenient, we can implement some sub command like `./manager-api stop` and `./manager-api restart` and etc (after https://github.com/apache/apisix-dashboard/issues/739 is solved).

**Comment by membphis** [comment]
how to find the old pid? local file? like `nginx.pid`?

**Comment by tokers** [comment]
> how to find the old pid? local file? like `nginx.pid`?

Yep.

**Comment by juzhiyuan** [comment]
any update?

**Comment by tokers** [comment]
It seems the priority of this feature is not so high, so what about postponing it to a future milestone?

**Comment by juzhiyuan** [comment]
good to me 😄

**Comment by juzhiyuan** [comment]
in 2.4 or 2.5?

**Comment by tokers** [comment]
I think 2.4 is appropriate.
