### ISSUE TITLE
CI: need a better name

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#748]
unit test? or E2E test?

I think we need a better name

![image](https://user-images.githubusercontent.com/6814606/98538216-64cd2600-22c5-11eb-9232-42600ce63f54.png)

**Comment by moonming** [comment]
ping @nic-chen

**Comment by nic-chen** [comment]
ok, will fix soon

**Comment by juzhiyuan** [comment]
Please update the Test Cli if possible.
