### ISSUE TITLE
bug: an error will occur if `pass_host` is set to `node` when creating upstream

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#749]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

- What happened?
If possible, provide a way to reproduce the error.

when creating an upstream, set its  field `pass_host` to `node`, will occur a 500 error.

**Comment by membphis** [comment]
we need fix this bug in `2.0`, welcome PR ^_^

**Comment by nic-chen** [comment]
fixed.
