### ISSUE TITLE
do we should use `updated_time` and `created_time`?

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#752]
we are using `update_time` and `create_time`, they are not good name style.

I think we should change them to `updated_time` and `created_time`.

![image](https://user-images.githubusercontent.com/6814606/98551607-78ce5300-22d8-11eb-833f-55cb95c655be.png)

**Comment by juzhiyuan** [comment]
```
1. time -> 13:22
2. date -> 2019-01-01
3. datetime -> 2019-01-01 13:22
```

I would prefer using `_at`, e.g `updated_at`

**Comment by juzhiyuan** [comment]
no conclusion and not urgent here so closed.
