### ISSUE TITLE
request help: add `info` page for Apache APISIX 

### ISSUE THREAD

**Issue by moonming** [apache/apisix-dashboard#756]
### Issue description
Return the version number, configuration information, and listening port number etc, for user feedback and debugging

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by juzhiyuan** [comment]
- [ ] API Support
- [ ] Frontend Support

**Comment by juzhiyuan** [comment]
Duplicate with https://github.com/apache/apisix-dashboard/issues/755 IMO

**Comment by juzhiyuan** [comment]
related issues

1. https://github.com/apache/apisix-dashboard/issues/850
2. https://github.com/apache/apisix-dashboard/issues/849
3. https://github.com/apache/apisix/issues/2821

**Comment by juzhiyuan** [comment]
duplicate with #850
