### ISSUE TITLE
[DISCUSS] Create a new file to generalize error response

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#758]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

Hi, I recommend creating a new file to generalize error response which is more convenient and normative.

Now:
https://github.com/apache/apisix-dashboard/blob/a050e8464165c973663fc14fa5a7ecfd7255f1ae/api/filter/authentication.go#L39-L42

Advice:

```go

var (
  ErrorUnauthorized = gin.H{"code": 010013, "message": "Request Unauthorized")
)
```

**Comment by starsz** [comment]
By the way, maybe we can provide a doc to introduce code and message for users.

**Comment by nic-chen** [comment]
agree with you.

**Comment by membphis** [comment]
@ShiningRush do you have any suggestion about this issue?

**Comment by ShiningRush** [comment]
We already have a file to place all errors in [here](https://github.com/apache/apisix-dashboard/blob/master/api/internal/utils/consts/error.go)

> By the way, maybe we can provide a doc to introduce code and message for users.

Agree +1,document will be very helpful.

**Comment by starsz** [comment]
> We already have a file to place all errors in [here](https://github.com/apache/apisix-dashboard/blob/master/api/internal/utils/consts/error.go)

Yeah, I advise creating a `common` directory under `api` and move the files under the `internal/const` directory into that(maybe do a small refactor),  so that the filter module and internal module can use them better.

**Comment by ShiningRush** [comment]
Out project is follow [project-layout](https://github.com/golang-standards/project-layout), if we want other library can use those errors then we can move errors to `pkg/const/error.go`, then make `pkg`  be a sub module.

**Comment by juzhiyuan** [comment]
done or ?

**Comment by starsz** [comment]
@juzhiyuan. Not done.

I review the code again. There is too much error handler.

Like: 

https://github.com/apache/apisix-dashboard/blob/4f12ae6f8495a441c330415802d891a9d7d1b2d6/api/internal/handler/handler.go#L53-L68

and 

https://github.com/apache/apisix-dashboard/blob/6fa6a16559a1c1d0e90de4a3277a3db6e73cb9fc/api/internal/utils/consts/api_error.go#L28-L52

I think we can design it and implement it in M2.4.

**Comment by starsz** [comment]
This will be discussed in M2.4 and finished in M2.5.
cc @juzhiyuan
