### ISSUE TITLE
need request-validation work in dashboard

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#764]
Request-validation properties may be nested in multiple layers, making it very difficult to display them in the form UI.

After communicating with @membphis, we hope to resolve the issue in the following way: Allow users to enter the required data directly into the input box.

Things we need to do:
- [ ] format code(JSON or YAML)
- [ ] verify that the data entered by the user matches the schema definition.

![image](https://user-images.githubusercontent.com/31329157/98635361-ca6df080-235f-11eb-8dd0-8608b9826d09.png)

related issue: https://github.com/apache/apisix/issues/2082
related comment: https://github.com/apache/apisix/issues/2082#issuecomment-721552396

feel free to comment here. 

cc @juzhiyuan @liuxiran

**Comment by juzhiyuan** [comment]
Free to go.
