### ISSUE TITLE
manager-api startup problem

### ISSUE THREAD

**Issue by Applenice** [apache/apisix-dashboard#766]
Please answer these questions before submitting your issue.
- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
```
$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

$ git branch -v
* v2.0 9d4b371 docs: add makefile && modify  develop and deploy  docs (#729)
```

- What happened?
```
$ ./api/run.sh
panic: couldn't open sink "/usr/local/src/apisix-dashboard/output/logs/error.log": open /usr/local/src/apisix-dashboard/output/logs/error.log: no such file or directory

goroutine 1 [running]:
github.com/apisix/manager-api/log.fileWriter(0x1555a50, 0xc000202900)
	/usr/local/src/apisix-dashboard/api/log/zap.go:78 +0x1fc
github.com/apisix/manager-api/log.init.0()
	/usr/local/src/apisix-dashboard/api/log/zap.go:31 +0x34
```
___
### Requirements or improvement
Currently, the startup problem is solved by manually creating files `/logs/error.log`

**Comment by nic-chen** [comment]
we don't support to start by `api/run.sh` now

please refer:

https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy.md#run
https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy.zh-CN.md#%E5%90%AF%E5%8A%A8

https://github.com/apache/apisix-dashboard/blob/v2.0/docs/develop.md#start
https://github.com/apache/apisix-dashboard/blob/v2.0/docs/develop.zh-CN.md#%E5%90%AF%E5%8A%A8

Thanks.

**Comment by juzhiyuan** [comment]
Hi @Applenice , because from RC2 to RC3, there have a lot of changes on docs, so please refer to the latest docs.

**Comment by Applenice** [comment]
> Hi @Applenice , because from RC2 to RC3, there have a lot of changes on docs, so please refer to the latest docs.

The redeployment is working fine, thank you.
