### ISSUE TITLE
页面菜单请求返回 401 Unauthorized

### ISSUE THREAD

**Issue by ztgoto** [apache/apisix-dashboard#769]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
#702  该问题修复了404页面的问题，页面能登入成功，但是 路由，证书，上游，Consumer菜单相关的请求接口返回401 Unauthorized 导致退出到登入界面。
通过http请求来看 存在Authorization请求头，但是值为空
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

代码使用 分支 v2.0  commit c140f41acdc90b53db3b349f63a43503666a76fe 代码构建的docker镜像

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Could you have a try on this IP[1]? It's deployed with the latest codes from v2.0 by Docker CD.

[1] http://139.217.190.60

**Comment by ztgoto** [comment]
@juzhiyuan  你们提供的可以，我查看过你们的http请求中携带了jwt token在Authorization 中。
我构建的dockers镜像不行，Authorization头信息为空值，登入是可以成功的,但是 /apisix/admin/user/login 接口没有返回任何数据。
而且镜像中看不到docker输出日志

**Comment by juzhiyuan** [comment]
OK, let me cc @idbeta to test this issue.

**Comment by idbeta** [comment]
I cannot reproduce this issue in my env, I used the 2.0rc branch. @juzhiyuan @ztgoto

**Comment by idbeta** [comment]
I reproduced this problem in my environment, thanks for feedback.
