### ISSUE TITLE
bug: There is no error log when the address already in use.

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#775]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

APISIX Dashboard v2.0-rc2

- What happened?
If possible, provide a way to reproduce the error.

Hi, I found that there is no error log when the address already in use.
Because the function doesn't print any message. 
Maybe you had mistaken using of logrus. : ) 

See:
https://github.com/apache/apisix-dashboard/blob/a050e8464165c973663fc14fa5a7ecfd7255f1ae/api/main.go#L56

And the [logrus doc](https://godoc.org/github.com/sirupsen/logrus#WithError)

```golang
func WithError
func WithError(err error) *Entry
WithError creates an entry from the standard logger and adds an error to it, using the value defined in ErrorKey as key.
```
___

**Comment by nic-chen** [comment]
Thanks for feedback. 
we are not using logrus now.
see:
https://github.com/apache/apisix-dashboard/blob/v2.0/api/main.go#L55

please use branch v2.0, thanks : )
