### ISSUE TITLE
user name is empty

### ISSUE THREAD

**Issue by yankunsam** [apache/apisix-dashboard#777]
ssue description
Dashboard Project

After run the api.sh:

panic: etcd get failed: etcdserver: user name is empty

Environment
apisix version (cmd: apisix version):
OS: MacOS

**Comment by juzhiyuan** [comment]
cc @idbeta

**Comment by idbeta** [comment]
@yankunsam Could you deploy version 2.0rc3? Because we no longer recommend using ```api.sh``` to start.
https://github.com/apache/apisix-dashboard/blob/v2.0/README.zh-CN.md

**Comment by moonming** [comment]
2.0rc3 not released yet.
and we should dig the reason

**Comment by nic-chen** [comment]
@yankunsam  
does your ETCD enabled authentication?

**Comment by nic-chen** [comment]
close first. if you have the problem feel free to reopen
