### ISSUE TITLE
web: failed to call `yarn install`

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#780]
![image](https://user-images.githubusercontent.com/6814606/98762188-15e0d700-2412-11eb-82f9-bb91afa8ac15.png)

```
$ yarn
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error swagger-client@3.10.12: The engine "node" is incompatible with this module. Expected version ">=10.21.0". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by membphis** [comment]
@juzhiyuan please confirm if we should update the doc or it is a bug.

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/blob/v2.0/.github/workflows/test-frontend-multiple-node-build.yml#L25

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/98762407-87b92080-2412-11eb-80ea-5012403e7e36.png)

This doc need to be updated.

**Comment by membphis** [comment]
> Expected version ">=10.21.0". Got "10.19.0"

![image](https://user-images.githubusercontent.com/6814606/98762458-a3242b80-2412-11eb-8405-9d3cdfca26b9.png)

I think I have installed a right version.
