### ISSUE TITLE
能否增加配置导入导出的功能，用于升级或多数据中心的apisix之间进行迁移

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix-dashboard#782]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Other

___
### Question
- What do you want to know?

能否增加配置导入导出的功能，用于升级或多数据中心的apisix之间进行迁移

**Comment by idbeta** [comment]
etcdctl provide `snapshot save` and `snapshot restore`, does it meet your requirements?

**Comment by juzhiyuan** [comment]
cc @membphis

**Comment by membphis** [comment]
This is the function we plan to do, and it is very useful for business users.

Do you have any thoughts on this feature?

**Comment by fregie** [comment]
How about add two apis to export and import a config file?
The config file saves all related data in etcd encoded.
Another thing we need to consider is what to do if there is a conflict when import,do you have any expectation？
@membphis @juzhiyuan

**Comment by juzhiyuan** [comment]
LGTM, could you propose this feature?
