### ISSUE TITLE
上游节点分组节点主机权重配置为0时，dashboard进行路由配置时，选后节点分组，报undefined

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix-dashboard#783]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Bug

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
api-dashboard : 2.0 rc3
OS:centos7

1、上游节点分组节点主机权重配置为0时，dashboard进行路由配置时，选后节点分组，报undefined;
etcd里数据是0
![image](https://user-images.githubusercontent.com/68040978/98785240-4129ed00-2437-11eb-998e-65ffa51d6a11.png)

**Comment by LiteSun** [comment]
I reproduce this bug in [demo page](http://139.217.190.60/routes/328072574489592268/edit). When the upstream nodes weight is 0, the API has no weight value. @nic-chen Please have a look.
![image](https://user-images.githubusercontent.com/31329157/98791262-c1ece700-243f-11eb-9b86-e06af65b36be.png)

**Comment by nic-chen** [comment]
> I reproduce this bug in [demo page](http://139.217.190.60/routes/328072574489592268/edit). When the upstream nodes weight is 0, the API has no weight value. @nic-chen Please have a look.
> ![image](https://user-images.githubusercontent.com/31329157/98791262-c1ece700-243f-11eb-9b86-e06af65b36be.png)

it's a bug here.
