### ISSUE TITLE
makefile: for `make release-src`, it should release the source code

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#787]
https://github.com/apache/apisix-dashboard/blob/v2.0/Makefile#L93

that is wrong, for `make release-src`, it should release the source code. 

but we released binary file now, this is wrong.

```
.PHONY: release-src
release-src:
	tar –cf dashboard.tar ./output/*

**Comment by membphis** [comment]
@gxthrj you can take a look at this PR

**Comment by gxthrj** [comment]
ok, we can call it `make release`,the release package contains the binary file of `manager-api` and static files of `web`.

**Comment by juzhiyuan** [comment]
make-release is more semantic and clearer.

**Comment by gxthrj** [comment]
@membphis Can we close this issue now? 
The document has changed the original purpose of packaging the `output` directory.
`make release-src` is for source release now. #816

**Comment by juzhiyuan** [comment]
We could close this one IMO.
