### ISSUE TITLE
bug: dashboard2.0  ip-restriction plugin set blacklist, can not set ipv4 or ipv4/CIDR

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#788]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

dashboard2.0  ip-restriction plugin set `blacklist`, can not set ipv4 or ipv4/CIDR,  `whitelist` doesn't have this problem.
![image](https://user-images.githubusercontent.com/7396835/98628362-617f7c00-2351-11eb-9bc3-071c1cac418f.png)

**Comment by juzhiyuan** [comment]
This schema works in many ways, but it's not compatible with the react-jsonschema-form dependency now, we will try to reactor the schema first as usual.

Only when we couldn't build the schema which can't work with that dependency, we will have to solve it on the frontend.

**Comment by juzhiyuan** [comment]
So just pending and need some time on checking if there has a working scheme.
