### ISSUE TITLE
bug: when create a route with kafka-logger, the plugin's option is missing field.

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#790]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

when create a route with kafka-logge, the plugin's option is missing field.
![image](https://user-images.githubusercontent.com/7396835/98897409-501ba880-24e6-11eb-93b5-f131fce26c8d.png)

**Comment by juzhiyuan** [comment]
Duplicate as most of other plugins, need some time to build the schema that could work with react-jsonschema-form.

**Comment by liuxiran** [comment]
`broker_list` has to be transformed schema, from 
```json
{
		"properties": {
			...
			"broker_list": {
				"type": "object"
			}
                 }
}
```

to 

```json
{
    "properties": {
        ...
        "broker_list": {
	"type": "array",
        "items": {
          "type": "object",
          "properties": {
            "host": {
              "type": "string"
            },
            "port": {
              "type": "integer"
            }
          },
          "required": ["host", "port"],
          "minItems": 1
        }
    }
}
```
