### ISSUE TITLE
bug: setting proxy-cache plugin prompt error

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#791]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

When setting the mandatory option `cache_zone`, the non-mandatory option `cache_bypass`, `no_cache` will automatically prompt an error, and `cache_zone` should be placed in the header
![image](https://user-images.githubusercontent.com/7396835/98900609-17330200-24ed-11eb-9088-860456e3b005.png)

**Comment by juzhiyuan** [comment]
Not sure what happened but still duplicate as other plugins that need to rebuild the schema so they could work with react-jsonschema-form. Just added the checking label.
