### ISSUE TITLE
bug: echo plugin can not set headers

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#792]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

The `headers` option will automatically refresh as `Opthion3` when setting the other option,
and the `headers` option can not be set.
![image](https://user-images.githubusercontent.com/7396835/98907517-e86f5880-24f9-11eb-8630-6d59d5133822.png)

**Comment by liuxiran** [comment]
There are two errors here:

1. `headers` schema should be transformed just like `proxy-rewrite` and `response-rewrite` in fe plugin component

1. `echo` schema still uses Draft5, that why we will see select element `Option1` in page. so It also needs to change the echo shema to Draft7.
```json
{
    "additionalProperties": false,
    "required": ["before_body","body","after_body"],
    "minProperties": 1,
    "properties": {
	"after_body": {
		"description": "body after the modification of filter phase.",
			"type": "string"
		},
		"auth_value": {
			"description": "auth value",
			"type": "string"
		},
		"before_body": {
			"description": "body before the filter phase.",
			"type": "string"
		},
		"body": {
			"description": "body to replace upstream response.",
			"type": "string"
		},
		"headers": {
			"description": "new headers for response",
			"minProperties":1,
			"type": "object"
		}
	},
	"type": "object"
}
```

**Comment by nic-chen** [comment]
fixed by code-mirror

**Comment by juzhiyuan** [comment]
closed by https://github.com/apache/apisix-dashboard/pull/898
