### ISSUE TITLE
bug: proxy-rewrite plugin's headers option is invalid

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#793]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

Already set, but invalid
![image](https://user-images.githubusercontent.com/7396835/98915481-ef4f9880-2504-11eb-8b25-40d7777a38bb.png)
![image](https://user-images.githubusercontent.com/7396835/98915307-b31c3800-2504-11eb-9468-a737c60eae79.png)

actual result:
```
127.0.0.1 - - [12/Nov/2020 16:29:50] "GET /test/home.html HTTP/1.1" 200 -
Host: 127.0.0.1
X-Real-IP: 127.0.0.1
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Host: 127.0.0.1
X-Forwarded-Port: 9080
User-Agent: curl/7.54.0
Accept: */*
```

**Comment by juzhiyuan** [comment]
Not sure what happened 😂

Is this data invalid when sending the request?

![image](https://user-images.githubusercontent.com/2106987/98921378-30977680-250c-11eb-868c-2b1bdff1bb96.png)

**Comment by liuxiran** [comment]
`headers` should be format to
```json
{
X-Api-version: 'v1'
}
```
let me check the related code😂

**Comment by juzhiyuan** [comment]
ok!

**Comment by membphis** [comment]
if that is a bug, should we remove `checking` label and add `bug` label?

@idbeta I think you can provide more information, especially information about warning or error messages. Then the developer can confirm this bug easier. Many thx for your report
