### ISSUE TITLE
doc: bad example

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#797]
comment: https://github.com/apache/apisix-dashboard/pull/765/files#r522219656

this style is better.

```sh
$ ./api/build-tools/schema-sync.sh /your/path/apisix
```

**Comment by juzhiyuan** [comment]
Because the doc improvement PR is still under reviewing, could we use this one in that PR?

**Comment by membphis** [comment]
which PR?

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/pull/785

This PR has been merged, and that content has been moved to FAQ, does it meet your needs?

https://github.com/apache/apisix-dashboard/blob/v2.0/docs/FAQ.md#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard

**Comment by membphis** [comment]
got it. thx.

we can close this issue
