### ISSUE TITLE
example-plugin return 500 error code

### ISSUE THREAD

**Issue by Applenice** [apache/apisix-dashboard#802]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
In the routing configuration，`Edit Route`->`Plugin Config`->`example-plugin`，Click on Setting，Return 500 error code.
Click to return to the home page, but can not return, need F5 refresh.

This also occurs with online demo, which are reproducible.

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
```
$ git branch -v
* v2.0 e08f3ab feat: remove CD for PR
$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
```
Chrome 86.0.4240.183

- What happened?
Dashboard error logs are as follows:
```
$ pwd
/usr/local/src/apisix-dashboard/output/logs
$ tail -f error.log 
2020-11-13T13:55:56.243+0800	WARN	log/log.go:60	data not found by key: 328359111706018426
2020-11-13T13:57:54.173+0800	WARN	log/log.go:60	data not found by key: 328359111706018426
2020-11-13T13:59:41.897+0800	WARN	log/log.go:60	data not found by key: 328359111706018426
2020-11-13T13:59:43.664+0800	WARN	log/log.go:60	data not found by key: 328359111706018426
```

**Comment by juzhiyuan** [comment]
Ya this issue is resolved in the APISIX(disabled it because it's just a demo plugin), and this error is due to its wrong schema, maybe we should update the schema in the dashboard as well. Thanks for your report!

**Comment by Applenice** [comment]
> Ya this issue is resolved in the APISIX(disabled it because it's just a demo plugin), and this error is due to its wrong schema, maybe we should update the schema in the dashboard as well. Thanks for your report!

Thank you for your response, I found it while learning how to use the plugin and submitted it!

**Comment by juzhiyuan** [comment]
And we are working on how to let users use plugins no matter if its scheme is ok for frontend, will be added soon.

**Comment by juzhiyuan** [comment]
Then shall we close this issue?

**Comment by Applenice** [comment]
> Then shall we close this issue?

I personally would like to have documentation or video tutorials on how to configure the plugin so I can learn quickly!

**Comment by juzhiyuan** [comment]
May I know do you mean how to configure it in the dashboard or API?

**Comment by Applenice** [comment]
> May I know do you mean how to configure it in the dashboard or API?

emmm, similar to an instructional video that demonstrates the configuration of plugins in Dashboard, which may be easier to understand. The online demo does not currently provide these.

**Comment by Applenice** [comment]
Personally, I think the Dashboard can operate faster and be easier to understand than the API.

**Comment by juzhiyuan** [comment]
> > May I know do you mean how to configure it in the dashboard or API?
> 
> emmm, similar to an instructional video that demonstrates the configuration of plugins in Dashboard, which may be easier to understand. The online demo does not currently provide these.

Oh I see, it seems that there has more work to do, let's add a label for this issue.
