### ISSUE TITLE
request help: run git commit return hook failed error

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#803]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

When tried to commit to V2.0 branch,  I got the error msg like this:

![image](https://user-images.githubusercontent.com/2561857/99039886-208e9e00-25c3-11eb-9f73-3a3ee26d21d3.png)

It can be solved by `add --no-verify to bypass`, but I think this is just a way to circumvent the problem, and I have not found a better way,  so how to solve this problem?

**Comment by juzhiyuan** [comment]
This is due to the `.git` in the root folder, but the web source codes are under the `web` folder.

**Comment by membphis** [comment]
@idbeta You can take a look at this problem, I remember you got this error too.
