### ISSUE TITLE
proxy-rewrite plugin header data missing

### ISSUE THREAD

**Issue by Applenice** [apache/apisix-dashboard#805]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
```
$ git branch -v
* v2.0 6dae80b feat(docs): improve README & Deploy (#785)
```
Chrome 86.0.4240.198

In the routing configuration，`Edit Route`->`Plugin Config`->`proxy-rewrite`，Click on `Setting`->Click on the `left unconfigured area` or `cancel` -> Click again `proxy-rewrite Setting`，Header's configuration is missing.
![Snipaste_2020-11-13_23-36-21](https://user-images.githubusercontent.com/30207614/99091059-53a85000-260a-11eb-8acd-2abfa4f034ba.png)

Only the header part of the configuration is missing, the configuration of host, regex_uri, and schema is still there.👀

I've observed the network request. The response is normal.
```
Request URL: http://192.168.1.118:8080/apisix/admin/routes/328415276909462181
Request Method: GET
Status Code: 200 OK
Remote Address: 192.168.1.118:8080
Referrer Policy: strict-origin-when-cross-origin
```
The Plugin section of the response contains the header data.
```
"plugins": {
    "basic-auth": {},
    "proxy-rewrite": {
        "headers": {
            "Accept": {
                "key": "Accept",
                "value": "application/json"
            }
        },
        "host": "xxxxxxx",
        "regex_uri": [
            "^/geo/(.*)$",
            "/json/$1"
        ],
        "scheme": "http"
    }
},
```

**Comment by membphis** [comment]
@juzhiyuan @LiteSun please confirm if we need to update the schema of plugin `proxy-rewrite`

**Comment by liuxiran** [comment]
Replicated in my local env, checking~
