### ISSUE TITLE
Service 'manager' failed to build

### ISSUE THREAD

**Issue by wenlincheng** [apache/apisix-dashboard#806]
Service 'manager' failed to build， when I install it in docker .

docker-compose -p dashboard up -d

Step 13/17 : RUN  cd /go/manager-api/build-tools      && lua schema-sync.lua > /go/manager-api/schema.json      && cd /go/manager-api/      && rm -rf /go/manager-api/build-tools/
 ---> Running in 5f5de1ed1677
lua: ./apisix/plugins/api-breaker.lua:24: attempt to index field 'shared' (a nil value)
stack traceback:
	./apisix/plugins/api-breaker.lua:24: in main chunk
	[C]: in function 'require'
	schema-sync.lua:128: in main chunk
	[C]: ?
ERROR: Service 'manager' failed to build : The command '/bin/sh -c cd /go/manager-api/build-tools      && lua schema-sync.lua > /go/manager-api/schema.json      && cd /go/manager-api/      && rm -rf /go/manager-api/build-tools/' returned a non-zero code: 1

**Comment by idbeta** [comment]
@wenlincheng Can you provide more information? like OS and dashboard version

**Comment by nic-chen** [comment]
@wenlincheng please use branch v2.0，and follow the guide：
[https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy-with-docker.md](https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy-with-docker.md)

**Comment by wenlincheng** [comment]
> @wenlincheng Can you provide more information? like OS , docker, dashboard version

**Comment by wenlincheng** [comment]
> Service 'manager' failed to build， when I install it in docker .
> 
> docker-compose -p dashboard up -d
> 
> Step 13/17 : RUN cd /go/manager-api/build-tools && lua schema-sync.lua > /go/manager-api/schema.json && cd /go/manager-api/ && rm -rf /go/manager-api/build-tools/
> ---> Running in 5f5de1ed1677
> lua: ./apisix/plugins/api-breaker.lua:24: attempt to index field 'shared' (a nil value)
> stack traceback:
> ./apisix/plugins/api-breaker.lua:24: in main chunk
> [C]: in function 'require'
> schema-sync.lua:128: in main chunk
> [C]: ?
> ERROR: Service 'manager' failed to build : The command '/bin/sh -c cd /go/manager-api/build-tools && lua schema-sync.lua > /go/manager-api/schema.json && cd /go/manager-api/ && rm -rf /go/manager-api/build-tools/' returned a non-zero code: 1

**Comment by wenlincheng** [comment]
> @wenlincheng Can you provide more information? like OS , docker, dashboard version
macOS Catalina 10.15.6
Docker version 19.03.13
dashboard version is the master branch
I use the docker-compose file in [https://github.com/apache/apisix-dashboard/tree/master/compose](https://github.com/apache/apisix-dashboard/tree/master/compose)

**Comment by idbeta** [comment]
@wenlincheng could you try the RC3 branch? It is easier https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy-with-docker.zh-CN.md

**Comment by juzhiyuan** [comment]
@wenlincheng hi, we are working on the v2.0 branch currently, please deploy according to the docs in the previous comment.

**Comment by wenlincheng** [comment]
I solved the problem by using the v2-rc3 version, thanks!
