### ISSUE TITLE
My process of deploying dashboard on kubernetes

### ISSUE THREAD

**Issue by ziyou434** [apache/apisix-dashboard#809]
- [X] Other

___
### Question
My process of deploying dashboard on kubenetes - 2020/11/16
___

Because there is no official image right now, so I used iiqi‘s image [https://github.com/iiQi/apisix-dashboard-docker](url)
you can find “iiqi/apisix-dashboard“ and "iiqi/apisix-manager" in dockerhub
I use deployment.yaml and service.yaml  deployed these images on kubernetes.
First I set two new configmap for images

/etc/nginx/conf.d/backend.conf 
```
upstream backend {
  server 127.0.0.1:8080;    # put your manager-api service's cluster IP
}
```
/go/manager-api/conf/conf.json
```
"etcd": {
          "endpoints":"127.0.0.1:2379"   # put your etcd service's cluster IP
...
...
"user": [
      {
        "username": "admin",
        "password": "admin"
      },
      {
        "username": "user",
        "password": "user"
      }
        },
```
Then change your apisix's configmap
/usr/local/apisix/conf/config-default.yaml
```
enable_admin: true     # change to false
```
Finally, use your kubernetes ingress or apisix create a route 

example:
```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
  "uri": "/*",
  "host": "apisix-dashboard.alpha.tplinknbu.com",
  "upstream": {"nodes": {"apisix-dashboard.api-gateway.svc.cluster.local:8080": 1}, "type": "roundrobin"}
}'
```
Go to apisix-dashboard.alpha.tplinknbu.com and login

**Comment by membphis** [comment]
@ziyou434 you can write an article about this ^_^

Chinese or English, they are all fine.

**Comment by juzhiyuan** [comment]
👏

and we have Docker support in the v2.0 branch.

**Comment by juzhiyuan** [comment]
Hi @ziyou434, would like to file a PR here[1] so we can add your posts to website[2].

[1] **https://github.com/apache/apisix-website/tree/master/website/blog
[2] https://apisix.apache.org/blog/

**Comment by ziyou434** [comment]
> Hi @ziyou434, would like to file a PR here[1] so we can add your posts to website[2].
> 
> [1] https://github.com/apache/apisix-website/tree/master/website/blog
> [2] https://apisix.apache.org/blog/

Of course, some details involve company information, so I just wrote it roughly. If it can help others, I will be honored.
I will organize and summarize it tonight

**Comment by juzhiyuan** [comment]
Hi, anything could I help you?

**Comment by ziyou434** [comment]
.

> Hi, anything could I help you?

emm... I find you added the wait for update label, I remembered I added the PR ,but I can't find my action about this ,maybe I did the wrong operation.

**Comment by juzhiyuan** [comment]
Oh yes, I added that label because no update here 😂 kindly refile a PR when you are free 💯

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/apisix-website/pull/118
