### ISSUE TITLE
Dashboard Create Comsumer promblem：”Please enable one authentication plugin“

### ISSUE THREAD

**Issue by ziyou434** [apache/apisix-dashboard#812]
- [x] Question or discussion
___
### Question
I wrote my own authentication plugin, but It is classified in ”Other“.
I find development team use api7-dashboard-components to manage plugins，so only preset plugins have categories, my plugins has not. 
Then I can't use my  authentication plugin, because I must select one of plugins which category is authentication.
I think it's unreasonable，maybe you can let user define the dashboard-components/packages/plugin/src/data.tsx.

**Comment by juzhiyuan** [comment]
This will be resolved in 2.1

**Comment by ziyou434** [comment]
> 这将在2.1中解决
I think this issue is similar to #532 .
User need to define plugin's type by themselves.

**Comment by juzhiyuan** [comment]
Yep, and there will have a proposal to let the community check.
