### ISSUE TITLE
Integrate with code-mirror to have a fallback to plugins' render issue

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#815]
![image](https://user-images.githubusercontent.com/2106987/99651003-0c4e1380-2a91-11eb-81f5-c58f5609bc3e.png)

## Background

As shown in the figure, on the left side is the current plugin page and an example diagram of the interaction of editing a plugin.

After the user finds the target plugin,

1. View the data saved by the plugin via the **View Raw** button
2. Invoke the Plugin Form, which is a library of `react-jsonschema-form`, built from the plugin's jsonschema, via the **Setting** button.
3. Determine whether to enable the plugin via the `Enable/Disable` button.

## Problem

The problem we are currently experiencing is that many plugins cannot properly render forms via [react-jsonschema-form](https://rjsf-team.github.io/react-jsonschema-form/) because the library supports most of the features of the jsonschema, but some of them are not supported. In addition, plugin developers only need to focus on the jsonschema, and building interfaces that are supported by the library requires higher development costs.

Over the past few months, we tried to update the plugin schema to match the library, but it was inefficient and users could not edit the plugin data properly.

## Solution

*Temporarily* disables **react-jsonschema-form** building forms, and only supports **manual data entry** by the user via the **Plugin Data Editor (View Raw)** interface.

### Disadvantages

1. This approach would sacrifice user experience and require the user to enter the configuration manually, based on the documentation examples.

### Advantages

1. Solves the problem that all plugins are not rendering the form properly.
2. Plugin developers only need to care about writing the correct jsonschema.

As for the feature that allows users to enter plugin data via a form (instead of manually entering JSON), this will remain a concern, and we will resubmit the proposal to resolve the issue when a suitable solution is available to cover all plugins.

## Reference

- [CodeMirror](https://codemirror.net/)

**Comment by juzhiyuan** [comment]
Please take a look at this proposal, though it's not very friendly for users to input JSON, it works for all the plugins.

cc @liuxiran @LiteSun @moonming @membphis @ShiningRush @idbeta

**Comment by juzhiyuan** [comment]
We will use [CodeMirror](https://codemirror.net/) to highlight the json data.

**Comment by idbeta** [comment]
Agree, need to provide users with JSONschema examples of each plugin, you can add a link next to the plugin to make it easier for users to find these examples.

**Comment by juzhiyuan** [comment]
> Agree, need to provide users with JSONschema examples of each plugin, you can add a link next to the plugin to make it easier for users to find these examples.

Ya, a quick way is adding a link to that plugin's doc 😂

**Comment by liuxiran** [comment]
I think this proposal is a good compromise. 
We can improve the documentation to increase the experience, we can try to provide some **configuration template** for common scenarios, then users can use our plugin by copying the template and modifying some configuration parameters.

**Comment by juzhiyuan** [comment]
> I think this proposal is a good compromise.
> We can improve the documentation to increase the experience, we can try to provide some **configuration template** for common scenarios, then users can use our plugin by copying the template and modifying some configuration parameters.

Than

**Comment by liuxiran** [comment]
> > I think this proposal is a good compromise.
> > We can improve the documentation to increase the experience, we can try to provide some **configuration template** for common scenarios, then users can use our plugin by copying the template and modifying some configuration parameters.
> 
> That's it!!

and this may be easier to use than visual forms :)

**Comment by tokers** [comment]
I have just one question, is the plugin data editor friendly enough? say user puts some unexpected characters accidently (like adding extra commas)
will the editor highlights the error to help user to rectify it?

**Comment by juzhiyuan** [comment]
> will the editor highlights the error to help the user to rectify it?
Not sure, if CodeMirror supports it, we will add this feature.

BTW, the frontend will validate the data according to schema before sending APIs.

**Comment by tokers** [comment]
> > will the editor highlights the error to help the user to rectify it?
> 
> Not sure, if CodeMirror supports it, we will add this feature.
> BTW, the frontend will validate the data according to schema before sending APIs.

I think the feeling of interaction is important, some low level syntax errors are not so easy to found especially when the plugin data is fairly long.

**Comment by juzhiyuan** [comment]
> > > will the editor highlights the error to help the user to rectify it?
> > 
> > Not sure, if CodeMirror supports it, we will add this feature.
> > BTW, the frontend will validate the data according to schema before sending APIs.
> 
> I think the feeling of interaction is important, some low level syntax errors are not so easy to found especially when the plugin data is fairly long.

Got it, we support validating with jsonschema, errors will show up if there has something incompatible with schema.

**Comment by juzhiyuan** [comment]
ok, then I'm going to do this this week.

**Comment by juzhiyuan** [comment]
This issue is related to those issues.

#764 
#802 
#812 
#814 
#790 
#788 
#762

**Comment by juzhiyuan** [comment]
After some research and trying, I find that we should add a Format button instead of auto-formatting because auto-formatting will make the input Textarea lost focus.

**Comment by juzhiyuan** [comment]
When users input or paste some JSON codes here, they could click the format button to achieve code format, easy to implement.

**Comment by juzhiyuan** [comment]
Snapshot

![image](https://user-images.githubusercontent.com/2106987/100563889-7d47c380-32fa-11eb-8be4-b8bfa95e58e6.png)

**Comment by membphis** [comment]
> After some research and trying, I find that we should add a Format button instead of auto-formatting because auto-formatting will make the input Textarea lost focus.

agree ^_^

**Comment by juzhiyuan** [comment]
ping @membphis

**Comment by membphis** [comment]
got it
