### ISSUE TITLE
Support global plugin

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#820]
## Background
The global plugin acts on every request and it is not bound to any Service, Route, or Consumer, which reduces the need to set up the same plugin configuration repeatedly for multiple resources.

### Frontend

In the plug-in module, we will first support the global plugin, and in-scope plugin in the future. In this proposal, the focus will be on the **global plugin**.

3 pages are involved:
1. The plugin enabled list page;
2. Plugin list page;
3. The plugin configuration page.

In this revision, the plugin list page and plugin configuration page will be adjusted, and the following are the changes:
1. The plugin list page is only used to select plug-ins;
2. Plugin configuration from the original drawer, changed to a separate plugin configuration page, mainly to be compatible with the increase in the number of fields behind, resulting in the drawer **can not well carry more content**.

![image](https://user-images.githubusercontent.com/2106987/102069664-07cf0d80-3e39-11eb-8728-ac13d93eae3f.png)

**Use process**
1. Users in the plugin module, click the Add Plugin button to jump to the plug-in list page;
2. The user in the plugin list page, find the target plugin, then click the configuration button to enter the plugin configuration page;
3. Users in the plugin configuration page, you can choose to enable or disable the plugin, you can choose the scope of the plugin: global or with scope (Service, Route), currently only supports the global;
4. The user enters data in the plugin data editor (form or code editor, currently only the latter is supported) and returns to the enabled plugins list page after successful saving.

**NOTE**
We will modify 3 modules:
1. Add Plugins module;
2. Update Route, Consumer with the latest plugin component mentioned above.

### Backend

refer to https://github.com/apache/apisix/blob/5de6ee467f83c38f31eff6cfd683736b441ac9c2/doc/zh-cn/architecture-design.md#global-rule

**API: set global plugins**
```
PUT /apisix/admin/global_rules/{FIXED_GLOBAL_RULE_ID}
```
```json
{
        "plugins": {
            "limit-count": {
                "time_window": 60,
                "policy": "local",
                "count": 2,
                "key": "remote_addr",
                "rejected_code": 503
            }
        }
    }
```

**API: get global plugins**
```
GET /apisix/admin/global_rules/{FIXED_GLOBAL_RULE_ID}
```
```json
{
        "plugins": {
            "limit-count": {
                "time_window": 60,
                "policy": "local",
                "count": 2,
                "key": "remote_addr",
                "rejected_code": 503
            }
        }
    }
```

## Reference
- https://docs.konghq.com/hub/kong-inc/acl/#enabling-the-plugin-globally
- https://github.com/apache/apisix-dashboard/issues/448
- https://github.com/apache/apisix-dashboard/issues/815

**Comment by moonming** [comment]
We need to list the plug-in as an object separately, at this time etcd may not be convenient to use directly

**Comment by juzhiyuan** [comment]
got it

**Comment by moonming** [comment]
why remove from MS？

**Comment by membphis** [comment]
@juzhiyuan you need to submit your design for this issue and update the title

**Comment by juzhiyuan** [comment]
Of course, the proposal would be finished and discuss completed no longer than next week.

**Comment by juzhiyuan** [comment]
Please take a look at this proposal, to check if there have any improvements about Global Plugin.

cc @nic-chen @liuxiran @ShiningRush @tokers @LiteSun @Miss-you @membphis

**Comment by membphis** [comment]
@juzhiyuan the Admin API has implemented the `global rule` API: https://github.com/apache/apisix/blob/5de6ee467f83c38f31eff6cfd683736b441ac9c2/doc/zh-cn/architecture-design.md#global-rule

So I think we'd better use the existing APIs.

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/102013971-5d9aab80-3d8e-11eb-936a-70058bcbab12.png)

**Comment by juzhiyuan** [comment]
@membphis np, I just updated the proposal.

**Comment by nic-chen** [comment]
I think the APIs should be consistent with the existing, [refer to](https://github.com/apache/apisix/blob/master/doc/architecture-design.md#Global-Rule):

**API: set global rule**
```
PUT /apisix/admin/global_rules/1
```
```json
{
        "plugins": {
            "limit-count": {
                "time_window": 60,
                "policy": "local",
                "count": 2,
                "key": "remote_addr",
                "rejected_code": 503
            }
        }
    }
```

**API: get global rule**
```
GET /apisix/admin/global_rules/1
```
```json
{
        "plugins": {
            "limit-count": {
                "time_window": 60,
                "policy": "local",
                "count": 2,
                "key": "remote_addr",
                "rejected_code": 503
            }
        }
    }
```

**API: get global rule list(new)**
```
GET /apisix/admin/global_rules?page=1&page_size=10
```
```json
{
    "code": 0,
    "message": "",
    "data": {
        "rows": [
            {
                "id": 1,
                "plugins": {
                    "limit-count": {
                        "time_window": 60,
                        "policy": "local",
                        "count": 2,
                        "key": "remote_addr",
                        "rejected_code": 503
                    }
                }
            }
        ]
    }
}
```

**Comment by juzhiyuan** [comment]
The only difference between your comment and this proposal is, this proposal doesn't have the target rule id, as a global API, why there will have **multiple global** records? but yes, you are right, for the frontend, it will use the target rule id, there will not have a global rule list.

![image](https://user-images.githubusercontent.com/2106987/102031594-683a5c80-3df1-11eb-82a7-005f477f7743.png)

![image](https://user-images.githubusercontent.com/2106987/102031601-70929780-3df1-11eb-8f38-66e7d07dd511.png)

**Comment by moonming** [comment]
There is a more obvious problem in this design:
The plugin menu bar on the left is not just for global plugins. It can also become a universal plug-in object like service and upstream. For example, a limit count plugin and configuration can be referenced by multiple routes.

The global plug-in is just an attribute of the plug-in, and it is not worth a separate menu.

**Comment by juzhiyuan** [comment]
after discussion with @membphis @moonming @nic-chen, we have reached an agreement in the general direction, I will update the proposal today:
- UE
- features in the future

**Comment by juzhiyuan** [comment]
Hello, I just updated this proposal, kindly review when you are free 😊

cc @nic-chen @liuxiran  @membphis @moonming

**Comment by sampy2518** [comment]
I have a peculiar situation in my project where I am trying to replace my existing old Proxy code with APISIX. my current proxy backtrack the versions apis and services in a different way. for example. 
API Versions available : V1, V2, V3

Routes should be created in below format 
V1
	API1 
		Service1
		Service2 
	API2
		Service3
		Service4
	API3
		Service5

V2
	API2
		Service4
	API4 
		Service6
V3
	API2
		Service4
	API5 
		Service7

API routing, fallback and backtracking rules to follow 
case 1:  	
APP A : current Version used V2. All any API from the frontend will be called with V2

Invoke V2/API1/Service1/ will be redirected to V1/API1/Service1, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service1 in API1.

Invoke V2/API1/Service2/ will be redirected to V1/API1/Service2, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service2 in API1.

Invoke V2/API2/Service3/ will be redirected to V1/API2/Service3, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service3 in API2.

Invoke V2/API2/Service4/ will be redirected to V2/API2/Service4, As it is present in V2
 
Invoke V2/API3/Service5/ will be redirected to V1/API3/Service5, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service5 in API3.

Invoke V2/API4/Service6/  will be redirected to V2/API4/Service6, As it is present in V2

case 2:  	
APP b : current Version used V3. All any API from the frontend will be called with V3

Invoke V3/API1/Service1/ will be redirected to V1/API1/Service1, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service1 in API1.

Invoke V3/API1/Service2/ will be redirected to V1/API1/Service2, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service2 in API1.

Invoke V3/API2/Service3/ will be redirected to V1/API2/Service3, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service3 in API2.

Invoke V3/API2/Service4/ will be redirected to V3/API2/Service4, As it is present in V3
 
Invoke V3/API3/Service5/ will be redirected to V1/API3/Service5, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service5 in API3.

Invoke V3/API4/Service6/ will be redirected to V2/API4/Service6, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V2 and search for the Service6 in API4.

Invoke V3/API4/Service7/ will be redirected to V3/API5/Service7, As it is present in V3

I would like to ask how can i define a customer global plugin which is work when for any incoming request from client and rewrite the URL as per above rule.
