### ISSUE TITLE
[Proposal]: Alarm Mechanism

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#822]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [X] Feature or performance improvement
- [ ] Other

### Why
To allow users to see anomalies in the system. I propose that we need to add an alarm module, and for now consider the alarm on the route

#### Front-End
1. An alarm configuration page needs to be added. 
The page needs to include the following fields (temporary)
   - Severity: High, Medium, Low, Ignore
   - Event Type：All event types、Status Code、Traffic、Latency、Unknown Parameters、Abnormal Values、Value Type
   - HTTP Methods 
2. Alarm list page

#### Back-end
1. Need a field data interface to receive front-end pages. 
2. Need a list interface to display alert messages.
#### APISIX
Not sure if APISIX needs to be changed.

**Comment by juzhiyuan** [comment]
cc @nic-chen @membphis @tokers @liuxiran

**Comment by membphis** [comment]
This feature can be implemented in `grafana`.

https://grafana.com/docs/grafana/latest/alerting/create-alerts/

**Comment by nic-chen** [comment]
I prefer to use grafana too

**Comment by juzhiyuan** [comment]
Just to make sure, do you mean we don't need to implement this feature, just use Grafana is ok?

**Comment by membphis** [comment]
> Just to make sure, do you mean we don't need to implement this feature, just use Grafana is ok?

I think this is enough

**Comment by juzhiyuan** [comment]
fine, then we could close this issue now.
