### ISSUE TITLE
[Proposal]: Version management of route

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#823]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [X] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

Need more time to think.

**Comment by moonming** [comment]
Why empty?

**Comment by juzhiyuan** [comment]
For draft proposal, please add some attractive notes, such as in title [DRAFT]

**Comment by LiteSun** [comment]
In order to manage api more finely, I propose to add api version management feature.

## front-end
 - add version management section in route step1 page
 
![image](https://user-images.githubusercontent.com/31329157/102568888-6b9a5480-411f-11eb-93b5-7f3bf69585f8.png)

- when `enable version` turn on,  section `version config` and `version table` will show.

![image](https://user-images.githubusercontent.com/31329157/102569147-df3c6180-411f-11eb-9aee-31c67c6ddfb6.png)

![image](https://user-images.githubusercontent.com/31329157/102569417-67226b80-4120-11eb-90e4-fe0e48439d01.png)

- when click `add` or `edit`, `Edit version drawer` will show.
![image](https://user-images.githubusercontent.com/31329157/102569807-20814100-4121-11eb-8653-7e7c02db1c80.png)

## back-end
- `POST /apisix/admin/routes` and `PUT /apisix/admin/routes` need to  support `version`.

```json
{
...,
...,
version: {
    enable: true,
    location:'header' | 'url' | 'first part of path',
    strip_versio?n: false,
    name:'string',
    default: 'string',
    version_list:[{
                value:'v1',
                override target host:'string',
                expires: timestamp
    },{}]
}
}
```

- need a new API to get version list, `get /version`:
```json
   version_list:[{
                value:'v1',
                override target host:'string',
                expires: timestamp
    },{}]
```

## apisix
need to discuss.

cc @juzhiyuan @liuxiran  @moonming @membphis @nic-chen

**Comment by membphis** [comment]
In the first version, I think it is enough to control the API version by only supporting the header.
This makes our implementation design easier.

I was confused with `Edit version drawer` and `version table`, need more docs @LiteSun , I can not understand them.

**Comment by LiteSun** [comment]
> I was confused with `Edit version drawer` and `version table`, need more docs @LiteSun , I can not understand them.

1. version table is used to show the version list, just like our  `Advanced Routing Matching Conditions`
![image](https://user-images.githubusercontent.com/31329157/102585838-09a01600-4144-11eb-8ca1-b1d93dae3508.png)

2.` Edit version drawer` is used to edit or create a version item. will trigger show when you click the `add` button or `edit`

**Comment by juzhiyuan** [comment]
I will take this proposal.
