### ISSUE TITLE
Add docker image that contains apisix, apisix-dashboard and all dependencies 

### ISSUE THREAD

**Issue by moonming** [apache/apisix-dashboard#824]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
Users do not need to install any dependencies, such as OpenResty, etcd, Node, Go etc., and can directly experience Apache APISIX and dashboard. 

Of course, it is not recommended to use in the production environment.

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by tokers** [comment]
What about the dependencies of plugins? So users can experience the plugins also.

**Comment by moonming** [comment]
yes, we need install all dependencies, including plugins.

**Comment by gxthrj** [comment]
I think putting all dependencies in a `base image` may be a good choice .

**Comment by juzhiyuan** [comment]
any update?

**Comment by gxthrj** [comment]
Before submitting, I want to discuss the implementation method. I am not going to modify the `Dockerfile` in the root directory. It is for production.

Suggest to create a new docker directory to store the new `Dockerfile` to solve this issue.

Do you agree ?

**Comment by juzhiyuan** [comment]
Do this in the apisix-docker repo?

**Comment by gxthrj** [comment]
> Do this in the apisix-docker repo?

Yes, it is OK.

After that, apisix-docker will serve two projects: APISIX & APISIX dashboard.

What other people think? @moonming @membphis @nic-chen

**Comment by nic-chen** [comment]
> Before submitting, I want to discuss the implementation method. I am not going to modify the `Dockerfile` in the root directory. It is for production.
> 
> Suggest to create a new docker directory to store the new `Dockerfile` to solve this issue.
> 
> Do you agree ?

agree with that. It should be another `Dockerfile`

**Comment by membphis** [comment]
@gxthrj please confirm if we can close this issue
