### ISSUE TITLE
chore: manager api should exit when ETCD can't be connect

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#827]
manager api should exit when ETCD can't be connect

at the same time should print error on screen not just log file.

**Comment by membphis** [comment]
> manager api should exit when ETCD can't be connect

Only when it starts?

**Comment by jinchizhou** [comment]
Is this still an issue? I'd like to contribute to this open source project!

**Comment by nic-chen** [comment]
Hi, @jinchizhou 
This issue have been resolved incidentally by some PR.

I think you could try other issue that suitable for first PR like:  #566

Here is some develop guide:
https://github.com/apache/apisix-dashboard/blob/master/docs/develop.md

If you have any questions, please feel free to contact me in the issue or the PR you submitted. 

Thanks.

**Comment by juzhiyuan** [comment]
> Hi, @jinchizhou 
> This issue have been resolved incidentally by some PR.
> 
> I think you could try other issue that suitable for first PR like:  #566
> 
> Here is some develop guide:
> https://github.com/apache/apisix-dashboard/blob/master/docs/develop.md
> 
> If you have any questions, please feel free to contact me in the issue or the PR you submitted. 
> 
> Thanks.
> 

Closed
