### ISSUE TITLE
bug: `manager-api` should be mutually exclusive

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#828]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

`manager-api` should be mutually exclusive, do not continue to run other instances when it is found that there is already a `manager-api` running, it can display an message, should not record error logs.

**Comment by nic-chen** [comment]
it can't run multi instances that using same port, and duplicate with  #827
