### ISSUE TITLE
v2.0  release  manager-api  Emergency stop

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix-dashboard#836]
v2.0  release manager-api  Emergency stop
Service is often shut down after a while
view log
/usr/local/apisix-dashboard/output/logs
<img width="694" alt="image" src="https://user-images.githubusercontent.com/17898385/99783746-ca3ad580-2b55-11eb-9f74-0658c3a0999b.png">

**Comment by juzhiyuan** [comment]
Which version are you using from 2.0? RC4 or RC5?

**Comment by liubinqi2007** [comment]
> Which version are you using from 2.0? RC4 or RC5?

![image](https://user-images.githubusercontent.com/17898385/99785047-9c569080-2b57-11eb-9408-e5dc2f3f35a9.png)

**Comment by nic-chen** [comment]
@liubinqi2007  

thanks for feedback.

what OS do you run on?

**Comment by liubinqi2007** [comment]
> @liubinqi2007
> 
> thanks for feedback.
> 
> what OS do you run on?
centos 7

**Comment by nic-chen** [comment]
@liubinqi2007  is there other logs？

**Comment by liubinqi2007** [comment]
> @liubinqi2007 is there other logs？

no

**Comment by nic-chen** [comment]
@liubinqi2007 
could you contact my QQ 4061470 ? Which talk more conveniently

**Comment by nic-chen** [comment]
@liubinqi2007
please confirm the result and then share here, thanks.

**Comment by liubinqi2007** [comment]
已解决

**Comment by moonming** [comment]
How did it solved？ @nic-chen

**Comment by nic-chen** [comment]
He used 

```sh
$ ./manager-api &
``` 
to run `manager api`, so it automatically exit after the terminal closed a while.


After using
```sh
$ nohup ./manager-api &
``` 
It works fine.

**Comment by moonming** [comment]
so I think we need to support `deamon`

**Comment by nic-chen** [comment]
@moonming  sure. I had created an issue about this before. #842
