### ISSUE TITLE
feat: Refactor Route publish and offline

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#837]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement

Refer to: 
#611
#437 

### Refactor:

- APISIX implement Route publish/offline status in dp (issue: https://github.com/apache/apisix/issues/2737)

- manager-api provides an interface to write data to etcd

- fe add publish and offline button to every route item list table, at the same time, create route also need to add a publish form item.

**Comment by juzhiyuan** [comment]
cc @nic-chen

**Comment by nic-chen** [comment]
LGTM

**Comment by juzhiyuan** [comment]
Then do we have a final plan? dev, due date, and so on.

**Comment by LiteSun** [comment]
I think this issue should be kept in sync with the apisix (issue: https://github.com/apache/apisix/issues/2737) milestone.

**Comment by moonming** [comment]
This PR is in 2.2 milestone, and Apache APISIX supports it in https://github.com/apache/apisix/pull/2943

**Comment by moonming** [comment]
What is the progress in dashboard? @liuxiran @nic-chen

**Comment by membphis** [comment]
this feature depends on https://github.com/apache/apisix/pull/2943

we need to release a new version of APISIX. so I want to change the milestone to `2.3`

@liuxiran @nic-chen please confirm if this is ok ^_^

**Comment by liuxiran** [comment]
> this feature depends on [apache/apisix#2943](https://github.com/apache/apisix/pull/2943)
> 
> we need to release a new version of APISIX. so I want to change the milestone to `2.3`
> 
> @liuxiran @nic-chen please confirm if this is ok ^_^

ok, and related pr for fe and manager-api will be created as a draft later this week.

**Comment by LiteSun** [comment]
Just for reminder: [apache/apisix#2943](https://github.com/apache/apisix/pull/2943) is merged two days ago. cc @liuxiran
