### ISSUE TITLE
Bug: Add defer recover for all go routines to prevent abnormal crash of manager-api

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-dashboard#838]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
2.0

- What happened?
Manager-api may crash without any logs.
In gin, we use `filter.RecoverHandler()` to prevent crash. 
But we can not control the exceptions in other go-routines.
Need to add `defer recover()` for all go routines to prevent abnormal crash of manager-api .

**Comment by tokers** [comment]
We may use https://github.com/kubernetes/apimachinery/blob/master/pkg/util/runtime/runtime.go#L45 to handle it.

**Comment by juzhiyuan** [comment]
Any update for this issue?

**Comment by gxthrj** [comment]
cc @nic-chen @starsz what do you think about this

**Comment by starsz** [comment]
> cc @nic-chen @starsz what do you think about this

Agree +1. But what should we do if we catch the other goroutine panic?

**Comment by nic-chen** [comment]
> cc @nic-chen @starsz what do you think about this

sure, agree +1
