### ISSUE TITLE
feat: support to connect etcd with `username` and `password`

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#839]
`etcd` can specify access username/password and assign different permissions, which is more secure.

`manager-api` needs to support this feature.

**Comment by membphis** [comment]
related PR: https://github.com/apache/apisix-dashboard/pull/811

**Comment by juzhiyuan** [comment]
Will this be resolved in 2.2?

**Comment by membphis** [comment]
I think `2.2` is fine. I add this issue to `2.2` milestone

**Comment by juzhiyuan** [comment]
Who is glad to resolve this issue?

**Comment by nic-chen** [comment]
close by #951
