### ISSUE TITLE
feat: support run `manager api` as OS service

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#842]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
in 2.3?

**Comment by tokers** [comment]
You mean systemd and supervisord?

**Comment by juzhiyuan** [comment]
Ya, would this issue be resolved in M2.3?

**Comment by membphis** [comment]
@nic-chen @tokers It depends on building the package for the specific OS, eg: ubuntu, centos.  

I think we can remove milestone `2.3`.

**Comment by nic-chen** [comment]
> @nic-chen @tokers It depends on building the package for the specific OS, eg: ubuntu, centos.
> 
> I think we can remove milestone `2.3`.

OK

**Comment by juzhiyuan** [comment]
any plan?

**Comment by bisakhmondal** [comment]
Hello guys, can I give it a try to demonize the manager_api which includes making the necessary change in the main program (terminating on SIGTERM, SIGKILL & reloading configurations on SIGHUP) & create it as a systemd service in Linux?
Thank you.

**Comment by nic-chen** [comment]
> Hello guys, can I give it a try to demonize the manager_api which includes making the necessary change in the main program (terminating on SIGTERM, SIGKILL & reloading configurations on SIGHUP) & create it as a systemd service in Linux?
> Thank you.

sure, PR is welcome!

**Comment by bisakhmondal** [comment]
Hii everyone, I have opened a draft PR. Though it is not fully complete, I would love to have this reviewed by you all.
Currently, the config is facing a write permission error to write logs in `error.log` file
Here's the last log in reverse ordering

```-- Logs begin at Mon 2021-03-15 21:16:03 IST, end at Wed 2021-03-24 23:52:48 IST. --
Mar 24 23:42:50 turing systemd[1]: Stopped Manager-API service.
Mar 24 23:42:45 turing systemd[1]: manager-api.service: Failed with result 'exit-code'.
Mar 24 23:42:45 turing systemd[1]: manager-api.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/Desktop/OSS/apisix-dashboard/api/cmd/manager/main.go:27 +0x2b
Mar 24 23:42:45 turing manager-api[377717]: main.main()
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
Mar 24 23:42:45 turing manager-api[377717]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fe
Mar 24 23:42:45 turing manager-api[377717]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f2c80, 0xc000000180, 0xc000031f78, 0x407d85)
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x47c
Mar 24 23:42:45 turing manager-api[377717]: github.com/spf13/cobra.(*Command).execute(0xc0004f2c80, 0xc0001181b0, 0x0, 0x0, 0xc0004f2c80, 0xc0001181b0)
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/Desktop/OSS/apisix-dashboard/api/cmd/managerapi.go:76 +0xbb
Mar 24 23:42:45 turing manager-api[377717]: github.com/apisix/manager-api/cmd.NewManagerAPICommand.func1(0xc0004f2c80, 0x1721268, 0x0, 0x0, 0x0, 0x0)
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/Desktop/OSS/apisix-dashboard/api/internal/log/zap.go:39
Mar 24 23:42:45 turing manager-api[377717]: github.com/apisix/manager-api/internal/log.InitLogger(...)
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/Desktop/OSS/apisix-dashboard/api/internal/log/zap.go:43 +0x3f
Mar 24 23:42:45 turing manager-api[377717]: github.com/apisix/manager-api/internal/log.GetLogger(0x0, 0x3)
Mar 24 23:42:45 turing manager-api[377717]:         /home/bisakh/Desktop/OSS/apisix-dashboard/api/internal/log/zap.go:103 +0x208
Mar 24 23:42:45 turing manager-api[377717]: github.com/apisix/manager-api/internal/log.fileWriter(0x0, 0x0, 0x0)
Mar 24 23:42:45 turing manager-api[377717]: goroutine 1 [running]:
Mar 24 23:42:45 turing manager-api[377717]: panic: couldn't open sink "/home/bisakh/Desktop/OSS/apisix-dashboard/output/logs/error.log": open /home/bisakh/Desktop/OSS/apisix-dashboard/output/logs/error.log: permission denied
Mar 24 23:42:45 turing systemd[1]: Started Manager-API service.
Mar 24 23:42:45 turing systemd[1]: Starting Manager-API service...
Mar 24 23:42:45 turing systemd[1]: Stopped Manager-API service.
Mar 24 23:42:45 turing systemd[1]: manager-api.service: Scheduled restart job, restart counter is at 74.
Mar 24 23:42:40 turing systemd[1]: manager-api.service: Failed with result 'exit-code'.
```
is this issue regarding `writer, _, err := zap.Open(logPath)` for not providing any permission/umask explicitly.

It would be great if you guys could provide any sort of guide/help. Thank you.

**Comment by juzhiyuan** [comment]
cc @starsz @nic-chen to help when you have time.

**Comment by nic-chen** [comment]
hi @bisakhmondal 
Need to confirm, is the owner of the logs directory and running manager-api the same user?

**Comment by bisakhmondal** [comment]
hii @nic-chen thanks for the heads up,
its working perfectly now,
latest logs in reverse order
```
-- Logs begin at Mon 2021-03-15 21:16:03 IST, end at Fri 2021-03-26 17:12:41 IST. --
Mar 26 17:12:09 turing manager-api[571177]: Logfile : /home/bisakh/Desktop/OSS/apisix-dashboard/output/logs/error.log
Mar 26 17:12:09 turing manager-api[571177]: Loglevel: warn
Mar 26 17:12:09 turing manager-api[571177]: Listen  : 127.0.0.1:9000
Mar 26 17:12:09 turing manager-api[571177]: GitHash : efdb869
Mar 26 17:12:09 turing manager-api[571177]: Version : 2.4
Mar 26 17:12:09 turing manager-api[571177]: The manager-api is running successfully!
Mar 26 17:12:09 turing systemd[1]: Started Manager-API service.
Mar 26 17:12:09 turing systemd[1]: Starting Manager-API service...
```
it was causing by 
`PermissionsStartOnly=true`  which was overriding user & group info to provide syslog access over the generated logs(stdout & stderr).
so putting 
```
User=<>
Group=<>
```
after syslog initialization (which was put before the statement by me earlier), solves it. 
Thanks, pushing the changes soon.

**Comment by bisakhmondal** [comment]
Hi guys, do we have to document the features introduced in #1667?
I forgot to add it into the respective PR😅

**Comment by juzhiyuan** [comment]
ya, if there have features introduced, then we should update the document.

**Comment by nic-chen** [comment]
> Hi guys, do we have to document the features introduced in #1667?
> 
> I forgot to add it into the respective PR😅

sure, please add it, thanks.😄
