### ISSUE TITLE
Key verification failure occurs intermittently for routes with key verification enabled

### ISSUE THREAD

**Issue by nirvanareborn** [apache/apisix-dashboard#848]
# Bug report
Key verification failure occurs intermittently for routes with key verification enabled

## Describe the bug
Key verification is enabled for routing, which can be verified in most cases. Occasionally, it fails to be verified. This happens in a fixed time window.
![apisix3](https://user-images.githubusercontent.com/3364969/99922845-9afeb100-2d6d-11eb-92fa-c58883f17588.jpg)
![apisix2](https://user-images.githubusercontent.com/3364969/99922722-f7150580-2d6c-11eb-8d3e-1065e6dc68db.png)
![apisix1](https://user-images.githubusercontent.com/3364969/99922759-1f9cff80-2d6d-11eb-86bb-4e0ab5c26a82.jpg)

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [Linux]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0]

**Comment by nirvanareborn** [comment]
![1](https://user-images.githubusercontent.com/3364969/99924200-3430c600-2d74-11eb-8212-80997010648f.png)

**Comment by tokers** [comment]
@nirvanareborn Could you paste the complete Route, Consumer configuration? Some part of them are collapsed.

**Comment by nic-chen** [comment]
Please confirm the nginx processes for APISIX and confirm that all processes are OK (no orphan process or double master process).

**Comment by nirvanareborn** [comment]
@tokers The above is the complete routing and comsumer configuration information
路由
![1](https://user-images.githubusercontent.com/3364969/99926642-5bd85c00-2d7d-11eb-96ef-46e09a7e1fe2.png)
Consumer
![2](https://user-images.githubusercontent.com/3364969/99926657-64309700-2d7d-11eb-9722-c87bf7265263.png)

**Comment by nirvanareborn** [comment]
@nic-chen 
the nginx processes for APISIX  all processes are OK (no orphan process or double master process).

![11](https://user-images.githubusercontent.com/3364969/99926759-ba9dd580-2d7d-11eb-8b54-c570a7ceaaa5.png)

**Comment by tokers** [comment]
Are there some logs in your error.log? @nirvanareborn

**Comment by nic-chen** [comment]
have you update config of the consumer (change the key) ?

**Comment by nirvanareborn** [comment]
@nic-chen I haven't updated the configuration of the consumer

**Comment by nirvanareborn** [comment]
@tokers No error log,only access log。
![1](https://user-images.githubusercontent.com/3364969/99940856-fcdc0c80-2da7-11eb-92c4-db4cc720fd3a.png)

**Comment by juzhiyuan** [comment]
ping @nic-chen

**Comment by nic-chen** [comment]
We use real-time chat tools to contact, which makes it easier to locate what is going on.

**Comment by membphis** [comment]
If there is any new news, please leave a message.

**Comment by nic-chen** [comment]
This bug had fixed by PR:
https://github.com/apache/apisix/pull/2575#discussion_r521784444

**Comment by nirvanareborn** [comment]
Thank you very much ！
