### ISSUE TITLE
frontend APISIX instance status page

### ISSUE THREAD

**Issue by tokers** [apache/apisix-dashboard#850]
# Feature request

## Please describe your feature
We have already some discussions about this topic: https://lists.apache.org/thread.html/re3097f7e88d636e8137231c36462c32773b2b4817d91f7997e91358f%40%3Cdev.apisix.apache.org%3E.

## Additional context

This thread is used to track the development progress of Dashboard frontend part.

The related issues:

* https://github.com/apache/apisix/issues/2821
* apache/apisix-dashboard#849

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/99937911-b71c4580-2da1-11eb-8b18-a22e0f55b45a.png)

Hi, how about using this sketch to build the web page?

Note: All values will be formatted in JSON (stringify).

cc @liuxiran @tokers @LiteSun @moonming

**Comment by juzhiyuan** [comment]
After discussion with @tokers @starsz, here is the latest sketch for the info page.

![image](https://user-images.githubusercontent.com/2106987/99941383-e7b3ad80-2da8-11eb-812d-145e381f29c2.png)

- supports showing apisix nodes' status by using selector.

## JSON for target apisix's node

```json
{
    "data":[
        {
            "category":"system",
            "version":"2.0"
        },
        {
            "category":"system",
            "apisix_id":"2.1"
        },
        {
            "category":"categoryA",
            "key":"value1"
        },
        {
            "category":"categoryA",
            "key":"value2"
        },
        {
            "category":"categoryB",
            "key":"value1"
        },
        {
            "category":"categoryB",
            "key":{
                "customKey1":"customValue1"
            }
        }
    ]
}
```

**Comment by juzhiyuan** [comment]
waiting for #849

**Comment by juzhiyuan** [comment]
@starsz @tokers Could we have API schema confirmed? so that the frontend would go parallel.

**Comment by juzhiyuan** [comment]
This issue would be addressed by @guoqqqi

**Comment by guoqqqi** [comment]
> This issue would be addressed by @guoqqqi

OK, please let me handle it

**Comment by guoqqqi** [comment]
OK, please let me handle it

**Comment by membphis** [comment]
this feature depends on https://github.com/apache/apisix/pull/2926

we need to release a new version of APISIX first.
so I want to change the milestone to 2.3

@tokers @guoqqqi @juzhiyuan  please confirm if this is ok ^_^

**Comment by juzhiyuan** [comment]
Ok for me, the frontend is ready, once apisix and manager api are ready, we would release them soon 😊
