### ISSUE TITLE
bug: manager-api do not support add consumer with custom create time or update time

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#851]
# Bug report

## Describe the bug
use manager-api add a consumer with custom create time or update time, 
but the consumer actually created does not use the custom time.

**Comment by starsz** [comment]
Hi, @idbeta, I can't get your point. 
Can you give me an example or steps to reproduce the issue?

**Comment by idbeta** [comment]
hi, @starsz you can refer tohttps://github.com/apache/apisix-dashboard/pull/830/files#diff-d6674616f38aabf4e6e7f91f04b057982213b9b3758fc363ffc140843db957e3R344-R385
this case is failed, it will return the current timestamp.

**Comment by starsz** [comment]
OK, I reproduce the issue.

**Comment by ShiningRush** [comment]
I don't think it is a bug, audit field should maintain by server not client.So we should not accept client audit field such as CreatedAt, CreatedBy etc.

**Comment by juzhiyuan** [comment]
Not sure if it's a bug indeed, what's your opinion? I would be more prefer with @ShiningRush's opinion 🤔

cc @membphis @nic-chen @liuxiran @tokers

**Comment by liuxiran** [comment]
> I don't think it is a bug, audit field should maintain by server not client.So we should not accept client audit field such as `CreatedAt`, `CreatedBy` etc.

agree +1.
If the user customizes these fields, it goes against the original intent of using these fields to record the time.

**Comment by nic-chen** [comment]
> I don't think it is a bug, audit field should maintain by server not client.So we should not accept client audit field such as `CreatedAt`, `CreatedBy` etc.

agree +1

**Comment by starsz** [comment]
OK. So the conclusion is that we should not accept the client audit fields such as CreatedAt, CreatedBy.
If the client put those fields, just ignore them.

**Comment by juzhiyuan** [comment]
Should we add this tip to FAQ?

**Comment by idbeta** [comment]
At the beginning, I referred to the processing of adminAPI. After reading your comments, I think that manager-api does not need to be the same as adminAPI at this point. I will modify the related test cases.
