### ISSUE TITLE
bug: manager-api supported `POST` method for consumer

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#852]
# Bug report

## Describe the bug
manager-api supported `POST` method for consumer.
but it should not support the `POST` method for consumer, the same as APISIX's adminapi.
```testcase
{
			caseDesc: "create consumers with post method",
			Object:   MangerApiExpect(t),
			Path:     "/apisix/admin/consumers",
			Method:   http.MethodPost,
			Body: `{
				"username":"case_9",
				"desc": "new consumer",
				"create_time": 1602883670,
				"update_time": 1602893670
		   }`,
			Headers:      map[string]string{"Authorization": token},
			ExpectStatus: http.StatusMethodNotAllowed,
		},
```

**Comment by starsz** [comment]
Hi, @idbeta. It's easy to fix, you can assign it to me.

**Comment by juzhiyuan** [comment]
The frontend will use put instead of post now.

**Comment by membphis** [comment]
> So I think apisix-dashboard should forbid `POST` and merge `Create and Update` into a function which was called by`PUT` method.

agree with this. @starsz would like to fix this issue?

**Comment by starsz** [comment]
> > So I think apisix-dashboard should forbid `POST` and merge `Create and Update` into a function which was called by`PUT` method.
> 
> agree with this. @starsz would like to fix this issue?

My pleasure, please assign to me.
