### ISSUE TITLE
feat: show some important information after started the `manager-api`

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#853]
# Feature request

After starting manager-api, no information is output.
Make new users easily confused.

We can print some tips and make this step more friendly.

![image](https://user-images.githubusercontent.com/6814606/99930312-90531480-2d8b-11eb-9f4f-2751e2c9a03b.png)

## Describe the solution you'd like

Show some important things for the user. 

For example: `manager-api is running, and listen on: http://127.0.0.1:8080.`

**Comment by membphis** [comment]
@nic-chen what do you think?

**Comment by nic-chen** [comment]
> @nic-chen what do you think?

yes, it is good for users.

**Comment by starsz** [comment]
Hi, @membphis @nic-chen, I think I can do this for the community. You can assign it to me.

**Comment by nic-chen** [comment]
> Hi, @membphis @nic-chen, I think I can do this for the community. You can assign it to me.

thanks!

**Comment by juzhiyuan** [comment]
Just to make sure, what will log when starting the manager-api? How about this one?

```
The manager-api is running successfully！

You can now access it by using those addresses.

  Local:            http://localhost:3000
  On Your Network:  http://172.16.21.71:3000
```

**Comment by starsz** [comment]
Hi,@juzhiyuan. I think the version info is needed.

And it's difficult to get  `On your network` info accurately if the machine has multiple network cards.

**Comment by juzhiyuan** [comment]
oh yes! 

Please add some needed info in the log :)

**Comment by starsz** [comment]
Need to finish #866 first.

**Comment by starsz** [comment]
It looks like this.

How about it?

```
The manager-api is running successfully!

Version : v2.1-rc1(277ae59)
Listen  : 127.0.0.1:8080
Loglevel: warn
Logfile : /Users/Work/apisix-dashboard/api/logs/error.log
```

**Comment by juzhiyuan** [comment]
🤔 `Listen on` and `Log path`would be better IMO
