### ISSUE TITLE
bug: 2.1 version schema-sync.sh display error when sync apisix's custom plugin.

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#865]
# Bug report

## Describe the bug
2.1 version schema-sync.sh display error when sync apisix's custom plugin.
```
... ...
lua: ./apisix/plugins/batch-requests.lua:23: attempt to index a nil value (field 'string')
stack traceback:
	./apisix/plugins/batch-requests.lua:23: in main chunk
	[C]: in function 'require'
	schema-sync.lua:134: in main chunk
	[C]: in ?
```

**Comment by moonming** [comment]
How to reproduce？

**Comment by idbeta** [comment]
> How to reproduce？

create a custom plugin, then follow the [FAQ](https://github.com/apache/apisix-dashboard/blob/master/docs/FAQ.md#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard)

**Comment by moonming** [comment]
`batch-requests` is not a custom plugin.

**Comment by membphis** [comment]
that is a bug, confirmed.

https://github.com/apache/apisix-dashboard/blob/master/api/build-tools/schema-sync.lua#L55-L56

here is a way we can make a try:

```lua
local t_idx = {
    __index = function (t, key)
        local val = {}
        rawset(t, key, val)
        return val
   end
}

package.loaded['apisix.core'] = {
    __index = t_idx
}
```

**Comment by membphis** [comment]
https://github.com/apache/apisix-dashboard/commit/cdab40954340d37c94a5e7e6fecf41a4020e2570#diff-89ff393b58f42ba20bebfddf49f17dc9652e90d21a47a10727da861c16b3fdabR110-R111

fixed this issue
