### ISSUE TITLE
feat: manager-api need show version info

### ISSUE THREAD

**Issue by starsz** [apache/apisix-dashboard#866]
# Feature request

## Please describe your feature

Hi, I think manager-api needs version info. 

Like: `./manager-api version`

And when `manager-api` start, show the manager-api version.

releated #853 

## Describe the solution you'd like

In golang, there are some ways to manage version.

1. Create a file, named `version.go` and write the current version in this file.

2. Use go build ldflags. Such as 
`go build -ldflags "-X main.VERSION=1.0.0 -X 'main.BUILD_TIME=date' -X 'main.GO_VERSION=go version'"`
We can add this into Makefile.

I prefer the second solution.

**Comment by juzhiyuan** [comment]
Do we have any ideas?

cc @liuxiran @tokers @nic-chen @membphis @ShiningRush

**Comment by tokers** [comment]
AFAIK, Most golang projects are using the second way to inject the version info.

**Comment by membphis** [comment]
> Most golang projects are using the second way to inject the version info, like istio, etcd.

This is a good reason.

**Comment by nic-chen** [comment]
second way +1
but could the version be read by status API mention in #849 ?

**Comment by tokers** [comment]
@nic-chen The status API in #849 exposes APISIX instances' data, which contains APISIX version.

**Comment by nic-chen** [comment]
> @nic-chen The status API in #849 exposes APISIX instances' data, which contains APISIX version.

sure. I know that. but I think we should expose data of `manager-api` too.
