### ISSUE TITLE
Support priority field in Route module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#879]
# Feature request

## Please describe your feature

Users could use the priority field to do some actions like a grayscale release.

## Describe the solution you'd like

1. Add that field in the Route module.

## Describe alternatives you've considered

None

## Additional context

None

**Comment by juzhiyuan** [comment]
cc @nic-chen I remember the manager-api supports this field, right?

cc @membphis

**Comment by membphis** [comment]
need @nic-chen 's confirm. `manager-api` should support this field, same as `admin api`

**Comment by nic-chen** [comment]
> cc @nic-chen I remember the manager-api supports this field, right?
> 
> cc @membphis

sure, it has supported.
