### ISSUE TITLE
the manger API should not listen 8080, which is the port of data plane

### ISSUE THREAD

**Issue by moonming** [apache/apisix-dashboard#901]
# Bug report

https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L21

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

**Comment by nic-chen** [comment]
@moonming 
OK. What is the recommended port? 9081 or 8081? Thanks.

**Comment by moonming** [comment]
@gxthrj @membphis @spacewander @tokers what do you think about the port of CP?

**Comment by nic-chen** [comment]
ping @gxthrj @membphis @spacewander @tokers  
request help, thanks.

**Comment by tokers** [comment]
@moonming Since the admin api port in DP will be changed to 9180 in version 3.0, what about using 9180 also?

**Comment by membphis** [comment]
We used port `9180` as CP in APISIX before, I think this is not a good port.

I prefer `9000` now.  Here are the reasons:

1. The ports on the control plane and the data plane should be very different.
2. The port of the control plane allows the use of HTTP protocol or HTTPS protocol. So this port number avoids any protocol-related identification (such as 80 or 443).

**Comment by gxthrj** [comment]
But I think `80`/ `443` is more accepted by the public, and the manager-api will be completely independent in 3.0, the port of `CP` and `DP` do not affect each other, so we can treat `CP` as an independent project.

**Comment by nic-chen** [comment]
Through a meeting, it was finally determined that the default port of dashboard manager api will change to 9000.

Participants:
@gxthrj @membphis @spacewander @tokers @moonming @ShiningRush @nic-chen 


will send a mail to our maillist.
