### ISSUE TITLE
Manage multiple apisix gateways with one dashboard

### ISSUE THREAD

**Issue by hyt05** [apache/apisix-dashboard#905]
My company is using four kubernetes clusters, which are distributed in different geographic locations, namely "dev, staging, production, and Ali cloud". 

I want to use apisix instead of the default nginx Controller. For this reason, I don’t want to deploy multiple apisi dashbord, which not only increases the amount of operation and maintenance, but also inconvenient my operation. Can the current apisix dashbord manage apisix entries in multiple geographic locations?

For example: konga https://github.com/pantsel/konga.git
It can add multiple kong gateway addresses in the web interface, and then pay attention to configuring each kong gateway

**Comment by juzhiyuan** [comment]
cc @ShiningRush @membphis @liuxiran

**Comment by membphis** [comment]
cc @gxthrj

**Comment by membphis** [comment]
This is a very interesting and important feature.

But it is not useful for all users. A simple and easy-to-use version will be welcomed by the community.

Welcome to the mailing list to discuss project design with everyone.

**Comment by gxthrj** [comment]
This is a requirement for unified management of multiple clusters with one dashboard. The simple solution is to switch and manage multiple APISIX clusters on the dashboard. 
If you need cluster linkage function, it will need more in-depth discussion.

**Comment by hyt05** [comment]
@gxthrj You fully described my idea, hope it can be realized as soon as possible, it will be easier to operate and maintain。

**Comment by juzhiyuan** [comment]
duplicate with #648
