### ISSUE TITLE
ci: Error:     printer.go:54: PUT http://127.0.0.1:8080/apisix/admin/routes/r1

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#907]
# Bug report

CI failed: https://github.com/apache/apisix-dashboard/runs/1470134423#step:5:87

![image](https://user-images.githubusercontent.com/6814606/100565824-6192ec00-32ff-11eb-9826-00ba1035cf35.png)

**Comment by nic-chen** [comment]
It should be unstable. watching on it.

**Comment by membphis** [comment]
Do we need to fix this issue in 2.1.1 or later?

**Comment by nic-chen** [comment]
we could fix it later.
