### ISSUE TITLE
enhance e2e test for upstream

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#908]
here is the detail list:
 - [ ] key: remote_addr, query_string, arg_xxx
 - [ ] hash_on: consumer, header, cookie

**Comment by nic-chen** [comment]
@idbeta

**Comment by membphis** [comment]
we can only implement some important feature in `2.1.1`

**Comment by idbeta** [comment]
Hi, please assign it to me.

**Comment by nic-chen** [comment]
updated.

**Comment by idbeta** [comment]
@nic-chen I submitted 3 PRs to solve this issue, #897 #932 #936 , and some cases todo: `hash_on: vars, health check: basic config`.

**Comment by nic-chen** [comment]
close according PRs merged.
