### ISSUE TITLE
feat(e2e): display more meaningful information when running E2E test cases fail

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#911]
Here is the current output:

![image](https://user-images.githubusercontent.com/6814606/100574819-ca855e80-3315-11eb-9e05-ca6d1b2d65bb.png)

Need to show `caseDesc` field. 
Without it, we would not be able to quickly confirm which test case caused the failure.

It would be better if the original test case line number could be displayed.

**Comment by membphis** [comment]
@nic-chen Do you have anything to add?

**Comment by nic-chen** [comment]
I think showing `caseDesc` is OK for us
