### ISSUE TITLE
chore: use `Desc` to replace of `caseDesc`

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#912]
![image](https://user-images.githubusercontent.com/6814606/100576857-e854c280-3319-11eb-9fd4-495bc5ad8e2e.png)

keep one name style, same as others.

**Comment by starsz** [comment]
Hi, @juzhiyuan. I checked it, and I think it was fixed.

See line 166.

https://github.com/apache/apisix-dashboard/blob/40d8f97de8770187599ff5963617049603020e92/api/test/e2e/base.go#L165-L181
