### ISSUE TITLE
bug: 修改upstream权重为0熔断后，修改rout会出现问题

### ISSUE THREAD

**Issue by NetRainn** [apache/apisix-dashboard#920]
### 修改upstream
![image](https://user-images.githubusercontent.com/35440615/100592114-a2a3f400-3331-11eb-949e-4b6002ca2b4a.png)
### 修改rout
![image](https://user-images.githubusercontent.com/35440615/100592237-ccf5b180-3331-11eb-803a-59ff6942e598.png)

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/100596500-31ffd600-3337-11eb-8b6c-319c478ded40.png)

Backend should not omit any fields from the user's input

**Comment by membphis** [comment]
need @nic-chen confirm. we fixed one bug about the `weight` equal to `0`

**Comment by nic-chen** [comment]
yes, we had fixed it in this PR #847 

@NetRainn  please take a try with the master branch. Thanks.

**Comment by NetRainn** [comment]
ok,I use version 2.0,i will use the latest


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix-dashboard"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 晚上6:23
收件人:&nbsp;"apache/apisix-dashboard"<apisix-dashboard@noreply.github.com&gt;;
抄送:&nbsp;"三年"<1084194568@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/apisix-dashboard] bug: 修改upstream权重为0熔断后，修改rout会出现问题 (#920)





 
yes, we had fixed it in this PR #847
 
@NetRainn  please take a try with the master branch. Thanks.

**Comment by juzhiyuan** [comment]
@membphis @nic-chen the snapshot is taken from http://139.217.190.60/ here.
