### ISSUE TITLE
test: E2E test case unstable

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#922]
https://github.com/apache/apisix-dashboard/runs/1474065168#step:5:91

![image](https://user-images.githubusercontent.com/6814606/100618235-849cba80-3356-11eb-88a1-c1d15df15577.png)

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/103138304-0f7d9480-470c-11eb-834e-c02813c86343.png)

FYI: @starsz is working on this issue.

**Comment by starsz** [comment]
Yes. Please assign it to me.
