### ISSUE TITLE
feat: allow consumer bind with two more auth plugins

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#935]
# Feature request

the related issue of APISIX: https://github.com/apache/apisix/issues/2850#issuecomment-733655243

both Manager-API and Dashboard need to update.

**Comment by juzhiyuan** [comment]
The frontend doesn't limit this action.

**Comment by juzhiyuan** [comment]
@nic-chen Does the manager-api support this?

**Comment by nic-chen** [comment]
Manager API doesn't limit too.
