### ISSUE TITLE
panic: dial udp 8.8.8.8:80: connect: network is unreachable

### ISSUE THREAD

**Issue by lin2627** [apache/apisix-dashboard#938]
./manager-api   内网不能联外网，启动提示connect: network is unreachable
panic: dial udp 8.8.8.8:80: connect: network is unreachable
goroutine 1 [running]:
github.com/apisix/manager-api/internal/utils.GetOutboundIP(0x0, 0x0, 0x0)
	/root/apisix-dashboard/api/internal/utils/utils.go:61 +0x133
github.com/apisix/manager-api/internal/utils.init.0.func1(0x0, 0xecb95ae00, 0x0)
	/root/apisix-dashboard/api/internal/utils/utils.go:41 +0x2b
github.com/sony/sonyflake.NewSonyflake(0x0, 0x0, 0x0, 0xc0000e5eb0, 0x0, 0x3)
	/root/go/pkg/mod/github.com/sony/sonyflake@v1.0.0/sonyflake.go:75 +0x14a
github.com/apisix/manager-api/internal/utils.init.0()
	/root/apisix-dashboard/api/internal/utils/utils.go:39 +0xb4

**Comment by membphis** [comment]
@gxthrj I think we should allow the user to set the DNS resolver via `conf/config.yaml`

**Comment by gxthrj** [comment]
We use snowflake do not have to rely on external networks，we'd better to  remove the network dependency .

**Comment by membphis** [comment]
> @gxthrj @nic-chen I think we should allow the user to set the DNS resolver via `conf/config.yaml`

ignore what I said. ^_^

**Comment by membphis** [comment]
@lin2627 you can make a try with the latest master branch. please feel free to reopen this issue if you still have this issue
