### ISSUE TITLE
The view for create a route is missing publish and offline button?

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#939]
# Bug report

## Screenshots
![image](https://user-images.githubusercontent.com/12752710/100742664-1fa89980-3416-11eb-892f-ccb47219e1dc.png)

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows] CentOS Linux release 7.9.2009 (Core)
- Browser (if applies) [e.g. Chrome, Safari, Edge] Chrome 78
- Version: [e.g. 2.0-rc3] 2.1

## Additional context
When i create a route, I found that there are no buttons for online and offline functions on the interface, So I'm not sure if there is a problem with the deployment? Or is this part of the function removed in the new version of the dashboard?

![image](https://user-images.githubusercontent.com/12752710/100743183-ecb2d580-3416-11eb-9136-e6ef89a49a47.png)
I deployed the dashboard 1.5 version, there are these buttons

**Comment by nic-chen** [comment]
Yes, we temporarily removed this feature and will reimplement it later.

**Comment by Caelebs** [comment]
When will these feature be re-implemented in the future and probably in which version?
@nic-chen

**Comment by juzhiyuan** [comment]
Just added today morning, please use the latest codes in the master branch.
