### ISSUE TITLE
test: need to do custom check for plugins

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#941]
Some plugins directly use special codes to verify parameters instead of JSONSchema verification. We need to use JSONSchema verification in APISIX instead, so that neither the FE nor the `Manager API` need to be modified, and subsequent maintenance is more convenient.

Example:
https://github.com/apache/apisix/blob/master/apisix/plugins/jwt-auth.lua#L109-L124

here is the list:

- [ ] jwt-auth
- [ ] cors
- [ ] ip-restriction
- [ ] openid-connect
- [ ] proxy-cache (need to read `conf/config.yaml` in APISIX to check cache zone )
- [ ] proxy-rewrite
- [ ] redirect
- [ ] request-validation
- [ ] response-rewrite
- [ ] uri-blocker (regular expression in Lua and `ngx.re`)

Dashboard need to do is make E2E test to confirm it works  well after APISIX update.

related issue: #856

**Comment by membphis** [comment]
@nic-chen is this a bug? I think this issue should be `test`

**Comment by nic-chen** [comment]
> @nic-chen is this a bug? I think this issue should be `test`

sure.
we need to fix `jwt-auth` first, the others could be later.

**Comment by idbeta** [comment]
I don’t quite understand your issue, can you provide a more detailed explanation? @nic-chen

**Comment by nic-chen** [comment]
fixing in APISIX: https://github.com/apache/apisix/pull/3021
