### ISSUE TITLE
Improve CI & CD order

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#943]
# Feature request

Only all CI are passed, the CD would be triggered.

## Describe the solution you'd like

Need @nic-chen's check.

## Describe alternatives you've considered

Or it's strange to see CI failed but CD successfully.

## Additional context

None

**Comment by juzhiyuan** [comment]
If yes, kindly close this issue, just to make sure.

**Comment by membphis** [comment]
ping  @nic-chen @gxthrj

**Comment by gxthrj** [comment]
Got it, will check it this week.
