### ISSUE TITLE
Improve the Bug Report issue template

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#944]
# Feature request

Once the info page is added, users could provide more information easily. 

## Describe the solution you'd like

Update the issue template.

## Describe alternatives you've considered

None

## Additional context

related issue or PR

#853 
#850

**Comment by stu01509** [comment]
Can I pick this issue? btw I think maybe we can standardize all of APISIX's repo issue templates? It may help the user easily to submit the issue.

**Comment by juzhiyuan** [comment]
Ya, we should standardized all repos :) welcome to send PR for one repo first.

**Comment by stu01509** [comment]
Hi @nic-chen and @juzhiyuan 

I adjust the ISSUE template, What do you think this?

```markdown
## Issue description
<!-- A clear and concise description of what the issue is. -->
    
## Expected behavior
<!-- A clear and concise description of what you expected to happen. -->

## How to Reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Screenshots
<!-- Add screenshots to help explain your problem if applicable. -->

## Environment
* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

## Additional context
<!-- Do you want to solve this issue? or add any other context about the problem here. -->

```

**Comment by nic-chen** [comment]
> Hi @nic-chen and @juzhiyuan
> 
> I adjust the ISSUE template, What do you think this?
> 
> ```gfm
> ## Issue description
> 
>     
> ## Expected behavior
> 
> 
> ## How to Reproduce
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> ## Screenshots
> 
> 
> ## Environment
> * apisix version (cmd: `apisix version`):
> * OS (cmd: `uname -a`):
> * OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
> * etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
> * apisix-dashboard version, if have:
> * Browser version, if have:
> 
> ## Additional context
> 
> ```

I think you could submit a PR directly, and we could review to give suggestions.
