### ISSUE TITLE
bug: JSON schema verification should be performed on the original data submitted by the user

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#955]
# Bug report

## Describe the bug

JSON schema verification should be performed on the original data submitted by the user, not the data after binding structures

The usual practice in Go is to bind the request body to a structure for subsequent processing of the request body. 

This will cause a problem, that is, if there is no corresponding value in the request body for the fields defined in the structure, 
the bound object will automatically be assigned a value of zero. 

At this time, there may be problems with json schema verification.

**Comment by moonming** [comment]
Don't understand what the bug is.
@nic-chen please add more details

**Comment by nic-chen** [comment]
> Don't understand what the bug is.
> @nic-chen please add more details

updated
