### ISSUE TITLE
feat: upstream support set `pass_host` parameter

### ISSUE THREAD

**Issue by yangxikun** [apache/apisix-dashboard#962]
# Feature request

## Please describe your feature

When create upstream on apisix-dashboard, we need to set https://github.com/yangxikun/apisix/blob/master/doc/admin-api.md#upstream `pass_host` parameter.

**Comment by gy09535** [comment]
I think it is a good feature, now the pass_host value is always "pass", when we set the upstream node with domain , it can not set the host to the upstream, It is a problem.

**Comment by juzhiyuan** [comment]
Just to make sure, if the manager-api supports this feature?

cc @nic-chen

**Comment by nic-chen** [comment]
> Just to make sure, if the manager-api supports this feature?
> 
> cc @nic-chen

yes, it has supported.
