### ISSUE TITLE
bug: the FAQ.md lacks a description about enabling custom plugin

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#963]
# Bug report

## Describe the bug

The FAQ.md lacks a description about enabling custom plugin: after `manually copy api/conf/schema.json to the conf directory`, **the manager-api needs to be restarted.**

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/blob/master/docs/FAQ.md#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard
