### ISSUE TITLE
bug: Modify proxy_rewrite plugin in dashboard,unable to save it

### ISSUE THREAD

**Issue by chenyicai** [apache/apisix-dashboard#965]
### Issue description
When i modify proxy_rewrite plugin in dashboard, i can not save it
Fill in the configuration, click the confirm button, there is no response

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: centos 7

**Comment by juzhiyuan** [comment]
Will be resolved in 2.2 in 8 days.

**Comment by membphis** [comment]
you can make a try with 2.1.1 branch

**Comment by juzhiyuan** [comment]
> you can make a try with 2.1.1 branch

🤔 this is a bug from plugin form, will be resolved by using code mirror.

**Comment by chenyicai** [comment]
When I upgraded to version 2.1.1, my problem was solved，thank you very much!
