### ISSUE TITLE
feat: collect code coverage for backend e2e test

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix-dashboard#966]
We have added a lot of [e2e test cases](https://github.com/apache/apisix-dashboard/tree/master/api/test/e2e) to the Manager API, but there is currently no way to collect the code coverage of the Manager API by the e2e tests.

We currently start ETCD, APISIX, Manager API through [docker-compose,](https://github.com/apache/apisix-dashboard/blob/master/api/test/docker/docker-compose.yaml) and then test through http request.

If necessary, this part can also be adjusted accordingly.

Thanks.

**Comment by juzhiyuan** [comment]
done?

**Comment by nic-chen** [comment]
duplicate with #1033
