### ISSUE TITLE
show a message: "not support Service object now" when user uses `Service` object

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#968]
If the user uses a feature that is not yet supported by Dashboard, a friendly prompt will be returned to tell him/her that it is not yet supported.

![image](https://user-images.githubusercontent.com/6814606/101239632-0cead900-3724-11eb-9f13-f6c5bf545342.png)

**Comment by juzhiyuan** [comment]
How to check that feature doesn't support yet?

e.g check if the data has service id or service object.

**Comment by membphis** [comment]
contains `service_id` in `route`, here is an example:

https://github.com/apache/apisix/blob/2ba28ff6a7a1823c3ea37e2cdcd7427d4244f3d9/t/node/merge-route.t#L82

here is the doc link:

https://github.com/apache/apisix/blob/master/doc/admin-api.md#route

![image](https://user-images.githubusercontent.com/6814606/101281676-595d1400-380b-11eb-9e70-32d5e46443ba.png)

**Comment by juzhiyuan** [comment]
will be resolved in #471
