### ISSUE TITLE
docs: API document about `Manager-API`

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#973]
The API interfaces of Manager API and Admin API are mostly the same.

However, the Manager API actually adds some new APIs, such as the search interface for Dashboard.

We need a separate documentation page to list the API interfaces that the Manager API implements separately.

**Comment by membphis** [comment]
@nic-chen Do you have time to check this issue?

**Comment by nic-chen** [comment]
@membphis  
Here is the list:

|Method      |Request URI|Request Body|Description        |
|---------|-------------------------|--|------|
|GET      |/apisix/admin/routes?page=&page_size=&name=&uri=|NULL|Fetch route list|
|GET      |/apisix/admin/routes/{id}|NULL|Fetch route|
|PUT      |/apisix/admin/routes/{id}|{...}|Create route by ID|
|POST     |/apisix/admin/routes     |{...}|Create route, and ID is generated by server|
|DELETE   |/apisix/admin/routes/{id}|NULL|Remove route|
|GET      |/apisix/admin/notexist/routes?name=&exclude=|NULL|Check route exists by name|
|GET      |/apisix/admin/services?page=&page_size=&name=|NULL|Fetch service list|
|GET      |/apisix/admin/services/{id}|NULL|Fetch service|
|PUT      |/apisix/admin/services/{id}|{...}|Create service by ID|
|POST     |/apisix/admin/services     |{...}|Create service, and ID is generated by server|
|DELETE   |/apisix/admin/services/{id}|NULL|Remove service|
|GET      |/apisix/admin/upstreams?page=&page_size=&name=|NULL|Fetch upstream list|
|GET      |/apisix/admin/upstreams/{id}|NULL|Fetch upstream|
|PUT      |/apisix/admin/upstreams/{id}|{...}|Create upstream by ID|
|POST     |/apisix/admin/upstreams     |{...}|Create upstream, and ID is generated by server|
|DELETE   |/apisix/admin/upstreams/{id}|NULL|Remove upstream|
|GET      |/apisix/admin/ssl?page=&page_size=&sni=|NULL|Fetch SSL list|
|GET      |/apisix/admin/ssl/{id}|NULL|Fetch SSL|
|PUT      |/apisix/admin/ssl/{id}|{...}|Create SSL by ID|
|POST     |/apisix/admin/ssl     |{...}|Create SSL, and ID is generated by server|
|DELETE   |/apisix/admin/ssl/{id}|NULL|Remove SSL|
|POST     |/apisix/admin/check_ssl_cert     |{"cert": "xx", "key":"xx"}|verify SSL cert and key|
|POST     |/apisix/admin/check_ssl_exists     |["a.com", "b.com"]|check SSL exists or not by sni|
|GET      |/apisix/admin/consumers?page=&page_size=&username=|NULL|Fetch consumer list|
|GET      |/apisix/admin/consumers/{username}|NULL|Fetch consumer|
|PUT      |/apisix/admin/consumers|{...}|Create consumer by username|
|DELETE   |/apisix/admin/consumers/{username}|NULL|Remove consumer|
|GET      |/apisix/admin/plugins|NULL|Fetch plugin list|
|GET      |/apisix/admin/schema/plugins/{name}|NULL|Fetch Plugin schema|
|POST   |/apisix/admin/user/login|{"username":"xx", "password":"xx"}|User login|

**Comment by moonming** [comment]
we need swagger to manager those APIs

**Comment by membphis** [comment]
@nic-chen we do not need a full API list. only need some new API different from Admin API.

**Comment by nic-chen** [comment]
> we need swagger to manager those APIs

OK, It's a better way for api doc.

**Comment by nic-chen** [comment]
> @nic-chen we do not need a full API list. only need some new API different from Admin API.

updated. I will submit the first PR about api doc with those APIs.

**Comment by membphis** [comment]
I confirm some detail.

eg, the API `/apisix/admin/routes?page=&page_size=&name=&uri=`

The API doc should focus on the new argument: `page`, `page_size`, `name` and `uri`. 

@nic-chen all right?

**Comment by nic-chen** [comment]
> I confirm some detail.
> 
> 
> 
> eg, the API `/apisix/admin/routes?page=&page_size=&name=&uri=`
> 
> 
> 
> The API doc should focus on the new argument: `page`, `page_size`, `name` and `uri`. 
> 
> 
> 
> @nic-chen all right?

OK
