### ISSUE TITLE
request help: import k8s_deployment_info to upstream cann't use it

### ISSUE THREAD

**Issue by ryianyang** [apache/apisix-dashboard#974]
### Issue description
how to set apisix upstream config with k8s_deployment_info, I have import the k8s_deployment_info to upstream,but the upstream dashboard cann't display，also use k8s_deployment config the routes.

### Environment
kubernetes 1.15

* apisix version (cmd: `apisix version`):2.1
* OS: centos 7.8

> I am not quite understand what you mean, but from `the upstream dashboard cann't display` it looks like a dashboard problem?

I use postman input the k8s_deployment_info to set the upstream, it's return add it success, but when I check this upstream 
record from the apisix dashbard, some items display null

**Comment by juzhiyuan** [comment]
Has the manager api supported that field?

cc @nic-chen

**Comment by nic-chen** [comment]
> Has the manager api supported that field?
> 
> cc @nic-chen

sure, it has supported.

**Comment by juzhiyuan** [comment]
Please take a look at this issue 💯 

cc @membphis

**Comment by juzhiyuan** [comment]
ping @membphis

**Comment by juzhiyuan** [comment]
related discussion: https://github.com/apache/apisix/issues/3068
