### ISSUE TITLE
test: add frontend e2e test for create route

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-dashboard#975]
use the current test framework to write web E2E tests:

- [ ] create a route according to the default steps

       1. input route `Name`
       2. input route `Path`
       next
       3. input upstream `Node ip`
       next
       4. click submit
       5. confirm page return

- [ ] verify the route
       check on the `/routes/list` page
- [ ] delete the route

**Comment by moonming** [comment]
What is "web test"?

Please use technical terms

**Comment by guoqqqi** [comment]
HI~, We already have a test related to the issue, I can propose a new PR to update its specification ~
![image](https://user-images.githubusercontent.com/72343596/106780490-0379e080-6683-11eb-9703-4307eadd8718.png)

**Comment by juzhiyuan** [comment]
great!
