### ISSUE TITLE
not found the error code list doc

### ISSUE THREAD

**Issue by NetRainn** [apache/apisix-dashboard#987]
麻烦请问下整理的错误文档在哪里？找了会儿没有找到...

**Comment by nic-chen** [comment]
@NetRainn 
here is an example(but not used), please have a look:
https://github.com/apache/apisix-dashboard/blob/master/api/internal/utils/consts/error.go

**Comment by membphis** [comment]
@NetRainn please use English in public channel

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/apisix-dashboard/issues/758
