### ISSUE TITLE
feat: Add a new API to get plugin information

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-dashboard#990]
# Feature request

We have already discuss about this feature in the [mail list](https://lists.apache.org/thread.html/r33b8d142ba57cfda467b4912ec94d5ae9c77b1eec4982f39f2e6bf0e%40%3Cdev.apisix.apache.org%3E), and it will be Implemented in M2.3

- Dependent conditions:  a command-line tool used to synchronize the data from APISIX. [discussed link](https://lists.apache.org/thread.html/r33b8d142ba57cfda467b4912ec94d5ae9c77b1eec4982f39f2e6bf0e%40%3Cdev.apisix.apache.org%3E)

- related issues: https://github.com/apache/apisix-dashboard/issues/529

**Comment by juzhiyuan** [comment]
Any update about that command line?

**Comment by membphis** [comment]
@liuxiran we can use this feature to export the JSON schema: https://github.com/apache/apisix/pull/3092
if you need any help, please let us know

**Comment by juzhiyuan** [comment]
FYI This issue would be resolved once `plugins?all=true` is supported.
