### ISSUE TITLE
Dashboard function does not seem to be perfect.

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#995]
# Bug report

[Global Rule](https://github.com/apache/apisix/blob/master/doc/architecture-design.md#Global-Rule)
#### Plugin just can be binded to Service or Route, if we want a Plugin work on all requests, how to do it? We can register a global Plugin with GlobalRule

A global plugin can be registered as described in the document, but in the dashboard, I did not find how to register a global plugin, It looks like this feature is not found in the dashboard, Can these rules be created only through `admin api` at present? 

And also in this document, It mentions a `service` concept, but in the dashboard, I can't find how to create a `service`

[Service](https://github.com/apache/apisix/blob/master/doc/architecture-design.md#service)
## System information
- OS: [e.g. macOS, Windows] `CentOS Linux release 7.4.1708 (Core)`
- Browser (if applies) [e.g. Chrome, Safari, Edge] `Chrome/78.0.3904.108`
- Version: [e.g. 2.0-rc3] `apisix-dashboard:v2.1.1` & `apisix v2.1`

**Comment by juzhiyuan** [comment]
duplicate with https://github.com/apache/apisix-dashboard/issues/820 https://github.com/apache/apisix-dashboard/issues/471
