### ISSUE TITLE
only enable cors plugin will take empty object

### ISSUE THREAD

**Issue by souzens** [apache/apisix-dashboard#996]
# Bug report

## Describe the bug

in plugin step , if I only enable cors plugin but not to click on SETTINGS button and click on ”确认"

Finally,  it seems the data of cors object is empty by reading etcd.

My idea is that there should be a default value when only the plugin is enabled

![image](https://user-images.githubusercontent.com/35559209/101610659-83008000-3a43-11eb-9d45-5605ab651f32.png)

## System information

- OS: [e.g. macOS, Windows] centos
- Browser (if applies) [e.g. Chrome, Safari, Edge] Chrome
- Version: [e.g. 2.0-rc3]  2.0-2.11

**Comment by juzhiyuan** [comment]
will be resolved with https://github.com/apache/apisix-dashboard/pull/898

**Comment by juzhiyuan** [comment]
doc https://github.com/apache/apisix/blob/master/doc/plugins/cors.md
